### ISSUE TITLE
When run in parallel create new thread for each test.

### ISSUE THREAD

**Issue by astafev** [cbeust/testng#1000]
If in one of test some thread specific properties are set (for example ContextClassLoader), it can affect next runs.

Here is an example: https://github.com/astafev/testng-methods-order
Test1 set ContextClassLoader in @BeforeClass and restores it in @AfterClass. Because of #261 Test2 is executed between those calls.

My idea is to create new thread for each new test. Not sure how it can be done with one thread like in the project above without fixing #261, but with big project and multiple threads it could be really useful.

**Comment by juherr** [comment]
Did you try [`group-by-instances`](http://testng.org/doc/documentation-main.html#dependent-methods) and/or [parallel](http://testng.org/doc/documentation-main.html#parallel-running) features?

**Comment by krmahadevan** [comment]
Closing this issue since `group-by-instances` when applied to the `testng.xml` in the above mentioned project, runs all tests and no errors are seen.
