### ISSUE TITLE
SkipException doesn't work with PowerMock 

### ISSUE THREAD

**Issue by thekingnothing** [cbeust/testng#1003]
In case if PowerMock is used, then `SkipException`doesn't work and test is marked as failed instead skipped. 

> org.testng.SkipException: Skipp test
> 
> 	at samples.testng.FinalTest.mockingFinalClassesAndMethodsWorkWithTestNGAndEasyMock(FinalTest.java:29)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:782)
> 	at org.testng.TestRunner.run(TestRunner.java:632)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
> 	at org.testng.TestNG.run(TestNG.java:1064)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The root clause in this method: 

```
private boolean isSkipExceptionAndSkip(Throwable ite) {
    return SkipException.class.isAssignableFrom(ite.getClass()) && ((SkipException) ite).isSkip();
  }
```

PowerMock uses a new class loader per test, so `Throwable its` is loaded with other class loader than `org.testng.internal.Invoker` and `SkipException.class.isAssignableFrom(ite.getClass())`always false in this case. 

Further `((SkipException) ite)` will cause ClassCastException. 

So need some other way to check if `ite` is a instance of `SkipException`. Do you have any thoughts?

**Comment by juherr** [comment]
In your sample, I've just replaced 
```java
this.delegate = new URLClassLoader(new URL[]{currentClassLoader.getResource("")}, null);
```
by
```java
this.delegate = new URLClassLoader(new URL[]{currentClassLoader.getResource("")}, currentClassLoader);
```
and the test is working well then.
Why not specifying a classloader parent?

**Comment by thekingnothing** [comment]
I did it, to emulate PowerMock case, where fully new class loader is used to create a class instance and run test.  PowerMock modifies classes for test during loading. So we need to be sure that no one class is loaded without modifying in case if the class have to be modified. The goal could be achieved only by using a new class loader and reloading all class if they has already been loaded during test initialisation.

**Comment by juherr** [comment]
You should have a look at https://github.com/raphw/byte-buddy/issues/54

**Comment by thekingnothing** [comment]
Thanks, I fixed it in PowerMock.

**Comment by juherr** [comment]
:+1:
