### ISSUE TITLE
Add @Factory to TestNG dynamically

### ISSUE THREAD

**Issue by jpaugh** [cbeust/testng#1004]
Is it possible to add a test factory to an instance of `TestNG` using Java code? There doesn't appear to be a mechanism for it, aside from generating a once-off xml file.

**Comment by skirkpatrick** [comment]
You should be able to add test factories the same way you add test classes, i.e. [`TestNG.setTestClasses(Class[])`](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L496).

**Comment by juherr** [comment]
:+1: It may work

**Comment by jpaugh** [comment]
It turns out that calling `setTestCLasses` *does* work. It is able to pull in both the test instances returned by the `Factory` and the test methods on that instance; looks like this was a wild goose chase, after all: my real problem was that I neglected the `@Test` annotation.
