### ISSUE TITLE
Groups at class level

### ISSUE THREAD

**Issue by badrinyn** [cbeust/testng#1005]
While Defining groups at class level, i see if the class name starting with Test or ending with Test is only picked when executing via maven using groups. Is it a naming convention which we need follow while defining the class name if we are executing using groups?

```java
@Test(groups="RegressionTest")
public class TestGroups{
  @Test
  public void testAddUser(){
  }
}
```

Executing via `mvn clean test -Dgroups="RegressionTest"`

if I change the class name to just Groups by removing Test,  the above test case did not run.

**Comment by juherr** [comment]
You have to configure surefire which has a naming convention by default.

> A list of <include> elements specifying the tests (by pattern) that should be included in testing. When > not specified and when the test parameter is not specified, the default includes will be 
> ```xml
> <includes>
>  <include>**/Test*.java</include>
>  <include>**/*Test.java</include>
>  <include>**/*TestCase.java</include>
> </includes>
> ```

https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes
