### ISSUE TITLE
What's the difference between run() and runSuitesLocally() in the TestNG object.

### ISSUE THREAD

**Issue by schreibermm** [cbeust/testng#1006]
Hi the TestNG object has 2 methods: run() and runSuitesLocally().
What is exactly the difference between the 2 methods?

I could not find any info in the documentation.
If there is a description, please send me a link.

Thanks.

**Comment by juherr** [comment]
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L1127-L1131

> This needs to be public for maven2

You are not supposed to use `runSuitesLocally()`
