### ISSUE TITLE
Order of method execution specified in IMethodInterceptor is not getting followed.

### ISSUE THREAD

**Issue by raynaya** [cbeust/testng#1008]
The list returned by IMethodInterceptor is not followed while executing. The problem starts in the method   `private ITestNGMethod[] intercept(ITestNGMethod[] methods) `, in the last line it tries to form an array from the list it receives and the order is incorrect in the array it returns.

**Comment by juherr** [comment]
@raynaya Why did you close it? Is it working as expected?

**Comment by raynaya** [comment]
It is working but not as i was expecting it to. The thing is if we set preserve order to true then it doesn't follow the order you specify in method interceptor.  I was expecting method interceptor to override all other settings in xml. Though that can be debatable.

**Comment by raynaya** [comment]
@juherr It is working but not as i was expecting it to. The thing is if we set preserve order to true then it doesn't follow the order you specify in method interceptor.  I was expecting method interceptor to override all other settings in xml. Though that can be debatable.
