### ISSUE TITLE
xmlpathinjar reports wrong xml file in use

### ISSUE THREAD

**Issue by dodtsair** [cbeust/testng#101]
$ java  org.testng.TestNG -testjar Tests-0.0.1-SNAPSHOT-tests.jar -xmlpathinjar Config/AllGroups.xml
[TestNG] Running:
 ...\tests\lib\testng.xml

vs

$ java  org.testng.TestNG -testjar Tests-0.0.1-SNAPSHOT-tests.jar -xmlpathinjar Config/NOFILEFOUND.xml
[TestNG] Couldn't find a testng.xml in the jar file, running all the classes

Looks like a display bug to me

My current working directory was  ...\tests\lib\

**Comment by juherr** [comment]
Fixed by 9c2a9f1
