### ISSUE TITLE
RetryFailed mechanism does not run properly

### ISSUE THREAD

**Issue by matzinger0670** [cbeust/testng#1011]
We run our test with dataProvider. Every method run with different test parameter. 
From time to time, the Selenuim WebDriver get an TimeOut for page load. In these cases we want to rerun the testcase.
Therefor we have annotated an RetryAnalyzer at these methods. 
Every testCase which got an TimeOut exception from WebDriver  should rerun the one time again.

For the first testCase failed looks everything fine. The case failed because method got the TimeOut exception. The rerun after, works fine and the testCase return with success.
A second testCase failed with TimeOut exception and start the rerun. The rerun works fine again and the testCase return with succes too. But then, the rerun starts a second time with same parameters. This seems like a bug in Invoker class. The instances saved in the FailureContext never removed after testCase is done, but it should.
The loop in this part of the code run through the saved instances of retryFailed.

Invoker.java - line 1142

``` java
           if (failure.instances.isEmpty()) {
                       result.addAll(tmpResults);
            } else {
                  for (Object failedInstance : failure.instances) {
                    List<ITestResult> retryResults = Lists.newArrayList();
                    failure.count = retryFailed(
                            failedInstance, testMethod, suite, testClass, beforeMethods,
                     afterMethods, groupMethods, retryResults,
                     failure.count, expectedExceptionHolder,
                     testContext, parameters, parametersIndex);
                  result.addAll(retryResults);
                  }
              }
```

The Failed Instances add to FailureContext at line 1363.

**Comment by juherr** [comment]
It looks like you've already made the analyze.

Why not proposing a pull-request with a test case and the appropriate fix? :)

**Comment by matzinger0670** [comment]
yes, I want to do it.
First of all I have to test it locally.

What I`m missing is the remote package for using testNG in Eclipse.
Do you know something about it.

**Comment by juherr** [comment]
TestNG remote moved here: https://github.com/testng-team/testng-remote
But I don't understand why you need it because you should be able to write an unit test without it.

**Comment by matzinger0670** [comment]
Yes you are right.
Thanks.
