### ISSUE TITLE
Reporter.log is ignored in skipped test listener

### ISSUE THREAD

**Issue by skirkpatrick** [cbeust/testng#1017]
Calling `Reporter.log` in a skipped test listener (`ITestListener.onTestSkipped(ITestResult)`) results in the message being orphaned. Most of the time this manifests as the message being lost completely, though if the user logs messages in listeners for subsequent failed or successful tests on the same thread then the message will become associated with those tests.

I've written a unit test that demonstrates this issue on my fork: https://github.com/skirkpatrick/testng/blob/skip-listener-reporter/src/test/java/test/reports/ReporterLogTest.java#L27

Uncommenting the print statements in the test linked to above will give the output:

    [foo, foo, Log from test_onFailure, Listener: onTestFailure]
    [foo, foo, Log from test_onFailure, Listener: onTestFailure]
    [foo, foo, Log from test_onFailure, Listener: onTestFailure, Listener: onTestSkipped, Log from test_onSuccess, Listener: onTestSuccess]
whereas the expected output is:

    [foo, foo, Log from test_onFailure, Listener: onTestFailure]
    [foo, foo, Log from test_onFailure, Listener: onTestFailure, Listener: onTestSkipped]
    [foo, foo, Log from test_onFailure, Listener: onTestFailure, Listener: onTestSkipped, Log from test_onSuccess, Listener: onTestSuccess]

**Comment by juherr** [comment]
:+1: Do you know why the issue appears?

**Comment by skirkpatrick** [comment]
The bug is in [`Invoker#invokeMethod`](https://github.com/cbeust/testng/blob/285cf3d9825eb4ed6f05a35c1626c989e5aece96/src/main/java/org/testng/internal/Invoker.java#L566). `Reporter.setCurrentTestResult` is only being called if the configuration methods pass. I'm pretty sure the fix is to call it in the `else` block on [line 655](https://github.com/cbeust/testng/blob/285cf3d9825eb4ed6f05a35c1626c989e5aece96/src/main/java/org/testng/internal/Invoker.java#L655). If that sounds right to you, I can submit a fix with my unit tests.

**Comment by skirkpatrick** [comment]
Another possibility is setting the current test result earlier in `invokeMethod`, but I'm not familiar enough with the code/history to know if there's a reason it is being called within that `if` block.

**Comment by adamjson** [comment]
I believe this may explain the problem we are seeing with our (home brew) ScreenshotListener class logging the incorrect screenshot when we are using a Factory + DataProvider to spin up our tests. Our home brew ScreenshotListener class is similar to the one at com.thoughtworks.selenium.ScreenshotListener, however we are not explicitly calling Reporter.setCurrentTestResult(result); at the beginning of the onTestFailure method, and then Reporter.setCurrentTestResult(null); at the end. Are we not using the TestNG reporter correctly by not explicitly calling setCurrentTestResult in our onTestFailure / onConfigurationFailure methods, or does our problem sound related to the issue described in this ticket?

Thanks!

**Comment by skirkpatrick** [comment]
That's the same issue described here. I assume it is a TestNG bug because the behavior of the listeners differs depending on the test result in an unexpected, unrelated way, and because this used to work (this is a regression, my team is looking into upgrading from 6.8.7 and Reporter logging works fine in that version).

6.9.11 was just released, so assuming my fix gets merged it won't be available until 6.9.12 which could be several months away. Unless you plan on hosting your own 6.9.12-SNAPSHOT jar, I'd recommend calling `setCurrentTestResult` explicitly as a workaround for now, which is what I plan to do.

**Comment by adamjson** [comment]
Thanks for the feedback. We are running 6.9.9, so this all makes sense. I'm also using the setCurrentTestResult workaround for now.

**Comment by skirkpatrick** [comment]
Looking into this issue further, it seems that it was introduced by c9a91722631f3b2f9bcc5a300e7a84c61cd4764f and 38542477be2810926b6187f7f42159929a6e8588. Before this, the output was getting associated with the `null` test result, so it would show up in the full log but wouldn't actually be associated with the skipped test itself, but now output mapping is based on the TestResult hash code so a `null` test result will cause output to be orphaned and not even appear in the full log.

The fix I submitted in #1019 will have the side-effect that the output will now be associated with the skipped test, which is different behavior from before. To me, this seems like the intended behavior, but I assume @juherr will appreciate being made aware of this side-effect.
