### ISSUE TITLE
Guice module reinitialization for a test class

### ISSUE THREAD

**Issue by atais** [cbeust/testng#1027]
Hello.

I have long enjoyed the ease of use of Guice and TestNG together. Lately, we have prepared couple of integration test that main requirement is to run on a freshly initialized system.

They all work fine, separately. But when run together they fail. The reason, as I understood so far, is because TestNG initializes the Guice Module once and then injects it. Since some part of our application is based on in-memory caches that depend on Guice, they remain through the tests and therefore - the tests fail.

Is there any way I could reset the guice module, force it to reinitialize or something like that? 
For the moment I run the test with IntellJ and our project is based on Maven.

**Comment by juherr** [comment]
Hi,

I don't know why you closed the issue but I can try to answer your question.

In fact, the build-in support of Guice may have some limitations depending on what you have to do.
If you have specific needs like I suppose according to your message, I advice you to manage the guice injection by yourself.
You have many possibilities to do that:

* Before/after methods
* [listeners](http://testng.org/doc/documentation-main.html#testng-listeners)
* ITestObjectFactory

**Comment by atais** [comment]
I closed the issue because actually it was more of my fault then TestNG, however as you say - I ended up managing the Guice on my own.
