### ISSUE TITLE
Issue with getting XmlTest from test method 

### ISSUE THREAD

**Issue by RocketRaccoon** [cbeust/testng#1029]
HI,

Please found following [issue](http://stackoverflow.com/questions/36689568/testng-parallel-execution-behavior-doesnt-match-the-expected-one/36770699#36770699). There is an issue with getting XmlTest from InvokedMethod in case when test are running in parallel (for single run it works correctly). So there is `@Test(invocationCount = 5, threadPoolSize = 5)` and `invokedMethod.getTestMethod().getXmlTest()` return null but `testResult.getTestContext().getCurrentXmlTest()` returns XmlTest correctly. It seems like a bug...

**Comment by juherr** [comment]
Thank for the report!

Why not trying to send a pull-request that will fix it? :)

**Comment by RocketRaccoon** [comment]
I'm so good developer to fix it :) but I have investigated it a little bit.
In case when `invocationCount = 1` `method.getTestMethod().getXmlTest()` returns correct value. In case when `invocationCount = 5` it returns null, but `method.getTestMethod().getTestClass().getXmlTest()` contains valid `XmlTest` object
