### ISSUE TITLE
Parameterized test class crashes when data provider returns empty array

### ISSUE THREAD

**Issue by qerub** [cbeust/testng#1030]
Let's say I have a test class with a `@Factory`-annotated constructor:

```java
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;

public class TestTest {
    @DataProvider(name = "values")
    public static Object[][] values() {
        return new Object[][]{{1}, {2}, {3}};
    }

    private final int value;

    @Factory(dataProvider = "values")
    public TestTest(int value) {
        this.value = value;
    }

    @Test
    public void test() {
        assertEquals(value, 2);
    }
}
```

This works perfectly (apart from the assertion errors this silly test throws).

However, if I change the data provider to return an empty array instead (`new Object[][]{}`), TestNG crashes:

```
org.testng.TestNGException: 
Can't invoke public void TestTest.test(): either make it static or add a no-args constructor to your class 
```

I expected the test to be ignored, just like it is when the data provider is on method-level instead of class-level. Is this the desired behaviour? If so, why? I ran into this issue because I have data providers that are supposed to be NOPs in certain test configurations.

**Comment by juherr** [comment]
How do you run the test?

**Comment by qerub** [comment]
Through Surefire and IntelliJ IDEA. The generated XML suite looks something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default Suite">
  <test name="foo">
    <classes>
      <class name="TestTest"/>
    </classes>
  </test>
</suite>
```

**Comment by juherr** [comment]
Ok, thank :)

**Comment by qerub** [comment]
@juherr: Do you agree with me that this is a bug? (Just wonder if I should find another strategy or wait for a fix.)

**Comment by juherr** [comment]
@qerub I didn't try to reproduce it but it looks like a bug for sure.
I won't have time to fix it soon. But if you are agree to try to fix it by yourself, I can help youto do it.

First step is to add a new tset case that proves the issue, then try to find where is the issue and fix it :)

**Comment by priyanshus** [comment]
@qerub Have you tried running your test programmatically? Do you still face similar issue. I tried it and it does not complain me. It looks like:

```
package test.testng1030;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;

public class TestEmptyReturnFromDataProvider {
	@DataProvider(name = "values")
	public static Object[][] values() {
		return new Object[][] {};
	}

	private int value;

	@Factory(dataProvider = "values")
    public TestEmptyReturnFromDataProvider(int value) {
        this.value = value;
    }
	@Test
	public void test() {
		assertEquals(value, 2);
	}
}
```

```
public static void main (String [] arg) {
		TestListenerAdapter tla = new TestListenerAdapter();
		TestNG testng = new TestNG();
		testng.setTestClasses(new Class[] { TestEmptyReturnFromDataProvider.class });
		testng.addListener(tla);
		testng.run();
	}
```

it does not throw any exception. Could you check it please.

**Comment by juherr** [comment]
Which version are you both using?

**Comment by priyanshus** [comment]
I have clone repo yesterday, shows 6.9.12.

**Comment by ryanlevell** [comment]
@priyanshus It looks like the test fails for the same reason programmatically if you print the exception:
```
public static void main(String[] args) {
	TestListenerAdapter tla = new TestListenerAdapter();
	TestNG testng = new TestNG();
	testng.setUseDefaultListeners(false);
	testng.setTestClasses(new Class[] { TestEmptyReturnFromDataProvider.class });
	testng.addListener(tla);
	testng.run();
	System.out.println(tla.getFailedTests().get(0).getThrowable());
}
```

Output:
```
[TestNG] Running:
  Command line suite
===============================================
Command line suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
org.testng.TestNGException: 
Can't invoke public void com.levell.test_ng_test.AppMain.test(): either make it static or add a no-args constructor to your class
```
I pulled from master today, but it says 6.9.11 in the pom. Gradle shows 6.9.12 though, is that where you found 6.9.12?

**Comment by juherr** [comment]
@ryanlevell Gradle is the official build tool, so the current master is 6.9.12(-SNAPSHOT)

**Comment by priyanshus** [comment]
@juherr What should be the intended behaviour if dataprovider returns an empty array? Should it throw an exception saying that you must have to provide values in dataprovider?

**Comment by juherr** [comment]
IMO, an empty dataprovider means "no case for the test" and should not fail (at least, not like observed). 
But a test with no case is a bit strange too. Maybe we can add it in the skipped list to notify we found a test which was not run.

What do you think @cbeust ?

**Comment by cbeust** [comment]
I'm not sure.

On one hand, I'd like to signal the user that something odd happened (empty data provider should be extremely rare) but on the other hand, marking this test SKIPPED might be a bit too strong but a simple log line might go unnoticed...

**Comment by cbeust** [comment]
Let's go for a log line, or a warning "Warning: the data provider returned an empty array so this test is not doing anything", but let's mark the test as a success.

Thoughts?

**Comment by ryanlevell** [comment]
Currently a test with an empty data provider returns 0 tests results, which seems intuitive to me, instead of marking the test as passed. I don't believe it has a log line though, which I agree should be added.

This issue only happens when combining an empty data provider with a Factory. Should it also just show 0 tests ran, or as you mentioned, make both situations show 1 test success?

**Comment by priyanshus** [comment]
@cbeust 
Without using @Factory for dataProvider test result look like this

`Total : 0 Passed: 0 Failed : 0 Skipped : 0`

Either we should fix both the cased or let it be same as without @Factory i.e. 0 result.

**Comment by priyanshus** [comment]
I tried debugging the issue but could not fix it. 

Could not find the reason of having null value for `testMthdInst.getInstance()` at 
https://github.com/cbeust/testng/blob/d0fe7c63973110e78d55880ada7cc61035140345/src/main/java/org/testng/internal/TestMethodWorker.java#L112

And that is causing the exception. In case of non empty values the `testMthdInst.getInstance()` has some value.

**Comment by ryanlevell** [comment]
@priyanshus  ```getInstance()``` is null because [```FactoryMethod#invoke```](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/FactoryMethod.java#L68) returns an empty array when the data provider is empty.

This then prevents the [loop in ```TestNGClassFinder```](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestNGClassFinder.java#L153) from adding any instances.

Since this is the only place an instance would be found in this case, we have an instance test method with no instance that can be used to call it which causes [```Utils#checkInstanceOrStatic```](https://github.com/ryanlevell/testng/blob/issue1030/src/main/java/org/testng/internal/Utils.java#L773) to throw the error.

I have [code](https://github.com/ryanlevell/testng/blob/issue1030/src/main/java/org/testng/internal/TestMethodWorker.java#L113) that fixes it, but it would also hide real user errors by preventing the error thrown by [```Utils#checkInstanceOrStatic```](https://github.com/ryanlevell/testng/blob/issue1030/src/main/java/org/testng/internal/Utils.java#L773). So I don't think it is a good solution yet.

**Comment by juherr** [comment]
> warning "Warning: the data provider returned an empty array so this test is not doing anything".

+

> returns 0 tests results

in both cases (`@DataProvider` and `@Factory`).

@cbeust Agree?

------

@ryanlevell 

I'm not sure `TestMethodWorker` is the good place to make the fix as it is common code with other `ITestMethod`.

Which line is calling `Utils#checkInstanceOrStatic` and then failing? 

We must not forget that a factory could be a constructor too (so we need test it too).

**Comment by juherr** [comment]
Caution: since https://github.com/cbeust/testng/pull/1044 the behavior maybe changed

**Comment by cbeust** [comment]
@juherr LGTM
