### ISSUE TITLE
[TestNGContentHandler]

### ISSUE THREAD

**Issue by littu27** [cbeust/testng#1032]
Whenever I try to run the XML file I get this error "**[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
org.testng.TestNGException: 
Cannot find class in classpath:**".

Kindly let me know what could be

**Comment by juherr** [comment]
Could you explain what you are trying to do and share files to understand the context?

BTW, I see 2 diffrent things:

1. Your `testng.xml` doesn't have the appropriate doctype
2. TestNG doesn't find class with tests. I suppose your `test.xml` is not good.

I close the issue until we determine if it is a real issue or not.
