### ISSUE TITLE
MethodError

### ISSUE THREAD

**Issue by littu27** [cbeust/testng#1034]
I am getting this error when I run the testng.xml file.

"**java.lang.NoSuchMethodError: org.apache.poi.util.POILogger.log(I[Ljava/lang/Object;)V**"

**Comment by cbeust** [comment]
Unlikely a TestNG error.

**Comment by littu27** [comment]
But I tried to run same on two laptops but same results

**Comment by cbeust** [comment]
TestNG doesn't use POI so the problem is most likely in your code.
