### ISSUE TITLE
Get pro-grammaticallyparameters  used to run a test to re-run it wh

### ISSUE THREAD

**Issue by thasherwin** [cbeust/testng#1037]
Is it possible to get pro-grammatically parameters used to re-run a test if it fails
This is more like a question. I wonder whether it’s possible to get pro-grammatically the parameters to re-run a test whenever it fails?
For example when a test fails that is executed on for example Intellij I can right click on the method and run the test again.
 If I run a test on Jenkins and it fails I will have to execute the whole suite again to very if it is really fail or test this manually. If I know the parameters used to run a test, I can maybe kick-off that specific test automatically using the parameters to verify if it works.

**Comment by juherr** [comment]
Your use case is really dependent of how you are running TestNG (ant, maven, gradle, ...) but you can have a look on http://testng.org/doc/documentation-main.html#rerunning

I close the issue because it is question, and prefer to ask it on StackOverflow or the mailing list which have more audience.
