### ISSUE TITLE
I am unable to run a testng.xml with groups with geb framework

### ISSUE THREAD

**Issue by Subrahmanyam83** [cbeust/testng#1039]
Following is my sample `testng.xml`:

```xml
<suite name="Sample Suite">
    <test name="testing">
        <groups>
            <run>
                <include name="smoke"/>
            </run>
        </groups>

        <classes>
            <class name="Specs.Smoke.SmokeSpec" />
        </classes>
    </test>
</suite>
```

and here is my Spec class:

```java
public class SmokeSpec extends BaseSpec{
    @Test(groups="smoke")
    public void testFunc() {
        to LoginPage
    }
}
```

it throws error: failed to create driver. Could somebody let me know

**Comment by juherr** [comment]
It sounds like a geb issue. You should open an issue there.

**Comment by sridharyalla** [comment]
does your BaseSpec extend GebSpec?

**Comment by Subrahmanyam83** [comment]
It extends GebTest. I pretty much found the issue. Its because of some issue with the build.gradle which i am using to drive my tests which is not allowing to run the groups. Thanks anyways.

**Comment by juherr** [comment]
@Subrahmanyam83 Could we/you close the issue?
