### ISSUE TITLE
6.9.11版本中缺少src\main\java\org\testng\remote目录

### ISSUE THREAD

**Issue by ruberzhu** [cbeust/testng#1042]
在最新的6.9.11源码中，未发现src\main\java\org\testng\remote目录。导致eclipse直接运行testng时，报error。提示无法找到remoteNG类。

**Comment by FibreFoX** [comment]
@ruberzhu could you please report in english?

**Comment by cbeust** [comment]
Yes, English please :)

**Comment by missedone** [comment]
@ruberzhu 
you need to update to latest testng eclipse plugin.
the remote package was removed in PR https://github.com/cbeust/testng/pull/953

**Comment by ruberzhu** [comment]
Sorry, I would say, in the latest 6.9.11 source code not found src \ main \ java \ org \ testng \ remote directory. Eclipse caused when run directly testng, reported error. Tip Can not find remoteNG class. @FibreFoX @cbeust

**Comment by ruberzhu** [comment]
Thanks for  missedone @missedone
