### ISSUE TITLE
TestNG css files contain incorrect comments (using Java/Javascript style)

### ISSUE THREAD

**Issue by DaveBrad** [cbeust/testng#1048]
The testng.CSS files contain an incorrect comment format on certain lines. These lines are flagged as in error by more up-to-date CSS editors.
e.g.
`.main-panel-header {
    padding: 5px;
    background-color: #9FB4D9; //afeeee;
    font-family: monospace;
    font-size: 18px;
}`
The // is a Javascript/Java form of comment. The CSS specification states

" 4.1.9 Comments

Comments begin with the characters "/_" and end with the characters "_/". They may occur anywhere outside other tokens, and their contents have no influence on the rendering. Comments may not be nested.

CSS also allows the SGML comment delimiters ("") in certain places defined by the grammar, but they do not delimit CSS comments. They are permitted so that style rules appearing in an HTML source document (in the STYLE element) may be hidden from pre-HTML 3.2 user agents. See the HTML 4 specification ([HTML4]) for more information. 

https://www.w3.org/TR/CSS2/syndata.html#comments
"

I imported github testNG into Netbeans 8.1 as a Maven projectThese errors were flagged. Additionally, some browsers have started to be picky about correctly formatted HTML and CSS content and in some cases the CSS class is ignored when errors/incorrect settings are incorporated into classes. (Takes a while to figure it out when displays don't appear as coded.)

**Comment by cbeust** [comment]
Thanks for reporting this. Would you be interested in sending a pull request to https://github.com/testng-team/testng-team.github.io ?

**Comment by DaveBrad** [comment]
Hi,

Will do and I'll fork from the testng-team github.

Also, I use Java 8 and when generating Javadoc I notice some reported 
errors. I'll look into those too, but a different push.

Thanks
Dave
