### ISSUE TITLE
Do you like to have native support of Allure Framework 

### ISSUE THREAD

**Issue by baev** [cbeust/testng#1073]
Hi there! Do you like to have native support of Allure Framework? We would like to move Allure integration code to your repository, so you could maintain it at your will and e.g. add early support of your new features. We on our turn would like to move a little bit away from solving test framework specific issues and concentrate on general reporting problems to make Allure rock. What do you guys think?

**Comment by juherr** [comment]
What does it mean? Having your `allure-testng-adaptor` module here? Or are yoy thinking about something else?

I don't really like the idea more things here but why not having a dedicated repository under the @allure-framework or @testng-team organisation (and adding appropriate rights to be able to contribute easily)?

I'm ok to give you some help, but I've no idea what it means.

**Comment by juherr** [comment]
BTW, Allure already rocks! ;p

**Comment by cbeust** [comment]
@juherr My understanding is that @baev would like to transfer the Allure-TestNG integration to TestNG, so they can focus on the core and leave external integrations to interested parties.

I don't have a problem with that, although obviously, such a transfer doesn't mean we'll be working actively on it, it will heavily depend on who wants to contribute.

**Comment by juherr** [comment]
Yes, it is what I understood too. So, I think @testng-team is the best place for it.

**Comment by baev** [comment]
> What does it mean? Having your allure-testng-adaptor module here? Or are yoy thinking about something else?

Yep, we would like to move Allure adaptor source code to your repository (I can send you the pull request with all the changes). It would also be great to see Allure as default TestNg report. Also it would be nice to support your test grouping (as far as I know usually TestNG users are using Suite -> Test -> Class -> Method grouping), save all parameters to the report and so on. Could you also briefly describe how do you see a perfect report? Would you like to have Allure as default one?

> BTW, Allure already rocks! ;p

Thanks!

> although obviously, such a transfer doesn't mean we'll be working actively on it, it will heavily depend on who wants to contribute.

The problem is that our team doesn't use the TestNG at all, so we don't have any valuable TestNG expertise. For now allure-testng-adaptor is supported mostly by the community as well.

**Comment by juherr** [comment]
> I can send you the pull request with all the changes

Just tell me what is the related code.

> It would also be great to see Allure as default TestNg report

It should be a user choice. I'd prefer to remove the current default html one :]

> how do you see a perfect report?

No opinion, it depends un user needs. But IMO, something dynamic could be awesome. See http://stackoverflow.com/q/37746067/4234729

> The problem is that our team doesn't use the TestNG at all

You should! ;)

BTW, it's just my opinion and @cbeust will have final words :)

**Comment by juherr** [comment]
@baev I created https://github.com/testng-team/allure-testng-adaptor (history kept) and gave you admin rigths on the repository.

**Comment by RocketRaccoon** [comment]
> It should be a user choice. I'd prefer to remove the current default html one :]

Where could we vote?

**Comment by juherr** [comment]
No need to vote: You already manage your dependencies yourself. 
And when I say "remove", I mean "extracted in a dedicated dep". 
But nothing is planned, I'm just sharing my minds.

**Comment by RocketRaccoon** [comment]
Then it seems logical to add a chapter about this reporting option to TestNG documentation.

**Comment by juherr** [comment]
@RocketRaccoon Like http://testng.org/doc/documentation-main.html#testng-listeners and/or http://testng.org/doc/documentation-main.html#logging ?

**Comment by sskorol** [comment]
@baev @cbeust @juherr the main question I'm a bit worried about is how you're going to perform `allure-testng-adaptor` integration testing? Technically adaptor is now located outside both projects, but it still contains corresponding `testng` / `allure` dependencies. Leaving it to community means that people must be aware of both projects' core updates. Otherwise, any PR to adaptor may completely break everything. This should have at least CI support for reports visualization.

The other question is: who is going to have a final word regarding dependencies / java version updates? E.g. Allure 2 is re-written on Java 8. Testng is still on Java 7. Adaptor has both dependencies. What would be a new version of `allure-testng-adaptor`? Or there will be the same unsuccessful discussion as in https://github.com/cbeust/testng/issues/864?

**Comment by RocketRaccoon** [comment]
@juherr Yes, but dedicated to Allure features

**Comment by juherr** [comment]
@sskorol 

> how you're going to perform allure-testng-adaptor integration testing?

+1 It is something I planned to ask too. How could we test it? What is already available? ...

> What would be a new version of allure-testng-adaptor?

About the Java dependency, it is easy to answer: 
* it is not planned to move TestNG core in java8
* allure-testng-adaptor will have to follow the higher java version of its dependencies

**Comment by juherr** [comment]
@RocketRaccoon A link to https://github.com/allure-framework/allure-core/wiki/TestNG (or its future new place)?

**Comment by RocketRaccoon** [comment]
@juherr At least for beginnig... We currently have testing framework based on TestNG with powered ReportNG, but moving reporting to Allure. I could provide some code examples of extended usage of TestNG Listeners and Allure, which could be useful for newcomers.

**Comment by sskorol** [comment]
> allure-testng-adaptor will have to follow the higher java version of its dependencies

@juherr correct. I just want to make sure that no one would then say: "hey, this project is a part of testng, so it should have the same java version". :)

**Comment by juherr** [comment]
@RocketRaccoon Depending on the size of the sample, feel free to create a dedicated repository. Then I can host it under @testng-team and provide you push rights on this repo.

@sskorol To be honnest, I think @allure-framework is a better place for `allure-testng-adaptor`. But it is not a problem to host it under @testng-team

**Comment by sskorol** [comment]
Looking at it from different angle I'd conclude the following:
 - Allure team: hi TestNG team, do you want to support our adaptor, as we're not aware of your internals?
 - TestNG team: not really, but let's give it to our community! Someone may want to give it a shot, but if not - it's not our business.
 - Allure team: ok, pushing code... Done. Now it's yours.
 - TestNG team: ok, but it's not ours, it now belongs to the entire community!
:)

**Comment by baev** [comment]
@sskorol calm down. Give me some time and I'll try to explain to you what is going on (kinda busy right now).

**Comment by sskorol** [comment]
@baev ok, would be appreciated :)

**Comment by juherr** [comment]
@sskorol 
The "problem" about testng team is: https://github.com/cbeust/testng/graphs/contributors?from=2015-06-28&to=2016-06-28&type=c or https://github.com/cbeust/testng-eclipse/graphs/contributors?from=2015-06-28&to=2016-06-28&type=c
As usual, it's a time issue and I'm not sure that only the free time of 3 persons is enough to support more.
I'm open to provide some help to allure because I like what they are doing, but the TestNG core will be always my priority :)
For the moment, I've just imported sources to understand the context and nothing is done.

BTW, you should considere to propose some help on both projects if you want a better support ;)

**Comment by sskorol** [comment]
@juherr fyi, I'm already contributing to Allure, so I'm interested in keeping testng-adaptor alive. ;) But it doesn't really mean that I want to do it without any assistance. Both teams should cooperate together as only main committers know everything about projects' architecture, further plans, and potential pitfalls. And leaving it purely to community won't be an option at all. Anyway, I don't have a full picture about allure team intentions, so will just wait for some comments / details.

**Comment by baev** [comment]
Sorry for the delay. Seems like I should start this discussion with the following explanation.

Allure consists of two big parts: report generation tool and a collection of adapters for different test frameworks. Adapters save test execution results for each test framework to a predefined format which is then used to generate a report.

So far as we have sufficient experience with JUnit and TestNG frameworks, respective adapters reside in main Allure repository and we spend more time improving them.

The rest of adapters are community-driven projects and live in separate repositories. They have different level of integration with Allure: some adapters correctly map test execution data to most of Allure features and some support only basic ones. 

The first important problem I would like to talk about is the following. Very often test framework developers are not aware of existing Allure adapter or consider it an independent project. But unfortunately it’s a common case when we have no knowledge of concrete test framework or no time to fix created issues ourselves. We would like to fix this by better collaborating with test framework developers.

From the other side being compared with other approaches adapters are a big advantage of Allure. For example surefire.xml are not supporting all newest reporting trends and requirements. This is why we implemented a separate data storage format used to generate a report.

For the moment, our experience in communicating with real Allure users from different test frameworks we understood that the next data storage format should be adopted. For example current format sometimes does not correctly support test classification approaches widely used in some test frameworks. Also it would be great to use event-driven model for real-time reporting functionality.

The second problem I would discuss is Allure data storage format. It seems that we need to update it again to support new requirements. What we would like to do is to create an open data storage format for test frameworks being supported by the majority of existing frameworks and newcomers.

Having a common data format supported by the most important test frameworks we would concentrate on improving report generation part of Allure. We would like to propose you to participate in this work as the first framework supporting new format. We think your project is the best candidate for this purpose because you have a lot of loyal users and very flexible test grouping capabilities.

There is no need to move our code to your repository right now. All we need is consider the stages we need to complete before you be able to move the integration to your repository. Yep, personally I’d like to create a new module in TestNG repository. It would be much easier to test and support the integration in your repository, not in the separated one. But for now the most important thing is team collaboration on the way to perfect reporting tool.

**Comment by juherr** [comment]
> We would like to fix this by better collaborating with test framework developers.

Feel free to ping me on testng related issues ;)

> We would like to propose you to participate in this work as the first framework supporting new format.

What will be the expected effort? Writing a reporter is not a big one if we have a nice library that helps to generate the good format.

**Comment by baev** [comment]
> Feel free to ping me on testng related issues ;)

@juherr I just started my work on new TestNG adapter and have a few questions. Is there any place where we can discuss them (we can use this issue or create a new one, or use some kind of im like gitter)

**Comment by juherr** [comment]
@baev https://groups.google.com/forum/#!forum/testng-dev ?

**Comment by baev** [comment]
@juherr I created 2 topics, both about the same problem but I guess the second is more clear one, so you can approve only the second one

**Comment by juherr** [comment]
@baev I'm not seeing them. Could you provide a link?

**Comment by baev** [comment]
Nope, I cant see pending posts

**Comment by krmahadevan** [comment]
@juherr - Is this discussion underway ? Just going through issues to see which of them can be closed.

**Comment by juherr** [comment]
@krmahadevan I don't know. It looks Allure still maintain the testng support with https://github.com/allure-framework/allure-java
@baev What is the current plan?

**Comment by baev** [comment]
For now we decided to keep the integration in our repository. 

At the moment the only issue is that there is no listener for data provider methods (see https://groups.google.com/forum/#!topic/testng-dev/WASvXfvq3_M ) 

BTW Thanks you guys for support

**Comment by juherr** [comment]
@baev Thanks. I've added an issue for the listener part #1490
