### ISSUE TITLE
Package initialize all classes at start

### ISSUE THREAD

**Issue by AlmogH** [cbeust/testng#1075]
Hi,
I'm trying to run all of my test by running <package name=".*"/>

The problem is that it initializes all the classes at start ant not when it get to class

 I'm on version 6.9.10

Thanks in advance

**Comment by juherr** [comment]
I'm not sure to understand your problem but, by design, TestNG creates instances for tests first, and then launches them.
So it looks to work as designed :)

Feel free to reopen the issue if you really think it is still a problem.
