### ISSUE TITLE
TestNG Eclipse Plugin fails to resolve maven artifact

### ISSUE THREAD

**Issue by dalgleish** [cbeust/testng#1076]
I have installed TestNG and TestNG M2E Integration Eclipse plugins.
When I try to run an any existing TestNG class or test (Run As > TestNG test) it immediately fails with an error like:

```
Could not resolve artifact com._:_:pom:0.0.1-SNAPSHOT
Could not transfer artifact com._:_:pom:0.0.1-SNAPSHOT from/to central (http://central): central: unknown error
Could not transfer artifact com._:_:pom:0.0.1-SNAPSHOT from/to _-snapshots (http://nexus._.com/nexus/content/repositories/_-snapshots/): Access denied to http://nexus._.com/nexus/content/repositories/_-snapshots/com/_/_/0.0.1-SNAPSHOT/_-0.0.1-SNAPSHOT.pom. Error code 401, Unauthorized
```

(`_` is placeholder for actual name).

Maven is working (`mvn clean install`) and also in Eclipse (Maven > Update Project...).

It seems like TestNG isn't using the credentials I have in `~/.m2/settings.xml` or something.
Any ideas on how to resolve this?

**Comment by cbeust** [comment]
Isn't this an issue for http://github.com/cbeust/testng-eclipse and not TestNG?

**Comment by dalgleish** [comment]
@cbeust Oh yes, it would be - moving question to there.
