### ISSUE TITLE
TestNG cannot handle load

### ISSUE THREAD

**Issue by lud200** [cbeust/testng#1077]
Hi,

I tried to run regression for almost 1000 suites. The performance with testng is fine till I ran 500-600 suites, but when the load increases, testng is getting stuck at topologicalsort in MethodHelper.class. 

Please let me know if anyone faced this issue or if there is any way to resolve this. 

Regards,
Udaya

**Comment by cbeust** [comment]
Stuck as in "it stops moving" or it's just slow?

Any way we can reproduce this?


-- 
Cédric

**Comment by lud200** [comment]
It keeps on moving but it is slow.  When we start the regression run using selenium grid, we had set max instances as 5. When we run less number of suites all the 5 instances of firefox are occupied, but as the suite count increases, there is only one instance of firefox active most of the time. 

We have the testng.xml with around 1160 suites. I tried to debug and check the code. 
We have a testrunner which contains a dataprovider that reads all the suites from xml. @Factory is creating the instances and returning an Object. 

Then the instance list is passed to MethodHelper.class ( private static Graph<ITestNGMethod> topologicalSort). I don't know the exact reason why the execution hangs in here for a lot of time. 

For the firefox instances to start it takes 10-15 mins. The thread count I set in testng.xml is 5 and I had set parallel ="instances".

**Comment by cbeust** [comment]
If you have narrowed this down to a data provider, could you try to make
this data provider lazy? (returning an iterator instead of an array)

-- 
Cédric

**Comment by juherr** [comment]
And use 6.9.12 which fixes some issues with lazy data provider.

**Comment by juherr** [comment]
@lud200 Do you have some dependencies between methods?

**Comment by lud200** [comment]
Not too many dependencies. I had one dependency for retry of failed methods.

**Comment by juherr** [comment]
Ok. In fact, only one `dependsOnXxx` with many tests is making the issue. See #1081, I think it is the same problem.

**Comment by lud200** [comment]
Wow, that worked like magic. Thanks a lot.

**Comment by lud200** [comment]
The problem looks similar to #1081 But if I remove the dependson method at several places, this is going to change the structure of entire framework. Is there a solution for this issue? I tried a couple of things like grouping the test suites and calling the group of test suites and changing Parallel="methods" but this is not allocating all the instances as expected. Is there an alternative approach to resolve this issue?

**Comment by juherr** [comment]
We don't have a solution for the moment. We expect to fix the both issue at the same moment.
