### ISSUE TITLE
Having indices on Factory

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1083]
Like DataProvider, it could be useful to have indices (only on factory methods?) to limit the run on specific instances.

WDYT @cbeust ?

From: https://youtrack.jetbrains.com/issue/IDEA-157827

**Comment by cbeust** [comment]
Maybe. Personally, I'd wait until somebody asks for it :-)

**Comment by juherr** [comment]
Yes, for sur, or even wait for someone who will propose it. It was just a way to track the potential need extracted from the idea issue tracker
