### ISSUE TITLE
DataProvider tests ignored by TestNG 6.9.12 using Gradle 2.14

### ISSUE THREAD

**Issue by ethauvin** [cbeust/testng#1085]
DataProvider tests are ignored by TestNG 6.9.12 using Gradle 2.14 (2.13 and 2.12 too.)

Sample project [here](https://github.com/ethauvin/DataProviderTest) using dp sample code from docs.

Switching to 6.9.11 (without any code change) works.

**Comment by cbeust** [comment]
@juherr I worked with Erik on this one, it's pretty puzzling. Here is what I found so far: the problem seems to be strictly limited to Gradle (I tested 2.14, 2.13, 2.12) and TestNG 6.9.12. TestNG 6.9.11 works fine.

If you build the example project with Gradle, you'll see:

```
Gradle Test Executor 1 started executing tests.

Gradle suite > Gradle test > LibraryTest.verifyData1 SKIPPED
Gradle Test Executor 1 finished executing tests.
```

The tests run fine 1) manually (from master with IDEA) and 2) with Kobalt.

**Comment by juherr** [comment]
Ok, really strange. I think it is something related with my changes on data provider but why is it only happening with gradle...

I think that the next step is to open an issue on the gradle project: https://issues.gradle.org

@ethauvin Could you add maven on your sample project?

**Comment by ethauvin** [comment]
@juherr Done. DP test is skipped too, so probably not Gradle.

![capture](https://cloud.githubusercontent.com/assets/705618/16646693/520ff63c-43e0-11e6-9042-48cd52bbf002.PNG)

**Comment by juherr** [comment]
ok, thank!

**Comment by ethauvin** [comment]
Just noticed the following:

![capture](https://cloud.githubusercontent.com/assets/705618/16647117/7f71f6b4-43e2-11e6-9df0-a0ee924327d2.PNG)

**Comment by juherr** [comment]
Ok, catched! Good job @ethauvin :+1: 
I use Guava which is not a direct dependency of TestNG (but a transitive one from Guice which is optional).

@cbeust I see 2 solutions: adding Guava as dependency (it will allow us to use guava) OR rewrite the method I use. Which one do you prefer?

**Comment by juherr** [comment]
@ethauvin As workarround, you can add guava as dependency of your project. It should work.

**Comment by ethauvin** [comment]
@juherr It should, I'll play with it tomorrow.

@cbeust Let him use Guava, no need to reinvent the wheel.

**Comment by cbeust** [comment]
Maybe it's not worth depending on Guava just for that?

And yes, the bottom line is that you should always declare your direct dependencies in your build file, otherwise you may break in very mysterious ways :-)

**Comment by juherr** [comment]
> Maybe it's not worth depending on Guava just for that? We have to be very careful what dependencies we bring in with TestNG.

No opinion, you choose!

> And yes, the bottom line is that you should always declare your direct dependencies in your build file, otherwise you may break in very mysterious ways :-)

For sure, and IDE/buid tools should warn about it when it is not the case (maven has a plugin for that)

**Comment by cbeust** [comment]
Ok then no Guava :)


-- 
Cédric

**Comment by ethauvin** [comment]
FYI, as expected, workaround works with Gradle, Kobalt and Maven.

Sample project has been updated.
