### ISSUE TITLE
how to controll class's running order in the testng.xml

### ISSUE THREAD

**Issue by zsyet** [cbeust/testng#1088]
for example:

```xml
<suite name="qrcode" verbose="1" >
  <test name="cinemamgr" enabled="true">
    <classes>
       <class name="com.CinemaTestNG" />
       <class name="com.FilmTestNG" />
    </classes>
  </test>
  <test name="ticketmgr" enabled="true">
    <classes>
       <class name="com.TicketTestNG" />
    </classes>
  </test>
</suite>
```

i expects the test and the classes will be ran just as the order they are in the xml, it's possible to run `FilmTestNG` until all methods in `CinemaTestNG` are completed, i can't find an answer from testng document

**Comment by madhu4a3** [comment]
Hi zsyet,
 If i understand correctly your classes are running in a random fashion.In your case you wanted CinemaTestNG test methods to run first and then FilmTestNG test methods later. If yes, you can try like this by adding preserve order param to your test tag <test name="cinemamgr" enabled="true" preserve-order="true"> .

**Comment by juherr** [comment]
Please, ask your question on stackoverflow or the mailing list before.
