### ISSUE TITLE
TESTNG - dataProvider and retryAnalyzer combination problem

### ISSUE THREAD

**Issue by jpreddygithub** [cbeust/testng#1091]
Hi Guys

We are seeing an issue where when the test case fails with any of the parameter of the dataProvider, it 
retries with nextParameter as well.

Brief investigation shows this part of code as the problem(Invoker.java)

``` java
finally {
                if (failure.instances.isEmpty()) {
                  result.addAll(tmpResults);
                } else {
                  for (Object failedInstance : failure.instances) {
                    List<ITestResult> retryResults = Lists.newArrayList();

                    failure.count = retryFailed(
                            failedInstance, testMethod, suite, testClass, beforeMethods,
                     afterMethods, groupMethods, retryResults,
                     failure.count, expectedExceptionHolder,
                     testContext, parameters, parametersIndex);
                  result.addAll(retryResults);
                  }
                }
```

i don't see where failure.instances is being cleared for the next Parameter

Please see the attached files to simulate the problem. We are failing the test when the param is "Idaho" exclusively

You will see output  as

```
Colorado
Idaho
Idaho
Idaho
Seattle
Seattle
```

Where when we expect the output as

```
Colorado
Idaho
Idaho
Idaho
Seattle
```

[RetryAnalyzer.txt](https://github.com/cbeust/testng/files/362502/RetryAnalyzer.txt)
[Test.txt](https://github.com/cbeust/testng/files/362503/Test.txt)

**Comment by Imran216** [comment]
This problem is happening only when use 
DataProvider and RetryAnalyzer are used together on latest version of TestNG (>6.7)

**Comment by jpreddygithub** [comment]
Any update on this issue?

**Comment by juherr** [comment]
Not yet but feel free to try to propose a fix :)

**Comment by rodrigomunoz** [comment]
This seems to be fixed in the latest version. I tested it with 6.14.2 and I don't see the behavior anymore.

**Comment by krmahadevan** [comment]
Closing this issue based on the above inputs from @rodrigomunoz 

Please comment, if this is still a problem.
