### ISSUE TITLE
Eclipse plugin should provide a "rerun test" key command

### ISSUE THREAD

**Issue by stephenh** [cbeust/testng#1101]
With JUnit, I've got Control-F12 bound to "Rerun last test". It'd be nice to be able to do this with TestNG as well.

**Comment by juherr** [comment]
Please, add your feature request on https://github.com/cbeust/testng-eclipse

**Comment by stephenh** [comment]
Cool, done.

**Comment by missedone** [comment]
link to https://github.com/cbeust/testng-eclipse/issues/268
