### ISSUE TITLE
Improve error messages when comparing collections.

### ISSUE THREAD

**Issue by fhur** [cbeust/testng#1102]
When you compare collections with the `assertEquals(Collection expected, Collection actual)` methods, and their sizes do not match, you get the following (example):

```
lists don't have the same size, expected 5 but was 6
```

or something like that. Wouldn't it be better if instead you got the error message you get when comparing iterators or collections of the same size:

```
Lists differ at element [" + i + "]: " + e + " != " + a
```

**Comment by fhur** [comment]
So basically, I would eliminate the `assertEquals(actual.size(), expected.size(), (message == null?"":message + ": ") + "lists don\'t have the same size");` line inside `assertEquals(Collection<?> actual, Collection<?> expected, String message)`

**Comment by cbeust** [comment]
Have you considered using assert4j? I think its assertions are superior to
TestNG's overall.


-- 
Cédric


On Tue, Jul 19, 2016 at 11:43 AM, Fernando Hurtado <notifications@github.com

**Comment by juherr** [comment]
+1 for assertj. They are making a really good job which will be difficult to compete. And we are higher priority :)

**Comment by krmahadevan** [comment]
@juherr - Do you think we can close off this issue, since we are recommending that people look at `assertj` for use-cases such as this ?

**Comment by juherr** [comment]
@krmahadevan I think we can :+1:
