### ISSUE TITLE
Add org.testng.internal.junit.ArrayAsserts.assertArrayEquals(boolean[], boolean[])

### ISSUE THREAD

**Issue by jhalterman** [cbeust/testng#1103]
Would be nice to have a  `org.testng.internal.junit.ArrayAsserts.assertArrayEquals(boolean[], boolean[])` implementation. It seems to be the only one missing and I actually ended up needing it today.

**Comment by juherr** [comment]
Feel free to propose it. But for more complex assertions, assertj is recommanded.
