### ISSUE TITLE
Method description from Suite xml is not retrieved properly from a suite

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1113]
My test class looks like below

```
public class MethodDescriptionSample {
    @Test
    public void helloWorld() {
        System.err.println("Hello world");
    }
}
```

My suite xml looks like below

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Class1Suite" parallel="false" verbose="2">
    <test name="Class1Test">
        <classes>
            <class name="organized.chaos.forums.MethodDescriptionSample">
                <methods>
                    <include name="helloWorld" description="A sample description"/>
                </methods>
            </class>
        </classes>
    </test> <!-- Class1Test -->
</suite> <!-- Class1Suite -->
```

Now from within a Listener, when we try to access the description that was set via the suite xml file, it comes back as null.. i.e.,

`org.testng.xml.XmlInclude#getDescription` returns null.

This query came up on the TestNG forum. 
Here's the thread https://groups.google.com/d/msg/testng-users/KoaZzQ32aJE/BINHWlXxCwAJ

**Comment by juherr** [comment]
Could be similar to #1112

Any clues about a fix ?

**Comment by krmahadevan** [comment]
@juherr 
Yes, its the same. Infact the post seems to be by the same user on both StackOverflow and testng google forums. I have the fix. I will be raising a pull request shortly.

**Comment by juherr** [comment]
Closed as duplicate.

**Comment by avinashatgit** [comment]
Thanks  krishnan and juherr for revalidating and posting as issue. Yes, i posted this on both of the forums. I hope to see this fixed in future. 

Regards,
Avinash
