### ISSUE TITLE
Comparing List<boolean[]> Regression

### ISSUE THREAD

**Issue by NikolayMetchev** [cbeust/testng#1116]
The following test passes with TestNG 6.8.8 but fails with 6.9.12:
```java
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.testng.Assert;
import org.testng.annotations.Test;

public class TestCollectionArrays {
  @Test
  public void testArrays() {
    List<boolean[]> arraysList1 = new ArrayList<>();
    arraysList1.add(new boolean[] {true,false});

    List<boolean[]> arraysList2 = Arrays.asList(new boolean[] {true,false});

    Assert.assertEquals(arraysList1, arraysList2);
  }
}
```

**Comment by juherr** [comment]
Since #870 and TestNG 6.9.10, some behaviors with assertions changed.
Now:

> "arrays inside lists are compared by reference in assertEquals"

https://github.com/cbeust/testng/blob/master/src/test/java/test/asserttests/ArrayEqualityAssertTest.java#L72

The observed behavior is the expected one.
