### ISSUE TITLE
Is there any way to make the particular test execution skip on conditional basis?  

### ISSUE THREAD

**Issue by ankit8051** [cbeust/testng#1129]
Hi Team,

I have below test cases.

```
@Test
public void test1(){
   // Test case1
}

@Test
public void test2(){
   // Test case2
}
```
I want test1() will execute if some condition will satisfy and test2() if other.

Is there any way to make the particular test execution skip on the conditional basis?

**Comment by juherr** [comment]
```java
@Test
public void test1(){
   if (!someConditions) {
      throw new SkipException();
   }
   // Test case1
}

@Test
public void test2(){
   if (!someOtherCondition) {
      throw new SkipException();
   }
   // Test case2
}
```

or use a listener (IInvokedMethodListener , IHookable or IInvokedMethodListener ) to filter test execution: http://testng.org/doc/documentation-main.html#testng-listeners

If you need more details, please use stackoverflow instead.
