### ISSUE TITLE
Guice AOP does not work correct

### ISSUE THREAD

**Issue by olgmaks** [cbeust/testng#1132]
When try to use TestNG 6.9.10 with Guice 
bindInterceptor( ...... , ..... , new MethodInterceptor());

 MethodInterceptor was not bind to class and it does not intercept method invocation

Previous TestNG versions (6.8) work fine

**Comment by juherr** [comment]
Thanks for the report.

Could you share a runnable project in order to understand what is the regression?

**Comment by olgmaks** [comment]
https://github.com/olgmaks/testng-guice.git

**Comment by juherr** [comment]
Thanks for the example. It helped!

I'm not sure to issue come from TestNG:

```java
Injector injector = Guice.createInjector(new InjModule());
Rectangle instance = injector.getInstance(Rectangle.class);
instance.messagedVoid();
``` 

prints, as expected:

> Hellow world message
> syso

But 
```java
Injector injector = Guice.createInjector().createChildInjector(new InjModule());
Rectangle instance = injector.getInstance(Rectangle.class);
instance.messagedVoid();
``` 

will only print

> syso

**Comment by juherr** [comment]
Well, it is working well with:

```java
public class InjModule extends AbstractModule {
    @Override
    protected void configure() {
        bindInterceptor(Matchers.any() , Matchers.annotatedWith(Message.class), new MessageListener());
        bind(Rectangle.class);
    }
}
```

For more detail: https://github.com/google/guice/issues/893

**Comment by juherr** [comment]
Another solution is having:

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Suite1" parent-module="com.olgmaks.InjModule">
    <test name="Nopackage">
        <classes>
            <class name="com.olgmaks.GuiceTest"/>
        </classes>
    </test>
</suite>
```

And

```java
@Guice
public class GuiceTest {

  // ...
}
```

Can we consider the issue as closed?

**Comment by juherr** [comment]
I think the issue is closed. Feel free to reopen it if you consider it is not the case.
