### ISSUE TITLE
6.9.13-SNAPSHOT contains a weird version of XmlTest

### ISSUE THREAD

**Issue by gjuillot** [cbeust/testng#1133]
Hi,

I was trying 6.9.13-SNASPHOT to test latest fixes and found something weird : the XmlTest class inside has `Boolean getPreserveOrder()` while repo here show it should rather be `String getPreserveOrder`.

**Comment by juherr** [comment]
I'm not sure to understand because the master branch has `Boolean` too: https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XmlTest.java#L712

```java
  public Boolean getPreserveOrder() {
    if (m_preserveOrder == null) {
      return m_suite.getPreserveOrder();
    }
```
