### ISSUE TITLE
DataProvider could support Object[] as a valid return type

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1139]
From: http://stackoverflow.com/q/39332119/4234729

**Comment by virenv** [comment]
Can be achieved by 2-D array with only 1 column. Effectively making it a single D array. Is there more requirements to it?

@Test(dataProvider = "getNames")
public void test01(Name name) {
	System.out.println(name.name + " " + name.id);
}

@DataProvider
public Object[][] getNames() {
	Name[][] result = new Name[2][1];
	result[0][0] = new Name("john", 5);
	result[1][0] = new Name("doe", 4);
	return result;
}

I tested your code with the change I am suggesting it works just fine.

**Comment by juherr** [comment]
Yep, you describe the test case to valid the feature. But we have to be strong on failure validation too and try to convert every case:
* Object[] -> 1 method param
* Object[] -> n method params
* Object[] -> 1 array method param
* Object[] -> n method params with an or more array param(s) (in different position)
* ...

Same for Object[][].

**Comment by virenv** [comment]
Yes you are right, it will not be able to display the params. However if we override the toString we can get something readable

```
	@Test(dataProvider = "getNames")
	public void test01(Name name) {
		System.out.println(name.name + " " + name.id);
	}

	@DataProvider
	public Object[][] getNames() {
		Name[][] result = new Name[2][1];
		result[0][0] = new Name("john", 5);
		result[1][0] = new Name("doe", 4);
		return result;
	}
```

But yes completely agree that if a small change can make more readable output. However, I think you will still need the toStirng method to get readable output?

**Comment by juherr** [comment]
In fact the complain was about the 2d array which is possible with junit.

**Comment by nitinverma** [comment]
sugar syntax:
return types for a data-provider can be anything depending on the use case involved.
for instance test(int) <-suffices- `int data()` or `Integer data()` or `int[] data()` or `List<Integer> data()`  or good old `Object[][] data()` etc.

following are few intuitive returns i can think of.
```
?
?[]
Collection<?>
?[][]
Collection<?[]>
Collection<Collection<?>>
```

**Comment by nitinverma** [comment]
point is, for most cases, developers do not need an array.

**Comment by nitinverma** [comment]
we need nested arrays or lists to solve situations like `test(String[], String)`

**Comment by juherr** [comment]
* `?`: I'm not sure to understand the use case behind it.
* ` ?[]` : will be available with https://github.com/cbeust/testng/pull/1161
* `Collection<?>`: But I think `Iterable<?>` will be better instead and collection.iterator() is not a big deal IMO
* `?[][]`: is already working
* `Collection<?[]>`: Same as `Collection<?>`
* `Collection<Collection<?>>`: Same as `Collection<?>`

**Comment by juherr** [comment]
@nitinverma Feel free to open another issue if you think others sugar syntaxes may be implemented.

**Comment by nitinverma** [comment]
>> `?: I'm not sure to understand the use case behind it.`
User wanted to call single param test method once.

>> `Collection<Collection<?>>: Same as Collection<?>`
Consider user intents  to call`testMethod(int a...)` twice. First with '1,2,3' then with '7,8,9' and writes a DataProvider `Object [] data(){returns a List containing 1,2,3,7,8,9}`.
User thinks: 'hmmm... How would any logic deduce my intention exchanging that datatype? Let me try `Collection<Collection<?>>`'
A user accustomed of using `Collection<?>` would not latch to `Object[][]` without reading documentation or googling.

`Iterable<?>` 👍 

Following are the natural progressions i think:
`? -> ?[] -> ?[][]`
or
`? -> Iterable<?> -> Iterable<Iterable<?>>`

**Comment by juherr** [comment]
ok, why not. You can open an issue to keep a trace (or better, propose a pull request)

**Comment by ben-manes** [comment]
The exception message is out of date, as is the annotation and website's documentation. Can you please update so that this enhancement is more visible?

**Comment by juherr** [comment]
@ben-manes Which exception message?

**Comment by ben-manes** [comment]
```java
throw new TestNGException("Data Provider " + dataProvider + " must return"
    + " either Object[][] or Iterator<Object>[], not " + dataProvider.getReturnType());
```

**Comment by juherr** [comment]
@ben-manes It supposed to be done with #1376 (available in the next release): https://github.com/cbeust/testng/blob/ce05e2779d87f73a445ffb3926119783610b411a/src/main/java/org/testng/internal/MethodInvocationHelper.java#L137

**Comment by juherr** [comment]
@ben-manes And I've just added the missing documentation in the todo list: https://github.com/testng-team/testng-team.github.io/issues/16

**Comment by ben-manes** [comment]
Thanks!
