### ISSUE TITLE
Add Class and Constructor as legal native dependency injection

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1144]
`Method` and `ConstructorOrMethod` are legal but not yet `Class` or `Constructor`.

Idea from: http://stackoverflow.com/q/39391569/4234729

**Comment by gjuillot** [comment]
It looks to me that `Constructor` is in fact [already supported](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/MethodInvocationHelper.java#L152)

**Comment by juherr** [comment]
@gjuillot Ok, thanks! But when I tried it didn't work.
Could you check we already have a test which covers that case? And if not add one (could be the one from the stackoverflow question)?
