### ISSUE TITLE
Wrong test is run when re-running failed DataProvider tests a second time

### ISSUE THREAD

**Issue by nocomply78** [cbeust/testng#1148]
```java
public class DataProviderExample {

    @DataProvider(name = "test1")
    public Object[][] createData1() {
        return new Object[][] {
                { "Cedric", new Integer(36) },
                { "Anne", new Integer(37)},
        };
    }

    //This test method declares that its data should be supplied by the Data Provider named "test1"
    @Test(dataProvider = "test1")
    public void verifyData1(String n1, Integer n2) {
        boolean pass = n1.equals("Cedric");
        System.out.println(n1 + " == Cedric - " + pass);
        Assert.assertTrue(pass);
    }

}

```
Running the above test results in the following output:

```
Cedric == Cedric - true
Anne == Cedric - false

===============================================
DataProvider Example Suite
Total tests run: 2, Failures: 1, Skips: 0
===============================================
```

Running the resulting testng-failed.xml creates the following output:

```
Anne == Cedric - false

===============================================
Failed suite [DataProvider Example Suite]
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

Running the testng-failed.xml created after the previous re-run-failed creates the following output:
```
Cedric == Cedric - true

===============================================
Failed suite [Failed suite [DataProvider Example Suite]]
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

## Expected Result:
Second re-run-failed attempts to re-run the test that has been failing (i.e. invocation-number 1, which was added to the testng-failed.xml file after the very first test run), rather than the test that passed in the very first run
e.g. resulting in the following output:
```
Anne == Cedric - false

===============================================
Failed suite [Failed suite [DataProvider Example Suite]]
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

**Comment by juherr** [comment]
How do you run the suite ?

**Comment by juherr** [comment]
The result is strange:

```
Cedric == Cedric - true

===============================================
DataProvider Example Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

How it is possible to have 1 failure?

**Comment by nocomply78** [comment]
Sorry, my bad. Copy & paste fail. I'll update the original comment now.

In answer to the first question, I've run it two ways - once through IntelliJ (right-clicking a config xml and then doing so again on the generated testng-failed.xml), and also running said xml files from command line.
Attaching a zip of the project and a couple of batch files for running.
[TestNG.zip](https://github.com/cbeust/testng/files/468363/TestNG.zip)

**Comment by nocomply78** [comment]
Seems like this may be a duplicate of #148 ('Run Failed Test' doesn't run the proper tests after 2nd rerun when DataProvider is used)
That issue appears to suggest the problem is with the Eclipse plugin, but the two issues look eerily similar

**Comment by juherr** [comment]
Nice catch, thanks!

I close this one as duplicate and will continue to follow the other one.
