### ISSUE TITLE
Eclipse runner fails with 6.9.13

### ISSUE THREAD

**Issue by ben-manes** [cbeust/testng#1160]
I tried upgrading to `6.9.13` and received the following error in Eclipse,

>Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.5.1) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:123)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:38)

I checked for updates (none) and restarted Eclipse in case previous weren't applied. Unfortunately no luck. The installation details for the plugin are,

> TestNG  6.9.12.201607091356	org.testng.eclipse.feature.group	Cedric Beust

`6.9.12` works great, so I'll stick to that until this is resolved. Thanks!

**Comment by juherr** [comment]
Please, open the issue on https://github.com/cbeust/testng-eclipse/

**Comment by ben-manes** [comment]
Oops, thanks!

**Comment by missedone** [comment]
hi @juherr 
there are two issues with 6.9.13:
1. the `DEV-SNAPSHOT` does not get correctly substituted
2. the jar was built with jdk8 rather than jdk7

```
// Compiled from Version.java (version 1.8 : 52.0, super bit)
public class org.testng.internal.Version {
  
  // Field descriptor #15 Ljava/lang/String;
  public static final java.lang.String VERSION = "DEV-SNAPSHOT";
  
  // Method descriptor #18 ()V
  // Stack: 1, Locals: 1
  public Version();
    0  aload_0 [this]
    1  invokespecial java.lang.Object() [1]
    4  return
      Line numbers:
        [pc: 0, line: 3]
  
  // Method descriptor #22 ()Ljava/lang/String;
  // Stack: 1, Locals: 0
  public static java.lang.String getVersionString();
    0  ldc <String "DEV-SNAPSHOT"> [3]
    2  areturn
      Line numbers:
        [pc: 0, line: 8]
```

**Comment by ben-manes** [comment]
Linking to https://github.com/cbeust/testng/issues/1160

**Comment by juherr** [comment]
@missedone 
Ok, duplicate of #1159 then
