### ISSUE TITLE
Provider mismatch issue with jmockit tool

### ISSUE THREAD

**Issue by AlexStasko** [cbeust/testng#1162]
Hi
I faced an issue with **testng** 6.9.11 and higher. I tend the issue in jmockit tool and I created issue there. https://github.com/jmockit/jmockit1/issues/337 . But there is a chance issue is on your side.

Thank you,
Alex

**Comment by juherr** [comment]
I close the issue because JMockit should upgrade its TestNG version.

Another issue could be a SPI on TestNG side in order to help JMockit to do its job.
