### ISSUE TITLE
Not able to run multiple test cases in testng with different set of test data from csv file

### ISSUE THREAD

**Issue by prakashriti** [cbeust/testng#1163]
TestNG Version - 6.9.10

I want to run few test cases using testng with different set of data from csv file. I need to use data from each column of csv file in different test cases and i need to iterate all the test cases again if i have multiple rows in csv file. I want the solution to run test1() with first column of first row, test2() with second column of first row, test3() with third column of first row and test4() with fourth column of first row and then same need to be iterated with second row and so on. I have tried the below sample code,

```java
public class YourTest {

    @DataProvider
    public static Object[][] data() {
        try( FileReader read = new FileReader(fileName)) {
            CSVReader csvReader = new CSVReader(reader);

            List<CSVRecord> records = ... read data;

            Object[][] parameters = new Object[records.length][1];
            for(int i=0; i<records.length; i++) {
               parameters[i][0] = records.get(i);
            }
            return parameters;
        }
    }

    @Test(dataProvider="data")
    public void test(CsvRecord record) {
         ...do something with the record
    }
}
```

But the above code dint work as expected. It should run as test1() > test2() > test3() for every row in csv file. But it works in a way like test1() is executed with all the rows of csv and then it moves to test2() and so on.

**Comment by juherr** [comment]
Your description is the expected behavior.

You should have a look on [dependencies](http://testng.org/doc/documentation-main.html#dependent-methods) and/or [factory](http://testng.org/doc/documentation-main.html#factories).
