### ISSUE TITLE
Better message to user when param injection is not good

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1165]
From: http://stackoverflow.com/q/39642327/4234729

**Comment by krmahadevan** [comment]
@juherr - Can you please let me know what is the expectation here ? Based on that, I can try taking a jab at this.

**Comment by juherr** [comment]
I think `Method tearDownClass requires 1 parameters but 0 were supplied in the @Configuration annotation` should be replaced by something else because `ITestNGMethod` is not related to a parameter but it is a native injection param.

In this case, we should provide a more precise message like "It is not possible to inject ITestNGMethod into an after method" maybe with the link to the doc: http://testng.org/doc/documentation-main.html#native-dependency-injection

We should check the other similar cases too.

**Comment by krmahadevan** [comment]
@juherr - I have tried fixing this.

Here's how a sample test looks like 

```
@AfterClass (alwaysRun = true)
public void tearDownClass(final ITestNGMethod itx) {
    final Method m = itx.getConstructorOrMethod().getMethod();
    System.out.println(m.getName());
}
```
and a sample error message would look like

```
org.testng.TestNGException: 
Cannot inject @Configuration annotated Method [tearDownClass] with [interface org.testng.ITestNGMethod].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
```
