### ISSUE TITLE
Add feature to allow combining data providers

### ISSUE THREAD

**Issue by kotovdv** [cbeust/testng#1171]
### Combining data providers

It would be very nice to have a feature, that will allow us to combine multiple data providers into single DP. The result of such combination could be a **cartesian product** or **concatenation**, depending on options specified.

### Simple example
 Lets say we have two dataProviders **first** and **second**. We are already using these two somewhere in our tests and we need the third one, which is going to be **cartesian product** of these two.

 ```
    @Test(dataProvider = "combination")
    public void combinedDpTest(int firstDpArgument, int secondDpArgument) {
        //test method body
    }


    @CombinedDataProvider(mode = CARTESIAN_PRODUCT)
    public String[] combination() {
        return new String[]{"first", "second"};
    }


    @DataProvider
    public Object[][] first() {
        return new Object[][]{
                {1},
                {2},
                {3}
        };
    }

    @DataProvider
    public Object[][] second() {
        return new Object[][]{
                {4},
                {5},
                {6}
        };
    }

**Comment by cbeust** [comment]
This has come up a few times and I've never really been convinced it's worth adding such an implementation to TestNG when there are so many ways data providers can be combined.

**Comment by cbeust** [comment]
This has come up a few times and I've never really been convinced it's worth adding such an implementation to TestNG when there are so many ways data providers can be combined and it's pretty trivial to write your own.

**Comment by kotovdv** [comment]
Yeah, i'm aware of the fact that these combinations are easy to implement on your own, but it would be handy to have such thing "out of the box" anyway imo.

**Comment by juherr** [comment]
Duplicate of https://github.com/cbeust/testng/pull/865
