### ISSUE TITLE
Improvement :: Can the Default output directory be modified be user rather being hard-coded

### ISSUE THREAD

**Issue by parasvora1987** [cbeust/testng#1176]
### TestNG Version - 6.9.13.6

Need to have capability to re-set the default test-output folder

**Comment by juherr** [comment]
Thanks for the report but sorry, I don't understand what you ask for :(

**Comment by dr29bart** [comment]
Will it help?
http://maven.apache.org/components/surefire/maven-surefire-report-plugin/examples/report-custom-location.html

**Comment by krmahadevan** [comment]
@dr29bart - Are you suggesting that there be some mechanism to change the default `test-output` folder ? If yes, then for what sort of execution are you needing this capability ?

**Comment by parasvora1987** [comment]
I need capability to save the execution report into user defined location which is presently, mandatory into the test-output folder. In case this capability is added, user would be able to save the report into remote location as well (needless to mention the remote location should be in the same LAN or should be accessible). The default location may still be the test-output folder as it is now.

**Comment by krmahadevan** [comment]
@parasvora1987 - I don't think its mandated. You have the luxury of changing this via whatever mechanism you are using to trigger your testng executions. Surefire plugin gives you this mechanism to change this if you are doing it through maven. Refer to the link shared in this comment https://github.com/cbeust/testng/issues/1176#issuecomment-252410323 by @dr29bart

**Comment by juherr** [comment]
@parasvora1987 The ouput directory is supposed to be managed by runners. Which runner are you using?

**Comment by krmahadevan** [comment]
Closing off this as this is not an issue. TestNG lets its users customize the output directory.
