### ISSUE TITLE
NullPointerException on getting excluded/included groups

### ISSUE THREAD

**Issue by slipwalker** [cbeust/testng#1180]
TestNg Version 6.9.13.6

My testng.xml file contains block `<groups></groups>` with some defined excluded groups in. I'm running the tests by using Maven. Just on starting I've got the following NPE:

```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project ui-test: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process] 
org.testng.TestNGException: java.lang.NullPointerException
at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:325)
at org.testng.TestNG.run(TestNG.java:1081)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290) 
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException
at org.testng.xml.XmlSuite.getExcludedGroups(XmlSuite.java:1072)
at org.testng.xml.XmlTest.getExcludedGroups(XmlTest.java:227)
at org.testng.internal.OverrideProcessor.process(OverrideProcessor.java:37)
at org.testng.xml.Parser.parse(Parser.java:225)
at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:305)
```

Everything works OK on the previous older version (e.g. 6.9.8)

**Comment by juherr** [comment]
Could you share your `testng.xml`?

**Comment by slipwalker** [comment]
It looks something like that:

`<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >`

`<suite name="My Suite" verbose="2"  parallel="tests" thread-count="1">`

    <groups>
        <run>
            <exclude name="broken"/>
        </run>
    </groups>

    <test name="Some Tests">
        <classes>
            <class name="com.project.some.SomeMyTests"/>
        </classes>
    </test>
`</suite>`

**Comment by krmahadevan** [comment]
@juherr - I would like to give this a try and see if i can fix it. The issue is recreateable.
Here's what I have found so far.
By default the data member `XmlRun` is never instantiated when you create a `XmlGroup` instance, but the [code](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XmlSuite.java#L1038-L1040) tries to access the list of included and excluded groups via XmlGroup.getRun() method which leads to the `NullPointerException`. In the previous versions somehow `m_xmlGroups` was always null and as such the fact that `getRun()` would result in a null was never triggered, but now somehow for the same test `m_xmlGroups` is not `null` anymore. I will continue debugging this after work today. Just thought I would call this out, so that someone else doesn't also end up picking this issue and work :)

**Comment by juherr** [comment]
@krmahadevan Ok, great! I think the most important part is to add some tests.

> <!ELEMENT groups (define*,run?,dependencies?) >

As `run` is optional, I don't know if we should create a new instance with the `groups` object. But I've no recommendation, then I let you find the best solution :)

**Comment by krmahadevan** [comment]
Sure Julien. Will do that. I am also not completely sure as to how the fix
would be. I have just managed to come closer to where the problem might be.
I will add tests as well, when I raise the Pull Request.

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/
My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by juherr** [comment]
👍

**Comment by ranadinesh786** [comment]
issue :
=====
 How to solve NULLPOINTEREXCEPTION while using grouping concepts in POM with Extends Reporting ?


Solutions: 
======
	       1. Use below parameters to all the configuration annotations which we are using i.e. in base test;
		(alwaysRun = true)
		2. Use valid try catch block inside the page class and don’t use throws [incorrect exception]
		3. Use parameterized values instead of taking hardcode values inside the page or script.
