### ISSUE TITLE
MethodMatcherException: Data provider mismatch

### ISSUE THREAD

**Issue by archiecobbs** [cbeust/testng#1181]
### TestNG Version
6.9.13.6

### Expected behavior
Test works like it has for years

### Actual behavior
Test parameter wiring fails with:

```
org.testng.internal.reflect.MethodMatcherException:
Data provider mismatch
Method: testLongEncodeLength([Parameter{index=0, type=long, declaredAnnotations=[]},
Parameter{index=1, type=int, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer)0,(java.lang.Integer)1]
```

Looks like testng forgot how to automatically widen `int` to `long`.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
    @Test(dataProvider = "lengths")
    public void testLongEncodeLength(long value, int expected) {
     ...
    }

    @DataProvider(name = "lengths")
    public Object[][] genLengths() {
        return new Object[][] { { 0, 1 } };
   }
```

**Comment by juherr** [comment]
@nitinverma Any idea for a fix?

**Comment by krmahadevan** [comment]
@juherr - I have tried fixing this issue. Can you please help take a look ?

**Comment by nitinverma** [comment]
pardon me, Im on a vacation.

fix is a sugar syntax for numbers. strict syntax works even today; `0L` would have indicated user intension. 
<code>
return new Object[][] { { 0L, 1 } };
</code>
Error msg was load and clear asking for a long/Long `Arguments: [(java.lang.Integer)0,(java.lang.Integer)1]`

@krmahadevan plz verify if need any changes in error/warns given to the user.

**Comment by archiecobbs** [comment]
Are you saying this doesn't need to be fixed?? That's crazy talk.

(a) This has worked fine in TestNG for years; this bug is a regression.
(b) Java programmers expect automatic widening conversions.

Either (a) or (b) alone is reason enough to fix this; both together is that much more compelling.

**Comment by nitinverma** [comment]
@archiecobbs does the comment (https://github.com/cbeust/testng/issues/1181#issuecomment-253276860) any where said this fix was unneeded? we need error/warm messaging inline with this fix.

**Comment by archiecobbs** [comment]
My apologies if I misread your comment.

It seemed to be implying the user was at fault for not specifying `0L` instead of `0`.

**Comment by nitinverma** [comment]
my bad should not have written from a beach side having distractions close by.

**Comment by krmahadevan** [comment]
@nitinverma - What error message are you talking about ? Can you please help elaborate ?
The reason why i didnt feel that an error/warning message was needed here was because

1. This used to work fine in the earlier versions of TestNG
2. This seemed counter-intuitive to me when compared to Java's behavior because Java allows widening conversions.

Please let me know if I am missing something obvious here.

**Comment by nitinverma** [comment]
@krmahadevan no issues, i'll verify myself soon.
