### ISSUE TITLE
Javadoc for @BeforeXXX and @AfterXXX

### ISSUE THREAD

**Issue by stoerr** [cbeust/testng#119]
Can you please put a Javadoc class comment at the before and after annotations? Even the one sentence short description in the documentation would be something that serves many purposes. There should be at least something you get shown in the IDE when you hover over an annotation. 

Thanks so much!

Hans-Peter

**Comment by krmahadevan** [comment]
@juherr - We can close this issue as well. All the TestNG annotations have proper javadocs.

**Comment by juherr** [comment]
Done
