### ISSUE TITLE
XML report is incomplete

### ISSUE THREAD

**Issue by nbruning** [cbeust/testng#1203]
### TestNG Version
6.9.13, master

### Expected behavior
The XML report file is written correctly and completely.

### Actual behavior
The XML report file is incomplete, ending in the middle of an XML tag. The file size in bytes is an exact multiple of 100.000.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

We have observed this recently when changing the source level of our project to java 8.
Bug seems to come from the fact that the `BufferedWriter` in `FileStringBuffer` is not flushed. We have observed that adding `bw.flush()` fixes the probles.
(https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/reporters/FileStringBuffer.java#L83)

**Comment by juherr** [comment]
Thanks for the report.

As you've already done all the job, why not proposing the fix into a pull request? :)
