### ISSUE TITLE
Recognize annotations on default methods in implemented interface

### ISSUE THREAD

**Issue by epkugelmass** [cbeust/testng#1220]
### TestNG Version

6.9.13.6
### Expected behavior

When TestNG is invoked on a class, it should invoke any concrete (default) methods annotated with `@Test` on any interface or super-interface, just as it currently does with concrete methods in abstract classes. 

This is a feature parity request for JUnit 5 (http://junit.org/junit5/docs/current/user-guide/#writing-tests-interface-default-methods)
### Actual behavior

Default method tests are not run
### Is the issue reproducible on runner?

Tested on shell, IDEA, and buck
### Test case sample

```
interface TestMixin {
@Test 
default void test1() { }
}

class TestClass implements TestMixin {
@Test
public void test2() { }
}
```

When testing TestClass, both test1 and test2 should run and pass. Currently, only test2 is invoked.

**Comment by navkast** [comment]
Seems like something important given the direction Java is headed (implementations inside interfaces).

**Comment by cbeust** [comment]
Sounds reasonable. I'm guessing default methods are not returned by the `getMethods()` call so we just need to find out which method from the reflection API will give us that.

**Comment by juherr** [comment]
The difficulty should not to find the test method, but to run it and test the feature. 

For the record : http://stackoverflow.com/questions/22614746/how-do-i-invoke-java-8-default-methods-refletively

**Comment by d1231** [comment]
Hi,

Trying the latest version (6.11), default methods which are annotated with `@Test` are indeed working.

But for other methods, annotated with annotation such as `@BeforeClass`, the default method are not working.

Looking inside the code I found that difference the test methods are found with: `org.testng.internal.reflect.ReflectionHelper#getLocalMethods`

which adds the default methods to the method list

where the other annotated methods are found inside:
`org.testng.internal.ClassHelper#getAvailableMethods`

with only a call to `clazz.getDeclatedMethods()` which doesn't take into account the default methods.

If it's ok, I would like to submit a pull request which replace the call inside getAvailableMethods from 
`clazz.getDeclaredMethods()`
to
`getLocalMethods()`
at the file : `org/testng/internal/ClassHelper.java:180`
and some tests verifying that default methods are working as expected.

Thanks

**Comment by krmahadevan** [comment]
@d1231 - We would be more than happy to accept a pull request.

Please refer [here](https://github.com/cbeust/testng/issues/1391#issuecomment-287666556) for learning how to contribute.

**Comment by d1231** [comment]
Hi, thanks for the reference. Good read.

Regarding the tests for this feature, it occurred to me that the project is written in java 7 while default methods are only from java 8. Any advice regarding how to test it?

**Comment by juherr** [comment]
@d1231 One option could be to have a specific folder for java8 test (ie: `src/test/java8`) and include it with gradle only if the current jdk version is >=8

**Comment by d1231** [comment]
Sound good.

I will hope to finish this in the next day or two.

**Comment by d1231** [comment]
I was busier than I thought in the last few days, but finally finished and made a pull request.

What I did in the end is creating another source "test8" that compiles with java 8 and run it's test after the test task.
I would love to hear if there might be a better way to this or any feedback about the solution as I'm gradle master. 

Thanks
