### ISSUE TITLE
Documentation is missing for -usedefaultlisteners CLI param

### ISSUE THREAD

**Issue by ericjang96** [cbeust/testng#1225]
### TestNG Version
6.9.10

### Expected behavior
Running testng.xml with the lines:
```
<listeners> 
    <listener class-name="org.testng.reporters.FailedReporter" />
    <listener class-name="org.testng.reporters.XMLReporter" />
</listeners>
```

should produce only those 2 reports in the output folder.

### Actual behavior
Running this suite only works in IntelliJ. Running the same suite through command line results in all of the default reports being written to the output folder.

### Is the issue reproductible on runner?

- [x] Shell

**Comment by juherr** [comment]
Thanks for the report.
What is the command line you run?
You are supposed to use `-usedefaultlisteners false` if you don't want default listeners.

**Comment by ericjang96** [comment]
I didn't know that I had to add that command. It works now, thank you! Could you add that to the documentation? That information doesn't seem to be on: http://testng.org/doc/documentation-main.html

**Comment by krmahadevan** [comment]
This now stands fixed and the documentation portal has been updated to include this information.
