### ISSUE TITLE
Swap invocation order between IExecutionListener implementation and report generation.

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1231]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Currently, implementations of `org.testng.IExecutionListener` are being executed before the report generation phase. 

### Actual behavior
Per the javadocs of `org.testng.IExecutionListener` the implementation will get a call back when TestNG run ends. But this is happening before the report generation phase instead of happening after the report generation phase. Can we have the order changed ?

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

No specific test case is required to simulate this behavior.
Suggesting that we change the order of invocation [here](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L1099-L1103).

From
```
    runExecutionListeners(false /* finish */);

    if(null != suiteRunners) {
      generateReports(suiteRunners);
    }
```

To
```
    if(null != suiteRunners) {
      generateReports(suiteRunners);
    }

    runExecutionListeners(false /* finish */);
```

This way, it will give end-users the capability to incorporate things such as "archive reports after they were generated into a different file system location".

Similarly we need to swap the invocation of [IExecutionListener](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L1092-L1093) before anything kicks in.

i.e., Change
```
    runSuiteAlterationListeners();
    runExecutionListeners(true /* start */);
```

To 
```
    runExecutionListeners(true /* start */);
    runSuiteAlterationListeners();
```

**Comment by krmahadevan** [comment]
@cbeust / @juherr - Please let me know your thoughts on this.

**Comment by juherr** [comment]
It depends on what is an execution for you: just the execution of tests (without reports) or the execution of testng itself (with reports).
The documentation is not clear enough because I understand `Invoked before the TestNG run starts` like "as soon as possible" but I understand `Invoked once all the suites have been run` as "after the run, before the report)". 

Which real life issue will the change fix?

BTW, I've no opinion about the change :)

**Comment by krmahadevan** [comment]
Thanks Julien for your inputs. I was in the same dilemma as well. But I
feel that if we move the IExecutionListener invocation after the report
generation phase, it would give the end-users to put the IExecutionListener
to a much more proper usage by housing all the clean-up after reporting and
can address a much more practical use case.

Thanks & Regards
Krishnan Mahadevan

**Comment by juherr** [comment]
Good point. So we must not forget to clarify the doc if/when the change will be done.

**Comment by krmahadevan** [comment]
Sure :)
I will also be curious to hear what @cbeust feels on this change.
I can go ahead and submit a PR if he is fine with the change.


Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/
My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by cbeust** [comment]
I can't think of anything bad that could come out of this and there's a small upside, so I'm fine with it.
