### ISSUE TITLE
Prevent TestNG from adding duplicate instances of the same listener

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1232]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Irrespective of whichever mechanisms that I use to add a listener to TestNG i.e., either via

- Service Loader (or)
- `@Listeners` annotation (or)
- `<listeners>` tag
- runners: surefire plugin, ant, cli, ...

TestNG must only register one listener instance to it.

### Actual behavior
Currently I can inject the same listener as multiple instances via each of the above cited 4 mechanisms, thus causing the same listener's implementation being invoked multiple times.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

There is no specific sample for this. Issue can be easily recreated by wiring the same listener through all the above mentioned mechanisms.

**Comment by juherr** [comment]
In fact, it depends on the listener but I can't remember the case I needed something different (@gjuillot do you?).

But first, we need exhaustive tests to check the current behavior to understand what will be the impacts of the change.

**Comment by krmahadevan** [comment]
@juherr - Thanks for your inputs. I would also be curious to understand a use-case wherein a user requires multiple instances of the same listener to be wired into the same instance of `TestNG`. 

So far I have been experiencing this as a problem (lets say I built a listener which implements `IInvokedMethodListener` wherein inside its `beforeInvocation()` a browser instance gets created for every `@Test` method whenever it sees a `@Browser` annotation. Duplicate instances of this listener ends up causing multiple browser instances getting created and thus causing unwanted confusions. To circumvent this, I had to build a custom `ListenerManager` implementation which resorts to having all the listeners register itself to it, and then within every method call of the listener, I end up adding a query to the listener manager to check if the listener method can be invoked on the instance. I kind of feel this is a lot of boiler plate code and it would be easier if `TestNG` maintained it as a map so that we can add the appropriate edit checks.

Also please note as part of #1230 we are already trying to ensure that atleast with `IReporter` implementations there are no duplicates (It already used a `set` and now we have changed it to start using a `Map`

> But first, we need exhaustive tests to check the current behavior to understand what will be the impacts of the change.

Can you please let me know what you are hinting at ? Are you looking for a test which maybe looks something like [this](https://github.com/cbeust/testng/pull/1233/files#diff-600cf991cda81c75a7ef8b7ec9589114) ? 

@cbeust - It would be great if you could also please help advise on this requirement.

**Comment by juherr** [comment]
> Can you please let me know what you are hinting at ? 

I'm looking for a global view of the current listener state (which one is called/instantiated, when/how many times/...).

Tests from https://github.com/cbeust/testng/pull/1093/ are doing a part of the job but I don't know if it is enough.

**Comment by juherr** [comment]
Ok, you got me! I mismatched things. Go ahead then! 😄

**Comment by krmahadevan** [comment]
Thanks Julien. I will work on submitting a pull request for this. 


Thanks & Regards

Krishnan Mahadevan






On Tue, Nov 8, 2016 at 6:44 PM +0530, "Julien Herr" <notifications@github.com> wrote:












Ok, you got me! I mismatched things. Go ahead then! 😄
