### ISSUE TITLE
IRetryAnalyzer : Not able to re-run failed tests when same tests are being run multiple times

### ISSUE THREAD

**Issue by ksmanoj** [cbeust/testng#1241]
### TestNG Version
> Note: only the latest version is supported

When the retry count is set to 1 from retry listener, From the below sample test, test2() method is run for the second time for Test with <test name="Test One"> (refer testng.xml below) where as when i invoke the same set of tests for the second time with <test name="Test Two">, test2() method is not run for the second time though it has failed.

### Expected behavior
Listeners are used to retry test failed tests.
Since test2() fails in first attempt, it should re-run test2() for <test name="Test One"> and <test name="Test Two">

### Actual behavior
Listeners are used to retry test failed tests.
test2() is re-runs for <test name="Test One"> where as for <test name="Test Two"> test2() fails the first time and it is not re-run for second time

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

I have implemented listener class as following : http://stackoverflow.com/questions/28208202/retry-failed-test-case-in-testng/36320794#36320794

Below is my test case

```java
import org.testng.Assert;
import org.testng.annotations.Test;
public class SampleTest {
	@BeforeTest
	public void setup(ITestContext context){
		System.out.println("inside setup.."+context.getCurrentXmlTest().getName());
	}
	
	@Test(priority=1)
	public void test1(){
		System.out.println("inside test1()...");
		Assert.assertTrue(true);
	}
	
	@Test(priority=2)
	public void test2(){
		System.out.println("inside test2()...");
		Assert.assertTrue(false);
	}
}
```

Below is my XML
```xml
<suite name="Test Suite" verbose="1">
	<test name="Test One">
		<classes> <class name="com.example.SampleTest" > </classes>
	</test>
	<test name="Test Two">
		<classes> <class name="com.example.SampleTest" > </classes>
	</test>
        <listeners> <listener class-name="com.example.RetryListener"/> </listeners>
</suite>
```

**Comment by juherr** [comment]
Thanks for the report. Could you share your `RetryListener` too?

**Comment by juherr** [comment]
Thanks for the report. Could you share you retry listener, the current behavior and the current one?

**Comment by ksmanoj** [comment]
Please find the attached ZIP file for listeners and sample test and the expected vs actual results below.

[testNG_Issue.zip](https://github.com/cbeust/testng/files/596542/testNG_Issue.zip)

Expected output : 
```
inside setup..Test One
inside test1()...
inside test2()...
Listener : retryCount : 0 || maxRetryCount : 1
Retrying test <test2> with status FAILURE for the 1 time(s).
inside test2()...
Listener : retryCount : 1 || maxRetryCount : 1

inside setup..Test Two
inside test1()...
inside test2()...
Listener : retryCount : 0 || maxRetryCount : 1
Retrying test <test2> with status FAILURE for the 1 time(s).
inside test2()...
Listener : retryCount : 1 || maxRetryCount : 1
```

Actual output : 
```
inside setup..Test One
inside test1()...
inside test2()...
Listener : retryCount : 0 || maxRetryCount : 1
Retrying test <test2> with status FAILURE for the 1 time(s).
inside test2()...
Listener : retryCount : 1 || maxRetryCount : 1

inside setup..Test Two
inside test1()...
inside test2()...
Listener : retryCount : 1 || maxRetryCount : 1
```

**Comment by juherr** [comment]
I think it could be already fixed by https://github.com/cbeust/testng/pull/1235
Could you try with the latest snapshot?

**Comment by ksmanoj** [comment]
I have tried with `6.9.14-SNAPSHOT` but i do not see the expected results. It is same as previous.

**Comment by juherr** [comment]
Currently, retry analyzers are initialized once by suite. I can't say if it is expected or if it is an issue.

An option could be to mix the retry analyzer with an ITestListener and reset the retry analyzer when a new test is run. But it is not working for the moment.

@cbeust What is your favorite solution? Having a new retry analyzer instance by `<test>` and/or be able to combine a retry analyzer with listeners (register the retry analyzer if it is a listener too)?

**Comment by ksmanoj** [comment]
@juherr Do we have a workaround for this situation? or this needs to be implemented in the core testNG?

**Comment by juherr** [comment]
@ksmanoj Yep, the following is supposed to work as expected.

```java
@Listeners(GitHub1241Sample.ResetRetryAnalyzer.class)
public class GitHub1241Sample {

    @Test(retryAnalyzer = MyRetry.class)
    public void test1() {
    }

    @Test(retryAnalyzer = MyRetry.class)
    public void test2() {
        Assert.fail();
    }

    public static class MyRetry implements IRetryAnalyzer {

        private int retryCount;
        private int maxRetryCount;

        public MyRetry() {
            reset();
        }

        public void reset() {
            retryCount = 0;
            maxRetryCount = 1;
        }

        @Override
        public boolean retry(ITestResult result) {
            if (retryCount < maxRetryCount) {
                retryCount++;
                return true;
            }
            return false;
        }
    }

    public static class ResetRetryAnalyzer extends TestListenerAdapter {

        private final List<IRetryAnalyzer> retryAnalyzers = new ArrayList<>();

        @Override
        public void onStart(ITestContext testContext) {
            retryAnalyzers.clear();
        }

        @Override
        public void onTestStart(ITestResult result) {
            IRetryAnalyzer retryAnalyzer = result.getMethod().getRetryAnalyzer();
            if (!retryAnalyzers.contains(retryAnalyzer)) {
                if (retryAnalyzer instanceof MyRetry) {
                    MyRetry retry = (MyRetry) retryAnalyzer;
                    retry.reset();
                    retryAnalyzers.add(retry);
                }
            }
        }
    }
}
```

```java
public class GitHub1241Test extends SimpleBaseTest {

    @Test
    public void test() {
        XmlSuite suite = createXmlSuite("Test Suite", "Test One", GitHub1241Sample.class);
        createXmlTest(suite, "Test Two", GitHub1241Sample.class);

        TestNG tng = create(suite);

        InvokedMethodNameListener listener = new InvokedMethodNameListener();
        tng.addListener((ITestNGListener) listener);

        tng.run();

        assertThat(listener.getInvokedMethodNames()).containsExactly(
                "test1", "test2", "test2",
                "test1", "test2", "test2"
        );
    }
}
```

@krmahadevan If you want to have a look at it and try to fix it, you already have the sample ;)

**Comment by cbeust** [comment]
Resetting the retry analyzer doesn't sound very good to me, but I don't really have a strong feeling overall. I'm under the impression that having different retry analyzers per suite is a bit overkill...

**Comment by juherr** [comment]
> I'm under the impression that having different retry analyzers per suite is a bit overkill...

I image the use case is something around selenium like having retry analyzer because it is an integration test of a website with a different browser by `<test>`.
In that case, I understand users want to have all tests retried for every browser and not only for the first which will fail.

BTW, I found a workaround (and then we can close the issue) but I think something could be improved.

**Comment by ksmanoj** [comment]
@juherr  In the above example `GitHub1241Sample` when i tried with thread count > 1 then the retry count does not seem to be matching. 

Scenario tried : 
`Retry count = 1 ; 
Thread count = 2`

Actual Output : 
`One of Test One or Test Two's test2 will be retried. `

**This works fine if the thread-count is 1**

Below is the xml .

    <suite name="Dummy2" verbose="1"  parallel = "tests" thread-count="2">

	<test name="Test One">
		<classes>
			<class name="com.testng.github.issue.GitHub1241Sample" />
		</classes>
	</test>
	
	<test name="Test Two">
		<classes>
			<class name="com.testng.github.issue.GitHub1241Sample" />
		</classes>
	</test>
    </suite>

**Comment by juherr** [comment]
It can't work in parallel because all different methods share the same retry analyzer instance (1 for `test1` and 1 for `test2`).
A solution could be to store `retryCount` and `maxRetryCount` according to their dedicated ITestContext: `Map<ITestContext, Counters>`.

**Comment by juherr** [comment]
@cbeust 
I think something is weird around `ITestNGMethod` because it mixes test model/description (static) and instance (dynamic).

> ITestNGMethod: Describes a TestNG annotated method and the instance on which it will be invoked. This interface is not meant to be implemented by users.

Is it expected that `ITestResult#getMethod()` is returning the same value in different `<test>` context?
Is it expected to have the same instance between different `<test>` or to have one instance by `<test>`?

**Comment by cbeust** [comment]
I think `ITestResult#getMethod()` could return the same method in different tests if it is indeed the same test method being run, otherwise it shouldn't.

**Comment by juherr** [comment]
@cbeust Ok, but what about its instance? The same instance in different `<test>` too, even if they are run in // ? Because currently, only one method means only one instance.

**Comment by Prasant-Sutaria** [comment]
@cbeust Any work around, for managing retry count per test case instead of suite level.

**Comment by SrinivasanTarget** [comment]
@juherr @cbeust Any update on this?

**Comment by nayakprashant** [comment]
Thanks a lot @juherr 
Spent entire day looking for the solution and finally found this link. It worked :+1:

**Comment by juherr** [comment]
Ping @krmahadevan If you want to have a look at it :)

**Comment by nayakprashant** [comment]
@juherr 
The solution provided by you worked for me. Thanks so much for the solution. :+1:
