### ISSUE TITLE
windows: serviceloader does not find any ITestNGListener

### ISSUE THREAD

**Issue by lukasj** [cbeust/testng#125]
[note: this issue happens only on windows]

follow http://testng.org/doc/documentation-main.html#listeners-service-loader

or

-clone current codebase on windows 7 (not sure if exact win version matters)
-set JAVA_HOME to some JDK 6 - I'm using JDK 6 u27
-run _ant clean dev_

on a machine running Windows 7

=> listener passed to TestNG through META-INF/services is not found, one has to use -listeners to get around this

also note that  _test.serviceloader.ServiceLoaderTest_ from TestNG codebase fails on windows (at least in my local environment)

**Comment by krmahadevan** [comment]
@juherr - I think we can close this issue off. I tried recreating this issue on Windows 8 with JDK8 and I can see the build passing. Maybe this issue is an old one.

**Comment by juherr** [comment]
@lukasj Thanks for the report but we made a lot of work since your report (ant -> maven -> gradle) and it is supposed to work now.

@krmahadevan Thanks!
