### ISSUE TITLE
Source files are without license headers

### ISSUE THREAD

**Issue by puntogil** [cbeust/testng#1255]
Hi

All java source files are without license headers.

Please, confirm the licensing of code and/or content/s, and add license headers

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance

Regards

**Comment by cbeust** [comment]
The license (Apache 2.0) can be found at the root of the project:

https://github.com/cbeust/testng/blob/master/LICENSE.txt
