### ISSUE TITLE
6.10 not properly in Maven central

### ISSUE THREAD

**Issue by ph-hs** [cbeust/testng#1261]
http://search.maven.org/#search%7Cga%7C1%7Ctestng

**Comment by cbeust** [comment]
This is what Bintray has been telling me each time I've tried to sync for several days now:

![image](https://cloud.githubusercontent.com/assets/92322/20901379/1f9820fc-bae7-11e6-8001-954989bcadad.png)

Seems I'm not the only one:

http://stackoverflow.com/questions/40972473/unnable-to-sync-jcenter-to-maven-central

**Comment by ph-hs** [comment]
https://issues.sonatype.org/browse/OSSRH might be the place to raise the ticket. My own blocked syncs in years gone by, were resolved there (former CodeHaus sync to 'central).

**Comment by cbeust** [comment]
Good news, looks like they fixed it and TestNG 6.10 should appear on Maven Central soon:

![image](https://cloud.githubusercontent.com/assets/92322/20941769/e0b794fa-bbac-11e6-96fc-b01c9599594e.png)
