### ISSUE TITLE
[Bug] JUnit Reporter includes redundant ignored methods

### ISSUE THREAD

**Issue by gdemecki** [cbeust/testng#1265]
### TestNG Version
6.10

### Expected behavior

In the JUnit xml report files I should see entries `<skipped/>` only for tests which have been marked with `@Test(enabled = false)`.

### Actual behavior

Now, in  JUnit xml report files I can see a plethora redundant `<skipped/>` entries. Each test report contain literally all methods which have been inherited from the parent test, executed once, and thus skipped by the TestNG for remaining inherited classes.

Whereas I believe that only methods annotated with a `@Test(enabled = false)` should appear in the JUnit report.

EDIT: it is even worse: in each and every report, there are entries for methods marked with `@Test(enabled = false)` which come from totally different classes and have nothing to do with the actual class (look at the `should_be_ignored` method in the example below).

### Is the issue reproductible on runner?

- [x ] Maven

### Test case sample

```java
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;

public abstract class ParentTest {

    @BeforeSuite
    public synchronized void startEverything() throws Exception {
    }

    @AfterSuite
    public synchronized void shutdownContainer() throws Exception {
    }
}
```
FirstTest.java:

```java
import static org.testng.Assert.*;
import org.testng.annotations.Test;

public class FirstTest extends ParentTest {

    @Test
    public void should_pass() {
        assertEquals("abc", "abc");
    }

    @Test(enabled = false)
    public void should_be_ignored() {
        assertEquals("abcd", "abc");
    }
}
```

SecondTest.java:

```java
public class SecondTest extends ParentTest {

    @Test
    public void should_pass_second() {
        assertEquals("abc", "abc");
    }
}
```

ThirdTest.java:

```java
public class ThirdTest extends ParentTest {

    @Test
    public void should_pass_third() {
        assertEquals("abc", "abc");
    }
}
```

JUnit output is extremely weird:

junitreports/TEST-abc.FirstTest.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="abc.FirstTest" tests="1" time="0.001" ignored="5" failures="0" timestamp="08 Dec 2016 10:53:32 GMT" skipped="0" hostname="EPPLGDAW0188" errors="0">
  <testcase name="should_pass" time="0.001" classname="abc.FirstTest"/>
  <testcase name="shutdownContainer" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- shutdownContainer -->
  <testcase name="shutdownContainer" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- shutdownContainer -->
  <testcase name="startEverything" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- startEverything -->
  <testcase name="startEverything" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- startEverything -->
  <testcase name="should_be_ignored" classname="abc.FirstTest">
    <skipped/>
  </testcase> <!-- should_be_ignored -->
</testsuite> <!-- abc.FirstTest -->
```

junitreports/TEST-abc.SecondTest.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="abc.SecondTest" tests="1" time="0.005" ignored="5" failures="0" timestamp="08 Dec 2016 10:53:32 GMT" skipped="0" hostname="EPPLGDAW0188" errors="0">
  <testcase name="should_pass_second" time="0.005" classname="abc.SecondTest"/>
  <testcase name="shutdownContainer" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- shutdownContainer -->
  <testcase name="shutdownContainer" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- shutdownContainer -->
  <testcase name="startEverything" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- startEverything -->
  <testcase name="startEverything" classname="abc.ParentTest">
    <skipped/>
  </testcase> <!-- startEverything -->
  <testcase name="should_be_ignored" classname="abc.FirstTest">
    <skipped/>
  </testcase> <!-- should_be_ignored -->
</testsuite> <!-- abc.SecondTest -->
```

`junitreports/TEST-abc.ThirdTest.xml ` is the same, to I skip it here.

It seems to me that this whole mess is a result of implementing the issue #1211 .

Kind regards,
Greg

**Comment by juherr** [comment]
Ping @krmahadevan

**Comment by krmahadevan** [comment]
@juherr  :) This was the next one in the radar :)

**Comment by krmahadevan** [comment]
btw @juherr it would be good if I could assign issues to my name.. That way you would also have a clarity on what I am working on. Any way I can do that ? I cant seem to be able to find that option.

**Comment by juherr** [comment]
> btw @juherr it would be good if I could assign issues to my name.. That way you would also have a clarity on what I am working on. Any way I can do that ? I cant seem to be able to find that option.

You need have rights on the repository and only @cbeust can manage them :)

**Comment by krmahadevan** [comment]
@juherr - Oh ok.. Thanks for letting me know.

@gdemecki 

I have a fix locally ready. But before I raise a PR out of it, I just want to make sure that I understand your expectations. 

Assuming I used the same java classes you shared and then executed them via a suite xml file which looks like below

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1265_Suite" parallel="false" verbose="2">
    <test name="1265">
        <classes>
            <class name="org.rationale.emotions.github.issue1265.FirstTest"/>
            <class name="org.rationale.emotions.github.issue1265.SecondTest"/>
            <class name="org.rationale.emotions.github.issue1265.ThirdTest"/>
        </classes>
    </test>
</suite>

```

Please let me know if the below xmls is what you expect to see as a report ?

`cat target/surefire-reports/junitreports/TEST-org.rationale.emotions.github.issue1265.FirstTest.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="MacBook-Pro.local" name="org.rationale.emotions.github.issue1265.FirstTest" tests="2" failures="0" timestamp="08 Dec 2016 16:57:22 GMT" time="0.002" errors="0">
  <testcase name="should_pass" time="0.002" classname="org.rationale.emotions.github.issue1265.FirstTest"/>
  <testcase name="should_be_ignored" classname="org.rationale.emotions.github.issue1265.FirstTest">
    <skipped/>
  </testcase> <!-- should_be_ignored -->
```

`cat target/surefire-reports/junitreports/TEST-org.rationale.emotions.github.issue1265.SecondTest.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MacBook-Pro.local" name="org.rationale.emotions.github.issue1265.SecondTest" tests="1" failures="0" timestamp="08 Dec 2016 16:57:22 GMT" time="0.000" errors="0">
  <testcase name="should_pass_second" time="0.000" classname="org.rationale.emotions.github.issue1265.SecondTest"/>
</testsuite> <!-- org.rationale.emotions.github.issue1265.SecondTest -->
```

`cat target/surefire-reports/junitreports/TEST-org.rationale.emotions.github.issue1265.ThirdTest.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MacBook-Pro.local" name="org.rationale.emotions.github.issue1265.ThirdTest" tests="1" failures="0" timestamp="08 Dec 2016 16:57:22 GMT" time="0.000" errors="0">
  <testcase name="should_pass_third" time="0.000" classname="org.rationale.emotions.github.issue1265.ThirdTest"/>
</testsuite> <!-- org.rationale.emotions.github.issue1265.ThirdTest -->
```

**Comment by cbeust** [comment]
@juherr @krmahadevan I have no problems making you both managers so you can assign issues and do more management things but I can't find anything to that effect in the github interface...

**Comment by krmahadevan** [comment]
@cbeust - Do you think the following would work ?

* Add me and @juherr as [collaborators](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) to the testng repository from [here](https://github.com/cbeust/testng/settings/collaboration) 
* lock down `master` branch as a `protected branch` from [here](https://github.com/cbeust/testng/settings/branches ) 

[Here's](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/) some documentation I found related to `protected branches`.

**Comment by krmahadevan** [comment]
@gdemecki - I have gone ahead and raised a Pull Request which satisfies the output as I shared [here](https://github.com/cbeust/testng/issues/1265#issuecomment-265794315)

@juherr FYI.. (Just ensuring that you are aware of this conversation)

**Comment by gdemecki** [comment]
@krmahadevan looks fine for me. Thanks.
