### ISSUE TITLE
[Bug] JUnit Reporter produces a wrong number of total test methods

### ISSUE THREAD

**Issue by gdemecki** [cbeust/testng#1266]
### TestNG Version
6.10

### Expected behavior

Attribute `tests` inside `<testsuite>` element should also count ignored methods in the current class.

<testsuite name="com.netadmin.service.UserSearchServiceTest" tests="4" time="0.174" ignored="1" failures="1" skipped="0" errors="1"  timestamp="..." hostname="..." >

### Actual behavior

Now, in JUnit xml report file, attribute `tests` doesn't reflect the true amount of `<testcase >` elements in the file. Because I think number of disabled tests is not included.

### Is the issue reproducible on runner?

- [ x] Maven

### Test case sample

```java
 @Test
 public void should_pass() {
     assertEquals("abc", "abc");
 }

 @Test(enabled = false)
 public void should_be_ignored() {
     assertEquals("abcd", "abc");
 }
```

should result in:
```xml
<testsuite name="SomeTest" tests="2"  skipped="1" errors="0" ...
```
but now is:
```xml
<testsuite name="SomeTest" tests="1" ignored="1"  skipped="0" errors="0" ...
```

Moreover: there should NOT be any `ignored=` parameter. JUnit already has a parameter for this purpose and it is called `skipped`. So please remove the `ignored` attribute from the `<testsuite>` element and use a `skipped` attribute instead.

Regards

**Comment by krmahadevan** [comment]
@gdemecki 

I used the same example that you shared. Here's how the xml would look like (the one that resides under here) after my fix. 

```
 ➭ tree junitreports/
junitreports/
└── TEST-org.rationale.emotions.junit.MyTestcase.xml
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="MacBook-Pro.local" name="org.rationale.emotions.junit.MyTestcase" tests="2" failures="0" timestamp="08 Dec 2016 13:36:41 GMT" time="0.007" errors="0">
  <testcase name="should_pass" time="0.007" classname="org.rationale.emotions.junit.MyTestcase"/>
  <testcase name="should_be_ignored" classname="org.rationale.emotions.junit.MyTestcase">
    <skipped/>
  </testcase> <!-- should_be_ignored -->
</testsuite> <!-- org.rationale.emotions.junit.MyTestcase -->
```

**Comment by gdemecki** [comment]
@krmahadevan thanks, the above xml looks fine.
