### ISSUE TITLE
Parallel (methods) execution with dependsOn running in unexpected order

### ISSUE THREAD

**Issue by kreinholt** [cbeust/testng#1287]
Stackoverflow reference here: http://stackoverflow.com/questions/41253297

I'm trying to run tests with parallel methods. Method3 is not waiting for method1 to complete. It appears to wait for method2 to complete, but I'm not sure why.
### TestNG Version
6.10
### Expected behavior
Output should be 
```
Starting method1
Starting method2
Ending method2
Ending method1
Starting method3
Ending method3
```
### Actual behavior
Output is:
```
Starting method1
Starting method2
Ending method2
Starting method3
Ending method3
Ending method1
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
public class TestClass {
    @Test(groups = { "groupA" })
    public void method1() throws InterruptedException {
        System.out.println("Starting method1");
        Thread.sleep(1000 * 10); // wait 10 seconds
        System.out.println("Ending method1");
    }
    @Test(groups = { "groupB" })
    public void method2() throws InterruptedException {
        System.out.println("Starting method2");
        Thread.sleep(1000 * 2); // wait 2 seconds
        System.out.println("Ending method2");
    }
    @Test(groups = "groupB", dependsOnGroups = { "groupA" })
    public void method3() throws InterruptedException {
        System.out.println("Starting method3");
        Thread.sleep(1000 * 2); // wait 2 seconds
        System.out.println("Ending method3");
    }
}
```
testng.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" parallel="methods" thread-count="5">
    <test name="Test">
        <classes>
            <class name="com.testngGroup.TestClass"></class>
        </classes>
    </test>
</suite>
```

**Comment by juherr** [comment]
Thanks for the report. Could you explain us do you run the class? Which options from the eclipse plugin?

**Comment by kreinholt** [comment]
I ran it by right clicking the testng.xml -> run as -> testNG Suite. I also ran it using maven from the command line with the same results.

I did however find that the bug was introduced in version 6.9.13.5. 6.9.13.4 and below work as expected.

**Comment by juherr** [comment]
I'm surprised because it is supposed to be the same code base for all `6.9.13.x`.

**Comment by kreinholt** [comment]
Looks like it's due to this commit: https://github.com/cbeust/testng/commit/d51b2b1672090234e3b216e6d8ae7ea265e63955

I think it might be an issue with the getFreeNodes function within DynamicGraph. It is returning method3 as a free node because it is the lowest priority even though it has a dependency that has not been fulfilled yet.

**Comment by juherr** [comment]
Good catch ! :+1: I supposed it comes from it.

Feel free to propose a fix and/or a test if you find something else :)

**Comment by egglestonbd** [comment]
The following simple project with java 8 can be executed which will exhibit the failure:  https://github.com/egglestonbd/testng-test  
Simply clone the project and execute `mvn verify`.  Changing to version 6.9.11, does not show the issue.

**Comment by juherr** [comment]
In fact, TestNG is supposed to wait for the **end** of the method before running a dependent method.
The issue comes from https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/DynamicGraph.java#L104-L111 where, sometimes, we ignore a dependency and run a method.

I've already a wip fix for the issue but it generates important performance issues for the moment.

**Comment by jatheisenii** [comment]
Any planned release for this fix yet?

**Comment by cbeust** [comment]
The tests are clean and the change log looks big enough.

I think we're ready for 6.11. @juherr @krmahadevan, any objections?

**Comment by krmahadevan** [comment]
@cbeust none from me.

**Comment by juherr** [comment]
@cbeust We can make a release, but I won't fix this specific issue because it is not fixed yet. I worked on it but I don't have a fix for the moment (and less free time).

**Comment by cbeust** [comment]
@juherr Noted. Leaving this issue open then.

**Comment by cbeust** [comment]
Leaving a note for myself and future fixers: this is an important issue which we should fix as soon as possible.

**Comment by juherr** [comment]
@cbeust A fix is ongoing with #1290

**Comment by jatheisenii** [comment]
Looks like this is said to be in current and not in 6.11 but above it was said to be on plan for 6.11.  Is it in 6.11?  If not, when is a new release going to include it?

**Comment by juherr** [comment]
@jatheisenii Not yet planned but you can ask for it on the mailing list :)
