### ISSUE TITLE
testng-failed.xml includes setup and tearDown (before and after annotations) of passed tests

### ISSUE THREAD

**Issue by praveen133t** [cbeust/testng#1297]
### TestNG Version
6.10

### Expected behavior
testng-failed.xml should only include before and after annotation and `@test` of failed test class

### Actual behavior
testng-failed.xml includes setup and tearDown (before and after annotations) of passed tests

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
public class FailedReporterTest1 {
	@BeforeTest
	public void setup() {
	}
	@Test
	public void newTest1() {
		System.out.println("In the first test.....");
	}
	@AfterTest
	public void tearDown() {
		System.out.println("Done...1");
	}
}
```

```java
public class FailedReporterTest2 {

	@BeforeTest
	public void setup() {
	}
	@Test
	public void newTest2() {
		System.out.println("In the second test.....");
		Assert.fail();
	}
	@AfterTest
	public void tearDown() {
		System.out.println("Done...2");
	}

}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="failedReporterTestSuite">
	<test name="failedReporterTest">
		<classes>
			<class name="com.testng.playground.tests.FailedReporterTest1" />
			<class name="com.testng.playground.tests.FailedReporterTest2" />
		</classes>
	</test>
</suite>
```

**Generated testng-failed.xml :** 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" name="Failed suite [failedReporterTestSuite]">
  <test name="failedReporterTest(failed)">
    <classes>
      <class name="com.testng.playground.tests.FailedReporterTest1">
        <methods>
          <include name="tearDown"/>
          <include name="setup"/>
        </methods>
      </class> <!-- com.testng.playground.tests.FailedReporterTest1 -->
      <class name="com.testng.playground.tests.FailedReporterTest2">
        <methods>
          <include name="setup"/>
          <include name="newTest2"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- com.testng.playground.tests.FailedReporterTest2 -->
    </classes>
  </test> <!-- failedReporterTest(failed) -->
</suite> <!-- Failed suite [failedReporterTestSuite] -->
```

**Comment by praveen133t** [comment]
[https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/reporters/FailedReporter.java#L153](url) ---> was not getting all the tests in one of the older testng versions. But now it's getting all the tests. Is that how it's supposed to be?

**Comment by krmahadevan** [comment]
@praveen133t - I don't think this is an issue.
Your FailedReporterTest1 is declared as below

```java
public class FailedReporterTest1 {
	@BeforeTest
	public void setup() {
	}
	@Test
	public void newTest1() {
		System.out.println("In the first test.....");
	}
	@AfterTest
	public void tearDown() {
		System.out.println("Done...1");
	}
}
```

And in your suite xml file, you have included this class as part of the same `<test>` tag.
So the `@BeforeTest` and `@AfterTest` are bound to be executed for any failed test classes that are part of the same `<test>` tag which explains why you are seeing

```xml
 <class name="com.testng.playground.tests.FailedReporterTest1">
        <methods>
          <include name="tearDown"/>
          <include name="setup"/>
        </methods>
      </class> <!-- com.testng.playground.tests.FailedReporterTest1 -->
```
Remember  that `@BeforeTest` are going to be executed for all the `@Test` methods that are part of the same `<test>` tag.

The only time when this would be an issue is when you use `@BeforeClass` and `@AfterClass` within `FailedReporterTest1` and that gets referred to in your `testng-failed.xml`

**Comment by dsankouski** [comment]
Passed configuration methods appear in testng-failed.xml, when failure was after passed test. See [unit test](https://github.com/cbeust/testng/pull/2620)

**Comment by juherr** [comment]
@dsankouski Configuration methods used by the failure tests are included because we need them if we want to rerun failing tests. #2618 fix it and didn't break tests from #1326. What is the expected behavior?

**Comment by dsankouski** [comment]
btw, I found this by accident, because test _testExclusionOfPassedConfigsInvolvingGroupsAtTestLevel_ creates suite with package, and it seems  test run order is undefined in this case. So test is flickering.

**Comment by krmahadevan** [comment]
@dsankouski 

> No passed tests should appear in testng-failed.xml

This is not true. If a test has a `dependsOnMethods` or `dependsOnGroups` and if that test failed, then the upstream dependencies need to be re-run too for this test to be re-evaluated no ? In that case, the upstream method should appear in the `testng-failed.xml` irrespective of whether it passed or not.

**Comment by dsankouski** [comment]
Ok, let's rephrase it like: `No passed tests should appear in testng-failed.xml unless they depends on failed tests`.
I think, `dependsOn` cases needs it's own tests.

**Comment by krmahadevan** [comment]
@dsankouski 

I would just say `All pre-requistes for a failed test case should be present in the testng-failed.xml`

Here pre-requisite can be :

* Method level, class level configurations as applicable
* test level and suite level configuration methods (These are absolutely needed) 
* Upstream `@Test` methods upon which this failed test method `dependsOn`
