### ISSUE TITLE
Assert equals for map of byte arrays is broken

### ISSUE THREAD

**Issue by Randgalt** [cbeust/testng#1300]
### TestNG Version
6.10

### Expected behavior
given: `Map<String, byte[]>` Assert.assertEquals() should do a deep compare

### Actual behavior
It appears to be doing an ID compare on the byte arrays

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample

```
            Map<String, byte[]> m1 = new HashMap<>();
            m1.put("1", "test".getBytes());
            Map<String, byte[]> m2 = new HashMap<>();
            m2.put("1", "test".getBytes());
            Assert.assertEquals(m1, m2);      
```

This worked as expected in 6.8.8

**Comment by juherr** [comment]
The behavior changed with #870
And the related test is there https://github.com/cbeust/testng/blob/master/src/test/java/test/asserttests/ArrayEqualityAssertTest.java#L88

**Comment by Randgalt** [comment]
In that case it would be nice to have an Assert.assertEqualsDeep() or something. I was very surprised that working tests started failing when I updated to the latest version.

**Comment by juherr** [comment]
Sure. Maybe could you propose something? :)
