### ISSUE TITLE
Getting error The method getEscapeHtml() is undefined for the type Reporter

### ISSUE THREAD

**Issue by rishabh-hs** [cbeust/testng#1310]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@rishabh-hs - The method has been there for atleast 5 years now. Please see [here](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/Reporter.java#L68-L70)

Can you please add more information on what you are doing to trigger this error ? You have not included any information related to that.

**Comment by krmahadevan** [comment]
No answer from the user. Closing this issue. Please re-open if the problem persists.
