### ISSUE TITLE
query: any pointers to easy issues to fix

### ISSUE THREAD

**Issue by p00j4** [cbeust/testng#1312]
i'm willing to contribute to the project. However start is the difficult phase for newbies like me. It would be great help if can we have "easy" label tagged to few real easy issues to start with.

**Comment by juherr** [comment]
Done! We will just have to determine if the fix could be easy or not and that's not always easy :p

**Comment by p00j4** [comment]
very true @juherr , I understand and second your thoughts on it. 
`
probably as an example, docs updation related issues might fall in easy category because in the same process to find out right content or links, I might learn the complete flow of the feature of this beautiful tool.
`
Thank You, 
eager for the notifier :D

if ( len(getListOfOpenIssues([fix-easy](https://github.com/cbeust/testng/labels/fix-easy)) ) > 0){
   notify("yay! time for stop excusing yourself and raise PR");
}
