### ISSUE TITLE
ITestResult#getInstance() method returns null for IConfigurationListener

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1319]
### TestNG Version
6.10

### Expected behavior
Not null

### Actual behavior
Null

### Test case sample
```java
@Listeners(Listener.class)
public class Tests {

    @Test
    public void test1() {
        System.out.println("test 1");
    }

    @AfterTest
    public void after(){
        System.out.println("After test");
    }
}
```

```java
public class Listener implements IConfigurationListener {

    public void onConfigurationSuccess(ITestResult itr) {
        System.out.println("Conf result: " + itr.getInstance()); // <- should not be null here
        System.out.println("Conf status: " + itr.getStatus());
    }

    public void onConfigurationFailure(ITestResult itr) {
    }

    public void onConfigurationSkip(ITestResult itr) {
    }
}
```

From: http://stackoverflow.com/q/41998960/4234729

**Comment by krmahadevan** [comment]
@juherr - I been off for quite a while :) I will pick this up and see if I can raise a PR on this.

**Comment by juherr** [comment]
Ok, great! 👍 

@cbeust Could you gives more rights to @krmahadevan? I'm not able to assign him issues. I suppose it only works for `Collaborator`. Or if it works, maybe you can provide some rights to the `@testng-team/testng` team, I've just added him into.
