### ISSUE TITLE
Specifying a listener will disable @BeforeMethod annotation to be considered

### ISSUE THREAD

**Issue by artgo** [cbeust/testng#1325]
### TestNG Version
6.10
### Expected behavior
Create an integration test class MyTestIT and create a setup() method annotated with ```@BeforeMethod(alwaysRun = true)```
When test is executed by maven-failsafe-plugin, setup method is executed before every test.

Now create any implementation of ITestListener interface and specify it in configuration properties of maven-failsafe-plugin.

Both ITestListener implementation AND method marked with ```@BeforeMethod(alwaysRun = true)``` are executed.

### Actual behavior
ITestListener implementation is executed BUT method marked with ```@BeforeMethod(alwaysRun = true)``` is NOT.

Note: changing useDefaultListeners parameter does not change anything. And it is supposed to be true by default anyway

### Is the issue reproducible on runner?
Reproducible 100% of the time.

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```java
@Test
public class SomeIT {
	@BeforeMethod(alwaysRun = true)
	public void setup() {
           System.out.println("This is setup");
        }

        public void testMe() {
            assert(true);
        }
}

public class TestListener implements ITestListener {
     // ...
}
```

maven:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>2.19.1</version>
    <configuration>
       <properties>
         <property>
           <name>listener</name>
           <value>com.somecompany.TestListener</value>
         </property>
      </properties>
    </configuration>
    <executions>
       <execution>
           <goals>
             <goal>integration-test</goal>
             <goal>verify</goal>
           </goals>
         </execution>
     </executions>
</plugin>
```

**Comment by juherr** [comment]
Strange. Do you reproduce the issue in a IDE like eclipse or intellij?

**Comment by artgo** [comment]
Of course! And yes, I also was surprised - couldn't find in the code why that would be...

**Comment by juherr** [comment]
Strange, because I'm not able to reproduce the issue on my side with intellij.

Could you try with `6.10.1-SNAPSHOT`?
Maybe you can share the full project too?

**Comment by artgo** [comment]
OK, when I was creating a sample project and couldn't reproduce it anymore...
I guess something might have cached in my system causing it to behave weirdly. I guess we can close this bug.
If I ever be able to find conditions to reproduce I will request to re-open it again with reference to repro repository.

**Comment by juherr** [comment]
Ok, thanks for the update :)
