### ISSUE TITLE
Use GitHub as an up2date source for the documentation

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1329]
[ ] Configure github custom domain (testng.org): https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
[ ] Configure DNS www.testng.org: CNAME to cbeust.github.io
[ ] Configure DNS testng.org: A to 192.30.252.153 + A to 192.30.252.154 (from https://help.github.com/articles/setting-up-an-apex-domain/)

https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

**Comment by cbeust** [comment]
Why would I want to do this?

**Comment by juherr** [comment]
Since I succeed to remove PHP pages and local Javadoc, there is no more dependency on a 3rd party server or post production things.
I think everything is static and run as expected now (check http://cbeust.github.io/testng/)

So, it will avoid manual update of the site and it will reduce the time between a doc contribution and its deployment (== less work for you, just merge).

**Comment by cbeust** [comment]
Ah so just updating the doc and pushing it will update the web site?

That'd be nice. I'm a bit nervous mucking with the DNS though but I'll look into it.

**Comment by juherr** [comment]
I got it.
But take your time.

A first step could be use a temp subdomain like gh.testng.com but the configuration is not exactly the same than root or www.

**Comment by juherr** [comment]
@cbeust Did you already change something? Some issue on the documentation ("table of content" or http://testng.org/doc/dtd/) on  http://testng.org/doc/documentation-main.html

**Comment by cbeust** [comment]
Indeed, the js and css files are no longer there. I don't see them on the testng-team either, weird. Looking.

**Comment by juherr** [comment]
Strange! But maybe it is the perfect time to move to github :p

**Comment by cbeust** [comment]
Fixed:  https://github.com/testng-team/testng-team.github.io/commit/9b948ae3e088141aa79cab8c2c1f652bc8efde49

Not sure how this ever worked, these files were never checked in the testng-team repo.

As for github,  I don't think I'm going to do this: I'm not comfortable tying the documentation to an external service, even if that service is github.

**Comment by juherr** [comment]
No prob. But in that case, why not removing the folder from here and remove the duplication?

**Comment by cbeust** [comment]
Indeed. Done.
