### ISSUE TITLE
Make EmailableReport name configurable

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1332]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Emailable report file name should be configurable.

### Actual behavior
Its currently hard-coded to emailable-report.html

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Question arises from this SO post : http://stackoverflow.com/a/42188021/679824

**Comment by krmahadevan** [comment]
@juherr - I saw your response on SO http://stackoverflow.com/a/42188021/679824
Just curious do you think we should support this via a JVM argument (or) do you think it should go via the TestNG command line parameters ? 

The JVM argument would be an easy change. Just thought I would get your inputs on this.

**Comment by juherr** [comment]
@krmahadevan Why not both? :)

I think it is not documented but you can pass params to reporters from command line or xml thanks to https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/ReporterConfig.java (used in `TestNG` class)
But JVM args could be used too and override params.
