### ISSUE TITLE
BeforeClass doesn't work when BeforeGroup run on Class with excluded tests

### ISSUE THREAD

**Issue by pavetok** [cbeust/testng#1338]
### TestNG Version
6.10

### Expected behavior
BeforeClass should be invoked when BeforeGroup run on Class with excluded tests

### Actual behavior
BeforeClass doesn't work when BeforeGroup run on Class with excluded tests

### Is the issue reproductible on runner?

- [x] Maven

### Test case sample
Minimal [case](https://github.com/pavetok/testng-group-setup)

**Comment by juherr** [comment]
Thanks for the report but I'm not sure to understand.
Configuration methods are only run if a test method exists in their own scope.
According to your sample, what is the expected/actual behavior? Which are the methods run?

**Comment by pavetok** [comment]
Thanks for the response.
Try to run my sample. You will get NPE:

    $ mvn clean test
    ...
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running TestSuite
    Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.305 sec <<< FAILURE! - in TestSuite
    groupSetUp(com.pavetok.testng_group_setup.SecondTest)  Time elapsed: 0.237 sec  <<< FAILURE!
    java.lang.NullPointerException

    Results :

    Failed tests:
      SecondTest>BaseTest.groupSetUp:16 » NullPointer

    Tests run: 2, Failures: 1, Errors: 0, Skipped: 1

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2.336 s
    [INFO] Finished at: 2017-02-22T08:12:49+03:00
    [INFO] Final Memory: 15M/169M
    [INFO] ------------------------------------------------------------------------

Is NPE correct behavior in that case?
It seems correct behavior could be "first test passed and second test omitted":

    $ mvn clean test
    ...
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running TestSuite
    Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.26 sec - in TestSuite

    Results :

    Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2.059 s
    [INFO] Finished at: 2017-02-22T08:19:26+03:00
    [INFO] Final Memory: 15M/195M
    [INFO] ------------------------------------------------------------------------

**Comment by juherr** [comment]
`@BeforeGroups` is run before `@BeforeClass` because a group may have many classes. 
And that's why you have the NPE.

**Comment by pavetok** [comment]
`@BeforeGroups` was invoked on the `SecondTest` instance because it first in the `testng.xml`.
Would it be possible to invoke `@BeforeGroups` on the `FisrtTest` instance?

**Comment by juherr** [comment]
Ok, I got it! I agree the behavior looks stupid but the answer is currently no ;)

Imagine you have a `ThirdTest` with a `@Test(groups = {"group2"})`: on which instance should we invoke the `@BeforeGroups`? `SecondTest` instance or `ThirdTest` instance?
And as you understood, TestNG takes the first instance it finds for the moment.

BTW, we are open to any better ideas :)

**Comment by pavetok** [comment]
Yet another couple of questions.

> @BeforeGroups is run before @BeforeClass because a group may have many classes.

If you look at the report, `@BeforeGroups` is run after `FirstTest` instance `@BeforeClass`. Why?
![report](https://cloud.githubusercontent.com/assets/912757/23211160/b864bac6-f911-11e6-9bad-019b221a2702.png)

> TestNG takes the first instance it finds for the moment.

If TestNG executes methods in `FisrtTest` instance, why it can't invoke `@BeforeGroups` on that instance?

**Comment by juherr** [comment]
I've just had a look with my IDE this time and I was wrong: before group is run AFTER before class.

@cbeust Could you explain why? Is it expected? As a group is defined on a `<test>`, I think it is more logic to have `@BeforeTest` -> `@BeforeGroup` -> `@BeforeClass`. WDYT?

@pavetok I reproduced the issue and we can expect to have "the first instance involved in the suite" instead of "the first instance"

**Comment by cbeust** [comment]
@juherr Sounds reasonable, but there might be reasons I forgot. If the
behavior is easy to change, go ahead and change it and let's see what tests
break...


-- 
Cédric
