### ISSUE TITLE
ClassHelper.isOverridden() takes a lot of CPU time

### ISSUE THREAD

**Issue by nathanila** [cbeust/testng#1339]
### TestNG Version
6.10

### Expected behavior
The method should run faster

### Actual behavior
The method consumes 38.9% of the time in my profile.

### Is the issue reproductible on runner?

- [?] Shell
- [?] Maven
- [?] Gradle
- [?] Ant
- [X] Eclipse
- [?] IntelliJ
- [?] NetBeans

I only ran the tests from Eclipse.  However, I would imagine this is reproducible on any of these since this is a core method.

### Test case sample
No can do.  I have a lot of tests.

The method `ClassHelper.isOverridden()` goes through all of the methods in the collectedMethods Set.  Instead, use a `Map<String, List<Method>` in which the key is the method name.  This will drastically reduce the number of methods to search through.  This change will upgrade the algorithm from O(n^2) to O(n).

**Comment by juherr** [comment]
It looks you already have the solution. Why not proposing it in a pull request ?

**Comment by nathanila** [comment]
I don't have a solution.  I just have a suggestion on how to optimize the code.

**Comment by juherr** [comment]
Ok. Does the suggestion fix the issue as you expect? Could you try? Without a significative test case it will be difficult for us to reproduce ans fix.
