### ISSUE TITLE
Abstract Class implementation shows weird behaviour. Abstract method called twice.

### ISSUE THREAD

**Issue by bit-cracker007** [cbeust/testng#1340]
### TestNG Version
> 6.10

### Expected behaviour
The abstract method implementation of a abstract class should not get called without calling in some test method of implementing test class. This is only happening when the child class has defined TestGroup on it else it works as expected.

### Actual behaviour
The overridden method is automatically called after BeforeSuite and also after getting called in BeforeClass. I just want the method to be called only once and that too when it gets called from BeforeClass.

**Note:** It works fine when I remove `@Test(groups = {"abc"})` i.e Test Group annotation.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
**Failure case:**
```java
@Slf4j
public abstract class AbstractTest {
    /**
     * This method will be executed before the first test declared within the test element is invoked.
     */
    @BeforeSuite(alwaysRun = true)
    public void beforeSuite() {
        log.info("beforeSuite...");
    }

    /**
     * Download input address file relevant for the test in progress.
     */
    public abstract void download();
}

@Slf4j
@Test(groups = {"abc"})
public final class MyTest extends AbstractTest {

        @BeforeClass
        public void init() {
             log.info("BeforeClass...");
             download();
        }

       @Test(enabled = true)
       public void TestFirst() {
            log.info("TestFirst...");
       }

       @Override
       public void download() {
            log.info("Downloading....");
       }
}
```

**Actual output(Wrong):**
```
BeforeSuite...
BeforeClass...
Downloading...
Downloading...
TestFirst...
```

**Expected(Correct output) :**
```
BeforeSuite...
BeforeClass...
Downloading...
TestFirst...
```

**XML file:**
```xml
<!DOCTYPE suite SYSTEM "http://beust.com/testng/testng-1.0.dtd" >
<suite name="TestPackage">
    <test name="TestFirst">
        <classes>
            <class name="com.tests.MyTest" />
        </classes>
    </test>
</suite>
```

**Ant testNG run:**
```xml
<testng outputdir="${bp:package-build-root}/brazil-reports-from-tests"
            failureproperty="tests.failed" haltonfailure="true" useDefaultListeners="false" verbose="2">
            <xmlfileset dir="${testng.directory}" includes="lol.xml" />
</testng>
```

**Comment by juherr** [comment]
Thanks for the report.

According to your sample, it looks the `download` method is seen as a test method.
If you set a `@Test` on the class, it means all methods of the class are test methods (including `download`).
I suppose it is what you are doing with `@Test(groups = {"abc"})`.

**Comment by krmahadevan** [comment]
@juherr - This is just a hunch. Would it have anything to do with the `@Slf4j` annotation causing the logger to duplicate logging ?

The reason why I ask is because, when I removed off the logger and replaced it with a `System.out.println` here's what my output looked like (which matches what @bit-cracker007 is expecting as well)

```
[TestNG] Running:
  /Users/krmahadevan/githome/PlayGround/testbed/src/test/resources/1340.xml
beforeSuite...
[TestRunner] Starting executor for test 1340_Tests with time out:2147483647 milliseconds.
BeforeClass...
Downloading....
TestFirst...
PASSED: TestFirst
```

**Comment by juherr** [comment]
@krmahadevan I think so too. If you want to test with `@Slf4j`, it comes from https://projectlombok.org/features/Log.html

**Comment by juherr** [comment]
@bit-cracker007 Could tell us what is your slf4j logger engine and could you share its configuration?

**Comment by bit-cracker007** [comment]
@juherr 👍 
The 1st reason was correct. I had already figured out.

**Comment by juherr** [comment]
:+1: for @krmahadevan instead ;)
