### ISSUE TITLE
[TestNG] TestNG Assert messages not getting published.

### ISSUE THREAD

**Issue by bit-cracker007** [cbeust/testng#1358]
### TestNG Version
6.10

# Issue
I have few assert conditions for test success/failure verdict like:
`Assert.assertTrue(condition, "message"); // Assert comes from org.testng.assert`
Here, on failure "message" is not getting published.

**I am using Slf4j logger built on top of log4j2.**

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

**Comment by juherr** [comment]
What is the current string?

**Comment by krmahadevan** [comment]
No response from the user. Closing this issue. Please comment if this is still a problem
