### ISSUE TITLE
Custom parser is not used for .xml

### ISSUE THREAD

**Issue by ChristiKh** [cbeust/testng#1365]
Custom parser for .xml test script does not work - the default parser is processed. For other then .xml extension custom parser works fine.
Reproduced here:
https://github.com/ChristiKh/testng-custom-parser-failure

**Comment by juherr** [comment]
The feature was not designed to allow to override the default xml/yaml parsers.
It just allows adding new kind of formats.

Could you tell us what are you trying to do and why? :)

**Comment by ChristiKh** [comment]
Hi, I want to have an .xml test script of my own format.

**Comment by ChristiKh** [comment]
Thank you!

**Comment by cbeust** [comment]
Like @juherr said, this fix is still not going to allow you to do what you are asking for (having your own custom XML format). You'd have to write some transformation layer that will take your input and turn it into `XmlSuite`, `XmlTest`, etc...

**Comment by ChristiKh** [comment]
Hi Cedric,
yes, my custom parser returns XmlSuite built from xml data
thank you
