### ISSUE TITLE
Is there any way to stop further test execution when a test fails?

### ISSUE THREAD

**Issue by prasanta-biswas** [cbeust/testng#1368]

**Comment by amedvedjev** [comment]
@Test(dependsOnMethods = "testThatFails")

**Comment by prasanta-biswas** [comment]
This is not what I meant. Suppose there are 100 test methods, and for some condition any test method out of 100 fails, then I want to stop execution of tests. The failed method is not a particular method.

**Comment by juherr** [comment]
Please, use StackOverflow or the mailing list for questions.
