### ISSUE TITLE
dependency broken: com:beust:jcommander:1.64

### ISSUE THREAD

**Issue by onacit** [cbeust/testng#1369]
### TestNG Version
6.11

### Expected behavior
`com.beust:jcommander:1.64` should be available on the central.

### Actual behavior
mvn can't find `com.beust:jcommander:1.64`.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@cbeust - Can you please advise on whether `jcommander` is published to Maven central ?

**Comment by juherr** [comment]
@onacit We don't use any new jcommander api, so you can force a previous JCommander version.

**Comment by Stephan202** [comment]
(Though that solution is not so nice when [`RequireUpperBoundDeps`](https://maven.apache.org/enforcer/apidocs/org/apache/maven/plugins/enforcer/RequireUpperBoundDeps.html) is enabled. :).)

**Comment by juherr** [comment]
@Stephan202 Sure! Another option: you can add jcenter as maven repository where every jcommander versions are available. 
https://bintray.com/cbeust/maven/jcommander

**Comment by marcmyers** [comment]
@juherr is basically asking you to add this to your pom.xml
```
<repositories>
<repository>
            <id>jcenter</id>
            <url>https://dl.bintray.com/cbeust/maven/</url>
        </repository>
    </repositories>
```

**Comment by juherr** [comment]
Yes, or even the whole https://jcenter.bintray.com/

**Comment by cbeust** [comment]
I just synced JCommander 1.64 to Maven Central, it should appear there shortly. Please reopen if it doesn't.

**Comment by cbeust** [comment]
And as @juherr suggested, you might as well add JCenter as another repo in your build files anyway.

**Comment by Stephan202** [comment]
@cbeust, thanks for syncing! Can confirm it worked.

(Indeed, I could have our company Nexus proxy to an additional repo, but prefer to keep its configuration as simple as possible. So thanks again!)

**Comment by Christopher-Hasanali** [comment]
I'm getting below error now. Is this related?

Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.beust:jcommander:jar:1.71 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by cbeust** [comment]
This is very weird because I double checked that TestNG 6.13.1 depends on [JCommander 1.72](https://repo.maven.apache.org/maven2/org/testng/testng/6.13.1/testng-6.13.1.pom):

```
<dependency>
    <groupId>com.beust</groupId>
    <artifactId>jcommander</artifactId>
    <version>1.72</version>
</dependency>
```
What version of TestNG are you using?

**Comment by Christopher-Hasanali** [comment]
1.72 worked for me. 1.71 version failed with "mvn clean && mvn compile" too.
