### ISSUE TITLE
testng.org/testng-1.0.dtd should have 'none' instead of 'false' for property 'parallel'

### ISSUE THREAD

**Issue by PeterGabriel2** [cbeust/testng#1383]
### TestNG Version
latest version

### Expected behavior

"http://testng.org/testng-1.0.dtd" should be updated or new version of dtd should be published.

### Actual behavior

warning in console:

[XmlSuite] [WARN] 'parallel' value 'false' is deprecated, default value will be used instead: 'none'.:

### Is the issue reproductible on runner?

- [x] Maven
- [x] IntelliJ

### Test case sample
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="demo"
       parallel="false"><!-- this should be 'none' correctly but in dtd is not now -->
</suite>
```

**Comment by juherr** [comment]
In fact, TestNG is using the DTD included in the jar and that's why it complains when you pass a "wrong" suite file but not your xml editor which points to the old dtd.

@cbeust Could you add a http redirection from http://testng.org/testng-1.0.dtd to https://raw.githubusercontent.com/cbeust/testng/master/src/main/resources/testng-1.0.dtd ?

**Comment by juherr** [comment]
@cbeust In fact, if you synch the site from https://github.com/testng-team/testng-team.github.io it should do the job: https://github.com/testng-team/testng-team.github.io/blob/master/.htaccess#L2

**Comment by cbeust** [comment]
The redirect is in place, but note that the best way to access the DTD is to go to http://testng.org/dtd which displays the correct DTD but with highlighting.

**Comment by juherr** [comment]
@cbeust your link is not good because it uses the old DTD file via the old php page. Instead, it should be http://testng.org/doc/dtd/ but the index.html file is missing.

**Comment by cbeust** [comment]
Try http://beust.com/dtd/ again.

**Comment by juherr** [comment]
Still not ok: the redirection points to `http://testng.org/testng-1.0.dtd.php/` => 404

And http://testng.org/testng-1.0.dtd.php:

> <b>Warning</b>:  file_get_contents(doc/testng-1.0.dtd) [<a href="function.file-get-contents">function.file-get-contents</a>]: failed to open stream: No such file or directory in <b>/nfs/c07/h01/mnt/98219/domains/testng.org/html/testng-1.0.dtd.php</b> on line <b>42</b><br>

**Comment by juherr** [comment]
And you should remove `http://beust.com/dtd/`(or redirect it to http://testng.org/dtd/)  which is really out-to-date ;)

**Comment by cbeust** [comment]
Ok, latest changes:

- Removed http://beust.com/dtd
- http://testng.org/dtd points to a colorized version of the DTD
- http://testng.org/testng-1.0.dtd points to the actual DTD

Better?

**Comment by juherr** [comment]
Looks good now 👍
