### ISSUE TITLE
Custom annotation inside @Test annotation 

### ISSUE THREAD

**Issue by jawlitkp** [cbeust/testng#1387]
Hello,

is there any way i can create custom annotation which i can call inside `@Test` annotation method.my purpose is to log each step description in page object framework 

below is what i want to achive,i want to create `@Step` annotation which i can call inside `@Test` annotation and print all steps details in the report

```java
	@Test
	public void loginTest() {
		
		@Step("Launching webiste")		
		atg.launchConcept();
		
		@Step("Executing precondition if user is already logged in then log out")		
		atg.preCondition().mlogOutFromAccount();
		
		@Step("Navigate to login page")		
		atg.sTopMenu().mNavigateToAccountLoginAsNonAuthUser();

		@Step("Login to account")		
		atg.pLoginPage().mLoginToAccount();

	}	
```

**Comment by krmahadevan** [comment]
@jawlitkp - I don't think you can do this yet. This is not a limitation of TestNG but this is yet to be supported in JDK.

But here's one way in which you can get this done 

* Put the `@Step` annotation on all the methods definitions (for e.g., on `launchConcept()`)
* For your logging purposes, I think you can use AOP wherein you define point-cuts and have your advice inspect if there was an annotation and if yes, log them.
* You can then clean up your `@Test` method of all the `@Step` annotations.

**Comment by juherr** [comment]
As @krmahadevan said, what you are asking for is not possible in Java.

But you should have a look at a BDD framework like:

- JBehave - http://jbehave.org/
- Cucumber - http://cukes.info/
- Concordion - http://www.concordion.org
