### ISSUE TITLE
http://testng.org/ returns 403 Forbidden

### ISSUE THREAD

**Issue by rhencke** [cbeust/testng#1392]
I wasn't sure where else to report this.

If you visit http://testng.org/, it currently shows:

```
Forbidden

You don't have permission to access / on this server.

Apache/2.2.22 Server at testng.org Port 80
```

However, links _within_ testng.org seem to be alright.  For example http://testng.org/doc/ works just fine.

**Comment by krmahadevan** [comment]
ping @cbeust - I can confirm this is a problem.

**Comment by cbeust** [comment]
Should be fixed, thanks for the notice!
