### ISSUE TITLE
Optimize ClassHelper.getAvailableMethods()

### ISSUE THREAD

**Issue by nathanila** [cbeust/testng#1394]
### TestNG Version
6.11

### Actual behavior
`ClassHelper.getAvailableMethods()` calls `ClassHelper.extractMethods()` which calls `ClassHelper.isOverridden()`.  The numerous calls to `ClassHelper.isOverridden()` amounts to 12 out of 25 seconds to startup TestNG.

Normally, I wouldn't care about 12 seconds since I have bigger fish to catch.  However, 25 seconds every time I need to test some small change is painful.

### Expected behavior
I first noticed that `isOverridden()` is being called with methods for `java.lang.Object`.  I figured `Object`'s methods would never be a test method and hence I figured one could optimize `extractMethods()` by adding the following code at the top of the method...

    if (Object.class.equals(clazz))
       return(Collections.emptyMap());

I then realized that we could optimize `getAvailableMethods()` instead.  The `while` statement could be changed from...

      while (null != parent)

... into ...

      while ((null != parent) && (!Object.class.equals(parent)))

This solves the problem.  I leave it to the TestNG team to figure out if this optimization is safe.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I tried creating a reproducing test case but getting a similar profile proved to be very difficult.

**Comment by krmahadevan** [comment]
@nathanila - Sometime you had raised #1339  and I had fixed it as part of this [Pull Request](https://github.com/cbeust/testng/pull/1349/files) 

Can you please confirm, if this bug takes into account the fix for #1339 ?

**Comment by nathanila** [comment]
Yes, this issue takes into account the fix for #1339.  I am running with the fix for #1339 (i.e. TestNG 6.11).  Now that #1339 is fixed, issue #1394 can be discovered.

**Without** #1339 fixed, `isOverridden()` is being called for every method and would examine all other discovered methods so far.  **With** #1339 fixed, `isOverridden()` is now doing a lot of work on the `java.lang.Object` methods.  **With #1394** fixed in my hack, `isOverridden()` doesn't show up in the profiler any more and the total start time for TestNG drops.

**Comment by juherr** [comment]
As `parent` is only `null` for Object, we can remove the null check:

```java
if (clazz != Object.class) {
  Class<?> parent = clazz.getSuperclass();
  while (parent != Object.class) {
    ...
  }
}
```

**Comment by krmahadevan** [comment]
@juherr 

> As parent is only null for Object, we can remove the null check:

Partially true. If the method gets called with `org.testng.internal.ClassHelper.getAvailableMethods(Object.class)` (This is happening in the codebase when [TestNGClassFinder.isTestNGClass()](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestNGClassFinder.java#L217-L255) recursively climbs up the hierarchy and invokes the `getAvailableMethods` with a base class.
It currently doesn't have any edit check to stop querying the `Object.class` (maybe we should add it there as well i.e., change
`for (cls = c; cls != null; cls = cls.getSuperclass()) {`
to
`for (cls = c; cls != null && !Object.class.equals(cls); cls = cls.getSuperclass()) {`
