### ISSUE TITLE
2nd call to same test method in testng.xml ignored

### ISSUE THREAD

**Issue by Brokeneggs** [cbeust/testng#1395]
It seems that testng won't allow to run the same method or class in one test execution multiple times .For example, the last test below which is a second run of the clickBrowserTab1 `@Test`-annotated method is completely ignored.  After Tab2 clicked, i need to rerun clickBrowserTab1. I understand that, as a workaround, I could have two differently-named `@Test` methods which each call the method to click Tab1, but that is ugly. 

```xml
<test name="CommonReportingTests" preserve-order="true" > 
    <classes> 
        <class name="jason.test.Main"> 
                       <methods> 
                            <include name="clickBrowserTab1" /> 
                            <include name="clickBrowserTab2" /> 
                            <include name="clickBrowserTab1" / > 
                     </methods> 
       </class>
    </classes>
</test>
```

**Comment by krmahadevan** [comment]
@Brokeneggs - You should look at using the xml file as way to select methods within a single class but adhering to the rules of Java. If you were to be asked to do this directly in Java, how would you be able to do this ? i.e., lets assume that there was no xml support, and you had to build a test class in java, how would that class look like ? Whatever would be in that Java class is what is expected to be available as support in the xml as well.
At-least that's my understanding. 

ping @juherr / @cbeust - Your thoughts ?

**Comment by juherr** [comment]
As @krmahadevan said, the suite file is used to select the tests to run and their order (a bit), not to describe the test logic/workflow (which is describe by the java tests).
