### ISSUE TITLE
Latest testNG not running from command line

### ISSUE THREAD

**Issue by santhosh12992** [cbeust/testng#1399]
### TestNG Version - 6.11 (org.testng.eclipse_6.11.0.201703011520) I downloaded it on 7/March/2017. It is supposed to be the latest version at that time
> Note: only the latest version is supported

### Expected behavior
Tried to integrate with jenkins. So, thought of triggering the xml from command line manually. I had set the class path correctly but the Test cases were failed. But  it was running from eclipse. If we execute a @test which doesn't have any selenium related stuff(driver is not initiated) it was getting passed i  command line.  

I uninstalled java, eclipse appium and installed it again. Checked the environment variables again Everything was fine. Later i found the solution. viola!!!!!

I uninstalled the current latest version of testng and installed the previous version of it(org.testng.eclipse_6.8.6.20141201_2240). Updated the testng.jar in the lib folder of project home directory and to my surprise  testng is able to run with appium/Selenium now successfully.

### Actual behavior
Only java related codes are running. For selenium related commands, @test is getting failed.

### Is the issue reproductible on runner?
Yes, it is.
- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans
1. Install the latest testng in eclipse.
2. Create a sample test case such as launching a browser.
3. Create a xml and run from eclipse.
4. After adding lib and setting class path run the xml from command. The same test case passed in eclipse will fail now.

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cbeust** [comment]
I don't understand the problem, can you show some code or something that fails?

It sounds like you solved that problem?

**Comment by juherr** [comment]
@santhosh12992 Feel free to reopen the issue if you have more details to share.
