### ISSUE TITLE
Feature: Fail a passing test

### ISSUE THREAD

**Issue by fzakaria** [cbeust/testng#1401]
I would like to do something similar to the `successPercentage` & `invocationCount`  through a `IRetryAnalyzer`.

The problem I have now faced is that it is difficult/impossible to mark a test as failed if it has succeeded.

Within `Invoker.java` the retrying of tasks is done through the `FailureContext` which is never passed downstream to any listeners or transformers.

I see `Invoker#handleInvocationResults`uses IRetryAnalyzer to determine retry but there is no way prior to this point to change the ITestResult.

Would love if the listeners were called perhaps before `handleInvocationResults` or it had its own interface `IInvocationResultHandler`

**Comment by juherr** [comment]
Have you already try to change the `ITestResult` status from an [`IInvokedMethodListener#afterInvocation`](https://jitpack.io/com/github/cbeust/testng/master-6.11-g76c52be-79/javadoc/org/testng/IInvokedMethodListener.html#afterInvocation-org.testng.IInvokedMethod-org.testng.ITestResult-)?

**Comment by fzakaria** [comment]
Changing the test status is not sufficient.
You need to modify the 'fail' object which is already set by the time the listeners are invoked.

A simple solution to my problem would be if the `IRetryAnalyzer` was called irrespective of test result.
(Right now it is called only for failure)

**Comment by krmahadevan** [comment]
https://github.com/cbeust/testng/issues/1525 addresses something similar and there's a good chance that it may have addressed this problem. Please retry this using the latest snapshot version of TestNG and re-open if the issue persists along with a sample that can be used to reproduce the problem.
