### ISSUE TITLE
Feature: TestNG Reporting, how to quickly identify Retry-d Tests?

### ISSUE THREAD

**Issue by bipo1980** [cbeust/testng#1402]
### TestNG Version
> 6.11

### Expected behavior
Hello: When a `@Test fails` and a `Retry` happens, is there a direct way in TestNG to distinguish between a Test that has been Retried and a test that has not been retried - such as through a NG context method or variable?

- Case 1: If a Test not been retried then the `1st test` is a test that has not been retried.
- Case 2: If a Test that has been retried 2 times then the `3rd test` is a test that has not been retried.

An option to do this: [http://www.seleniumeasy.com/testng-tutorials/retry-listener-failed-tests-count-update](http://www.seleniumeasy.com/testng-tutorials/retry-listener-failed-tests-count-update).

### Actual behavior
Currently, there is currently no easy way to determine a retried test. 
Reference: [http://stackoverflow.com/questions/43069150](http://stackoverflow.com/questions/43069150)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by juherr** [comment]
Thanks for the report! :)

**Comment by krmahadevan** [comment]
@bipo1980 - You should be able to do this very easily today. The idea is to basically query the retry analyzer instance associated with a test and check its retry count. If you found a value greater than zero then that method was retried. Here's a sample that shows what I am talking about

```java
package com.rationaleemotions.stackoverflow;

import org.testng.Assert;
import org.testng.IRetryAnalyzer;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

@Listeners(IdentifyRetriedTests.IdentifyingListener.class)
public class IdentifyRetriedTests {
    private static AtomicInteger counter = new AtomicInteger(0);
    private static AtomicInteger anotherCounter = new AtomicInteger(0);

    @Test(retryAnalyzer = Retry.class)
    public void hello() {
        if (counter.incrementAndGet() == 3) {
            Assert.assertTrue(true);
        } else {
            Assert.fail();
        }
    }

    @Test(retryAnalyzer = Retry.class)
    public void anotherHello() {
        if (anotherCounter.incrementAndGet() == 5) {
            Assert.assertTrue(true);
        } else {
            Assert.fail();
        }
    }

    @Test(retryAnalyzer = Retry.class)
    public void bye() {
        Assert.assertTrue(true);
    }

    public static class IdentifyingListener extends TestListenerAdapter {

        @Override
        public void onTestSuccess(ITestResult tr) {
            IRetryAnalyzer retry = tr.getMethod().getRetryAnalyzer();
            if (retry instanceof Retry) {
                //Check if the retry analyser's retry count was greater than zero. If yes, then its a retried method
                if (((Retry) retry).getRetryCount() > 0) {
                    tr.setAttribute("retried", true);
                }
            }
        }

        @Override
        public void onFinish(ITestContext testContext) {
            Set<ITestResult> results = new HashSet<>();
            results.addAll(testContext.getFailedTests().getAllResults());
            results.addAll(testContext.getPassedTests().getAllResults());
            for (ITestResult result : results) {
                if (result.getAttribute("retried") != null) {
                    System.err.println(result.getMethod().getMethodName() + "() was retried");
                }
            }
        }
    }

    public static class Retry implements IRetryAnalyzer {
        private AtomicInteger retryCount = new AtomicInteger(0);
        private static int maxRetryCount = 10;

        public boolean retry(ITestResult result) {
            return retryCount.getAndIncrement() < maxRetryCount;
        }

        int getRetryCount() {
            return retryCount.get();
        }
    }
}

```

**Comment by AJ-72** [comment]
@krmahadevan while this would work, it would be better to have this in the emailable html report itself. Probably a different section for retried tests and an updated summary table that shows the pass and fail count based on final results.

**Comment by krmahadevan** [comment]
@AJ-72 - Sure. Would you be willing to help submit a pull request for this change ? We should be able to help vet it out and get it merged for you.

**Comment by AJ-72** [comment]
@krmahadevan Yeah am checking that emailable report. Is it emailablereport2 that I should check?

**Comment by krmahadevan** [comment]
@AJ-72 - Currently its based on a condition. See [here](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L946-L960)
So you may have to check both.
