### ISSUE TITLE
Can't get test case name when use testng6.11

### ISSUE THREAD

**Issue by debbyzang** [cbeust/testng#1408]
### TestNG Version
> Note: only the latest version is supported
testng6.11
### Expected behavior
Get all test case name (test method simple name)
![2](https://cloud.githubusercontent.com/assets/21197863/24745853/b91f5152-1ae9-11e7-9431-ac6e45ee201e.png)

### Actual behavior
Can't get method name
![default](https://cloud.githubusercontent.com/assets/21197863/24745826/9b7be8f4-1ae9-11e7-9132-824a0a656d9a.png)

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

import org.testng.annotations.Test;
step 
add @test before class ,then run with testng , actual result see pic in [Actual behavior]

then I tried testng6.8.5, the issue never happened

```java
@Test
public class Testaa {

//	@Test
	public void test01(){
		
	}
	
	public void test02(){}
	
	public void test03(){}
}
```

**Comment by juherr** [comment]
Thanks for the report. Could you try the behavior with 6.9.9 and 6.9.10?

If it is working with 6.9.9 and failing with 6.9.10, then it means the reporter is not using the appropriate method to get the test name.

**Comment by debbyzang** [comment]
It is working with 6.9.9 and failing with 6.9.10

**Comment by juherr** [comment]
Thanks for the feedback. I think your issue is related to #922. Could you try again with 6.11 and the latest maven surefire plugin?
Or maybe you can share a full runnable project?

**Comment by debbyzang** [comment]
after I update testng 6.11 plugin, I try again with 6.11, 6.9.10, 6.9.9, test case name display. I think it maybe for not use the lastest plugin, should I closed this issue?

**Comment by juherr** [comment]
Yes, I close as it is fixed :)
