### ISSUE TITLE
regular expression in "dependsOnMethods" not work

### ISSUE THREAD

**Issue by missedone** [cbeust/testng#141]
hi, cbeust

I read the user guide

> Both dependsOnGroups and dependsOnMethods accept regular expressions as parameters.

so i tried to use regular expression in "dependsOnMethods", for example:

``` java

@Test
public void testMethod1() {...};

@Test
public void testMethod2() {...};

@Test (dependsOnMethods="test.*")
public void testMethod3() {...};
```

but i got an error below:

org.testng.TestNGException: 
example.testMethod3() depends on nonexistent method **test.***
    at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:98)

though the workaround is quit straightforward, just let you know this issue.
thanks

**Comment by syntastical** [comment]
yeah this still seems broken.
I'm getting Method "DatadogLogTests.asdf()[pri:0, instance:XXX]" depends on nonexistent method "Test_C[0-9]{7}"

And my test looks like
```
    @Test(dependsOnMethods = "Test_C[0-9]{7}")
    public void asdf() {
        System.out.println("test");
    }
    @Test
    public void Test_C6390323() { ... }
```

**Comment by syntastical** [comment]
@krmahadevan yeah we're on 7.6.1.  The problem seems to be around https://github.com/cbeust/testng/blob/cd85bcb7afebbaecd2299cbc72632e27f89a441b/testng-core/src/main/java/org/testng/DependencyMap.java#L56

When it gets here "methodName" is the regex `Test_C[0-9]{7}` and it cannot match the dependencies in the List.

**Comment by krmahadevan** [comment]
@syntastical - Would you be willing to help file a pull request for this (Since you seem to have spent time and effort in debugging this)? We can help you get it reviewed/merged.
