### ISSUE TITLE
TestNG parallel settings are confusing when using @DataProvider and @Factory

### ISSUE THREAD

**Issue by mping** [cbeust/testng#1413]
We have a data provider and a factory for generating test data and tests respectively, and also have the following xml:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="UI Tests" verbose="4" parallel="classes" data-provider-thread-count="2" thread-count="2" group-by-instances="false">

    <test name="Test">
        <classes>
            <class name="some.Factory"/>
        </classes>
    </test>
</suite>
```

The factory just returns a `[Test]`. The test is as follows:

```
class Test {
...

 @Test
 void testMethod1() {...}

 @Test(dependsOnMethods="testMethod1"
  void testMethod2() {...}

}
```

### TestNG Version
latest

### Expected behavior
That the ```Test``` class runs only two tests at a time

### Actual behavior
The test limit is not respected, lots of tests start running.
**If** I squash both tests onto a single `@Test`, it works fine.

**Comment by juherr** [comment]
Could you try the SNAPSHOT version and tell us if you still see the issue?

**Comment by krmahadevan** [comment]
@mping - I tried reproducing this with TestNG 6.11 but I am not able to reproduce this issue.

Here's what I have

```java
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class MyFactory {
    @Factory
    public static Object[] produce() {
        return new Object[]{
                new TestInstance(),
                new TestInstance(),
                new TestInstance(),
                new TestInstance(),
                new TestInstance()
        };
    }

    public static class TestInstance {
        @Test
        void testMethod1() {
            System.err.println(debug("TestMethod1"));
        }

        private String debug(String methodName) {
            return methodName + " running on Thread " + Thread.currentThread().getId() +
                    " with instance as " + this;
        }

        @Test(dependsOnMethods = "testMethod1")
        void testMethod2() {
            System.err.println(debug("TestMethod2"));
        }

    }
}
```

Here's the suite xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="My Suite" verbose="2" parallel="instances" thread-count="2">
    <test name="Some Workflow Tests">
        <classes>
            <class name="com.rationaleemotions.github.issue1413.MyFactory"/>
        </classes>
    </test>
</suite>
```

Here's the output
```
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...
TestMethod1 running on Thread 11 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@4cb2c100
TestMethod1 running on Thread 12 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@3f2a3a5
TestMethod1 running on Thread 12 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@614c5515
TestMethod1 running on Thread 11 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@60addb54
TestMethod1 running on Thread 12 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@6fb554cc
TestMethod2 running on Thread 11 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@4cb2c100
TestMethod2 running on Thread 12 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@3f2a3a5
TestMethod2 running on Thread 11 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@614c5515
TestMethod2 running on Thread 12 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@60addb54
TestMethod2 running on Thread 11 with instance as com.rationaleemotions.github.issue1413.MyFactory$TestInstance@6fb554cc

===============================================
My Suite
Total tests run: 10, Failures: 0, Skips: 0
===============================================
```

As you can see, the thread id is only toggling between 11 and 12, indicating that TestNG is indeed honoring the thread pool size of 2.

**Comment by juherr** [comment]
@krmahadevan You don't have any data provider in your sample. It could make the difference.

**Comment by juherr** [comment]
Maybe it is the same issue than #326

**Comment by krmahadevan** [comment]
@juherr 

> You don't have any data provider in your sample. It could make the difference.

I checked. And it doesn't make any difference.

I agree with you. I think this is perhaps more related to #326

**Comment by tejaschitale123** [comment]
Can we use data-provider-thread-count="2" without using testNG.xml?
I mean to say as we invoke @Dataprovider on method can we specify data-provider-thread-count="2" there?
Some thing like this
    @Test(dataProvider = "ExcelDataProvider", groups = { "abc" },data-provider-thread-count="2" )

**Comment by krmahadevan** [comment]
AFAIK, you can't do that, because the "@Test" annotation does not have the
attribute. By default it would be set to 10 which can be changed via the
TestNG attribute "data-provider-thread-count" in your suite file.

Alternatively if you are using Maven and relying on surefire plugin to run
your tests, you can add something like below:

<properties>
  <name>dataproviderthreadcount</name>
  <value>2</value>
</properties>

>

**Comment by krmahadevan** [comment]
Closing this issue since there is no response from the OP. Also #326 is also fixed.
