### ISSUE TITLE
Retry Configuration Failures

### ISSUE THREAD

**Issue by dhirenmudgil** [cbeust/testng#1415]
### TestNG Version
6.11
### Expected behavior
When we run any test which has some configurations, for example one of my test requires token from Facebook. So i have a configuration (`@BeforeMethod`) which creates a test user on Facebook and return a token which is then used by a test method.

Sometimes network call fails to get token from Facebook, for the same implemented retry analyzer but it does not retry configuration (`@BeforeMethod`).

### Actual behavior
If something fails in configuration also, it should retry configuration as well. 

### Is the issue reproductible on runner?

- [x] Shell
- [x] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
``` java
private FacebookTestUser facebookTestUser;
private String token;

    @BeforeMethod(alwaysRun = true)
    public void setUp() throws Exception {
        facebookTestUser = new FacebookTestUser();
        token = facebookTestUser.geToken();
    }
    @Test
    public void verifyStatusCode() throws Exception {
        assertThat(FACEBOOK_ACCESS_TOKEN_NULL,token,is(notNullValue()));
    } 
```

**Comment by dhirenmudgil** [comment]
@juherr @krmahadevan : Please look into this issue.

**Comment by dhirenmudgil** [comment]
Sorry by mistake.

**Comment by krmahadevan** [comment]
@juherr @cbeust - What do you think on this one ? Should configuration methods have retry capabilities as well ?

**Comment by cbeust** [comment]
I'm concerned this is a very rare case and that adding this functionality to TestNG would significantly increase its complexity.

If you ever need to write a configuration method that needs some retry mechanism, I think you should just implement it yourself in that method.
