### ISSUE TITLE
listener won't execute when run test case with param -Dtest

### ISSUE THREAD

**Issue by toutoudnf** [cbeust/testng#1416]
### TestNG Version
testng version: 6.9.10
maven-surefire-plugin version:2.19.1

i execute my test cases by command:
`mvn clean test -Dtestng=local-testng.xml -Dtest=demo.maven.TestCase#test`
and local-testng.xml show as bellows:
```
    <listeners>
        <listener class-name="demo.maven.ISuiteListenerImplTest" />
        <listener class-name="demo.maven.InvokeMethodListenerImplTest" />
    </listeners>
    <test name="local">
        <packages>
            <package name="demo.maven.*">
            </package>
        </packages>
    </test>
```
### Expected behavior

listener in local-testng.xml will be triggerred.

### Actual behavior

listener in local-testng.xml dose not be triggerred.

### Is the issue reproductible on runner?

- [ √] Maven

### Test case sample
TestCase:
```
package demo.maven;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

@Test
public class TestCase {

    Logger logger = LoggerFactory.getLogger(getClass());

    @BeforeClass
    public void before() {
        logger.info("before");
    }

    @Test
    public void test() {
        logger.info("test");
    }

    @AfterClass
    public void after() {
        logger.info("after");
    }
}
```

**Comment by juherr** [comment]
According to the surefire documentation, it is the expected behavior:

> This parameter overrides the includes/excludes parameters, and the TestNG suiteXmlFiles parameter.

https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test

Surefire allows you to configure listeners too, check https://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html

BTW, if you really want to take listeners from the suite into account with the `-Dtest` param, something will have to be done in surefire.
Ping @Tibor17

**Comment by Tibor17** [comment]
I think the `test` parameter and `includes/excludes+suite xml` are exclusive.
AFAIK we do not perform filtering in suites xml.
Tell me if Method Selector is filter applicable to suites xml within TestNG.
https://github.com/apache/maven-surefire/blob/master/surefire-providers/surefire-testng-utils/src/main/java/org/apache/maven/surefire/testng/utils/MethodSelector.java

**Comment by Tibor17** [comment]
We passed `local-testng.xml` to TestNG instance, nothing more.
The class-path should contain the listeners.

**Comment by juherr** [comment]
@Tibor17 Yes, it is the current behavior. But @toutoudnf would like to have some information from `suite xml` when `test` is used, a kind of merge. I'm not sure it is a good idea but who knows?

@toutoudnf Another way to declare listener is service loader: http://testng.org/doc/documentation-main.html#listeners-service-loader

**Comment by Tibor17** [comment]
It cannot be merged because the `test` is filter.
Not sure if applicable to suites xml or the xml is completely ignored. I would say it is ignored.

**Comment by juherr** [comment]
@Tibor17 Are you saying that surefire is providing the `suite xml` even when `test` is used?

**Comment by Tibor17** [comment]
I think it is opposite. The class path is given and `test` is a filter if `test` property presents non-empty. AT least this is in JUnit providers and should be the same in testng provider too.

**Comment by juherr** [comment]
@Tibor17 Ok, we will check it when we will fix #1406 (which is a similar issue). Thanks for the clarification.

**Comment by toutoudnf** [comment]
thanks a lot  @juherr :)
but there exists one case in my CI system:
- test configuration is complicated
- more than one scripts will use this configuration, such as a CI system need run different type of test cases
if i need to specify listener on each script instead of write them in testng.xml, it will make maintaince of scripts become a hard work :( 
so is there any better solution for the case above?
thanks in advance:)

**Comment by krmahadevan** [comment]
@toutoudnf - Here's one way of executing listeners at will 

First you can build a listener like below

```java
import org.apache.commons.io.FileUtils;
import org.testng.IExecutionListener;
import org.testng.ISuite;
import org.testng.ISuiteListener;
import org.testng.ITestNGListener;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class DynamicListener implements IExecutionListener, ISuiteListener {
    List<ITestNGListener> listeners = new ArrayList<>();

    public DynamicListener() throws IOException {
        String listenerNames = System.getProperty("listeners");
        boolean all = (listenerNames != null && !listenerNames.trim().isEmpty() &&
                "all".equalsIgnoreCase(listenerNames));
        List<String> names = new ArrayList<>();
        if (!all) {
            names = Arrays.asList(listenerNames.split(","));
        }

        for (String name : listeners()) {
            ITestNGListener eachListener = listenerInstance(name);
            if (all) {
                listeners.add(eachListener);
                continue;
            }
            if (names.contains(eachListener.getClass().getCanonicalName())) {
                listeners.add(eachListener);
            }
        }
    }


    @Override
    public void onExecutionStart() {
        for (ITestNGListener listener : listeners) {
            if (listener instanceof IExecutionListener) {
                ((IExecutionListener) listener).onExecutionStart();
            }
        }
    }

    @Override
    public void onExecutionFinish() {
        for (ITestNGListener listener : listeners) {
            if (listener instanceof IExecutionListener) {
                ((IExecutionListener) listener).onExecutionFinish();
            }
        }
    }

    @Override
    public void onStart(ISuite suite) {
        for (ITestNGListener listener : listeners) {
            if (listener instanceof ISuiteListener) {
                ((ISuiteListener) listener).onStart(suite);
            }
        }
    }

    @Override
    public void onFinish(ISuite suite) {
        for (ITestNGListener listener : listeners) {
            if (listener instanceof ISuiteListener) {
                ((ISuiteListener) listener).onFinish(suite);
            }
        }
    }

    private static List<String> listeners() throws IOException {
        return FileUtils.readLines(new File("src/test/resources/listeners.txt"), Charset.defaultCharset());
    }

    private static ITestNGListener listenerInstance(String name) {
        try {
            Class<?> clazz = Class.forName(name);
            Object instance = clazz.newInstance();
            if (instance instanceof ITestNGListener) {
                return ((ITestNGListener)instance);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        throw new IllegalArgumentException(name + " is NOT valid TestNG listener");
    }
}
```

You then wire the above listener using a service loader as explained [here](http://testng.org/doc/documentation-main.html#listeners-service-loader).

Add all those listener names that are supposed to be part of your project into the `src/test/resources/listeners.txt` file.

Now you can invoke adhoc listeners via the JVM argument `-Dlisteners=` and specify fully qualified class name of the listener that has to be wired in. If you don't specify the listener name, all the listeners specified in the text file would get executed.

Do you think that would help your use-case ? This would not need any change from TestNG.

**Comment by toutoudnf** [comment]
@krmahadevan yes, service loader do the same thing like set listeners in testng.xml file. Thanks a lot :)
