### ISSUE TITLE
TestNG create parallel threads only after java initialize classes

### ISSUE THREAD

**Issue by FibYar** [cbeust/testng#1425]
### TestNG Version
6.10

### Expected behavior
When I run a project I should get correct ThreadID's for every call of `Thread.currentThread().getId()`.

### Actual behavior
Call of `Thread.currentThread().getId()` returns "1" for the fields.

### Is the issue reproductible on runner?

- [ v] IntelliJ

### Test case sample
[Sample.zip](https://github.com/cbeust/testng/files/973551/Sample.zip)

**Comment by krmahadevan** [comment]
@FibYar - I am not sure I quite understand what the problem here is...

I looked at the sample...

Your **Debug1.java** and **Debug2.java** looks like below

```java
package autotests;

import org.testng.annotations.Test;
import paralleltest.TestConstructor;

public class Debug1 {

    TestConstructor testConstructor = new TestConstructor();

    @Test
    public void debug1() {
        new TestConstructor();
        System.out.println("Debug1. Thread.currentThread(): " + Thread.currentThread().getId());
    }
}

```

And your **TestConstructor.java** looks like below

```java
package paralleltest;

public class TestConstructor {
    public TestConstructor() {
        System.out.println("Конструктор. Thread.currentThread(): " + Thread.currentThread().getId());
    }
}
```

The execution output looks like below

```
```

**Comment by FibYar** [comment]
@krmahadevan I guess I didn't explained the problem clearly.
The execution output looks like below:
```
Конструктор (_Constructor_). Thread.currentThread(): 1
Конструктор (_Constructor_). Thread.currentThread(): 1
Debug1. Thread.currentThread(): 9 (some dynamic process)
Debug2. Thread.currentThread(): 10 (one more dynamic process).
```
But I want to see this:
```
Конструктор (_Constructor_). Thread.currentThread(): 9  ( _some dynamic process_ )
Конструктор (_Constructor_). Thread.currentThread(): 10  (_one more dynamic process_).
Debug1. Thread.currentThread(): 9 (_some dynamic process_)
Debug2. Thread.currentThread(): 10 (_one more dynamic process_).
```

**Comment by krmahadevan** [comment]
@FibYar - Your current code that you shared has been written such that it creates two instances of `TestConstructor` java class per test class. Not sure what you are calling out as a problem here with TestNG.

If its the order of the output that you are talking about, then I guess its only a timing issue. Both the test methods are start off in individual threads. The below output re-iterates that statement 
```
[TestRunner] Starting executor for test Autotests with time out:2147483647 milliseconds.
Конструктор. Thread.currentThread(): 10
Конструктор. Thread.currentThread(): 11
Debug1. Thread.currentThread(): 10
Debug2. Thread.currentThread(): 11
```
The lines 
```
Running TestSuite
Конструктор. Thread.currentThread(): 1
Конструктор. Thread.currentThread(): 1
```
Are getting printed when TestNG creates instances for `Debug1.java` and `Debug2.java` which houses your test classes. 

Try changing your test classes to look like below 

```java
package autotests;

import org.testng.annotations.Test;
import paralleltest.TestConstructor;

public class Debug2 {
    @Test
    public void debug2() {
        new TestConstructor();
        System.out.println("Debug2. Thread.currentThread(): " + Thread.currentThread().getId());
    }
}
```
And re-run your project. Your output will then look like below
```
[INFO] Surefire report directory: /Users/krmahadevan/temp/Sample/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[TestRunner] Starting executor for test Autotests with time out:2147483647 milliseconds.
Конструктор. Thread.currentThread(): 10
Конструктор. Thread.currentThread(): 11
Debug1. Thread.currentThread(): 10
Debug2. Thread.currentThread(): 11
PASSED: debug2
PASSED: debug1

===============================================
    Autotests
    Tests run: 2, Failures: 0, Skips: 0
===============================================
```

**Comment by FibYar** [comment]
@krmahadevan 

> Your test code is instantiating TestConstructor instance as a data member in each of your test classes. That explains the below output
> 
> Running TestSuite
> Конструктор. Thread.currentThread(): 1
> Конструктор. Thread.currentThread(): 1
That is exactly what I'm talking about. I've set up "parallel="**classes**"" in testng.xml and expect that everything that my **classes** contains (data members as well) will run in individual threads. Am I wrong?
I agree that I can just move instantiating TestConstructor inside the test methods but I want to know if it a bug or not.

**Comment by krmahadevan** [comment]
@FibYar 

> That is exactly what I'm talking about. I've set up "parallel="classes"" in testng.xml and expect that everything that my classes contains (data members as well) will run in individual threads. Am I wrong?

I think you are wrong.. atleast AFAIK. `parallel="classes"` only instructs how TestNG to should go about executing `@Test` methods and not instructing TestNG on how to go about instantiating test classes. These two are two different things. The `parallel` attribute is all about controlling the execution mechanism of `@Test` methods ONLY and has got nothing to do with controlling the instantiation of test classes.

So IMO its not a bug and TestNG is working as designed.

@juherr / @cbeust - Thoughts ?

**Comment by juherr** [comment]
Agree with @krmahadevan 
The parallel feature doesn't care about classes instantiation and its behavior is not specified (means it could change between versions).
Configuration methods (`@Before*`) or listeners are here to do the init job at the expected time.

Can we close the issue then?

**Comment by FibYar** [comment]
@juherr ok, I understand. I think the issue can be closed.
