### ISSUE TITLE
Unable to install TestNG from Eclipse marketplace

### ISSUE THREAD

**Issue by ajit1988** [cbeust/testng#1428]
Greetings..!!

On trying to install TestNG via eclipse market place on eclipse luna, am getting below error message and the installation process is getting aborted. 

An error occurred while installing the items
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]org.eclipse.jst.j2ee.core 1.3.100.v201404161520, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.InstallBundleAction).
The artifact file for osgi.bundle,org.eclipse.jst.j2ee.core,1.3.100.v201404161520 was not found.

Request your assistance on the same.

**Comment by juherr** [comment]
It's an issue for https://github.com/cbeust/testng-eclipse or maybe https://github.com/testng-team/testng-p2

Ping @missedone

**Comment by missedone** [comment]
similar to issue https://github.com/cbeust/testng-eclipse/issues/316, @ajit1988 , do you still see the same error if use the update site: http://dl.bintray.com/testng-team/testng-eclipse-release/
