### ISSUE TITLE
Test is running in parallel but class are not running in parallel

### ISSUE THREAD

**Issue by VXM97280** [cbeust/testng#1436]
### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >


<suite name="PlacementAdmin" thread-count="2" parallel="tests"
	verbose="2">

	<test name="chrome" allow-return-values="true">
		<parameter name="browser" value="chrome">
		</parameter>
		<classes>

			<class name="com.psm.portalautomation.pageObjects.LoginPage"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.AdGatewayCluster"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.Densities"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.Devices"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.DynamicFields"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.IntegrationMethods"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.InterstitialTypes"></class>


		</classes>
	</test>

<test name="firefox" allow-return-values="true">
		<parameter name="browser" value="firefox">
		</parameter>
		<classes>
			<class name="com.psm.portalautomation.pageObjects.LoginPage"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.AdGatewayCluster"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.Densities"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.Devices"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.DynamicFields"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.IntegrationMethods"></class>
			<class name="com.psm.portalautomation.PlacementAdmin.InterstitialTypes"></class>
		</classes>
	</test> 


</suite>
```

**Comment by juherr** [comment]
> parallel="tests": TestNG will run all the methods in the same <test> tag in the same thread, but each <test> tag will be in a separate thread. This allows you to group all your classes that are not thread safe in the same <test> and guarantee they will all run in the same thread while taking advantage of TestNG using as many threads as possible to run your tests.

http://testng.org/doc/documentation-main.html#parallel-tests

I think the behavior is the expected one according to your configuration.
Feel free to reopen or comment if you think it is still an issue.

**Comment by p00j4** [comment]
@VXM97280  if you really want to execute classes in parallel, you need to set `parallel="classes"` instead of `parallel="tests"` 
however to remember, tests within same class will run sequentially as well described the docs Julien had shared
