### ISSUE TITLE
Improve error message when wrong params on configuration methods

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1440]
Related to #202 and #128 

> Error shown :- FAILED CONFIGURATION: @AfterTest Fail_Test || java.lang.IllegalArgumentException: wrong number of arguments

With 

```java
@AfterTest
void Fail_Test(ITestResult Result) throws IOException {
  ...
```

From: https://stackoverflow.com/q/44134266/4234729

**Comment by krmahadevan** [comment]
@juherr - As an effort to get back to normalcy, I am working on this one :)

**Comment by juherr** [comment]
Great :+1:
