### ISSUE TITLE
Child test behaviour when Parent before method is private

### ISSUE THREAD

**Issue by yarafed** [cbeust/testng#1441]
### TestNG Version
6.11

**First Case** -  The BasicTest throws SkipException in his private before method.
User selects two tests for execution. First is the BasicTest, second is the ChildTest.

**Second case** - The BasicTest does not throw SkipException in his private before method.
User selects two tests for execution. First is the BasicTest, second is the ChildTest.

![run_tests](https://cloud.githubusercontent.com/assets/7060626/26452547/fe17b9c0-4168-11e7-8888-909a8ed2c839.png)

### Expected behavior
**First case expected behaviour:**
The ChildTest should be executed, not skipped. As the BasicTest before method is private and his result should be ignored.

**Second case expected behaviour:**
Second parent test method, which is private, should not be executed for ChildTest. From my point of view, as far as parent private before method is ignored for a child test, parent private test method should be also ignored.

### Actual behavior
**First case actual behaviour:**
The BasicTest starts running. It is skipped, as the SkipException is thrown in a before method. Then the ChildTest starts running, but it also is skipped.

**Second case actual behaviour:**
Test execution flow: Parent before method  -> parent tests -> child before method -> parent test methods. In the Child tests part Parent Before method is not executed as far as it's private.

**Console output:**
```
init
@Test - runTest1
init
@Test - runTest2
setup
@Test - runTest1
setup
@Test - runTest2
```

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```java
public class BasicTest {

    @BeforeMethod
    private void init(){
        System.out.println("init");
        throw new SkipException("Slip test");
    }

    @Test
    public void runTest1() {
        System.out.println("@Test - runTest1");
    }

    @Test
    private void runTest2() {
        System.out.println("@Test - runTest2");
    }
}
______________________________________________
public class ChildTest extends BasicTest{


    @BeforeMethod
    public void setup(){
        System.out.println("setup");
    }


}
```

**Comment by juherr** [comment]
It makes sense but TestNG never cares about the visibility (private or package) before.

To avoid regression, it could be an extra param to enable this behavior (and change its default value in a next major version, a day).

@cbeust WDYT?

**Comment by krmahadevan** [comment]
@juherr - But I would like to understand a typical use case when a user would want to annotate a private method with a TestNG annotation ? When do you think someone would do this.

@yarafed - Can you please help clarify your use case ? If its a private method, then it doesn't make any sense for the method to be annotated with a TestNG annotation [ Yes TestNG is agnostic of the visibility is a different story and we can get to it ]. But I would like to understand why would you do that.

**Comment by juherr** [comment]
@krmahadevan You mean we should skip private methods? 
Visibility could be a way to configure the behavior of tests inheritance, but I've no real use case in mind.

**Comment by krmahadevan** [comment]
@juherr 

> You mean we should skip private methods?

I am not sure if we should be making that decision. Personally I feel that its the test writer's responsibility to annotate methods properly. Not sure if TestNG should make those decisions. Personally I don't see it making any sense for one to add a TestNG annotation on top of a private method. Its counter intuitive when you look at it from just Java's perspective.

That is why I feel that it doesn't make much of a sense to fix this issue.

**Comment by juherr** [comment]
@krmahadevan Yes, it is an option too. In fact, I'm just wondering what behavior is the most natural and if can improve it. BTW, the current behavior must be kept by default for a historical reason.

**Comment by krmahadevan** [comment]
@juherr - One of the option would be to add an optional configuration to TestNG CLI and also to the DTD with a default value which adheres to the current behavior and which can be flipped ( for e.g., the `parallel` attribute which has its default value set to `false` ). But personally I feel its just a bit of over engineering by TestNG do do this.

**Comment by juherr** [comment]
@krmahadevan I understand your point of view :)

**Comment by krmahadevan** [comment]
@juherr - I am of the opinion that we can close off this issue. WDYT ?

**Comment by juherr** [comment]
@yarafed It is possible to something but without a real use case, it is difficult for us to determine if we need to support it or not.
BTW, thanks for the idea and feel free to reply if you want to debate about it.
