### ISSUE TITLE
[Question] Method Parallel from all classes inside test tag

### ISSUE THREAD

**Issue by SrinivasanTarget** [cbeust/testng#1442]
### TestNG Version
Is there a way in testng to execute methods from all classes parallely? 

### Expected behavior
when i say methods parallel in xml, i expected methods from all the classes present in xml runs parallely at same time not one after the other class.

### Actual behavior
When we mention parallel='methods' does runs methods parallely from a first class mentioned in xml whereas rest of classes in same xml waits till methods from first class execution is done.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```
<suite name="Automation Suite" parallel="methods" data-provider-thread-count="15">
    <listeners>
        <listener class-name="asdf.utlis.WebDriverListener"></listener>
    </listeners>
    <test name="REGRESSION">
        <parameter name="browserName" value="chrome"></parameter>
        <groups>
            <run>
                <include name="Regression"/>
            </run>
        </groups>
        <classes>
            <class name="asdf.tests.aaaaaa"/>
            <class name="asdf.tests.bbbbb"/>
            <class name="asdf.tests.cccccc"/>
            <class name="asdf.tests.dddddd"/>
            <class name="asdf.tests.eeeeee"/>
            <class name="asdf.tests.fffffff"/>
        </classes>
    </test>
```
It executes methods inside aaa class parallely then picks methods inside bbb class. Is there a way to execute all the methods from all the classes parallely based on the thread count given?

**Comment by juherr** [comment]
Prefer to use StackOverflow or the mailing list for questions.

Could you try to use `preserve-orde="false"` on the suite node?

**Comment by SrinivasanTarget** [comment]
Nope it doesn't work either. Since it could be a feature req and i didn't find any resource related to it i raised it here.

TestNG goes sequentially with classes even thought methods are set parallel. I expected it will parallelize the methods for all the classes but it completes parallel execution of methods inside one class and goes to next class.

**Comment by krmahadevan** [comment]
@SrinivasanTarget - I can't recreate your issue. Here's what I have

Both ClassA and ClassB look like below

```java
public class ClassA {
    @Test(groups = "regression")
    public void methodA() {
        printer();
    }

    @Test(groups = "regression")
    public void methodB() {
        printer();
    }

    @Test(groups = "regression")
    public void methodC() {
        printer();
    }

    private void printer() {
        String clazz = this.getClass().getName();
        String method = Reporter.getCurrentTestResult().getMethod().getMethodName();
        System.err.println("Executing " + clazz + "." + method + "() on Thread #" + Thread.currentThread().getId());
    }
}
```

Here's my suite xml file (Notice that I have enabled `parallel="methods"` at the `<test>` level.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1400_Suite" verbose="3">
    <test name="REGRESSION" parallel="methods">
        <groups>
            <run>
                <include name="regression"/>
            </run>
        </groups>
        <classes>
            <class name="com.rationaleemotions.github.issue1442.ClassA"/>
            <class name="com.rationaleemotions.github.issue1442.ClassB"/>
        </classes>
    </test>
</suite>
```

Here's the output from command line :
```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ testbed ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...

Executing com.rationaleemotions.github.issue1442.ClassB.methodB() on Thread #16
Executing com.rationaleemotions.github.issue1442.ClassA.methodB() on Thread #13
Executing com.rationaleemotions.github.issue1442.ClassA.methodA() on Thread #12
Executing com.rationaleemotions.github.issue1442.ClassA.methodC() on Thread #14
Executing com.rationaleemotions.github.issue1442.ClassB.methodA() on Thread #15
Executing com.rationaleemotions.github.issue1442.ClassB.methodC() on Thread #14

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.316 sec - in TestSuite

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

```

FWIW, I am running on TestNG 6.11 but that shouldn't matter since this is a very basic use case for TestNG and there are regression tests that test this.

**Comment by SrinivasanTarget** [comment]
Sorry it was my bad, thought it is not working with data provider.It looks fine.
