### ISSUE TITLE
Retry mechanism will not work when the beforemethod/aftermethod got exception,

### ISSUE THREAD

**Issue by fionazj** [cbeust/testng#1444]
### TestNG Version
> Note: only the latest version is supported
TestNG 6.11
### Expected behavior
Retry mechanism is still working.

### Actual behavior
Retry is not working.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
RetryAnnotationListener 
```

public class RetryAnnotationListener implements IAnnotationTransformer {
  @Override
  public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor,
      Method testMethod) {
    IRetryAnalyzer retry = annotation.getRetryAnalyzer();
    if (retry == null) {
      annotation.setRetryAnalyzer(MyRetryAnalyzer.class);
    }

  }

```
MyRetryAnalyzer
```
public class MyRetryAnalyzer implements IRetryAnalyzer {
  public static int MAX_RETRY_COUNT = 3;

  // to avoid the thread safe issue, use the AtomicInteger class, instead of Integer
  AtomicInteger count = new AtomicInteger(MAX_RETRY_COUNT);

  public boolean isRetryAvailable() {
    return (count.intValue() > 0);
  }

  /**
   * retry a failed test
   *
   * @param ITestResult result - the test result of current test case
   * 
   * @return Returns true if the test method has to be retried, false otherwise.
   * 
   * @author Fiona Zhang
   */

  @Override
  public boolean retry(ITestResult result) {
    boolean retry = false;
    if (isRetryAvailable()) {
      System.out.println("Going to retry test case: " + result.getMethod() + ", "
          + (MAX_RETRY_COUNT - count.intValue() + 1) + " out of " + MAX_RETRY_COUNT);
      retry = true;
      // --count
      count.decrementAndGet();
    }
    return retry;
  }
}
```

BeforeMethod
```
  @BeforeMethod(alwaysRun = true)
    public void beforeMethod() {
		Assert.assertTrue(false);
}
```

Test
```
@Test
 public void test(){
   Assert.assertTrue(false);
}
```
> 

}

**Comment by krmahadevan** [comment]
@fionazj - I don't think this is an issue. The retry analyzer to the best of my knowledge is applicable only to `@Test` methods and not to configuration methods. So a failure on a configuration method will cause a test method to be **skipped**. Since a test method is skipped the retry analyzer won't be applicable.

**Comment by fionazj** [comment]
Hi @krmahadevan  , thanks for your explanation,  but i set the parameter "alwaysRun = true", so just think the retry will work.. And as far as you know, is there any solution for this? Cause in our project, test process it is controlled by @before/after/test in different classes, and some operations are did in @before/after method... so our expected behavior should be if the @before/after method is failed, retry still work.

Thanks

**Comment by krmahadevan** [comment]
@fionazj - The attribute `alwaysRun=true` when set causes TestNG to **always** run the configuration method irrespective of what group was chosen to be executed.

Quoting the javadocs from [here](https://jitpack.io/com/github/cbeust/testng/master-6.11-gc0bb558-111/javadoc/org/testng/annotations/BeforeMethod.html#alwaysRun--)

> For before methods (beforeSuite, beforeTest, beforeTestClass and beforeTestMethod, but not beforeGroups): If set to true, this configuration method will be run regardless of what groups it belongs to.
For after methods (afterSuite, afterClass, ...): If set to true, this configuration method will be run even if one or more methods invoked previously failed or was skipped.

I don't think TestNG has any ways in which a configuration method can be re-tried if there was a failure. So you may have to re-design your code such that the operation is part of a `@Test` method.

**Comment by fionazj** [comment]
@krmahadevan  thanks for your reply, I will close the ticket.

**Comment by thibaut-sticky** [comment]
Sorry to publish again on this issue, but we have hundred of Selenium tests skipped because of  flaky beforeMethod (due to the server, the network etc). So the retry feature for the configuration would be really nice. 
Do you know any workaround to implement this without editing all the test classes?

**Comment by krmahadevan** [comment]
@thibaut-sticky - The answer remains the same for now. TestNG doesn't retry configuration methods and AFAIK, there's no way of having TestNG do this as well.

**Comment by Akashkansal065** [comment]
@krmahadevan Retry mechanism not working in case if i set the test to fail Explicitly.

**Comment by shankbond** [comment]
@thibaut-sticky,

What did you do to overcome this issue? Can you please share the code.
Did you add a custom retry in configuration methods or something else.

**Comment by thibaut-sticky** [comment]
@shankbond We just try to make our BeforeMethod/Class more robust and stable. We didn't implement specific listener or logic. It's really specific for each test.

**Comment by afsaralihooq** [comment]
I had the similar situation where tests are skipping  due to configuration method failure 

we implemented within try catch  to overcome this issue ..

int count = 0;
int maxTries = 3;


@BeforeMethod
public void beforeMethod(){
while(true) {
    try {
        // Some Code
        // break out of loop, or return, on success
    } catch (SomeException e) {
        // handle exception
        if (++count == maxTries) throw e;
    }
}
}

**Comment by krmahadevan** [comment]
This would now be facilitated via the PR https://github.com/cbeust/testng/pull/2262

**Comment by lazogio** [comment]
how can I rerun @beforemethod after skipped or failed? I am trying everything, can some one show me example how it will work ?
