### ISSUE TITLE
Feature Request: Configure XML output of XmlSuite

### ISSUE THREAD

**Issue by sachsgit** [cbeust/testng#1455]
### TestNG Version
6.11

### Expected behavior
We would like to be able to configure the XML that XmlSuite generates.
For example, we would like to disable to "end" comments of a test case or test suite, for within XML, you cannot nest comments. We would also like to be able to "pretty up" the XML, spacing between entries, and 

Reference: [How to customize TestNG file creation programmatically to avoid comments
](https://stackoverflow.com/questions/44183892/how-to-customize-testng-file-creation-programmically-to-avoid-comments/44249164#44249164)

**Comment by juherr** [comment]
The fix could be to extract the xml generation logic outside the class and allow the user own logic.
