### ISSUE TITLE
Remove/Warn support of constructor with String param

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1456]
The behavior from https://github.com/cbeust/testng/blob/6a026bc9e3545b6b5da3a3d7977fc44ff1fcc6d6/src/main/java/org/testng/internal/ClassHelper.java#L410-L419 is a bit strange (what is the usecase?) and undocumented.
IMO, it is more natural to remove it in the next major version.
So, first, we may warn users which are using this feature.

From: https://youtrack.jetbrains.com/issue/IDEA-174878

**Comment by cbeust** [comment]
Mmmh... The risks of removing this constructor far outweigh the benefit gained from removing this code, in my opinion.

**Comment by juherr** [comment]
In a minor version, for sure.
In a major I suppose we can.

But the first idea is to add a warn and complains from users (as they already do) will allow us to determine the real risk.
