### ISSUE TITLE
Can not import testng when scope is marked 'test' in maven pom.xml

### ISSUE THREAD

**Issue by jedi-tester** [cbeust/testng#1458]
### TestNG Version
6.11

### Actual behavior
I've marked testng dependency scope as 'test'
Trying to import testng annotations from test folder, however `import org.testng.annotations.Test;` gets marked as error - Can not resolve symbol 'Test'

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
testng dependency in pom.xml
```
</dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>
</dependencies>
```

folders layout:
```
src/test/java  - java test folder
src/test/resources - test resources folder
```

**Comment by juherr** [comment]
Hi,

It looks you have a problem with maven or your IDE.
I've no idea how we are supposed to fix it.

Maybe you can share your project which will help us to reproduce the issue.

**Comment by missedone** [comment]
You can check if maven download the testng jar success in the local maven repo: `$HOME/.m2/repository/org/testng/testng/6.11/`
If the file is currpt , remove it , maven build again.

**Comment by jedi-tester** [comment]
@juherr 
I think you are correct, seems like IntelliJ bug. I can run an mvn verify command and tests are executed successfully, however I still can not import testng classes in my tests and IntelliJ gives me errors.

You can find a simple sample here: https://github.com/jedi-tester/test

Basically everything seems to be working when running tests from console with maven. However I can not run tests from IDE because IntelliJ does not see testng classes. Only if I remove 'test' scope from testng dependency in pom.xml then everything seems to be working as expected

**Comment by elishaebenezer** [comment]
This is more an issue with IntelliJ than TestNG.  Same code works well with NetBeans / Eclipse.

**Comment by juherr** [comment]
@elishaebenezer Thanks for the feedback! Do you reproduce the issue on intellij too?

**Comment by juherr** [comment]
Same question on O: https://stackoverflow.com/questions/44756498/importing-testng-classes-when-scope-marked-test

BTW, you should post an issue on IDEA bugtracker: https://youtrack.jetbrains.com/issues

**Comment by madhu4mobile** [comment]
Try changing the scope as compile.
<scope>compile</scope>

**Comment by teju8** [comment]
@juherr This is a bit unrelated to this question, but I have few classes like dataproviders in 'src/main/java' and maven is explicitly throwing error for not being able to detect the testNG annotations for classes of 'src/main/java'. Can you tell me how to fix that?

**Comment by juherr** [comment]
@teju8 It is related to the maven runner and it will be difficult to investigate without more context. BTW, you should ask your question on StackOverflow with the `maven-surefire-plugin` tag maybe @Tibor17 will be able to answer you there.

**Comment by dxmano1985** [comment]
> @juherr This is a bit unrelated to this question, but I have few classes like dataproviders in 'src/main/java' and maven is explicitly throwing error for not being able to detect the testNG annotations for classes of 'src/main/java'. Can you tell me how to fix that?

Hi @juherr, I am facing the same issue. Did you get a solution?

**Comment by dxmano1985** [comment]
> @juherr This is a bit unrelated to this question, but I have few classes like dataproviders in 'src/main/java' and maven is explicitly throwing error for not being able to detect the testNG annotations for classes of 'src/main/java'. Can you tell me how to fix that?

Hi, I understand that this issue posted in 2021 and I have read this since I faced the same issues. Hope you found the solution already. The reason in my case is in pom.xml for testng dependency <scope> was set to 'test'. The value 'test' limits the dependency to use it under src/test/java/. If I remove the <scope> or set it to 'compile' then I am able to import testng classes under src/main/java.  Maven explains about dependency and scope here https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope
	<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.8.0</version>
			<scope>test</scope>
		</dependency>

Hope this helps someone! Cheers!!
