### ISSUE TITLE
Gmail doesn't render links in emailable-report.html

### ISSUE THREAD

**Issue by harshpatil** [cbeust/testng#1462]
### TestNG Version
> Note: only the latest version is supported
6.10

### Expected behavior
All the links in report should work on clicking them.

### Actual behavior
I am passing emailable-report.html file as body in jenkins email report plugin (Example - ${FILE,path="target/surefire-reports/emailable-report.html"})
When I open the  email received from jenkins, hyperlinks doesn't work. If I click on failed test, it doesn't render me to stack trace.

P.S - This works well on chrome browser.

### Is the issue reproductible on runner?
No.

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Steps to reproduce
1) Run test suite
2) Send emailable-report.html file to gmail or any other email provider using jenkins or any other source.
3) Open email, click on test method name
4) User should be taken to method failure stack trace. (which is not working)

**Comment by krmahadevan** [comment]
Do the links in the `emailable-report.html` that is available in your Jenkins workspace work fine ?
If they work fine there, but don't when clicked from the html file you received as an attachment, I would probably attribute that to your mail client (gmail web app in this case) which is perhaps stripping those capabilities to ensure that you don't encounter a phishing attack. In either case, it would be good if you can please help attach both the html files here.

**Comment by harshpatil** [comment]
Do the links in the emailable-report.html that is available in your Jenkins workspace work fine ?
  ---> Yes, it works fine in jenkins workspace
If I send emailable-report.html as an attachment, download it from mail and open in browser, it works fine too.
It doesn't work when I set gmail to open this html file as part of mail body.

Attaching all the files and screen-shot.

[emailable-report_Downloaded_From_Jenkins_Workspace.html.zip](https://github.com/cbeust/testng/files/1128593/emailable-report_Downloaded_From_Jenkins_Workspace.html.zip)
[emailable-report_Received_As_Attachment_From_Jenkins.html.zip](https://github.com/cbeust/testng/files/1128595/emailable-report_Received_As_Attachment_From_Jenkins.html.zip)
<img width="1040" alt="emailable-report_screen_shot_of_gmail_this_is_where_it_doesn t_work" src="https://user-images.githubusercontent.com/14204978/27922720-9cba7ac4-6241-11e7-9327-3c35bd3389bb.png">

Let me know if you need anything else.

**Comment by krmahadevan** [comment]
@harshpatil - I am not sure what can be done here from TestNG side. TestNG's role ends with creating the `emailable-report.html` with full functioning links (This you have confirmed when you say that it works fine when you download the html and use it). I believe it could be something at `Gmail` front which strips off all the hyperlinks when a html gets embedded into its body (We also don't know how you are adding the html to the body of the email). 

I would suggest that you please stick to attaching the report as an attachment to the body (or) you would need to build a mail composer, which would weave the entire contents of the test reports as an email and send it as well to whichever account you are using. That should retain the hyperlinks in the mail.

**Comment by harshpatil** [comment]
Alright, I will write a mail composer. Thanks for looking into this.
