### ISSUE TITLE
Enabled = false does not have any effect

### ISSUE THREAD

**Issue by kiru** [cbeust/testng#1471]
### TestNG Version
6.11

### Expected behavior
If Test class is marked with enabled = false then it should not run any tests in that class.

### Actual behavior
enabled = false or true seems to be ignored

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x ] IntelliJ
- [ ] NetBeans

### Test case sample
```

/**
 * @author Kirusanth Poopalasingam ( code@kiru.io )
 */
public class TestNgEnableBehaviour {

    public static void main(String[] args) throws Exception {
        // we run the test programmatically
        TestNG testng = new TestNG();

        testng.setTestClasses(new Class[]{
            TestDisabled.class,
            TestA.class,
        });

        // lets run the test
        testng.run();
    }

    @Test(enabled = false)
    public static class TestDisabled {
        @Test
        public void aTestMethod1() {
            System.out.println("TestDisabled test method 1");
        }
    }

    @Test
    public static class TestA {
        @Test
        public void aTestMethod1() {
            System.out.println("TestA test method 1");
        }

        @Test(enabled = false)
        public void aTestMethod2() {
            System.out.println("TestA test method 2");
        }
    }
}
```
The output is:

> TestA test method 1
> TestDisabled test method 1

I don't understand why TestGroupADisabled#aTestMethod1() is executed.

**Comment by kiru** [comment]
I have added a slightly changed example as test.

**Comment by juherr** [comment]
It works as expected. See https://github.com/cbeust/testng/pull/861
