### ISSUE TITLE
Optimize DynamicGraph.getUnfinishedNodes()

### ISSUE THREAD

**Issue by nathanila** [cbeust/testng#1472]
### TestNG Version
6.11

### Expected behavior
Less CPU time spent in DynamicGraph.getUnfinishedNodes()

### Actual behavior
DynamicGraph.getUnfinishedNodes() spends a lot of CPU time inside ArrayList.contains() due to m_nodesReady and m_nodesRunning being ArrayLists.  If possible, please change m_nodesReady and m_nodesRunning to HashSet.

getUnfinishedNodes() is only called by getFreeNodes().  getFreeNodes() doesn't need the Collection.  Please change Collection<T> getUnfinishedNodes() to boolean hasUnfinishedNodes().  This will allow hasUnfinishedNodes() to short-circuit when it finds the first node and avoid allocating a Collection.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
This would require a lot of test cases with most of the test cases with a default priority and several test cases with a priority > 0.

**Comment by juherr** [comment]
Thanks for the report.

What you are proposing could be cool. Why don't you try to propose a pull request?

**Comment by nathanila** [comment]
Here is the code which implements issue #1472 and #1473.

[DynamicGraph.zip](https://github.com/cbeust/testng/files/1149354/DynamicGraph.zip)

**Comment by juherr** [comment]
Thanks but a pull request will help us to review the change and check if it doesn't break things.
Do you think you can do it ?

**Comment by nathanila** [comment]
I've never done a pull request.  I am under pressure to meet a deadline and can't take time to figure out how to do a pull request.

**Comment by juherr** [comment]
It is an excellent opportunity to learn it and we have the time if you want to do it later.

In few words, just fork the project in your own GitHub space, clone the project on your computer, commit the changes, push the branch and click on the "pull request" button.

At least, we have the code and we will be able to apply the changes. Again, thanks for that :)

**Comment by krmahadevan** [comment]
@nathanila - [Here's](https://rationaleemotions.wordpress.com/2016/01/16/contributing-to-open-source-projects-on-github/) an elaborate step-by-step tutorial. I wrote up this blog when I had started off with contributing to TestNG.
