### ISSUE TITLE
Override the default 60 minutes timeout for tests

### ISSUE THREAD

**Issue by ephilippona** [cbeust/testng#1486]
### TestNG Version
TestNG-6.8

### Expected behavior
Run a test for longer than an hour

### Actual behavior
Test times out after 60 minutes

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

I found the error message ("The tests timed out and were killed.") in TestNGAntTask.java but setTimeout() does not seemed to be used anywhere. Is there a way to set this timeout in order to run a test for longer than 60 minutes? 

I tried setting timeout values for my suite, test group and individual tests with no success. 

Related posts I found: [post](https://groups.google.com/forum/#!topic/testng-users/uReYDErHVzs)

**Comment by krmahadevan** [comment]
@ephilippona - The setters are called via your build.xml file I guess.

For e.g., if I have something like below

```xml
<taskdef name="testng" classname="org.testng.TestNGAntTask" classpathref="build.classpath"/>

<target name="testng" depends="compile">
    <testng timeout="120" classpath="build.test.classpath">
        <xmlfileset dir="${baseDir}" includes="suite.xml"/>
    </testng>
</target>
```
It would translate to invoking the below mentioned setters within the class `org.testng.TestNGAntTask`

* `org.testng.TestNGAntTask#setTimeout` (Provide a value in milliseconds).
* `org.testng.TestNGAntTask#setClasspath`
* `org.testng.TestNGAntTask#addXmlfileset`

So can you please try setting the timeout from within your `build.xml` as shown above and see if that helps ?

**Comment by krmahadevan** [comment]
Closing this issue, since there's no response from the user on this for quite sometime. Please re-open if the above mentioned explanation doesn't help in fixing the problem.
