### ISSUE TITLE
Improve test debugging on CI

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1491]
As @selenareneephillips pointed it on #1487, debugging issues on Travis is a pain.

Last time I checked, I found potential ideas:
* export test results like an artifact, but I don't know where https://docs.travis-ci.com/user/uploading-artifacts/
* we can use extentx but we need to host the server somewhere (heroku free instance?) https://github.com/anshooarora/extentx/issues/70
* move to another ci service (I remember some travis challengers allow to store files)

**Comment by krmahadevan** [comment]
We can perhaps consider uploading the test artifacts to some new repository under https://github.com/testng-team to the `gh-pages` branch by following this instructions https://gist.github.com/domenic/ec8b0fc8ab45f39403dd.

We will perhaps need @cbeust to help us with generating and adding a new pair of credentials as detailed [here](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials)

**Comment by juherr** [comment]
@krmahadevan Yes, it was the idea behind https://github.com/testng-team/testng-travis-reports but I've never gone further.

**Comment by selenareneephillips** [comment]
Could I also suggest migrating over to more modern and fully featured logging framework like slf4j + logback? It's significantly less clunky than java.util.logging. It can also capture the thread ID. I discovered that the Java logger cannot do that when I was working on the logging for the paralellization test suite.

**Comment by juherr** [comment]
@selenareneephillips Where do you want slf4j? 
For internal usage, @cbeust doesn't like to add extra dependencies, then we will have to design an optional dependency to slf4j around the current testng logger first if you want to use slf4j out of the box.
If you want it in tests, I think it won't be a problem so feel free to use it as a test dependency.

**Comment by juherr** [comment]
Fixed with #1537
