### ISSUE TITLE
Build a test that validates a TestNG release

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1492]
It would be good to have a test, that when executed can validate a TestNG release for common things such as 

* Ensuring that the javadocs and sources are available in BinTray
* Dependencies information is proper.

There's already something like this for [Kobalt](https://github.com/cbeust/kobalt/blob/master/src/test/kotlin/com/beust/kobalt/VerifyKobaltZipTest.kt). We can perhaps think of building something similar for TestNG as well.

**Comment by juherr** [comment]
To check:
* javadoc and source jars are here and not empty
* class files are compiled with java7
* Version.class and META-INF contain the expected value
* the scope of dependencies in the generated pom are good

**Comment by missedone** [comment]
also:
* no fat jar

**Comment by krmahadevan** [comment]
[x] class files are compiled with java7
Made use of jclasslib plugin to test this

[x] Version.class
When running a suite file with a verbosity of 2, I see the version displayed as below.

```bash
...
... TestNG 6.14.0-RC1 by Cédric Beust (cedric@beust.com)
...

```

[x] The scope of dependencies in the generated pom are good
Here are the steps that I followed. [This is just for my reference, so that I don’t forget how to do this :) ]

Contents of ./release-validate.sh :

```bash
#!/bin/bash
rm diff.txt
cp ~/.m2/repository/org/testng/testng/$1/testng-$1.pom pom.xml
mvn dependency:resolve
mvn -o dependency:list | grep ":.*:.*:.*" | cut -d] -f2- | sed 's/:[a-z]*$//g' | sort -u > $1.txt
rm pom.xml
cp ~/.m2/repository/org/testng/testng/$2/testng-$2.pom pom.xml
mvn dependency:resolve
mvn -o dependency:list | grep ":.*:.*:.*" | cut -d] -f2- | sed 's/:[a-z]*$//g' | sort -u > $2.txt
diff $1.txt $2.txt > diff.txt
rm $1.txt
rm $2.txt
cat diff.txt
```

output output

```bash
./release-validate.sh 6.13.1 6.14.0-RC1
2,3c2
< com.beust:jcommander:jar:1.72
< com.google.code.findbugs:jsr305:jar:3.0.1
---
> com.beust:jcommander:jar:1.66
5c4
< com.google.inject:guice:jar:4.1.0
---
> com.google.inject:guice:jar:no_aop:4.1.0
11,13d9
< org.assertj:assertj-core:jar:3.5.2
< org.beanshell:bsh:jar:2.0b4
< org.codehaus.groovy:groovy-all:jar:2.4.1
15,16d10
< org.spockframework:spock-core:jar:1.0-groovy-2.4
< org.testng:testng:jar:6.9.13.7
```

References: Referred [Stackoverflow](https://stackoverflow.com/a/38461128/679824) for the command line script that prints the dependencies information in a short way.

**Comment by juherr** [comment]
Some other ideas on #1628

**Comment by krmahadevan** [comment]
Attempted at creating a project in the testng-team org that can do all of this

https://github.com/testng-team/release-validator

**Comment by krmahadevan** [comment]
The project https://github.com/testng-team/release-validator fixes all of the asks detailed in this issue and also #1628
