### ISSUE TITLE
Incorrect message in exception

### ISSUE THREAD

**Issue by praveen133t** [cbeust/testng#1504]
### TestNG Version
Version 6.11

### Expected behavior
Correct error message should be displayed along with the exception

### Actual behavior
Incorrect error message is displayed

> FAILED CONFIGURATION: @AfterTest tearDown(@AfterTest tearDown: Wrong number of arguments were passed by the Data Provider: found 1 but expected 2)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
    @AfterTest
    public void tearDown(ITestContext context, ITestResult result) {
        System.out.println("In after test..");

    }
```

> **FAILED CONFIGURATION: @AfterTest tearDown(@AfterTest tearDown: Wrong number of arguments were passed by the Data Provider: found 1 but expected 2)**
> java.lang.IllegalArgumentException: wrong number of arguments
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
> 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
> 	at org.testng.TestRunner.afterRun(TestRunner.java:958)
> 	at org.testng.TestRunner.run(TestRunner.java:606)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
> 	at org.testng.TestNG.runSuites(TestNG.java:1144)
> 	at org.testng.TestNG.run(TestNG.java:1115)
> 	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
> 	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
> 	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

Not sure if the message is right but it's confusing as I'm not using any DataProvider here.
This message is also some what identical in `@Test` annotation

**Comment by krmahadevan** [comment]
The problem lies in your test code. 

For an `@AfterTest` annotated method, you can only inject `ITestContext` and `XmlTest`.

```
org.testng.TestNGException: 
Can inject only one of <ITestContext, XmlTest> into a @AfterTest annotated tearDown.
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection

	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:334)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:274)
	at org.testng.internal.Parameters.createParameters(Parameters.java:562)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:150)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:206)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.afterRun(TestRunner.java:1007)
	at org.testng.TestRunner.run(TestRunner.java:638)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
```

I agree with you on the verbiage of the error message. This was fixed in TestNG 6.12 (This is yet to be released into Maven central. I believe @cbeust is resolving some issues in terms of syncing up Maven Central with BinTray)

You can however, still consume TestNG `6.12`, by doing the following in your `pom.xml`

First you need to add the below entry in your pom file

```xml
<repositories>
    <repository>
        <id>jcenter</id>
        <url>https://jcenter.bintray.com</url>
    </repository>
</repositories>
```

You then add a dependency to TestNG `6.12` as below

```xml
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.12</version>
</dependency>
```

For now you can refer to this wiki page https://github.com/cbeust/testng/wiki/Allowed-parameters-injection-in-methods

Once TestNG 6.12 is released to Maven central, we will be updating the TestNG documentation portal with a similar table as well (A PR for the same has already been merged in the documentation. Its just pending update to the actual site, since TestNG 6.12 is not yet officially gone out)
