### ISSUE TITLE
Upload TestNG 6.12 to Maven Central

### ISSUE THREAD

**Issue by frekele** [cbeust/testng#1506]
Hi,

Upload TestNG 6.12 to Maven Central, please.

Thank you.

**Comment by juherr** [comment]
https://groups.google.com/forum/m/#!topic/testng-users/nIGIqKliavM

**Comment by frekele** [comment]
I added in my repository:

```
<profiles>
   <profile>
       <repository>
           <id>bintray</id>
           <name>Bintray repo (releases)</name>
           <url>https://jcenter.bintray.com/</url>
           <releases>
              <enabled>true</enabled>
              <updatePolicy>always</updatePolicy>
              <checksumPolicy>warn</checksumPolicy>
           </releases>
           <snapshots>
              <enabled>false</enabled>
              <updatePolicy>never</updatePolicy>
              <checksumPolicy>fail</checksumPolicy>
          </snapshots>
       </repository>           
   </profile>
</profiles>
```
But I was trying to avoid adding another repository, I try to centralize everything in the central maven.

Thank you @juherr .

**Comment by juherr** [comment]
6.12 will be available on maven central once the sync issue will be resolved ;)

**Comment by hemano** [comment]
Is it possible to get a commit which has relevant fixes as a maven dependency?

            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>66d78dc</version>
            </dependency>

**Comment by juherr** [comment]
@hemano You can do it with https://jitpack.io

**Comment by bartoszmajsak** [comment]
Can you try to sync from bintray's jcenter to Maven Central again? I see the artifact has been published in former but not the latter.

**Comment by krmahadevan** [comment]
ping @cbeust - Gentle reminder.

**Comment by cbeust** [comment]
I just gave this another try and still getting

```
Last Sync Errors: Invalid Signature: '/org/testng/testng/6.12/testng-6.12.jar.asc' is not a valid signature for 'testng-6.12.jar'. Invalid Signature: '/org/testng/testng/6.12/testng-6.12-sources.jar.asc' is not a valid signature for 'testng-6.12-sources.jar'. Dropping existing partial staging repository.
```

The signatures look valid to me;

```
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: GPGTools - http://gpgtools.org

iQEcBAABAgAGBQJaAUJTAAoJEJRAyNbeyvoSP8UIAJQQ1GfSVF5PyTu4geAymxhv
rFO8tP+jGs2YEhysv8/d0wdvhLmWsO1SYqhm6bttawdp0yUU5gzs48gUVYjAux+5
DB2Q3rIyp1hWSYo+9kycok5juSduSGUJNzI+wWacBGpml0wvZ9U0CMuUhWTS+McU
xOvIs7BiNuKROlgFVnshrBH9S4KJzLFOAtJI8+jMqxa4tLdKLph3tOkChmP+K+sK
m/+1/vjO4A1n0+8mbwl9cjZ6rci/B93eAdZ2WSUaXKh8EcZDH0DSz9FdNGyf9ehA
7FDVWTSmc4WPZopapo/xaJhZ+fDjls6Sz9puck9oNlsxgjRxlkpndmpnKTuVi9I=
=WMzu
-----END PGP SIGNATURE-----
```

**Comment by krmahadevan** [comment]
@cbeust - Does JCenter have some sort of support mechanism from whom we can get some help ? I have always only published to Maven central directly. So I dont have too much knowledge.

**Comment by juherr** [comment]
@cbeust You have really no luck with maven central 🤣

**Comment by krmahadevan** [comment]
@juherr @cbeust - So how do we get past this issue ? Should we reach out to Sonatype's support by filing a Jira ticket and asking for this help ?

**Comment by phillipross** [comment]
testng 6.12+ support in arquillian is still blocked on getting this 🔔

**Comment by juherr** [comment]
@phillipross We are going to release 6.13 in the next days and @cbeust will try to push the version into central.

**Comment by cbeust** [comment]
6.13 is now available on Maven Central.

**Comment by bartoszmajsak** [comment]
Thanks, it almost works. I'm getting following error now:
`Failure to find com.beust:jcommander:jar:1.66 in http://repo.maven.apache.org/maven2`

It seems that this version is missing in central and it comes as transitive dependency to TestNG. 
http://repo.maven.apache.org/maven2/com/beust/jcommander/

Simple workaround:
```
<dependency>
  <groupId>com.beust</groupId>
  <artifactId>jcommander</artifactId>
  <version>1.69</version>
  <scope>test</scope>
</dependency>
```

**Comment by cbeust** [comment]
JCommander is in JCenter and is required by TestNG itself, it can't be in `<test>` scope.

Please add JCenter to your list of repos.

**Comment by bartoszmajsak** [comment]
Why can't it be in `test` scope if `testng` is? That's really a secondary problem here, as jcomander will inherit scope from testng in such if I'm not mistaken.

The reason why this whole issue exists is that `testng` wasn't synced with mvn central. So if we assume we only wish to use official maven repo, JCommander should also be available there. Otherwise we are back to square one with adding `jcenter` as the repository.

**Comment by cbeust** [comment]
Fair point.

I just deployed TestNG 6.13.1 to Maven Central, which depends on [JCommander 1.72, which is on Maven Central](http://search.maven.org/#artifactdetails%7Ccom.beust%7Cjcommander%7C1.72%7Cjar).

TestNG 6.13.1 should appear on Maven Central in a few hours.

**Comment by bartoszmajsak** [comment]
Thanks a lot for your instant help! I know syncing with Central is a nightmare sometimes, been there too many times, so I really appreciate this.
