### ISSUE TITLE
JCenter's TestNG brings JUnit in unoptionally

### ISSUE THREAD

**Issue by buumi** [cbeust/testng#1516]
### TestNG Version
6.12

### Expected behavior
In JCenter's 6.11 build and in Git's latest build.gradle JUnit is marked as an optional dependency. I expect that defining TestNG in my pom.xml does not thus bring JUnit in automatically.

### Actual behavior
JUnit is not marked as optional in JCenter's 6.12 pom.xml [Link to folder](http://jcenter.bintray.com/org/testng/testng/6.12/). JUnit is brought in automatically. 

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Define a maven project with TestNG 6.12. Check stuff brought in by TestNG and notice JUnit is there.

**Comment by juherr** [comment]
Thanks for the report. It should be fixed before #1506

**Comment by juherr** [comment]
Fixed in 6.13
