### ISSUE TITLE
Try Gradle build scan

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1526]
Could be a good way to follow test status (instead of travis log)
https://gradle.com/build-scans

**Comment by krmahadevan** [comment]
@juherr - This seems to be like a paid project no ?

**Comment by juherr** [comment]
@krmahadevan In a french podcast (https://lescastcodeurs.com/2017/08/01/lcc-174-interview-sur-la-build-avec-cedric-champeau-et-arnaud-heritier-partie-1/), @melix said (if I understood well) that some parts are free and maybe these parts will help us.

**Comment by krmahadevan** [comment]
@juherr - Ah ok. Any pointers on from where can we get started? (I don't understand French so am not sure if I would be able to understand the podcast) 
I can give this a shot.

**Comment by melix** [comment]
Just follow the instructions on https://scans.gradle.com/get-started

**Comment by krmahadevan** [comment]
@melix - Thank you Cedric. I have managed to get the scans available by following the instructions in the link you shared.
