### ISSUE TITLE
Wrong thread names in method runs reports

### ISSUE THREAD

**Issue by sergebg** [cbeust/testng#153]
A test with 2 <code>@Test</code> methods and one <code>@BeforeMethod</code>. When it is executed with parallel = true, reported thread names are incorrect. Code example (only class body):

<pre>
@BeforeMethod public void init() {
    Reporter.log(Thread.currentThread().toString());
}
@Test public void test1() {}
@Test public void test2() {}
</pre>

Lines from report (here threads are correct):

<pre>
Thread[pool-2-thread-1,5,main]
Thread[pool-2-thread-2,5,main]
</pre>

And this information is extracted from the "Method runs, sorted chronologically" report (methods.html):

<pre>
11/12/31 01:30:26   0   >>init  <b>pool-2-thread-1@1272266587</b>   
11/12/31 01:30:26   -1  >>init  <b>pool-2-thread-1@1272266587</b>   
11/12/31 01:30:26   6   test1   pool-2-thread-1@1272266587  
11/12/31 01:30:26   6   test2   pool-2-thread-2@489854530   
</pre>

In the report for the both invocations of <code>init()</code> method the same thread is shown.

**Comment by krmahadevan** [comment]
The new reporter viz., `org.testng.reporters.jq.Main` which now generates the reports, no longer shows the output for configuration methods but confines itself to showing the output of test methods only.
