### ISSUE TITLE
google chrome browser does not redirect to to e.g. "Chronological view"

### ISSUE THREAD

**Issue by jonasSel** [cbeust/testng#1540]
### TestNG Version
6.11
Chrome version: Version 60.0.3112.113 (Official Build) (64-bit)

### Expected behavior
Links in reporter output are working under chrome

### Actual behavior
In Google-Chrome browser, but not Firefox or Edge: links in the "Info" square are not redirect to the respective results:
-clicking on "Reporter output", Ignored methods" or "Chronological view"  rest on the same view. I have to switch to Firefox.

**Comment by krmahadevan** [comment]
@jonasSel - Can you please help add a sample test which can be run to recreate the problem ?

**Comment by krmahadevan** [comment]
No response from the user. Closing this issue. Please re-open once you have some additional information.
