### ISSUE TITLE
Method that is failed because of missing parameters is passed to listener as a skipped one

### ISSUE THREAD

**Issue by gaurnar** [cbeust/testng#156]
I encountered a rather vicious problem with passing test results to listener. If a method fails because of missing parameters, it is passed to registered listener as a skipped one (i.e. onTestSkipped method is called and test result object has skipped status). I can see that it is actually failed because it is stated so in summary box that is written to STDOUT:

```
===============================================
test
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

and also because it is marked as failed in test-output/emailable-report.html. There is also relevant exception message displayed:

```
Parameter 'param' is required by @Test on method foo but has not been marked @Optional or defined in ...
```

I verified this problem in latest released version - 6.3.1.

Here is a simple test to reproduce this issue:

``` java
package org.gaurnar;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class FooTest
{
  @BeforeClass( description = "prep" )
  public void preparation()
  {

  }

  @Test( description = "foo" )
  @Parameters( "param" )
  public void foo( String param )
  {

  }
}
```

and a simple runner to launch the test and set listener:

``` java
package org.gaurnar;

import java.util.LinkedList;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;
import org.testng.TestNG;

public class Runner
{
  public static class Listener implements ITestListener
  {
    public void onTestStart( ITestResult result )
    {
      System.out.print( "test start\n" );      
    }

    public void onTestSuccess( ITestResult result )
    {
      System.out.print( "test success\n" );
    }

    public void onTestFailure( ITestResult result )
    {
      System.out.print( "test failure\n" );
    }

    public void onTestSkipped( ITestResult result )
    {
      System.out.print( "test skipped\n" );
    }

    public void onTestFailedButWithinSuccessPercentage( ITestResult result )
    {
    }

    public void onStart( ITestContext context )
    {
      System.out.print( "class start\n" );

    }

    public void onFinish( ITestContext context )
    {
      System.out.print( "class finish\n" );
    }
  }

  public static void main( String[] args ) throws Exception
  {
    TestNG testNG = new TestNG();
    testNG.setListenerClasses( new LinkedList<Class>() {{ add( Listener.class ); }} );
    testNG.setTestClasses( new Class[] { FooTest.class } );
    testNG.run();
  }
}
```

**Comment by krmahadevan** [comment]
Tried this again on TestNG 6.12 and cannot reproduce this issue any more.

Here's the output that I see when using the same sample shared here.

```
class start
test failure
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Parameter &apos;param&apos; is required by @Test on method foo but has not been marked @Optional or defined

	at org.testng.internal.Parameters.createParams(Parameters.java:248)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:286)
	at org.testng.internal.Parameters.createParameters(Parameters.java:547)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:672)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1316)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1044)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1134)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at com.rationaleemotions.github.issue156.Github156TestRunner.main(Github156TestRunner.java:46)

class finish

===============================================
Command line suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0

```

As seen from the output, now the listener's `com.rationaleemotions.github.issue156.Github156TestRunner.Listener#onTestFailure` is invoked correctly.

**Comment by komalshrivas** [comment]
import org.testng.annotations.Test;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.testng.annotations.AfterTest;

public class Login_Intel_ParallelExecution {
	public WebDriver driver;
  @Test
  
  public void f() {
	  driver.findElement(By.xpath(".//*[@id='username']")).sendKeys("123");
	  driver.findElement(By.xpath(".//*[@id='password']")).sendKeys("12345");
	  driver.findElement(By.xpath(".//*[@id='content']/div/div[2]/form/fieldset/div[3]/button")).click();
	  
  }
  
  @BeforeTest
  @Parameters("chrome")

  public void beforeTest(String chrome) throws Exception {
	  
	if(chrome.equalsIgnoreCase("firefox"))
	  {
	  System.setProperty("webdriver.gecko.driver","E:\\library1\\geckodriver.exe");
	  driver=new FirefoxDriver();
	  driver.get("xyz");
		Thread.sleep(4000);
	  }
	  else if(chrome.equalsIgnoreCase("chrome"))
	  {
		  System.setProperty("webdriver.chrome.driver","E:\\library1\\chromedriver.exe");	
		  driver=new ChromeDriver();
		  driver.get("xyz");  
	  }
	  else if(chrome.equalsIgnoreCase("ie"))
	  {
		  System.setProperty("webdriver.ie.driver", "E:\\Library1\\IEDriverServer.exe");		
		  driver=new InternetExplorerDriver();
		  driver.get("xyz"); 
	  
  }
  }

  @AfterTest
  public void afterTest() {
	  driver.quit();
  }

}







Parameter 'chrome' is required by @Configuration on method beforeTest but has not been marked @Optional or defined 


i can't understand this type error can you please help to solve it
