### ISSUE TITLE
Beanshell based execution using method-selectors is taking a long time to start as it loops through

### ISSUE THREAD

**Issue by praveen133t** [cbeust/testng#1562]
### TestNG Version
6.12

### Expected behavior
TestNG should only pick up the specified package and should not loop through the beanshell code in testng.xml

### Actual behavior
It loops through the beanshell code and takes a long time to start the tests

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
This is a base class
```
package com.web.pack.others;
public class BaseClass {

    public void baseClassMethod() {
        System.out.println("In BasseClassMethod....");
    }
}
```

This is a Test1 class
```
package com.web.pack.testcases;
import org.testng.annotations.Test;
import com.web.pack.others.BaseClass;
public class TestCase1 extends BaseClass {
    @Test
    public void testMethod1() {
        System.out.println("In test method 1");
    }
}
```

This is a Test2 class
```
package com.web.pack.testcases;
import org.testng.annotations.Test;
import com.web.pack.others.BaseClass;
public class TestCase2 extends BaseClass {
    @Test
    public void testMethod2() {
        System.out.println("In test MEthod 2...");
    }
}
```

My testng.xml
```
<?xml version="1.0" encoding="UTF-8"?> 
	<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Package-Suites">
	<test name="Package-Tests">
		<method-selectors>
			<method-selector>
				<script language="beanshell">
                <![CDATA[packageName = System.getProperty("packageName");
                print("--------------------------------------------------------------------------------");
                print(packageName);]]>
                method.getDeclaringClass().getPackage().getName().contains(packageName);
				</script>
			</method-selector>
		</method-selectors>
		<packages>
			<package name="com.web.pack.*" />
		</packages>
	</test>
</suite>
```

Now when I run with -DpackageName=testcases (As my Test1 and Test2 are in `testcases` package) I get the below output

```
[RemoteTestNG] detected TestNG version 6.11.0
--------------------------------------------------------------------------------
testcases
--------------------------------------------------------------------------------
testcases
--------------------------------------------------------------------------------
testcases
--------------------------------------------------------------------------------
testcases
--------------------------------------------------------------------------------
testcases
--------------------------------------------------------------------------------
testcases
In test method 1
In test MEthod 2...

===============================================
WWW-Package-Suites
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```

If you see I'm printing the `packageName` in the beanshell. When I run the testng.xml it loops through the beanshell code multiple times. I have many packages in my project and each package has about 100 test cases. So it's taking a long time to even start the first test case.

**Comment by krmahadevan** [comment]
@praveen133t - Beanshell is basically a method selector. So it is going to be called for every method to  help TestNG decide if it should be executed or not.

You shouldn't be using a method selector if you wanted to build a dynamic behavior wherein the packages to be executed itself is dynamic and not known until runtime.

I would suggest that you please make use of something like an `org.testng.IAlterSuiteListener` for these sort of purposes.

Please take a look at [this](https://rationaleemotions.wordpress.com/2017/09/29/building-dynamic-testng-suites/) blog post that I created which shows how to do this.

**Comment by praveen133t** [comment]
Thanks a lot @krmahadevan  I will give it a shot

But what I observed was I have two projects. One with Page factory model and one without Page factory model. Using this Beanshell type of execution, Page Factory model based execution is taking very very long time to even start running the test cases when compared to non-page factory model based execution. Is it because of too many annotations (like @androidFindBy etc) ?

**Comment by krmahadevan** [comment]
@praveen133t - PageFactory basically uses reflection under the hoods. That explains the additional amount of time it takes for your project.  The annotations are basically used in page factory only to bind locator information. You can instead consider leveraging something like [Simple Se Page Objects](https://github.com/RationaleEmotions/simplese) which is also built around the page objects pattern, but does away with annotation driven locators.

**Comment by praveen133t** [comment]
@krmahadevan : Thanks a lot. That helps!
