### ISSUE TITLE
6.12 not released to maven for use as a dependency

### ISSUE THREAD

**Issue by jatheisenii** [cbeust/testng#1564]
### TestNG Version
6.12

### Expected behavior
Available at https://mvnrepository.com/artifact/org.testng/testng

### Actual behavior
6.11 is the last release

### Is the issue reproductible on runner?

- [ ] Shell
- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I can update in eclipse to 6.12 testng but I cannot use it as a dependency in maven

**Comment by juherr** [comment]
Duplicate of #1506
