### ISSUE TITLE
Invalid XML characters in Params in testng-results.xml

### ISSUE THREAD

**Issue by TheLQ** [cbeust/testng#1566]
### TestNG Version
6.11

### Expected behavior
Invalid XML 1.0 characters are escaped, replaced, or removed from the output. Or the file being XML 1.1 which supports more characters

### Actual behavior
The 0xC character is present in the testng-results.xml file, making in unopenable in other tools like Jenkins

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```java
@DataProvider
public Object[][] dataProvider() {
	return new Object[][]{{
		"test \u000C"
	}};
}

@Test(dataProvider = "dataProvider")
public void test(String argument) {
}
```

**Comment by juherr** [comment]
Related issue: https://issues.apache.org/jira/browse/SUREFIRE-1428
