### ISSUE TITLE
Synchronization/lock of onStart not working

### ISSUE THREAD

**Issue by VenkateshPS** [cbeust/testng#1568]
### TestNG Version
> Note: only the latest version is supported

### Expected behaviour
Running tests in parallel using xml
```xml
<suite name ="A" parallel ="tests" thread-count="3">
````
Below is the listener class,  I want to print increment testInstance for each thread variable but it does not works. 

```java
Class myListener implements ITestListener{
private final Lock lock= new ReentrantLock();
private static testInstace =1;
	@SuppressWarnings("unchecked")
	public  void onStart(ITestContext context) {
		try{
		lock.lock();
		System.out.println("In On Start" + testInstance);
              testInstace++;
     }
     finally{
         lock.unlock()
}
```
	
### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@VenkateshPS

What do you mean by it does not work ? Can you please help elaborate ? Can you please help share a full fledged sample test case, which we can execute to understand the problem statement better?

**Comment by VenkateshPS** [comment]
Testing.xml used to run tests in parallel.
`<?xml version="1.0" encoding="UTF-8"?>

<suite name="VCS Android Automation test Run" parallel="tests" thread-count="3">

	<test name="vcsSingleDeviceregressiontest1">
	 <parameter name = "nodeIP" value = "127.0.0.1"/>
	  <parameter name = "port" value = "4723"/>
	   <parameter name = "DeviceID" value = "5210328dfaadb343"/>
	   <parameter name = "DeviceName" value = "Samsung A5"/>
	   
		<classes>
 		    <class name="com.vcs.GenieAsContactTests" />
			
		</classes>
	</test>
	
	<test name="vcsSingleDeviceregressiontest2">
	 <parameter name = "nodeIP" value = "127.0.0.1"/>
	  <parameter name = "port" value = "4725"/>
	   <parameter name = "DeviceID" value = "3208df540c2471a1"/>
	   <parameter name = "DeviceName" value = "Samsung S5"/>
		<classes>
		    
			<class name="com.vcs.SmokeTests" />
			
		</classes>
	</test>
	
	<test name="vcsSingleDeviceregressiontest3">
	 <parameter name = "nodeIP" value = "127.0.0.1"/>
	  <parameter name = "port" value = "4727"/>
	   <parameter name = "DeviceID" value = "1215fc20a4e53105"/>
	   <parameter name = "DeviceName" value = "Samsung S6"/>
		<classes>
		
		       
 			<class name="com.vcs.ConversationExpiryTest"/>  
		 	
		</classes>
	</test>
	</suite>`

ExtentListener class with Thread locking used for onStart, what I wanted was unique incremental value of variable testInstance, but for all the threads I get the value as 1.


[Extentlistener.txt](https://github.com/cbeust/testng/files/1362628/Extentlistener.txt)

**Comment by krmahadevan** [comment]
@VenkateshPS - I still don't understand what you are trying to do. Your issue has got nothing to do with TestNG.Here's a sample that shows how to get the count of `<test>` tags from within your listener.

**Test class**

```java
import org.testng.annotations.Test;

public class Issue1568Sample {
    @Test
    public void testMethod() { }
}
```

**Sample listener that counts the test tags**
```java
import org.testng.ITestContext;
import org.testng.TestListenerAdapter;

import java.util.concurrent.atomic.AtomicInteger;

public class Issue1568Listener extends TestListenerAdapter {
    private AtomicInteger counter = new AtomicInteger(0);

    @Override
    public void onStart(ITestContext testContext) {
        System.err.println("Running on thread [" + Thread.currentThread().getId()
                + "] for the test <" + testContext.getName() + ">");
        counter.incrementAndGet();
    }

    public int getCounter() {
        return counter.get();
    }
}
```

**Test runner**
```java
import org.testng.ITestNGListener;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.util.Arrays;
import java.util.Collections;

import static org.assertj.core.api.Assertions.assertThat;

public class Issue1568TestRunner {
    @Test
    public void testMethod() {
        XmlSuite suite = new XmlSuite();
        suite.setName("suite");
        suite.setTests(
                Arrays.asList(
                        createXmlTest(suite, "test_1", Issue1568Sample.class),
                        createXmlTest(suite, "test_2", Issue1568Sample.class)
                )
        );
        suite.setParallel(XmlSuite.ParallelMode.TESTS);
        TestNG testng = new TestNG();
        testng.setXmlSuites(Collections.singletonList(suite));
        Issue1568Listener listener = new Issue1568Listener();
        testng.addListener((ITestNGListener) listener);
        testng.setVerbose(3);
        System.err.println("Suite xml that will be used.");
        System.err.println(suite.toXml());
        testng.run();
        assertThat(listener.getCounter()).isEqualTo(2);
    }

    private XmlTest createXmlTest(XmlSuite suite, String testName, Class<?> clazz) {
        XmlTest test = new XmlTest(suite);
        test.setName(testName);
        test.setClasses(Collections.singletonList(new XmlClass(clazz)));
        return test;
    }
}
```

**Here's the output**
```bash
Suite xml that will be used.
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="suite" parallel="tests">
  <test name="test_1">
    <classes>
      <class name="com.rationaleemotions.github.issue1568.Issue1568Sample"/>
    </classes>
  </test> <!-- test_1 -->
  <test name="test_2">
    <classes>
      <class name="com.rationaleemotions.github.issue1568.Issue1568Sample"/>
    </classes>
  </test> <!-- test_2 -->
</suite> <!-- suite -->

===== Invoked methods
===== Invoked methods
        Issue1568Sample.testMethod()[pri:0, instance:com.rationaleemotions.github.issue1568.Issue1568Sample@3632be31] 909295153
=====
Issue1568Sample.testMethod()[pri:0, instance:com.rationaleemotions.github.issue1568.Issue1568Sample@370736d9] 923219673
=====
Running on thread [11] for the test <test_1>
Running on thread [12] for the test <test_2>
PASSED: testMethod
PASSED: testMethod

===============================================
    test_2
    Tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
    test_1
    Tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

===== Invoked methods
    Issue1568TestRunner.testMethod()[pri:0, instance:com.rationaleemotions.github.issue1568.Issue1568TestRunner@55f3ddb1] 1442045361
=====
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

**Comment by VenkateshPS** [comment]
@krmahadevan OK, Let me explain what I intended to do.

I have a class integer variable `private static int testInstance=1;`, which I wanted to increment in onStart() method of test listener class, now to avoid concurrent access to this variable  , I put a reentrant lock in the onStart method of listener.

With this lock in place I expect that even if I have multiple <tests> in my xml I should be able to increment my class variable in a sequential way, which I was not able to do.

Hope this clears what I am trying to do.

**Comment by krmahadevan** [comment]
@VenkateshPS - So in a nutshell you are trying to count the number of `<test>` tags in your suite xml file via your listener ? The same that I shared basically shows you how to do that, without the need for any locking etc., (Please refer to the samples that I shared above). There is nothing wrong with TestNG here. I think this is more of a query on how to do something using TestNG. I would suggest that you please post this query on the [testng google forums](https://groups.google.com/forum/#!forum/testng-users)
