### ISSUE TITLE
Sequence of tests when there are group and methods are involved in testng.xml

### ISSUE THREAD

**Issue by pranaybiswas2611** [cbeust/testng#1573]
### TestNG Version
6.11

###Steps
below gist contains the test from testng.xml 

https://gist.github.com/pranaybiswas2611/48e0fd2307e3fbe50b96d63c16fb8a4c

### Expected behavior
Sequence of testcases : 
1. Tests of 'exploreGoal' group from 'Explore' class sequentially as written in class
2. Tests of 'exploreGoal' from 'Goal' class sequentially as written in class
3. Methods of 'Concept' class sequentially which is mentioned above
4. last 'backtoHome' method

there is no priority inside @test of classes

### Actual behavior
1. Tests of 'exploreGoal' group from 'Explore' class is not sequentially as written in class, its according to alphabets 

and so on

please help out to get expected sequence of testcases.

**Comment by krmahadevan** [comment]
@pranaybiswas2611 - `groups` is a filtering mechanism to find out what tests to execute and what not to.

> Tests of 'exploreGoal' group from 'Explore' class is not sequentially as written in class

TestNG uses reflection to retrieve test methods in a class before it runs them. Reflection in Java doesn't guarantee that the order of methods retrieved will match the order in which they occur. That is why TestNG provides you with the `priority` attribute. Why not use it ?

@juherr - WDYT ?

**Comment by pranaybiswas2611** [comment]
@krmahadevan i think in 6.11 if i use priority in testmethods of classes which contains that particular group then it will work but those test methods are using in different tests as well and my scenario is contains some methods from group and some independent methods. so i think hardcoding priority is not a good solution in my case.

You can suggest some kind of workaround as well which will be generic for all kinds of combination.

**Comment by juherr** [comment]
As @krmahadevan said, the order of methods in a class is not specified and depends on the jvm implementation or even its version.

Instead of using "priority", you can use "dependsOnMethods" or use your own custom annotation and use it in your custom "IMethodInterceptor".

I close the issue because I don't see any issue here. But we are still open to discuss if you think there is an issue somewhere in your sample.
