### ISSUE TITLE
Eclipse-Plugin: Icons looks pixelated on HiDPI monitors

### ISSUE THREAD

**Issue by davidbilge** [cbeust/testng#1577]
### TestNG Maven-Plugin Version
6.12.0.201709050550

### Expected behavior
The icons in the TestNG-view look good on HiDPI monitors.

### Actual behavior
The icons looks pixelated

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

![image](https://user-images.githubusercontent.com/762988/31703733-3e8723d2-b3de-11e7-8e8b-282292a170fb.png)
(you need to click on the screenshot to see it in full resolution)

**Comment by krmahadevan** [comment]
@davidbilge - It would be great if you could file this in https://github.com/cbeust/testng-eclipse 
ping @missedone

**Comment by davidbilge** [comment]
Really sorry, I did not find the separate github project. I created https://github.com/cbeust/testng-eclipse/issues/363 there.

**Comment by krmahadevan** [comment]
@davidbilge - Thank you.
