### ISSUE TITLE
TestNG can not gaurantee the ExecutionListener Instance as singleton.

### ISSUE THREAD

**Issue by eyehwan** [cbeust/testng#1587]
### TestNG Version
TestNG 6.12

### Expected behavior
TestNG need to gaurantee the ExecutionListener Instance as singleton.

### Actual behavior
TestNG can not gaurantee the ExecutionListener Instance as singleton.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans
ALL.

### Test case sample
https://github.com/cbeust/testng/pull/1586/files 

`ExecutionListenerAndSuiteListener `implements two `ISuiteListener`, `IExecutionListener `interfaces. The field `testString `(**non-static**)in this listener initialized in `onExecutionStart`, would be used in `onStart(ISuite suite)`. 

The listener is added into both `parent.xml` and `child.xml` suite files. `child.xm`l is child suite of `parent.xml`. 

When we trigger the testng,
1.   `TestNG.addListener(ITestNGListener listener)` would scan listeners getting from parent and child suite files. 
The instance of `ExecutionListenerAndSuiteListener `(Marked as **InstanceA**) registered in parent.xml would be scaned firstly.  then **InstanceA** would be added into `TestNG.m_suiteListeners` and 'Configuration.m_executionListeners'. 
2.    The instance of this listener(Marked as **InstanceB**) registered in child.xml would be scaned secondly. Because `maybeAddListener(m_suiteListeners, suite)` would guarantee no duplicated listener would be added, **InstanceB** will **not** be added in `TestNG.m_suiteListeners` to replace InstanceA. 
**But**  `m_configuration.addExecutionListener((IExecutionListener) listener)` would replace **InstanceA** with **InstanceB** in 'Configuration.m_executionListeners'. 
3.    `onExecutionStart` belong to **InstanceB** would be invoked first, within it the field `testString = "initialized"`. 
4.    `onStart(ISuite suite)` belong to **InstanceA** would be invoked in the next step, when the field `testString` is invoked here, **NPE** would be thrown, because it is **non-static**, cannot be initialized in `onExecutionStart` by other instance.

**Comment by krmahadevan** [comment]
In a nutshell, this changeset ensures that when dealing with a suite or suites wherein the `IExecutionListener` is defined in both the `parent` and the `child` suite, only the one that is defined in the parent (which was what was found first) would get added and the one in the child suite would get discarded.  This is useful in scenarios wherein the same class resorts to implementing both the `ISuiteListener` and the `IExecutionListener` and they end up sharing states between the listener method calls.

**Comment by eyehwan** [comment]
@krmahadevan nice abstract :+1:
