### ISSUE TITLE
Started configuration method has wrong status and end time during execution

### ISSUE THREAD

**Issue by ariel777** [cbeust/testng#1590]
### TestNG Version
6.9.9

### Expected behavior
Started configuration method in the middle of execution should be reported as having status STARTED & end time should not be defined.

### Actual behavior
Started configuration method in the middle of execution reported as having status SUCCESS & defined end time (it equals to start time).

### Is the issue reproductible on runner?
- [x ] IntelliJ
(not tested on other runners)

### Test case sample

Test has loooong setup:

```java
public class ZWsLocalTest {
    @BeforeClass
    public void setupClass() throws Exception {
        Thread.sleep(12000000);
    }
...
}
```

Get `suite.getAllInvokedMethods();`  (suite is SuiteRunner) during execution of the setupClass()

1st InvokedMethod corresponds to setupClass()
```
[TestResult name=setupClass status=SUCCESS method=ZWsLocalTest.setupClass()[pri:0, instance:ZWsLocalTest@a6301f] output={null}]
```

So the method is still running while status is SUCCESS! It should be ITestResult.STARTED indeed.

```java
ITestResult testResult = invokedMethod.getTestResult();
testResult.getStartMillis() == testResult.getEndMillis()
```

`testResult.getEndMillis(): 1509557717177`

while method did not finish yet! Expected not defined (e.g. 0) returned by getEndMillis()

It leads to wrong custom report.

**Comment by krmahadevan** [comment]
@ariel777 

> Get suite.getAllInvokedMethods(); (suite is SuiteRunner) during execution of the setupClass()

Do you have a sample for where you would be doing this ? The sample test you have added merely adds a long setup method, but doesn't show the part wherein you are retrieving the status and the timings etc., Please help add that information as well here.

**Comment by krmahadevan** [comment]
Sample that can be used to reproduce the issue

```java
import java.util.concurrent.TimeUnit;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class TestclassSample {
  static int status;
  static long timestamp;

  @BeforeClass
  public void beforeClass(ITestContext context) throws InterruptedException {
    TimeUnit.SECONDS.sleep(1);
    ITestResult result = context.getSuite().getAllInvokedMethods().get(0).getTestResult();
    status = result.getStatus();
    timestamp = result.getEndMillis();
  }

  @Test
  public void testMethod() {
  }
}
```

```java
import org.assertj.core.api.Assertions;
import org.testng.ITestResult;
import org.testng.TestNG;
import org.testng.annotations.Test;

public class IssueTest {

  @Test
  public void testMethod() {
    TestNG testng = new TestNG();
    testng.setTestClasses(new Class[] {TestclassSample.class});
    testng.run();
    Assertions.assertThat(TestclassSample.timestamp).isLessThanOrEqualTo(0);
    Assertions.assertThat(TestclassSample.status).isNotEqualTo(ITestResult.SUCCESS);
  }
}
```

**Comment by ariel777** [comment]
Thank you for the fix!
