### ISSUE TITLE
The constructor removed from TestRunner would stop Eclipse working.

### ISSUE THREAD

**Issue by eyehwan** [cbeust/testng#1613]
### TestNG Version
latest

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

**Comment by missedone** [comment]
@eyehwan , could you paste the exception stacktrace here
