### ISSUE TITLE
Archive TestNG CI execution reports into github

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1615]
As a TestNG developer or contributor one would like to view the reports so that one can find out what went wrong etc.,

Currently TestNG does this by sharing a link at the end of the build job that takes one to the Gradle scans site, wherein the details on what failed can be obtained.

This issue is being logged to see if we can extract out our execution test results (only when the build is being run from within Travis CI) and have them published into the `gh-pages` branch of the repository https://github.com/testng-team/testng-travis-reports/

A high level overview on how this could be accomplished is available in this blog : http://blog.yuriy.tymch.uk/2013/03/sharing-travis-ci-generated-files.html

**Comment by juherr** [comment]
The idea is good, but it may not work on pull request builds because travis is not providing env vars (due to security issue if the pull request print the decrypted var).
I have the same problem with sonarqube analyze on pull requests :(

**Comment by vlsi** [comment]
@krmahadevan  , @juherr , how are you doing?

I just pushed "refine Guice integration" PR #2547, and I realized CI output is not very readable :)

My experience with pgjdbc suggests that it works great if the successful test execution does not print messages to stdout/stderr.
For example, https://github.com/pgjdbc/pgjdbc/pull/2113/checks?check_run_id=2573944079#step:8:294

What do you think if the test logging is reduced by default? I doubt you read it every time :)
I understand you have **a lot** of tests, however, it is likely there's a small fraction of tests that produce 80% of all the output.

**Comment by vlsi** [comment]
PS Have you considered migrating to GitHub Actions?

**Comment by krmahadevan** [comment]
@vlsi - We already have an integration with github actions. Please refer [here](https://github.com/cbeust/testng/tree/master/.github/workflows)

**Comment by vlsi** [comment]
No idea how I missed Actions. It is indeed there
