### ISSUE TITLE
Test cases with priority and dependsOnGroups dependencies, execution order is chaos.

### ISSUE THREAD

**Issue by eyehwan** [cbeust/testng#1616]
### TestNG Version
6.12
Take a test class for example: 
```
   @Test(groups = { "g1" }, priority = 2)
    public void t1() {
        System.out.println("test 1");
    }

    @Test(groups = { "g2" }, dependsOnGroups = "g1", priority = 0)
    public void t2() {
        System.out.println("test 2");
    }

    @Test(groups = { "g2" }, dependsOnGroups = "g1", priority = 1)
    public void t3() {
        System.out.println("test 3");
    }
```
### Expected behavior
Expected execution order: t1, t2, t3

### Actual behavior
Actual execution order: t1, t3, t2

### Is the issue reproductible on runner?
All

**Comment by GauravKumarQA** [comment]
Hi All,
I agree with your solutions.
But I am facing an issue in using depends-on in Testng.xml file within groups node.
Please suggest something. We have a existing framework which is on Testng version 6.9.9 and everything works as expected,But right now i am trying to upgrade my testNg with above 6.10 and my whole suit is hampered.

Please follow my question over stackoverflow.
https://stackoverflow.com/questions/52968603/depends-on-not-working-as-expected-with-testng-version-6-13-1

Thanks

**Comment by krmahadevan** [comment]
@GauravKumarQA - I have responded to your query on Stackoverflow.

**Comment by GauravKumarQA** [comment]
Thanks @krmahadevan . Worked for me.

**Comment by GauravKumarQA** [comment]
@krmahadevan 
I have tried to implement the latest version in my current existing framework.

I am getting an error while running from xml using eclipse.
============================================
[RemoteTestNG] failed to get TestNG version from class: java.lang.IllegalArgumentException: invalid version "7.0.0-": non-numeric "0-"
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] now trying to parse the version from MANIFEST.MF
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.0.0) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:121)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:49)
===================================================================

And when i am running from POM.XML its running but getting an error of Cyclic dependency in @Before Test

Are these known issues?
 Thanks

**Comment by krmahadevan** [comment]
@GauravKumarQA try removing priority and then running the tests.

If my memory serves me right, I dont think you can mingle priority and groups and then run the tests based on groups because both of these are basically mechanisms to order tests with priority being a soft dependency mechanism (if a higher priority method fails, the lower ones still get executed) whereas dependsOnGroups/dependsOnMethods is a hard dependency mechanism.

Also please note, if you are still facing problems, please open up a new issue instead of commenting on a closed issue, and add relevant sample that can be used to reproduce the problem.
