### ISSUE TITLE
Use Maven central dependencies when pushed on Maven central

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1627]
### TestNG Version
6.13

### Actual behavior
jcommander 1.69 is missing on maven central

Related to #1506

**Comment by cbeust** [comment]
I just deployed TestNG 6.13.1 to Maven Central, which depends on [JCommander 1.72, which is on Maven Central](http://search.maven.org/#artifactdetails%7Ccom.beust%7Cjcommander%7C1.72%7Cjar).
