### ISSUE TITLE
[Feature Request] Implicitly inject dataProviderClass into Factory meta-data

### ISSUE THREAD

**Issue by sskorol** [cbeust/testng#1631]
### TestNG Version
6.13.1

### Expected behavior

```java
public class FactoryTests {

    public FactoryTests() {
    }

    @Factory(dataProvider = "data")
    public FactoryTests(final int i) {
        // not important
    }

    @DataProvider
    public Object[] data() {
        return new Object[]{1, 2, 3};
    }

    @Test
    public void fakeTest() {
        // not important
    }
}
```

```java
public class DataProviderTransformer implements IAnnotationTransformer2 {

    @Override
    public void transform(final IFactoryAnnotation annotation, final Method testMethod) {
        if (!annotation.getDataProvider().isEmpty()) {
            // -> annotation.getDataProviderClass() == FactoryTests.class
        }
    }
}
```

If user hasn't specified `dataProviderClass` explicitly, it should be filled in with an actual factory class.

Note that such meta-data is required for [**test-data-supplier**](https://github.com/sskorol/test-data-supplier) library to implement a newly raised [**feature request**](https://github.com/sskorol/test-data-supplier/issues/48).

### Actual behavior

```java
public class DataProviderTransformer implements IAnnotationTransformer2 {

    @Override
    public void transform(final IFactoryAnnotation annotation, final Method testMethod) {
        if (!annotation.getDataProvider().isEmpty()) {
            // -> annotation.getDataProviderClass() == null
        }
    }
}
```

`dataProviderClass` is **null**, which makes impossible to introspect a class, where corresponding data provider is used. 

Well, in the above sample everything except data provider name is **null**. In such case transformer is not so useful.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
See above

**Comment by kool79** [comment]
Can you extract class from `Method`? When dataProviderClass is not set then provider is located in the same class as factory method (which is passes as `Method testMethod`)
```java
public class DataProviderTransformer implements IAnnotationTransformer2 {
    @Override
    public void transform(final IFactoryAnnotation annotation, final Method testMethod) {
        Class<?> clazz = null;  
        if (!annotation.getDataProvider().isEmpty()) {
            clazz = annotation.getDataProviderClass() != null 
                  ? annotation.getDataProviderClass()
                  : method.getDeclaringClass();
        }
    }
}

**Comment by sskorol** [comment]
@kool79 I wish I could, but `testMethod` is null in case of `Factory` usage with a constructor. I've mentioned it in the description:

```
everything except data provider name is null
```
