### ISSUE TITLE
Remove dependency on a pre-created jar for running unit tests for JarFileUtils

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1637]
The current unit tests for `JarFileUtils` viz., `JarFileUtilsTest` relies on a pre-created jar. We should be leveraging something such as https://github.com/shrinkwrap/shrinkwrap to have the jar generated at runtime for the tests to use.

The source code for the `testng-tests.jar` is being attached as well.

[testng-tests.zip](https://github.com/cbeust/testng/files/1529536/testng-tests.zip)

**Comment by eyehwan** [comment]
Here I attched what I have updated for testng-tests for #1635 
[testng-tests.zip](https://github.com/cbeust/testng/files/1586794/testng-tests.zip)
