### ISSUE TITLE
Run different data sets for each test in a sequence for each loop using one common data provider

### ISSUE THREAD

**Issue by Brad19** [cbeust/testng#1638]
### TestNG Version
Version: 6.11

### Expected behavior
The point here that i'm expecting is to iterate the data sets for each tests under one common data provider, in such a way that each test should be running its own data in a sequence till all tests are completed and then move to next iteration. This is bit tricky to explain. 

**For eg., data from code snippet is below**

verifyPersonalRegoPageWindow - {{"Rego step1"} ,{"Rego step1"}}
validateAndCompletePersonalRegoForm_FirstPage -  {{"Australia", dataGen.getEmail(firstName), "Model"}, {"United States of America", dataGen.getEmail(firstName), "Model"}}
validateAndCompletePersonalRegoForm_SecondPage - {{ "Mr", firstName, "Model"},{ "Mrs", someName, "Model"}} 
validateAndSubmitPersonalRegoForm_ThirdPage - {{"AUD", "USD"}, {"USD", "NZD"}

**Given the data , I would like to run like the following**
1st iteration
verifyPersonalRegoPageWindow - {"Rego step1"}
validateAndCompletePersonalRegoForm_FirstPage- {"Australia", dataGen.getEmail(firstName)} 
validateAndCompletePersonalRegoForm_SecondPage - { "Mr", firstName, "Model"}
validateAndSubmitPersonalRegoForm_ThirdPage - {"AUD", "USD"}

2nd iteration
verifyPersonalRegoPageWindow - {"Rego step1"}
validateAndCompletePersonalRegoForm_FirstPage- {"United State of America", dataGen.getEmail(firstName)} 
validateAndCompletePersonalRegoForm_SecondPage - { "Mr", someName, "Model"}
validateAndSubmitPersonalRegoForm_ThirdPage - {"USD", "NZD"}

Please find my code snippet below.

```java 
@DataProvider(name ="PersonalRego")
 public Object[][] credentials(Method method) {

      String firstName=dataGen.getFirstname(); 
      if (method.getName().equals("verifyPersonalRegoPageWindow")) {
            return new Object[][]{{"Rego step1"}, {"Rego step1"}};
        } else if (method.getName().equals("validateAndCompletePersonalRegoForm_FirstPage")) {
            return new Object[][] { {"Australia", dataGen.getEmail(firstName), "Model"}, {"United States 
             of America", dataGen.getEmail(firstName), "Model"} };
        } else if (method.getName().equals("validateAndCompletePersonalRegoForm_SecondPage")) {
            return new Object[][] { { "Mr", firstName, "Model"}, { "Mr", firstName, "Model"} };
        } else if (method.getName().equals("validateAndSubmitPersonalRegoForm_ThirdPage")) {
            System.out.println("calling dp for third page");
            return new Object[][] { {"AUD", "USD"}, {"USD", "NZD"}};
        } else if (method.getName().equals("resetApplication")) {
            return new Object[][]{ {"reset"} };
        } else {
            return new Object[][]{};
        }
 }
```

### Actual behavior
At the moment if I don't provide the second data in each data sets. ie., for e.g., {"United States 
of America", dataGen.getEmail(firstName), "Model"} for validateAndCompletePersonalRegoForm_FirstPage and for others, it all works good. But when I provide the second data set for each Test, then it tries to run group of data for one test and there by it fails. 

PFA for the same 
![image](https://user-images.githubusercontent.com/10935246/33593388-4625c3ca-d9e3-11e7-938a-2fcdf9fd60c1.png)

If someone could advise on this, that'll be great and timely.

Thanks,
Brad

**Comment by kool79** [comment]
You are trying to use dataprovider in wrong way. You must not use it to create dependent steps/tests.
You cannot sync different test-methods on data-rows from data-provider. 
Consider to use @Factory and pass testdata as parameter to constructor.  This test-data should include all params, required for one iteration. To run tests in specific order use parameter `dependOnMethods` for @Test annotation.
  Below is example for DataProvider and Factory (it can have mistakes, I just wrote it):
```java

class RegoData{
	String currency, firstName, email;
	public static RegoData generate(){
		return  new RegoData();  // generate new
	}
}


class RegoFlow {
	private final RegoData regoData;

	@DataProvider
	private static Object [][] regoDataProvider() {
		return new Object[][]{
				new Object[]{RegoData.generate()},
				new Object[]{RegoData.generate()}
		};
	}

	@Factory(dataProvider = "regoDataProvider")
	public RegoFlow(RegoData regoData) {
		this.regoData = regoData;
	}

	@Test
	public void verifyPersonalRegoPageWindow() {/* ...*/}

	@Test(dependsOnMethods = "verifyPersonalRegoPageWindow")
	public void validateAndCompletePersonalRegoForm_FirstPage() {
		// form.field = regoData.email;
	}

	@Test(dependsOnMethods = "validateAndCompletePersonalRegoForm_FirstPage")
	public void validateAndCompletePersonalRegoForm_SecondPage() {
		// form.field = regoData.currency;
	}

	@AfterClass(alwaysRun = true)
	public void reset(){/*...*/}
}
```
Example here: http://opensource-soa.blogspot.com/2015/06/testng-using-factory-and-dataprovider.html
**_Note:_** You need to set group-by-instances = true to have desired execution order. 
Also testNG does not guarantee that execution order will be same as provided in regoDataProvider()

**Comment by Brad19** [comment]
Thanks for your response. I tried the similar @factory method approach yesterday after i posted my issue, but still i see the similar result

```
public class SampleFactory {
    DataGenerators dataGen;
    @Factory(dataProvider="dp")
    public Object[] createInstances(String country, String email, String firstName, String securityQuestion, String title, String ccyFrom, String ccyTo) {
        return new Object[] {new PersonalRegoTest(country, email, firstName, securityQuestion, title, ccyFrom, ccyTo)};
    }
    @DataProvider(name="dp")
    public static Object[][] dataProvider() {
        Object[][] dataArray = {
                {"Country1", "test@testmail.com","abc", "Model", "Mr", "AUD", "USD"},
                {"Country2", "test1@testmail.com","abcd", "Model", "Mr", "USD", "NZD"}               
        };
        return dataArray;
    }
}

And my PersonalRegoTest is as follows

    public class PersonalRegoTest extends Appium {
    PersonalRego personalRego;
    DataGenerators dataGen;
    String country="";
    String email="";
    String firstName="";
    String securityQuestion="";
    String title="";
    String ccyFrom="";
    String ccyTo="";`

    PersonalRegoTest(String country, String email, String firstName, String securityQuestion, String t 
   title, String ccyFrom, String ccyTo) {
        super();
        this.country = country;
        this.email = email;
        this.firstName = firstName;
        this.securityQuestion = securityQuestion;
        this.title = title;
        this.ccyFrom = ccyFrom;
        this.ccyTo = ccyTo;
    }
    @BeforeClass(alwaysRun = true)
    public void initialize() throws IOException {
        personalRego = new PersonalRego(driver, System.getProperty("platform"));
        dataGen = new DataGenerators();
    }
    @Test(priority = 1, alwaysRun=true, description="select of Personal Rego form", groups="personalRego")
    public void verifyPersonalRegoPageWindow() {
        personalRego.isPersonalRegoWindowDisplayed();
    }
    @Test(priority = 2, alwaysRun=true, description = "fill step 1 of Personal Rego form", groups="personalRego")
    public void validateAndCompletePersonalRegoForm_FirstPage() {
        ...
    }
    @Test(priority = 3, alwaysRun=true, description = "fill step 2 of Personal Rego form", groups="personalRego", dependsOnMethods = "validateAndCompletePersonalRegoForm_FirstPage")
    public void validateAndCompletePersonalRegoForm_SecondPage() {
        ...
    }
    @Test(priority = 4, alwaysRun=true, description = "fill step 3 of Personal Rego form", groups="personalRego", dependsOnMethods = {"validateAndCompletePersonalRegoForm_FirstPage", "validateAndCompletePersonalRegoForm_SecondPage"})
    public void validateAndSubmitPersonalRegoForm_ThirdPage() {
       ...
    }
    @Test(priority = 5, alwaysRun=true, description = "Last step of Personal Rego form to reset app", groups="personalRego", dependsOnMethods = {"validateAndSubmitPersonalRegoForm_ThirdPage"})
    public void resetApplication(String reset) {
        System.out.println("reset application ");
        ..
    }

PFA the similar result as like before. Please advise me if i'm doing something wrong now

![image](https://user-images.githubusercontent.com/10935246/33634862-cb25b2d4-da69-11e7-8e4a-3ab7417268f8.png)

**Comment by kool79** [comment]
• Use dependsOnMethod only. Don't use priority. Scope of priority is not limited by single class (or class instance). It much wider and limited by <test> tag (see testng.xml)  When you have several instances with tests (actually you have at least 2 instances)  then testng will run ALL tests (from different instances) with priority=1 and after they finished -> starts to run with  priority=2 etc. 
• You MUST set parameter group-by-instances = true in testng.xml (tag <test>).  BTW I don't know what has higher priority: `group-by-instances` or `priority`.  So if 
• If you use IDE to run your tests, make sure that group-by-instances = true is included in generated testng.xml file. For example, when you run test in IntelliJ IDEA from context menu on class, IDEA generates temporary file but in does not have this parameter. To run in IDEA you should create valid my-testng.xml and then run tests from context menu on this file. (I did not found how to set this via custom Run/Debug Configuration in IDEA)

_Other notes:_
• For _ThirdPage it is not required to depend on _FirstPage
• Why you use groups? it is not required . BTW if still need groups you can define group name at class level in @Test annotation. It will be applied to every test-method and configuration-method in this class.

**Comment by kool79** [comment]
Below is working example:
**SampleFactory.java:**
```java
public class SampleFactory {

	@DataProvider
	public static Object[][] dataProvider() {
		return new Object[][]{
				{"Country1", "test@testmail.com"},
				{"Country2", "test1@testmail.com"}
		};
	}

	@Factory(dataProvider="dataProvider")
	public Object[] createInstances(String country, String email) {
		return new Object[] {new PersonalRegoTest(country, email)};
	}
}```
**PersonalRegoTest:**
```java
// define groups for all methods (nor required)
@Test(groups="personalRego")
public class PersonalRegoTest {
	final String country;
	final String email;

	PersonalRegoTest(String country, String email) {
		super();
		this.country = country;
		this.email = email;
	}

	@BeforeClass
	public void initialize(){
		System.out.println("initialize for " + country);
	}

	@Test(description = "select of Personal Rego form",
	      alwaysRun = true)
	public void step1() { System.out.println("step1 for " + country);}

	@Test(description = "fill step 1 of Personal Rego form",
	      dependsOnMethods = "step1",
	      alwaysRun = true)
	public void step2() {
		System.out.println("step2 for " + country);
	}

	@Test(description = "fill step 2 of Personal Rego form",
	      dependsOnMethods = "step2",
	      alwaysRun = true)
	public void step3() {
		System.out.println("step3 for " + country);
	}

	@Test(description = "fill step 3 of Personal Rego form",
	      alwaysRun = true,
	      dependsOnMethods = "step3")
	public void step4() {
		System.out.println("Step4 for " + country);
	}

	@AfterClass(alwaysRun = true)
	public void resetApplication() {
		System.out.println("reset application for " + country);
	}
}
```
**my-testng.xml**:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Automation Regression">
  <test name="Personal Registration" group-by-instances="true">
    <classes>
      <class name="qa.tests.SampleFactory"/>
    </classes>
  </test>
</suite>
```

**Comment by kool79** [comment]
@juherr , I think this issue can be closes because of no issue ))

**Comment by juherr** [comment]
@kool79 Thanks for the explanation. You should contribute to the mailing list/StackOverflow too ;)

**Comment by Brad19** [comment]
@here Thanks all for your help. The problem was with priority in each Test methods. After removing it started working find.

**Comment by NaderMonigle** [comment]
I am attempting the same issue, where my methods need to run in a specific order but using data provider it always runs method 1 through all data sets first. I have "group-by-instances = true" in my XML and my methods have "dependsOnMethods" set for each one. Yet none of these change the order in which my TestNG suite runs the methods in regards to the data set. Is factory required for this to work? Should I separate my dataProvider method into another class and add factory?

**Comment by NaderMonigle** [comment]
This is my one class I am trying to run:

`	


        public class pagesTests {
	         // WebDriver Setup
	         static WebDriver driver;
	
	         // set values for Site and Login parameters
	         private String URL;
	         private String username;
	         private String password;

       @Factory(dataProvider="getData")
	public pagesTests(String URL, String username, String password) {
		this.URL = URL;
		this.username = username;
		this.password = password;
	}
	
	@DataProvider
	public static Object[][] getData()
	{
	   Object [][] myData = 
                        {{"http://test1.net/site/login","root@monigle.com","HoneyBadger$1"},
	                 {"http://test2.net/site/login","root@monigle.com","HoneyBadger$1"},
	                 {"http://test3.net/site/login","root@monigle.com","HoneyBadger$1"},
	                 {"http://test3.net/site/login","root@monigle.com","HoneyBadger$1"},
	                 {"http://test4.net/site/login","root@monigle.com","HoneyBadger$1"},
	                 {"http://test5.net/site/login","root@monigle.com","HoneyBadger$1"}};
	   return myData;
	}

       	@Test(dataProvider="getData", alwaysRun = true)
	public void addPage(String URL, String username, String password) throws InterruptedException, 
        AWTException {	

                // Open Site
		driver.get(URL);

                // Login to site
		Thread.sleep(1000);
		driver.findElement(By.id("LoginForm_email")).sendKeys(username);
		driver.findElement(By.id("LoginForm_password")).sendKeys(password);
		Robot enter = new Robot();
		enter.keyPress(KeyEvent.VK_ENTER);
		enter.keyRelease(KeyEvent.VK_ENTER);

                }
	@Test(dependsOnMethods="addPage", dataProvider="getData", alwaysRun = true)
	public void permissionsTest(String URL, String username, String password) throws 
        InterruptedException, AWTException {

                // Open Site
		driver.get(URL);

                // Login to site
		Thread.sleep(1000);
		driver.findElement(By.id("LoginForm_email")).sendKeys(username);
		driver.findElement(By.id("LoginForm_password")).sendKeys(password);
		Robot enter = new Robot();
		enter.keyPress(KeyEvent.VK_ENTER);
		enter.keyRelease(KeyEvent.VK_ENTER);
                }

	@Test(dependsOnMethods= {"addPage", "permissionsTest"}, dataProvider="getData", alwaysRun = 
        true)
	public void deletePage(String URL, String username, String password) throws InterruptedException, 
        AWTException { 

                // Open Site
		driver.get(URL);

                // Login to site
		Thread.sleep(1000);
		driver.findElement(By.id("LoginForm_email")).sendKeys(username);
		driver.findElement(By.id("LoginForm_password")).sendKeys(password);
		Robot enter = new Robot();
		enter.keyPress(KeyEvent.VK_ENTER);
		enter.keyRelease(KeyEvent.VK_ENTER);
                }
         }
`
Here is the XML:
`


           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
           <suite name="Suite">
              <test name="ChromeTest" group-by-instances="true">
  	         <parameter name="browser" value="Chrome" />
  		     <classes>
  			    <class name="clearchoice.pagesTests"></class>
  		     </classes>
               </test> 
            </suite> 
`

No matter what I do, the suite always runs as follows:

Test Method 1 (Data set 1)
Test Method 1 (Data set 2)
Test Method 1 (Data set 3)
...

Test Method 2 (Data set 1)
Test method 2 (Data set 2)
Test Method 3 (Data set 3)

I am looking to keep the methods of the class in order for each data set since they have dependencies:
Test Method 1 (Data set 1)
Test Method 2 (Data set 1) 
Test Method 3 (Data set 1)
