### ISSUE TITLE
Test case execution order not as expected when using priority and dependsOnMethods

### ISSUE THREAD

**Issue by dslaveykov** [cbeust/testng#1645]
### TestNG Version
6.13.1

### Expected behavior
Before Test1 class
Class Test1; method testB
Class Test1; method testC
Class Test1; method testA
After Test1 class
Class Test2; method testE
Class Test2; method testF
Class Test2; method testD

### Actual behavior
Class Test2; method testE
Class Test2; method testF
Before Test1 class
Class Test1; method testB
Class Test1; method testC
Class Test2; method testD
Class Test1; method testA
After Test1 class

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
[files.zip](https://github.com/cbeust/testng/files/1563012/files.zip)

**Comment by juherr** [comment]
The current behavior is the expected one: `priority` is scoped on all the suite, not only the class. 

So TestNG is executing lower priorities first (testB/testC/testE/testF).
`testB` must be before the `testC` and `testE` must be before `testF` (which is the case).
Many orders are valid and not specified: testB/testC/testE/testF, testE/testF/testB/testC, testB/testE/testF/testC, ...
