### ISSUE TITLE
Depends on method is not respected on the sequential run on second test that extends same base testClass

### ISSUE THREAD

**Issue by nikolmarku** [cbeust/testng#1648]
### TestNG Version : 6.13.1  6.13 6.11
> Note: only the latest version is supported

Maven surefire  2.20.1 2.20
I have Checked only those versions 

I have two concrete Test Classes 
TestOne
TestTwo
They both extend class B that extends Class A. 
Abstract class A and B have 2 test each and I need to run them in order: 
A -> Test one then Test two
 then 
      B - Test one then test two

If I run the test using IDE one by one all is fine test run in order same if I run using maven.

If I run those test together[single thread one at the time] in IDE or maven The first Test run tests in order but the second Test the order is not the same and as they extend same Base class should be the same.

If I run the test in parallel the order is preserved..

Could you kindly advice how to make sure when running the test sequentially the order of execution is preserved even after the first test running [that extends the same base]

### Expected behavior
```
A TestOne 1 ........
A test Two  ........
B test 1 ........
B test 2........

A TestOne 1 ........
A test Two  ........
B test 1 ........
B test 2........
```

### Actual behavior
"B test 1" is executed after "A TestOne 1" and should be executed after "A test Two "

### Is the issue reproductible on runner?

- [x] Maven
- [x] IntelliJ

```
A TestOne 1 ........
A test Two  ........
B test 1 ........
B test 2........
```
-----------------------------
```
A TestOne 1 ........
B test 1 ........
A test Two  ........
B test 2........
```

Note:
Maven Profile
threadCount = 1
maven surefire plugin 
```xml
                             <forkCount>${threadCount}</forkCount>
                            <parallel>suites</parallel>
                            <threadCountClasses>${threadCount}</threadCountClasses>
```

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
public abstract class A {
    @Test
    protected void test1(){       System.out.println("A TestOne 1 ........");    }

    @Test(dependsOnMethods = {"test1"} )
    protected void test2(){        System.out.println("A test Two  ........");    }
}

public abstract class B extends A {
    @Test(dependsOnMethods = {"test2"})
    protected void test3(){     System.out.println("B test 1 ........"); }

    @Test(dependsOnMethods = {"test3"})
    protected void test4(){  System.out.println("B test 2........");    }
}

public class TestOne extends B {
}
public class TestTwo extends B {
}
```

Thank you for your help

**Comment by juherr** [comment]
Thanks for the report, could you try to run your test into an IDE like IntelliJ or Eclipse. Do you reproduce the issue?

**Comment by nikolmarku** [comment]
yes same issue running on cmd with maven or IDE intellij

**Comment by juherr** [comment]
Oops, sorry, I didn't see IntelliJ the first time :)

**Comment by nikolmarku** [comment]
Hi Juherll,

Could you advice an ETA on this major issue please ?

**Comment by juherr** [comment]
No planned ETA. Maybe you can propose a fix yourself?
