### ISSUE TITLE
Assert.assertEquals(Object[][], Object[][]) fails since 6.9.10

### ISSUE THREAD

**Issue by d1ss0nanz** [cbeust/testng#1661]
### TestNG Version
All versions >= 6.9.10

### Expected behavior
Assert.assertEquals(Object[][], Object[][])  should compare the contents of the inner Object[]

### Actual behavior
Assert.assertEquals(Object[][], Object[][]) fails, while up to TestNG 6.9.10 it succeeded

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
        final Object[][] actual =
            new Object[][]
            { { TestCase.POSITIVE, 0, "hello" }, { TestCase.POSITIVE, 1, "world" }, { TestCase.NEGATIVE, null, "!" } };
        final Object[][] expected =
            new Object[][]
            { { TestCase.POSITIVE, 0, "hello" }, { TestCase.POSITIVE, 1, "world" }, { TestCase.NEGATIVE, null, "!" } };

        Assert.assertEquals(actual, expected);

**Comment by juherr** [comment]
Linked to #870 and #790
