### ISSUE TITLE
addListener deprecated?

### ISSUE THREAD

**Issue by jakehm** [cbeust/testng#1683]
### Test case sample
```
TestNG tng = new TestNG();
TestListenerAdapter tla = new TestListenerAdapter();
tng.addListener(tla);

```
This is an example taken from documentation. It is marking `addListener` as deprecated. What else should be used instead then? And shouldn't the documentation be updated?

**Comment by juherr** [comment]
The specific methods are deprecated.

And according the javadoc:

> Use addListener(ITestNGListener) instead

```java
TestListenerAdapter tla = new TestListenerAdapter();
tng.addListener((ITestNGListener) tla);
```
