### ISSUE TITLE
Unable to run parallel tests in Selenium 3, the same code is working fine selenium 2

### ISSUE THREAD

**Issue by suresh02** [cbeust/testng#1684]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Two browsers should open at a time

### Actual behaviour
Second browser is opening after completing execution of first browser

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

XMl file
```xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Suite" parallel="tests">

 <test name="FirefoxTest">

 <parameter name="browser" value="firefox" />

 <classes>

 <class name="test1.Multibrowser" />

 </classes>

 </test>

 <test name="ChromeTest">

 <parameter name="browser" value="chrome" />

 <classes>

 <class name="test1.Multibrowser" />

 </classes>

 </test>

</suite> 
```

**Comment by krmahadevan** [comment]
This is a #1636 which has been fixed and released as part of `6.14.2`. Please retry using the latest version.
