### ISSUE TITLE
Continue WebDriver test execution, when element is not visible/clickable

### ISSUE THREAD

**Issue by plaidshirtakos** [cbeust/testng#1685]
### TestNG Version
6.14.2

### Expected behavior
In case element isn't visible or not clickable, it should write to log currently executed class and method name with an error message.

### Actual behavior
Test should be continued in case of failure, instead of exit with exception.

### Test case sample
I have a Selenium WebDriver based testsuite. XPATH on site are changing sometimes, so I would like to use this to identify which XPATH has to be refreshed.

**Comment by kool79** [comment]
> In case element isn't visible or not clickable, it should write to log currently executed class and method name with an error message.
All this info you can found in the stacktrace for error in failed test.
>Test should be continued in case of failure, instead of exit with exception.
what do you expect from such test?  Tonnes of errors for every code line??  Please learn java (or any programming language)  before reporting such issues.

**Comment by krmahadevan** [comment]
This issue doesn't seem to look like its related to TestNG. 

@plaidshirtakos - I would strongly encourage you to post your query on the selenium-users google forum.

I am closing this issue.
