### ISSUE TITLE
Defining dataProviderClass in a subclass

### ISSUE THREAD

**Issue by sonOfRa** [cbeust/testng#1691]
I'm not sure if this is even possible, but I've got a few test cases where I can run the same tests for two implementations of a class, however they require different input data. So I've created a shared superclass for both tests, and set the tests with ``@Test(dataProvider = "myProvider")``. Then, in the actual test classes, I set ``@Test(dataProviderClass = Provider.class)``. Provider has a method annotated as a ``@DataProvider`` and named ``myProvider``
### TestNG Version
6.14.2
### Expected behavior
TestNG should pick up the dataProviderClass set in the subclasses

### Actual behavior
TestNG fails with an error (stacktrace is attached in the gist below), complaining about a missing dataprovider.

Things work fine if I move the methods from ``Provider`` into the test classes as well, it just doesn't seem to work when I separate the providers into a separate class.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
https://gist.github.com/sonOfRa/dd337372e75b8a86fa68aeac6d0094ef

**Comment by krmahadevan** [comment]
@sonOfRa - No that's not possible the way in which you are trying to do. If you make use of `@Test(dataProvider = "externalHashes")` then it will cause TestNG to ONLY look for a data provider named `externalHashes` in the current class and TestNG won't club its value with the `@Test` annotation that you provided at the class level, at least not afaik. But you can make use of something like this to get past your issue.

First define a custom annotation that lets you express the data provider class and name.

```java
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.METHOD;

@Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
@Target({METHOD})
public @interface DataProviderInformation {
    String name();

    Class<?> dataProviderClass();
}
```

You now build a generic data provider adaptor, which will have the ability to patch through the call to an actual underlying data provider. It would look like below

```java
import org.testng.annotations.DataProvider;
import org.testng.internal.reflect.ReflectionHelper;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.stream.Stream;

public class DataProviderAdapter {

    @DataProvider(name = "getData")
    public static Object[][] getData(Method method) throws InvocationTargetException, IllegalAccessException {
        DataProviderInformation info = method.getAnnotation(DataProviderInformation.class);
        if (info == null) {
            return new Object[][]{
                    {"Jack"},
                    {"Daniels"}
            };
        }

        Class<?> clazz = info.dataProviderClass();
        String dpName = info.name();
        Method[] methods = ReflectionHelper.excludingMain(clazz);
        Method found = Stream.of(methods).filter(method1 -> {
                    DataProvider dp = method1.getAnnotation(DataProvider.class);
                    return dp != null &&
                            (dp.name().equalsIgnoreCase(dpName) || method1.getName().equalsIgnoreCase(dpName));

                }
        )
                .findFirst().orElseThrow(IllegalArgumentException::new);
        return (Object[][]) found.invoke(new Object[] {});
    }
}
```

And now here's a few data provider implementations that give different types of data.

```java
import org.testng.annotations.DataProvider;

public class BooleanProvider {

    @DataProvider(name = "getData")
    public static Object[][] getData() {
        return new Object[][]{
                {true},
                {false}
        };
    }
}
```

```java
import org.testng.annotations.DataProvider;

public class NumbersProvider {
    @DataProvider(name = "getData")
    public static Object[][] getData() {
        return new Object[][]{
                {1},
                {2},
                {3}
        };
    }
}
```

finally here's the test case

```java
import org.testng.annotations.Test;

public class TestClass {

    //Ask for a boolean data provider
    @DataProviderInformation(dataProviderClass = BooleanProvider.class, name = "getData")
    @Test(dataProvider = "getData", dataProviderClass = DataProviderAdapter.class)
    public void consumesBoolean(boolean flag) {
        System.err.println("Got the boolean " + flag);
    }

    //Ask for a number data provider
    @DataProviderInformation(dataProviderClass = NumbersProvider.class, name = "getData")
    @Test(dataProvider = "getData", dataProviderClass = DataProviderAdapter.class)
    public void consumesNumbers(int number) {
        System.err.println("Got the number " + number);
    }

    //fall back to using the default data provider data
    @Test(dataProvider = "getData", dataProviderClass = DataProviderAdapter.class)
    public void consumesString(String txt) {
        System.err.println("Got the text " + txt);
    }

}
```

You should be able to extend this example to your use case and apply it there as well.

Please let me know if this would work for you and if we can close off this issue.

**Comment by juherr** [comment]
@krmahadevan Do you think it is something we can do? I don't see any functional issue if the data provider definition is in a child class and its usage in a parent class.

**Comment by krmahadevan** [comment]
@juherr - I did ponder over it. But since TestNG always overrides the values of `@Test` set at the class level, with the values of `@Test` set at the method level, I think its going to be a bit tricky because, if a user sets the data provider information at the class level and then expects it to be cascaded over to the method level, it wont happen (That is what the user's use case is, in this case)

**Comment by juherr** [comment]
What is the problem here? The `dataProviderClass` value is lost between the class level and the method level?

**Comment by sonOfRa** [comment]
I've ended up just using my first workaround, that is, simply having the dataProvider methods in the subclasses, which works. Something that I've used successfully in Tests without inheritance is this:

```java
@Test(dataProviderClass = MyProvider.class)
public class MyTest {
    @Test(dataProvider = "one")
    public void testOne(String foo, String bar) {
        //...
    }

    @Test(dataProvider = "two")
    public void testTwo(String bar) {
        //...
    }
}
```

```java
public class MyProvider {
    @DataProvider
    public Object[][] one { return new Object[][] { {"foo", "bar" }, {"baz", "quux"}; }
    @DataProvider
    public Object[][] two { return new Object[][] { {"foo"} };
}
```

This setup works, it just doesn't seem to work if inheritance comes into play.

**Comment by sskorol** [comment]
@sonOfRa it should work in [test-data-supplier](https://github.com/sskorol/test-data-supplier). Check it please. Note that IntelliJ plugin will be updated in several days to support such syntax.

**Comment by sskorol** [comment]
Finally supported on IDEA level:
[![demo](http://img.youtube.com/vi/A5aU0l4ed4o/0.jpg)](https://www.youtube.com/watch?v=A5aU0l4ed4o)
