### ISSUE TITLE
Need ability to mark "failed but up for retry" tests differently from "skipped" tests

### ISSUE THREAD

**Issue by vishveshmulay** [cbeust/testng#1697]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
The details are captured at https://groups.google.com/forum/#!topic/testng-users/WCiSM9mE_5k

I have a framework which at the end of every test case execution pushes all the metadata information about that execution to ELK stack and shows various trends etc on the kibana dashboard.  

This includes all of the metadata including test execution status  which can be one of 1. success 2. failure 3. skip

I have a RetryAnalyzer implementation that retries failed tests 3 times and it marks the failed tests as "SKIP" if they are up for a retry, 

What that does is , once the retryAnalyzer is executed on the failed test, the status gets updated to SKIP and it shows it that way on our dashboard and after retry we show one more execution as either success or failure .

We have hundreds of test cases and each test case execution time is quite significant (These are E2E functional test cases) So we want to minimize the retries by fixing the underlying inconsistencies.   To get the clear idea of what types of tests are inconsistent (so in turn have to be retried) we need to post execution info for EACH test case run.  So we are posting info even for the skipped ones. 

However there are 2 cases when tests can be marked as "SKIP" 
1. where tests are skipped BEFORE they are executed  for reasons below
          a. When a configuration method fails.
          b. When a test method depends on another method and the original method fails, causing the 
               dependent method to be skipped.
         c. When a data provider has a problem 
2.  Where Test is marked as "SKIP" AFTER it is executed and it fails but is up for a retry
This feels like overloading the definition of SKIP and when we see a test with this status we are not sure whether it has been skipped because of # 1 above or # 2 

What we would like is a different status enum which marks the status correctly for the tests that failed but are going to be retried.

### Actual behavior
NOT sure what to put here.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by vishveshmulay** [comment]
@krmahadevan  This is the issue logged as per your suggestion on the google group.

Again, thanks for spending time on this.

**Comment by krmahadevan** [comment]
ping @juherr @cbeust - What do you think ? Please let me know.

**Comment by juherr** [comment]
I think we should do something, but we already had the discussion on https://github.com/cbeust/testng/issues/878 and maybe other retry-analyzer issues https://github.com/cbeust/testng/issues?utf8=%E2%9C%93&q=label%3A%22Feature%3A+retry-analyzer%22+

If you find an easy way go ahead but it could imply a lot of changes.

**Comment by eyehwan** [comment]
In my test framework, I mark retry result as RERUN instead of SKIP defined in TestNG. In the final result statistics, I remove SKIP (marked as RERUN) from skipped test case list, which would make statistics correct.

**Comment by juherr** [comment]
@eyehwan Could you elaborate? Where and how do you mark result as RERUN?

**Comment by eyehwan** [comment]
In my own test framework, I mark test result as RERUN in IRetryAnalyzer.retry.
But if consider it in TestNG, I would put it to Invoker.handleInvocationResults if (willRetry){testResult.setStatus(ITestResult.RERUN);}
Of course, surrounding handlings like ITestListener, verdict handlings, statistics handling etc should also be considerred.
