### ISSUE TITLE
Test ignored if @BeforeMethod in base class fails for another test class

### ISSUE THREAD

**Issue by kateleiza** [cbeust/testng#1700]
### TestNG Version
latest (TestNG 6.15.0-SNAPSHOT)

### Expected behavior
test2 is not ignored, because setUp for test2 successfully finished

### Actual behavior
test2 ignored

### Is the issue reproductible on runner?
IntelliJ

### Test case sample
```java
public class BaseClass {

    @BeforeMethod(alwaysRun = true)
    public void setUp(Method method) {
        if (method.getName().contains("test1"))
            Assert.assertEquals(2, 1);
    }

}
public class MyTest3 extends BaseClass {

    @Test
    public void test1() {
       System.out.print("test1");
    }

}
public class MyTest4 extends BaseClass {

    @Test
    public void test2() {
        System.out.print("test2");
    }

}
```

**Comment by juherr** [comment]
Thanks for the report.

@krmahadevan Do you have free time to have a look at it?

**Comment by krmahadevan** [comment]
@juherr - I will take a look at this.
