### ISSUE TITLE
The  report emailable-report.html is not available either  onTestSuccess neither onFinish(ISuite suite)

### ISSUE THREAD

**Issue by Anda77** [cbeust/testng#1708]
### TestNG Version
> 6.11

### Expected behavior
The report emailable-report.html  is available in onFinish(ISuite suite) when run my test case from command line

### Actual behavior
The report emailable-report.html  is not available in onFinish(ISuite suite) when run my test case from command line

### Is the issue reproductible on runner?

- [ X] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
>I created a jar file that contains all test classes. 
I tried to run my test case from CMD. jar - jar 'Namejar'  xmlfile - OK
I set to send emails on the method onFinish(ISuite suite) and added  this add this listener in my xml file.
The test case is run programatically from the main method.

**Comment by krmahadevan** [comment]
TestNG will kick off report generation only after all the `<suite>` have run to completion. 

`onFinish(ISuite suite)` is the last step of suite execution, and only after it runs will TestNG start report generation.

You should be implementing `org.testng.IExecutionListener` and plugging in the logic of sending emails in this listener.

This is not a bug. TestNG is working as designed.
