### ISSUE TITLE
Testng execution dependency graph.

### ISSUE THREAD

**Issue by pavankumarmt** [cbeust/testng#1713]
Hi,

I am trying to create a TestNG dependency graph which basically includes the dependency methods and the order in which they execute. I am looking for a solution or hints to implement so I can include selective tests and groups that they depend to make a selective run based in case of test failures.

**Comment by krmahadevan** [comment]
@pavankumarmt - It looks like you have more of a question than actually an issue. So I would request you to please post your questions on the [testng-users google forums](https://groups.google.com/forum/#!forum/testng-users) than here.
