### ISSUE TITLE
Cannot view full exception chain in new reports

### ISSUE THREAD

**Issue by ash2k** [cbeust/testng#172]
Currently there is no way to view full chain of exceptions (and to see the root cause) that caused test failure. It is very inconvenient!

**Comment by krmahadevan** [comment]
This doesn't seem to be an issue anymore in TestNG `7.0.0-beta1`. The sample project available in 
https://github.com/cbeust/testng/issues/216#issuecomment-450471204
can be used to check.
Closing this issue.
