### ISSUE TITLE
Does dependsOnMethods Capability of TestNG suport hierachy chain?

### ISSUE THREAD

**Issue by louis57** [cbeust/testng#1720]
### TestNG Version
> 6.14.2

I have 3 test methods, let's call `method1`, `method2` and `method3`. `Method1` can be executed alone. But `method2` depends on `method1`, it means, `method1` prepares the workflow for `method2` to continue. And `method3` depends on `method1` and `method2` in this regard.

Of course I can combine all 3 in one test method and it worked. But since I use TestNG, and I find out about `dependsOnMethods`, so I would like to try it. That's why i break down my test into 3 methods like this:

    @Test
    public void method1() {
        // do test steps        
    }

    @Test(dependsOnMethods = {"method1"})
    public void method2() {
        // do test steps
    }

    @Test(dependsOnMethods = {"method2"})
    public void method3() {
        // do test steps
    }

And `method1` is executed successfully. When I execute `method2`, then `method1` is executed first and then `method2`. This is what I want.

That's why I suppose that, if I execute `method3`, then `method2` will be executed, and since `method2` depends on `method1`, then `method1` should be executed first, so in this order: `method1 -> method2 -> method3`. But it doesn't work apparently. I get this `TestNGException`:

    method2() is depending on method1(), which is not annotated with @Test or not included

After that I try this:

    @Test(dependsOnMethods = {"method1" , "method2"})
    public void method3() {
        // do test steps
    }
Actually, `method1` is called first, because I see web browser is opened with the url, but that's it, it doesn't go further, it stops there, and I get this log:

    org.openqa.selenium.remote.ProtocolHandshake createSession
    INFO: Detected dialect: OSS
    [1521042814,797][SEVERE]: Unable to retrieve document state disconnected: received Inspector.detached event

    org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status
    from disconnected: received Inspector.detached event

Am I doing something wrong? Can anyone suggest me an explanation and a solution. My tests run on Chrome. Thank you for reading.

**EDIT**: I run the test via IntelliJ IDE (right click on @Test annotation and run). I tested with testng_xml, and it worked.

**Comment by krmahadevan** [comment]
@louis57 - But how are you running your methods ? Is it via the IDE or is it via a shite xml? Please help clarify that part.

**Comment by louis57** [comment]
@krmahadevan I run via IDE. I edited my question

**Comment by krmahadevan** [comment]
@louis57 - When you say IDE, you didn't mention which one. Is it IntelliJ or eclipse ?

**Comment by louis57** [comment]
@krmahadevan Sorry. I use IntelliJ.

**Comment by krmahadevan** [comment]
@louis57 - The IntelliJ TestNG plugin is not maintained by the TestNG team. You would need to take it up with the IntelliJ folks.

@juherr - Can you please help share the bug tracker link for IntelliJ TestNG plugin ?

**Comment by juherr** [comment]
Here: https://youtrack.jetbrains.com/issues/IDEA?q=%23%7BUnit%20Testing.%20TestNG%7D%20

**Comment by krmahadevan** [comment]
Since this is more of an IntelliJ issue than a TestNG issue, closing this issue.

@louis57 - Please file a bug in the link shared by @juherr and follow up accordingly.
