### ISSUE TITLE
TestNG v6.14.2 - started-at and finished-at attributes of <suite> tag,  <test> tag and <test-method> tag in testng-results.xml needs to mention the timezone.

### ISSUE THREAD

**Issue by Debanjan-B** [cbeust/testng#1722]
### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [Yes ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample : Sample **testng-results.xml** file produced : 

<?xml version="1.0" encoding="UTF-8"?>
```
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13267" started-at="2018-03-17T10:50:04Z" finished-at="2018-03-17T10:50:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13267" started-at="2018-03-17T10:50:04Z" finished-at="2018-03-17T10:50:17Z">
      <class name="Config_property_demo.Index">
        <test-method status="PASS" signature="handling_multiple_windows()[pri:1, instance:Config_property_demo.Index@2bbf4b8b]" name="handling_multiple_windows" duration-ms="13236" started-at="2018-03-17T10:50:04Z" finished-at="2018-03-17T10:50:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handling_multiple_windows -->
      </class> <!-- Config_property_demo.Index -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
```

**Comment by krmahadevan** [comment]
Please refer to the documentation [here](http://testng.org/doc/documentation-main.html#logging-xml-reports) to control the timezone values. By default TestNG generates time in `UTC` timezone.

**Comment by Debanjan-B** [comment]
Thanks @krmahadevan for the reply. This issue had nothing to do with controlling timezone values. I have checked the documentation you pointed [output of reporter](http://testng.org/doc/documentation-main.html#logging-xml-reports) which doesn't speaks about UTC/GMT timezones. The timestamps which we see definitely points us to UTC/GMT but the timestamps need a reference e.g. UTC, IST,

**Comment by krmahadevan** [comment]
@Debanjan-B - Like I mentioned before, you can plug in your own time formats via the attribute `timestampFormat` but the timezone is always defaulted to `UTC` by TestNG.  This issue essentially duplicates #1723
