### ISSUE TITLE
TestNG v6.14.2-Is there a configuration to change the timestamp from GMT to IST or any other timezone

### ISSUE THREAD

**Issue by Debanjan-B** [cbeust/testng#1723]
### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [Yes ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample : Sample of `testng-results.xml` file produced during a recent execution :

```
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13267" started-at="2018-03-17T10:50:04Z" finished-at="2018-03-17T10:50:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13267" started-at="2018-03-17T10:50:04Z" finished-at="2018-03-17T10:50:17Z">
      <class name="Config_property_demo.Index">
        <test-method status="PASS" signature="handling_multiple_windows()[pri:1, instance:Config_property_demo.Index@2bbf4b8b]" name="handling_multiple_windows" duration-ms="13236" started-at="2018-03-17T10:50:04Z" finished-at="2018-03-17T10:50:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handling_multiple_windows -->
      </class> <!-- Config_property_demo.Index -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
```

Though my system timestamp (apprx) at 2018-03-17T16:50:04Z but <suite> tag and <test-method> tag both shows 2018-03-17T10:50:04Z

**Comment by krmahadevan** [comment]
@Debanjan-B - TestNG by default generates time in `UTC`. To change timestamp formats etc., you can refer to the TestNG documentation [here](http://testng.org/doc/documentation-main.html#logging-xml-reports)

**Comment by Debanjan-B** [comment]
Thanks @krmahadevan The [link](http://testng.org/doc/documentation-main.html#logging-xml-reports) you provided does speaks about _sample of the output of such a reporter_ but doesn't provide a guidance if it is possible/feasible to change timestamp formats .

**Comment by krmahadevan** [comment]
@Debanjan-B - If you looked at the table in the documentation that I shared, you would notice that there's an option called `timestampFormat` using which you can specify a different timestamp formats, but when I looked at the codebase I noticed that the codebase is defaulting to `UTC` timezone.

@cbeust @juherr - Is there any historical reasons behind why TestNG always defaults to `UTC` timezone instead of getting the local timezone (or) the one set via the JVM argument `-Duser.timezone`

**Comment by juherr** [comment]
@krmahadevan I don't see any good reason. What is saying the `git history` on the lines?

**Comment by krmahadevan** [comment]
@juherr - I noticed that it was introduced as part of fixing https://github.com/cbeust/testng/issues/237
But now if we change it to default to the current Timezone, am kind of concerned, if it would cause failures for people who have relied on the xml and the time being in UTC for whatever parsing they been doing. I am thinking of a JVM argument perhaps that is not the standard one (bcoz the standard one always has a valid local timezone set), using which a user can pass in a custom timezone. But am also concerned about the growing number of JVM arguments in TestNG :)
Thoughts ?

**Comment by juherr** [comment]
@krmahadevan It should not break anything if the timezone version is provided in the date format. Could you take care of #489 at the same time?
