### ISSUE TITLE
Support Java 10 JRE

### ISSUE THREAD

**Issue by hezico5** [cbeust/testng#1729]
### TestNG Version
> Note: only the latest version is supported

Running trying to run testng with some suite xml files (worked on version 6.9.10) on Java 10.

### Expected behavior

TestNG runs my tests successfully.

### Actual behavior
I got an error:

[TestNG] [ERROR] java.lang.IllegalArgumentException: InputStream cannot be null
Exception in thread "main" java.lang.NullPointerException
        at org.testng.TestNG.getStatus(TestNG.java:211)
        at org.testng.TestNG.main(TestNG.java:1324)

### Is the issue reproductible on runner?

- [ X] Shell

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@hezico5 - I am not quite sure I u'stand what combination doesn't work for you ?

Can you please let us know what happens when you use TestNG `6.14.3` (latest released version) with JDK10 ?

**Comment by juherr** [comment]
And it may depend on how you are running the test (classpath or module).
Fyi, we are not supporting (because not really tested) java9 yet: #1642 or #938

**Comment by juherr** [comment]
Java 10 is not a target but it should not failed.
We will check it with https://github.com/cbeust/testng/issues/1808
