### ISSUE TITLE
Couldn't install TestNG in my machine with Maven Project 

### ISSUE THREAD

**Issue by ShivaCsk5557** [cbeust/testng#1730]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Installation Successful

### Actual behavior
Installation is only partially successful as sometimes i can see TestNG in Java perspective and TestNG options on Project right click,
But now i am not able to install itself.

### Is the issue reproductible on runner?
YES 100% 

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
>Below is the Installation Error while tried via Eclipse Install New Software option.
I also tried installing offline via dropins folder and maven dependency build but neither resolved the issue. PLEASE HELP ASAP. 

> ##  I am also attaching my pom, testng.xml files and logs of Maven build failure in docx.

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.dsl, phase=org.eclipse.equinox.inte
[Cannot Install TestNG for Maven Project.docx](https://github.com/cbeust/testng/files/1840693/Cannot.Install.TestNG.for.Maven.Project.docx)
rnal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.m2e.archetype.common,1.8.3.20180227-2135
No repository found containing: osgi.bundle,org.eclipse.m2e.core,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.core.ui,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.discovery,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.editor,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.editor.xml,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.importer,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.jdt,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.jdt.ui,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.launching,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.lifecyclemapping.defaults,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.indexer,1.8.3.20180227-2135
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.runtime,1.8.3.20180227-2135
No repository found containing: osgi.bundle,org.eclipse.m2e.maven.runtime.slf4j.simple,1.8.3.20180227-2135
No repository found containing: osgi.bundle,org.eclipse.m2e.model.edit,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.profiles.core,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.profiles.ui,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.refactoring,1.8.3.20180227-2137
No repository found containing: osgi.bundle,org.eclipse.m2e.scm,1.8.3.20180227-2137
No repository found containing: org.eclipse.update.feature,org.eclipse.m2e.feature,1.8.3.20180227-2137
```

**Comment by krmahadevan** [comment]
@ShivaCsk5557 - I cannot open up any of your attachments. I would request you to please create a demo project on github with your project contents and share the link. Also I would suggest that you start off by posting this as a query on the [TestNG-users(https://groups.google.com/forum/#!forum/testng-users) google forums. We encourage users to use the forum for asking help and we tend to use the github-issues page as a place to track bugs.

Being able to consume TestNG as a maven artifact is a very basic use case and right now there are no known issues with that. So please post your issue on the google forum.

**Comment by missedone** [comment]
@ShivaCsk5557, looks like your Eclipse distro is "Eclipse IDE for Java and DSL Developers", it does not have M2E (Maven to Eclipse plugins) installed.
if you do want to use Maven features in Eclipse, you either install M2E in your current Eclipse instance, or install TestNG Eclipse Plugins in the Eclipse JEE package which has M2E installed out of the box.

1. M2E: https://www.eclipse.org/m2e/m2e-downloads.html
2. Eclipse JEE Package: https://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/oxygen3

HTH.
