### ISSUE TITLE
suite.getSuiteState().isFailed() returns false 

### ISSUE THREAD

**Issue by Anda77** [cbeust/testng#1733]
### TestNG Version
> Note: only the latest version is supported
TestNG 6.11

### Expected behavior
suite.getSuiteState().isFailed()  returns TRUE

### Actual behavior
suite.getSuiteState().isFailed()  return FALSE

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [X ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

    public void onFinish(ISuite suite) {

        Map<String, ISuiteResult> resultsSuite = suite.getResults();

        System.out.println("resultsSuite " + resultsSuite.size());
        
        System.out.println("suite.getSuiteState() " + suite.getSuiteState().isFailed());

        if (suite.getSuiteState().isFailed()) {
            resultsSuita = false;
        } 

        System.out.println("resultsPasses " + resultsSuita);
        
    }

**Comment by krmahadevan** [comment]
@Anda77 - Can you please try using the latest released version of TestNG (currently it is `6.14.3`) and let us know if you are still facing the problem. If its still a problem, please help provide a standalone test that can be executed to reproduce the problem. Whatever you have shared is not sufficient to investigate the problem.

**Comment by Anda77** [comment]
I used testng-6.14.2.


here is my test class

@Listeners({chrome65.DotTestListener.class})
public class NewEmptyTestNGTest {



    public NewEmptyTestNGTest() {
    }

    // TODO add test methods here.
    // The methods must be annotated with annotation @Test. For example:
    //
    // @Test
    // public void hello() {}
    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    public void randomWait() {
        try {
            Thread.sleep((long) (Math.random() * 1000));
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Test(enabled = true)
    public void showFailure() {
        randomWait();
        Assert.fail();
    }

    @Test
    public void Test() {

        String[] rto1 = {"boolean", "BigInteger", "List",};
        String[] rto2 = {"List", "BigInteger", "boolean",};

        Assert.assertEqualsNoOrder(rto1, rto2);

    }

  
}

and listener:

public class DotTestListener implements IExecutionListener, ISuiteListener, ITestListener {


    String typeTest = "";
    int failedTests = 0;
    int totalFailedTests = 0;

    boolean resultsSuita = true;

    public void onStart(ITestContext context) {

    }

    public void onTestStart(ITestResult result) {

    }

    public void onTestSuccess(ITestResult result) {

    }

    public void onTestFailure(ITestResult result) {

    }

    public void onTestSkipped(ITestResult result) {

    }

    public void onTestFailedButWithinSuccessPercentage(ITestResult result) {

    }

    public void onFinish(ITestContext context) {

    }

    public void onExecutionStart() {
        System.out.println("onExecutionStart()");

    }

    public void onStart(ISuite suite) {

    }

    public void onFinish(ISuite suite) {

      
        SuiteRunState run1 = suite.getSuiteState();
        System.out.println(suite.getSuiteState());

        System.out.println("suite.getSuiteState() " + suite.getSuiteState().isFailed());

        if (suite.getSuiteState().isFailed()) {
            resultsSuita = false;
        }

        System.out.println("resultsPasses " + resultsSuita);

    }

    public void onExecutionFinish() {

    }

}

The suite is failed, so the result for suite.getSuiteState().isFailed() would be true not false.

Can you give a workaround, please?

**Comment by juherr** [comment]
Using a listener is already the best workaround you can use but why do you use the suite state instead of managing the value by yourself with `onTestFailure`?

**Comment by krmahadevan** [comment]
@Anda77 - If you look at the java docs of `SuiteRunState` you would notice that its mentioned that it is intended to figure out if there are any failures in the `@BeforeSuite` annotated methods.

https://github.com/cbeust/testng/blob/67b8f040aae98088cab6331a78d66c9536f87b27/src/main/java/org/testng/SuiteRunState.java#L5-L8

In your case you dont have any `@BeforeSuite` methods nor any failures in them. That is why you dont get a proper response when you query `isFailed()`.

As far as I know, TestNG is working as designed here. You are making use of a wrong mechanism to figure out the state.

Your `onFinish(ISuite)` should perhaps look like this, if you would like to know if there were any failures in your suite

```java
public void onFinish(ISuite suite) {
    boolean resultsSuita = suite.getResults()
            .values()
            .stream()
            .map(iSuiteResult -> iSuiteResult.getTestContext().getFailedTests().size())
            .map(size -> size == 0)
            .findFirst()
            .orElse(true);
    System.out.println("resultsPasses " + resultsSuita);
}
```

**Comment by Anda77** [comment]
Thanks from my soul for your response.

Your response was very util.

In this night I will sleep well.

**Comment by Anda77** [comment]
and if I need to know if crash my setup method how can verify?

**Comment by juherr** [comment]
an `onTestFailure` will be called and you can find all the information you need from ITestResult

**Comment by Anda77** [comment]
Your solution is not correct:

If I have a suite from 6 test cases and the 4 test cases is failed the  resultsSuita is true, this is incorrect.
 

 boolean resultsSuita = suite.getResults()
            .values()
            .stream()
            .map(iSuiteResult -> iSuiteResult.getTestContext().getFailedTests().size())
            .map(size -> size == 0)
            .findFirst()
            .orElse(true);

**Comment by krmahadevan** [comment]
@Anda77

The snippet I shared was supposed to just show you how to go about figuring
this out on your own and not necessarily meant to be consumed as is.
You should try altering/tweaking it to suite your needs.
