### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1740]
For example AssertJ to the 3.x branch https://joel-costigliola.github.io/assertj/assertj-core.html

**Comment by krmahadevan** [comment]
We use AssertJ only as test dependency right. So why upgrade when what's
already there satisfies our test dependency needs. Just curious.

> --

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/

My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by juherr** [comment]
Because we have Java8 now ;) https://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion

**Comment by atulagrawal** [comment]
I have raised my FIRST PR - https://github.com/cbeust/testng/pull/1841 for bumping up version.
