### ISSUE TITLE
Missing Artifact for 6.14.3

### ISSUE THREAD

**Issue by mburger81** [cbeust/testng#1752]
### TestNG Version
`6.14.3`

### Expected behavior
We are unable to download version `testng 6.14.3`
If you go to https://bintray.com/cbeust/maven/testng/6.14.3 there are now direct download enabled and if you add the maven depencency to a pom file we get the error : missing artifcat `org.testng.testng:jar:6.14.3`

we need only required jar files, but can neither download them anywhere nor can we use maven to add the dependency.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@mburger81 

You should be able to download TestNG `6.14.3` as a maven dependency by adding the below section to either your `pom.xml` or to your `~/.m2/settings.xml`

```xml
<repositories>
    <repository>
        <id>jcenter</id>
        <name>jcenter</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>
```

**Comment by krmahadevan** [comment]
ping @cbeust - Is it possible for you to please help sync up Maven central with JCenter ?

**Comment by cbeust** [comment]
I just synced 6.14.3 to Maven Central.
