### ISSUE TITLE
[Help] Build virtual TestNG suite xml, when add XmlTest failed

### ISSUE THREAD

**Issue by ansonliao** [cbeust/testng#1767]
### Platform:
- Mac OS 10.13.4
- Java: 8
- Build System: Maven

Want to build virtual TestNG XML, and meet problem when add `Xml Test` to `Xml Suite`:

code: 

Initialise `XmlSuite` instance: 

```java
public XmlSuite newXmlSuite() {
    XmlSuite xmlSuite = new XmlSuite;
    // set the xml suite's `name`, `thread-number`, `preserve order`, `parallel` mode
    xmlSuite.setName("XML Suite Sample");
    xmlSuite.setParallel(XmlSuite.ParallelMode.TESTS);
    xmlSuite.setPreserveOrder(false);
    xmlSuite.setThreadCount(Runtime.getRuntime().availableProcessors());
    xmlSuite.setVerbose(2);
    return xmlSuite;
}
```

#### This sample will be passed:

```java
public XmlSuite appendXmlTest(XmlSuite xmlSuite) {
    XmlTest xmlTest = new XmlTest(xmlSuite);    // initialise a xml test instance with XmlSuite instance
    // below is initialise `xmlTest` instance context, for example, testing class, testing method of testing     class
    ...
    return xmlSuite;
}

// no problem to run the virtual xml suite
public void testRun() {
    XmlSuite xmlSuite = newXmlSuite();
    xmlSuite = appendXmlTest(xmlSuite);
    log.info(xmlSuite.toXml());

    TestNG testng = new TestNG();
    testng.setXmlSuites(asList(xmlSuite));
    testng.run();
}
``` 

#### This sample will be failed:

```java
public XmlTest getXmlTest() {
    XmlTest xmlTest = new XmlTest();     // initialise xml test instance without any parameter
    // get xml test details
    ...
    return xmlTests;
}

// error met below
public void testRun() {
    XmlSuite xmlSuite = newXmlSuite();
    log.info(xmlSuite.toXml());

    xmlSuite.addTest(getXmlTest());
    TestNG testng = new TestNG();
    testng.setXmlSuites(asList(xmlSuite));
    testng.run();
}

```

and error message: 

```bash
Exception in thread "main" java.lang.NullPointerException
	at org.testng.xml.XmlTest.isJUnit(XmlTest.java:281)
	at org.testng.xml.DefaultXmlWeaver.asXml(DefaultXmlWeaver.java:153)
	at org.testng.xml.XmlWeaver.asXml(XmlWeaver.java:67)
	at org.testng.xml.XmlTest.toXml(XmlTest.java:475)
	at org.testng.xml.DefaultXmlWeaver.asXml(DefaultXmlWeaver.java:139)
	at org.testng.xml.XmlWeaver.asXml(XmlWeaver.java:57)
	at org.testng.xml.XmlSuite.toXml(XmlSuite.java:518)
```

Tried to print out the suite xml (`xmlSuite.toXml()`), and notice that the failed case xml is same as passed case xml.

#### Update:
used `.setTests(List<XmlTest>)` also met the same error.

```java
xmlSuite.setTests(asList(xmlTest));
```

Could anyone provide how can I fix the failed issue?

**Comment by krmahadevan** [comment]
@ansonliao - When you instantiate an `XmlTest` object, you should ensure that it is bound with an `XmlSuite` object in one of the following two ways

1. Via the `XmlTest` constructor `org.testng.xml.XmlTest#XmlTest(org.testng.xml.XmlSuite)` (or) `org.testng.xml.XmlTest#XmlTest(org.testng.xml.XmlSuite, int)`
2. Via the setter method `org.testng.xml.XmlTest#setSuite`

The null pointer exception is basically arising due to the fact that the `XmlTest` object is trying to access the attributes of a `null` `XmlSuite`.

I have now added an edit check which ensures that you dont see a `NullPointerException` but instead see a proper error message.

**Comment by ansonliao** [comment]
@krmahadevan 
Thanks for your reply.
