### ISSUE TITLE
Unexpected results when declaring a test that has cycles

### ISSUE THREAD

**Issue by btsweber** [cbeust/testng#1776]
### TestNG Version
6.14.0

### Expected behavior

The test case I provided has a cycle in the test dependency. testD->testC->testB->testA, but testA is also marked priority=1 which would require it to run after all the other tests which are priority=0.

In this case, I would expect that testNG would provide an error or warning that a dependency cycle exists. Under these circumstances, I would not expect any tests to run. If any tests are run, I would expect the @afterClass method to run as well. 

### Actual behavior

Only testA runs.  Note also the @afterClass method does not run at the conclusion of the test. There is no indication that there is a problem in the test's configuration. Note also that if you comment out testD, all the tests and the afterClass method run as expected.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```javascript

package com.seastreet.testng;

import org.testng.annotations.Test;
import org.testng.annotations.AfterClass;

public class CycleTest {
  @AfterClass
  public void afterClass() {
	  System.out.println("afterClass()");
  }

  @Test(groups={"A"}, priority=1)
  public void testA() {
	  System.out.println("testA()");
  }

  @Test(groups={"B"}, dependsOnGroups={"A"})
  public void testB() {
	  System.out.println("testB()");
  }

  @Test(groups={"C"}, dependsOnGroups={"B"})
  public void testC() {
	  System.out.println("testC()");
  }

  @Test(groups={"D"}, dependsOnGroups={"C"})
  public void testD() {
	  System.out.println("testD()");
  }
}
```

**Comment by krmahadevan** [comment]
I was able to reproduce this in TestNG `6.14.3`. But I am not able to reproduce this using the latest SNAPSHOT version of TestNG viz., `7.0.0-SNAPSHOT`. So I think it got fixed as a side effect of some other fix. Now all the methods would be executed because when running the class directly and no filtering is specified (ie., filter by groups etc.,) all methods are expected to run.

PS: The output now would be as below :
```
testA()
testB()
testC()
testD()
afterClass()

===============================================
Default Suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================
```
when executed from the IDE (i.e., there's no suite xml involved)
