### ISSUE TITLE
ITestListener's onTestFailure only getting called at the last line of Feature File.

### ISSUE THREAD

**Issue by VinnieM** [cbeust/testng#1784]
### Expected behavior
The onTestFailure to be called everytime an error is present.
### Actual behavior
I have 2 feature files. The first feature file has 2 Scenarios, and the second feature file has 1. For sake of brevity, let us assume that all the scenarios are the same(Copy-pasted), so that when I introduce an error in scenario1, the same would replicate in all the scenarios. The problem is that after introducing the error, onTestFailure is being called only at the end of the feature file. In the first Feature file, after the first scenario error's out, the second scenario is called when the second scenario error's out(the last scenario in that feature file) the onTestFailure is called. In the second feature file, since there is only one scenario, it is being called at the end.

### Is the issue reproductible on runner? Yes

- [x] Maven
- [x] IntelliJ

### Test case sample
TestNG.xml

```
<suite name="Execute Tests" parallel="tests" verbose="1"
  configfailurepolicy="continue" thread-count="5">
  <listeners>
    <listener class-name="test.main.ExecutionListener"/>
    <listener class-name="com.listener.FeatureListener"/>
    <listener class-name="test.main.TestListener"/>
  </listeners>
// Omitting the rest
</suite>
```
Runner Class
```
 /**
   * Marks a class or a method as part of the test. This function creates a session with Appium and
   * then starts to execute the feature files.
   *
   * @param cucumberFeature Contains the feature file which needs to be executed.
   */
  @Test(
      dataProvider = "provideFeatures",
      alwaysRun = true,
      invocationCount = 1
  )
  public void executeFeature(CucumberFeatureWrapper cucumberFeature) {
    HashMap<String, BaseToolLibrary> driverInstances = DriverManager.getAllDriverInstances();
    if (driverInstances.size() > 0) {
      driverInstances.forEach((user, appiumInstance) -> {
        try {
          appiumInstance.createInternalDriverInstance();
        } catch (TestCaseFailedException testCaseFailedException) {
          Xlog.printErrorLog("TestCase Failed Exception !!!", getClass(), testCaseFailedException);
        } catch (FrameworkSetupException frameworkSetupException) {
          Xlog.printErrorLog("Framework Setup Exception !!!", getClass(), frameworkSetupException);
        }
      });
      this.testNGCucumberRunner.runCucumber(cucumberFeature.getCucumberFeature());
    } else {
      throw new IllegalStateException(
          "Driver Instances are Empty!!! Double check the TestNG.xml with the deviceDriver.json");
    }
  }

  /**
   * Marks a method as supplying data for a test method. The @Test method that wants to receive data
   * from this DataProvider needs to use a dataProvider name equals to the name of this annotations
   *
   * @return an Object[][] where each Object[] can be assigned the parameter list of the test
   * method.
   */
  @DataProvider
  public Object[][] provideFeatures() {
    FeatureListener.totalFeatures = this.testNGCucumberRunner.getFeatures().size();
    return this.testNGCucumberRunner.provideFeatures();
  }
```
TestListener class which implements ITestListener
```
  public void onTestFailure(ITestResult iTestResult) {
    if (iTestResult.getStatus() == ITestResult.FAILURE) {
      Xlog.printInfoLog("On Test Failure", getClass()); // Called only at the end of the feature file.
    }
  }
```

Please do let me know if you need more inputs.

**Comment by krmahadevan** [comment]
@VinnieM - Are you expecting your `onTestFailure` to be invoked after every Scenario ? If that's the case, then there's nothing much that can be done by TestNG here. Its the cucumber implementation that's at fault here, because it treats all scenarios in a `.feature` file as one `@Test`. So if your `.feature` file had 5 scenarios, then the cucumber implementation essentially runs all the 5 in the `.feature` file in 1 iteration (remember that the integration treats multiple `.feature` file as multiple data driven iterations) and after the first iteration is completed, it goes on to execute the listeners.

TestNG does not understand scenarios from the cucumber world. It only understands its annotations. The runner implementation you have shared is basically causing TestNG to run all scenarios in a feature as 1 iteration.

TestNG is working as designed here.

**Comment by VinnieM** [comment]
Thanks for clearing this up Krishnan.
