### ISSUE TITLE
The "emailable-report" cannot be generated successfully when build and run suite with command line

### ISSUE THREAD

**Issue by edwardguo0123** [cbeust/testng#1786]
### Description
Since I need to deploy the suite on Jenkins for a daily run, so I need to set up two cmd for my suite as below:
1. javac -classpath lib/* -d ./bin ./src/test/java/pssw/isen/testcase/*.java ./src/test/java/pssw/isen/api/single/*.java ./src/test/java/pssw/isen/util/*.java ./src/test/java/org/json/*.java
2. java -cp bin;lib/* org.testng.TestNG ./TestSuite_all.xml 

The first is to build all java files into .class files and the second one is to run test suite.

I have added one class to generate the emailable-report.html replacing the default and also added one listener into the TestSuite_all.xml

### Expected behavior
I hope the emailable-report.html can be generated each time I run suite using commandline.

### Actual behavior
The emailable-report.html is only generated when I run my suite from my IDE IntelliJ, but cannot be generated through command line. (I have also tried to add the listener on my test case class which either doesn't work)

Does anyone know what caused this issue? Thanks a lot!

**Comment by krmahadevan** [comment]
No response from the user. Closing this off.

@edwardguo0123 - Please comment back on this ticket when you have an update and we can have the issue re-opened if required.  Also please help share samples that we can use to reproduce the problem.

**Comment by edwardguo0123** [comment]
This has been resolved by updating following method in my customized report file, I suppose it was because my customized report overwritten by the default one when running with commandline, so I changed its output path:
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites,
                               String outputDirectory) {
        try {
//Update the path
            File directory = new File("");
            outputDirectory = directory.getAbsolutePath();
//
            writer = createWriter(outputDirectory);
        } catch (IOException e) {
            LOG.error("Unable to create output file", e);
            return;
        }
        for (ISuite suite : suites) {
            suiteResults.add(new IsenCustomizedEmailableReporter.SuiteResult(suite));
        }

        allSuiteResult = SuiteCommon.getTestResult();
        writeDocumentStart();
        writeHead();
        writeBody();
        writeDocumentEnd();

        writer.close();
    }

I uploaded my project, and below is my compiling and running commands:
javac -classpath lib/* -d ./bin ./src/*.java
java -cp bin;lib/* org.testng.TestNG ./TestSuite_all.xml 

This issue has been resolved with a workaround thought I still not sure what is the exact reason for this
My project has been uploaded
[TestNGReportTest.zip](https://github.com/cbeust/testng/files/2078695/TestNGReportTest.zip)
