### ISSUE TITLE
When both bean shell and annotation transform is used to select methods to execute, methods with priority attribute set are not executed.

### ISSUE THREAD

**Issue by formynet** [cbeust/testng#1798]
### TestNG Version 6.14.3
> Note: only the latest version is supported

### Expected behavior
BOth methods with priority and without priority should be executed.

### Actual behavior
Only testng class with method with out priority is executed.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven - reproducible with maven 
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Steps
1.Set up eclipse -test ng project with the following:
a. add a method in testng class with priority and any group name.
b. add another testng class with method with out priority.
2.Add a bean shell method selector to select any group in a testng suite with testng class from step 1.
3.Add a listener class with overridden tranform from IAnnotationTransformer3 that has the same logic as in beanshell method selector to select a method of any group.
4.Execute both testng classes using testng suite.

**Comment by formynet** [comment]
What I have observed after hours of testing is:
1. If priority for methods is defined in both testng classes, testng executes all the methods without priority in both classes. It then DOES NOT execute methods with priority.
Ex: Lets say there are two classes:
Class 1  
method 1 priority 1
method 2 priority 2
method 3 no priority set
method 5 dependsOn=method1
Class 2 
method 1 priority 3
method 2 priority 4
method 4 no priority set

With these classes in testng suite, only Class1-method 3 and Class2- method 4 are executed. Methods with priority set are not executed.

2. If priority is set for methods in one class, irrespective of order of classes defined in testng suite, testng executes methods without priority and then executes methods with priority from the only class where priority is set.

**Comment by formynet** [comment]
I think a user expects all methods to be executed unless test attribute :enabled is set to false

**Comment by krmahadevan** [comment]
@formynet - Please add a sample (your test class, listeners, suite xml etc) that can be used to reproduce the problem. 

Also please share the expected output and the actual output, so that its easier to compare.

**Comment by formynet** [comment]
Suite file
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Automated_TestSuites" verbose="1">
	<test name="Tests">
		
		<classes>
				<class name="com.abc.ete.unittest.groups.GroupTests"/>
			<class name="com.abc.ete.io.pdf.PDFUtilTest" />
         	<class name="com.abc.ete.ui.RegisterPageTests" /> 	
		
		</classes>
	</test>
</suite>

**Comment by formynet** [comment]
@krmahadevan 
![testng](https://user-images.githubusercontent.com/23082208/40518318-f6e3bc60-5f87-11e8-8a52-1dc37e77b4fa.PNG)

ignore custom annotations.. they are not important for this test
![image](https://user-images.githubusercontent.com/23082208/40518692-dc80f6a6-5f89-11e8-8a05-ab652ad783e7.png)

if you execute only above from testng suite file all methods are executed.

second suite file without any priorities set at method level
![image](https://user-images.githubusercontent.com/23082208/40518791-53971fc2-5f8a-11e8-90b0-92352a721f3a.png)

if you execute first and second suite file, all methods in both tests are executed

observe that 3 rd class file below also has checkForPDFCount method with priority set
![image](https://user-images.githubusercontent.com/23082208/40518860-9ee2f154-5f8a-11e8-910d-cbcf81fb32c4.png)

Now if you execute all the 3 classes, only methods with out priority set are executed and methods with priority set in Test annotation are ignored. Problem has nothing to do with logic mentioned in the methods, one can just have system.out.println added in the methods too. 

If I remove priority in both classes, then all tests are executed. 

Expected: All methods from all classes should execute.
Actual: Only methods without priority are executed when two classes involve methods that have priority

**Comment by krmahadevan** [comment]
@formynet - Can you please add source code as is instead of adding them as screenshots ? The whole idea of asking for samples is so that we can run them to simulate the problem.

So please help furnish samples that we can actually execute to reproduce the problem [ It needn't have everything. It could even just have a bunch of `System.out.println` statements ]. Also include the relevant suite xml if applicable. 

Without that, its hard to take a look at the bug.

**Comment by formynet** [comment]
i tried to enter source code here using code comments but it is modified incorrectly in the preview. that is the reason i added comments using screenshots. I will ping you offline.

**Comment by krmahadevan** [comment]
@formynet - For learning on how to format code on github please refer here https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by krmahadevan** [comment]
ping @formynet. Any updates? If we dont hear back, then I would have to close out on this issue. I am basically going through issues and trying to ensure that we are addressing all issues and thus reduce the overall open issues in TestNG. So it would be really great if you could please help attach the sample as requested, so that we can get to the bottom of this. Appreciate your earliest response on the same.

**Comment by krmahadevan** [comment]
No response from the user. Closing the issue. Please comment once you are able to attach sample tests to reproduce this issue.
