### ISSUE TITLE
Should I implement assertEquals(float[], float[]) and assertEquals(double[], double[]) versions with delta?

### ISSUE THREAD

**Issue by danilcha** [cbeust/testng#1803]
Currently TestNG contains `assertEquals(float[], float[])` and `assertEquals(double[], double[])` overloads, but no versions with `delta` parameter. They are rather useless without them. Should I make a pull request?

**Comment by juherr** [comment]
The idea is good, feel free to propose a PR :)

**Comment by juherr** [comment]
@atulagrawal Maybe you'd like to fix it? :)

**Comment by atulagrawal** [comment]
Sure. I will take this up.

**Comment by danilcha** [comment]
Thank you! Could you please also add the `assertNotEquals` counterparts?
