### ISSUE TITLE
If I use sikuli script to hit a element and generate batch file,will it hit that element?

### ISSUE THREAD

**Issue by pradeepsai11** [cbeust/testng#1806]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
Please post your question on a sikuli related forum. TestNG does not own or deal with sikuli
