### ISSUE TITLE
Add more targets on Travis

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1808]
https://sormuras.github.io/blog/2018-05-31-jdk-matrix.html

**Comment by krmahadevan** [comment]
@juherr - What is the expectation from this issue? Can you please elaborate ?

Should we be changing https://github.com/cbeust/testng/blob/6394847b1c3c25e72a2b1aa3d1c045c693c0c129/.travis.yml#L26-L27 

to include references to :

* openjdk9
* openjdk10
* openjdk11

**Comment by juherr** [comment]
Yes, I think we should try the most environment as possible (linux & mac).
It will allow us to know when an issue is system dependent.

**Comment by juherr** [comment]
Add more OS too: https://blog.travis-ci.com/2018-10-11-windows-early-release
