### ISSUE TITLE
TestNG @DataProvider Iterator<Object[]> gives error at @Test method-Data provider mismatch

### ISSUE THREAD

**Issue by Pankaj12121** [cbeust/testng#1809]
### TestNG Version
> Note: only the latest version is supported
6.14
### Expected behavior
It should read the data for iterator dataProvider

### Actual behavior
It is giving error- DataProvider misMatch

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by Pankaj12121** [comment]
Code for your reference- 
public class Dataprovider {
	
	@Test(dataProvider="dp001")
	
	public void myData(ArrayList<Object> test2){
		System.out.println(test2.get(0).toString());
		System.out.println(test2.get(1).toString());
		System.out.println(test2.get(2).toString());
		
		
	}
	
	
	@DataProvider(name="dp001")
	public Iterator<Object[]>dp001(){
		
		ArrayList<Object[]> test1= new ArrayList<>();
		
		test1.add(new Object[] {"WebDriver"});
		test1.add(new Object[] {"TestNG"});
		test1.add(new Object[] {"Framework"});
	
		return test1.iterator();
		
	}

}

**Comment by Pankaj12121** [comment]
[RemoteTestNG] detected TestNG version 6.14.3
FAILED: myData
org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: myData([Parameter{index=0, type=java.util.ArrayList, declaredAnnotations=[]}])
Arguments: [(java.lang.String) WebDriver]

**Comment by krmahadevan** [comment]
There is nothing wrong with TestNG here. Your data provider is returning back an `Object[] {}` (Object array) for every iteration, but your test method is expecting an array list of objects `ArrayList<Object>` as test parameter. 

You would need to fix your data provider as below 

```java
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestclassSample {
  @Test(dataProvider = "dp001")
  public void myData(List<Object> test2) {
    System.out.println(test2.get(0).toString());
    System.out.println(test2.get(1).toString());
    System.out.println(test2.get(2).toString());
  }

  @DataProvider(name = "dp001")
  public Iterator<Object[]> dp001() {
    ArrayList<Object[]> test1 = new ArrayList<>();
    List<String> items = Arrays.asList("WebDriver", "TestNG", "Framework");
    test1.add(new Object[] {items});
    return test1.iterator();
  }
}
```

Closing this issue with resolution as _TestNG working as designed_

**Comment by Pankaj12121** [comment]
Now its working fine...Thanks a lot for your quick & kind support.

Really appreciate your help.

Regards,

Pankaj Yogi

(+91) 8080350555
