### ISSUE TITLE
Nullpointer exception when running TestNG tests from CMD

### ISSUE THREAD

**Issue by SotirisAnt** [cbeust/testng#1810]
Hello,

I face the following situation with TestNG. I have a Maven project which runs normally from within Eclipse. When I try to run the tests from CMD I get java.lang.NullPointerException as shown in screenshot below:

![image](https://user-images.githubusercontent.com/36734902/40781018-0a494a3a-64e3-11e8-93ef-13957f18013f.png)

The structure of the folders are like this (assuming that current location is within the project's directory):
- ./libs/  contains all the jar files
- ./src/main/java/com/site/tests/  contains the java classes
- ./target/classes/com/site/tests/  contains the .class files

I have tried the following commands but to no avail - the result is the same!
`java -cp libs\* org.testng.TestNG testng.xml` and
`Java -cp .\target\classes\com\site\tests\*;.\libs\* org.testng.TestNG testng.xml`

Do you have any idea why I might be getting a nullPointer? Attached you may find the project's folder and the testng.xml

![image](https://user-images.githubusercontent.com/36734902/40781382-514364ec-64e4-11e8-807b-7ec8d0e5afd4.png)

![image](https://user-images.githubusercontent.com/36734902/40781667-69af9b44-64e5-11e8-9313-0269ae44869f.png)

### TestNG Version
6.14.2

### Java version
![image](https://user-images.githubusercontent.com/36734902/40781436-925b7686-64e4-11e8-8949-758c5349903e.png)

Thank you in advance!

**Comment by krmahadevan** [comment]
@chenshinan 

> how to fix？

Its already fixed. Please try again using TestNG `7.0.0-beta3`

**Comment by sagarkale8** [comment]
Had the same problem. I think TestNG changes the classpath variable and moves all class files to /target/classes directory. But if we try to point this path in cmd, it doesnt work. For bat file to run all class files HAVE to be in bin folder. Do the following

Goto Eclipse -> right click on Project ->Properties -> Source tab

Here, change the output folder to bin. Now run the testng xml from eclipse to make sure everything still works.

Then goto bin folder, your class files should now be here. Then run your testng command, should start working.
