### ISSUE TITLE
Test result sent to beforeInvocation() of skipped test differs from what onTestSkipped() receives

### ISSUE THREAD

**Issue by sbabcoc** [cbeust/testng#1824]
### TestNG Version
> 6.14.3
> Behaves as expected with TestNG 6.10

### Expected behavior
For skipped test, the same test result object should be sent to beforeInvocation() and onTestSkipped()

### Actual behavior
For skipped test, beforeInvocation() and onTestSkipped() receive differing test results.
(Point of fact, it appears that beforeInvocation() receives a semi-initialized "dummy" result.) 

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```java
package org.example;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import java.io.File;
import java.lang.reflect.Method;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestContext;
import org.testng.ITestNGListener;
import org.testng.ITestResult;
import org.testng.SkipException;
import org.testng.TestNG;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.internal.IResultListener;
import org.testng.xml.XmlSuite;

public class Issue1602ReproTest {
    @Test
    public void reproduceIssue() {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{ExampleClass.class});
        testNG.setConfigFailurePolicy(XmlSuite.FailurePolicy.CONTINUE);
        MethodListener methodListener = new MethodListener();
        ResultListener resultListener = new ResultListener();
        testNG.addListener((ITestNGListener) methodListener);
        testNG.addListener((ITestNGListener) resultListener);
        testNG.run();
        String file = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
        System.out.println("TestNG v" + new File(file).getParentFile().getName());
        assertEquals(methodListener.skippedTest, resultListener.skippedTest);
    }

    static class ExampleClass {

        @BeforeMethod
        public void beforeMethod(Method method) {
            if ("test1".equals(method.getName())) {
                System.out.println("beforeSkipped");
                throw new SkipException("beforeSkipped");
            }
        }

        @Test
        public void test1() {
            assertTrue(true);
        }

        @Test
        public void test2() {
            assertTrue(true);
        }
    }

    static class MethodListener implements IInvokedMethodListener {
        ITestResult skippedTest = null;

        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
            if ("test1".equals(method.getTestMethod().getConstructorOrMethod().getName())) {
            	skippedTest = testResult;
            }
        }

        @Override public void afterInvocation(IInvokedMethod method, ITestResult testResult) { }
    }
    
    static class ResultListener implements IResultListener {
    	
    	ITestResult skippedTest = null;

		@Override
		public void onTestSkipped(ITestResult arg0) {
			skippedTest = arg0;
		}

		@Override public void onFinish(ITestContext arg0) { }
		@Override public void onStart(ITestContext arg0) { }
		@Override public void onTestFailedButWithinSuccessPercentage(ITestResult arg0) { }
		@Override public void onTestFailure(ITestResult arg0) { }
		@Override public void onTestStart(ITestResult arg0) { }
		@Override public void onTestSuccess(ITestResult arg0) { }
		@Override public void onConfigurationFailure(ITestResult arg0) { }
		@Override public void onConfigurationSkip(ITestResult arg0) { }
		@Override public void onConfigurationSuccess(ITestResult arg0) { }
    }
}
```

**Comment by krmahadevan** [comment]
@sbabcoc - Can you please check if the problem exists in TestNG `7.0.0-SNAPSHOT` as well ?

**Comment by sbabcoc** [comment]
Appears to work as expected in TestNG 7.0.0-SNAPSHOT

**Comment by krmahadevan** [comment]
In that case, can we close this issue off ? You would need to wait for TestNG `7.0.0` to be released.

**Comment by krmahadevan** [comment]
And oh btw, friendly advice.. dont rely on the apis under `org.testng.internal` package. They are meant to be internal TestNG APIs and will change without any warnings or any deprecation strategies because they were never meant to be consumed by anyone else apart from TestNG.

**Comment by sbabcoc** [comment]
I get the same broken behavior with ITestListener. I was merely using this "internal" interface because it also extends IConfigurationListener. This wasn't necessary here, but was an artifact of the origin of the repro code.

**Comment by krmahadevan** [comment]
Scott

Am a bit confused now. So are you saying the problem goes away in the 7.0
series or are you saying the problem exists ?

Can you please also help update the same to use the public interfaces that
TestNG provides as listener interfaces ?
-- 

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/

My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by sbabcoc** [comment]
How long until 7.0.0 is released? This version has issues with tests that are skipped or fail in @BeforeMethod methods. Version 6.14.3 fails in the same scenarios, but with somewhat different behavior.

**Comment by sbabcoc** [comment]
Sorry for lack of clarity... I get the same broken behavior in 6.14.3 if I implement the "public" ITestListener interface instead of the "internal" IResultListener interface. This is unsurprising, since IResultListener extends ITestListener.

**Comment by krmahadevan** [comment]
It's gonna take sometime before 7.0 comes out because we are still
iterating over bugs refactoring code etc.

So if this issue is resolved by using TestNG 7.0 let's close it. For any
other issues with TestNG listeners you maybe experiencing let's open up
distinct issues. That way it's easy to focus and fix them one at a time.

-- 

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/

My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by sbabcoc** [comment]
If no further fixes will be offered for the 6.x releases, I'll just stick with 6.10. No point in opening issue reports if no new 6.x releases will address them. I can open an issue report for the 7.0.0 behavior.

**Comment by juherr** [comment]
We don't plan a new 6.x release unless someone wants to support it and backports fixes from the 7.x branch ;)

**Comment by krmahadevan** [comment]
@sbabcoc - The example you shared in this issue, runs fine without any failures when tried on the latest snapshot of TestNG (7.0.0-SNAPSHOT). So I am closing this issue. If there are any other issues with listeners, please file new issues for them.
