### ISSUE TITLE
ant task could support resource collections for class ref

### ISSUE THREAD

**Issue by quidryan** [cbeust/testng#183]
Currently the TestNG ant task has the "classfilesetref" attribute, which serves its purpose. But it's restricted to just a <fileset>, which in themselves is a little limiting. Ant 1.8.0 introduced a concept of generalized "Resource Collections", which allows more source types and more complex operations on collections. E.g. I need to use <union> (http://ant.apache.org/manual/Types/resources.html#union) to merge two file sets. The resulting reference is a perfectly valid resource collection, and can be used by the junit ant task. For the sake of an example:

```
<fileset id="test.fileset.test" dir="${test.dir}" includes="**/*Test.class"/>
<fileset id="test.fileset.src" dir="${build.dir}" includes="**/*Test.class"/>
<union id="test.fileset"><fileset refid="test.fileset.test"/><fileset refid="test.fileset.src"/></union>
```

Please support resource collections in addition to fileset's for the class ref.

**Comment by juherr** [comment]
Fixed by #195
