### ISSUE TITLE
Configurable ThreadPoolExecutor

### ISSUE THREAD

**Issue by atulagrawal** [cbeust/testng#1835]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
TestNG class is having tight coupling with GraphThreadPoolExecutor. This code can be further improved by decoupling the implementation. 

Once Executor is configurable, developers can control the execution of test cases as per their own requirements. This will also allow them to try out different implementation, algorithms and design styles. 

The implementing class can be loaded either via property files or via command line args.

Ref: https://github.com/cbeust/testng/blob/testng-6.8.9/src/main/java/org/testng
/TestNG.java#L1163

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@atulagrawal - What sort of customization do you have in mind? Can you please elaborate. 
What do you have as issues in terms of the current implementation of `GraphThreadPoolExecutor`. I would be curious to hear about that.

@cbeust @juherr - Your thoughts on this?

**Comment by atulagrawal** [comment]
We are using TestNg for the functional testing of micro services that are running in distributed environment and have multiple upstream and downstream integrations. 

The test cases for these services are complex in nature and have complex test scenarios, data setup requirements and validations requirements. This complexity has caused unwanted test flakiness, reliability issues and longer run times.

In order to fix above mentioned problems, we are splitting up a test method into multiple logical test steps (divide and conquer approach) and then running them as per required order (parallel, sequential etc.). This has helped us a lot and that is why we want to extend current implementation of GraphThreadPoolExecutor.

**Comment by juherr** [comment]
I'm not sure to understand the use case but I don't see any problem to add another configurable thing.

@atulagrawal Are you able to propose a pull request? It will help us to see what will be the impact of the change.

**Comment by atulagrawal** [comment]
Sure. I will do the required analysis and raise PR.

**Comment by krmahadevan** [comment]
@atulagrawal - Any updates on this since you mentioned you were going to be raising a PR? 
Just trying to ensure that new bugs logged get looked at in time and doesn't add to the backlog.

**Comment by atulagrawal** [comment]
@krmahadevan I did some initial analysis and found that changes will require significant refactoring. 

I am thinking of doing this in incremental way. First by doing changes to make code more readable and extensible and then thiking of apllying Abstract Factory design pattern across all factories.

Let me know your thoughts !!

**Comment by krmahadevan** [comment]
> First by doing changes to make code more readable and extensible 

What code are you hinting at? 

> then thinking of apllying Abstract Factory design pattern across all factories.

A PR would better convey the intent.
