### ISSUE TITLE
IHookable Listener not working with spring-test

### ISSUE THREAD

**Issue by waitshang** [cbeust/testng#1840]
### TestNG Version
> Note: only the latest version is supported
6.14.3
### Expected behavior
The run() method should invoked before every @Test tagged method. 

### Actual behavior
The run() method never invoked.

### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

#### Test Class/Method
	public class TestClass extends AbstractTestNGSpringContextTests {
		@Test
		public void test_method1(){...}
	}
#### Listener
	public class MyListener implements IHookable {
		
		@Override
		public void run(IHookCallBack callBack, ITestResult testResult) {
			if (flag) {
				callBack.runTestMethod(testResult);
			}
		}
	}

**Comment by krmahadevan** [comment]
@waitshang

The IHookable interface is meant to be implemented by a test class (a class
that houses one or more @Test annotated test methods). When such a class
implements the IHookable interface, then TestNG guarantees that the run()
method from the IHookable interface would be executed instead of invoking
each and every @Test method in the test class. This interface is not meant
to be used like an interface.

**Comment by krmahadevan** [comment]
I meant to say, IHookable is not meant to be used as a listener (which you
inject via a @Listeners annotation or via the <listeners> tag in your suite
xml file)

**Comment by krmahadevan** [comment]
Closing this issue, since this is not a problem.

**Comment by waitshang** [comment]
@krmahadevan Thanks a lot. I wander is there a way to invoke the `run()` method before every `@Test` annotated method.

**Comment by krmahadevan** [comment]
@waitshang - No. That is not possible. If you want to run something before every `@Test` invocation, you should leverage annotations such as `@BeforeMethod` (or) use a TestNG listener such as `IInvokedMethodListener`
