### ISSUE TITLE
Cannot package JAR with test classes

### ISSUE THREAD

**Issue by plaidshirtakos** [cbeust/testng#1844]
### TestNG Version
6.14.3

### Expected behavior
JAR file should be generated with test classes.

### Actual behavior
I use maven-assembly-plugin in pom.xml to generate jar.

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>test.LeanFTest</mainClass>
                        </manifest>
                    </archive>
                    <finalName>${project.artifactId}-fatjar-${project.version}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptors>
                        <descriptor>src/main/assembly/leanft-assembly.xml</descriptor>
                    </descriptors>
                </configuration>
            </plugin>
```

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
This project has same structure as my project: https://github.com/kohli-harshit/leanft-testng-template

**Comment by krmahadevan** [comment]
This issue has got nothing to do with TestNG.
Also since the project shared has references to licensed jars that are not available in the internet, we cannot use this project as is to simulate the problem.

So I went ahead and created a sample project using which you can see how to solve the problem.

[kungfu-panda.zip](https://github.com/cbeust/testng/files/2142290/kungfu-panda.zip)

Below is a sample that shows how the test classes are being executed via the uber jar

```
23:03 $ java -jar target/kungfu-panda-1.0-SNAPSHOT.jar -testclass com.rationaleemotions.MasterShifu
Executing :com.rationaleemotions.MasterShifu.testOne()
Executing :com.rationaleemotions.MasterShifu.testTwo()

===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

```

Closing this question with resolution as *Question answered*

**Comment by krmahadevan** [comment]
I have also updated my answer to your question on stackoverflow to include the required information https://stackoverflow.com/a/51034894/679824
