### ISSUE TITLE
Release a 7.0-alpha-1 version

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1862]
From #1743

**Comment by slipwalker** [comment]
@juherr When it's expected to see new version available with all of the changes and fixes described in CHANGES.txt file? There are quite a lot of good fixes and features which we're waiting for. Thanks in advance.

**Comment by juherr** [comment]
@slipwalker It's already the case: https://search.maven.org/artifact/org.testng/testng/7.0.0-beta1/jar

**Comment by slipwalker** [comment]
@juherr but I still can reproduce GITHUB-1709 in 7.0.0-beta1 that is marked as fixed in CHANGES.txt file. That's why I was wondering about new release cause it looks like that fix is not there (and might be some others too).

**Comment by slipwalker** [comment]
@juherr Any thoughts on that inconsistency I mentioned above? I would really appreciate to get that fix in new release.

**Comment by juherr** [comment]
@slipwalker I reopen the issue

**Comment by krmahadevan** [comment]
@slipwalker - Do you have a sample that can be used to recreate this issue ?
