### ISSUE TITLE
Support fractional per-core thread counts in Maven

### ISSUE THREAD

**Issue by Pr0methean** [cbeust/testng#1867]
### TestNG Version
6.11 (maven-surefire-plugin 2.21.0, maven-failsafe-plugin 2.17)

### Expected behavior
I can set something like this in the Surefire and Failsafe plugin configuration to indicate that I want 1 thread per 2 cores (e.g. because my tests themselves use up to 2 threads each -- my actual use case -- or because I'm running on a VM that has about half the host's resources but sees all of them) :
```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.21.0</version>
         <configuration>
            <parallel>tests</parallel>
            <threadCount>0.5</threadCount>
            <perCoreThreadCount>true</perCoreThreadCount>
          </configuration>
        </plugin>
```
### Actual behavior
`threadCount` is specified to be an integer.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
See above.

**Comment by krmahadevan** [comment]
@Pr0methean - The `threadCount` attribute is internally used to decide the size of the `ThreadPoolExecutor` pool size. I dont think it accepts a fractional value. I am guessing that this configuration viz., `threadCount` is being exposed by Maven surefire plugin. So you might want to file an issue here https://github.com/krmahadevan/maven-surefire

**Comment by juherr** [comment]
@krmahadevan https://issues.apache.org/jira/projects/SUREFIRE/issues looks better ;)

**Comment by krmahadevan** [comment]
@juherr - Should we close this issue ?

**Comment by juherr** [comment]
Out of TestNG scope.
