### ISSUE TITLE
Using shared dataprovider for all test cases but testng running single test cases multiple times

### ISSUE THREAD

**Issue by kmehta30** [cbeust/testng#1868]
### TestNG Version
> 6.14.3
### Expected behavior
I am reading data from excel and providing the same data provider to all test cases but within the test case I am filtering data based on test case name by an if condition. When running from pom.xml or testNg each test should run one time only.

### Actual behavior
TestNg is running my first test case 7 time although in excel there are only two rows out of which one should match with the test case by name.

###Agenda
I am trying to create a integrated project for UI and Api flow automation with selenium and restAssure.

### Is the issue reproductible on runner?
This is reproducible with eclipse and maven.

### Test case sample
![image](https://user-images.githubusercontent.com/12829098/42795852-2b8d9c32-89b9-11e8-8b88-3bd4be07a4d9.png)

![image](https://user-images.githubusercontent.com/12829098/42795870-3e3dd3f6-89b9-11e8-9468-5e89725e6503.png)
![image](https://user-images.githubusercontent.com/12829098/42795880-4c072a1e-89b9-11e8-971d-3aeae4ea127b.png)

**Comment by krmahadevan** [comment]
@kmehta30 - Couple of things.

1. Is this issue reproducible using the latest released version of TestNG (v6.14.3) ? 
2. Screenshots of code doesn't help a lot. Can you please help create a simple standalone test (which doesn't use the excel etc., ) that can be used to reproduce the problem and include the actual code in your issue by editing your issue and adding it there. You can include the source code between "```java" and "```"
3. How are you running your tests? If you are using maven, please help share the testng suite file, the actual maven command, your surefire plugin information etc., that can help us debug to find out what is going wrong.

**Comment by kmehta30** [comment]
Yes issue is reproducible with latest version.
 Can I share the whole code with you in some way.

**Comment by kmehta30** [comment]
[IdentityCore.zip](https://github.com/cbeust/testng/files/2200204/IdentityCore.zip)

Here is the standalone file. 
Run from testNg.xml and Pom.xml. Notice first test run multiple times

**Comment by krmahadevan** [comment]
@kmehta30 - Couple of things..
`The testng.xml` that you are talking about has only this 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">
	<listeners>
		<listener class-name="com.identitycore.listners.ExtentReportListener"></listener>
	</listeners>
  <test thread-count="5" name="Test">
    <classes>
      <class name="Garbage.Standalone"/>
    </classes>
  </test> <!-- Test -->
</suite> <!-- Suite -->
```

The corresponding java class looks like below

```java
package Garbage;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;

import com.identitycore.base.InitTest;
import com.identitycore.utils.Timeout;
import com.identitycore.utils.WebDriverUtility;
import com.identitycore.workflows.FbLoginActions;

public class Standalone {

	@Test
	public void verifyFbLogin() throws Exception {
		String testname = Thread.currentThread().getStackTrace()[1].getMethodName();
		InitTest.createDriver(testname);
		WebDriver driver = InitTest.getDriver(testname);
		driver.get("https://d23pywlk4w9g3a.cloudfront.net");
		WebDriverUtility.waitForLoad(driver, Timeout.T10s.getValue());
		String fbToken = FbLoginActions.getFbJwtToken(driver, "kamal.mehta.qa111@gmail.com", "test123");

	}

	@Test
	public void verifyLoginWithEmailPhoneNumber() throws Exception {
		String testname = Thread.currentThread().getStackTrace()[1].getMethodName();
		System.out.println(testname);
	}
}
```

I dont see a reference to either any excel spreadsheet nor a data provider here.

Are you sure you shared the correct project ? Can you please help just share a trimmed version of the test classes in question that can be used to reproduce the problem. Its kind of hard to basically sift through a full project and figure out things in a limited time.

**Comment by krmahadevan** [comment]
ping @kmehta30 - Gentle reminder on this.

**Comment by krmahadevan** [comment]
No response from the user. Closing this issue. Please comment when you have an answer to the question.
