### ISSUE TITLE
Can't differentiate between skip source of test method

### ISSUE THREAD

**Issue by dagansandler** [cbeust/testng#1869]
When a configuration method fails, tests which are skipped as a consequence are injected with the failure cause.
This change was introduced to resolve issue #674. The accepted fix is: #1242 

While this fix gives valuable information that wasn't present before, it presents a new challenge in understanding where the Throwable originated from. Did the test method throw this Throwable itself, and if not, which previous invocation _did_ throw this exception?

**Comment by dagansandler** [comment]
Yes, having access to the original ITestNGMethod that threw the exception would add the necessary information in my opinion.

I came across this issue because we're currently upgrading to the newest release version and it created a bug in our own reports.
Previously (using v6.9.4) when we encountered the state where the status of a @Test method is SKIP, we checked if there's a Throwable on the test result object. If there was, we logged it as the skip reason, and if not, we searched previous invocation (similar to the solution) and logged that error, but with some additional text, which indicated where the exception came from.
After we upgraded (v6.14.3), this logic is no longer applicable, and probably redundant as you always get the skip cause.

However, I still think there's a slight issue, where a config method explicitly throws a `SkipException`. That SkipException will be injected to the ITestResult of a test method being skipped. When a listener receives that SkipException, there's no way to tell if that exception came from the test method itself, or from a previous config method.

I'll try to provide a code sample as you suggested which will encapsulate the challenge more clearly.

**Comment by krmahadevan** [comment]
Please check if the fix https://github.com/cbeust/testng/pull/1879
basically addresses this problem.
As part of PR #1879, I have now provided a way from within ITestResult,
wherein you can query the ITestNGMethod's that were responsible for the
current method getting skipped.

>
