### ISSUE TITLE
Ambiguous behavior of IInvokedMethodListener

### ISSUE THREAD

**Issue by dagansandler** [cbeust/testng#1870]
### TestNG Version
6.14.3

IInvokedMethodListener Javadoc states:

> A listener that gets invoked before and after a method is invoked by TestNG.
> This listener will only be invoked for configuration and test methods.

However, it seems like actual behavior is a bit ambiguous (see #1602 and #1317)

### Expected behavior
Listener methods should only be called when a method is **invoked**

### Actual behavior
Even if method is skipped completely (because of a failed configuration for example), listener methods are still called

### Test case sample
Run the following test class with the provided listener
```java
public class SkippedTestMethod {
    @BeforeClass
    public void beforeClass() {
        throw new SkipException("Skippity Skip");
    }

    @Test
    public void testMethod() {
        // shouldn't ever be called
    }
}

public class SkippedTestMethodListener implements IInvokedMethodListener {

    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        if(method.isTestMethod()) {
            throw new RuntimeException("beforeInvocation should not be called if no actual invocation occurs!");
        }
    }

    @Override
    public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
        if(method.isTestMethod()) {
            throw new RuntimeException("afterInvocation should not be called if no actual invocation occurs!");
        }
    }
}
```

**Comment by dagansandler** [comment]
I realize that actually fixing this may introduce a regression with past behavior, so maybe the documentation should change.
However, I would prefer having the IInvokedMethodListener actually do what its name implies and listen to **invoked** methods

**Comment by krmahadevan** [comment]
@dagansandler - As part of 
https://github.com/cbeust/testng/issues/1883 we have now documented the existing listener invocation and order behavior.  

`beforeInvocation()` and `afterInvocation()` will be invoked all the time for all methods be it they got executed or if they got skipped.  That is the behavior I have noticed with the existing code, which is now documented via the tests that can be referred to by users to understand the order.

I will raise a PR to fix the javadocs of this interface.

**Comment by dagansandler** [comment]
Sounds good!

**Comment by kool79** [comment]
@juherr @cbeust 
I'm sad to read this issue. 
> Listener methods should only be called when a method is invoked
>> I realize that actually fixing this may introduce a regression with past behavior,
Actually fixing the #1602 was the regression with past behavior

For listener with name ***beforeInvocation*** I expect it will run ***before*** actual ***invocation***. 
 There is official documentation http://testng.org/doc/documentation-main.html#invokedmethodlistener where with "black-on-white" is written: 
  "The listener IInvokedMethodListener allows you to be notified whenever TestNG ***is about to invoke*** a test (annotated with @Test) or configuration"
 So 

  It is sad to say but starting from ~v6.11 we have many changes/PRs/isues which 'fix' testNG in the way that brokes compatibility.  Very often we fix the 'bugs' which are not actually bugs but the expected behaviour which is described in documentation (but who reads documentation? )
 Time to switch to junit ((
 Sorry for that spam in bugtracker

**Comment by krmahadevan** [comment]
The codebase has evolved over a period of time and many contributors have
come in and gone. So it's not necessary that everyone remembers the
functionality from when it was introduced.

That basically means that contributors fall back to the cushion that the
existing unit tests give in terms of guarding the existing behavior. So as
a contributor one tries to keep the existing tests happy.

In terms of broken functionalities, if there are any specific issues please
help file issues with details.

With only a handful bunch of us working on the codebase, we are trying our
level best.

With respect to this particular issue, please let me know what the problem
is. I will try to get to it at the earliest.

> --

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/

My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by dagansandler** [comment]
Hi @krmahadevan ,

I tend to agree with @kool79 in terms of the expectations from `IInvokedMethodListener`, which is why I opened this issue in the first place.

It's weird that an invocation listener gets called even if no invocations occur....

I regret my previous comment with regards to the solution, I should have tried to advocate my initial stance a bit more.

Since this is not released yet and there's work towards releasing 7.0.0 with standardizing listeners behavior, hopefully this solution can still be reversed?

The reasoning is that, as @kool79 mentions, there seem to be bug fixes, like #1602 which aren't really bug fixes. The issue there wasn't that `beforeInvocation` was not getting called for skipped tests, the issue was that `afterInvocation` **was** getting called.

So what happened was -
1. IInvokedMethodListener has always stated that it should be called for *invocations* of methods
2. There was a bug in the IInvokedMethodListener (`afterInvocation` was getting called for skipped tests)
3. #1602 Issue was reported but with the reverse actual and expected behavior
4. Bug was fixed with the wrong behavior, thus breaking consistency with the documentation
5. This issue was opened in regards to the inconsistency between the documentation and the behavior
6. The documentation was updated to reflect the current (and possibly incorrect) behavior

Thinking about it now, what is the difference (at the current state) between IInvokedMethodListener and ITestListener/IConfigurationListener ? What is the justification for IInvokedMethodListener's existence?

**Comment by krmahadevan** [comment]
@dagansandler - Can you please take a look at https://github.com/cbeust/testng/issues/1883 which attempts at baselining testng listener invocation behaviors as of today (which means which documents  the best to my understanding and without breaking any tests). In specific you might want to take a look at this test which attempts at clarifying the behavior via unit tests.

* [ListenerInvocationDefaultBehaviorTest.java]( https://github.com/cbeust/testng/blob/master/src/test/java/test/listeners/ordering/ListenerInvocationDefaultBehaviorTest.java)

* [ListenerInvocationListenerInvocationDisabledBehaviorTest.java](https://github.com/cbeust/testng/blob/master/src/test/java/test/listeners/ordering/ListenerInvocationListenerInvocationDisabledBehaviorTest.java)

in conjunction with the new parameter viz., `-alwaysrunlisteners` which controls *Should MethodInvocation Listeners be run even for skipped methods*

> Thinking about it now, what is the difference (at the current state) between IInvokedMethodListener and ITestListener/IConfigurationListener ? What is the justification for IInvokedMethodListener's existence?

`IInvokedMethodListener` is applicable to everything which means both `@Test` and a configuration method 

`IConfigurationListener` is specific to configuration methods alone. 

Also IInvokedMethodListener is agnostic of a method's result, whereas `IConfigurationListener` lets you handle specific results for a configuration method.

So request you to please revisit your use case using TestNG `7.0.0-SNAPSHOT` and let us know what discrepancies are still existing for you.

Last but not the least, TestNG project encourages people to contribute. So if you or @kool79 for that matter aren't happy with how things are, please do help raise pull requests that attempt at fixing the problem. We can brainstorm/discuss/debate on the behavior in the PR and then bring it to closure.

@cbeust @juherr - Please help chime in, if I have missed anything here.

**Comment by dagansandler** [comment]
OK, so I took a deeper look at the tests as @krmahadevan suggested, specifically with the `alwaysrunlisteners` flag set to **false**.
In this scenario, I expect the IInvokedMethodListener to only be called if a method is actually about to be invoked.

They look OK except for one test method - `test.listeners.ordering.ListenerInvocationListenerInvocationDisabledBehaviorTest#testOrderHasOnlyFailedAndSkippedConfigAndSkippedTestMethod`, in which the expected result should not contain `IINVOKEDMETHODLISTENER` events for the skipped configuration methods because that method is not being invoked.

I can open a new issue regarding this, and I can also provide a PR with a more specific test for the invoked method listener which can be used as a better reference for the logic concerning this listener.

In addition, I believe the `alwaysrunlisteners` flag is unnecessary, or at least should not affect `IInvokedMethodListener`, as that listener (IMO) should ONLY be called for methods which ARE invoked and NEVER called for methods which aren't going to be invoked.

**Comment by juherr** [comment]
@dagansandler please open a new issue
