### ISSUE TITLE
Possibility to add priority on a class in TestNG xml

### ISSUE THREAD

**Issue by ankitagarwal021** [cbeust/testng#1875]
Continuation to Issue id #1324
Class level priority annotation is throwing error "Annotation priority is not supported here"
`<class name="tests.Invoicing.GenerateCSVExtract" priority="1"/>`

Please advice what need to be done here?

**Comment by krmahadevan** [comment]
@ankitagarwal021 - I am not sure I understand what you are expecting.
You cannot set priority via suite xml file. That functionality doesn't exist as of today 
 I thought I already mentioned that to you in 
https://github.com/cbeust/testng/issues/1324#issuecomment-407653762

Is there something that you are expecting as additional information here ?

**Comment by krmahadevan** [comment]
Unless you aren't expecting any additional information here, this issue would also be closed off with a resolution as *Wont fix*

**Comment by ankitagarwal021** [comment]
@krmahadevan Thank you for reverting quickly and clarifying, your comment was not reflecting my side.
Please close the issue. sincere apologies for the inconvenience.

Regards
Ankit Agarwal

**Comment by krmahadevan** [comment]
Closing this issue.
