### ISSUE TITLE
suite parallel="methods" does not work when there are multiple <test> tags in the testng.xml

### ISSUE THREAD

**Issue by sthadeshwar** [cbeust/testng#188]
suite parallel="methods" does not work when there are multiple <test> tags in the testng xml file. It runs each <test> tag in its own thread-pool and the execution is sequential.

Below is the example:

testng.xml:

```xml
<suite name="p,q suite(s)" verbose="1" parallel="methods" thread-count="50">

 <test name="AB">
      <classes>
       <class name="com.mytests.parallels.A" />
           <class name="com.mytests.parallels.B" />
    </classes>
 </test>

 <test name="CD">
      <classes>
       <class name="com.mytests.parallels.C" />
           <class name="com.mytests.parallels.D" />
    </classes>
 </test>

 <test name="EF">
      <classes>
       <class name="com.mytests.parallels.E" />
           <class name="com.mytests.parallels.F" />
    </classes>
 </test>

</suite>
```

Below is a sample class A.java and all other test classes mentioned in above xml have similar dummy tests which just prints the test name and the thread name:

```java
@Test
public void testA1() {
    System.out.println("Executing testA1 : " + Thread.currentThread().getName());
    System.out.println("Waiting for 10 secs inside testA1 : " + System.currentTimeMillis());
    CommonUtils.sleep(10);
    System.out.println("Done waiting for 10 secs inside testA1 : " + System.currentTimeMillis());
}

@Test
public void testA2() {
    System.out.println("Executing testA2 : " + Thread.currentThread().getName());
}

@Test
public void testA3() {
    System.out.println("Executing testA3 : " + Thread.currentThread().getName());
}
....
....
```

Below is the output:

```
run:
   [testng] [TestNGAntTask] TESTNG PASSED @/var/folders/Xr/XrWzi723gI0qWejNi3tO+JPvw5I/-Tmp-/testng5975172026000129049 WHICH CONTAINS:
   [testng]   -log
   [testng]   2
   [testng]   -suitename
   [testng]   Ant suite
   [testng]   -testname
   [testng]   Ant test
   [testng]   /path-to-my-testng-file/run-testng.xml
   [testng] [TestNG] Running:
   [testng]   /path-to-my-testng-file/run-testng.xml
   [testng] 
   [testng] [TestRunner] Starting executor for test AB with time out:2147483647 milliseconds.
   [testng] Executing testB5 : pool-2-thread-10
   [testng] Executing testB4 : pool-2-thread-9
   [testng] Executing testB2 : pool-2-thread-7
   [testng] Executing testA1 : pool-2-thread-1
   [testng] Executing testA3 : pool-2-thread-3
   [testng] Executing testB1 : pool-2-thread-6
   [testng] Executing testA5 : pool-2-thread-5
   [testng] Executing testB3 : pool-2-thread-8
   [testng] Executing testA4 : pool-2-thread-4
   [testng] Executing testA2 : pool-2-thread-2
   [testng] Waiting for 10 secs inside testA1 : 1331249133317        <--- Execution of entire test suite blocks here
   [testng] Done waiting for 10 secs inside testA1 : 1331249143320
   [testng] PASSED: testB4
   [testng] PASSED: testB5
   [testng] PASSED: testB2
   [testng] PASSED: testA3
   [testng] PASSED: testB1
   [testng] PASSED: testA5
   [testng] PASSED: testB3
   [testng] PASSED: testA4
   [testng] PASSED: testA2
   [testng] PASSED: testA1
   [testng] 
   [testng] ===============================================
   [testng]     AB
   [testng]     Tests run: 10, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] Executing testC1 : pool-3-thread-1
   [testng] Executing testC3 : pool-3-thread-3
   [testng] Executing testC2 : pool-3-thread-2
   [testng] Executing testC4 : pool-3-thread-4
   [testng] Executing testC5 : pool-3-thread-5
   [testng] Executing testD1 : pool-3-thread-6
   [testng] Executing testD2 : pool-3-thread-7
   [testng] [TestRunner] Starting executor for test CD with time out:2147483647 milliseconds.
   [testng] Executing testD3 : pool-3-thread-8
   [testng] Executing testD4 : pool-3-thread-9
   [testng] Executing testD5 : pool-3-thread-10
   [testng] PASSED: testC1
   [testng] PASSED: testC3
   [testng] PASSED: testC2
   [testng] PASSED: testC4
   [testng] PASSED: testC5
   [testng] PASSED: testD1
   [testng] PASSED: testD2
   [testng] PASSED: testD3
   [testng] PASSED: testD4
   [testng] PASSED: testD5
   [testng] 
   [testng] ===============================================
   [testng]     CD
   [testng]     Tests run: 10, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] Executing testE1 : pool-4-thread-1
   [testng] Executing testE2 : pool-4-thread-2
   [testng] Executing testE3 : pool-4-thread-3
   [testng] Executing testE4 : pool-4-thread-4
   [testng] Executing testE5 : pool-4-thread-5
   [testng] Fxecuting testF1 : pool-4-thread-6
   [testng] Fxecuting testF2 : pool-4-thread-7
   [testng] [TestRunner] Starting executor for test EF with time out:2147483647 milliseconds.
   [testng] Fxecuting testF3 : pool-4-thread-8
   [testng] Fxecuting testF4 : pool-4-thread-9
   [testng] Fxecuting testF5 : pool-4-thread-10
   [testng] PASSED: testE2
   [testng] PASSED: testE3
   [testng] PASSED: testE4
   [testng] PASSED: testE5
   [testng] PASSED: testF1
   [testng] PASSED: testF2
   [testng] PASSED: testF3
   [testng] PASSED: testF4
   [testng] PASSED: testF5
   [testng] PASSED: testE1
   [testng] 
   [testng] ===============================================
   [testng]     EF
   [testng]     Tests run: 10, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng] p,q suite(s)
   [testng] Total tests run: 30, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] [TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@2a9df354: 25 ms
   [testng] [TestNG] Time taken by [TestListenerAdapter] Passed:0 Failed:0 Skipped:0]: 0 ms
   [testng] [TestNG] Time taken by org.testng.reporters.EmailableReporter@51b48197: 6 ms
   [testng] [TestNG] Time taken by org.testng.reporters.JUnitReportReporter@58ecb281: 6 ms
   [testng] [TestNG] Time taken by org.testng.reporters.XMLReporter@3a6ac461: 13 ms

BUILD SUCCESSFUL
Total time: 13 seconds
```

From the output you can see that the execution gets blocked at testA1's sleep() for 10 seconds. Also, testng creates 3 thread-pools since there are 3 <test> tags and executes the test tags sequentially.

---

Now if I update my testng.xml to something like this:

```xml
<test name="ABCDEF">
    <classes>
        <class name="com.mytests.parallels.A" />
                    <class name="com.mytests.parallels.B" />
        <class name="com.mytests.parallels.C" />
                    <class name="com.mytests.parallels.D" />
        <class name="com.mytests.parallels.E" />
                    <class name="com.mytests.parallels.F" />
           </classes>
</test>
```

It works just as expected: It will run ALL the methods in parallel in its own thread:

run:
```
   [testng] [TestNGAntTask] TESTNG PASSED @/var/folders/Xr/XrWzi723gI0qWejNi3tO+JPvw5I/-Tmp-/testng3337858474629479499 WHICH CONTAINS:
   [testng]   -log
   [testng]   2
   [testng]   -suitename
   [testng]   Ant suite
   [testng]   -testname
   [testng]   Ant test
   [testng]   /path-to-my-testng-file/run-testng.xml
   [testng] [TestNG] Running:
   [testng]   /path-to-my-testng-file/run-testng.xml
   [testng] 
   [testng] [TestRunner] Starting executor for test ABCDEF with time out:2147483647 milliseconds.
   [testng] Executing testC1 : pool-2-thread-11
   [testng] Executing testA5 : pool-2-thread-5
   [testng] Executing testB1 : pool-2-thread-6
   [testng] Executing testE1 : pool-2-thread-21
   [testng] Executing testA1 : pool-2-thread-1
   [testng] Executing testD4 : pool-2-thread-19
   [testng] Executing testA4 : pool-2-thread-4
   [testng] Fxecuting testF4 : pool-2-thread-29
   [testng] Executing testA3 : pool-2-thread-3
   [testng] Executing testB4 : pool-2-thread-9
   [testng] Executing testE3 : pool-2-thread-23
   [testng] Executing testA2 : pool-2-thread-2
   [testng] Executing testB5 : pool-2-thread-10
   [testng] Executing testE5 : pool-2-thread-25
   [testng] Executing testD3 : pool-2-thread-18
   [testng] Executing testE2 : pool-2-thread-22
   [testng] Executing testD2 : pool-2-thread-17
   [testng] Executing testE4 : pool-2-thread-24
   [testng] Executing testD1 : pool-2-thread-16
   [testng] Executing testB2 : pool-2-thread-7
   [testng] Waiting for 10 secs inside testA1 : 1331249533970
   [testng] Fxecuting testF3 : pool-2-thread-28
   [testng] Executing testC2 : pool-2-thread-12
   [testng] Executing testB3 : pool-2-thread-8
   [testng] Executing testC4 : pool-2-thread-14
   [testng] Fxecuting testF5 : pool-2-thread-30
   [testng] Executing testD5 : pool-2-thread-20
   [testng] Executing testC3 : pool-2-thread-13
   [testng] Fxecuting testF1 : pool-2-thread-26
   [testng] Executing testC5 : pool-2-thread-15
   [testng] Fxecuting testF2 : pool-2-thread-27
   [testng] Done waiting for 10 secs inside testA1 : 1331249543974
   [testng] PASSED: testA5
   [testng] PASSED: testB1
   [testng] PASSED: testC1
   [testng] PASSED: testD4
   [testng] PASSED: testA4
   [testng] PASSED: testF4
   [testng] PASSED: testA3
   [testng] PASSED: testB4
   [testng] PASSED: testE3
   [testng] PASSED: testA2
   [testng] PASSED: testB5
   [testng] PASSED: testE5
   [testng] PASSED: testD3
   [testng] PASSED: testE2
   [testng] PASSED: testD2
   [testng] PASSED: testE4
   [testng] PASSED: testD1
   [testng] PASSED: testB2
   [testng] PASSED: testF3
   [testng] PASSED: testC2
   [testng] PASSED: testB3
   [testng] PASSED: testC4
   [testng] PASSED: testF5
   [testng] PASSED: testD5
   [testng] PASSED: testC3
   [testng] PASSED: testF1
   [testng] PASSED: testC5
   [testng] PASSED: testF2
   [testng] PASSED: testE1
   [testng] PASSED: testA1
   [testng] 
   [testng] ===============================================
   [testng]     ABCDEF
   [testng]     Tests run: 30, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng] p,q suite(s)
   [testng] Total tests run: 30, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] [TestNG] Time taken by [TestListenerAdapter] Passed:0 Failed:0 Skipped:0]: 0 ms
   [testng] [TestNG] Time taken by org.testng.reporters.JUnitReportReporter@2acdb06e: 10 ms
   [testng] [TestNG] Time taken by org.testng.reporters.XMLReporter@6fc5f743: 12 ms
   [testng] [TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@15a62c31: 17 ms
   [testng] [TestNG] Time taken by org.testng.reporters.EmailableReporter@1f4384c2: 8 ms

BUILD SUCCESSFUL
Total time: 13 seconds
```

**Comment by sureshgupta-cpi** [comment]
Cedric - I also see the same issue. Test methods run in different threads but the execution is sequential i.e. Test2 starts on a new thread only after Test1 finishes.

**Comment by juherr** [comment]
@sureshgupta-cpi Could you share a project that shows the problem? (or maybe propose a PR with a test)

**Comment by sureshgupta-cpi** [comment]
TestNG Version: 6.9.4
JDK: 1.8

parallesuite.xml:

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Parallel Issue Suite" parallel="methods" thread-count="3" verbose="1">
	<test name="Test1" preserve-order="false">
		<classes> <class name="script.ParallelTest"></class> </classes>
	</test>
	<test name="Test2" preserve-order="false">
		<classes> <class name="script.ParallelTest"></class> </classes>
	</test>
	<test name="Test3" preserve-order="false">
		<classes> <class name="script.ParallelTest"></class> </classes>
	</test>
</suite>


ParallelTest.java:

import org.testng.annotations.Test;
import java.util.Date;

public class ParallelTest {
    @Test
    public void sampleTest(){
        System.out.println("Inside sampleTest, Current Time: " + new Date() + ", Thread ID: " + Thread.currentThread().getId());

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}


Output:
Inside sampleTest, Current Time: Mon Oct 05 16:58:00 IST 2015, Thread ID: 12
Inside sampleTest, Current Time: Mon Oct 05 16:58:10 IST 2015, Thread ID: 13
Inside sampleTest, Current Time: Mon Oct 05 16:58:20 IST 2015, Thread ID: 14

===============================================
Parallel Issue Suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================


If you look closely at the Current Time, you will notice that next test case starts after previous test has finished (i.e. after 10 seconds)

**Comment by sureshgupta-cpi** [comment]
TestNG Version: 6.9.4
JDK: 1.8

parallelsuite.xml
<suite name="Parallel Issue Suite" parallel="methods" thread-count="3" verbose="1">
	<test name="Test1" preserve-order="false">
		<classes> <class name="script.ParallelTest"></class> </classes>
	</test>
	<test name="Test2" preserve-order="false">
		<classes> <class name="script.ParallelTest"></class> </classes>
	</test>
	<test name="Test3" preserve-order="false">
		<classes> <class name="script.ParallelTest"></class> </classes>
	</test>
</suite>


ParallelTest.java:

import org.testng.annotations.Test;
import java.util.Date;
public class ParallelTest {
    @Test
    public void sampleTest(){
        System.out.println("Inside sampleTest, Current Time: " + new Date() + ", Thread ID: " + Thread.currentThread().getId());

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

Inside sampleTest, Current Time: Mon Oct 05 16:58:00 IST 2015, Thread ID: 12
Inside sampleTest, Current Time: Mon Oct 05 16:58:10 IST 2015, Thread ID: 13
Inside sampleTest, Current Time: Mon Oct 05 16:58:20 IST 2015, Thread ID: 14

===============================================
Parallel Issue Suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================

If you look closely at the Curren Time, you will notice that next test case starts after previous test case has finished i.e. after 10 seconds

**Comment by sureshgupta-cpi** [comment]
TestNG Version: 6.9.4
JDK: 1.8

parallelsuite.xml:

    <suite name="Parallel Issue Suite" parallel="methods" thread-count="3" verbose="1">
    	<test name="Test1" preserve-order="false">
    		<classes> <class name="script.ParallelTest"></class> </classes>
    	</test>
    	<test name="Test2" preserve-order="false">
    		<classes> <class name="script.ParallelTest"></class> </classes>
    	</test>
    	<test name="Test3" preserve-order="false">
    		<classes> <class name="script.ParallelTest"></class> </classes>
    	</test>
    </suite>

ParallelTest.java:
<pre><code>
import org.testng.annotations.Test;
import java.util.Date;
public class ParallelTest {
    @Test
    public void sampleTest(){
        System.out.println("Inside sampleTest, Current Time: " + new Date() + ", Thread ID: " + Thread.currentThread().getId());

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
</code></pre>

Output:

Inside sampleTest, Current Time: Mon Oct 05 16:58:00 IST 2015, Thread ID: 12
Inside sampleTest, Current Time: Mon Oct 05 16:58:10 IST 2015, Thread ID: 13
Inside sampleTest, Current Time: Mon Oct 05 16:58:20 IST 2015, Thread ID: 14

**===============================================
Parallel Issue Suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================**

**If you look closely at the Current Time, you will notice that the next test case starts after the previous test case has finished i.e. after 10 seconds**

**Comment by Hazok** [comment]
@sthadeshwar @cbeust @juherr 

Was there every any resolution to this issue? I am facing the same problem sthadeshwar described when there are multiple XML suite files.

In our setup, we have many suite XML files that are nested inside a "parent" suite XML file. We run our tests using Maven Surefire.

I've tried many different combinations for the options and values used for executing tests in parallel in both the Surefire and while I can get the methods within each of the nested suite XML file to execute in parallel, each suite XML file is executed in sequence.

For example, the parent XML file is something like:

```
<suite name="MySuite" verbose="1" parallel="tests" thread-count="50">
    <suite-files>
        <suite-file path="path1.xml"/>
        <suite-file path="path2.xml"/>
    </suite-files>
<suite>
```

Then lets say in path1.xml there is Test1A and Test1B and in path2.xml there is Test2A and Test2B. While Test1A will run in parallel with Test1B, and Test2A will run in parallel with Test2B, everything in path1.xml has to complete before anything is started in path2.xml.

How do I configure TestNG to run _**all of the tests**_ from both suites files in parallel so Test2A and Test2B does not wait for Test1A and Test1B to finish first?

This behavior is consistent and can easily be captured from logging. This is not a mix-up with how to analyze parallel processing behavior, but just an ignorance on what options needs to be set in Surefire or TestNG to run this as desired.

I've looked through the documentation several times and this scenario is not mentioned. There also appears to be a lack of forum posts regarding this issue and this GitHub issue is the first discussion I've found on the issue.

**Comment by Hazok** [comment]
@juherr I did a bit of digging and played around with this one a bit more, which it turns out that there is an option in 6.9.8 that handles this quite well. Without any change to my existing suite file, I simply updated my pom to use TestNG 6.9.8, added JUnit since we were pulling in JUnit as a transitive dependency from TestNG 6.9.6 which changed going to 6.9.8, then added the following tags to the Surefire plugin nested under the `configuration` tag:

```
							<parallel>all</parallel>
							<useUnlimitedThreads>true</useUnlimitedThreads>
							<properties>
								<property>
									<name>suitethreadpoolsize</name>
									<value>20</value>
								</property>
							</properties>
```

Now I'm not certain if parallel is really needed or not since it seems to be a value specific to JUnit, but this was the configuration that finally worked. Here's the final configuration for the Maven profile we use for end-to-end testing with project-specific properties removed:

```
		<profile>
			<id>e2e-test</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>2.19</version>
						<dependencies>
							<dependency>
								<groupId>org.apache.maven.surefire</groupId>
								<artifactId>surefire-testng</artifactId>
								<version>2.19</version>
							</dependency>
						</dependencies>
						<configuration>
							<suiteXmlFiles>
								<suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
							</suiteXmlFiles>
							<parallel>all</parallel>
							<useUnlimitedThreads>true</useUnlimitedThreads>
							<properties>
								<property>
									<name>suitethreadpoolsize</name>
									<value>20</value>
								</property>
							</properties>
							<excludes>
								<exclude>**/junit/**</exclude>
							</excludes>
							<includes>
								<include>**/e2e/**</include>
							</includes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
```

We might be able to cleanup some options further, not sure if includes/excludes is still needed, but wanted to give the FYI that I finally did get this to work. Would be nice if the TestNG documentation were updated with more examples of use cases like this one to help TestNG clients to get things going faster.

Thanks for taking a look and reopening this issue.

**Comment by juherr** [comment]
@Hazok Are you able to reproduce the issue without maven?

**Comment by krmahadevan** [comment]
@juherr - I think the reason behind this issue is [this](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/SuiteRunner.java#L412) statement

`boolean testsInParallel = XmlSuite.ParallelMode.TESTS.equals(xmlSuite.getParallel());`

If we change it to 
`boolean testsInParallel = !XmlSuite.ParallelMode.NONE.equals(xmlSuite.getParallel());`

This would ensure that all the `<test>` tags are always run in parallel for all parallel modes except when its disabled.

But the flip side of this is that, the number of parallel threads is first always dependent on the number of `<test>` tags. So for the following scenario

* Thread count = 10
* Number of `<test>` tags = 3
* Number of classes per `<test>` tag = 1
* Number of `@Test` methods per class = 2

and with a test class and test runner as below 

**Test class**
```java
import org.testng.annotations.Test;

import java.util.Date;

public class Issue188TestSample {
    @Test
    public void sampleTest() {
        printer("sampleTest");
    }

    @Test
    public void anotherSampleTest() {
        printer("anotherSampleTest");
    }

    private void printer(String text) {
        Thread t = Thread.currentThread();

        System.out.println("Inside " + text + ", Current Time: " + new Date() + ", Thread ID: " + Thread.currentThread().getId()
                + ", Thread Group Name : " + t.getThreadGroup().getName());
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
}
```
**Test runner**
```java
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.util.Collections;

public class Issue188TestRunner {

    @Test
    public void testMethod() {
        TestNG testng = new TestNG();
        XmlSuite xmlSuite = new XmlSuite();
        xmlSuite.setParallel(XmlSuite.ParallelMode.METHODS);
        xmlSuite.setVerbose(2);
        xmlSuite.setThreadCount(10);
        xmlSuite.setName("Parallel Issue Suite");
        createXmlTest(xmlSuite, "1", Issue188TestSample.class);
        createXmlTest(xmlSuite, "2", Issue188TestSample.class);
        createXmlTest(xmlSuite, "3", Issue188TestSample.class);
        testng.setXmlSuites(Collections.singletonList(xmlSuite));
        testng.run();
    }

    private static XmlTest createXmlTest(XmlSuite xmlSuite, String suffix, Class<?> clazz) {
        XmlTest xmlTest = new XmlTest(xmlSuite);
        xmlTest.setThreadCount(1);
        xmlTest.setParallel(XmlSuite.ParallelMode.METHODS);
        xmlTest.setName("Test" + suffix);
        xmlTest.setXmlClasses(Collections.singletonList(new XmlClass(clazz)));
        return xmlTest;
    }
}
```

I always notice the output as below 

```
Inside anotherSampleTest, Current Time: Fri Oct 20 17:31:40 IST 2017, Thread ID: 16, Thread Group Name : main
Inside anotherSampleTest, Current Time: Fri Oct 20 17:31:40 IST 2017, Thread ID: 15, Thread Group Name : main
Inside anotherSampleTest, Current Time: Fri Oct 20 17:31:40 IST 2017, Thread ID: 14, Thread Group Name : main
Inside sampleTest, Current Time: Fri Oct 20 17:31:50 IST 2017, Thread ID: 15, Thread Group Name : main
Inside sampleTest, Current Time: Fri Oct 20 17:31:50 IST 2017, Thread ID: 14, Thread Group Name : main
Inside sampleTest, Current Time: Fri Oct 20 17:31:50 IST 2017, Thread ID: 16, Thread Group Name : main
```

So TestNG resorts to true parallelism (i.e., running *classes|instances|methods* in parallel) when set at the `<suite>` level, is applicable only when `<suite>` has just 1 `<test>` tag. If there are multiple `<test>` tags, then TestNG will either run all the `<test>` tags in parallel (when specified via the `parallel` attribute) or in sequence. No other form of parallelism seems to be currently available.

But this changeset (if we agree to apply it) will basically break the parallel execution test suite that @selenareneephillips has built. Not sure what direction should I move towards.

**Comment by juherr** [comment]
@krmahadevan A previous comment said it was working with ` 6.9.8`. Could you check the behavior? It will help to decide what is the expected behavior ;)

**Comment by krmahadevan** [comment]
@juherr - I don't think it works with TestNG 6.9.8 as well. Here's the output 

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running test.Issue188TestRunner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@368239c8
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="10" verbose="2" name="Parallel Issue Suite" parallel="methods">
  <test name="Test1" parallel="methods">
    <classes>
      <class name="test.Issue188TestSample"/>
    </classes>
  </test> <!-- Test1 -->
  <test name="Test2" parallel="methods">
    <classes>
      <class name="test.Issue188TestSample"/>
    </classes>
  </test> <!-- Test2 -->
  <test name="Test3" parallel="methods">
    <classes>
      <class name="test.Issue188TestSample"/>
    </classes>
  </test> <!-- Test3 -->
</suite> <!-- Parallel Issue Suite -->

...
... TestNG 6.9.8 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
  Command line suite

[TestRunner] Starting executor for test Test1 with time out:2147483647 milliseconds.
Inside anotherSampleTest, Current Time: Mon Oct 23 08:25:51 IST 2017, Thread ID: 10, Thread Group Name : main
Inside sampleTest, Current Time: Mon Oct 23 08:25:51 IST 2017, Thread ID: 11, Thread Group Name : main
PASSED: anotherSampleTest
PASSED: sampleTest

===============================================
    Test1
    Tests run: 2, Failures: 0, Skips: 0
===============================================

[TestRunner] Starting executor for test Test2 with time out:2147483647 milliseconds.
Inside anotherSampleTest, Current Time: Mon Oct 23 08:26:01 IST 2017, Thread ID: 12, Thread Group Name : main
Inside sampleTest, Current Time: Mon Oct 23 08:26:01 IST 2017, Thread ID: 13, Thread Group Name : main
PASSED: sampleTest
PASSED: anotherSampleTest

===============================================
    Test2
    Tests run: 2, Failures: 0, Skips: 0
===============================================

[TestRunner] Starting executor for test Test3 with time out:2147483647 milliseconds.
Inside anotherSampleTest, Current Time: Mon Oct 23 08:26:11 IST 2017, Thread ID: 14, Thread Group Name : main
Inside sampleTest, Current Time: Mon Oct 23 08:26:11 IST 2017, Thread ID: 15, Thread Group Name : main
PASSED: sampleTest
PASSED: anotherSampleTest

===============================================
    Test3
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Parallel Issue Suite
Total tests run: 6, Failures: 0, Skips: 0
===============================================
```
