### ISSUE TITLE
Invoker.considerExceptions() should call ITestResult.setThrowable(null) if Expected Exception

### ISSUE THREAD

**Issue by nathanila** [cbeust/testng#1882]
### TestNG Version
6.14.3

### Expected behavior
If the exception is expected, then Invoker.considerExceptions() should call ITestResult.setThrowable(null).

### Actual behavior
I have a test suite of 107,905 test cases and 67,938 configurations.  There are 30,063 test cases that throw an expected exception.  Each exception has a call stack.  All of these call stacks end up consuming 86 MB.  It is the #1 consumer of heap space.  #2 consumer of heap space is a distant 30 MB.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Uh... I am not about to share 30,063 test cases that throw exceptions.

### Proposed code change

The code change is very simple.  Here is the code for Invoker.considerExceptions().  I am proposing that 1 line be added.  It is commented with "Add this line".  I am not sure what impact this will have on reporting or other code.

```java
  private StatusHolder considerExceptions(ITestNGMethod tm, ITestResult testresult, ExpectedExceptionsHolder
          exceptionsHolder, FailureContext failure) {
    StatusHolder holder = new StatusHolder();
    holder.status = testresult.getStatus();
    holder.handled = false;

    Throwable ite = testresult.getThrowable();
    if (holder.status == ITestResult.FAILURE && ite != null) {

      //  Invocation caused an exception, see if the method was annotated with @ExpectedException
      if (exceptionsHolder != null) {
        if (exceptionsHolder.isExpectedException(ite)) {
          testresult.setStatus(ITestResult.SUCCESS);
          testresult.setThrowable(null);                                          // Add this line
          holder.status = ITestResult.SUCCESS;
        } else {
          if (isSkipExceptionAndSkip(ite)) {
            holder.status = ITestResult.SKIP;
          } else {
            testresult.setThrowable(exceptionsHolder.wrongException(ite));
            holder.status = ITestResult.FAILURE;
          }
        }
      } else {
        handleException(ite, tm, testresult, failure.count++);
        holder.handled = true;
        holder.status = testresult.getStatus();
      }
    } else if (holder.status != ITestResult.SKIP && exceptionsHolder != null) {
      TestException exception = exceptionsHolder.noException(tm);
      if (exception != null) {
        testresult.setThrowable(exception);
        holder.status = ITestResult.FAILURE;
      }
    }
    return holder;
  }
```

**Comment by nathanila** [comment]
Here is a workaround.  It requires adding TestListener as a TestNG listener.

```
public class TestListener implements ITestListener
{
   @Override
   public void onTestSuccess(@Nullable ITestResult result)
   {
      if (result != null)
         result.setThrowable(null);                                             // Reduce heap usage
   }

   // All other methods do nothing
   ...
}
```

**Comment by krmahadevan** [comment]
@nathanila - Why not raise a Pull Request with the changes ? We will be more than happy to help with the merge

**Comment by nathanila** [comment]
@krmahadevan Please share documentation on how to do a pull request.

**Comment by krmahadevan** [comment]
Please refer here
https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md

-- 

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/

My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by krmahadevan** [comment]
@nathanila - We had to revert the fix since it breaks backward compatibility. Please refer to this comments https://github.com/cbeust/testng/issues/1979#issuecomment-446689103

Since we do have ways of achieving this from within a test project itself, am marking this issue as **Wont fix**
