### ISSUE TITLE
Configurable InvokedMethodListener

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1892]
2 different behaviors are expected for InvokedMethodListener:
* notified by skipped methods
* skipped methods ignored

The behavior could be configurable and/or we should have another InvokedMethodListener.

**Comment by krmahadevan** [comment]
Having another variant of `IInvokedMethodListener` (say for e.g., `StatusAgnosticInvokedMethodListener`) would need code changes from the end-user to get the new behavior and they dont have any way of going back.

I would personally lean towards a configuration driven `IInvokedMethodListener` behavior, which would let the users toggle between both the reasons (for whatever their reasons are). We could perhaps have the default configuration as off, which means `IInvokedMethodListener` never gets executed for any `SKIPPED` methods (be it configuration or test).

Your thoughts @juherr ?

**Comment by krmahadevan** [comment]
This needs to be fixed before `7.0.0` is released so that it fixes all questions related to TestNG listener invocation order.
