### ISSUE TITLE
Emailable test result report colors

### ISSUE THREAD

**Issue by Amr1977** [cbeust/testng#1902]
Colors are so painful in emailable test report.

![image](https://user-images.githubusercontent.com/3415198/44316131-48194f00-a42a-11e8-92de-c58bdeb5e2f0.png)

**Comment by vinoopraj** [comment]
You can customize using implements "IReporter" and add listener to your class or suite

**Comment by Amr1977** [comment]
@vinoopraj Thank you, I will do that inshallah, anyway if default colors were refined I think it would be better.

**Comment by vinoopraj** [comment]
Yes, Better you should re-design all the methods.
