### ISSUE TITLE
How to Implement Retry analyzer in try,catch Block at selenium

### ISSUE THREAD

**Issue by Manish503** [cbeust/testng#1903]
Below is my code after got the exception immediately it should trigger one more time for execution but didn't execute.Without try,catch it was executing but after keep the code in try and catch RetryAnalyzer is not working as expected please anyone help me how to implement RetryAnalyzer in try,catch block

@Test(priority=4,enabled=true,retryAnalyzer=RetryAnalyzer.class)
public void TC_04() throws InterruptedException
{
    try
    {
    extent=new 
    ExtentReports("/Users/anakin/workspace/Reports/MKE.html");
    Login_Objects.Switch_PB2U(driver).click();
    String screenshot_path = Screenshot.createScreenshot(driver);
    String image = log.addScreenCapture(screenshot_path);
    log.log(LogStatus.PASS, "To Stocks",image);
    extent.endTest(log);
    driver.closeApp();
}
catch(Exception e)
{
    String screenshot_path = Screenshot.createScreenshot(driver);
    String image = log.addScreenCapture(screenshot_path);
    log.log(LogStatus.FAIL, "Verify Suggest Stocks ", image);
    extent.endTest(log);
}
}

**Comment by krmahadevan** [comment]
This is not a bug.
This is a question.
You should be posting questions related to TestNG on the google forums for
TestNG : https://groups.google.com/forum/#!forum/testng-users

>
