### ISSUE TITLE
TestNG website down

### ISSUE THREAD

**Issue by ghenadied** [cbeust/testng#1909]
### TestNG Version
6.13.1

### Actual behavior
` [echo] Property 'useSuiteFiles' is set. Will use suite-files which will be replaced for tokens.
  [xmltask] java.io.IOException: Server returned HTTP response code: 503 for URL: http://testng.org/testng-1.0.dtd
  [xmltask] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
  [xmltask] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:646)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1300)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1267)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1164)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
  [xmltask] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
  [xmltask] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
  [xmltask] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
  [xmltask] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  [xmltask] 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
  [xmltask] 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
  [xmltask] 	at com.oopsconsultancy.xmltask.ant.XmlTask.documentFromStream(XmlTask.java:343)
  [xmltask] 	at com.oopsconsultancy.xmltask.ant.XmlTask.documentFromFile(XmlTask.java:387)
  [xmltask] 	at com.oopsconsultancy.xmltask.ant.XmlTask.access$000(XmlTask.java:27)
  [xmltask] 	at com.oopsconsultancy.xmltask.ant.XmlTask$InputFile.getDocument(XmlTask.java:203)
  [xmltask] 	at com.oopsconsultancy.xmltask.ant.XmlTask.execute(XmlTask.java:638)
  [xmltask] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
  [xmltask] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
  [xmltask] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [xmltask] 	at java.lang.reflect.Method.invoke(Method.java:483)
  [xmltask] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
  [xmltask] 	at org.apache.tools.ant.Task.perform(Task.java:348)
  [xmltask] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
  [xmltask] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
  [xmltask] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [xmltask] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  [xmltask] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [xmltask] 	at java.lang.reflect.Method.invoke(Method.java:483)
  [xmltask] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
  [xmltask] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
  [xmltask] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
  [xmltask] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
  [xmltask] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [xmltask] 	at java.lang.reflect.Method.invoke(Method.java:483)
  [xmltask] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
  [xmltask] 	at org.apache.tools.ant.Task.perform(Task.java:348)
  [xmltask] 	at org.apache.tools.ant.Target.execute(Target.java:390)
  [xmltask] 	at org.apache.tools.ant.Target.performTasks(Target.java:411)
  [xmltask] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
  [xmltask] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
  [xmltask] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
  [xmltask] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
  [xmltask] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
  [xmltask] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
  [xmltask] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
  [xmltask] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [xmltask] 	at java.lang.reflect.Method.invoke(Method.java:483)
  [xmltask] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
  [xmltask] 	at org.apache.tools.ant.Task.perform(Task.java:348)
  [xmltask] 	at org.apache.tools.ant.Target.execute(Target.java:390)
  [xmltask] 	at org.apache.tools.ant.Target.performTasks(Target.java:411)
  [xmltask] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
  [xmltask] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
  [xmltask] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
  [xmltask] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
  [xmltask] 	at org.apache.tools.ant.Main.runBuild(Main.java:809)
  [xmltask] 	at org.apache.tools.ant.Main.startAnt(Main.java:217)
  [xmltask] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
  [xmltask] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

`

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@ghenadied - Please try once again. There was a downtime on the site, but now its been taken care of.

**Comment by juherr** [comment]
=> Resolved
