### ISSUE TITLE
[maven]Test are not getting executed when placed under Groups &[TestNG]- -The execution fails to execute Group wise or Class wise 

### ISSUE THREAD

**Issue by VikashGittt** [cbeust/testng#1912]
### TestNG Version : 6.14.3
> Note: only the latest version is supported
How to run the test suite as mentioned in the testng.xml

Setup & Steps Description
A1. There is 1 Suite and 1 Test having 2 test classes in that suite
A2. The 2 Test Classes contain multiple methods(ie.. testcases)[Designed under Page Factory Concept]
These test classes are
- HomepageTest [Used to test Homepage]
- SigninPageTest [Used to test SignIn Page]

A3: On each of these 2 Test pages I have 
A3.1:  Provided Priority to the test cases
A3.2:  Also grouped the testcases

A4. Now I put some groups in the testng.xml under run tag  
A5. Now I am running the test using maven  i.e executing pom.xml (mvn tests)

Test result: [Behaviour = Beh]
Beh1. It runs 1st method of both of these 2 test classes i.e method having Priority = 1
Test result just says Build success with total no. of test executed = 2 however, more than 10  tests exists 
in these test classes combined
For ex: 
Test class Homepage has 10 test methods [Under @test annotation]
and test class SigninPage has 6 test methods [Under @test annotation]
Total test executed = 2 [Priority 1 of both classes] ==> 
Console Message --Build Success--

Question: 
Q1: Why all the test that comes under mentioned group fails to execute. 
Q2: Why it is executing only 1 method of each Class.

==>> Beh2. Test page of 1st Run Method fails to get closed but test page of last run method gets closed. It should close both of these test pages
==>> Beh3. When I remove any of the test class and execute in same way.. it then executes all the methods of the not removed test class
for  ex: 
1. HomapageTest[Read HPT] - removed
2. SigninTest - [Read SIT] not removed
Total test executed = [All Tests under mentioned group]
Message --Build Success--

Summary: When there is only 1 class under ClassesTags then it executes perfectly but If there are 2 classes then it fails to run all methods[Just executes P1 of both methods] 

==>> ==>> [Execute using Only TestNG - Run As TestNG Suit] ===============
3. Now add the Removed test class >> So we have now 2 classes under testng.xml: Execute the same testng.xml by (RtClick testng.xml) and RunAs [TestNG suite]
(Read  P1 = Priority1, P2 = Priority2 )
(HPT = HomapageTest, SIT = SigninTest]

TestResult:  It executes all of the tests from both the test classes whhich come under mentioned group
Note: But the execution order is as mentioned below 

**==>3A**: Executes P1 of HPT > Then executes P1 of SIT> 
**==>3B:** Then executes P2 of HTP > Then executes P2 of SIT and so on ..till end
**==>>3C**: after 1st 5 methods of each test  the stock of SIT finishes (Because only 5 tests of it comes under 

mentioned group) 
[LastStatement] After this the remaining Test of HPT gets executed and Homepage gets closed as per 

coding..but Signin Page fails to get closed

**Question: Q4.** As per 3A and 3B test of both classes are getting executed one after  another. why So?
\I want all test of any Class for ex: HPT to get finished and repalted test page to get closed > 
>>There after only test page for next test should get launched and test execution should take place

**Q5:** As per [LastStatement] of 3C: Why STP doesnt get closed. Similar code written for HPT and it gets closed. Since all methods of SPT gets executed before HTP so it[SPT] sho
uld get closed 1st but it never closes

[HomepageTest.txt](https://github.com/cbeust/testng/files/2342208/HomepageTest.txt)
[SignInTest.txt](https://github.com/cbeust/testng/files/2342216/SignInTest.txt)
[testng.txt](https://github.com/cbeust/testng/files/2342245/testng.txt)

**Comment by krmahadevan** [comment]
@VikashGittt - It is not possible to figure out what is going on without proper sample.

So please do the following 

Create a simple standalone project (Without any dependency on external libraries such as selenium etc.,) which can be executed to reproduce whatever issue you are experiencing. Also I am going to assume you are working with TestNG `6.14.3` (latest released version as of today). If not, please use this version.

**Comment by krmahadevan** [comment]
@VikashGittt - There's nothing in this issue that indicates that there's a bug in TestNG. So you might be better off pursuing your post on Stackoverflow which you [already](
https://stackoverflow.com/questions/52128342/seleniumwebdriver-testng-erratic-behaviour-in-testng-execution-of-multiple-cla) posted.

**Comment by juherr** [comment]
Please, reopen the issue if you can provide more details.
