### ISSUE TITLE
Feature Request: Please change TestNG Report Look and Feel?

### ISSUE THREAD

**Issue by rajikuchana** [cbeust/testng#1919]
### TestNG Version
> 6.14.1

### Expected behavior
It is already years are passed but still TestNG Reports are not ReDesigned/ReModified ,If it is Modified then it is the world best Report ,any one can use.

### Actual behavior
We Require More beautiful TestNG Reports in upcoming TestNG releases,Please consider this as High priority,

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

**Comment by juherr** [comment]
@rajikuchana We prefer to let the community takes part of that. TestNG only provides basic reporters and are enough at the beginning.
If you need more, you can have a look at 3rd party integrations https://github.com/cbeust/testng/wiki/3rd-party-extensions#reporters--loggers, especially dashboards.
