### ISSUE TITLE
Docs: Missing information about exit codes

### ISSUE THREAD

**Issue by dr29bart** [cbeust/testng#1920]
Please, update paragraph 6.2 - [Logging and results](http://testng.org/doc/documentation-main.html#logging) with TestNG exit codes. 

Source info:
https://github.com/cbeust/testng/blob/590120c726086615944dd64221d4051009a781f6/src/main/java/org/testng/internal/ExitCode.java

**Comment by krmahadevan** [comment]
This information is now available on the documentation portal here: https://testng.org/doc/documentation-main.html#testng-exit-codes
