### ISSUE TITLE
Boolean is always false in Assert format(Object, Object, String, boolean), causes confusing assert messages

### ISSUE THREAD

**Issue by jkutil** [cbeust/testng#1921]
Affects 7.0.0-beta1

https://github.com/cbeust/testng/blob/590120c726086615944dd64221d4051009a781f6/src/main/java/org/testng/Assert.java#L845

The boolean parameter equality appears to always be false, leading to some nonsensical/confusing assert messages, such as:
did not expect to find [5.0] but found [0.5]

Whereas in the previous release it would read as:
expected [5.0] but found [0.5]

This is reproducible with a simple snippet:
assertEquals(0.5, 5.0);

**Comment by bluckau** [comment]
Good find, I'm seeing this too.

**Comment by krmahadevan** [comment]
This should be fixed by https://github.com/cbeust/testng/pull/1936
