### ISSUE TITLE
Error when converting JUnit4.4 test class to TestNG

### ISSUE THREAD

**Issue by tfischer4765** [cbeust/testng#194]
When I use the "Convert to TestNG" feature of the Testng Eclipse integration, the following, non-existing import is generated: 

import static org.testng.AssertJUnit.assertThat;

My testng-plugin version is   TestNG    6.4.0.20120226_1704

**Comment by krmahadevan** [comment]
ping @missedone - Nick can you please help take a look at this one and if this is no longer an issue, please help close this.

**Comment by missedone** [comment]
can't reproduce this on recent release 6.12.0.201709050550, @krmahadevan , plese colse this one. thx

**Comment by krmahadevan** [comment]
Closing this issue based on feedback from @missedone
