### ISSUE TITLE
SuiteHTMLReporter breaks order of invoked tests and makes it alphabetical

### ISSUE THREAD

**Issue by sergey-oplavin** [cbeust/testng#1959]
org.testng.reporters.SuiteHTMLReporter method gets the list of invoked methods from ISuite (ISuite.getAllInvokedMethods()) and sorts it in alphabetical order, so further reporters get a list of invoked methods with incorrect order.
To fix that, just need to copy all invoked methods list into a separate list and then use it.
Here is a link to a line in the code which causes the described bug:
https://github.com/cbeust/testng/blob/590120c726086615944dd64221d4051009a781f6/src/main/java/org/testng/reporters/SuiteHTMLReporter.java#L351

**Comment by krmahadevan** [comment]
@sergey-oplavin - Since you have spent time investigating the problem, why not raise a Pull Request to get the issue fixed ?

**Comment by sergey-oplavin** [comment]
@krmahadevan sure, will do that. Just had no time yet - had to spend time implementing workaround in our product.

**Comment by sergey-oplavin** [comment]
I found that this bug was already fixed in org.testng.SuiteRunner by commit: https://github.com/cbeust/testng/pull/1580/commits/b0abb0eb7089bf21fc9c2cb1c506663b94efaef5#diff-d5738f7005af33c3519f8d77156583de (as a part or https://github.com/cbeust/testng/pull/1580)
See:
https://github.com/krmahadevan/testng/blob/b0abb0eb7089bf21fc9c2cb1c506663b94efaef5/src/main/java/org/testng/SuiteRunner.java#L794-L797

This issue can be closed

**Comment by krmahadevan** [comment]
Closing this issue based on the above comments from @sergey-oplavin
