### ISSUE TITLE
ITestListener - Add unimplemeted methods missing in eclipse for

### ISSUE THREAD

**Issue by sen1983** [cbeust/testng#1964]
### TestNG Version - 7.0.0-beta1
> Note: only the latest version is supported

### Expected behavior
When the ITestListener or any other listener gets implemented eclipse should show add unimplemented methods option, when clicked on the option all the methods of the interface should included the class

### Actual behavior
Its not working as expected behavior
![screenshot](https://user-images.githubusercontent.com/45349008/49063814-9d8da500-f23e-11e8-85d0-d673047d12f4.JPG)

### Is the issue reproductible on runner?

- [x] Maven
- [x] Eclipse

### Test case sample
package com.freecrm.ExtentReportListener;
import org.testng.ITestListener;
public class MyListener implements ITestListener{
![image](https://user-images.githubusercontent.com/45349008/49063794-86e74e00-f23e-11e8-9cea-70930bec7df1.png)

}

**Comment by krmahadevan** [comment]
@sen1983 - TestNG 7.0.0 uses JDK8 and with it default methods within interfaces. What this means is that ever listener would now have a default implementation (which doesn't do anything ) for all methods defined within the interface. 

So now you won't see those indications from the IDE. The biggest benefit of default methods in interfaces is that let's say you are implementing an interface that has 10 methods defined in it, you can just implement whatever you need and the rest of the behavior comes via the default methods in the interface.

**Comment by sagaramritkar** [comment]
@krmahadevan - Thank you for the answer, adding more info to it.

When you are not able to add the unimplemented methods, start writing the code but do not add "@override".

**Comment by krmahadevan** [comment]
@sagaramritkar - Not sure what do you mean and what you were trying to explain. Care to explain one more time ?

**Comment by Abhi6692** [comment]
@sagaramritkar Agreed with your statement when I am adding the default method  

[ default void onTestFailure(ITestResult result) {
    // not implemented
  }  ] 
with "@override" it's giving me an error with a quick fix --> "Remove @Override annotation"

@krmahadevan  Please verify

**Comment by pranayKumarPK** [comment]
This issue belongs to TestNG 7.1.0. try to configure TestNG 6.14.3. Issue will not reproduce.

**Comment by prernabhandari2427** [comment]
is this an issue or change ?

**Comment by krmahadevan** [comment]
@prernabhandari2427 - Not sure what you mean by that.

**Comment by SunilGithub1** [comment]
> This issue belongs to TestNG 7.1.0. try to configure TestNG 6.14.3. Issue will not reproduce.

Thanks, it works

**Comment by Gulshanlc** [comment]
@pranayKumarPK 
@SunilGithub1  
Thanks, I changed to TestNG 6,.14.3, and the problem was resolved.
@krmahadevan 
Thanks for explaining reason

**Comment by VishKC** [comment]
Right click on the class --> select source --> choose override/implement methods --> then pick the methods you'd like to implement.

![image](https://github.com/testng-team/testng/assets/130653964/16e92fa8-0ddd-445f-8af9-95c7e14c213e)

**Comment by pradnesha** [comment]
Use IntelliJ’s Quick Fix / Generate
Put your cursor inside the class and do one of the following:

Press Command + N (Mac) / Alt + Insert (Windows/Linux) → select Implement Methods

Or right-click → Generate → Implement Methods

Then select all methods of ITestListener to override
