### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.MF

### ISSUE THREAD

**Issue by cowwoc** [cbeust/testng#1988]
This issue is related to but is not a duplicate of https://github.com/cbeust/testng/issues/1808.

One day you will transition Java 9...

Until that day, please add a `Automatic-Module-Name` entry to `MANIFEST.MF` to improve the life of people who have made the move and would like to continue depending on your library. See http://branchandbound.net/blog/java/2017/12/automatic-module-name/ for background information.

Thank you.

**Comment by krmahadevan** [comment]
@cowwoc - Any inputs on this : 
https://github.com/cbeust/testng/pull/1989#issuecomment-449903615
