### ISSUE TITLE
TestNG 7.0.0-beta2 is missing SkipException class

### ISSUE THREAD

**Issue by baflQA** [cbeust/testng#2002]
### TestNG Version
testNG 7.0.0-beta2
### Expected behavior
Hi. I've just bumped the TestNG maven dependency in my POM file to the beta2. 
When trying to compile my project, I get an exception, that the SkipException class can not be resolved. I can not find this class in the file tree too. 
<img width="430" alt="zrzut ekranu 2019-01-7 o 10 44 43" src="https://user-images.githubusercontent.com/27357499/50760884-4f21ec00-1269-11e9-8656-db55836647ea.png">

### Actual behavior
Skip exception class is not present in the jar available in the Maven repository.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Comment by cbeust** [comment]
Fixed in 7.0.0-beta3, now deployed on Maven Central:

https://search.maven.org/artifact/org.testng/testng/7.0.0-beta3/jar

**Comment by baflQA** [comment]
Hi. Confirmed, thx for the quick reaction!
