### ISSUE TITLE
TestNG 7.0.0-beta2 is missing Reporter class

### ISSUE THREAD

**Issue by mfuzalam** [cbeust/testng#2004]
### TestNG Version
TestNG 7.0.0-beta2

### Expected behavior
I updated TestNG version to 7.0.0-beta2 and getting a compile error that SkipException and Reporter classes are missing. Since there is already a report that SkipException class missing, I'm opening this for the latter. 

![screen shot 2019-01-07 at 9 11 36 am](https://user-images.githubusercontent.com/19399156/50782254-5db5d680-125c-11e9-97ac-c080ddc9e05b.png)

### Actual behavior
Reporter class is not present in the jar available in the Maven repository.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Comment by krmahadevan** [comment]
Issue is similar to https://github.com/cbeust/testng/issues/2002

This is now taken care of, as part of TestNG `7.0.0-beta3`

Please retry and report back if this is still a problem using the newer version.

**Comment by mfuzalam** [comment]
Hi @krmahadevan, just checked it works. But I noticed "IRetryAnalyzer getRetryAnalyzer();" has been deprecated in ITestAnnotation. What is the substitution for it?

**Comment by krmahadevan** [comment]
@mfuzalam - As explained in the [javadocs](http://static.javadoc.io/org.testng/testng/7.0.0-beta3/org/testng/annotations/ITestAnnotation.html#getRetryAnalyzer--) please make use of [getRetryAnalyzerClass()](http://static.javadoc.io/org.testng/testng/7.0.0-beta3/org/testng/annotations/ITestAnnotation.html#getRetryAnalyzerClass--)
