### ISSUE TITLE
Test Methods which are using DependsOnMethods not executing as part of same class

### ISSUE THREAD

**Issue by qtpsudhakar** [cbeust/testng#2015]
### TestNG Version 6.14.3
> Note: only the latest version is supported

### Expected behavior
The Test methods which are using DependsOnMethods methods should be executed as part of the same class.

### Actual behavior
The test methods with @dependsonmethods executed after dependent methods. But when executing multiple classes using TestNG XML file, the Test methods which are using DependsOnMethods are executed as final set after executing all test methods from all classes instead of executing as part of respective class. Is this how it works when executing through XML file??

- [x] Maven

**Comment by krmahadevan** [comment]
The latest released version of TestNG is `7.0.0-beta3`. Please retry using that. If this is still a problem, please help share a sample that can be used to reproduce the issue.

**Comment by egovedarov** [comment]
Hello @krmahadevan and @qtpsudhakar,
I tried to reproduce the issue with the latest TestNG version 7.0..0-beta3, but was not able to. I also was not able to reproduce the issue with 6.14.3. My sample was:
`public class testClass1 {
	
	@Test
	public void Test11() {
		System.out.println("Class 1 test 11");
	}
	
	@Test(dependsOnMethods = "Test11")
	public void Test12() {
		System.out.println("Class 1 test 12");
	}
	
	@Test
	public void Test13() {
		System.out.println("Class 1 test 13");
	}
	
	@Test(dependsOnMethods = "Test13")
	public void Test14() {
		System.out.println("Class 1 test 14");
	}

}`

`public class testClass2 {

	@Test
	public void Test21() {
		System.out.println("Class 2 test 21");
	}
	
	@Test
	public void Test22() {
		System.out.println("Class 2 test 22");
	}
	
	@Test(dependsOnMethods = "Test22")
	public void Test23() {
		System.out.println("Class 2 test 23");
	}
	
	@Test(dependsOnMethods = "Test21")
	public void Test24() {
		System.out.println("Class 2 test 24");
	}
}`

testng.xml:
`<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
  
<suite name="Suite1" verbose="1" >
  <test name="Nopackage" >
     <classes>
            <class name="testClass1"/>
            <class name="testClass2"/>
        </classes>
  </test>
</suite>`

I was able to reproduce the issue by adding priority=1 to a test that had dependsOnMethods. I think that is the problem comes when both priority and dependsOnMethods are used. The issue seems familiar to #1616 .

**Comment by anuragdeshpande** [comment]
I have the same issue too, please find an example below.

Overview of the setup. suite is set to run "classes" in parallel. which according to the documentation, should run each class in its own thread and all methods in that class in the same thread.

This is true only if the @Test annotation is not passed with any options.
The following class, all test methods will run in the same thread
`public class TestClass {


    @Test
    public void test1(){
        System.out.println("In Test 1 - Thread ID: "+Thread.currentThread().getId());
    }

    @Test
    public void test2(){
        System.out.println("In Test 2 - Thread ID: "+Thread.currentThread().getId());
    }

    @Test
    public void test3(){
        System.out.println("In Test 3 - Thread ID: "+Thread.currentThread().getId());
    }
}`


`output:
In Test 1 - Thread ID: 29
In Test 2 - Thread ID: 29
In Test 3 - Thread ID: 29
In Test 4 - Thread ID: 29
In Test 5 - Thread ID: 29
`


but, if there is any other option passed in the test (I have tested this for "priority", "dependsOnMethods" options only) the tests are not in the same thread. Consider modified class for the above mentioned version

`public class TestClass {


    @Test
    public void test1(){
        System.out.println("In Test 1 - Thread ID: "+Thread.currentThread().getId());
    }

    @Test(dependsOnMethods = "test1")
    public void test2(){
        System.out.println("In Test 2 - Thread ID: "+Thread.currentThread().getId());
    }

    @Test(dependsOnMethods = "test2")
    public void test3(){
        System.out.println("In Test 3 - Thread ID: "+Thread.currentThread().getId());
    }

    @Test(dependsOnMethods = "test3")
    public void test4(){
        System.out.println("In Test 4 - Thread ID: "+Thread.currentThread().getId());
    }

    @Test(dependsOnMethods = "test4")
    public void test5(){
        System.out.println("In Test 5 - Thread ID: "+Thread.currentThread().getId());
    }

}`

it results in something like below

`In Test 1 - Thread ID: 29
In Test 2 - Thread ID: 37
In Test 3 - Thread ID: 41
In Test 4 - Thread ID: 46
In Test 5 - Thread ID: 50
`

Below is the testng.xml file used.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Regression Regression" parallel="classes">
  <listeners>
    <listener class-name="framework.Listener"/>
  </listeners>
  <test thread-count="5" name="Regression" parallel="classes">
    <groups>
      <run>
        <exclude name="ClockMove"/>
      </run>
    </groups>
    <classes>
      <class name="TestClass"/>
    </classes>
  </test> 
</suite> 
`

hope this gives you sufficient example data for the issue.

Summary: when there is an option passed to @Test annotation. parallel = "classes" option is running each method in a class in its own thread.

**Comment by krmahadevan** [comment]
Anurag what version are you using ? The latest released version right now is `7.0.0-beta3`

**Comment by anuragdeshpande** [comment]
I have used 7.0.0-beta3 for the example above. But I have also tried all the release versions all the way until 6.13

**Comment by krmahadevan** [comment]
@anuragdeshpande - TestNG by design would split the test method execution into two parts (when it sees an ordering such as `dependsOnMethods`). 
In your example every method depends on the other, so you basically have created something like a dependency tree. In those conditions TestNG doesn't enforce thread affinity.

If you would like TestNG to always execute dependent test methods in the same thread, please make use of the JVM argument `-Dtestng.thread.affinity=true`. This will force TestNG to start enforcing thread affinity and as such the dependent methods would run in the same thread as their parent.

Here's an example that demonstrates this in action using TestNG `7.0.0-beta3`

```java
import org.testng.annotations.Test;

public class TestClass {
  @Test
  public void test1() {
    System.out.println("In Test 1 - Thread ID: " + Thread.currentThread().getId());
  }

  @Test(dependsOnMethods = "test1")
  public void test2() {
    System.out.println("In Test 2 - Thread ID: " + Thread.currentThread().getId());
  }

  @Test(dependsOnMethods = "test2")
  public void test3() {
    System.out.println("In Test 3 - Thread ID: " + Thread.currentThread().getId());
  }

  @Test(dependsOnMethods = "test3")
  public void test4() {
    System.out.println("In Test 4 - Thread ID: " + Thread.currentThread().getId());
  }

  @Test(dependsOnMethods = "test4")
  public void test5() {
    System.out.println("In Test 5 - Thread ID: " + Thread.currentThread().getId());
  }
}
```

```java
import java.util.Collections;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlSuite.ParallelMode;
import org.testng.xml.XmlTest;

public class IssueTest {

  @Test
  public void testMethod() {
    System.setProperty("testng.thread.affinity", Boolean.TRUE.toString());
    TestNG testng = new TestNG();
    testng.setXmlSuites(Collections.singletonList(suite()));
    testng.setVerbose(2);
    testng.run();
  }

  private XmlSuite suite() {
    XmlSuite suite = new XmlSuite();
    suite.setParallel(ParallelMode.CLASSES);
    suite.setName("sample_suite");
    xmlTest(suite);
    System.err.println(suite.toXml());
    return suite;
  }

  private void xmlTest(XmlSuite suite) {
    XmlTest xmlTest = new XmlTest(suite);
    xmlTest.setName("sample_test");
    xmlTest.setClasses(Collections.singletonList(xmlClass()));
  }

  private XmlClass xmlClass() {
    return new XmlClass(TestClass.class, true);
  }
}

```

**Execution output**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="sample_suite" parallel="classes">
  <test thread-count="5" name="sample_test" parallel="classes">
    <classes>
      <class name="com.rationaleemotions.github.issue2015.TestClass"/>
    </classes>
  </test> <!-- sample_test -->
</suite> <!-- sample_suite -->

In Test 1 - Thread ID: 11
In Test 2 - Thread ID: 11
In Test 3 - Thread ID: 11
In Test 4 - Thread ID: 11
In Test 5 - Thread ID: 11
PASSED: test1
PASSED: test2
PASSED: test3
PASSED: test4
PASSED: test5

===============================================
    sample_test
    Tests run: 5, Failures: 0, Skips: 0
===============================================


===============================================
sample_suite
Total tests run: 5, Passes: 5, Failures: 0, Skips: 0
===============================================


===============================================
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```
