### ISSUE TITLE
Arquillian tests not covered by JaCoCo

### ISSUE THREAD

**Issue by james-r-smith** [cbeust/testng#2016]
### Overview

I have been stumped recently as to why my JaCoCo code coverage wasn't working. It worked in JUnit, but not for TestNG. With the help of the JaCoCo dev's ([here](https://github.com/jacoco/jacoco/issues/841)), it seems to be that TestNG needs to be added into the Arquillian container. Is there a way to avoid the additional configuration on the user-side, like in JUnit? Looking for opinions and perhaps other solutions to what seems like a bug. Thanks!

### TestNG Version

6.14.3

### Expected behavior

JaCoCo code coverage should be working inside Arquillian container.

### Actual behavior

JaCoCo code coverage is not captured until adding it into the Arquillian container.

### Test case sample

Zip files and modifications provided [here](https://github.com/jacoco/jacoco/issues/841) show the bug within TestNG, and the workaround solution.

**Comment by krmahadevan** [comment]
TestNG has nothing to do with arquillian containers   we don't maintain that codebase either. You might want to ideally speaking take it up with the arquillian project.
