### ISSUE TITLE
Guice module parent injector conflicts with maven surefire parallelism

### ISSUE THREAD

**Issue by josephlbarnett** [cbeust/testng#2017]
### TestNG Version
6.14.3

### Expected behavior
Tests that pass when run alone pass when run all together in parallel

### Actual behavior
Sometimes, we get `A just-in-time binding to [XYZ] was already configured on a parent injector.` when running our tests in CI with maven surefire parallelism set to 10.  When running with a forked executor for each test, our tests pass every time, but would like to move to single fork w/ parallelism instead.  At one point, was seeing one test depending on a module that implicitly bound an XYZ via constructor conflicting with another test that depended on a module that explicitly bound an XYZ to a given instance, but the exception was happening every time the tests ran, both in CI and locally via IDEA or maven.  Now, maybe one of 5 CI runs sees a similar issue, but not seeing it locally in either IDEA or maven.

It seems like somehow some tests are binding things that get set up in a parent injector that is shared by all tests, versus each test binding things only in its own child injector?

### Is the issue reproducible on runner?

- [X] Maven (sometimes)

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Don't currently have a minimal test case for this, but can try to set one up.

**Comment by krmahadevan** [comment]
@josephlbarnett - Can you please try reproducing this issue using TestNG `7.0.0-beta3` ? If its reproducible, please help share a sample.

**Comment by josephlbarnett** [comment]
@krmahadevan : https://github.com/josephlbarnett/test-inject/tree/guice-inject-fail demonstrates the failure I'm seeing with every maven build.  Not entirely sure why I'm seeing sporadic failures on a modified non-trivial private project.

Seems the issue is that default/just-in-time/implicit bindings are being set in the parent injector that is shared between tests?

If I change the test `runOrder` to `reversealphabetical` so that `SecondModuleTest` runs first, or set `forkCount` higher than the default of 1 to give each test its own VM, it passes.  It would also pass to make sure that `FirstModuleTest` loads a module that binds a `MetricsRegistry` explicitly, but in a non-trivial project it's not always easy to find which test/module combination is creating the just-in-time binding (which is what I've tried in the private project, but now getting sporadic failures).

**Comment by josephlbarnett** [comment]
ok, so looking at `Injector.createChildInjector` javadocs, the just-it-time binding being set on the parent injector is expected behavior.  What is gained by sharing the parent injector with all tests in the suite?  Would it be possible to disable that behavior and use a separate injector for every test (at least optionally)?

**Comment by josephlbarnett** [comment]
Attached PR uses a new independent injector for each test, which fixes the problem in the sample, but currently fails tests.

**Comment by josephlbarnett** [comment]
ok tests passing now by ensuring that the independent injectors have the parent module installed if it exists.
