### ISSUE TITLE
Wrong arg count -parameterless test and conf method declaring Object[]

### ISSUE THREAD

**Issue by stumbav** [cbeust/testng#202]
In the scenario where a configuration method declares Objec[] type parameter and 
is run for a parameterless test method, a superfluous (empty string) parameter is
added into the configuration method invocation, thus yielding IllegalArgumentException:

```
 @BeforeMethod setUp(@BeforeMethod setUp: 
    Wrong number of arguments were passed by the Data Provider: found 3 but expected 2)
```

Switching the configuration method parameters order didn't do the trick (similar issue - #128)

The following test clarifies the problem (run from Eclipse plugin:  6.4.0.20120308_1617 ):

```
@Test
public class TestNG_confMethodParamsBugTest {

    @BeforeMethod
    public void setUp(Object[] params, Method method) {}

    @Test(dataProvider="param")
    public void testMethod1_ok(String param) {}

    public void testMethod2_bug() {}

    @DataProvider(name="param")
    public Object[][] getParam() {
        return new Object[][]{{"Kuk"}};
    }
}   
```

**Comment by juherr** [comment]
Closed because we are not able to reproduce it.
Check comments from #1445 by @krmahadevan
