### ISSUE TITLE
Wrong test running with priority set

### ISSUE THREAD

**Issue by enivid** [cbeust/testng#2020]
With testng v7 beta 3, I set one of my tests to have a priority. Then I ran my testng suite file and it ran a test in that class where I set the priority but not the correct test. It looks like it ran the first tests in the class sorted alphabetically.

**Comment by juherr** [comment]
Could you share a sample?

**Comment by krmahadevan** [comment]
No update from the user. Closing this issue. If this is still a problem with the latest testng version, please share a sample here and we can have this issue re-opened.
