### ISSUE TITLE
Suite.xml files make web request when suite uses DTD over HTTPS

### ISSUE THREAD

**Issue by JLLeitschuh** [cbeust/testng#2022]
### TestNG Version
Looking at the source code on `master`

### Expected behavior

Regardless of the `Suite.xml` declarations, none of these cases should cause TestNG to make a network request to load the DTD.

```xml
<!DOCTYPE suite SYSTEM "http://beust.com/testng/testng-1.0.dtd" >
<suite name="My Test Suite"/>
```

```xml
<!DOCTYPE suite SYSTEM "https://beust.com/testng/testng-1.0.dtd" >
<suite name="My Test Suite"/>
```

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="My Test Suite"/>
```

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="My Test Suite"/>
```

### Actual behavior

The following two `Suite.xml` files cause TestNG to make HTTPS get a request to the server. This prevents TestNG from being able to execute in an offline mode. 

```xml
<!DOCTYPE suite SYSTEM "https://beust.com/testng/testng-1.0.dtd" >
<suite name="My Test Suite"/>
```

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="My Test Suite"/>
```

### Source Locations

https://github.com/cbeust/testng/blob/79c4d27b42463ac0d29020e2a4f89be66254e7a8/src/main/java/org/testng/xml/Parser.java#L22-L28
https://github.com/cbeust/testng/blob/79c4d27b42463ac0d29020e2a4f89be66254e7a8/src/main/java/org/testng/xml/TestNGContentHandler.java#L90-L117

### Why use HTTPS

Although when TestNG's suite XML parser parses the XML it loads the DTD using the one internally in the JAR, other tools like XML formatters or validators don't have that resource to pull from. By loading the TestNG DTD over HTTP, it opens those tools to an XXE vulnerability via a MITM.

https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

### Further Suggestions

I advise that TestNG disable the loading of XML entities entirely (or make it so that it only supports the one trusted DTD by default). It might make sense to add support for a user option to enable XXE processing for specific use cases.

**Comment by sjoshid** [comment]
Im having issues with using Testng with Spring. 
```
@ContextConfiguration(locations = { "classpath:location1.xml", "classpath:location2"})
public class SpringTestngTest extends AbstractTestNGSpringContextTests
{
	@Autowired
	public SpringBean bean;
	
	@DataProvider(name = "data-provider")
	public Object[][] dpMethod()
	{
		return new Object[][] { { 2, 3, 5 }, { 5, 7, 9 } };
	}
	
	@Test(dataProvider = "data-provider")
	public void myTest(int a, int b, int result)
	{
		int sum = a + b;
		Assert.assertEquals(result, sum);
		Assert.assertNotNull(bean);
	}
}
```

Im getting `java.net.ConnectException: Connection timed out: connect`. 
This means it still tries to connect to the internet.

Spring version: 5.0.8.RELEASE
Testng version: 7.3.0

I would be happy to provide more details if needed.

Thanks.

**Comment by JLLeitschuh** [comment]
@sjoshid I'm guessing that's a bug/vulnerability in the spring TestNG stuff, not TestNG proper.

**Comment by sjoshid** [comment]
True. Let me try to downgrade Testng.

**Comment by sjoshid** [comment]
Aaahha. It does work with 7.1.0. 
Looks like a bug in 7.3.0 for sure.

**Comment by askfor** [comment]
> @sjoshid I'm guessing that's a bug/vulnerability in the spring TestNG stuff, not TestNG proper.

Now in 7.3.0 the following xml will cause TestNG to make a call to the server when -Dtestng.dtd.http=true is specified,  then users won't be able to run test offline in intellij ( intelllij create a xml with "http://testng.org/testng-1.0.dtd" on the fly). Is this a bug?

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

**Comment by robbytx** [comment]
https://github.com/cbeust/testng/blob/2a2e11b/src/main/java/org/testng/xml/Parser.java#L33 seems like it is incorrectly specifying `https`, so it's exactly the same as the `HTTPS_TESTNG_DTD_URL` variable on the next line, and therefore the `http` version of the DTD url is unrecognized.

This variable was changed (and therefore I think the behavior was regressed) in https://github.com/cbeust/testng/commit/33e600fd1d2d0c6783272ff45266a02999a05a4a#diff-9ca66a84545cd97fc9ceac35fe5494a5c5e1a1eb0a08aaa7abdf2a5ca7eedd24.

**Comment by robbytx** [comment]
In case it's not clear: I've filed https://github.com/cbeust/testng/issues/2022 to document the current issue with the `http://testng.org/testng-1.0.dtd` URL in 7.3.0, which I believe was first mentioned by @sjoshid above on Aug 4.
