### ISSUE TITLE
Question about good way to use beforeClass on parallel='methods'

### ISSUE THREAD

**Issue by selenUser** [cbeust/testng#2024]
I have a @BeforeClass that is a setup, and running tests in parallel='methods'.
should i get my @BeforeClass on each separate thread ? (each test got separate thread)

Thanks

**Comment by krmahadevan** [comment]
@selenUser - `@BeforeClass` is executed only **ONCE** per test class. So if you need a setup to be done only once per test class, before all test methods run in it, then you can use `@BeforeClass`.

If you need your setup to be executed before every `@Test` method, then you should be using `@BeforeMethod`.

Closing this issue with resolution as *question answered*
