### ISSUE TITLE
Getting Error Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process

### ISSUE THREAD

**Issue by ashish081991** [cbeust/testng#2027]
### TestNG Version : 6.9.9 / 6.14.3
> Note: only the latest version is supported

### Actual behavior
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project WanderlyScenarios: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException:
[ERROR] Cannot find class in classpath: com.scenarios.Wanderly_ApplyJob_Scenario
[ERROR]         at org.testng.xml.XmlClass.loadClass(XmlClass.java:77)
[ERROR]         at org.testng.xml.XmlClass.init(XmlClass.java:69)
[ERROR]         at org.testng.xml.XmlClass.<init>(XmlClass.java:55)
[ERROR]         at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:575)
[ERROR]         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
[ERROR]         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
[ERROR]         at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
[ERROR]         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
[ERROR]         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
[ERROR]         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
[ERROR]         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[ERROR]         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
[ERROR]         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
[ERROR]         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
[ERROR]         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
[ERROR]         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
[ERROR]         at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
[ERROR]         at org.testng.xml.XMLParser.parse(XMLParser.java:38)
[ERROR]         at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
[ERROR]         at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
[ERROR]         at org.testng.xml.Parser.parse(Parser.java:152)
[ERROR]         at org.testng.xml.Parser.parse(Parser.java:233)
[ERROR]         at org.testng.TestNG.parseSuite(TestNG.java:295)
[ERROR]         at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
[ERROR]         at org.testng.TestNG.initializeEverything(TestNG.java:995)
[ERROR]         at org.testng.TestNG.run(TestNG.java:1009)
[ERROR]         at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
[ERROR]         at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR]         at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR]         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

### Is the issue reproductible on runner?

- [ ] Shell
- [yes ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
Have you tried fixing the error of TestNG not being able to find the class in your class path for `com.scenarios.Wanderly_ApplyJob_Scenario` by checking if the class name is correct ?

**Comment by ashish081991** [comment]
While running with Eclipse, my suit is running properly and getting passed [perform both run as maven test & run as testng suite]

But, while running the same suit from command prompt I am getting the above errors.[tried the 
mvn compile test / mvn clean compile test]

**Comment by ashish081991** [comment]
Hi Krishnan,

That issue got resolved.

Root cause of that issue was : 'src' folder structure.
My folder structure was 'src/com. Scenarios. Wanderly...'
This works inside eclipse but when we invoke code from cmd or externally. It wont work

I changed folder structure to
'src/test/java/com. Scenarios.wanderly...'
This is default maven folder structure.
Which works from both inside eclipse and cmd.

In old structure maven not able identify its default path to find the classes.

Thanks & Regards
Ashish Mishra
+91 8600942510
________________________________

**Comment by chandru226** [comment]
any one knows, is this issue solved?, since am getting this issue now.. i couldn't able to fix this. Could you please provide us any soltions. Thanks

**Comment by krmahadevan** [comment]
@chandru226 - This is not an issue to begin with. So there is nothing that needs to be done to fix this.
You need to look at the stack trace of your failure to figure out what is causing the problem.
