### ISSUE TITLE
how i can perform parallel test

### ISSUE THREAD

**Issue by Amrkamel1** [cbeust/testng#2039]
how i can perform parallel test, i have managed to run test on multiple devices but one after another

`
package src.mobile.AppiumTest;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;

public class ParallelExecutionTest implements multi {
    private static AndroidDriver<MobileElement> driver;

    @Parameters({ "deviceName_","UDID_","platformVersion_", "URL_" })
    @BeforeMethod
    public void beforeMethod(String deviceName_,String UDID_,String platformVersion_,String URL_) throws MalformedURLException, InterruptedException {

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", deviceName_);
        capabilities.setCapability("udid", UDID_);
        capabilities.setCapability("platformVersion", platformVersion_);
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.sec.android.app.music");
        capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".common.activity.MusicMainActivity");
        driver = new AndroidDriver<MobileElement>(new URL("http://"+URL_), capabilities);
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);

        Thread.sleep(10000);
    }

    @Override
    @Test
    public void f() {
        // driver.findElement(By.id("com.sec.android.app.music:id/menu_launch_search")).click();
        driver.findElementById("com.sec.android.app.music:id/menu_launch_search").click();

        // driver.findElementById("android:id/search_src_text").click();
        driver.manage().timeouts().implicitlyWait(4, TimeUnit.SECONDS);
        //driver.findElement(By.id("android:id/search_src_text")).sendKeys("hateer");

        driver.findElementById("android:id/search_src_text").sendKeys("hateer");
        driver.findElementById("com.sec.android.app.music:id/text_layout").click();
    }

    @AfterMethod
    public void afterMethod() {
    }

}
`

**Comment by Amrkamel1** [comment]
and this is my testNG.xml

`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default Suite">
    <test name="Mobile1">
        <parameter name="deviceName_" value="Galaxy Note5"/>
        <parameter name="UDID_" value="0715f75124ea0934"/>
        <parameter name="platformVersion_" value="7.0"/>
        <parameter name="URL_" value="127.0.0.1:4723/wd/hub"/>
        <classes>
            <class name="src.mobile.AppiumTest.ParallelExecutionTest"/>
        </classes>
    </test> 
    <test name="Mobile2">
        <parameter name="deviceName_" value="Galaxy Note8"/>
        <parameter name="UDID_" value="988a1641434e36333130"/>
        <parameter name="platformVersion_" value="9"/>
        <parameter name="URL_" value="127.0.0.1:5000/wd/hub"/>
        <classes>
            <class name="src.mobile.AppiumTest.ParallelExecutionTest"/>
        </classes>
    </test> 
</suite> 

`

**Comment by krmahadevan** [comment]
Please post questions on the TestNG Google forums instead of filing them as issues. 

URL : https://groups.google.com/group/testng-users
