### ISSUE TITLE
Broken DTD as of today

### ISSUE THREAD

**Issue by ghenadied** [cbeust/testng#2048]
### TestNG Version

6.13.1

### Actual behavior
Runing testng from ANT gives following error, starting today. Exactly, the xmlproperty ant task fails when trying to load the testng xml file.

[xmlproperty] [Fatal Error] testng-1.0.dtd:1:3: The markup declarations contained or pointed to by the document type declaration must be well-formed.

Removing DTD file reference from suite.xml solved the problem but now IDE doesn't know to offer suggestions.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [X ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
suite.xml contains:
`<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">`

**Comment by daroshchanka** [comment]
I have the same issue starting from today.
I use `groovy.util.XmlParser`.

```
org.xml.sax.SAXParseException; systemId: http://testng.org/testng-1.0.dtd; lineNumber: 1; columnNumber: 3; The markup declarations contained or pointed to by the document type declaration must be well-formed.

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at groovy.util.XmlParser.parse(XmlParser.java:250)
	at groovy.util.XmlParser.parseText(XmlParser.java:283)
```

**Comment by cbeust** [comment]
I recently updated links to https, wonder if it might be related...

-- 
Cédric

**Comment by cbeust** [comment]
Looks like the resolver is not honoring 301 redirects?

**Comment by cbeust** [comment]
Looks like a bug from `groovy.util.XmlParser`. It tries to resolve the DTD on its own but without following redirects.

**Comment by JLLeitschuh** [comment]
@daroshchanka @ghenadied 

Just a heads up, given that you were experiencing this issue, this indicates that your code was vulnerable to a Man-In-The-Middle (MITM) based XXE attack against whatever logic was parsing TestNG.

https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

If this exception occurred in production code, you probably had a security vulnerability.

**Comment by daroshchanka** [comment]
Read about issues with dtd redirects for java xml parser.
https://github.com/cbeust/testng/issues/1385#issuecomment-286454350

Switch to https works fine.

**Comment by wilx** [comment]
I am seeing issue related to this one. I have replaced `http` with `https` but I get different error. Now it complains that it cannot find valid certification path:

    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I think the issue is that your server does not send intermediate certificates. This is detected by SSL Test: <https://www.ssllabs.com/ssltest/analyze.html?d=testng.org>

**Comment by JLLeitschuh** [comment]
If this is implemented correctly, you should never be making HTTP or HTTPS requests from the XML parser. What is the contents of your suite XML file?

**Comment by wilx** [comment]
@JLLeitschuh We have additional information in XML comments, so it might be that we are instantiating the XML parser once more to get the comments. But in any case the SSL test shows some issues.
