### ISSUE TITLE
It's not possible to register a new ITestListener at the runtime

### ISSUE THREAD

**Issue by baflQA** [cbeust/testng#2055]
### TestNG Version
TestNg 7.0.0-beta5
### Expected behavior
ITestListener implementation added on suite start will be registered and executed.

### Actual behavior
A listener is not added to the list of the listeners.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
In the super test class,  ITestListener implementation is added to the set of the listeners https://github.com/baflQA/testNG_parallel_debug/blob/b94df072e0749f52e6ed318754d04f2b52ddf556/src/test/java/testngparallel/MasterTestClass.java#L22

When executing this test https://github.com/baflQA/testNG_parallel_debug/blob/b94df072e0749f52e6ed318754d04f2b52ddf556/src/test/java/testngparallel/Class1.java
the registered listener should be invoked.

It won't be invoked, because it's not really registered there: https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/SuiteRunner.java#L454

**Comment by baflQA** [comment]
Hi there! @krmahadevan @juherr @cbeust any plans to release this fix? The official maven repo is stuck on 7.0.0-beta4, which is unusable, so 7.0.0-beta3 is the current release as for now.
Would be nice to get something newer in the central repository.

**Comment by krmahadevan** [comment]
@baflQA `7.0.0-beta5` is already published to Bintray. You could try it today. But unfortunately its not been synced to Maven central.
