### ISSUE TITLE
IExecutionListener multiple runs

### ISSUE THREAD

**Issue by orenbigel** [cbeust/testng#2057]
### TestNG Version
6.10

### Expected behavior
onExecutionStart and onExecutionFinish should only run once per a TestNG run

### Actual behavior
onExecutionStart and onExecutionFinish run per suite tag in xml

### Is the issue reproductible on runner?
Yes

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
1) IExecutionListener class:
public class TestRunExecutioner2 implements IExecutionListener {

    @Override
    public void onExecutionStart() {
        System.out.println("TESTNG starts");
    }

    @Override
    public void onExecutionFinish() {
        System.out.println("TESTNG ends");
    }
}

2) Test class:
ContextConfiguration(classes = TestConfig.class)
@Listeners({TestRunExecutioner2.class})
public class BaseTeridionTest extends AbstractTestNGSpringContextTests {
....}

3) Suites xml (each inner suite is with several tests):
<suite name="fullSystem" parallel="tests" thread-count="20" verbose="1">
    <suite-files>
        <suite-file path="oren.xml"/>
        <suite-file path="oren2.xml"/>
    </suite-files>
</suite>

4) TestNG run via Maven/intellij:
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
log4j:WARN No appenders could be found for logger (com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl).
log4j:WARN Please initialize the log4j system properly.
TESTNG starts
TESTNG starts
TESTNG starts
[INFO] - [2019-04-16T12:35:04.723Z] - [oren2]: Suite started
[INFO] - [2019-04-16T12:35:04.723Z] - [oren]: Suite started
Apr 16, 2019 12:35:05 PM com.google.api.client.googleapis.services.AbstractGoogleClient <init>
WARNING: Application name is not set. Call Builder#setApplicationName.
[INFO] - [2019-04-16T12:35:06.992Z] - [t3a]: Test started
[INFO] - [2019-04-16T12:35:07.007Z] - [t2a]: Test started
[INFO] - [2019-04-16T12:35:07.013Z] - [t1a]: Test started
test3a
[INFO] - [2019-04-16T12:35:07.760Z] - [t3a]: Test completed successfully!
[INFO] - [2019-04-16T12:35:08.137Z] - [oren2]: Suite finished
test2a
[INFO] - [2019-04-16T12:35:08.337Z] - [t2a]: Test completed successfully!
[INFO] - [2019-04-16T12:35:08.696Z] - [t2b]: Test started
test2b
[INFO] - [2019-04-16T12:35:09.121Z] - [t2b]: Test completed successfully!
test1a
[INFO] - [2019-04-16T12:35:09.430Z] - [t1a]: Test completed successfully!
[INFO] - [2019-04-16T12:35:09.971Z] - [t1b]: Test started
test1b
[INFO] - [2019-04-16T12:35:12.405Z] - [t1b]: Test completed successfully!
[INFO] - [2019-04-16T12:35:12.756Z] - [t1c]: Test started
test1c
[INFO] - [2019-04-16T12:35:15.181Z] - [t1c]: Test completed successfully!
[INFO] - [2019-04-16T12:35:15.550Z] - [oren]: Suite finished
TESTNG ends
TESTNG ends
TESTNG ends
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.058 sec - in TestSuite

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

--->
"TESTNG starts" and "TESTNG ends" strings are printed 3 times while should be a single print

**Comment by krmahadevan** [comment]
Latest released version of TestNG is `7.0.0-brta5`. Please retry using that and post back your results

**Comment by orenbigel** [comment]
Works on 7.0.0-beta6
