### ISSUE TITLE
Log messages in reporter are hard to understand in some cases

### ISSUE THREAD

**Issue by Gotusso** [cbeust/testng#206]
In some cases the log messages aren't as useful as they were before the new reports.
Let's suppose we have the following snippet:

``` java
public class BarTest {
    @Factory()
    public static Object[] createTests() {
        final ArrayList<BarTest> tests = new ArrayList<BarTest>();

        tests.add(new BarTest("A", 1));
        tests.add(new BarTest("B", 2));
        tests.add(new BarTest("C", 3));
        tests.add(new BarTest("D", 4));

        return tests.toArray();
    }

    private final String parameter;
    private final int failCause;

    public BarTest(final String parameter, final int failCause) {
        this.parameter = parameter;
        this.failCause = failCause;
    }

    @Test
    public void bar() {
        Reporter.log("An useful trace to debug: " + failCause);
        if (parameter.equals("B")) {
            throw new IllegalArgumentException();
        }
    }
}
```

The reporter output for this test is:
- bar An useful trace to debug: 3
- bar An useful trace to debug: 1
- bar An useful trace to debug: 4
- bar An useful trace to debug: 2

Since the output is not next to the fail exception, is hard to know which trace belongs to the failed test

**Comment by krmahadevan** [comment]
I am not sure if this is a problem. `Reporter.log()` basically logs messages when invoked. Exceptions and failures are not logged automatically by TestNG via `Reporter.log()` and internally associated as a log message for a given test. If its needed, it has to be explicitly done so.

Closing this issue.
