### ISSUE TITLE
Retry functionality not working when running with multiple browser. 

### ISSUE THREAD

**Issue by ujjwal3687** [cbeust/testng#2062]
### TestNG Version

```java
public class MyListeners extends BaseClass implements IRetryAnalyzer, IAnnotationTransformer, ITestListener
{
	int counter = 0;
	int retry_limit = 1; 
	
	public MyListeners() throws Exception 
	{
		super();
	}
	
	@Override
	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) 
	{
		annotation.setRetryAnalyzer(com.Automation.Listeners.MyListeners.class);
	}

	@Override
	public boolean retry(ITestResult result) 
	{
		if(counter < retry_limit)
		{
			counter++;
			return true;
		}
		return false;
	}
```

```xml
<suite name="Suite" parallel="tests">
 <listeners>
 <listener class-name= "com.Automation.Listeners.MyListeners" />
</listeners> 

   <test name="Chrome Test Cases">
  <parameter name= "Browser" value = "Chrome" />
    <classes>
      <class name="com.Automation.TestCases.HomePage_Test_Cases"/>
    </classes>
  </test>  
 
   <test name="Firefox Test Cases">
  	<parameter name= "Browser" value = "Firefox" />
    <classes>
      <class name="com.Automation.TestCases.HomePage_Test_Cases"/>
    </classes>
  </test>

```

```java
public class HomePage_Test_Cases extends BaseClass
{
	public HomePage_Test_Cases() throws Exception 
	{
		super();
	}
	
	@BeforeMethod
	@Parameters("Browser")
	public void browser_init(String Browser_Name)
	{
		Launch_Browser(Browser_Name);
	}
	
	@Test
	public void test() throws Exception
	{
		Assert.assertTrue(false);
	}
	
	@Test
	public void test2() throws Exception
	{
		Assert.assertTrue(false);
	}
	
	@AfterMethod
	public void browser_close()
	{
		driver.quit();
	}
}
```

### Expected behavior
It should work for both Browser.

### Actual behavior
It's working only for first browser.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
Attempted at reproducing this issue using TestNG `7.0.0-beta5` (latest released version as of today). Unable to recreate this issue. Closing this issue.

Here's the sample that I used.

**Sample test class**

```java
import org.testng.Assert;
import org.testng.annotations.Test;

public class SampleTestCase {

  @Test(retryAnalyzer = ICanRetry.class)
  public void testMethod() {
    Assert.fail("Failing");
  }
}
```

**Retry analyzer**

```java
import java.util.ArrayList;
import java.util.List;
import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;

public class ICanRetry implements IRetryAnalyzer {
  static final List<String> msgs = new ArrayList<>();
  private int counter = 0;
  private static final int RETRY_LIMIT = 1;

  @Override
  public boolean retry(ITestResult result) {
    if (counter < RETRY_LIMIT) {
      counter++;
      msgs.add("Retrying for test tag <" + result.getTestContext().getName() + ">");
      return true;
    }
    return false;
  }
}
```

**Test runner**
```java
import java.util.Collections;
import org.assertj.core.api.Assertions;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

public class IssueTest {

  @Test
  public void testMethod() {
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setName("xml_suite");
    XmlTest chromeTests = new XmlTest(xmlSuite);
    chromeTests.setName("chrome_tests");
    chromeTests.setClasses(Collections.singletonList(new XmlClass(SampleTestCase.class)));

    XmlTest firefoxTests = new XmlTest(xmlSuite);
    firefoxTests.setName("firefox_tests");
    firefoxTests.setClasses(Collections.singletonList(new XmlClass(SampleTestCase.class)));

    TestNG testng = new TestNG();
    testng.setXmlSuites(Collections.singletonList(xmlSuite));
    testng.run();
    String[] expected = new String[] {
          "Retrying for test tag <chrome_tests>",
        "Retrying for test tag <firefox_tests>"
        };
    Assertions.assertThat(ICanRetry.msgs).containsExactlyInAnyOrder(expected);
  }
}
```

**Comment by ujjwal3687** [comment]
> ### TestNG Version
> ```java
> public class MyListeners extends BaseClass implements IRetryAnalyzer, IAnnotationTransformer, ITestListener
> {
> 	int counter = 0;
> 	int retry_limit = 1; 
> 	
> 	public MyListeners() throws Exception 
> 	{
> 		super();
> 	}
> 	
> 	@Override
> 	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) 
> 	{
> 		annotation.setRetryAnalyzer(com.Automation.Listeners.MyListeners.class);
> 	}
> 
> 	@Override
> 	public boolean retry(ITestResult result) 
> 	{
> 		if(counter < retry_limit)
> 		{
> 			counter++;
> 			return true;
> 		}
> 		return false;
> 	}
> ```
> 
> ```
> <suite name="Suite" parallel="tests">
>  <listeners>
>  <listener class-name= "com.Automation.Listeners.MyListeners" />
> </listeners> 
> 
>    <test name="Chrome Test Cases">
>   <parameter name= "Browser" value = "Chrome" />
>     <classes>
>       <class name="com.Automation.TestCases.HomePage_Test_Cases"/>
>     </classes>
>   </test>  
>  
>    <test name="Firefox Test Cases">
>   	<parameter name= "Browser" value = "Firefox" />
>     <classes>
>       <class name="com.Automation.TestCases.HomePage_Test_Cases"/>
>     </classes>
>   </test>
> ```
> 
> ```java
> public class HomePage_Test_Cases extends BaseClass
> {
> 	public HomePage_Test_Cases() throws Exception 
> 	{
> 		super();
> 	}
> 	
> 	@BeforeMethod
> 	@Parameters("Browser")
> 	public void browser_init(String Browser_Name)
> 	{
> 		Launch_Browser(Browser_Name);
> 	}
> 	
> 	@Test
> 	public void test() throws Exception
> 	{
> 		Assert.assertTrue(false);
> 	}
> 	
> 	@Test
> 	public void test2() throws Exception
> 	{
> 		Assert.assertTrue(false);
> 	}
> 	
> 	@AfterMethod
> 	public void browser_close()
> 	{
> 		driver.quit();
> 	}
> }
> ```
> 
> ### Expected behavior
> It should work for both Browser.
> 
> ### Actual behavior
> It's working only for first browser.
> 
> ### Is the issue reproductible on runner?
> * [ ]  Shell
> * [ ]  Maven
> * [ ]  Gradle
> * [ ]  Ant
> * [x]  Eclipse
> * [ ]  IntelliJ
> * [ ]  NetBeans
> 
> ### Test case sample
> > Please, share the test case (as small as possible) which shows the issue

Hi @krmahadevan : Thanks for the quick reply. Can you please let me know where i need to modify my code to work it correctly?
Thanks in Advance.

**Comment by krmahadevan** [comment]
@ujjwal3687 - I don't know what version of TestNG you are using. Please try using the latest version as how I have mentioned. There's no code change that I had to do to get it to work properly.

**Comment by ujjwal3687** [comment]
Hi @krmahadevan : I am using testng with version number 6.14.3.
Can you please check below code and let me know the error ? This is the code which is not working. Please check this code by copying this code & run in your machine.

Base claas. java
----------------
public class BaseClass 
{
	public Properties pro;
	public WebDriver driver;
	
	public BaseClass() throws Exception
	{
		File f = new File("./src/main/java/com/Automation/Configuration/Config.Properties");
		FileInputStream fis = new FileInputStream(f);
		pro = new Properties();
		pro.load(fis);
	} 
	
	@Parameters("Browser")
	public void Launch_Browser(String Browser_Name)
	{
		if(Browser_Name.equalsIgnoreCase("Chrome"))
		{
			ChromeOptions opt = new ChromeOptions();
			opt.addArguments("disable-infobars");
			opt.addArguments("disable-notifications");
			System.setProperty(pro.getProperty("Chrome_System_Property"), pro.getProperty("Chrome_Driver_Path"));
			driver = new ChromeDriver(opt);
		}
		else if(Browser_Name.equalsIgnoreCase("Firefox"))
		{
			System.setProperty(pro.getProperty("Firefox_System_Property"), pro.getProperty("Firefox_Driver_Path"));
			driver = new FirefoxDriver();
		}
		
		else if(Browser_Name.equalsIgnoreCase("Opera"))
		{
			System.setProperty(pro.getProperty("Opera_System_Property"), pro.getProperty("Opera_Driver_Path"));
			driver = new OperaDriver();
		}
		
		driver.manage().window().maximize();
		driver.manage().deleteAllCookies();
		driver.get(pro.getProperty("URL"));
		driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	}
}

----------------------
Config.Properties
-------------------
Chrome_System_Property = webdriver.chrome.driver
Chrome_Driver_Path = ./src/main/java/com/Automation/Drivers/chromedriver.exe
Firefox_System_Property = webdriver.gecko.driver
Firefox_Driver_Path = ./src/main/java/com/Automation/Drivers/geckodriver.exe
URL = https://www.google.com

-------------------------
MyListeners.java
-----------------------
public class MyListeners extends BaseClass implements IRetryAnalyzer, IAnnotationTransformer
{
	int counter = 0;
	int retry_limit = 1; 
	
	public MyListeners() throws Exception 
	{
		super();
	}
	
	@Override
	public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) 
	{
		annotation.setRetryAnalyzer(com.Automation.Listeners.MyListeners.class);
	}

	@Override
	public boolean retry(ITestResult result) 
	{
		if(counter < retry_limit)
		{
			counter++;
			return true;
		}
		return false;
	}
}

--------------------------------
Home_Page_Test_Cases.java	
--------------------------------
public class HomePage_Test_Cases extends BaseClass
{
	public HomePage_Test_Cases() throws Exception 
	{
		super();
	}
	
	@BeforeMethod
	@Parameters("Browser")
	public void browser_init(String Browser_Name)
	{
		Launch_Browser(Browser_Name);
	}
	
	@Test
	public void test() throws Exception
	{
		Assert.assertTrue(false);
	}
	
	@Test
	public void test2() throws Exception
	{
		Assert.assertTrue(false);
	}
	
	@AfterMethod
	public void browser_close()
	{
		driver.quit();
	}
}
---------------------------
testng.xml
-------------------------
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">

<suite name="Suite">
 <listeners>
 <listener class-name= "com.Automation.Listeners.MyListeners" />
</listeners> 

   <test name="Chrome Test Cases">
  <parameter name= "Browser" value = "Chrome" />
  <parameter name= "Browser" value = "Firefox" />
    <classes>
      <class name="com.Automation.TestCases.HomePage_Test_Cases"/>
    </classes>
  </test>  
 
   <test name="Firefox Test Cases">
  	<parameter name= "Browser" value = "Firefox" />
  	<parameter name= "Browser" value = "Chrome" />
    <classes>
      <class name="com.Automation.TestCases.HomePage_Test_Cases"/>
    </classes>
  </test>         
</suite>

**Comment by krmahadevan** [comment]
@ujjwal3687 

>  I am using testng with version number 6.14.3.

I am not sure where you are going with this. Irrespective of whether the issue exists or not in `6.14.3`, there is nothing that can be done about it. Its an old version. Please use the latest released version and try again. Your issue should no longer exist.

**Comment by ujjwal3687** [comment]
I tried with the latest version. Showing same error. I am new to Selenium
so I am exploring. Can you please recheck my code and logic implemented in
the code?

**Comment by krmahadevan** [comment]
> I am new to Selenium so I am exploring.

Can you please remove selenium from the equation and just try with a plain vanilla test that just uses `system.out.println` statements 

If you are still experiencing the same issue, then pls share that sample and we can investigate.
