### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by am9739** [cbeust/testng#2065]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
The test case is supposed to get executed

### Actual behavior
I'm getting Null Pointer Exception(ahooLoginTest("param-val-not-found", "param-val-not-found", "param-val-not-found")
java.lang.NullPointerException) when I'm executing the TestNg class and I'm getting this error message(Parameter &apos; url&apos; is required by @Test on method yahooLoginTest but has not been marked @Optional or defined
in /Users/arushreemohapatra/Desktop/Eclipse-Workspace/Guru99/src/TestNg.xml)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
  <suite name="Yahoo app Test Automation suite" verbose="1" >
      <test name="Yahoo App Test">
      <parameter name= "browser" value = "Chrome"/>
      <parameter name ="url" value= "https://login.yahoo.com/"/>
      <parameter name = "emailid"  value ="arush_india@yahoo.co.in"/>
     <classes>
    <class name="testNg.ParameterTestClass"/>
   </classes>
  </test>
</suite>
```

************************************
```java
package testNg;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class ParameterTestClass {
	
	WebDriver driver;

	@Test
	@Parameters({"browser"," url" , "emailid"})	
	public void yahooLoginTest(String browser,String url, String emailid){
		if(browser.equals("Chrome")) {
			System.setProperty("webdriver.chrome.driver", "/Users/arushreemohapatra/Documents/Selenium/chromedriver");
			driver = new ChromeDriver();
		} else if(browser.equals("FF")){
			System.setProperty("webdriver.gecko.driver","/Users/arushreemohapatra/Documents/Selenium/geckodriver");
			 driver = new FirefoxDriver();
		}
		
		driver.get(url);		
		driver.findElement(By.id("login-username")).clear();
		driver.findElement(By.id("login-username")).sendKeys(emailid);
		driver.findElement(By.id("login-signin")).click();
	}
}
```

**Comment by am9739** [comment]
This is my XML file.
************************
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
  
<suite name="Yahoo app Test Automation suite" verbose="1" >
      <test name="Yahoo App Test">
      
      <parameter name= "browser" value = "Chrome"/>
      <parameter name ="url" value= "https://login.yahoo.com/"/>
      <parameter name = "emailid"  value ="arush_india@yahoo.co.in"/>
     
    <classes>
    
      <class name="testNg.ParameterTestClass"/>
      
      
      
    </classes>
  </test>
</suite>

**Comment by krmahadevan** [comment]
I am going to assume that you have been trying to right click on your test class `testNg.ParameterTestClass` within your IDE (eclipse/IntelliJ) right click and then choosing run as TestNG test.

That is the only way in which you can get this exception.

Please right click on your suite file and then run it.

**Comment by am9739** [comment]
It should get executed even if i’m running the class file, I shouldn’t be getting null pointer exception. 
When in try to execute the xml file I get error message related to Optional keyword, when I haven’t used that keyword in my test.

**Comment by krmahadevan** [comment]
> It should get executed even if i’m running the class file, I shouldn’t be getting null pointer exception.

Unfortunately that is not how TestNG works. The parameters provided via the xml file would be injected only if the test class is getting executed via the testng suite xml file.

> When in try to execute the xml file I get error message related to Optional keyword, when I haven’t used that keyword in my test.

You are yet to show the complete stack trace.

On a side note, you have not also told us what version of TestNG are you working with ?

**Comment by krmahadevan** [comment]
With respect to the error when you run via the TestNG suite xml file, the problem lies in your test code.

Your parameter is defined as `url` but in your test method, you are referring to the parameter as ` url` (Notice the extra space in the parameter name). These two aren't the same.

```
@Parameters({"browser"," url" , "emailid"})
```

Please fix your test code and try again.
