### ISSUE TITLE
Thread ID not unique in a suite when running in Parallel Mode

### ISSUE THREAD

**Issue by anuragdeshpande** [cbeust/testng#2067]
### TestNG Version
> Note: only the latest version is supported

Using the latest version of TestNG: 7.0.0-beta4 but tested in each of previous versions until 6.13 (Same issue/ behavior)

### Expected behavior
When `<test>`s are running in parallel(parallel mode: Tests), thread ID should be unique through out the entire run

### Actual behavior
When tests are running in parallel, Thread ID is being reused. i.e., more than one <test> is running with same thread ID

### Is the issue reproducible on runner?
I have run the same scenario in Maven, command line, TestNG runner class, Intellij IDEA
- [X] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

# Official TestNG Documentaion

> TestNG will run all the methods in the same <test> tag in the same thread, **_but each <test> tag will be in a separate thread_** . This allows you to group all your classes that are not thread safe in the same <test> and guarantee they will all run in the same thread while taking advantage of TestNG using as many threads as possible to run your tests

By this explanation in the documentation, One would assume that each test will have its own thread ID 

# Test case 
>Setup
Each Class has one method that spins up a new driver and opens a URL
5 Classes written up as 5 `<Tests>` with one class each
1 Suite, Thread Count 3, Parallel Mode: Tests
Printing the thread ID in each test to track the thread the test is running in.

## Expectation
Each Test must have its own thread ID

## Actual Behavior
Depending on thread count, Initial Threads are started and the following tests reuse the thread ID from the initial threads created. 

## XML Suite file
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="3" name="Regression Regression" parallel="tests">
  <test name="TestClassFive">
    <classes>
      <class name="TestClassFive"/>
    </classes>
  </test> <!-- TestClassFive -->
  <test name="TestClassFour">
    <classes>
      <class name="TestClassFour"/>
    </classes>
  </test> <!-- TestClassFour -->
  <test name="TestClassOne">
    <classes>
      <class name="TestClassOne"/>
    </classes>
  </test> <!-- TestClassOne -->
  <test name="TestClassSix">
    <classes>
      <class name="TestClassSix"/>
    </classes>
  </test> <!-- TestClassSix -->
  <test name="TestClassThree">
    <classes>
      <class name="TestClassThree"/>
    </classes>
  </test> <!-- TestClassThree -->
  <test name="TestClassTwo">
    <classes>
      <class name="TestClassTwo"/>
    </classes>
  </test> <!-- TestClassTwo -->
</suite> <!-- Regression Regression -->

```

## Class Definition

Repeated the same class 5 times for running the test case.

```

public class TestClassOne  {
    @Test
    public void testOne() {
        long id = Thread.currentThread().getId();
        System.out.println(id+": Starting Test - autoFullClaim_FNOLTest in thread ID: "+id);
        ChromeDriver driver = new ChromeDriver();
        driver.get("http://www.google.com");
        driver.quit();
    }

```

## Result

```
31: Starting Test - testOne in thread ID: 31
29: Starting Test - testFive in thread ID: 29
30: Starting Test - testThree in thread ID: 30
30: Starting Test - testTwo in thread ID: 30
31: Starting Test - testFour in thread ID: 31
29: Starting Test - testSix in thread ID: 29

```

**Comment by krmahadevan** [comment]
This is not an issue. TestNG is working as designed here. TestNG internally makes use of a thread pool to manage concurrency. Threadpool by definition means that threads would be re-used. 

The documentation merely states that every method would run in its own thread. There is no guarantee that the threads would be unique all the time. If that has to be done, then it defeats the purpose of having a thread pool.
