### ISSUE TITLE
Customized XMLReporter set via ISuiteListener remains dormant

### ISSUE THREAD

**Issue by rjmartell** [cbeust/testng#207]
A reporter can be set on both the main TestNG driver and via the ISuiteListener interface (i.e. ISuite.addListener(lsnr:ITestNGListener)).

It seems that the suite-level reporter is never used (TestNG 6.4). Can these reporters coexist?

After creating a custom XMLReporter (by means of the usual ReporterConfig mechanism), it only appears effective when set on the main driver. But when an identically configured reporter is set on an ISuite instance (SuiteRunner), it's never called.

The intent is to embed a customized XMLReporter without resorting to extraneous input parameters. I was hoping there would be a third way to activate a non-default XMLReporter using a listener (in addition to the initial command-line and Ant configuration options). Is this possible?

Since reports are generated at the end of the run, perhaps any additional reporters could be registered if found in the suite runners.

e.g. Consider this little enhancement to TestNG.java

``` java
private void generateReports(List<ISuite> suiteRunners) {
  augmentReporters(suiteRunners);
  ...
}

private void augmentReporters(List<ISuite> suiteRunners) {
  for (ISuite suite : suiteRunners) {
    SuiteRunner runner = (SuiteRunner) suite;
    List<IReporter> reporters = runner.getReporters();
    for (IReporter reporter : reporters) {
      addListener(reporter);
    }
  }
}
```

**Comment by krmahadevan** [comment]
As of TestNG `7.3.0` following are some of the pre-requisites

* TestNG will not work with duplicate instances of the same listener class. As long as this can be satisfied, TestNG will accept listeners.
* Listeners can be easily added in via a [Service Provider Interface](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html) as detailed in the TestNG documentation [here](https://testng.org/doc/documentation-main.html#listeners-service-loader)
* One can also leverage `org.testng.IAlterSuiteListener` and add the listener in (But this would be like a listener adding another listener and kind of looks like a round about way of doing things). This interface should be leveraged when a suite contents need to be altered (add|remove|modify `<test>` contents for e.g.,) before TestNG starts executing it.

If this is still a problem, please add a comment along with a sample that can be used to reproduce the problem.
