### ISSUE TITLE
7.0.0-beta6 NoClassDefFoundError: com/beust/jcommander/ParameterException

### ISSUE THREAD

**Issue by escay** [cbeust/testng#2070]
### TestNG Version
7.0.0-beta6

### Expected behavior
No exception, my maven module with a number of testng test classes should just compile and test.
I am trying to upgrade from 6.14.3 to 7.0.0-beta to be able to use some new functionality.

The compile problem does not occur in 7.0.0-beta5

### Actual behavior
Stacktrace occurs:
<code>
Created at 2019-05-10T09:01:57.062
java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:86)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
</code>

### Is the issue reproductible on runner?
Yes it can be reproduced. It is also found in #2069 

- [ ] Shell
- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Just a regular maven module with a large number of TestNg test classes.

**Comment by escay** [comment]
Note that I was looking to upgrade from 6.14.3 to a more recent version. So I started using Maven which only contains 7.0.0-beta4, using 7.0.0-beta4 failed due to issue #2051 

I followed the suggestion to use 7.0.0-beta6 from JCenter, but it contains this problem.
I will now try to continue using 7.0.0-beta5 for the time being.
Perhaps it is wise to promote 7.0.0-beta5 to maven repository to avoid others following this path.

**Comment by escay** [comment]
I cannot seem to find commits in github when I look at the master codeline
https://github.com/cbeust/testng/commits/master based on these release dates:

<code>
7.0.0-beta5/         05-Apr-2019 18:36    -
7.0.0-beta6/         08-Apr-2019 22:06    -
</code>

There is also no tag in github for 7.0.0-beta5 or 7.0.0-beta6, I cannot directly see what went wrong.

When comparing both 7.0.0-beta5 and 7.0.0-beta6 jar files the only difference is the META-INF\MANIFEST.MF file content. There are some different properties and the ordening of the properties are a bit different.

**Comment by escay** [comment]
The problem seems to be in the pom file:
https://repo.spring.io/jcenter/org/testng/testng/7.0.0-beta6/testng-7.0.0-beta6.pom
it does not include the dependencies.
When I use the 7.0.00beta5 pom file, it works.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.testng</groupId>
  <artifactId>testng</artifactId>
  <version>7.0.0-beta6</version>
  <dependencies>
    <dependency>
      <groupId>com.beust</groupId>
      <artifactId>jcommander</artifactId>
      <version>1.72</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.ant</groupId>
      <artifactId>ant</artifactId>
      <version>1.10.3</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>1.21</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <version>4.1.0</version>
      <classifier>no_aop</classifier>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by krmahadevan** [comment]
@cbeust - Can you please help with this? We haven't pushed the tags, and looks like `beta6` also went stale.

**Comment by escay** [comment]
Another workaround is to add the dependency:

```
    <dependency>
      <groupId>com.beust</groupId>
      <artifactId>jcommander</artifactId>
      <version>1.72</version>
    </dependency>
```

manually to your project when you do not want to patch the pom manually.

**Comment by krmahadevan** [comment]
@escay - Can you please try again using TestNG `7.0.0-beta7` ?
http://repo1.maven.org/maven2/org/testng/testng/7.0.0-beta7/
