### ISSUE TITLE
Unable to resolve @Test or any other anotation

### ISSUE THREAD

**Issue by gitissuepost** [cbeust/testng#2071]
### TestNG Version
7.0.0-Beta4

### Expected behavior
Upon adding @Test, it shouldn't result into error

### Actual behavior
Test cannot be resolved to a Type.
Also unable to find org.testng.annotation in testng package 

### Is the issue reproductible on runner?
Yes
- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
Please make use of TestNG `7.0.0-beta5`. `beta4` was a bad build.

since `beta5` is not yet available on Maven central, you may have to add a repository section that looks like below to your `pom.xml` (or) to your `~/.m2/settings.xml`

```xml
                <repository>
                    <id>jcenter</id>
                    <name>jcenter</name>
                    <url>http://jcenter.bintray.com</url>
                </repository>
```
