### ISSUE TITLE
Testng exception

### ISSUE THREAD

**Issue by NawazDevops** [cbeust/testng#2072]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Running classes in parallel using selenium grid and testng

### Actual behavior
Getting below exception
Cannot inject @Test annotated Method [xxx] with [class org.openqa.selenium.remote.DesiredCapabilities].

### Is the issue reproductible on runner?
Maven

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@NawazDevops - You haven't provided sufficient information for us to debug.
What version of TestNG are you using ?
What does your code look like ?

Please help share a simple standalone test that can be used to reproduce this issue.

**Comment by juherr** [comment]
Please reopen once you'll have more details.
