### ISSUE TITLE
Test classes getting executed in unexpected order after TestNG version Upgrade

### ISSUE THREAD

**Issue by HemapriyaAnnadurai** [cbeust/testng#2073]
### TestNG Version
> 6.14.3

### Expected behavior
We have upgraded from version 6.8.5 to 6.14.3. Our test suites have <exclude> for specific methods as shown in the screenshot below

![suite](https://user-images.githubusercontent.com/50625968/57702029-d13c7a00-767a-11e9-8879-e953faf15964.jpg)

Expected behaviour is the Tests 1, 2 and 3 must run in order

### Actual behavior
Order is not preserved. Test3 runs before Test2. This issue is occuring from versions 6.9.13.3 till 6.14.3 

### Is the issue reproductible on runner?
Issue can be reproduced in Eclipse and IntelliJ

### Test case sample

**Comment by krmahadevan** [comment]
@HemapriyaAnnadurai - The latest released version of TestNG is `7.0.0-beta5`.
Please try using that and let us know what you see.

**Comment by HemapriyaAnnadurai** [comment]
@krmahadevan  We have tested with 7.0.0-beta5 version of TestNG and the issue seems to be resolved. The suite is running in the expected order. Thanks

**Comment by krmahadevan** [comment]
@HemapriyaAnnadurai - Thanks for the confirmation. 

Closing this issue.
