### ISSUE TITLE
Thread Interrupted when using expectedException v6.14.3

### ISSUE THREAD

**Issue by kcorman** [cbeust/testng#2074]
### TestNG Version
6.14.3

### Expected behavior
When a test defines a timeOut and an expectedException and the test passes, the runner thread should not be interrupted

### Actual behavior
When a test defines a timeOut, an expectedException, and is executed with some level of parallelism (I tried this with both class and method parallelism), after the test passes the runner thread is left with the interrupt flag set, so a subsequent test that makes some kind of interruptible call will fail unexpectedly.

### Is the issue reproductible on runner?

- [ ] Shell - didn't try
- [X] Maven
- [ ] Gradle - didn't try
- [ ] Ant - didn't try
- [X] Eclipse
- [ ] IntelliJ - didn't try
- [ ] NetBeans - didn't try

### Test case sample

```java
public class FailingInterruptTest {
	@Test(expectedExceptions=RuntimeException.class, timeOut=1000)
	public void shouldntInterruptTheThreadButDoesTest() {
		throw new RuntimeException("unit test exception");
	}
	
	@AfterMethod
	public void checkForInterrupts() {
		if(Thread.interrupted()) { // check for interrupts and clear the flag
			fail("Thread was interrupted but shouldn't have been");
		}
	}
}
```

If you run this with some non-serial parallelism setting, you'll see the @AfterMethod fail after execution of `shouldntInterruptTheThreadButDoesTest`. For example, in eclipse I used this testng xml file

```xml
<suite name="ExampleTestNGBug" verbose="1" parallel="classes" thread-count="2">
  <test name="ExampleTestNGBug" >
	  <classes>
	     <class name="FailingInterruptTest" />
	  </classes>
  </test>
</suite>
```

**Comment by NoOneOfConsequence** [comment]
This one cost us two days of head scratching before we finally tracked it down. It seems very poor behavior for the framework, particularly when combined with https://github.com/cbeust/testng/issues/2075
