### ISSUE TITLE
TestNG WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by SonaliBurghate** [cbeust/testng#2076]
### TestNG Version
> Note: only the latest version is supported
This issue seems with testng6.11 with Java 12.
### Expected behavior
Testng warnings are thrown while executing test suite from maven on Mac which should not be thrown.
Following are the environment details :
 - Java 12.0.1
- Maven 3.6.1
- Testng 6.11
### Actual behavior
**Stack trace -** 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.testng.xml.XMLParser (/testng-6.11.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of org.testng.xml.XMLParser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### Is the issue reproductible on runner?
- [ ] Shell
- [ ] Maven

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@SonaliBurghate - You seem to be using a very old version of TestNG. The latest released version of TestNG is `7.0.0-beta5`. Please try again using that and let us know what you see.

**Comment by SonaliBurghate** [comment]
@krmahadevan Thanks for looking into the the issue. However I cannot find TestNG 7.0.0-beta5 version in maven repository (https://mvnrepository.com/artifact/org.testng/testng).  I tried with 7.0.0-beta1 to 7.0.0-beta4, all of them throws error to me for using testNG annotations such as @BeforeMethod, @AfterMethod and failed to compile the code.

SoI tried with v 6.14.3 and it still shows me the warning. "WARNING: An illegal reflective access operation has occurred"

Let me know your thoughts . Thank you.

**Comment by krmahadevan** [comment]
@sonaliburghate - `7.0.0-beta5` is not yet synced to Maven central. It's only available in JCenter. 

Please refer this SO post to learn how to work with a JCenter repository. 
https://stackoverflow.com/questions/44265547/how-to-properly-specify-jcenter-repository-in-maven-config/44304245

**Comment by SonaliBurghate** [comment]
Thanks @krmahadevan . Sorry, but I am not willing to use JCenter at this point. Do u think it should work with 7.0.0-beta4?

If yes, i will again try for 7.0.0-beta4 version .

**Comment by krmahadevan** [comment]
@SonaliBurghate - `beta4` is a bad build. You cannot use that. You can try using `beta3` as well. The problem should have resolved in that too. I remember removing this explicit reference to an internal class of JDK via [this](https://github.com/cbeust/testng/commit/dc530fbf2164c7efa06ae806d4cf2716a2b86404#diff-6636f591b160c77f084eba19dacc7679) commit. So I think it should no longer exist.

**Comment by SonaliBurghate** [comment]
Sure. I will give it a try and let you know. Thanks

**Comment by krmahadevan** [comment]
@SonaliBurghate - If the problem is gone, please do help close off the issue as well.

**Comment by SonaliBurghate** [comment]
@krmahadevan Sure.

**Comment by krmahadevan** [comment]
ping @SonaliBurghate - Any updates on this? Can we close this issue ?

**Comment by SonaliBurghate** [comment]
Sorry @krmahadevan for late reply. Issue is resolved for me. Closing it.

**Comment by VolodymyrHunko** [comment]
7.0.0-betta3 still has this issue.

**Comment by krmahadevan** [comment]
@VolodymyrHunko - The latest released version is `7.0.0-beta7`. Please try again in that. If this is still a problem, please help share a sample and also the JDK version that you are using.

**Comment by VolodymyrHunko** [comment]
<img width="714" alt="Annotation 2019-07-24 103033" src="https://user-images.githubusercontent.com/20745796/61802359-4c01de00-adfe-11e9-9daa-0eced6a2dff3.png">

**Comment by VolodymyrHunko** [comment]
Same issue with betta7.

**Comment by krmahadevan** [comment]
@VolodymyrHunko  your exception doesn't seem to be stemming from TestNG. Please take a closer look, it looks like its hinting at some groovy plugin which is having this problem. Here's a corresponding issue related to this https://github.com/magarena/magarena/issues/1368

TestNG doesn't have anything to do with this problem.

**Comment by VolodymyrHunko** [comment]
Thanks
