### ISSUE TITLE
Cannot install TestNG plugin in Eclipse

### ISSUE THREAD

**Issue by HanishS** [cbeust/testng#2077]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
TestNG should get installed

### Actual behavior
error:
Unable to read repository at http://beust.com/eclipse.
Unable to read repository at http://beust.com/eclipse/6.9.13.
Unable to read repository at http://beust.com/eclipse/updatesites/6.9.13.201609291640/content.jar.
Read timed out

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by missedone** [comment]
pls checkout this doc first: https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md

**Comment by juherr** [comment]
Open an issue on https://github.com/cbeust/testng-eclipse if needed
