### ISSUE TITLE
Xml to Yaml does not capture the dependency definition in generated Yaml File

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2078]
### TestNG Version
> Note: only the latest version is supported
7.0.0-beta5

### Expected behavior
The generated Yaml file should contain the dependencies defined in the xml file

### Actual behavior
The generated Yaml file seems to be missing the dependency definition

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Here's a suite 

```xml
<!DOCTYPE suite SYSTEM "http://beust.com/testng/testng-1.0.dtd" >
<suite name="My_Suite">
  <test name="My_test">
    <groups>
      <dependencies>
        <group name="c" depends-on="a  b"/>
        <group name="z" depends-on="c"/>
      </dependencies>
    </groups>
    <packages>
      <package name="rationale.emotions"/>
    </packages>
  </test>
</suite>
```

Test code that attempts to do the transformation 
```java
import java.io.IOException;
import org.testng.Converter;

public class XmlToYaml {

  public static void main(String[] args) throws IOException {
    Converter.main(new String[]{"src/test/resources/dontcheckin/suite.xml", "-d", "src/test/resources/dontcheckin/"});
  }
}
```

**Comment by krmahadevan** [comment]
Captured from this forum thread https://groups.google.com/d/msg/testng-users/0-ytYftlEWg/0BUL6GyDAwAJ

**Comment by jiong-fu** [comment]
The corresponding YAML file for the XML suite should be
```
name: My_Suite
configFailurePolicy: skip
tests:
    - name: My_test
    xmlDependencyGroups:
      c: a b
      z: c
    xmlPackages:
    - name: rationale.emotions
```
I will be working on a correction on YAML parser.
