### ISSUE TITLE
Feature request: ability to include ONLY if test has all of multiple group names

### ISSUE THREAD

**Issue by djangofan** [cbeust/testng#2079]
### Feature Request

Feature request: I am requesting similar capability in TestNG, since TestNG seems to support the "OR" condition only and just not seem to allow inclusion of only Test methods that have 2 required groups on them.

My original thread: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/testng-users/n0raMSfdaEE/yOS6sKw_BAAJ

### Expected behavior

Allow defining effectively "AND and OR group inclusion conditions" within testng.xml .   

### Actual behavior

Currently able to only do an OR condition, where all tests are included if they have 1 group OR another group name.

```
   <groups>
      <define name="include-group">
        <include name="group.one" />
        <include name="group.two" />
      </define>
      <run>
        <include name="include-group" />
      </run>
    </groups>
```

Would like to perhaps be able to do something like this:

```
   <groups>
      <define name="include-group">
        <require name="group.one" />
        <require name="group.two" />
      </define>
      <run>
        <include name="include-group" />
      </run>
    </groups>
```

I am sure I am not the first person to ask for this.  Maybe there was a reason this was never implemented?  If, so can documentation be updated to mention it?

### Is the issue reproducible on runner?

To reproduce, use XML snippets  in above description.

### Test case sample

I think the above description explains the feature request.

**Comment by juherr** [comment]
Usually, using a script could be a good solution when groups are not enough.
https://testng.org/doc/documentation-main.html#beanshell

**Comment by djangofan** [comment]
That seems reasonable.   I assume script will also work within the 'groups' xml tag and not just within 'method-selector' ?

**Comment by juherr** [comment]
Groups are just a way to select methods ;)
But I've never used it, so you'll have to test it by yourself. 

>   java.util.Map<String, String> groups:  a map of the groups the current test method belongs to.

I think it should help to do what you expect.
Maybe @krmahadevan will have more details to share.

**Comment by krmahadevan** [comment]
@djangofan - My bad.. I completely forgot about the bean shell capabilities of TestNG... 

> I assume script might also work within the 'groups' xml tag (with a non-boolean return value) and not just within 'method-selector' ? OR will it only work, as described, within that 'method-selector' context?

The `<script>` tag will only work with a method selector and it will not work with the `<groups>` tag. the `<groups>` tag is in a way another variant of a method-selector because at the end of the day, it all boils down to helping testng filter out what to execute and what to skip

Here's how you can enforce your requirement using bean shell

```java
package com.rationaleemotions.github.issue2079;

import org.testng.annotations.Test;

public class TestClassSample {

  @Test(groups = {"shifu", "oogway"})
  public void kungfuPandaMethod() {
    System.err.println("Kung-fu panda");
  }

  @Test(groups = "tigress")
  public void tigressMethod() {
    System.err.println("tigress");

  }
}
```

Here's my suite xml file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1340_Suite" verbose="2">
  <test name="1340_Tests">
    <method-selectors>
      <method-selector>
        <script language="beanshell">
          <![CDATA[
                    import java.util.ArrayList;

                    ArrayList whatGroups = new ArrayList();
                    whatGroups.add("shifu");
                    whatGroups.add("oogway");
                    ArrayList groups = new ArrayList();
                    for (String g : testngMethod.getGroups()) {
                        groups.add(g);
                    }
                    boolean flag = true;
                    for (String eachGroup: whatGroups) {
                        if (!groups.contains(eachGroup)) {
                            flag = false;
                            break;
                        }
                    }
                    flag;
                ]]>
        </script>
      </method-selector>
    </method-selectors>
    <classes>
      <class name="com.rationaleemotions.github.issue2079.TestClassSample"/>
    </classes>
  </test>
</suite>
```

Here's the output
```
...
... TestNG 7.0.0-beta7 by Cédric Beust (cedric@beust.com)
...
Kung-fu panda
PASSED: kungfuPandaMethod

===============================================
    1340_Tests
    Tests run: 1, Failures: 0, Skips: 0
===============================================

===============================================
1340_Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================
```

Let me know if this would fulfill your ask and if we can close this issue ?

**Comment by djangofan** [comment]
@krmahadevan   I really appreciate the example.  I think I can work with that.
