### ISSUE TITLE
No context provided to IExecutionListener

### ISSUE THREAD

**Issue by rjmartell** [cbeust/testng#210]
Almost all TestNG listeners are passed some kind of context object.

e.g.
ISuiteListener.onStart(ISuite)
ITestListener.onStart(ITestContext)
ITestListener.onTestStart(ITestResult)

However, IExecutionListener receives no such help. At the start of a test run, having access to the main driver itself would be very useful to perform some final pre-run tweaking based on knowledge gleaned from the test environment.

`IExecutionListener.onExecutionStart(TestNG tng)`

For example, in TestNG#runExecutionListeners

```
if (start) l.onExecutionStart(this);
...
```

**Note**: I tried this out and noticed that TestRunner called onExecutionStart() in initListeners(). I gather these are collected from all @Listeners defined directly on a test class. Not sure why an IExecutionListener would be declared in this manner, but commenting out the relevant if block simplified the experiment ;-)

Everything seemed to behave as expected.

**Comment by krmahadevan** [comment]
ping @cbeust @juherr WDYT ?

**Comment by juherr** [comment]
I think the idea is nice but I don't like to expose `TestNG` as param. Instead, we should have an appropriate interface.

**Comment by krmahadevan** [comment]
@juherr - I am not sure as to what we would be giving as an advantage to our users by exposing a `TestNG` like object via the `IExecutionListener` interface. I was thinking that since we do expose most of the capabilities that can be tweaked, via the listener interface `org.testng.IAlterSuiteListener`, there's no additional need wherein anyone would need to get access to the `TestNG` like object. This interface exposes the list of `XmlSuite` to the end-user using which they can alter whatever they want.Your thoughts ?

**Comment by juherr** [comment]
@krmahadevan I see it well if you want to tweak params which are not provided in the suite model (I don't know if some exist)

**Comment by krmahadevan** [comment]
@juherr - Ok.. but wouldn't those parameters be exposed by the build tools such as Maven/Gradle which a user can customize via properties, without TestNG having to undergo any changes ? I see that most of the configurations/tweaks hover around a `<suite>` (or) a `<test>` and very few exist outside of these. Some of the ones that aren't available are 

* `-testjar`
* `-testrunfactory`
* `-suitethreadpoolsize` (This may not be applicable when a user is working with a suite of suites)
* `-xmlpathinjar`
* `-sourcedir`

I think this would need a bit more discussion. On a side note,

**Comment by juherr** [comment]
@krmahadevan I don't see any use case for that options that motivate the extra work.

@rjmartell Thanks for the idea and feel free to reply if you want to share your use case (if it still exist)
