### ISSUE TITLE
TestNG does not work with Eclipse 4.12 (2019-06)

### ISSUE THREAD

**Issue by SuperPat45** [cbeust/testng#2100]
TestNG 7.0.0.201902250541
Eclipse 4.12 (2019-06)
OpenJDK 11

After migration to eclipse 4.12 (2019-06) I have installed the Test NG plugin using t(he url  https://dl.bintray.com/testng-team/testng-eclipse/ (As TestNG was not available on the Marketplace for this eclipse version)

I added the library "TestNG" in hte classpath.
I have the error:
> Invalid classpath container: 'TestNG' in project

My test classes show errors:
> The import org.testng cannot be resolved.

I can not run the test using eclipse because of error:
> An internal error occurred during: "Launching VOCacheTest".
> java.lang.NullPointerException
> 	at org.eclipse.jdt.launching.JavaRuntime.computeDefaultContainerEntries(JavaRuntime.java:1593)
> 	at org.eclipse.jdt.launching.JavaRuntime.computeDefaultContainerEntries(JavaRuntime.java:1533)
> 	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1264)
> 	at org.eclipse.jdt.launching.StandardClasspathProvider.resolveClasspath(StandardClasspathProvider.java:95)
> 	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1657)
> 	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspath(AbstractJavaLaunchConfigurationDelegate.java:431)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.getClasspath(TestNGLaunchConfigurationDelegate.java:370)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.createVMRunner(TestNGLaunchConfigurationDelegate.java:215)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launchTypes(TestNGLaunchConfigurationDelegate.java:156)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launch(TestNGLaunchConfigurationDelegate.java:93)
> 	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
> 	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
> 	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1020)
> 	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1234)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by krmahadevan** [comment]
@SuperPat45 - Can you please file an issue in the eclipse plugin project instead of here to get better traction ? https://github.com/cbeust/testng-eclipse

**Comment by amitsrivastava4all** [comment]
TestNG Not Work for Eclipse Latest Release

**Comment by esatysh** [comment]
I too faced the same issue with eclipse 2019-06 using the marketplace option

I could install TestNG using Help->Install new software...

Use the url: http://beust.com/eclipse
