### ISSUE TITLE
TestNG Listeners not running if they are in dependency

### ISSUE THREAD

**Issue by javydreamercsw** [cbeust/testng#2101]
### TestNG Version
6.14.3

### Expected behavior
Listeners in dependencies are executed

### Actual behavior
Listeners are ignored when in a dependency.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [X] NetBeans

### Test case sample
[Sample.zip](https://github.com/cbeust/testng/files/3340687/Sample.zip)

**Comment by krmahadevan** [comment]
@javydreamercsw - Please retry using the latest released version of TestNG viz., `7.0.0-beta5`. If the problem still exists, please provide details on what needs to be executed from the zip file you have shared. Its not clear what needs to be run to reproduce the problem etc.,  because it has 2 projects in it.

**Comment by javydreamercsw** [comment]
Just run mvn tests on project b after compiling project a.

I'll give it a try ASAP.

**Comment by javydreamercsw** [comment]
Same behavior in 7.0.0-beta5.

**Comment by krmahadevan** [comment]
TestNG is working as designed.

The listener that you have added in `ProjectA` is via the surefire plugin. The entries added via surefire plugin will not have any effect in downstream projects (for e.g., ProjectB).

If you need to have that, you would need to explicitly do one of the following in ProjectB

1. Use `<listeners>` tag (or)
2. Use `ServiceLoader` approach. Refer [here](https://testng.org/doc/documentation-main.html#listeners-service-loader)
