### ISSUE TITLE
Documentation required for OneToTwoDimArrayIterator and OneToTwoDimIterator

### ISSUE THREAD

**Issue by tbarabanov** [cbeust/testng#2104]
### TestNG Version
6.14.3

Documentation says that there are two ways of declaring dataProviders:

```
@DataProvider(name = "test1")
public Object[][] createData1() {
// ...
}
```
and

```
@DataProvider(name = "test2")
public Iterator<Object[]> createData2() {
// ...
}
```

I was looking for a method of using dataProviders like

```
@DataProvider(name = "test3")
public Iterator<CustomDataClass> createData3() {
// ...
}
```

What I've found is that there is a OneToTwoDimIterator class and it looks like it does the job for me. Unfortunately it is not documented and there is no guaranties that this should work at all.

### Expected behavior
org.testng.internal.collections.OneToTwoDimArrayIterator and org.testng.internal.collections.OneToTwoDimIterator should be documented in order to avoid confusion and make their purpose clear for users. 

### Actual behavior
It is unclear what is the purpose and is it safe to rely on org.testng.internal.collections.OneToTwoDimIterator behavior for cases described above (for any casers).

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
package test;


import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.util.Iterator;

import static java.util.Arrays.asList;

/**
 * Unit test for simple App.
 */
public class AppTest {

    static class DataSource {
        int a;
        int b;
    }
    
    /**
     * Rigorous Test :-)
     */
    @Test(dataProvider = "test1")
    public void shouldAnswerWithTrue(DataSource ds) {
        Assert.assertTrue(ds.a == 0);
    }

    @DataProvider(name = "test1")
    public Iterator<DataSource> createData() {
        return asList(
                new DataSource(),
                new DataSource()
        ).iterator();
    }

}
```

**Comment by krmahadevan** [comment]
@tbarabanov - Both these two classes are internally used by TestNG which is why their package has `internal` as part of it. They are not meant to be consumed by anyone outside of the TestNG codebase which is why they don't have any user facing documentation. I believe this was done intentionally.

**Comment by tbarabanov** [comment]
Anyway is it done by purpose that 
```
@DataProvider(name = "test3")
public Iterator<CustomDataClass> createData3() {
// ...
}
```
works or it is just a coincidence?

**Comment by krmahadevan** [comment]
Looking at the codebase https://github.com/cbeust/testng/blob/67b8f040aae98088cab6331a78d66c9536f87b27/src/main/java/org/testng/internal/MethodInvocationHelper.java#L140-L148

I don't think its by co-incidence. But its working as designed.

**Comment by tbarabanov** [comment]
Exactly. Can u confirm that it is safe to relay on this behavior  and update data providers usage/example in testng docs?

**Comment by krmahadevan** [comment]
Am not entirely sure what confirmation are you asking for here.

With respect to updating TestNG docs, would you be interested in raising a pull request for it ?
You need to just Fork [this](https://github.com/testng-team/testng-team.github.io) repository and raise a pull request against it. We can get it merged for you.

**Comment by tbarabanov** [comment]
ok. I will try :)

**Comment by tbarabanov** [comment]
https://github.com/testng-team/testng-team.github.io/pull/32
