### ISSUE TITLE
NullPointerException in latest build

### ISSUE THREAD

**Issue by shah4corp** [cbeust/testng#2112]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
the java package is expected to run as usual after updating the build

### Actual behavior
getting NullPointerException soon after updating the TestNG new build in eclipse 

### Is the issue reproductible on runner?
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by campao** [comment]
Hello, 
I have same issues with the latest version of TestNG. 
The NullPointerException supposed to be corrected but the version 7.0.0-beta7 is unrunable in eclipse IDE. 

[There is  an example of my test case](https://stackoverflow.com/questions/57035692/eclipse-used-testng-7-without-built-with-maven-classpath-issue/57039604#57039604)

You can aslo find erros I had in my project. 
Thanks for help.

**Comment by krmahadevan** [comment]
@shah4corp @campao - Please file a bug in the eclipse TestNG plugin project https://github.com/cbeust/testng-eclipse
