### ISSUE TITLE
Default assertion message

### ISSUE THREAD

**Issue by cdalexndr** [cbeust/testng#2118]
It would be nice to provide some default messages when no mssage is provided, instead of showing:
```
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotEquals(Assert.java:1157)
	at org.testng.Assert.assertNotEquals(Assert.java:1162)
```

For this example the Object::toString method could be used to output "%s not equals %s", ex:
```
    public static void assertNotEquals(Object actual1, Object actual2) {
        String message = String.format( "%s not equals %s", actual1, actual2 );
        assertNotEquals(actual1, actual2, message);
    }
```
Similar to other methods where no message is provided.

TestNG 6.14.3

**Comment by krmahadevan** [comment]
@cdalexndr - Would you be willing to provide a pull request for this? We can help you get this merged.  Here's a document that explains how to go about contributing for TestNG https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md

Note: The latest released version of TestNG is `7.0.0-beta7`
