### ISSUE TITLE
org.testng.xml.Parser chokes on file: URI reference

### ISSUE THREAD

**Issue by rjmartell** [cbeust/testng#212]
If the test suite definition file is specified using a file: URI value, java.io.IOException is thrown, indicating that 

"The filename, directory name, or volume label syntax is incorrect"

e.g.
`>java -cp ./testng-6.5.1.jar org.testng.TestNG "file:///C:/TEMP/testng.xml"`

A suggested fix is to replace line 148 in org.testng.xml.Parser with

``` java
147 if (m_fileName != null) {
148     File mainFile = (m_fileName.startsWith("file:"))
                ? new File(URI.create(m_fileName)) : new File(m_fileName);
```

**Comment by krmahadevan** [comment]
ping @cbeust @juherr - Please advise if you think we should go ahead and do this ? I can't seem to think of a use case when a user would resort to the `file://` protocol for working with a suite xml file.

**Comment by juherr** [comment]
@krmahadevan I agree, users won't use it with `file://` but I see use cases with `http://` (I had the need in a previous job).
So the question is more: Should we support URI too?

**Comment by krmahadevan** [comment]
@juherr - If you already know of a use case wherein a user would use `http://` then we can perhaps go ahead and support that. But what all formats of the URI should be supported ? It would be good if we can go ahead and capture that here before we fix it.

**Comment by juherr** [comment]
@krmahadevan I think we just have to try to convert the string to URI (convert it to "file://" if fails) and provide the URI to `ISuiteParser`:

```
boolean accept(URI uri);
```

**Comment by krmahadevan** [comment]
Let me see if I can send a PR that addresses this.
