### ISSUE TITLE
Issue: Do you have an option so that TestNG does not load Spring context?

### ISSUE THREAD

**Issue by AnastasiaDrozhzha** [cbeust/testng#2120]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
https://testng.org/doc/
Should document an Option when run with Maven, using Surefire Plugin should read a maven option named like '-nospring', then it should run all tests defined by suite, but do not load spring context 

### Actual behavior
No currently such onption exists

### Is the issue reproductible on runner?

- [ ] Maven
- [ ] IntelliJ

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by AnastasiaDrozhzha** [comment]
> ### TestNG Version
> > Note: only the latest version is supported
> 
> ### Expected behavior
> https://testng.org/doc/
> Should document an Option when run with Maven, using Surefire Plugin should read a maven option named like '-nospring', then it should run all tests defined by suite, but do not load spring context
> 
> ### Actual behavior
> No currently such onption exists
> 
> ### Is the issue reproductible on runner?
> * [ ]  Maven
> * [ ]  IntelliJ
> 
> ### Test case sample
> > Please, share the test case (as small as possible) which shows the issue

I work on MobileIron project, where Spring context loads from 3 to 9 minutes, and if Spring context fails to load on whatever reason, TestNG runs it over and over again, resulting 6-8 hours to run all test suite. We do not have a solution to this problem yet. Maybe we can configure Jenkins in such a way that if timeout is reached, it re-runs only tests that do not require Spring Context.

**Comment by krmahadevan** [comment]
This is not a problem with TestNG. The TestNG spring integration is not managed by the TestNG project but by the spring project https://github.com/spring-projects/spring-framework (Specifically [this](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/context/testng/AbstractTestNGSpringContextTests.java) class)

Request you to please file this issue in the corresponding GitHub project.

**Comment by AnastasiaDrozhzha** [comment]
Thanks for a quick response

вс, 28 июл. 2019 г. в 16:53, Krishnan Mahadevan <notifications@github.com>:
