### ISSUE TITLE
JUnit Report should contain the output of org.testng.Reporter

### ISSUE THREAD

**Issue by UrsLange** [cbeust/testng#2124]
### TestNG Version
6.14.3

### Expected behavior
The JUnit report contains a `<system-out><![CDATA[...]]></system-out>` tag. When running TestNG, the generated JUnit report should contain the contents, sent to `org.testng.Reporter` as does the TestNG report.

### Actual behavior
The tag is not created for the JUnit Report:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HOSTNAME" failures="0" tests="1" name="TestNGIssue" time="0.005" errors="0" timestamp="03 Aug. 2019 06:52:05 GMT" skipped="0">
  <testcase classname="TestNGIssue" name="testReporter" time="0.005"/>
</testsuite> <!-- TestNGIssue -->
```
But in the `testng-results.xml` it is present:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[I would expect this message in the JUnit report.]]>
    </line>
  </reporter-output>
  <suite started-at="2019-08-03T06:52:05Z" name="TestNGIssue" finished-at="2019-08-03T06:52:05Z" duration-ms="23">
    <groups>
    </groups>
    <test started-at="2019-08-03T06:52:05Z" name="Command line test" finished-at="2019-08-03T06:52:05Z" duration-ms="23">
      <class name="TestNGIssue">
        <test-method signature="testReporter()[pri:0, instance:TestNGIssue@536aaa8d]" started-at="2019-08-03T06:52:05Z" name="testReporter" finished-at="2019-08-03T06:52:05Z" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[I would expect this message in the JUnit report.]]>
            </line>
          </reporter-output>
        </test-method> <!-- testReporter -->
      </class> <!-- TestNGIssue -->
    </test> <!-- Command line test -->
  </suite> <!-- TestNGIssue -->
</testng-results>
```

### Is the issue reproductible on runner?
Probably all, but verified for:
- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
import org.testng.Reporter;
import org.testng.annotations.Test;

public class TestNGIssue {
    @Test
    public void testReporter() {
        Reporter.log("I would expect this message in the JUnit report.");
    }
}
```

### Further remarks
Probably `org.testng.reporters.JUnitReportReporter` could make some use of `Reporter.getOutput(currentTestResult)` to implement this.

**Comment by jiong-fu** [comment]
@UrsLange I think the message logged with Reporter is not quite compatible with the JUnit format explained [here](https://help.catchsoftware.com/display/ET/JUnit+Format). The system-out tag is designed for data written to System.out stream, but Reporter.log actually does not call System.out internally.
@krmahadevan The message printed with System.out does not appear in system-out tag in JUnit report either. Should this be implemented?

**Comment by UrsLange** [comment]
@jiong-fu You are correct, this would not match the specification. However I would find it rather confusing, if I had to use System.out instead of the Reporter, in order to get the output to be displayed in the JUnit report, while having to use the Reporter, to have the output displayed in the TestNG report.

**Comment by krmahadevan** [comment]
@jiong-fu 

> but Reporter.log actually does not call System.out internally.

That is not true entirely. When you use `Reporter.log(msg, true)`, it does make use of `System.out.println` under the hoods. See [here](https://github.com/cbeust/testng/blob/a485be6e4d0920df1293bb7f1c6d2054a433cdbc/src/main/java/org/testng/Reporter.java#L135-L140)

So technically speaking, one could visualize `Reporter.log()` to be a variant of `System.out.println` and still have them be captured as part of the `<system-out>` tag in the JUnit report.

So in that perspective, I think this issue is valid. Do you want to take a jab at this ?

**Comment by jiong-fu** [comment]
@krmahadevan good catch and sorry, with the sample above, I did not notice that `Report.log` method has an overload that accepts a boolean value controlling the output to `System.out`. Yes, I will take a closer look on this issue. :-)
