### ISSUE TITLE
After Suite Method is getting skipped

### ISSUE THREAD

**Issue by aruvimal** [cbeust/testng#2125]
### TestNG Version
> Note: only the latest version is supported

I have After Test Suite Method is getting skipped 
On completion of Test Suite XML execution, instead of OnFinish TestNG Listener method is executed and stopped

### Expected behavior
On Finish TestNGlistener method and Test After Suite should be executed

### Actual behavior
Only On Finish TestNGlistener is executed

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@aruvimal - There's hardly any information in this issue which can be used to debug.  So closing this issue.

If this issue needs to be re-opened, please share the following

1. What version of TestNG are you using ? [ The latest released version is `7.0.0-beta7` ]
2. Please share a simple standalone project that can be used to reproduce this issue.
