### ISSUE TITLE
Testng.xml is not providing suggestions of tags which was working previously

### ISSUE THREAD

**Issue by tabhresh** [cbeust/testng#2128]
### TestNG Version
> Note: only the latest version is supported
TestNG Version on the system:- org.testng.source_6.14.3.r201802240500

### Expected behavior
When TestNG.xml is created with manual process after adding the following lines we open a tag and during that eclipse was giving suggestions of the choice you can opt based on the position of the pointer but now it's not doing with Eclipse 2019-03 and 2019-06 as well even after updation of all the software eclipse as well as testNG.

### Actual behavior
Attached screenshot

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [Yes ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
![TestNG XML issue](https://user-images.githubusercontent.com/22336822/63147660-74a37f00-c01c-11e9-8e21-9b4cd3ce46a3.png)

[Error Sample.txt](https://github.com/cbeust/testng/files/3508333/Error.Sample.txt)

**Comment by krmahadevan** [comment]
Please file a bug in the TestNG eclipse project https://github.com/cbeust/testng-eclipse

**Comment by tabhresh** [comment]
Ok done thanks
