### ISSUE TITLE
Not able to open my maven projects after updating TestNG to 7.0.0

### ISSUE THREAD

**Issue by Madhusudan-Devaraju** [cbeust/testng#2132]
### Expected behavior
1. Support my existing project (maven) even after the update.
2. I should be able to close the eclipse without any error display.

![TestNG-7 0 0-Error-Eclipse-MavenProject-Windows10](https://user-images.githubusercontent.com/32246035/63378338-acf5e500-c3af-11e9-91cf-1333c3fcf2ea.PNG)

![TestNG-7 0 0 - error while closing the eclipse](https://user-images.githubusercontent.com/32246035/63378626-458c6500-c3b0-11e9-83c1-f29112274bb1.PNG)

### Actual behavior
1. I'm not able to open my projects in eclipse after the updating testNG to 7.0.0.
I'm using eclipse 2019-06 version (Windows 10 - 64 bit)
2. I get javaNullPointerException while closing eclipse.

**Both the above issues are not seen if TestNG is uninstalled.**

###**Please help me to resolve this ASAP.**

**Comment by krmahadevan** [comment]
@Madhusudan-Devaraju 

We have a separate github project for tracking TestNG eclipse related issues.
Request you to file a bug in https://github.com/cbeust/testng-eclipse

**Comment by Madhusudan-Devaraju** [comment]
https://github.com/cbeust/testng-eclipse/issues/444 - new ticket created @  https://github.com/cbeust/testng-eclipse
