### ISSUE TITLE
Class loading disrupted in Servlet context when trying to run test suite packaged in JAR

### ISSUE THREAD

**Issue by rjmartell** [cbeust/testng#214]
I'm trying to run a test suite packaged as a JAR archive in a servlet context (i.e. executed in a Tomcat container via JAX-RS endpoint).

Unfortunately the test classes cannot be found, even though the bundled testng.xml file is successfully located (using setTestJar and setXmlPathInJar).

This behavior has been traced to a line in the `TestNG.initializeSuitesAndJarFile()` method that modifies the thread context ClassLoader:

`361 Thread.currentThread().setContextClassLoader(jarLoader);`

Commenting out the line (and the two preceding ones) fixes the problem.

**NOTE:**
With this line commented out, a command-line invocation simply requires that the test jar be explicitly added to the classpath, otherwise:

```
>java -cp testng-6.4a.jar;jcommander-1.23.jar org.testng.TestNG -testjar ets-alpha-1.0-SNAPSHOT.jar 
-xmlpathinjar org/example/ets/alpha/testng.xml

[TestNG] [ERROR]
Cannot find class in classpath: org.example.ets.alpha.StringChecker
```

**Comment by krmahadevan** [comment]
Closing this issue. Please comment with a reproducible sample if this is still a problem with `7.0.0`
