### ISSUE TITLE
TestNgMethodListener methods with context are not called

### ISSUE THREAD

**Issue by madisparn** [cbeust/testng#2145]
When implementing the org.testng.IInvokedMethodListener in testng 7.0.0 the methods with context are not called.
* org.testng.IInvokedMethodListener#beforeInvocation(org.testng.IInvokedMethod, org.testng.ITestResult, org.testng.ITestContext)
* org.testng.IInvokedMethodListener#afterInvocation(org.testng.IInvokedMethod, org.testng.ITestResult, org.testng.ITestContext)

**Comment by krmahadevan** [comment]
This is fixed in the latest snapshot version of TestNG and should be available in the next release of TestNG. 

Commit that fixed this : https://github.com/cbeust/testng/commit/7b655e145ff53450361f0e24685b4635fbe249ca
