### ISSUE TITLE
I can't run it on  laster Version,but Low version works fine(6.x)

### ISSUE THREAD

**Issue by luozhuwang** [cbeust/testng#2146]
### TestNG Version
> Note: only the latest version is supported

### Actual behavior
[RemoteTestNG] detected TestNG version 7.0.0
java.lang.NoSuchMethodError: org.testng.remote.AbstractRemoteTestNG.addListener(Lorg/testng/ISuiteListener;)V
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
	  @Test
	  public void test001() {			  
	        System.out.println("test001");  
	  }
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@luozhuwang - What version of TestNG eclipse plugin are you working with? TestNG `7.0.0` is not backward compatible with older testng eclipse plugins. You need to upgrade your plugin as well.
If even after upgrading your eclipse testng version, you are still facing problems, please file a bug in https://github.com/cbeust/testng-eclipse (this is the project for the eclipse TestNG plugin)

**Comment by luozhuwang** [comment]
tks,I will  upgrade my plugin
