### ISSUE TITLE
TestNG Reports multiple duplicate entries for the same test

### ISSUE THREAD

**Issue by sachsgit** [cbeust/testng#2147]
### TestNG Version
version 7.0.0.r201908191551

### Expected behavior
In the TestNG "Results of running suite" window, there should only be one instance of the test being execution.

### Actual behavior
For N time of tests, each test has N, N -1, ..., 1, instance diplayed, even though each test was only executed once.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Any suite with N tests will shows that each entry has N ...1 entries/showings.
Example, if you have 3 tests, each only has one method, the first test will have three duplicate entries, the second witll have two, while the last will have the single entry that they all should have.

**Comment by krmahadevan** [comment]
Please report TestNG eclipse plugin related issues in this repo https://github.com/cbeust/testng-eclipse
