### ISSUE TITLE
Multiple Test Groups Causing @BeforeMethod and @AfterMethod to be called multiple times for a single test

### ISSUE THREAD

**Issue by bc-joshroe** [cbeust/testng#2152]
### TestNG Version

7.0.0

### Expected behavior
@BeforeMethod and @AfterMethod should be called once per test method.  For the example below, I would expect this output:

```
SetUp!
Test!
TearDown!
```

### Actual behavior
@BeforeMethod and @AfterMethod are being called multiple times for one test method (6 times each).  The below example has this output:

```
SetUp!
TearDown!
SetUp!
TearDown!
SetUp!
TearDown!
SetUp!
TearDown!
SetUp!
Test!
TearDown!
SetUp!
TearDown! 
```

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```
@Test(groups={"Group1", "Group2", "Group3", "Group4"})
public class TestTest {
    @BeforeMethod
    public void setUp() {
        System.out.println("SetUp!");
    }

    @AfterMethod
    public void tearDown(ITestResult result) {
        System.out.println("TearDown!");
    }

    /**
     */
    public void test1() {
        System.out.println("Test!");
    }
}
```

### Initial Analysis
It looks like ConfigInvoker.invokeBeforeGroupsConfigurations should be checking if 'filteredMethods' already contains the method before adding it on line 109.  I'm unsure what other side effects this might have though.  It is also worth noting that if you remove the groups, this will behave as expected.

**Comment by bc-joshroe** [comment]
After further review, it appears that changing the tags to:
`@BeforeMethod(inheritGroups=false)`
and
`@AfterMethod(inheritGroups=false)`
is causing it to work as expected.  Closing this issue.

**Comment by bc-joshroe** [comment]
Re-opening this issue because it looks like this workaround is only working in intellij, but not when run from Maven.

**Comment by krmahadevan** [comment]
@bc-joshroe 

TestNG by behavior ends up inheriting the groups that are mentioned at the class level via the `@Test` annotation.

This behavior (which you have also analyzed) can be turned off by setting the attribute `inheritGroups` to `false` in your `@BeforeMethod`/ `@AfterMethod` annotation. This is by default `true`

This annotation attribute works the same irrespective of whether you are running from within an IDE or via a build tool such as maven.

[github2152.zip](https://github.com/cbeust/testng/files/3694171/github2152.zip)

The attached project demonstrates this. You can either run `mvn clean test` (or) run `mvn clean test -P testng` (to run the test via a suite xml file) or from within the IDE.

The behavior is the same.

```
14:48 $ mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.rationaleemotions:github2152 >------------------
[INFO] Building github2152 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ github2152 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/krmahadevan/temp/github2152/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ github2152 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/krmahadevan/temp/github2152/target/classes
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ github2152 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ github2152 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/krmahadevan/temp/github2152/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ github2152 ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.rationaleemotions.IssueTest
SetUp!
Test!
TearDown!
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.366 s - in com.rationaleemotions.IssueTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.728 s
[INFO] Finished at: 2019-10-06T14:48:48+05:30
[INFO] ------------------------------------------------------------------------
```

output via a profile 

```
✔ ~/temp/github2152
14:49 $ mvn test -P testng
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.rationaleemotions:github2152 >------------------
[INFO] Building github2152 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ github2152 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/krmahadevan/temp/github2152/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ github2152 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ github2152 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ github2152 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ github2152 ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SetUp!
Test!
TearDown!
PASSED: test1

===============================================
    2152_test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.399 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.209 s
[INFO] Finished at: 2019-10-06T14:51:02+05:30
[INFO] ------------------------------------------------------------------------
```

**Comment by juherr** [comment]
@krmahadevan Does your answer true for #2156 too?

**Comment by krmahadevan** [comment]
@juherr - I am somehow not convinced with my own answer :)

When a user runs a test in the regular mode (that is without selecting any groups etc., which is what I am doing in my example), `inheritGroups` attribute shouldn't come into picture at all, because no filtering using groups is being involved. Yet TestNG seems to go and honor this attribute, which is kind of wrong in my opinion. What do you say ?

**Comment by juherr** [comment]
I agree with your last comment :)

I will reword it as: If a (test or configuration) method has groups (from inheritance and/or from annotation), a test selection without group should ignore groups :)

**Comment by juherr** [comment]
The issue looks really similar to #2135 too

**Comment by krmahadevan** [comment]
This is fixed via PR https://github.com/cbeust/testng/pull/2167
