### ISSUE TITLE
Value assigned to a variable in @BeforeSuite method is not reflecting properly in @Test methods 

### ISSUE THREAD

**Issue by santhanam370** [cbeust/testng#2158]
### TestNG Version
7.0

### Expected behavior

```
[testng] ...
   [testng] ... TestNG 7.0.0 by C??dric Beust (cedric@beust.com)
   [testng] ...
   [testng] 
   [testng] Dummy value before reinitializing in @BeforeSuite annoted method : Initial value
   [testng] Dummy value after reinitializing in @BeforeSuite annoted method : Reinitialized value
   [testng] Dummy value inside test method : **Reinitialized value**
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression1
   [testng]     Tests run: 1, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression2
   [testng]     Tests run: 1, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression3
   [testng]     Tests run: 1, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] Dummy value inside test method : **Reinitialized value**
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression2
   [testng]     Tests run: 2, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression3
   [testng]     Tests run: 2, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] Dummy value inside test method : Reinitialized value
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression3
   [testng]     Tests run: 3, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng] SampleTestSuite
   [testng] Total tests run: 3, Passes: 3, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
```

### Actual behavior

```
[testng] ... TestNG 7.0.0 by C??dric Beust (cedric@beust.com)
   [testng] ...
   [testng] 
   [testng] Dummy value before reinitializing in @BeforeSuite annoted method : Initial value
   [testng] Dummy value after reinitializing in @BeforeSuite annoted method : Reinitialized value
   [testng] Dummy value inside test method : Initial value
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression1
   [testng]     Tests run: 1, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression2
   [testng]     Tests run: 1, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression3
   [testng]     Tests run: 1, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] Dummy value inside test method : Initial value
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression2
   [testng]     Tests run: 2, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression3
   [testng]     Tests run: 2, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] Dummy value inside test method : Reinitialized value
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] PASSED: test1
   [testng] 
   [testng] ===============================================
   [testng]     Regression3
   [testng]     Tests run: 3, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng] SampleTestSuite
   [testng] Total tests run: 3, Passes: 3, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] 
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [X] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

**TestNG xml config:
[TestNGBugInBeforeSuite.zip](https://github.com/cbeust/testng/files/3670913/TestNGBugInBeforeSuite.zip)
**

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SampleTestSuite" verbose="2" parallel="false" thread-count="1">
    <test name="Regression1">
        <packages>
            <package name="com.sample.*"/>
        </packages>
    </test>
    <test name="Regression2">
        <packages>
            <package name="com.sample.*"/>
        </packages>
    </test>
    <test name="Regression3">
        <packages>
            <package name="com.sample.*"/>
        </packages>
    </test>
</suite>
```

**Class containing test method :**

```java
package com.sample;

import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class SampleTestNG {

    private String dummyVal = "Initial value";

    @BeforeSuite
    public void setup(){
        System.out.println("Dummy value before reinitializing in @BeforeSuite annoted method : " + dummyVal);
        dummyVal = "Reinitialized value";
        System.out.println("Dummy value after reinitializing in @BeforeSuite annoted method : " + dummyVal);
    }

    @Test
    public void test1(){
        System.out.println("Dummy value inside test method : " + dummyVal);
    }
}
```

**Comment by krmahadevan** [comment]
This is not an issue with TestNG.

TestNG is working as designed.

`@BeforeSuite` is designed to be invoked only once per `<suite>`.  Your suite xml contains three `<test>` tags. The `setup()` will get invoked for `<test name="Regression1">` and gets skipped for `<test name="Regression2">` and `<test name="Regression3">` because they are all residing in the same `<suite>` tag.

If you need the initialization to happen for every `<test>` tag, please use `@BeforeTest`

**Comment by santhanam370** [comment]
Yes, it's obvious @BeforeSuite will be executed once per suite. The problem here is, if we re-assign a value to a global variable inside @BeforeSuite method, it's not reflecting in @Test method, only at the last test case execution the value is reflected.

You can see in the above logs, I have created a variable dummyVal with value "Initial value", and then reassigning the value inside @BeforeSuite method with value "Reinitialized value". Now our expectations is, inside the @Test methods, the value of dummyVal should be "Reinitialized value". But out of execution of the test case for three times, in the first two times the value of dummyVal is "Initial value", only last execution of test case the "Reinitialized value" value is reflected.

I am able to replicate in for n times execution of test cases, the value reassigen inside @BeforeSuite is not reflecting for first (n-1) time, only in the nth time execution the correct value is reflecting

**Comment by krmahadevan** [comment]
@santhanam370 - Please do not open duplicate issues for the same problem. It doesn't help in getting the issue resolved. You can add comments to the closed issue asking that it be re-open by providing additional context.

**Comment by santhanam370** [comment]
> @santhanam370 - Please do not open duplicate issues for the same problem. It doesn't help in getting the issue resolved. You can add comments to the closed issue asking that it be re-open by providing additional context.

Yes fine, Did you got the context of the problem?

**Comment by krmahadevan** [comment]
@santhanam370 
I revisited your example. The problem is still in your test code.

The `@BeforeSuite` annotated `setup()` method will get executed ONLY once for the entire `<suite>` tag.

In your suite you have 3 `<test>` tags, each of them are trying to access the value of the variable initialised via the `@BeforeSuite`.

Your output will be 

```
Dummy value inside test method : Initial value for test <Regression1>
Dummy value inside test method : Initial value for test <Regression2>
Dummy value inside test method : Reinitialized value for test <Regression3>
```

if you alter your `@Test` method to something like this

```java
  @Test
  public void test1() {
    ITestResult result = Reporter.getCurrentTestResult();
    String testname = result.getTestContext().getName();
    System.out.println("Dummy value inside test method : " + dummyVal + " for test <" + testname + ">");
  }
```

Now to answer your question as to why does the `@BeforeSuite` get executed only for the third `<test>` tag, I believe it has got something to do with reflection.

TestNG first extracts out all of the `@BeforeSuite` methods across all the `<test>` tags, and then goes about creating instances and running the method from the instance. Its very much possible that the 3rd instance (which got created for the 3rd `<test>` tag) was where the execution happened. I don't think TestNG has any control on this nor would it be able to enforce a control.

I am going to leave this issue as open and let you decide as to what do you want to do, based on the explanation I have shared.

IMO, this is not an issue in TestNG.

**Comment by santhanam370** [comment]
@BeforeSuite methods should be executed at suite level, not at one specific instance of test case.

Could see the same point being in the TODO list in the source.

The issue is in the below quoted source. As the invoker from test runner is picked and the test runner is being iterated over, at the end of TestRunner loop, invoker will be holding the invoker object from last instance of test runner, which is causing this issue.


**org.testng.SuiteRunner**
`// Get the invoker and find all the suite level methods
    for (TestRunner tr : testRunners) {
      **// TODO: Code smell.  Invoker should belong to SuiteRunner, not TestRunner**
      // -- cbeust
      **invoker = tr.getInvoker();**

      for (ITestNGMethod m : tr.getBeforeSuiteMethods()) {
        beforeSuiteMethods.put(m.getConstructorOrMethod().getMethod(), m);
      }

      for (ITestNGMethod m : tr.getAfterSuiteMethods()) {
        afterSuiteMethods.put(m.getConstructorOrMethod().getMethod(), m);
      }
    }`

Seems to be known issue, but not highlighted in TestNG docs.

You can either close this (as it is in the TODO list) or keep it open for reference to this issue. Hoping it will be picked up in future.

**Comment by krmahadevan** [comment]
@santhanam370 - The `TODO` points to a different thing and has got nothing to do with this issue. Its basically calling out a `code smell` (which usually refers to a diluted ownership of responsibility) and is asking that the responsibility part sorted out.

This is NOT a known issue.


> @BeforeSuite methods should be executed at suite level, not at one specific instance of test case.

This is still happening. What you are expecting is that the `BeforeSuite` method associated with the first `<test>` tag get called, but the actual behavior is that the last `<test>` tag's method is getting called. I dont still understand how is this deviating from the functionality which is basically that the `@BeforeSuite` will get executed before any test methods and that guarantee is still there.
How TestNG manages this execution is something that is internal. From an end-users perspective, the `@BeforeSuite` methods need to get executed before any `@Test` methods are run.

The issue in your code is that you are just duplicating the same `<test>` tag and including the same classes in all of your test tags, so when TestNG constructs the `beforeSuite` and `afterSuite` maps (wherein the key is `java.lang.reflect.Method` object) see [here](https://github.com/cbeust/testng/blob/4fe39cd286579520f89aaf9fb973aca6a5ccb881/src/main/java/org/testng/SuiteRunner.java#L306-L312), TestNG ends up pushing in the `ITestNGMethod` object obtained from the `3rd <test>` tag. That explains why TestNG runs the `@BeforeSuite` method residing in the instance that is part of `<test>` tag.

I am entirely not sure what is your use case that you are trying to solve so I can't suggest what is the better way of doing it.

This is not an issue and is very unlikely that it would get fixed.  If you feel that this can be fixed, we encourage you to raise a PR that fixes the problem and we will be more than glad to review it and get it merged.

**Comment by santhanam370** [comment]
> The issue in your code is that you are just duplicating the same <test> tag and including the same classes in all of your test tags

The code I shared is sample of my use case, so didn't added much details unrelated to this issue. In my actual case, I am trying to run the parameterized test by repeating the test with different parameter values, for same test case and at the same time using @BeforeSuite  method to reinitialize a  global variable, and I expected that the reinitialized  value be available in all the test methods(as BeforeSuite method is executed before all the test methods).

> This is still happening. What you are expecting is that the `BeforeSuite` method associated with the first `<test>` tag get called, but the actual behavior is that the last `<test>` tag's method is getting called. I dont still understand how is this deviating from the functionality which is basically that the `@BeforeSuite` will get executed before any test methods and that guarantee is still there.

The above statement is correct, expect for one thing, my expectation is @BeforeSuite method should not be associated to any <test> tag, its scope should be across the test cases not at one particular test case. And I agree, it's being executed only once per suite, irresspective of n number of test cases.

> This is not an issue and is very unlikely that it would get fixed. If you feel that this can be fixed, we encourage you to raise a PR that fixes the problem and we will be more than glad to review it and get it merged.

Trying my best. Closing it, will reopen it If I found a way of fixing it.

Thanks for quick replies @krmahadevan

**Comment by woxiangbo** [comment]
@krmahadevan could you give some help about  https://stackoverflow.com/questions/64056680/why-testng-beforesuite-only-provide-value-for-one-class-and-other-class-get-null?noredirect=1#comment113282631_64056680 ?

In my opinion,  @BeforeSuite could do something that shared by all @test , am I right ?

**Comment by krmahadevan** [comment]
@woxiangbo - That is not the documented behavior of `@BeforeSuite` method. This annotated method is expected to be invoked only once per `<suite>` tag.

**Comment by LizGrillo** [comment]
Hi, what about @beforeClass? Im having the same problem. Im initializing a variable and adding a value inside a @beforeClass in my Base file. Then, when trying to use this variable in a method from a class which extends the Base, the variable is null.

**Comment by krmahadevan** [comment]
> Hi, what about @beforeClass? Im having the same problem. Im initializing a variable and adding a value inside a @beforeClass in my Base file. Then, when trying to use this variable in a method from a class which extends the Base, the variable is null.

I would suggest that you post your query on the TestNG-users Google groups with a sample that can show what you are trying to do.
