### ISSUE TITLE
nested exceptions not displaying in report

### ISSUE THREAD

**Issue by cjyar** [cbeust/testng#216]
Using the default TestNG setup with Gradle, if a test fails with a nested exception, only the outer exception is displayed in the test report. Often, the inner ("nested") exception has critical information for determining the cause of the error. The nested exception is contained in the stack trace in testng-reports.xml, so it seems something in the XSLT or CSS is eating that information.

**Comment by krmahadevan** [comment]
This is no longer an issue with TestNG `7.0.0-beta1`. 

The attached project can be used to reproduce (its both gradle and maven aware)

[testng216.zip](https://github.com/cbeust/testng/files/2716122/testng216.zip)

Command line output from Maven

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running test.Test1
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@11028347
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.404 sec <<< FAILURE!
noTest(test.Test1)  Time elapsed: 0.015 sec  <<< FAILURE!
java.lang.RuntimeException: Couldn't get 5
	at test.Test1.noTest(Test1.java:15)
Caused by: java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at test.Test1.noTest(Test1.java:13)
	... 34 more


Results :

Failed tests:   noTest(test.Test1): Couldn't get 5

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
