### ISSUE TITLE
Test is executed infinite number of times when the data provider returns a new object

### ISSUE THREAD

**Issue by baflQA** [cbeust/testng#2163]
### TestNG Version
7.0.0

### Expected behaviour
The test is executed 3 times

### Actual behaviour
The test is executed infinitely 

### Is the issue reproducible on a runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
https://github.com/baflQA/testNG_parallel_debug/blob/master/src/test/java/testngparallel/RetryLoop.java

The data provider returns a new object. Looks like for each data provider execution a new RetryAnalyzer object is created, and the counter is set back to 1.

**Comment by baflQA** [comment]
I just checked that the last version that it worked fine is 7.0.0-beta1.

**Comment by baflQA** [comment]
The issue was instroduced most probably somewhere there: https://github.com/cbeust/testng/commit/7d5e89d72208bc9600efe0d423298d45146d15d8

**Comment by bogvol** [comment]
the issue is still reproducable with 7.1.0 and 7.1.1 verion as well

**Comment by krmahadevan** [comment]
@bogvol - Please create a sample that can be used to reproduce the problem and file a new bug.

**Comment by bogvol** [comment]
My fault, looks like misconfiguration issue. Not able to reproduce
