### ISSUE TITLE
Breaking change of assertEquals(Object, Object) in TestNG >= 6.9.4

### ISSUE THREAD

**Issue by j-be** [cbeust/testng#2164]
### Preamble

I'm not sure whether this is actually a bug in TestNG or the expected behavior. In the latter case consider it a change/feature request.

### The issue

I am currently trying to upgrade TestNG to `7.0.0` and I found that version `6.9.4` changed the behavior of `Assert.assertEquals`.

It was: `expected.equals(actual)`
It now is: `expected.equals(actual) && actual.equals(expected)`

For us, this breaks our tests, as in some cases we get `java.sql.Timestamp` (a subclass of `java.util.Date`) from OpenJPA where we declare the type to be `java.util.Date`. Now, while `java.util.Date`'s `equals()` just compares the result of `getTime()`, `java.sql.Timestamp` reqiures `other` to be an instance of `java.sql.Timestamp`.

In TestNG up to including `6.8.21` this is no issue, as `expected` in our test is always a `java.util.Date`.

### In general

There is no requirement for `equals()` to be commutative. In addition, some frameworks just don't allow to define the actual class of a return value (like OpenJPA returning a `Timestamp` for a `Date` in the example above). And sometimes there is even just no way to forge an `expected` object, which would satisfy `actual.equals(expected)` (think of: Function returns an instance of `SomeInterface`. I can implement `SomeInterface`, but the framework's actual, internal implementation will probably check for `instanceof` itself and hence never `equal` instances my forged class).

I propose to revert `assertEquals` and restrict it to `expected.equal(acutal)`. In cases where it is really needed, the current behavior could still be acheived using `assertEquals(one, other); assertEquals(other, one)`.

### TestNG Version

All >= 6.9.4

### Test case sample

```java
Date one = new java.util.Date();
Date other = new java.sql.Timestamp(one.getTime());

Assert.assertEquals(one.getTime(), other.getTime());
Assert.assertEquals(other, one); // Fails on anyting >= 6.9.4, but succeds on 6.8.21
Assert.assertEquals(one, other); // Fails on all
```

EDIT: The commit in question seems https://github.com/cbeust/testng/commit/18788dcf8b825f4e62e3a25bd9530786172a16ec, but it does not give any motivation on why this was changed.

**Comment by juherr** [comment]
Motivation is here: https://github.com/cbeust/testng/pull/490 and seems legit.

Your need is in a bit too specific and arguable. You should look at a more powerful assert library like https://joel-costigliola.github.io/assertj/index.html but I don't know if it will manage your need.

I close the issue as it is working as expected
