### ISSUE TITLE
Null pointer exception while running testng.xml with groups tag

### ISSUE THREAD

**Issue by GirishBaliga123** [cbeust/testng#2169]
```java
package com.qa.tc;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class GroupTest {
	
		WebDriver driver;

		@BeforeMethod
		public void setUp()
		{
	      System.setProperty("webdriver.chrome.driver", "D:\\Girish\\chromedriver_win32\\chromedriver.exe");
			
			driver = new ChromeDriver();
			driver.get("https://opensource-demo.orangehrmlive.com/");
			
			driver.manage().window().maximize();
			driver.manage().deleteAllCookies();
			driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);	
		}
		
	  @Test(groups= {"Smoke"})
	  public void signIntest() 
	  {
		  driver.findElement(By.xpath("//input[@id='txtUsername']")).sendKeys("Admin");
		  driver.findElement(By.xpath("//input[@id='txtPassword']")).sendKeys("admin123");
		  driver.findElement(By.xpath("//input[@id='btnLogin']")).click();
		  System.out.println(driver.getTitle());
		  
	  }
	  
	  @AfterMethod
		 public void tearDown()
		 {
		    driver.close();
	  }
}
```

Testng xml as below

```xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name = "Sample test Suite">
   <test name = "Sample test">   
   <groups>
     <run>
       <include name = "Smoke" />
     </run>
   </groups>
      <classes>
         <class name = "com.qa.tc.GroupTest" />
      </classes>
   </test>
</suite>
```

**Comment by GirishBaliga123** [comment]
Testng.xml something like below-

<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name = "Sample test Suite">
   <test name = "Sample test">   
   <groups>
     <run>
       <include name = "Smoke" />
     </run>
   </groups>
   
      <classes>
         <class name = "com.qa.tc.GroupTest" />
      </classes>
   </test>
</suite>

**Comment by GirishBaliga123** [comment]
![testng](https://user-images.githubusercontent.com/39024454/66291892-8f99bd80-e900-11e9-962c-f7ea43d186b2.PNG)

**Comment by krmahadevan** [comment]
Is this reproducible with `7.0.0` ?

**Comment by GirishBaliga123** [comment]
@krmahadevan Yes its reproducable in 7.0.0 as i am using POM dependency
![image](https://user-images.githubusercontent.com/39024454/66292021-dab3d080-e900-11e9-930f-11ae82eae654.png)

**Comment by krmahadevan** [comment]
Can you please take out selenium from the equation and provide a sample to recreate this issue ?

**Comment by GirishBaliga123** [comment]
package com.qa.tc;

import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class SampleTest
{

	@BeforeMethod
	public void setup()
	{
		System.out.println("Running ---->setup");
	}
	
	@Test(groups= {"MyGroup"})
	public void test()
	{
		System.out.println("Running---->test");
	}
	
	@AfterMethod
	public void teardown()
	{
		System.out.println("running----->teardown");
	}
}

**Comment by krmahadevan** [comment]
The second sample you shared doesn't have anything that can trigger your NPE.

The original sample that you shared, triggers an NPE because of a problem in your code.

Your `WebDriver` instantiation is being done via the `@BeforeMethod` annotation.
But you are choosing to run tests via groups called `Smoke` to which you haven't added your `@BeforeMethod` method and you haven't added the `alwaysRun=true` attribute also. 
So your `@BeforeMethod` is not getting executed.

To fix the problem, either add `alwaysRun=true` or add `Smoke` group to your `@BeforeMethod`

**Comment by GirishBaliga123** [comment]
Thanks @krmahadevan 
It worked when used alwaysRun=true attribute in @BeforeMethod annotation

**Comment by Phoenix-Birds** [comment]
This really helped us . 
Thankyou..

**Comment by LymariVineth** [comment]
thankyou, your comment really help me
