### ISSUE TITLE
TestNG runtime error

### ISSUE THREAD

**Issue by Reshma713** [cbeust/testng#2179]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
It should read values from excel.

### Actual behavior

[RemoteTestNG] detected TestNG version 7.0.0
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Method public void parameterisation.testData(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named :  getData in class parameterisation
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:580)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:795)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
You need to fix your test code. TestNG is working as designed. You have a data provider called `testData()` which is missing the `@DataProvider` annotation.

**Comment by Reshma713** [comment]
![git](https://user-images.githubusercontent.com/52806940/67173181-5b52f080-f41a-11e9-9609-82ffacc18717.PNG

**Comment by Reshma713** [comment]
It was added previously but getting error.

**Comment by krmahadevan** [comment]
Please provide a simple standalone example that can be used to reproduce the problem.

**Comment by Reshma713** [comment]
okay.
