### ISSUE TITLE
failed case number is not calculated correctly in the emailable report

### ISSUE THREAD

**Issue by funcode** [cbeust/testng#218]
I have 12 tests, 1 of them fails. I got below in the emailable-report.html:

Methods Scenarios   # skipped       # failed
Passed  Passed
12      11          0           12

That last number should be "1" in the above example.

**Comment by krmahadevan** [comment]
Works fine in TestNG `7.3.0`

![image](https://user-images.githubusercontent.com/909773/99030990-f5448880-259b-11eb-9231-4135ead2e603.png)
