### ISSUE TITLE
Showing inconsistent result when running in Parallel Mode using retry analyser

### ISSUE THREAD

**Issue by ujjwal3687** [cbeust/testng#2183]
### TestNG Version
> When Running in non-parallel mode
![Retry_Error_Non_Parallel](https://user-images.githubusercontent.com/48007549/67747437-b6a26580-fa4e-11e9-8a95-0e090cf35538.PNG)

> When Running in parallel mode
![Retry_Error_Parallel](https://user-images.githubusercontent.com/48007549/67747438-b6a26580-fa4e-11e9-9a31-0a88ccc64883.PNG)

### Expected behavior
It should run consistently and should display same result in both parallel as well as non-parallel mode

### Actual behavior
It is showing different result in both mode.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
[Test Cases.zip](https://github.com/cbeust/testng/files/3782276/Test.Cases.zip)

**Comment by krmahadevan** [comment]
@ujjwal3687 - Couple fo things 

1. Your screenshot shows that this is from the TestNG eclipse plugin. Is that the case ? If yes, then you should be logging a bug with the TestNG eclipse project [here](https://github.com/cbeust/testng-eclipse)
2. The attached project shows that you are using `6.14.3`. Please update to using `7.0.0` which is the latest released version of TestNG. If its still reproducible with `7.0.0` via the command line or via a build tool such as gradle/maven then please create a simple standalone test project which can be used to reproduce the problem (You seem to have attached a complete project which contains a lot of other stuff including selenium)

**Comment by ujjwal3687** [comment]
Hi,

This is the issue not related to either TestNG or Maven. This issue is
coming to both ways if i execute the code either through build tool such as
Maven or through TestNG showing same issue.

It's not related to 6.14.3 version even i cross verified with 7.0.0,
showing same error.

Kindly provide proper solution if you have.

**Comment by krmahadevan** [comment]
@ujjwal3687 - Then please share a simple standalone test project which can be used to reproduce the problem (Please dont include any 3rd party libs apart from TestNG)

**Comment by krmahadevan** [comment]
No response from user. Closing this issue.

If this is a problem please share a sample that can be used to reproduce the problem and we can get this issue re-opened again.
