### ISSUE TITLE
thread blocking in testng reporters

### ISSUE THREAD

**Issue by bahty** [cbeust/testng#219]
I have created a small test case to measure performance of certain introspection logic. The test case is defined with 20000 invocations (only 1 thread). The execution takes less than 20 seconds, however after execution the testng process is still hanging with blocked threads in TestNG reporters. 

The result from jstack: 
"main" cpu=366812.50 [reset 366812.50] ms allocated=50152969584 B (46.71 GB) [reset 50152969584 B (4
6.71 GB)] defined_classes=1367
io= file i/o: 6513525/17297792 B, net i/o: 0/23601286 B, files opened:40, socks opened:3  [reset fil
e i/o: 6513525/17297792 B, net i/o: 0/23601286 B, files opened:40, socks opened:3 ]
prio=6 tid=0x0000000001cae2b0 nid=0x1d0 runnable  [_thread_blocked (_call_back), stack(0x00000000020
90000,0x0000000002190000)] [0x000000000218f000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;(HashMap.jav
a:385)
        at java.util.HashSet.add(Ljava/lang/Object;)Z(HashSet.java:200)
        at org.testng.internal.ResultMap.getResults(Lorg/testng/ITestNGMethod;)Ljava/util/Set;(Resul
tMap.java:32)
        at org.testng.reporters.EmailableReporter.resultDetail(Lorg/testng/IResultMap;)V(EmailableRe
porter.java:228)
        at org.testng.reporters.EmailableReporter.generateMethodDetailReport(Ljava/util/List;)V(Emai
lableReporter.java:123)
        at org.testng.reporters.EmailableReporter.generateReport(Ljava/util/List;Ljava/util/List;Lja
va/lang/String;)V(EmailableReporter.java:69)
        at org.testng.TestNG.generateReports(Ljava/util/List;)V(TestNG.java:1080)
        at org.testng.TestNG.run()V(TestNG.java:1039)
        at org.testng.remote.RemoteTestNG.run()V(RemoteTestNG.java:109)
        at org.testng.remote.RemoteTestNG.initAndRun([Ljava/lang/String;Lorg/testng/CommandLineArgs;
Lorg/testng/remote/RemoteArgs;)V(RemoteTestNG.java:202)
        at org.testng.remote.RemoteTestNG.main([Ljava/lang/String;)V(RemoteTestNG.java:173)

The output from testng: 
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@214a7a12: 1910 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter@dfa6d18: 400446 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@7ab7b3f9: 4798 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@7eb1cc87: 2422 ms
[TestNG] Time taken by [TestListenerAdapter] Passed:0 Failed:0 Skipped:0]: 0 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@755c62bc: 12783 ms

As you can see EmailableReporter took 400 seconds to prepare the report. 

Thanks
Bahty

**Comment by krmahadevan** [comment]
Attempted at reproducing this issue using below sample.

```java

import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import org.testng.Reporter;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class SampleTestClass {

  private final Random random = new Random();
  private final AtomicInteger counter = new AtomicInteger(1);
  private static final int SIZE = 65000;

  @Test(dataProvider = "dp", invocationCount = 10)
  public void testMethod(boolean flag) throws InterruptedException {
    TimeUnit.MILLISECONDS.sleep(random.nextInt(50));
    Reporter.log("Running iteration [" + counter.getAndIncrement() + "]", true);
  }

  @DataProvider(name = "dp", parallel = true)
  public Object[][] getData() {
    Object[][] result = new Object[SIZE][1];
    for (int i = 0; i < SIZE; i++) {
      result[i][0] = random.nextBoolean();
    }
    return result;
  }
}
```

Here's the time taken by the reporter

```
[Utils] [INFO] [TestNG] Time taken by org.testng.reporters.JUnitReportReporter@6eebc39e: 10735 ms [ 10 seconds ]
[Utils] [INFO] [TestNG] Time taken by org.testng.reporters.jq.Main@617faa95: 123514 ms [ 120 seconds ]
[Utils] [INFO] [TestNG] Time taken by org.testng.reporters.XMLReporter@544fe44c: 46312 ms [46 seconds ]
[Utils] [INFO] [TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 1 ms
[Utils] [INFO] [TestNG] Time taken by org.testng.internal.ExitCodeListener@31610302: 0 ms
[Utils] [INFO] [TestNG] Time taken by org.testng.reporters.EmailableReporter2@13a5fe33: 14371 ms [14 seconds ]
```
