### ISSUE TITLE
FAIL "disables loading DTD from unsecured Urls" is reported when XML file need load local files

### ISSUE THREAD

**Issue by xirs** [cbeust/testng#2193]
### TestNG Version
> Note: only the latest version is supported
7.0.0

### Expected behavior
My suite XML file is as below:
[https://github.com/cbeust/testng/files/3849970/00_simple_s3.txt](url)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd"
        [<!ENTITY raw_listeners SYSTEM "testng/_listener/raw_listeners_no_compact.xml">]>
<suite name = "OSS Simple Test" configfailurepolicy = "continue">
    <test name = "Simple upload and download" preserve-order = "true">
        <classes>
            <class name = "com.jcloud.test.jss.object.s3.HttpOnlyTest"/>
        </classes>
    </test>
    &raw_listeners;
</suite>
```

when I run this suite file with TestNG7.0, it is always report " TestNG by default disables loading DTD from unsecured Urls. If you need to explicitly load the DTD from a http url, please do so by using the JVM argument [-Dtestng.dtd.http=true"

I debug it and find the Parser report FAIL when met `<!ENTITY raw_listeners SYSTEM "testng/_listener/raw_listeners_no_compact.xml">`, especially "testng/_listener/raw_listeners_no_compact.xml"

### Actual behavior
HTTPS is needed is introduced in pull request #2023
but it should not report FAIL (disables loading DTD from unsecured Urls) when XML file need load local files

### Is the issue reproductible on runner?
100% reproductible

- [ ] Shell
- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by Harendra-Pal** [comment]
Right Click on the class, select Run--> Run configuration
By default one testNg class will be generated with same class name under testng option
Select that class and go to Arguments tab
In the VM arguments provide -Dtestng.dtd.http=true

**Comment by Satyabrata4957** [comment]
@Harendra-Pal by doing so i am getting this error "Error: Could not find or load main class Dtestng.dtd.http=true"

Can you please tell me what is the exact issue and how to fix this !

**Comment by Satyabrata4957** [comment]
@krmahadevan could you please help me with this!

**Comment by krmahadevan** [comment]
@Satyabrata4957 JVM arguments should begin with `-D`. Please set the JVM argument properly

**Comment by Satyabrata4957** [comment]
thanks @krmahadevan you always help on time :)

**Comment by gvasanka** [comment]
@krmahadevan I am observing the same issue with below config
`<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="Test API" configfailurepolicy="continue">`

I tried -Dtestng.dtd.http=true and it works. But what should be the permanent solution here? Should TestNg host the dtd file with https or as individuals should we manged our own dtd file.

Can somebody please explain, am I missing something here.

**Comment by krmahadevan** [comment]
@gvasanka make sure you are on `7.3.0` and add `https` to your dtd url in suite file. That should suffice.

**Comment by gvasanka** [comment]
@krmahadevan  Thank you for the answer. I did try your solution. But I am getting the same error when trying to run on InteliJ

Error:
`org.testng.TestNGException: 
TestNG by default disables loading DTD from unsecured Urls. If you need to explicitly load the DTD from a http url, please do so by using the JVM argument [-Dtestng.dtd.http=true]
	at org.testng.xml.TestNGContentHandler.resolveEntity(TestNGContentHandler.java:115)
	at org.apache.xerces.util.EntityResolverWrapper.resolveEntity(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
`

Using TestNG 7.3.0
` 
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.3.0</version>
            <scope>test</scope>
        </dependency>`

and Suite XML as below
`<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="API API" configfailurepolicy="continue">
    <test name="List Service Complete">
        <classes>
            <class name="jmeter.test.RestUtilTestExecutor" />
        </classes>
    </test>
</suite>
`
Any input?

**Comment by krmahadevan** [comment]
@gvasanka - If you right click on a TestNG suite xml file that has the `https` and if you are on TestNG `7.3.0` you will not see this error on IntelliJ.

The only way in which this will come up is when you are right clicking on a individual class and then trying to run it as a TestNG test (In this case IntelliJ ends up creating an on the fly suite xml file, which doesn't have the `https` in it and hence this error). To fix this permanently only for IntelliJ, you can go ahead and add `-Dtestng.dtd.http=true` in the default configuration

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/909773/92406579-fc8f8600-f155-11ea-8d4a-59783767e072.png">

I had sometime back filed a bug in IntelliJ to fix this discrepancy as well https://youtrack.jetbrains.com/issue/IDEA-234765

**Comment by EmilianoRod** [comment]
I found a solution for me, I hope it works for you, you just have to change 
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
by the following
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
just change http to https, compile and test, good luck!

**Comment by gvasanka** [comment]
@EmilianoRod  I already had the https but getting issue when trying to run on IDE

But @krmahadevan last answer solved my issue.

**Comment by StanislavIvanovQA** [comment]
Got this issue in my old project with
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
in testng.xml
which was fine some months ago. Now I need to add "-Dtestng.dtd.http=true" again in the Intelij testng template.
What is the proper solution for this issue?

**Comment by juherr** [comment]
@StanislavIvanovQA Use the https url into your `testng.xml` file.
