### ISSUE TITLE
Allow users to provide their own Injector for Dependency Injection

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2199]
### TestNG Version
> Note: only the latest version is supported

7.0.0

### Expected behavior
User should be able to plug-in their own `Injector` variant when working with the DI support in TestNG.

### Actual behavior

Currently TestNG is hard wired to only rely on `Guice.createInjector()` for creation of `Injector`

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Refer https://stackoverflow.com/questions/59091590/how-to-inject-dependecies-using-governator-within-testng-test-cases for more elaborate details

**Comment by eljaiek** [comment]
Hi @krmahadevan thanks for your help. Do you know when next TestNG version is going to be released ?
