### ISSUE TITLE
DTD is missing from testng.org domain

### ISSUE THREAD

**Issue by ghenadied** [cbeust/testng#2202]
Hi,

Since Nov 30, the DTD file is missing from it's location: https://testng.org/testng-1.0.dtd

### TestNG Version
7

### Actual behavior
   [testng] [TestNG] [ERROR] java.io.FileNotFoundException: https://testng.org/testng-1.0.dtd
   [testng] Exception in thread "main" java.lang.NullPointerException
   [testng] 	at org.testng.TestNG.getStatus(TestNG.java:206)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1300)
   [testng] The tests failed.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Comment by Drimix20** [comment]
Probably because of "Website is down" - https://github.com/cbeust/testng/issues/2203#issue-531027540

**Comment by gfioretti** [comment]
I removed the `SYSTEM "https://testng.org/testng-1.0.dtd" ` portion from the xml file and the error is gone. Not sure if this is a sustainable solution but at least gave me and my team a quick workaround on the issue.

**Comment by juherr** [comment]
The DTD file is back.
