### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by devtester-ro** [cbeust/testng#2203]
Hi,
 Can you please verify why the website is down?
Thanks,
Iulian

**Comment by cbeust** [comment]
I filed a ticket with my provider.

**Comment by benken-parasoft** [comment]
Any alternative location to download releases?
The p2 repository for the Eclipse plugin was also hosted there so no one can get that either.

**Comment by cbeust** [comment]
http://testng.org should be back up (the https site will follow shortly).

If this doesn't work for you right away, open an incognito window and try again.

**Comment by benken-parasoft** [comment]
> http://testng.org should be back up (the https site will follow shortly).

http version doesn't seem to work (404s).  I also tried flushing DNS cache but that didn't help either.  Some evidence:

```
$ telnet testng.org 80
Trying 205.186.183.235...
Connected to testng.org.
Escape character is '^]'.
GET /doc/download.html HTTP/1.1
Host: testng.org

HTTP/1.1 404 Not Found
Date: Wed, 04 Dec 2019 00:18:30 GMT
Server: Apache/2.4.39
Content-Length: 282
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /doc/download.html was not found on this server.</p>
<hr>
<address>Apache/2.4.39 Server at testng.org Port 80</address>
</body></html>
```

**Comment by cbeust** [comment]
The DNS change might not have propagated to you yet. Here is what it should look like:

```
$ dig www.testng.org +noall +answer

; <<>> DiG 9.10.6 <<>> www.testng.org +noall +answer
;; global options: +cmd
www.testng.org.		17105	IN	A	185.199.108.153
```

If you're getting a different IP, you're still using the old cached value, which should go away within 24 hours. Please report back here then.

**Comment by benken-parasoft** [comment]
http://beust.com/eclipse returns a 404.

> Any alternative location to download releases?

To answer my own question, it looks like I can go to bintray.  For example:
http://dl.bintray.com/testng-team/testng-eclipse-release/

**Comment by cbeust** [comment]
Yes, and that's probably going to become the default site for Eclipse. More information on this once I have resolved the issue.

/cc @missedone @juherr @krmahadevan

**Comment by missedone** [comment]
@cbeust if you decide use bintray as the default site for testng eclipse plugin, we need to update the docs.
pls let me know.
