### ISSUE TITLE
Has TestNG 7.1.0 been actually released?

### ISSUE THREAD

**Issue by akarnokd** [cbeust/testng#2204]
### TestNG Version
7.1.0

### Expected behavior
Available at https://repo.maven.apache.org/maven2/org/testng/testng/7.1.0

### Actual behavior
Not available at https://repo.maven.apache.org/maven2/org/testng/testng/7.1.0
I'm using Dependabot which detected a new version in https://oss.jfrog.org/artifactory/libs-snapshot/org/testng/testng/7.1.0/

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

https://github.com/ReactiveX/RxJava/pull/6751
We don't have a `repository` entry pointing to jfrog so not sure how Dependabot found 7.1.0

**Comment by cbeust** [comment]
Not yet, we are testing the release before announcing it. There might be another revision coming. Please don't use 7.1.0 just yet.
