### ISSUE TITLE
Define what is new and released in 7.0 and 7.1.0

### ISSUE THREAD

**Issue by KroArtem** [cbeust/testng#2205]
Please define what's new and improved in version 7.0 and what was added in 7.1.0

All I managed to find is a topic in google-groups that contains some information about what's new. https://groups.google.com/forum/#!topic/testng-users/elein1RwVTo

[Changelog](
https://github.com/cbeust/testng/blob/master/CHANGES.txt) in repository is not user-friendly and doesn't reflect divide changes that were made in 7.1.0 and 7.0

### TestNG Version
7.0/7.1.0

**Comment by krmahadevan** [comment]
@KroArtem - There was an email sent to the group explaining what all was added to `7.0.0`.

Refer here : https://groups.google.com/forum/#!topic/testng-users/HKujuefBhXA

> Changelog in repository is not user-friendly and doesn't reflect divide changes that were made in 7.1.0 and 7.0

Can you please me understand what this means ? The change log clearly lists out all of the github issues that were fixed in every release. What more is being expected here ?

ping @juherr @cbeust

**Comment by KroArtem** [comment]
@krmahadevan , thanks for the link! I was a bit naive and just opened the website: no changelog.

Then I've opened github releases and there were no changes too: https://github.com/cbeust/testng/releases/tag/7.0.0

After that I've googled `what's new in testng 7.0` and found the link from my original post.

Lastly I've opened https://github.com/cbeust/testng/blob/master/CHANGES.txt and it's not clear when changes in 7.0 finished and 7.1 changes started. (as there is no divider like it was for 6.14.3 and previous releases).

I do understand you have not so many contributors to support website/write news/articles but for people who are not working very tightly with testng it's not clear whether I need to fix deprecations after moving to 7.0 and what other good things could be used.

**Comment by krmahadevan** [comment]
@KroArtem 

> Lastly I've opened https://github.com/cbeust/testng/blob/master/CHANGES.txt and it's not clear when changes in 7.0 finished and 7.1 changes started. (as there is no divider like it was for 6.14.3 and previous releases).

I have now fixed it. Please check now [here](https://github.com/cbeust/testng/blob/master/CHANGES.txt#L19)

> I do understand you have not so many contributors to support website/write news/articles 

Thanks for the understanding.

> but for people who are not working very tightly with testng it's not clear whether I need to fix deprecations after moving to 7.0 and what other good things could be used.

So what do you suggest we do? We are open to suggestions. The release notes like the earlier link I shared is one of the ways. What other ways can you suggest.

@cbeust / @juherr 

Can you please help with doing this : https://help.github.com/en/github/administering-a-repository/automation-for-release-forms-with-query-parameters

**Comment by KroArtem** [comment]
@krmahadevan , a message on the site/google groups is ok as you've done for 7.0 release

The only problem is that I didn't find those message via google.

**Comment by krmahadevan** [comment]
@KroArtem - I have now added a link to the release notes into the `README.md` file on the repository itself. See [here](https://github.com/cbeust/testng#release-notes)

If you are fine with this, we can perhaps close this issue.

Thanks for calling out an important aspect :) Appreciate it.

**Comment by KroArtem** [comment]
@krmahadevan , one more thing, it seems like 7.1.0 is already released or is it an RC or beta? If it's a release then one more announcement in google-groups is needed. :)

Otherwise this issue can be closed, thanks for your quick answers.

**Comment by krmahadevan** [comment]
@KroArtem - No its not an official release "yet". It should get into a beta release. For minor releases I am not sure if a google groups announcement detailing all the features in it would be done. But if its done, I will add the release notes back to the repository. If not, the changes.txt will be updated properly on a per version basis.

Closing this issue for now.
