### ISSUE TITLE
Dependency injector factory can't be configured via Maven surefire plugin

### ISSUE THREAD

**Issue by dmikhievich** [cbeust/testng#2207]
### TestNG Version
org.testng:testng:7.1.0

### Expected behavior
If the custom implementation class of `org.testng.IInjectorFactory` is passed via configuration properties of Maven surefire plugin it should be applied to executable tests.

### Actual behavior
Specified configuration option is ignored.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Sample of Surefire plugin definition:
 ```  
          <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <properties>
                        <property>
                            <name>dependencyinjectorfactory</name>
                            <value>customimplementationclass</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
```

**Comment by krmahadevan** [comment]
@dmikhievich - What is the error that you get ?
Also can you please help share a simple standalone full fledge example that can be used to reproduce the problem ?

I also believe that `7.1.0` perhaps had some issues and was to be regarded as a bad build.

@cbeust - Please confirm.

**Comment by dmikhievich** [comment]
> @dmikhievich - What is the error that you get ?
> Also can you please help share a simple standalone full fledge example that can be used to reproduce the problem ?
> 
> I also believe that `7.1.0` perhaps had some issues and was to be regarded as a bad build.
> 
> @cbeust - Please confirm.

**Comment by dmikhievich** [comment]
@krmahadevan we've tried to integrate [Governator|https://github.com/Netflix/governator] with TestNG and found out that running test suite ignores the implementation specified via `dependencyinjectorfactory` and uses the default one (via Guice). This feature (specification of custom `IInjectorFactory` instance) is very important for us, so I've created a PR with fix. Could you please take a look?
