### ISSUE TITLE
testng 7.1.0 java.lang.ClassNotFoundException: com.google.inject.Stage

### ISSUE THREAD

**Issue by missedone** [cbeust/testng#2223]
### TestNG Version
TestNG 7.1.0

### Actual behavior

the testng-remote integration test failed
https://travis-ci.org/testng-team/testng-remote/jobs/481901771

```
[RemoteTestNG] revisions:
	git.commit.id=32c8977
	git.branch=32c8977911e409c8c8c2d4bce973e94d2acf5ca7
	git.build.version=1.4.1-SNAPSHOT
[RemoteTestNG] loaded class org.testng.internal.Version at file:/home/travis/.groovy/grapes/org.testng/testng/jars/testng-7.1.0.jar
[RemoteTestNG] detected TestNG version 7.1.0
Caught: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
	at org.testng.remote.RemoteTestNG$main.call(Unknown Source)
	at TestNGTest.run(TestNGTest.groovy:49)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	... 9 more
[BaseMessageSender] Stopped receiver
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
https://github.com/testng-team/testng-remote/blob/master/remote-test/src/test/groovy/Tester.groovy

**Comment by krmahadevan** [comment]
@missedone 

In [7.0.0 pom](http://repo1.maven.org/maven2/org/testng/testng/7.0.0/testng-7.0.0.pom) below was the dependency information on guice

```xml
<dependency>
    <groupId>com.google.inject</groupId>
    <artifactId>guice</artifactId>
    <version>4.1.0</version>
    <classifier>no_aop</classifier>
    <scope>provided</scope>
</dependency>
```

In [7.1.0 pom](http://repo1.maven.org/maven2/org/testng/testng/7.1.0/testng-7.1.0.pom) below was the dependency information on guice

```xml
<dependency>
    <groupId>com.google.inject</groupId>
    <artifactId>guice</artifactId>
    <version>4.1.0</version>
    <classifier>no_aop</classifier>
    <scope>compile</scope>
</dependency>```


So perhaps this issue is because guice became a compile time dependency from being a provided dependency ?

**Comment by cbeust** [comment]
Doubtful. The dependency is harder now than it was before.

Note that the error is `NoClassDefFound`, not `ClassNotFound`. Guice is missing a dependency, it seems.

**Comment by liry** [comment]
Making `guice` compile time dependency seems to me as a wrong direction. And BTW, it's not backward compatible, so such a change should be in major version only.

**Comment by cbeust** [comment]
It is [api only](https://github.com/cbeust/testng/blob/master/build.gradle.kts#L68-L70) though.

If the `pom.xml` was generated as `compile`, this looks like a bug in Gradle(?).

**Comment by liry** [comment]
Well, maven (i.e. `pom.xml`) doesn't have "api only" scope. It's needed for compilation and it's being exposed by api -> `compile` scope.

BTW, what will happen, if I have `guice` required in the project in different incompatible version? Is it backward compatible?

**Comment by missedone** [comment]
Guice is compile time dependency: https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/Configuration.java#L33

so it's hard dependency

**Comment by rahulmogar** [comment]
please remove the jar file from the build path and install TestNG from help menu(install software) 
worked for me

**Comment by SantiBailors0** [comment]
Eclipse IDE for Java Developers, Version: 2019-12 (4.14.0), Build id: 20191212-1212.
TestNG 7.1.0.r202001120626

Removing the TestNG library from the build path of the project containing the test and installing TestNG from menu Help / Install New Software did not work for me, I kept getting this error.

What worked for me was downloading guice-4.2.2.jar (from https://github.com/google/guice/wiki/Guice422), copying it into any folder, and adding it to the build path of the project as external JAR.

**Comment by gauravpratap01** [comment]
> please remove the jar file from the build path and install TestNG from help menu(install software)
> worked for me

Can you please provide me the link to install plugin from "Install new software"

**Comment by bharathkjv** [comment]
> > please remove the jar file from the build path and install TestNG from help menu(install software)
> > worked for me
> 
> Can you please provide me the link to install plugin from "Install new software"

From Eclipse, Go to Help > Install software or You can install from market place as well (Help > Market Place). After installing TestNG from market place, it dint work, but installing the GUICE422.jar to the build path worked for me

**Comment by nixlend** [comment]
> Eclipse IDE for Java Developers, Version: 2019-12 (4.14.0), Build id: 20191212-1212.
> TestNG 7.1.0.r202001120626
> 
> Removing the TestNG library from the build path of the project containing the test and installing TestNG from menu Help / Install New Software did not work for me, I kept getting this error.
> 
> What worked for me was downloading guice-4.2.2.jar (from https://github.com/google/guice/wiki/Guice422), copying it into any folder, and adding it to the build path of the project as external JAR.

That is the only way that works for me as well, and the weirdest thing was TestNG version 7.0.1 was displayed in the console regardless of the TestNG version that I installed was 7.1.1. Anyway it works now.

**Comment by yaminikb** [comment]
@krmahadevan We need this fix, when is the next release of TestNG?

**Comment by krmahadevan** [comment]
@yaminikb - The release should be out soon (in a week or so).

**Comment by SantiBailors0** [comment]
JFI, my TestNG apparently has just updated, to 7.1.1.202003100345, but if I remove from the build path the Guice JAR that I had to add manually to avoid the NoClassDefFoundError, the error reappears.

So for me today's update made zero difference, besides the fact that now I can't tell for sure which TestNG version I have: expanding the TestNG node in Package Explorer says 7.1.0.r202001120626 (which is the same I already had since long before today's update), and under C:\eclipse\plugins, besides the 7.1.**0**.* JARs that I already had, I now also have two 7.1.**1**.* JARs which, as I mentioned, don't seem to be used.
But the bottom line is that for me this update did not affect the NoClassDefFoundError: the Guice JAR on the build path as an external JAR is still necessary for me.

**Comment by missedone** [comment]
The eclipse plugin update is not to fix this issue. Still need to wait for the new testng release .

**Comment by mlook172** [comment]
How to downgrade  to version 7.0.?

**Comment by mlook172** [comment]
[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more


I faced this issue kindly advice..

**Comment by missedone** [comment]
@mlook172 , you can try to install the beta build in your eclipse: 
"Help -> Install New Software.. -> paste the below update site url into `Work with:` field"
https://dl.bintray.com/testng-team/testng-p2/updatesites/7.2.0.b202003151750/

**Comment by mlook172** [comment]
its working fine now

thanks

**Comment by nixlend** [comment]
7.2.0.r202003151902 has fixed the issue, thank you!

**Comment by mlook172** [comment]
thanks a lot

في الثلاثاء، ١٧ مارس، ٢٠٢٠ ١١:٢٤ م Nicholas Lee <notifications@github.com>
كتب:

**Comment by zehrabatool** [comment]
Works for me as well. Thanks !

**Comment by subhashri1207** [comment]
I also faced the same issue. Thank you. It's working for me now

**Comment by twinki1624** [comment]
> Eclipse IDE for Java Developers, Version: 2019-12 (4.14.0), Build id: 20191212-1212.
> TestNG 7.1.0.r202001120626
> 
> Removing the TestNG library from the build path of the project containing the test and installing TestNG from menu Help / Install New Software did not work for me, I kept getting this error.
> 
> What worked for me was downloading guice-4.2.2.jar (from https://github.com/google/guice/wiki/Guice422), copying it into any folder, and adding it to the build path of the project as external JAR.

It did excuse the error. But all the test cases are skipping/ failing on introducing guice.jar
![image](https://user-images.githubusercontent.com/37446081/79283263-eea24580-7ed4-11ea-87f3-9bc3113bfd87.png)

**Comment by missedone** [comment]
@twinki1624 , could you try with my comment: https://github.com/cbeust/testng-eclipse/issues/472#issuecomment-599251156

**Comment by twinki1624** [comment]
> @twinki1624 , could you try with my comment: [cbeust/testng-eclipse#472 (comment)](https://github.com/cbeust/testng-eclipse/issues/472#issuecomment-599251156)

Unfortunately, it's still now working. 
![image](https://user-images.githubusercontent.com/37446081/79284585-b7359800-7ed8-11ea-9a6c-c06361af8d0e.png)

Can you guide me through any other steps? I'm in the mid of a project, need it to be resolved at the earliest.

**Comment by missedone** [comment]
@twinki1624 , for this DTD https url issue, pls update testng eclipse plugin to latest update site: https://dl.bintray.com/testng-team/testng-eclipse-release

**Comment by twinki1624** [comment]
> @twinki1624 , for this DTD https url issue, pls update testng eclipse plugin to latest update site: https://dl.bintray.com/testng-team/testng-eclipse-release

I tried it using the above link, help>install new software,it's not getting installed.
![image](https://user-images.githubusercontent.com/37446081/79309573-241c5280-7f18-11ea-810d-4e32a46eb922.png)

**Comment by kportner** [comment]
Any movement on this?  I"m seeing the same issue.

Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage

**Comment by SantiBailors** [comment]
> Any movement on this? I'm seeing the same issue.
Your version is probably not up to date, the problem was fixed with 7.2.0.r202003151902

**Comment by kukreja1980** [comment]
Install TestNG 7.1 and then install P2 libraries from TestNG 7.2
"Help -> Install New Software.. -> paste the below url Work with: field"
 https://dl.bintray.com/testng-team/testng-eclipse-release/
Eclipse is restarted, then again:
"Help -> Install New Software.. -> 
https://dl.bintray.com/testng-team/testng-p2-release/

**Comment by Geethu2593-GIT** [comment]
I'm also facing the same issue. I tried all the above solutions nothing worked for me

[RemoteTestNG] detected TestNG version 7.0.0
Exception in thread "main" java.lang.NoSuchMethodError: org.testng.TestNG.configure(Lorg/testng/CommandLineArgs;)V
at org.testng.remote.AbstractRemoteTestNG.configure(AbstractRemoteTestNG.java:75)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:235)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

I tried to match all the verion plugin and testng jar

For testNG p2- i used this urlhttps://dl.bintray.com/testng-team/testng-p2-release/7.0.0/

Can someone please help me here

**Comment by SantiBailors** [comment]
It's not the same issue, you have a NoSuchMethodError, not a NoClassDefFoundError. Look up the causes of NoSuchMethodError. A JAR *is* found in your case but you probably have some version mismatch, maybe an old guice.jar. 
As first thing I would uninstall TestNG and do a full reinstallation of the latest version, especially if you have been trying different workarounds.

**Comment by Geethu2593-GIT** [comment]
I also, tried that, uninstalled the TestNG and reinstalled the latest version, it didnt work.

then again i uninstalled the latest version an installed TestNG7.0.0 just to maintain same versions for jar file and plugin.

Although I'm not sure if that should be the case,

**Comment by SantiBailors** [comment]
I don't know how it didn't work so it's difficult to say much, but if you mean that you got the NoSuchMethodError even from a clean reinstallation I would be surprised. Anyway, based on what is known, if it was me I would install another Eclipse in a separate folder (it won't interfere with the existing Eclipse installation), making sure it's the latest Eclipse, then install TestNG there, via marketplace or update site URL. If it still gives the NoSuchMethodError it would be really strange.

**Comment by Geethu2593-GIT** [comment]
I already tried everything on brand new stuff, but once again i will try the same thing, may be I'm missing some key thing. 

Also, I copied my previous pom.xml file(dependencies only) in the new one, as it has many jars that are required in my project. may be that could be the reason too.. 

once again thank you @SantiBailors

**Comment by sujaniw-spec** [comment]
Removed TestNG jar file from the build path and add the following dependency to the POM.
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.1.0</version>
    <scope>test</scope>
</dependency>

It worked for me.

**Comment by vinayhegde2013** [comment]
@SantiBailors0  You saved my day after wasting 3-4 hrs to find the right answer. Adding a dependency of GUICE4.2.2 is working like charm. Thanks man
