### ISSUE TITLE
Where is the outputted jar file after running ./build-with-gradle?

### ISSUE THREAD

**Issue by edelauna** [cbeust/testng#2234]
### TestNG Version
7.1.1
> Note: only the latest version is supported

### Expected behavior
./target/testng.jar available after running ./build-with-gradle

### Actual behavior
jar file not found

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ x ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Performed the following:
$ git clone git://github.com/cbeust/testng.git
$ cd testng
$ ./build-with-gradle

Terminal output: BUILD SUCCESSFUL in 5m 28s
9 actionable tasks: 8 executed, 1 up-to-date

Publishing build scan...

I can't locate the jar file, even after creating directory `./target/`

Infrastructure
-- | -- | --
Operating system | Windows 7 6.1 |  
CPU cores | 8 cores |  
Max Gradle workers | 8 workers |  
Java runtime | Oracle Java(TM) SE Runtime Environment 1.8.0_201-b09 |  
Java VM | Oracle Java HotSpot(TM) 64-Bit Server VM 25.201-b09 (mixed mode) |  
Max JVM memory heap size | 503 MB |  
Locale | English (United States) |  
Default charset | windows-1252

**Comment by krmahadevan** [comment]
The jar is available in `$project/build/libs/` directory.

Here `$directory` represents the TestNG base directory. Read more [here](https://mkyong.com/gradle/gradle-create-a-jar-file-with-dependencies/)
