### ISSUE TITLE
TestNG 7.0.0 not working Asserts, Tags annotations, listeners

### ISSUE THREAD

**Issue by r4f431007** [cbeust/testng#2242]
### TestNG Version
7.0.0

### Expected behavior
previous versions were working normally

### Actual behavior
Not working

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
![image](https://user-images.githubusercontent.com/31752413/73962534-9fd89e00-48dc-11ea-804c-aee54a300b5b.png)

**Comment by krmahadevan** [comment]
The latest released version of TestNG is `7.1.0` Please try again using that. From the screenshot it looks like you have a messed up CLASSPATH

If you are still experiencing the same issue using `7.1.0` Please create a sample that can be used to demonstrate the problem and comment back.

If you are experiencing this problem only when you import the project within eclipse (but the same works fine when you run from Maven command line), please create an issue in https://github.com/cbeust/testng-eclipse/issues.

**Comment by r4f431007** [comment]
Fixed. I've changed to Eclipse 2018-09 (4.9) and it's working.
