### ISSUE TITLE
Not abstract super-classes mess up test run order

### ISSUE THREAD

**Issue by sergejjkim** [cbeust/testng#2249]
### TestNG Version
7.1.0

### Description
So i have classes A, BA, BB, BC and C 
Classes A, BA, BB and C have tests in them (2 tests per class test1 and test2)
and Class BC doesn't
Classes BA and BB inherit class BC 

So when i run my tests i expect tests order be like this

### Expected behavior

A.test1
A.test2
BA.test1
BA.test2
BB.test1
BB.test2
C.test1
C.test2

### Actual behavior

A.test1
C.test1
C.test2
A.test2
BA.test1
BA.test2
BB.test1
BB.test2

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Root cause
so the reason for that seems to be the following:
`DynamicGraphHelper.createClassDependencies()` looks like this

```java
 private static ListMultiMap<ITestNGMethod, ITestNGMethod> createClassDependencies(
      ITestNGMethod[] methods, XmlTest test) {
    Map<String, List<ITestNGMethod>> classes = Maps.newHashMap();
    // Note: use a List here to preserve the ordering but make sure
    // we don't add the same class twice
    List<XmlClass> sortedClasses = Lists.newArrayList();
    for (XmlClass c : test.getXmlClasses()) {    <--------------this gets all the classes even without test methods
      classes.put(c.getName(), new ArrayList<>());
      if (!sortedClasses.contains(c)) {
        sortedClasses.add(c);
      }
    }
```

and then later same method does the following

```java
 for (ITestNGMethod m : methods) {
      String name = m.getTestClass().getName();
      Integer index = indexedClasses1.get(name);
      // The index could be null if the classes listed in the XML are different
      // from the methods being run (e.g. the .xml only contains a factory that
      // instantiates methods from a different class). In this case, we cannot
      // perform any ordering.
      if (index != null && index > 0) {
        // Make this method depend on all the methods of the class in the previous
        // index
        String classDependedUpon = indexedClasses2.get(index - 1);
        List<ITestNGMethod> methodsDependedUpon = methodsFromClass.get(classDependedUpon);   <---------------when class with no tests methods appear hear, the methods of that suppose to depend on those depend on nothing
        for (ITestNGMethod mdu : methodsDependedUpon) {
          result.put(mdu, m);
        }
      }
    }
```
so test methods of class C which goes after class BC which has no test methods are considered not depending on anything and later when TestRunner.privateRun() calls graph.getFreeNodes() it gets A.test1 and all the C class test methods.

There is a simple solution to this issue - making BC class abstract will exclude it from `test.getXmlClasses()`

However maybe it's acceptable to filter out classes with no test methods in `DynamicGraphHelper.createClassDependencies` itself, if that's the case i'd be more than happy to submit a pull request

**Comment by krmahadevan** [comment]
@sergejjkim - Since you have done the analysis on the cause of the problem, why not raise a PR to fix the problem ?

**Comment by sergejjkim** [comment]
@krmahadevan hi again, i've submitted a pull request. 
https://github.com/cbeust/testng/pull/2250
looking forward to comments :)
