### ISSUE TITLE
Ensure test method parameters are visible in BeforeMethod config method

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2255]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior

The parameters that are being passed to a `@Test` via a `@DataProvider` should be visible and accessible from within a `@BeforeMethod`

### Actual behavior

The parameters aren't visible currently.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
import org.testng.ITestResult;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class GetTestMethodParameters {

  @BeforeMethod
  public void beforeMethod(ITestResult result) {
    Object[] parameters = result.getParameters();
    if (parameters == null || parameters.length == 0) {
      throw new IllegalStateException("parameters arent visible");
    }
  }

  @Test(dataProvider = "dp")
  public void testMethod(int i) {}

  @DataProvider(name = "dp")
  public Object[][] getData() {
    return new Object[][] {{1}, {2}};
  }
}
```

**Comment by QAthulhu** [comment]
Hi @krmahadevan , I'm checking the [change file ](https://github.com/cbeust/testng/blob/master/CHANGES.txt#L27)for 7.2, but can't find this issue, but [this issue](https://github.com/cbeust/testng/pull/2256) is merged?

**Comment by krmahadevan** [comment]
@QAthulhu - Please check once again or look at the change set. You should see the GITHUB issue mentioned in there.

**Comment by QAthulhu** [comment]
@krmahadevan oh I see it now. I was searching for 2255, I thought it would have the same number lol. Thank you!!
