### ISSUE TITLE
RetryAnalyzer doesn't retry @Before* methods that fail

### ISSUE THREAD

**Issue by cpjust** [cbeust/testng#2257]
### TestNG Version
7.0.0

### Expected behavior
From what I was told in this post, it was designed that way:  https://groups.google.com/forum/#!topic/testng-users/64YfIs1WjAg

However, I would suggest adding a feature to allow people to also retry @Before* methods that fail.

You may be asking why do we need this feature?  The answer is because for very complex software ecosystems (mine is composed of about 27 different VMs with different micro-services on them) environmental flakiness is inevitable.  Sometimes there may be timeouts or messages could get delayed in some parts of the system that could cause some of the test setup methods to fail; and simply retrying them could allow them to be successful, thereby allowing the rest of the tests to run normally.
Essentially, it's the same reason why the RetryAnalyzer retries @Test methods that fail.  Flaky tests are inevitable in large systems.

### Actual behavior
It looks like if the `@Test` method gets run and fails, it will retry the `@BeforeMethod` method before retrying the `@Test` method, but if the `@BeforeMethod` fails before the `@Test` runs, it won't get retried.
Also, if the  `@BeforeSuite`, `@BeforeClass` or `@BeforeGroups` methods fail they don't get retried either.

### Is the issue reproductible on runner?

- [x] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
public class Utility
{
    public static String getClassName() {
        StackTraceElement stElement = Thread.currentThread().getStackTrace()[2];
        return stElement.getClassName();
    }

    public static String getFunctionName() {
        StackTraceElement stElement = Thread.currentThread().getStackTrace()[2];
        return stElement.getMethodName();
    }

    public static String getClassAndFunctionName() {
        StackTraceElement stElement = Thread.currentThread().getStackTrace()[2];
        return stElement.getClassName() + "." + stElement.getMethodName();
    }
}
```

You can set different fail* boolean variables to true to see how it behaves for each type of failure.

```java
@Listeners({ MyListener.class })
public class TestMyListener
{
    private static final Logger LOG = Logger.getLogger(TestMyListener.class);

    private static Map<String, Integer> methodCalls = new HashMap<>();

    private static boolean failBeforeSuite = false;
    private static boolean failBeforeTest = false;
    private static boolean failBeforeClass = false;
    private static boolean failBeforeGroups = false;
    private static boolean failBeforeMethod = true;
    private static boolean failTest1 = false;
    private static boolean failAfterMethod = false;
    private static boolean failAfterGroups = false;
    private static boolean failAfterClass = false;
    private static boolean failAfterTest = false;
    private static boolean failAfterSuite = false;

    private void runFunction(String name, boolean shouldFail) {
        final String msg = "Called: " + name + " at timestamp: " + ZonedDateTime.now().toInstant().toEpochMilli();
        LOG.info(msg);

        if (methodCalls.containsKey(name)) {
            methodCalls.put(name, methodCalls.get(name) + 1);
        } else {
            methodCalls.put(name, 1);
        }

        if (shouldFail && (methodCalls.get(name).intValue() == 1)) {
            final String err = "Boom in: " + name;
            LOG.error(err);
            Assert.fail(err);
        }
    }

    @BeforeSuite(alwaysRun = true)
    public void beforeSuite() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failBeforeSuite);
    }

    @BeforeTest(alwaysRun = true)
    public void beforeTest() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failBeforeTest);
    }

    @BeforeClass(alwaysRun = true)
    public void beforeClass() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failBeforeClass);
    }

    @BeforeGroups("group1")
    public void beforeGroups() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failBeforeGroups);
    }

    @BeforeMethod(alwaysRun = true)
    public void beforeMethod() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failBeforeMethod);
    }

    /////////////////////////////////////////////////////////////////

    @Test(groups = "group1", retryAnalyzer = RetryAnalyzer.class, alwaysRun = true)
    public void test1() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failTest1);
    }

    /////////////////////////////////////////////////////////////////

    @AfterMethod(alwaysRun = true)
    public void afterMethod() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failAfterMethod);
    }

    @AfterGroups("group1")
    public void afterGroups() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failAfterGroups);
    }

    @AfterClass(alwaysRun = true)
    public void afterClass() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failAfterClass);
    }

    @AfterTest(alwaysRun = true)
    public void afterTest() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failAfterTest);
    }

    @AfterSuite(alwaysRun = true)
    public void afterSuite() {
        LOG.trace("*** Called: " + Utility.getClassAndFunctionName());
        runFunction(Utility.getFunctionName(), failAfterSuite);

        methodCalls.forEach((String name, Integer calls) -> LOG.info("### Called " + name + "() " + calls + " times."));
    }
}
```

**Comment by krmahadevan** [comment]
ping @cbeust @juherr 

This from my limited knowledge on the codebase may require a significant code change, so I would like to know your thoughts on this before we proceed further. I cant seem to think of anyway in which this could be done outside the realms of TestNG (at-least nothing comes to my head immediately). I will continue to ponder on any way in which this can still be supported in TestNG outside of it using any of its features. 

In the meantime please suggest your thoughts on this requirement.

@cpjust - You might want to further elaborate the expectations. When you say retry `@BeforeXX` what is the expectation here ?

Should a failure in `@BeforeClass` trigger just its retry (or) are you also expecting that the upstream dependencies be retried as well (am pretty sure that's not the ask, but just want to be explicit on this)

**Comment by cpjust** [comment]
@krmahadevan Well, I haven't seen @BeforeSuite or @BeforeGroup methods being used at my company, so personally I don't care that much if those get retried or not, but for the sake of completeness I included those in case someone else IS using them and would want them re-run.

At the very least, I would expect the @BeforeMethod and @BeforeClass methods to get re-run if they fail, then if they pass after however many retries are allowed by the RetryAnalyzer, it can then move on to the @Test methods in that class.

**Comment by juherr** [comment]
I think it can be already done in userspace with something like:

```java
    @BeforeSuite(alwaysRun = true)
    public void beforeSuite() {
        retry(3, () -> {
           // do stuff
        });
    }

    private static void retry(int maxRetry, Runnable function) {
        Exception currentException = null;
        for (int i = 0; i < maxRetry; i++) {
           try {
              function.run();
              return;
           } catch (Exception e) {
             currentException = e;
          }
        }
        throw currentException;
    }
```

**Comment by cpjust** [comment]
That's right, I can do it myself, but that would require me to add it to all my setup methods.  The same could be said about @Test methods; you can add your own retry logic there, but it would be easier if the test framework could handle all retries for us automatically.

**Comment by krmahadevan** [comment]
@cpjust - Here's a lesser invasive, *Do it yourself* option by leveraging `org.testng.IConfigurable`

```java
public class TestClassSample implements IConfigurable {

  private int counter = 1;

  @Override
  public void run(IConfigureCallBack callBack, ITestResult testResult) {
    callBack.runConfigurationMethod(testResult);
    if (testResult.getThrowable() != null) {
      for (int i = 0; i <= 3; i++) {
        callBack.runConfigurationMethod(testResult);
        if (testResult.getThrowable() == null) {
          break;
        }
      }
    }
  }
}
```

The above alternative along with a PR that I have raised should collectively let you retry configurations.

**Comment by cpjust** [comment]
Thanks!
I think that might do the trick.  I'll try it out as soon as it's merged.

**Comment by cpjust** [comment]
BTW, how long does it usually take for new versions to get uploaded to Maven?  The last one I see is from Dec. last year.  https://mvnrepository.com/artifact/org.testng/testng
I guess it doesn't happen automatically after you merge a PR?

**Comment by krmahadevan** [comment]
@cpjust - `7.1.0` was our last release. We are working on getting `7.2.0` release done in a week or two. 

If you are talking about `snapshots` getting published, we used to have that. For some reason it seems to have stopped. I am trying to find out what happened.

**Comment by darklynx** [comment]
@krmahadevan any news about plans to release ver. `7.2.0`?

**Comment by krmahadevan** [comment]
@darklynx - No. I dont have any updates on when the release would be done.

**Comment by zishanakhtar07** [comment]
@BeforeMethod is running properly during retry but @Test is not running after @BeforeMethod

**Comment by juherr** [comment]
@zishanakhtar07 If the issue still exists, could you open a new issue and share a runnable sample?

**Comment by hhlTer** [comment]
As I understand, the update solves repeating for @BeforeXXX and @AfterXXX.
But if the error occurs in the @Test - what if we need to repeat @BeforeXXX again for this test?  Even if @BeforeXXX is always passed?

**Comment by cpjust** [comment]
@hhlTer If the test fails, it should only re-run the @BeforeMethod.  The @BeforeClass & @BeforeSuite should only run once before the entire set of tests in the class/suite (unless those Before* methods fail, then they should get re-run with the fix above).
