### ISSUE TITLE
How can i pass the currentinvocation counter from invokelistener to the testmethod without any multithreading issues safely?

### ISSUE THREAD

**Issue by selvarajagurur** [cbeust/testng#2276]
I'm able to set the InvocationCount for my test method using IAnnotaionTransformer. Now I need to run my test method for number(InvocationCount) of times but with different data from excel sheet for each run.

I tried with IInvokedMethodListener class and override beforeInvocation method and used getTestMethod().getCurrentInvocationCount() to get the currentInvocationcount number.

I share this currentInvocationcount number using a counter class(some int variable in it) with the test method. Using this number i need to read the corresponding row in the excel sheet in the test method. For example, if the currentInvocationcount is 0, i will read the 1st row in the excel sheet and if it's 1, i will read the 2nd row in the excel sheet and so on. With SingleThread, I'm able to successfully implement this sequentially and i don't have any issues. But with multiple threads and multiple tests, the sequence is different and I'm not getting the right sequence of execution.
I have a synchronized counter like below.
`public class SynchronizedCounter {
    private static int ctr;
    public synchronized void setSynchroed(int ctr) {
        this.ctr=ctr;
    }
    public static synchronized int  getSynchroed() {
        return ctr;
    }
}`
And i share the currentinvocationcount from the InvokedMethodLister class like below. I thought synchronized way of sharing ctr would be helpful.but no use.
`
@Override
synchronized public  void  beforeInvocation(IInvokedMethod arg0, ITestResult arg1) {
    SynchronizedCounter sctr=new SynchronizedCounter();
    sctr.setSynchroed(arg0.getTestMethod().getCurrentInvocationCount());
}`
And i access the synnchronizedcounter value in the test like below.

`@Test
public void Test1() {
    System.out.println("The calling count of Make Payment Test 1 is"+SynchronizedCounter.getSynchroed());
int counter=SynchronizedCounter.getSynchroed();
//logic below to access excel sheet with "counter"th row.
}`
`@Test
public void Test2() {
    System.out.println("The calling count of Make Payment Test 2 is"+SynchronizedCounter.getSynchroed());
int counter=SynchronizedCounter.getSynchroed();
//logic below to access excel sheet with "counter"th row.
}`
Please see the output below. Just for easy understanding i kept only the relevant output. Test 2 and Test 3 is set to execute 12 and 15 times.You can notice that Test2 and Test3 is getting values overwritten by other tests(actually i ran Test1,Test4 also). Example:After Test2's 8th Run Test4 set the counter to 6 so Test2 used 6 again. Not sure why.

The calling count of Delete Payment Test 3 is0

The calling count of Make Payment Test 2 is0

The calling count of Make Payment Test 2 is1

The calling count of Make Payment Test 2 is2

The calling count of Make Payment Test 1 is2

The calling count of Delete Payment Test 3 is1

The calling count of Make Payment Test 2 is1

The calling count of Make Payment Test 2 is4

The calling count of Delete Payment Test 3 is3

The calling count of Make Payment Test 2 is5

The calling count of Delete Payment Test 3 is4

The calling count of Make Payment Test 2 is6

The calling count of Make Payment Test 2 is8

The calling count of Delete Payment Test 3 is8

The calling count of Make Payment Test 2 is8

The calling count of Make Payment Test 4 is6

The calling count of Make Payment Test 2 is6

The calling count of Delete Payment Test 3 is6

The calling count of Make Payment Test 2 is7

The calling count of Delete Payment Test 3 is7

The calling count of Delete Payment Test 3 is8

The calling count of Make Payment Test 2 is8

The calling count of Delete Payment Test 3 is9

The calling count of Delete Payment Test 3 is10

The calling count of Delete Payment Test 3 is11

The calling count of Delete Payment Test 3 is12

How can i pass the currentinvocation counter from invoke listener to the test without any multi threading issues safely?

**Comment by krmahadevan** [comment]
Please use the testng-users google forums to ask questions. We prefer to keep the issues page to just record issues.
