### ISSUE TITLE
Test is executed infinite number of times when the data provider returns a new array of object 

### ISSUE THREAD

**Issue by pandlab** [cbeust/testng#2280]
### TestNG Version
7.1.0 (version which contains #2163 ) 

### Expected behavior
The test is executed 3 times

### Actual behavior
The test is executed infinitely

### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

ensureRetryDoesntRunEndlesslyForDataDrivenTests - I modified existing unit test to cover the issue
https://github.com/cbeust/testng/commit/9ad6ec4bb22088d7e502ac57e3091647eb9f979f
timeout only to prevent infinitive loop

### Observation

When I set up breakpoin at testng-7.1.0-sources.jar!\org\testng\internal\BaseTestMethod.java#767 and watching "Arrays.toString(key)" I got next values
* [test1, [Ljava.lang.Object;@60194904]
* [test1, [Ljava.lang.Object;@5cd701e4]
for:
```
        {"test1", new Object[] {new Object()}},
```

**Comment by krmahadevan** [comment]
@pandlab - Since you have spent time investigating this, why not raise a PR for this ?

**Comment by pandlab** [comment]
@krmahadevan I was trying to solve this from the wrong side.

And suddenly, in the evening, I got the idea to use ParameterInvocationCount please review 
 #2281

**Comment by krmahadevan** [comment]
Fixed via https://github.com/cbeust/testng/pull/2281
