### ISSUE TITLE
testResult.getTestContext() return null when @BeforeMethod failed

### ISSUE THREAD

**Issue by dianny123** [cbeust/testng#2282]
### TestNG Version
7.1.0

### Expected behavior
If there is error in method with @BeforeMethod, the test method will be skipped and testContext in testResult will return instance `org.testng.TestRunner@617faa95` when use IInvokedMethodListener.

### Actual behavior
testContext in testResult  returns null.

### Is the issue reproductible on runner?
-  Maven  3.5.3
- Eclipse   Oxygen (4.7.3a)

### Test case sample
Here is test code and log:
CustomListener.java

```java
public class CustomListener implements IInvokedMethodListener {

    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        ITestContext dependsOn = testResult.getTestContext();
        System.out.println("beforeInvocation: " + dependsOn);
    }

    @Override
    public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
        ITestContext tct = testResult.getTestContext();
        System.out.println("afterInvocation: " + tct);
    }
}
```

TestClass.java

```java
@Listeners(CustomListener.class)
public class TestClass {
    @BeforeMethod
    public void beforeMethod1() {
        throw new SkipException("Skip happened at beforeMethod");
    }

    @Test
    public void test() {
        System.out.println("test is skiped");
    }
}
```

pom.xml
```xml
<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
            <scope>compile</scope>
    </dependency>
```
TestSuite.xml

```xml
<suite name="Test">
  <test name="tests">
    <classes>
      <class name="com.internal.TestClass"/>
    </classes>  
  </test>
</suite>
```

Run As TestNG Suite on eclipse
Log:

```
beforeInvocation: org.testng.TestRunner@617faa95
afterInvocation: org.testng.TestRunner@617faa95
beforeInvocation: null
afterInvocation: null
```

**Comment by dianny123** [comment]
If run with command line, the log result is:
beforeInvocation: org.testng.TestRunner@7d9d1a19
afterInvocation: org.testng.TestRunner@7d9d1a19
beforeInvocation: org.testng.TestRunner@7d9d1a19
afterInvocation: org.testng.TestRunner@7d9d1a19

**Comment by krmahadevan** [comment]
@dianny123 - If this issue is specific ONLY to TestNG eclipse plugin (I am not able to reproduce this with a regular TestNG test class that can be run via IntelliJ for .e.g,) then I would suggest that you please create an issue in the TestNG eclipse project https://github.com/cbeust/testng-eclipse

and include details on the TestNG eclipse plugin version that you are working with as additional context.
