### ISSUE TITLE
 java.lang.Exception parameters unresolved:

### ISSUE THREAD

**Issue by ShalluP** [cbeust/testng#2287]
[HD_FW_BaseClass_SelAut.java.txt](https://github.com/cbeust/testng/files/4410430/HD_FW_BaseClass_SelAut.java.txt)
[HD_FW_ExcelData_dataProvider.java.txt](https://github.com/cbeust/testng/files/4410431/HD_FW_ExcelData_dataProvider.java.txt)
[HD_FW_Methods.java.txt](https://github.com/cbeust/testng/files/4410432/HD_FW_Methods.java.txt)
[HD_FW_SetUpExcel_Class.java.txt](https://github.com/cbeust/testng/files/4410433/HD_FW_SetUpExcel_Class.java.txt)
[HD_FW_TestClass_SelAutoBlogSpot.java.txt](https://github.com/cbeust/testng/files/4410434/HD_FW_TestClass_SelAutoBlogSpot.java.txt)

Hi,
 I am working on a hybrid framework using TestNG.
I am combining Data driven and Keyword driven approach
The Test class contains, 2 methods
1. One for keyword driven, which is working fine
2. for hybrid:
where I want to fetch the login credentials(first name, last name and address) from the excel file, feed it in the web app 
and execute the methods, by comparing the name of methods from another excel file.
3. the excel file has two sheets, 
a. includes the keywords'
b. includes the first name,last name and address 

I have attached :
1. Base class file
2. Excel file
3. data provider file
4. Set up file for  excel
5.methods file

After executing the program from the test file, I ma getting the following error:

org.testng.TestNGException: 
Some DataProvider public static java.lang.Object[][] com.HybridDrivenFrameWork_Utility.HD_FW_ExcelData_dataProvider.LoginCredentials(java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception parameters unresolved:  at 0 type class java.lang.String
 at 1 type class java.lang.String
 at 2 type class java.lang.String

Kindly guide me
Thanks in advance
Best Regards

[Hybrid Framework.zip](https://github.com/cbeust/testng/files/4410406/Hybrid.Framework.zip)

**Comment by krmahadevan** [comment]
@ShalluP - There's nothing wrong with TestNG here.

TestNG is merely telling you that your test method is expecting 3 parameters but your data provider is not providing 3 parameters.

You need to fix either your data provider and have it return 3 values or alter your test method's parameters to just accept 2 parameters.

**Comment by ShalluP** [comment]
Ok Sir.
I will do it again
Thank you Sir

**Comment by steveDeep** [comment]
Hi , I am getting the same above error ,
"Some DataProvider public java.lang.Object  parameters unresolved:  at 0 type class java.lang.String"

My test method is having 2  parameters test date sheet also has  3 parameters. Than what could be the issue .

Kindly guide me
Thanks in advance
