### ISSUE TITLE
dataProvider on test level doesn't work when we have method dataprovider.

### ISSUE THREAD

**Issue by kobebryant2007** [cbeust/testng#2293]
### TestNG Version 7.1.0
> Note: only the latest version is supported

### Expected behavior

```java
@Test(dataProvider = "test2")
public class TesgNGUpliftDemo {
	@DataProvider(name = "test1")
    public Object[][] createDataMethodLevel() {
        return new Object[][] {
                { "Cedric", 36 },
                { "Anne", 37},
        };
    }

    @DataProvider(name = "test2")
    public Object[][] createDataClassLevel() {
        return new Object[][] {
                { "Pet", 16},
                { "Sun", 17},
        };
    }
	
	@Test(dataProvider = "test1")
    public void testClassAndMethodDataProvider(String name, int age) {
        JcatLoggingApi.setTestInfo("name: " + name + ", " + "age: " + age);
    }
}
```

dataProvider for test1 and test2 should be merged and executed.
### Actual behavior
Only test1 dataProvider was useful.
![image](https://user-images.githubusercontent.com/6948283/78755702-29275200-79ac-11ea-8e33-f96f98b8db1c.png)

![image](https://user-images.githubusercontent.com/6948283/78755723-33495080-79ac-11ea-82bb-0a3b864b696a.png)

### Is the issue reproductible on runner?
Yes, it is.
- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@kobebryant2007 

> dataProvider for test1 and test2 should be merged and executed.

Can you please point me to the documentation which leads you to believe that, this is how it should work ?

I don't remember TestNG ever merging data providers that were specified at the class level and the method level.

The attributes specified at the method level always override the values specified at the class level.

So unless you can point me to the official documentation which claims that this is the behaviour (which should be fixed and corrected for this discrepancy), I will have to close this bug with the resolution as **Working as designed**

**Comment by kobebryant2007** [comment]
Hi Krishnan,
Thank you for your quick response. I know this feature by your release note in google groups,the link is: https://groups.google.com/forum/#!topic/testng-users/HKujuefBhXA
`You can now define a data provider at the class level @Test and also add specifics of a test method by specifying a @Test at method level and TestNG will merge both and run your test as a data driven test.`
It said both will be merged.

**Comment by krmahadevan** [comment]
@kobebryant2007 

Ok, I think you misread that.

> Support reading data provider information from Class level @Testannotation
> You can now define a data provider at the class level @Test and also add specifics of a test method by specifying a @Test at method level and TestNG will merge both and run your test as a data driven test.
> 

What I meant to say was that you could specify a data provider at the class level and add specifics with respect to other attributes of a "@Test" annotation at the method level and they would get merged. I don't think it meant that you could merge two data providers using this mechanism.

**Comment by kobebryant2007** [comment]
OK, then I think it's clear, Thank you again for explaining, I will close this issue.
