### ISSUE TITLE
Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile

### ISSUE THREAD

**Issue by shashankmodi** [cbeust/testng#2298]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

> @shashankmodi - You haven't shared anything that points this to a TestNG problem. Unless you can add more details that points this to a TestNG problem, there's not much that can be done and we will have to close this issue.

my issue is related to maven plugin scala

**Comment by shashankmodi** [comment]
I am not able to fix this issue, please help soon

**Comment by shashankmodi** [comment]
Expected all dependencies to require Scala version: 2.11.12
 com.twitter:chill_2.11:0.9.3 requires scala version: 2.11.12
 org.apache.spark:spark-core_2.11:2.4.0 requires scala version: 2.11.12
 org.json4s:json4s-jackson_2.11:3.5.3 requires scala version: 2.11.11
Multiple versions of scala libraries detected!

**Comment by krmahadevan** [comment]
@shashankmodi - You haven't shared anything that points this to a TestNG problem. Unless you can add more details that points this to a TestNG problem, there's not much that can be done and we will have to close this issue.

**Comment by krmahadevan** [comment]
TestNG project does not own the maven Scala plugin. Please file the issue on the maven Scala plugin GitHub repository.
