### ISSUE TITLE
Ability to set reporter configuration options from Maven Surefire has been broken

### ISSUE THREAD

**Issue by sbabcoc** [cbeust/testng#2301]
### TestNG Version
7.1.0

### Expected behavior
Properties specified in the Surefire reporter configuration should be injected into the reporter object when it's instantiated.

### Actual behavior
Specified properties trigger warnings about the inability to set their values.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Create a Maven project that specifies the following Surefire configuration:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactld>maven-surefire-plugin</artifactld>
  <version>2.20.1</version>
  <configuration>
    <testSourceDirectory>${project.build.directory}/surefire-reports</testSourceDirectory>
    <testFailureIgnore>true</testFailureIgnore>
    <suiteXmlFiles>
      <suiteXmlFile>TestNgXmlFiles/${suiteFile}</suiteXmlFile>
    </suiteXmlFiles>
    <properties>
      <property>
        <name>usedefaultlisteners</name>
        <value>false</value>
      </property>
      <property>
        <name>reporter</name>
        <value>org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true</value>
      </property>
    </properties>
  </configuration>
</plugin>
```

The specified properties [generateTestResultAttributes] and [generateGroupsAttribute] should be injected into the configuration of the XMLReporter, but these simply result in warning messages.

The problem appears to originate in the factoring out of the properties into a configuration object. The `newReporterInstance()` method expects that the reporter object will maintain the properties directly, using Java Bean conventions. This method was not updated to support population of a separate configuration object.

**Comment by sbabcoc** [comment]
Hmmm... This may actually be a case where updated documentation is the right fix.
```xml
<property>
  <name>reporter</name>
  <value>org.testing.reporters.XMLReporter:config.generateTestResultAttributes=true,config.generateGroupsAttribute=true</value>
</property>
```
I think this might actually work as expected. Checking into this.

**Comment by krmahadevan** [comment]
@sbabcoc - Its already documented in 
https://testng.org/doc/documentation-main.html#logging-xml-reports

Quoting it for your reference.

> TestNG offers an XML reporter capturing TestNG specific information that is not available in JUnit reports. This is particularly useful when the user's test environment needs to consume XML results with TestNG-specific data that the JUnit format can't provide. This reporter can be injected into TestNG via the command line with -reporter.

> Here's a sample usage: `-reporter org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true`.

**Comment by krmahadevan** [comment]
@sbabcoc - Is this what you were looking for? If yes, then please close off this issue and the PR associated with it as well.

**Comment by sbabcoc** [comment]
No, the nested bean cannot be configured as currently implemented. I get this type of warning:
```
[PropertyUtils] [WARN] Cannot set property config.generateTestResultAttributes with value true. Property class could not be found
```
The implementation doesn't currently handle nested beans, which is how the configuration of **XMLReporter** is structured. I'm studying the Java Beans documentation to see if there's a way to support this structure through the standard Java Beans API without major revisions.
