### ISSUE TITLE
@BeforeGroups and @AfterGroups don't work as expected

### ISSUE THREAD

**Issue by ihorpts** [cbeust/testng#2319]
### TestNG Version
7.1.0

### Expected behavior
@BeforeGroups and @AfterGroups annotated methods should be executed before/after group tests execution

### Actual behavior
@BeforeGroups and @AfterGroups annotated methods are not invoked at all before/after group test execution.
This behavior works just fine in 7.0.0 and all older versions of TestNG

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```java
public class TestGroup {
    @BeforeGroups("group-one")
    public void setupGroupOne() {
        System.out.print("set up group one");
    }

    @AfterGroups("group-one")
    public void tearDownGroupOne() {
        System.out.print("tear down group one");
    }

    @Test(groups= "group-two")
    public void testGroupTwo1() {
        System.out.print("testGroupTwo1()");
    }

    @Test(groups= "group-two")
    public void testGroupTwo2() {
        System.out.print("testGroupTwo2()");
    }

    @Test(groups = "group-one")
    public void testGroupOne1() {
        System.out.print("testGroupOne1()");
    }

    @Test(groups = "group-one")
    public void testGroupOne2() {
        System.out.print("testGroupOne2()");
    }

    @Test(dependsOnGroups = {"group-one","group-two"})
    public void lastRun() {
        System.out.print("lastRun()");
    }
}
```
### Expected output (_IntelliJ_) is
```
set up group one

testGroupOne1()

testGroupOne2()

tear down group one

testGroupTwo1()

testGroupTwo2()

lastRun()

===============================================
Default Suite
Total tests run: 5, Passes: 5, Failures: 0, Skips: 0
===============================================
```
### Actual output (_IntelliJ_) is
```
testGroupOne1()

testGroupOne2()

testGroupTwo1()

testGroupTwo2()

lastRun()

===============================================
Default Suite
Total tests run: 5, Passes: 5, Failures: 0, Skips: 0
===============================================
```

**Comment by krmahadevan** [comment]
@ihorpts - TestNG is working as designed.

When you right click on a test class and run from IntelliJ or Eclipse, TestNG does not resort to running by groups (even though your test class may have groups defined).

For TestNG to resort to group selection (which is when the `@BeforeGroups` and `@AfterGroups` would run), you would need to create a suite file and then run the suite file.

Below is a sample suite file.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="2319_suite" parallel="false" configfailurepolicy="continue">
  <test name="2319_test">
    <groups>
      <run>
        <include name="group-one"/>
      </run>
    </groups>
    <classes>
      <class name="com.rationaleemotions.github.issue2319.TestGroup"/>
    </classes>
  </test>
</suite>

```

Sample output:

```
set up group one

testGroupOne1()

testGroupOne2()

tear down group one

===============================================
2319_suite
Total tests run: 2, Passes: 2, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

Closing this issue with the resolution as *Question answered*

**Comment by ihorpts** [comment]
@krmahadevan thank you for the answer.

The only question left is clarification about differences in execution for TestNG v7.0.0 and v7.1.0. Meaning, is it right conclusion that there were changes between v7.0 and v7.1, which brought such behavior (suite file adoption)?
Because our tests started just fail after upgrading to v7.1.0, so it means it had been working for few years somehow and now it's not. I just to be on safe side and fix those tests properly

Thank you in advance

**Comment by krmahadevan** [comment]
@ihorpts - Yep. I think this was a bug in TestNG always and the behavior was rectified in `7.1.0` as part of this PR https://github.com/cbeust/testng/pull/2167

Groups selection should ONLY work, when its used as a filtering mechanism. In all other cases it shouldn't come into picture.
