### ISSUE TITLE
Fail on beforeMethod causes all subsequent tests to be ignored

### ISSUE THREAD

**Issue by safokoi** [cbeust/testng#2324]
### TestNG Version
7.0.0

### Expected behavior
Fail is acceptable only for currently running test.

### Actual behavior
Fail causes all tests to be ignored.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```
@Test
class BeforeMethodTest {

    @BeforeMethod()
    public void setup(Method method) {
        if (method.toString().contains("test1")) {
            Assert.assertEquals(2,1);
        }
    }

    public void test1() {
    }

    public void test2() {
    }

    public void test3() {
    }

}
```

**Comment by krmahadevan** [comment]
@safokoi - TestNG is working as designed.

By default, TestNG resorts to skipping test methods if there is a failure in a configuration method.
You can change this by setting the attribute `configfailurepolicy="continue"` in your suite file and then running. Then TestNG will execute the remaining tests as well.

Closing this issue with resolution as *Question answered*
