### ISSUE TITLE
TestNG Jump between classes when doing priority

### ISSUE THREAD

**Issue by saginadav2** [cbeust/testng#2326]
Hey All
I have a question, I am using selenium, and I have 3 classes of tests, and in each class 4 test.
Class A - open websiet A  and perform tests
Class B - open website B and perform tests
Class C - open website c and perform tests

In each class I prioritized the tests (it is necessary in each page to do specific order )
When I run manually only class A and Only B and Only C all working.
However when I try to create testng xml and run
it is trying to perform action from class B in the website of A.
I do not need parallel, just to testng run as  human maid the actions. to run class A with all its tests by priority. after that to run class B with all its tests by priority and than class C. Is it possible that testNG do this thing? or just manually (and no automation can be made)

this is my XML
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">

<suite allow-return-values="true" name="sanitySuite" parallel="false" thread-count="1" verbose="1" >
    <test name="Role page"  preserve-order="true" >
        <parameter name="userName" value="selmadmin@gmail.com"/>
        <parameter name="password" value="bbb"/>
        <groups>
            <run>
                <include name="smokeTest"/>
             </run>
        </groups>

        <packages>
            <package name =".*"/>
        </packages>
        <classes>
            <class name="tests.classA"></class>
            <class name="tests.classB"></class>
			<class name="tests.classC"></class>
		
        </classes>
    </test>

    <!--<test name="Regression1">-->
        <!--<packages>-->
            <!--<package name=".*"/>-->
        <!--</packages>-->
    <!--</test>-->
</suite>
```

example of test attribute that exists in all 5 classes and in all tests just change the priority
`@Test(groups = {"smokeTest"}, enabled = true, priority = 1)`

**Comment by krmahadevan** [comment]
Please post your TestNG questions on the Testng-users Google groups. We would like to make sure that the issue tracker is tracking only issues.
