### ISSUE TITLE
Parameters not present on skipped Test because of failing configuration method

### ISSUE THREAD

**Issue by erickubenka** [cbeust/testng#2327]
### TestNG Version
7.2.0 and current master branch

### Description
For a better understanding I will provide some code samples, but at first I want to describe the error. 

When using the `Dataprovider` in mode `parallel=true` in combination with a `@BeforeMethod`, the configuration method will run for every dataset. This is intended behaviour. 
With a dataset-dependent configuration mehtod it could occur, that the `BeforeMethod` for dataset1 will pass, and for dataset 2 may will fail.
For a failing configuration method, the test method will be markes as skipped.

When providing an own listener implementing the `ITestListener` interface, and implementing the method `onTestSuccess` and 
`onTestSkipped` adressing the `ITestResult.getParameters()` method I encountered the issue, that for skipped test methods the parameters will be not set.

For reporting purposes and further handling I want to access the `parameters` for skipped methods in the same way as for passing or failing tests.

### Expected behavior
`ITestResult.getParameters()` for implementations of `onTestSkipped` in `ITestListener` interface returns parameters of data provider.

Output for appended test sample:
````
Success: [Dataset2]
Test ignored.
Skipped: [Dataset1]
````

### Actual behavior
`ITestResult.getParameters()` for implementations of `onTestSkipped` in `ITestListener` interface does not return parameters of data provider.

Output for appended test sample:
````
Success: [Dataset2]
Test ignored.
Skipped: []
````

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
.Listener Example
````java
public class SkipListener implements ITestListener {
  @Override
  public void onTestSuccess(ITestResult result) {
    System.out.println("Success: " + Arrays.toString(result.getParameters()));
  }

  @Override
  public void onTestSkipped(ITestResult result) {
    System.out.println("Skipped: " + Arrays.toString(result.getParameters()));
  }
}
````

.TestClass
````java
@Listeners(SkipListener.class)
public class ClassWithFailedBeforeMethod {

  static boolean fail = true;

  @BeforeMethod(alwaysRun = true)
  public void setupShouldFail(Method method, Object[] params) {

    if (fail) {
      fail = false;
      throw new RuntimeException("Failing in setUp");
    }
  }

  @DataProvider(parallel = true)
  public Iterator<Object> dummyData() {
    ArrayList<Object> objects = new ArrayList<>();
    objects.add("Dataset1");
    objects.add("Dataset2");
    return objects.iterator();
  }

  @Test(dataProvider = "dummyData")
  public void test1(String test) {}
}

````

If I should add any value to this issue, please let me know.
Further I will create a pull request for the bug fix, if you appreciate it.

Best regards,
Eric

**Comment by krmahadevan** [comment]
@erickubenka - If you are planning on raising a PR, please go ahead. We will help vet it out and get it merged as well.

This page should explain to you how to contribute https://github.com/cbeust/testng/blob/master/CONTRIBUTING.md
