### ISSUE TITLE
Add ability to get test method for which configuration method was called

### ISSUE THREAD

**Issue by nebehr** [cbeust/testng#2328]
It would be nice to be able to establish relationship between @BeforeMethod/@AfterMethod configuration methods and @Test method for which they were called in a listener. This could be useful in custom reporting systems.

At the moment it is possible only if parameter of type `Method` is injected in configuration methods; however this is not an acceptable solution in cases when there is no direct control over the way test code is written. A good place to provide such information would be `org.testng.ITestNGMethod` interface which is accessible from all relevant listeners either directly or via `org.testng.ITestResult`.

Issue posted based on discussion at https://stackoverflow.com/questions/62472419/get-test-method-for-which-configuration-method-was-called-in-testng

**Comment by baflQA** [comment]
@krmahadevan would it be possible to achieve the same behaviour for the DataProvider methods, and make them aware of the test context?

**Comment by krmahadevan** [comment]
@baflQA - You should be able to add `ITestContext` as a parameter to the `@DataProvider` method even today. Have you tried that ?

**Comment by baflQA** [comment]
Hm, seems like not yet... Thx for the tip, will try that and let You know!

**Comment by movigit** [comment]
hi! I that possible to do same for IClassListener? So it would be possible to get current test instance from that listener?
Or there is another mechanism to do get test class instance that triggered invocation of onBefore/AfterClass in IClassListener?

For now I see possibility to get all test instances for TestClass from ITestClass, but I do not know how to identify the one, that triggered IClassListener invocation.

**Comment by juherr** [comment]
The TestClass instance level is currently missing from the model. That's why it doesn't exist an easy way to get it or a dedicated listener.
The related issue is https://github.com/cbeust/testng/issues/1515
