### ISSUE TITLE
Test Execution Time is summed up from suite, test and methods in Eclipse Plugin

### ISSUE THREAD

**Issue by febner** [cbeust/testng#233]
When I run a simple test class with the Eclipse PlugIn I get this report:

Test: 1/1 Methods: 2 (22s)

Default suite (2/0/0/0) (7s)
  Default test (7s)
    com.....
      test1 (2s)
      test2 (5s)

I'm shure the execution time "22 s" is just an addition of the other values below- what's not right from my point of view

**Comment by krmahadevan** [comment]
Migrated to https://github.com/cbeust/testng-eclipse/issues/449
