### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Stage

### ISSUE THREAD

**Issue by tumelotj** [cbeust/testng#2340]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
Already fixed as part of https://github.com/cbeust/testng/issues/2223 and should be available in `7.2.0` which is the upcoming testng version to be released.
