### ISSUE TITLE
Error: Could not find or load main class org.testng.remote.RemoteTestNG

### ISSUE THREAD

**Issue by vishwanath-ts** [cbeust/testng#2344]
### TestNG Version
6.10

### Expected behavior
The test set to run

### Actual behavior
Throws above error.

### Is the issue reproductible on runner?
- [x] ivy
- [x] Eclipse

Env: 
QAF , Java , TestNG , Appium , IVY

### Test case sample
Not specific to any test. It was working earlier & now it is not.

**Comment by krmahadevan** [comment]
The latest released version of TestNG is `7.1.0`. Please use that and try again. If the problem persists, please ensure you share a sample project/example that can be used to reproduce the problem and comment. We can have this issue re-opened.

**Comment by vishwanath-ts** [comment]
Thanks for the quick response.
I have tried with new TestNG version & I saw same issue Error: Could not find or load main class org.testng.remote.RemoteTestNG. And as requested by you, I am also sharing the smaller version of the project. Please take a look. Please let me know if you need more info. 
Also, the ivy.xml in the project has all the latest versions specified in it & it is not working on trying both, to run as testngSuite & also through ant job. But it also has 1 more ivy-old.xml which does not work as testngSuite but works through ant job. Please help.
[app-automation.zip](https://github.com/cbeust/testng/files/4947617/app-automation.zip)

**Comment by krmahadevan** [comment]
@vishwanath-ts - When I tried using the sample project you shared, I see the below exception 

```
runtests:
     [echo] ${execution.classpath}
   [testng] Exception in thread "main" java.lang.NoClassDefFoundError: org/testng/internal/thread/graph/IThreadWorkerFactory
   [testng] 19:18:02.916 [main] DEBUG c.q.q.a.t.p.QAFAnnotationTransformer2 - QAFTestNGListener registered!...
   [testng] 	at java.lang.ClassLoader.defineClass1(Native Method)
   [testng] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
   [testng] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
   [testng] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
   [testng] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
   [testng] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
   [testng] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
   [testng] 	at java.security.AccessController.doPrivileged(Native Method)
   [testng] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
   [testng] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   [testng] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
   [testng] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   [testng] 	at org.testng.internal.Utils.log(Utils.java:217)
   [testng] 	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:962)
   [testng] 	at org.testng.TestNG.initializeConfiguration(TestNG.java:898)
   [testng] 	at org.testng.TestNG.initializeEverything(TestNG.java:988)
   [testng] 	at org.testng.TestNG.run(TestNG.java:999)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1336)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1304)
   [testng] Caused by: java.lang.ClassNotFoundException: org.testng.internal.thread.graph.IThreadWorkerFactory
   [testng] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
   [testng] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   [testng] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
   [testng] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   [testng] 	... 19 more
   [testng] The tests failed.

BUILD SUCCESSFUL
Total time: 16 seconds
```

Sounds like the QAF version that you are using is not compatible with `7.1.0` (Its using a very old version of TestNG. See [here](https://mvnrepository.com/artifact/com.qmetry/qaf/3.0.0-RC3) )

There's not much that can be done from TestNG perspective on this.

**Comment by vishwanath-ts** [comment]
Thanks! I saw that. But it was absolutely working fine with the ivy-old.xml which I have shared with you, couple of weeks back. And suddenly it stopped working throwing "Could not find or load main class org.testng.remote.RemoteTestNG". Any workaround?

**Comment by krmahadevan** [comment]
There is no workaround that I can think of because the problem for sure is not in TESTNG. It's a case of messed up CLASSPATH.

**Comment by vishwanath-ts** [comment]
Thanks once again! What exactly do you mean by messed up CLASSPATH in this context? Can you please give more clarity? I will try to do, if I can do something at my end.

**Comment by krmahadevan** [comment]
@vishwanath-ts - Messed up CLASSPATH = one of the following:

1. You have a combination of dependencies that is bringing in incompatible versions together (If it were in the maven world, I would do a `mvn dependency:tree` to find out what version of TestNG is being brought by whom.
2. You are trying to get incompatible versions of artifacts to work together (QAF and TestNG for example)

I am not well versed with ant+ivy combo (Tried figuring it out for a brief time, but didn't make a lot of progress). I am comfortable only with maven. 

But you would need to find out essentially what version of TestNG is being resolved. If its 7.1.0 and if you still see `NoClassDefFoundError` then its most likely due to incompatibilities of TestNG and QAF or any other library. 
Nothing to be done from TestNG standpoint.

**Comment by vishwanath-ts** [comment]
Fyi, <dependency org="com.qmetry" name="qaf" rev="2.1.15" force="true"/>, was working absolutely fine with TestNG 6.10. But then it suddenly stopped throwing the above error message. Now neither this combination(old) or the new combination (with all the latest versions) are working. Earlier we used to trigger tests through TestNG but now we started using ant because TestNG is not working. But attaching a debugger to the test triggered through ANT is posing a problem & even few more issues when triggered through ANT. It seems little hard when using ANT compared to TestnG. Tried few ways to attach the debugger to debug scripts triggered through ANT job but it is not working.

**Comment by vishwanath-ts** [comment]
After spending considerable time, finally, got to know the solution. The real culprit was the Eclipse version. It was Eclipse neon that was being used which was actually released in 2016 & was quite old. The Eclipse was upgraded from "Neon" to "2020-06" & after that everything worked smoothly. But still the compatible TestNG version for QAF framework is 6.10.

Just for the benefit of others, if we directly download the link 'Mac OS X (Cocoa) 64-bit' displayed under 'Download Links' on the right side here: https://www.eclipse.org/downloads/packages/release/neon/3/eclipse-ide-java-ee-developers, it actually downloads Eclipse Neon Version.

If you carefully notice at the top there is a info message "This package was released on 03/23/2017. A newer package is available here." and in this message if you click on the word 'here', you will actually be navigated to all the latest versions of Eclipse. I just thought(in-fact I was deceived) the most stable version is actually listed directly to the users and I downloaded Neon. Please don't repeat the same mistake.

It seems like Eclipse wants us to download and use Eclipse installer. So, first they are directing us to a page where we actually see older version of Eclispe. If at all we click the link as mentioned above, then we are navigated to a page where they have displayed a banner to download Eclipse installer along with the latest versions of Eclipse.
