### ISSUE TITLE
Skipping of all further tests and before-method configs if one @BeforeMethod failed

### ISSUE THREAD

**Issue by Maksym-Skrypchenko** [cbeust/testng#2345]
### Expected behavior
If one `@BeforeMethod` failed then skip only test it is applied for. Next time this configuration method will run and make an attempt to make config for the next test method.

### Actual behavior
If `@BeforeMethod` fails then all the methods after it will be skipped.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
```java
public class TestClass {

    @BeforeMethod
    public void beforeMethod(Method method) {
        if (method.getName().endsWith("test1")) {
            throw new RuntimeException("fail imitation");
        }
    }

    @Test
    public void test1() {
    }

    @Test
    public void test2() { // this method will be skipped as well as execution of beforemethod for it
    }
}
```

**Comment by krmahadevan** [comment]
@Maksym-Skrypchenko - TestNG is working as designed.

When you run a Test from within IDE, TestNG resorts to the configuration failure policy of `skip` (This is the default value that gets set, when the IDE creates an on the fly suite xml file).

If you would like TestNG to continue running configurations, then you should create a suite xml file and then explicitly set the configuration failure policy to `continue`

Below is an example of one such suite file.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="336_Suite-MySuite-InVM" parallel="false" configfailurepolicy="continue">
    <test name="336_test_1">
        <classes>
            <class name="com.rationaleemotions.github.issue2345.TestClass"/>
        </classes>
    </test>
</suite>
```

Closing this issue with resolution as **question answered**
