### ISSUE TITLE
TestNG DTD not getting downloaded despite of trying every solution already given

### ISSUE THREAD

**Issue by QAtester111** [cbeust/testng#2348]
### TestNG Version
7.1.0
I am a beginner. i am trying to generate testng.xml but its giving me this error. 

Error While downloading 'https://testng.org/testng-1.0.dtd' to C:\Users\Admin\.lemminx\cache\https\testng.org\testng-1.0.dtd.

Warning: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

I have even tried by changing https to http but didnt work.
There are no extra spaces in Testng.xml.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@QAtester111 - I am guessing that you are doing this on your office laptop/desktop which is behind a corporate proxy.
What is happening here is that, Java is basically complaining that when it tried hitting `https://testng.org` the server returned a bunch of certificates (usually the proxy server also appends its self signed certificate in the chain) of which one or more of them were not to be found in the `JAVA_HOME\jre\lib\security\cacerts`.

There are two ways of getting past this problem. 

1. You download your proxy server's certificate (called as trusted root certificate) (refer [here](https://smarie.github.io/develop-behind-proxy/know_your_proxy/) for some help on this) and add it to your `cacerts`
2. Run TestNG using the JVM argument `-Dtestng.dtd.http=true`

There's nothing wrong with TestNG as such. Closing this issue.

**Comment by darkchoci** [comment]
@ghost is this problem resolved to you if yes please guide me how you did
@krmahadevan I am also facing the same issue i am unable to download the root certificate Could you please guide me how to do

**Comment by VengababuNutalapatiTR** [comment]
I am also facing the same issue i am unable to download the root certificate Could you please help me to resolve
