### ISSUE TITLE
Unable to execute tests with TestNg 7.3.0

### ISSUE THREAD

**Issue by tulsi26ram** [cbeust/testng#2351]
### TestNG Version
7.1.0 to 7.3.0

### Expected behavior
Tests should run without any exception/error from TestNg.xml or TestNg class

### Actual behavior
Getting the following exception

[ERROR] There was an error in the forked process
[ERROR] org/testng/IInvokedMethodListener2
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org/testng/IInvokedMethodListener2
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.ja
va:978)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.j
ava:56)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven 👎 
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse 👎 
- [ ] IntelliJ 👎 
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

public class TestNgTest{
    
             @Test
            public void testTestNgVersion(){
                s.o.p("Version "
             }

[testng.txt](https://github.com/cbeust/testng/files/5025740/testng.txt)

@krmahadevan @cbeust

**Comment by tulsi26ram** [comment]
Even I have tried with downloading the external jar (testng-7.3.0) with standalone java project as well. Still No luck. There is only one version of TestNg in my machine. (i.e 7.3.0)

**Comment by tulsi26ram** [comment]
####
[pom.txt](https://github.com/cbeust/testng/files/5025753/pom.txt)
 Here is the POM file used

**Comment by krmahadevan** [comment]
Question was already answered in https://groups.google.com/g/testng-users/c/701X49hll44/m/pZ3ZNdOZBQAJ
