### ISSUE TITLE
Unit test loads spring resources

### ISSUE THREAD

**Issue by wjx1990323** [cbeust/testng#2353]
### TestNG Version
> Note: only the latest version is supported

At present, unit test is the collection mode of @ springboottest and TestNG. However, every time a unit test is started, it will have to load resources (various configuration files, initialize spring containers, and establish various connections), which is very time-consuming.

Question:

1: Do you have a solution to support unit testing that can reuse the last resource? Or give us some advice

2: Do you know that other enterprises have solved such problems?

To achieve this goal, our idea is:

Start the container first, and then request to start the service when executing MVN test. This can solve the problem of multiple loading of resources. However, this approach is actually equivalent to the interface request server, which is different from the TestNG implementation. There are many changes to be made, and it should be compatible with the previous TestNG rollback and other functions, so I don't know whether this design idea is feasible?

**Comment by krmahadevan** [comment]
@wjx1990323 - Please feel free to elaborate if I got your query incorrectly.
TestNG does not have any role to play in loading resources etc., Those I believe is a function of SpringBootTest which lets you do this.
The only role that TestNG is playing is, the role of a test orchestrator wherein TestNG merely runs the Tests that have been defined by your project.

So I am not quite sure as to how this would be related to TestNG. Maybe its something that could take up as a question in a Spring related forum. 

You can also take a look at this article to see if it will help with giving you answers to some of your questions (I am not very conversant with Spring)

https://docs.spring.io/autorepo/docs/spring-framework/4.2.0.RC2/spring-framework-reference/html/integration-testing.html

**Comment by wjx1990323** [comment]
I understand. What I should ask is springbootest. Thank you very much

**Comment by krmahadevan** [comment]
Closing this issue since no further action is needed from TestNG side.
