### ISSUE TITLE
TestNG 7.3.0 Causes build failure "TestNG by default disables loading DTD from unsecured Urls"

### ISSUE THREAD

**Issue by QAthulhu** [cbeust/testng#2354]
### TestNG Version
7.3.0
Working fine on 7.1.0

### Expected behavior
Using mvn clean install, build is successful

### Actual behavior
Build failure
TestNG by default disables loading DTD from unsecured Urls. If you need to explicitly load the DTD from a http url, please do so by using the JVM argument [-Dtestng.dtd.http=true]

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.3.0</version>
		</dependency>
```
Changing it back to 7.1.0 fixes the problem

My suites:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Sanity Runner">
	<groups>
		<run>
			<include name="sanity" />
			<exclude name="not-finished" />
			<exclude name="real-device" />
			<exclude name="qa-env" />
		</run>
	</groups>
	<suite-files>
		<suite-file path="module-suites/authentication-suite.xml"></suite-file>
	</suite-files>
</suite>
```
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Authentication Suite" >
	<test name="Sign In Tests" >
		<classes>
			<class name="SignInTests" />
		</classes>
	</test>
</suite>
```

**Comment by krmahadevan** [comment]
@QAthulhu - There's nothing that can be done.

You need to follow one of the recommendations.

1. Either change `"http://testng.org/testng-1.0.dtd"` to `"https://testng.org/testng-1.0.dtd"`in your suite file (or)
2. Use the JVM argument `-Dtestng.dtd.http=true` when running your tests.

This behavior will not be reverted back.

**Comment by QAthulhu** [comment]
Just tried this and yup this is working now. Imo, the error message should have been more clear that I just needed to change http to https

Thanks!!

**Comment by cbeust** [comment]
Also, testng.org is configured to automatically redirect http traffic to https (try it: load the DTD on your browser and see the redirect,  http://testng.org/testng-1.0.dtd).

I'm curious what part of the HTTP stack is not following the redirect.

**Comment by sabi0** [comment]
TestNG uses local copy of DTD for "recognized" public IDs:
https://github.com/cbeust/testng/blob/518bd75212805eb5f6f6a9518616abb5fd454159/src/main/java/org/testng/xml/TestNGContentHandler.java#L113

Why don't you just keep the previous http URLs as "recognized" for backward compatibility. There is no security risk since the local resource will be used. (And if it cannot be loaded the fallback will go to https anyway.)
Besides it will eliminate unnecessary network access which currently happens when running with `-Dtestng.dtd.http=true`.
