### ISSUE TITLE
TestNG creates multiple Guice Module Instances

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2355]
When user resorts to using Guice as a dependency injection framework and clubs it with TestNG by setting a parent module via suite file, TestNG ends up creating multiple Parent module instances even though only one per `<test>` is only needed. 

For sample pls use the samples available as part of this PR 

https://github.com/cbeust/testng/pull/2350

**Comment by geminicaprograms** [comment]
Hi,

That is a showstopper for me the upgrade to anything newer than `6.14.13` (I have reproduced the same problem with 7.0.0).
Is there any timeline that it would get released?

Regards
Jacek
