### ISSUE TITLE
Testng @BeforeGroups is running in parallel with testcases in the group

### ISSUE THREAD

**Issue by DAWadehra2020** [cbeust/testng#2359]
I have 2 test classes TC1 & TC2, which extends to GroupClass. Group class contains the @BeforeGroups beforgrp method.
my suite xml has these classes with following suite settings
parallel="methods" thread-count="5"

now when I run the suite. 4 test methods from class TC1 & TC2 runs along with beforgrp method simultaneously.

but ideally Test case execution should have started after the execution beforgrp method.

TestNg version used is 6.14.3

**Comment by krmahadevan** [comment]
@velma thank you for taking the time to create a sample that shows the problem and also for taking the time to fix it as well.
