### ISSUE TITLE
Version 7.3.0 Tag

### ISSUE THREAD

**Issue by staley-robert** [cbeust/testng#2367]
### TestNG Version
7.3.0

### Expected behavior
A tag or branch is available in TestNG GitHub repository for version 7.3.0

### Actual behavior
I do not see a tag or branch for version 7.3.0 in TestNG GitHub repository

We're required to maintain a local repository and rebuild all open source libraries we use.  I have not been able to determine how I can obtain the TestNG source associated with version 7.3.0.  Would it be possible to create a tag for version 7.3.0?  If there is another way to accomplish this please let me know.  Thanks!

**Comment by cbeust** [comment]
I just pushed a 7.3.0 tag.

**Comment by staley-robert** [comment]
Thank You!
