### ISSUE TITLE
only priority 1 is executing across multiple classes when we execute Testng suite version 6.14.3

### ISSUE THREAD

**Issue by srujan13** [cbeust/testng#2370]
### TestNG Version
>6.14.3

### Expected behavior
All method with all Priority from all classes should be executed

### Actual behavior
only priority 1 is executed

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

**Class1**

```java
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class HomePage {
	@BeforeSuite
	public void login(){
		
		System.out.println("User Logged in");
	}

	@Test(priority=2)
	public void verifyLogoIsPresent(){
		
		System.out.println("Logo");
	}
	
	@Test(priority=1)
public void verifyEmailIsPresent(){
		
		System.out.println("Email");
	}
	@Test(priority=3)
public void verifyPasswordIsPresent(){
	
	System.out.println("Passwor");
}
	@Test(priority=4)
public void averifySubmitIsPresent(){
	
	System.out.println("Submit");
}
}
```

**Class 2**

```java
package XXX.regression.LoginPageTestCases;

import org.testng.annotations.AfterSuite;

import org.testng.annotations.Test;

public class LoginPage {

	@Test(priority=2)
	public void verifyLogoIsPresent(){
		
		System.out.println("LoginLogo");
	}
	
	@Test(priority=1)
public void verifyEmailIsPresent(){
		
		System.out.println("LoginEmail");
	}
	@Test(priority=5)
public void verifyPasswordIsPresent(){
	
	System.out.println("LoginPassword");
}
	@Test(priority=6)
public void verifySubmitIsPresent(){
	
	System.out.println("LoginSubmit");
}
	@AfterSuite
	public void logout(){
		
		System.out.println("User Logged out");
	}
}
```
Testing.xml
-----------

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="module1">
<test name="regressiontesting">
<classes>
<class name="XXX.regression.HomePageTestCases.HomePage" />
<class name="XXX.regression.LoginPageTestCases.LoginPage" />
</classes>
</test>
</suite>
```
**Output Actual** 

```
User Logged in
Email
LoginEmail
User Logged out
```
**Output expected**

```
User Logged in
Email
LoginEmail
Logo
LoginLogo
Passwor
Submit
LoginPassword
LoginSubmit
User Logged out
```

**Comment by wengm** [comment]
@srujan13 
Could you please paste your suite xml file?

I tried and cannot reproduce with your test case configuration. 
Check my test classes, suite and result on wiki page [Issue2370](https://github.com/cbeust/testng/wiki/Issue2370).

**Comment by krmahadevan** [comment]
@srujan13 - Please upgrade to TestNG `7.3.0` (latest released version of TestNG as of today and try again).

I have tried reproducing this issue using `7.3.0` and it works fine 

```bash
...
... TestNG 7.3.0 by CÃ©dric Beust (cedric@beust.com)
...

User Logged in
Email
Logo
Passwor
Submit
LoginEmail
LoginLogo
LoginPassword
LoginSubmit

PASSED: verifyEmailIsPresent
PASSED: verifyLogoIsPresent
PASSED: verifyPasswordIsPresent
PASSED: averifySubmitIsPresent
PASSED: verifyEmailIsPresent
PASSED: verifyLogoIsPresent
PASSED: verifyPasswordIsPresent
PASSED: verifySubmitIsPresent

===============================================
    2370_test
    Tests run: 8, Failures: 0, Skips: 0
===============================================


User Logged out


===============================================
2370_suite
Total tests run: 8, Passes: 8, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by Meng-Chou** [comment]
> @srujan13 - Please upgrade to TestNG `7.3.0` (latest released version of TestNG as of today and try again).
> 
> I have tried reproducing this issue using `7.3.0` and it works fine
> 
> ```shell
> ...
> ... TestNG 7.3.0 by CÃ©dric Beust (cedric@beust.com)
> ...
> 
> User Logged in
> Email
> Logo
> Passwor
> Submit
> LoginEmail
> LoginLogo
> LoginPassword
> LoginSubmit
> 
> PASSED: verifyEmailIsPresent
> PASSED: verifyLogoIsPresent
> PASSED: verifyPasswordIsPresent
> PASSED: averifySubmitIsPresent
> PASSED: verifyEmailIsPresent
> PASSED: verifyLogoIsPresent
> PASSED: verifyPasswordIsPresent
> PASSED: verifySubmitIsPresent
> 
> ===============================================
>     2370_test
>     Tests run: 8, Failures: 0, Skips: 0
> ===============================================
> 
> 
> User Logged out
> 
> 
> ===============================================
> 2370_suite
> Total tests run: 8, Passes: 8, Failures: 0, Skips: 0
> ===============================================
> 
> 
> Process finished with exit code 0
> ```

I have met the same problem: my test.xml is as the following:
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="module1">
<test name="regressiontesting" parallel=false>
<classes>
<class name="XXX.regression.HomePageTestCases.HomePage" />
<class name="XXX.regression.LoginPageTestCases.LoginPage" />
</classes>
</test>
</suite>

but when I changed the parallel to "true", all the cases can be run. But I want the cases run in serial not parallel.  Is this a bug in TestNg Framework? And Is there any other solutions expect upgrade testNg to 7.3.0
