### ISSUE TITLE
Unsanitized string passed into format string

### ISSUE THREAD

**Issue by Dmitry-Me** [cbeust/testng#2378]
This was introduced with this commit https://github.com/cbeust/testng/commit/34c0cc5e63011a588b042ce0a5b4683cd6b455fc

This line https://github.com/cbeust/testng/blob/34c0cc5e63011a588b042ce0a5b4683cd6b455fc/src/main/java/org/testng/xml/TestNGContentHandler.java#L520 now effectively does this:

1. first, four strings are concatenated, three of them are constants and the fourth one contains a filename.
2. then result of concatenation is passed into String.format() as its first argument.

A filename can contain percent symbols (at least on Windows) and if it contains any percent symbol then result of concatenation may be interpreted to have more than one format placeholder. Filenames should not be concatenated into format strings, they should be passed as %s parameters instead.

**Comment by krmahadevan** [comment]
@Dmitry-Me why not raise a PR to fix this ? Since you have spent time on analysing this.

**Comment by krmahadevan** [comment]
@cbeust @juherr - Since the changeset was very minor and restricted to just the message formation, I took the liberty of pushing the change directly to master.

**Comment by krmahadevan** [comment]
@Dmitry-Me - I took care of it.
