### ISSUE TITLE
on

### ISSUE THREAD

**Issue by dmitriy-zhydchenko** [cbeust/testng#2380]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
Empty bug. Closing this off
