### ISSUE TITLE
TestNG version should be specified in MANIFEST.MF

### ISSUE THREAD

**Issue by akozlova** [cbeust/testng#2382]
at least starting from 7.1.0 manifest doesn't contain information about current version, so the version can't be retrieved by tools

Background:
I try to workaround the problem that old testng versions do not recognise "https:"-dtd url and download it from internet which is not acceptable during different IDE activities (IntelliJ). 

Could you please write correct Implementation-Version to the MANIFEST.MF?
Thanks

**Comment by krmahadevan** [comment]
@akozlova - While this gets implemented, you can figure out the TestNG version today using the below approach

```java
System.err.println(org.testng.internal.Version.VERSION);
```

**Comment by akozlova** [comment]
Thanks but in order to use the workaround I would need to load class `Version` in the new classloader and check field by reflection, because IDE may bundle different version from what user has. I am also afraid of `internal` in the classname 

I stay with jar name for now, I hope people do not rename jars nowadays...

**Comment by juherr** [comment]
@akozlova For my understanding, why do you need the version? 
`internal` is supposed to be a warning for common users, not for 3rd party integration.
If you need something from the `internal` package, just warn us and we will make extra effort to keep it safe.
At least, some backports across versions can be done via https://github.com/testng-team/testng-remote
