### ISSUE TITLE
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM...>

### ISSUE THREAD

**Issue by shaburov** [cbeust/testng#2383]
### TestNG Version
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.3.0</version>
</dependency>

![image](https://user-images.githubusercontent.com/15269131/95619881-fa338b00-0a77-11eb-81bc-fabc596f0026.png)
![image](https://user-images.githubusercontent.com/15269131/95620321-a6757180-0a78-11eb-8efe-80fadcea6cd4.png)

### Expected behavior
No WARN in the log if suite.xml contains `<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">`

### Actual behavior
![image](https://user-images.githubusercontent.com/15269131/95620609-200d5f80-0a79-11eb-82f3-924108588d7d.png)

### Is the issue reproductible on runner?
IntelliJ v2020.2.3 (TestNG IDE plugin ver. 202.7660.26)

**Comment by krmahadevan** [comment]
@shaburov - Can you please show us what does your TestNG suite xml file look like ?

**Comment by shaburov** [comment]
@krmahadevan  If you look at the first screenshot, you will see the first lines from the file. Which you actually need.
But it's not hard for me.
This is the default file generated by the TestNG plugin in Intellij Idea.
`cat ~/Library/Caches/JetBrains/IntelliJIdea2020.2/temp-testng-customsuite.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default Suite">
  <test name="buggy">
    <classes>
      <class name="org.touchbit.buggy.spring.boot.starter.example.tests.ExampleTests2">
        <methods>
          <include name="test_1"/>
        </methods>
      </class> <!-- org.touchbit.buggy.spring.boot.starter.example.tests.ExampleTests2 -->
    </classes>
  </test> <!-- buggy -->
</suite> <!-- Default Suite -->
```

**Comment by krmahadevan** [comment]
@shaburov - 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default Suite">
  <test name="buggy">
```
Your suite file refers to the dtd via a "http" endpoint. That explains why you are seeing that warning in the first place. Sometime back I had file a bug with IntelliJ to fix the plugin such that by default it generates a suite xml file with only the `https` endpoint reference. 

Here's the defect https://youtrack.jetbrains.com/issue/IDEA-234765

Its been marked as fixed. Not sure when its going to be rolled out.

In the meantime You can use the JVM argument `-Dtestng.dtd.http=true` in your TestNG run configuration and get past this warning on the IDE

See below for screenshot. Closing this issue with resolution as **question answered**

![image](https://user-images.githubusercontent.com/909773/95671129-d9bb1c00-0bb0-11eb-9de0-2ede673acc99.png)
