### ISSUE TITLE
[BUG] ISuiteListener#onStart(ISuite) disabling methods does not work

### ISSUE THREAD

**Issue by shaburov** [cbeust/testng#2389]
### TestNG Version - 7.3.0
```java
public class ExecutionListener implements ISuiteListener {
    @Override
    public void onStart(ISuite suite) {
        for (ITestNGMethod method : suite.getAllMethods()) {
            ((BaseTestMethod) method).setEnabled(false);
        }
    }
}
```

### Expected behavior
Execution of all methods for the suite is disabled.

### Actual behavior
All methods started

### Is the issue reproductible on runner?
ALL

**Comment by krmahadevan** [comment]
@shaburov - There are no exposed APIs using which TestNG guarantees that this can be done via the `ISuiteListener`. So this cannot be treated as a bug.

Now coming to the specific use case that your sample seems to be doing (i.e., disable tests), you should be using `org.testng.IAnnotationTransformer` to disable tests and not in this way. IMO there's nothing additional that needs to be done from TestNG side in this.

@juherr WDYT ?

**Comment by juherr** [comment]
I agree with @krmahadevan. `ISuiteListener` is too late in the process because test methods are already selected.
Maybe an exception should be throw by `setEnabled` when it won't have any effect.

`IMethodInterceptor` can be used or `IAnnotationTransformer` too, as proposed by @krmahadevan.

**Comment by shaburov** [comment]
Do you have the described listener initialization scheme?
Example:
1 - IAnnotationTransformer
2 - IMethodInterceptor
<...>
15 - ISuiteListener
<...>

**Comment by krmahadevan** [comment]
@shaburov - You might want to take a look at this test class [ListenerInvocationDefaultBehaviorTest](https://github.com/cbeust/testng/blob/master/src/test/java/test/listeners/ordering/ListenerInvocationDefaultBehaviorTest.java)
