### ISSUE TITLE
Stack trace truncated

### ISSUE THREAD

**Issue by tekumara** [cbeust/testng#239]
When viewing the stack trace of a test failure in the TestNG eclipse plugin the stack trace is truncated and I can't see the line of my test that failed. This is a particular problem when using AbstractTransactionalTestNGSpringContextTests - all I see is the outer spring exception. 

See screenshot: http://i.imgur.com/SLmuw.png

In the stacktrace in the screenshot I can see the transaction died and rolled back, but I have no idea why.

JUnit (using the spring junit runner) will show me the nested exceptions and the line in my test that failed in the stack trace.

**Comment by krmahadevan** [comment]
ping @missedone - Nick can you please help take a look at this one ?

**Comment by krmahadevan** [comment]
Migrated to https://github.com/cbeust/testng-eclipse/issues/450
