### ISSUE TITLE
Suite.xml files attempt to make web request when suite references standard TestNG DTD using HTTP

### ISSUE THREAD

**Issue by robbytx** [cbeust/testng#2403]
### TestNG Version
7.3.0

### Expected behavior
Suite file referencing `http://testng.org/testng-1.0.dtd` should NOT attempt to load the DTD URL, and therefore should not require `-Dtestng.dtd.http=true`.

### Actual behavior
The `http` version of the DTD URL is unrecognized by `Parser.isUnRecognizedPublicId`, and therefore TestNG complains that it needs the `testng.dtd.http` property to download the DTD from the URL.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
The following suite file is generated by IntelliJ 2020.2.3, when I right-click to run a class:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default Suite">
  <test name="myproject">
    <classes>
      <class name="example.TestClass"/>
    </classes>
  </test> <!-- myproject -->
</suite> <!-- Default Suite -->
```

**Comment by robbytx** [comment]
As I've mentioned on https://github.com/cbeust/testng/issues/2022#issuecomment-720155375, I believe this is a regression in 7.3.0 due to https://github.com/cbeust/testng/commit/33e600fd1d2d0c6783272ff45266a02999a05a4a#diff-9ca66a84545cd97fc9ceac35fe5494a5c5e1a1eb0a08aaa7abdf2a5ca7eedd24.

**Comment by krmahadevan** [comment]
@robbytx - There was a discrepancy with the way in which we were loading the DTDs. TestNG should always first try to load the DTD embedded in the jar, based on whether the DTD matches with what exists in the jar. only if that fails we should be trying to load from the URL.

This was fixed as part of https://github.com/cbeust/testng/commit/3f67d3e0df09dec5540fd22012e1d36f8d0f42fe

Can you please try using the snapshot version of TestNG ? (I think currently there's an issue with the publish snapshots to maven central piece). So you may have to build TestNG locally to test this out.

You can do that using the following:

1. Clone the codebase.
2. Publish to local maven repository using the command `./gradlew clean publishToMavenLocal -x test -x signCustomPublication`
3. Add a dependency to `7.4.0-SNAPSHOT` to your local project and try again.

Please post back the results of what you find.

**Comment by askfor** [comment]
This was also discussed here https://github.com/cbeust/testng/issues/2384
I haven't tried the snapshot version but it seems 3f67d3e didn't touch the parts discussed in 2384

> @robbytx - There was a discrepancy with the way in which we were loading the DTDs. TestNG should always first try to load the DTD embedded in the jar, based on whether the DTD matches with what exists in the jar. only if that fails we should be trying to load from the URL.
> 
> This was fixed as part of [3f67d3e](https://github.com/cbeust/testng/commit/3f67d3e0df09dec5540fd22012e1d36f8d0f42fe)
> 
> Can you please try using the snapshot version of TestNG ? (I think currently there's an issue with the publish snapshots to maven central piece). So you may have to build TestNG locally to test this out.
> 
> You can do that using the following:
> 
> 1. Clone the codebase.
> 2. Publish to local maven repository using the command `./gradlew clean publishToMavenLocal -x test -x signCustomPublication`
> 3. Add a dependency to `7.4.0-SNAPSHOT` to your local project and try again.
> 
> Please post back the results of what you find.

**Comment by krmahadevan** [comment]
@askfor - Just to re-iterate, TestNG will mandate that the DTD URL has to be `https` and cannot/should not be `http`. 
So please try using the snapshot, and then post back on what else is missing. That will be easier to manage and fix.

**Comment by robbytx** [comment]
I agree with this comment in #2384:

> Or that the non-HTTPS URL is not in the URLSlist (note that TESTNG_DTD_URL and HTTPS_TESTNG_DTD_URL are exactly the same).

This is exactly what I was pointing out. The HTTP version of the DTD URL is no longer recognized by TestNG (due to an over aggressive search+replace) so it attempts to load that DTD over the network. 

I think the solution is to rework the constants so that the HTTP DTD URLs are again recognized, so that TestNG will NOT attempt to load those URLs.

**Comment by krmahadevan** [comment]
@robbytx - TestNG will no longer honour any `http` urls for loading DTDs. It has to mandatorily be `https` or you use the JVM argument to override the behaviour. 

There is no going back to working with `http` URLs by default. 

Behaviour has changef.

**Comment by askfor** [comment]
I think the problem is when "-Dtestng.dtd.http=true" is provided, TESTNG should not load http://testng.org/testng-1.0.dtd from the network.

**Comment by krmahadevan** [comment]
@askfor

TestNG no longer has a http hosted DTD. So the removal of http endpoint is justified ( I think as of today a redirection has been setup. But it can be removed from the website and thus forcing everyone to use https )

For any other URL from where a DTD is to be loaded and if the user wants it to be from a http then they need to specify the JVM argument.

**Comment by askfor** [comment]
> @askfor
> 
> TestNG no longer has a http hosted DTD. So the removal of http endpoint is justified ( I think as of today a redirection has been setup. But it can be removed from the website and thus forcing everyone to use https )
> 
> For any other URL from where a DTD is to be loaded and if the user wants it to be from a http then they need to specify the JVM argument.

Sorry I didn't make my point clear.  I think when the DTD is "http://testng.org/testng-1.0.dtd" which intellij's testing plugin currently using, testng should load it from jar instead of load it from network.

**Comment by krmahadevan** [comment]
@askfor - That is why I was requesting you to please give a try using `7.4.0-SNAPSHOT` and see if that addresses your issue, because I recently fixed a defect around that area (have shared the commit ID in my earlier comment)

**Comment by askfor** [comment]
Got an error running mvn clean install after change to 7.4.0-SNAPSHOT

```
There was an error in the forked processjava.lang.NoClassDefFoundError: com/google/inject/Module
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked processjava.lang.NoClassDefFoundError: com/google/inject/Module
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:248)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)

```

**Comment by krmahadevan** [comment]
Please add a dependency for guice and try again

https://mvnrepository.com/artifact/com.google.inject/guice/3.0

**Comment by robbytx** [comment]
@krmahadevan I've followed your instructions to build `7.4.0-SNAPSHOT` from the master branch, and I've confirmed that I still get the following error when running TestNG via Intellij (confirming that my classpath references: `/Users/morgan/.m2/repository/org/testng/testng/7.4.0-SNAPSHOT/testng-7.4.0-SNAPSHOT.jar`:
```
org.testng.TestNGException: 
TestNG by default disables loading DTD from unsecured Urls. If you need to explicitly load the DTD from a http url, please do so by using the JVM argument [-Dtestng.dtd.http=true]
	at org.testng.xml.TestNGContentHandler.resolveEntity(TestNGContentHandler.java:123)
	at com.sun.org.apache.xerces.internal.util.EntityResolverWrapper.resolveEntity(EntityResolverWrapper.java:110)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(XMLEntityManager.java:997)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1151)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.testng.xml.XMLParser.parse(XMLParser.java:39)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:162)
	at org.testng.xml.Parser.parse(Parser.java:248)
	at org.testng.TestNG.parseSuite(TestNG.java:324)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:376)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:39)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

**Comment by robbytx** [comment]
> Please add a dependency for guice and try again
BTW -- this should really be an [optional Maven dependency](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#optional-dependencies).  If a project doesn't use Guice, then TestNG should force it into the classpath.

I personally have used `<exclusions>`, but I'd rather see libraries declare such dependencies as `<optional>true</optional>`, so they only take effect if said dependency already exists in the project.

**Comment by robbytx** [comment]
Related: In `7.3.0`, it is possible to exclude Guide using `<exclusions>`, but it seems like https://github.com/cbeust/testng/commit/ee6cbabdbf3b5c3eec7685007e4d2d97136308d1 has regressed that behavior, such that now Guice is a required dependency on the classpath, even if the project does NOT use Guice.

**Comment by robbytx** [comment]
Furthermore, TestNG `7.4.0-SNAPSHOT` does not appear to declare a dependency on Guice at all, so that's why I'm getting `java.lang.NoClassDefFoundError: com/google/inject/Module`, and I think that's also why @askfor was seeing the same.

As I stated in my comment above, I'd personally love to see TestNG declare Guice as an optional dependency, such that the expected version is factored into [Maven dependency convergence](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html), but the library itself does NOT require Guice to exist on the classpath in order to execute.

**Comment by robbytx** [comment]
I've reproduce this problem using Maven with the following files:

`pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>testng-2403</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.4.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.2.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/suites/suite.xml</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

`src/test/suites/suite.xml`:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="MySuite">
    <test name="myproject">
        <classes>
            <class name="example.TestClass"/>
        </classes>
    </test>
</suite>
```

`src/test/java/example/TestClass.java` (essentially irrelevant to this issue):
```java
package example;

import org.testng.annotations.Test;

public class TestClass {

    @Test
    public void test() {
        // this should pass
    }
}
```

**Comment by krmahadevan** [comment]
@robbytx 

Responding to your comment in https://github.com/cbeust/testng/issues/2403#issuecomment-721508492

IntelliJ does not use TestNG from the CLASSPATH. It uses an embedded jar and that explains why you are seeing the problem when you run via IntelliJ. The proper way of testing the fix (for the DTD discrepancy) would be to install TestNG jar to the local maven repo, and then add it as a dependency and run a test via the commandline using a build tool (Gradle/Maven) (or) create a main method and then use the TestNG main() method to run your test (That way you will bypass the IDE integration and prune all IDE side effects)

FWIW, I have already filed a defect with IntelliJ on the TestNG plugin generating suite files with `http` and thus triggering this problem. Refer https://youtrack.jetbrains.com/issue/IDEA-234765

**Comment by krmahadevan** [comment]
@robbytx 

Responding to your comment in https://github.com/cbeust/testng/issues/2403#issuecomment-721512807
Like I said before, using `http` as a URL in the DTD is NO LONGER an option. If you use it without the JVM argument, you will see TestNG throw errors. It has to be mandatorily `https` (or) you use the JVM argument.

What I am trying to look for as feedback here is just the below

```
Given I have a suite file
When the URL has a DTD url as http://testng.org/testng-1.0.dtd, 
Then TestNG should use the DTD from the jar and not from the internet.
```

**Comment by krmahadevan** [comment]
@robbytx 

Responding to your comments on the Maven dependency discrepancy

https://github.com/cbeust/testng/issues/2403#issuecomment-721509600
https://github.com/cbeust/testng/issues/2403#issuecomment-721509600
https://github.com/cbeust/testng/issues/2403#issuecomment-721511652

Please note that when TestNG is being released, it uses a [Kobalt build file](https://github.com/cbeust/testng/blob/master/kobalt/src/Build.kt) (atleast thats how I know it used to be).

Very recently @cbeust added [Github workflow integration](https://github.com/cbeust/testng/blob/master/.github/workflows/publish-maven-central.yml) which now uses the gradle build file itself.

I am not very sure on the release process. Either ways I would suggest that we extract out this discrepancy as a separate defect rather than club that here, so that its easy to track issues to closure.

@cbeust Please add if I have missed anything.

**Comment by robbytx** [comment]
@krmahadevan thank you for your replies.  Please allow me to clarify a few things.

### On this particular issue

> Like I said before, using http as a URL in the DTD is NO LONGER an option. If you use it without the JVM argument, you will see TestNG throw errors. It has to be mandatorily https (or) you use the JVM argument.

Right... I understand that using HTTP for an actual network request is no longer supported, and that is fine.

```
Given I have a suite file
When the URL has a DTD url as https://testng.org/testng-1.0.dtd, 
Then TestNG should use the DTD from the jar and not from the internet.
```
This is exactly the behavior I am expecting and not seeing, hence this bug report:

> Expected behavior: Suite file referencing http://testng.org/testng-1.0.dtd should NOT attempt to load the DTD URL, and therefore should not require -Dtestng.dtd.http=true.

As I've demonstrated [above](#issuecomment-721512807), this test case is still failing with 7.4.0-SNAPSHOT built from `master` (as of bdf1c95501d9b6afb8a6e1a038dbdfbbf7acc378).

### On other points

Re: Guice
> Either ways I would suggest that we extract out this discrepancy as a separate defect rather than club that here, so that its easy to track issues to closure.

I will file this as a separate issue.

Re: IntelliJ
> IntelliJ does not use TestNG from the CLASSPATH. It uses an embedded jar and that explains why you are seeing the problem when you run via IntelliJ.

I believe this was the behavior in the past, but it is not the case in latest version I'm running (IntelliJ 2020.2.3 with TestNG plugin version 202.7660.26 on Mac).  When I run a TestNG test via IntelliJ, the plugin forks a JVM process with the following command-line (which is visible in the first line of the Run/Debug console):
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java
-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:54917,suspend=y,server=n
-ea
-Didea.test.cyclic.buffer.size=1048576
-javaagent:/Users/morgan/Library/Caches/JetBrains/IntelliJIdea2020.2/captureAgent/debugger-agent.jar
-Dfile.encoding=UTF-8
-classpath
/Applications/IntelliJ\ IDEA.app/Contents/lib/idea_rt.jar:
/Applications/IntelliJ\ IDEA.app/Contents/plugins/testng/lib/testng-rt.jar:
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/charsets.jar:
...
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/tools.jar:
/Users/morgan/src/testng-2403/target/test-classes:
/Users/morgan/src/testng-2403/target/classes:
/Users/morgan/.m2/repository/org/testng/testng/7.4.0-SNAPSHOT/testng-7.4.0-SNAPSHOT.jar:
/Users/morgan/.m2/repository/com/beust/jcommander/1.78/jcommander-1.78.jar:
/Users/morgan/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar:
/Users/morgan/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:
/Users/morgan/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:
/Users/morgan/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar:
/Users/morgan/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:
/Users/morgan/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:
/Users/morgan/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:
/Users/morgan/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:
/Users/morgan/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:
/Applications/IntelliJ IDEA.app/Contents/plugins/testng/lib/jcommander-1.27.jar
com.intellij.rt.testng.RemoteTestNGStarter
-usedefaultlisteners
false
-socket54916
@w@/private/var/folders/6l/8lk5wyq94_39mxfl6_2nrsch0000gn/T/idea_working_dirs_testng.tmp
-temp
/private/var/folders/6l/8lk5wyq94_39mxfl6_2nrsch0000gn/T/idea_testng.tmp
```
You can see that the classpath contains a reference to `testng-7.4.0-SNAPSHOT.jar`, so it should be loading TestNG classes from the build JAR, and if I put a breakpoint in a TestNG class, that appears to be the case.

The only IntelliJ-specific modules on the classpath are `idea_rt.jar` (which is unrelated to TestNG), `testng-rt.jar` (which only contains classes in the `com.intellij.rt.testng` package), and `jcommander-1.27.jar` (at the end of the classpath, which is preempted by TestNG's own `jcommander-1.78.jar` earlier in the classpath).  

AFAICT IntelliJ's `testng-rt.jar` is simply used to bootstrap the process and add test listeners, but otherwise it invokes `org.testng.TestNG` to do the work of parsing the suite XML and running the tests.

**Comment by krmahadevan** [comment]
@robbytx - 

> This is exactly the behavior I am expecting and not seeing, hence this bug report:

This is not true. TestNG right now loads up the URL from the resource itself.

Try to setup a breakpoint in [here](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/TestNGContentHandler.java#L115) and then step through. 

I am seeing that TestNG is loading the embedded DTD via the call to `loadDtdUsingClassLoader()` [here](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/TestNGContentHandler.java#L128)

**Comment by robbytx** [comment]
@krmahadevan 

> Try to setup a breakpoint in here and then step through.

When I do this, the `TestNGContentHandler.resolveEntity` method:
 * skips the first conditional on line 118 because `publicId` is `"http://testng.org/testng-1.0.dtd"`
 * enters the next conditional on line 121 because `Parser.isUnRecognizedPublicId(publicId)` return `false` for `"http://testng.org/testng-1.0.dtd"`
 * throw `TestNGException` on line 123 because `RuntimeBehavior.useSecuredUrlForDtd() && isUnsecuredUrl(publicId)` is true.

This behavior is evident in the stack trace I [provided earlier](https://github.com/cbeust/testng/issues/2403#issuecomment-721508492) in my tests against `7.4.0-SNAPSHOT`:
```
org.testng.TestNGException: 
TestNG by default disables loading DTD from unsecured Urls. If you need to explicitly load the DTD from a http url, please do so by using the JVM argument [-Dtestng.dtd.http=true]
	at org.testng.xml.TestNGContentHandler.resolveEntity(TestNGContentHandler.java:123)
```

I believe this problem is due to the fact that `Parser.isUnRecognizedPublicId(publicId)` is *incorrectly* returning `false` for `"http://testng.org/testng-1.0.dtd"`, which is directly connected to the fact that https://github.com/cbeust/testng/commit/33e600fd1d2d0c6783272ff45266a02999a05a4a#diff-9ca66a84545cd97fc9ceac35fe5494a5c5e1a1eb0a08aaa7abdf2a5ca7eedd24 modified `TESTNG_DTD_URL` to no longer use `http`, and therefore the [Parser.URLS field](https://github.com/cbeust/testng/blob/33e600fd1d2d0c6783272ff45266a02999a05a4a/src/main/java/org/testng/xml/Parser.java#L36) no longer contains the URL `"http://testng.org/testng-1.0.dtd"`.

This is why I [suggested earlier](#issuecomment-720468801):
> I think the solution is to rework the constants so that the HTTP DTD URLs are again recognized, so that TestNG will NOT attempt to load those URLs.

**Comment by krmahadevan** [comment]
@robbytx - I think we are going around in circles. To the best of my understanding, TestNG is not supposed to look at anything that is `http`.  But for some reason you are not accepting it or not getting it.

> I think the solution is to rework the constants so that the HTTP DTD URLs are again recognized, so that TestNG will NOT attempt to load those URLs.

This will not be possible. We changed the urls to use `https` for a reason (fix security vulnerability). So that cannot be reverted.

Please change the URLs in your suite file, and then go through the debugging and let me know if its a problem.
If you are still not convinced, then I will step aside and have either @cbeust  or @juherr  help you out with this.

Alternatively you can raise a PR and we can vet it out as well. But like I said, having TestNG recognise any `http` URLs is NOT an option.

**Comment by robbytx** [comment]
@krmahadevan 
> I think we are going around in circles. To the best of my understanding, TestNG is not supposed to look at anything that is http. But for some reason you are not accepting it or not getting it.

The point I'm not understanding is whether TestNG should still have the behavior that [you suggested above](#issuecomment-721523563):

> What I am trying to look for as feedback here is just the below
```
Given I have a suite file
When the URL has a DTD url as https://testng.org/testng-1.0.dtd, 
Then TestNG should use the DTD from the jar and not from the internet.
```

Can you please clarify whether that behavior is expected?

Because that behavior is NOT occurring, as I've demonstrated.  Restoring that behavior would be advantageous to avoid breaking compatibility for no particular security benefit with existing suite files that may be difficult for developers to modify.

If you are intentionally breaking compatibility with this use case, then I'll be disappointed, but we would at least agree that this ticket should be closed.  

Otherwise, this behavior was unintentionally regressed in `7.3.0` and should be fixed.  (How you choose to fix the issue is up to you; I was simply providing a suggestion about reworking the `URLS` constant, but perhaps that's not the best solution.)

I think some of the confusion may stem from the issue title, so I will revise it to clarify that I'm explicitly talking about the (formerly-)recognized DTD URLs.

**Comment by robbytx** [comment]
Also, I've updated [my comment yesterday](#issuecomment-723531552) since I realized that I had indicated `Parser.isUnRecognizedPublicId(publicId)` was returning `false` rather than `true`.  It's obviously returning `true` because it enters the conditional, rather than skipping it.  Perhaps that was also a source of confusion for you.

**Comment by juherr** [comment]
It looks like a duplicate of https://github.com/cbeust/testng/issues/2384

HTTP should not be allowed by default, except for the schemas included in the jar and referred to by the "official" URI.
As said in the other issue, the problem is a bad copy/paste which should be rollbacked for this file: https://github.com/cbeust/testng/issues/2384#issuecomment-715589164

**Comment by krmahadevan** [comment]
@robbytx - I have pushed a fix that revamps the logic a bit. The commit message should explain in detail what i have done on that PR. Can you please rebuild master and try this out once again and tell me what you see ?

As long as you are having `testng.org` in the system url, we will now try to load the DTD embedded in the jar, and if that fails, only then we will now fall back to reaching `https://testng.org` (Note that we still will not hit `http://testng.org` and we will not honour the disable secure url JVM argument also.

That JVM argument is now going to be honoured only when your suite file refers to a 3rd party domain that hosts the DTD

**Comment by robbytx** [comment]
Yes, it is working now -- thank you for fixing it.

At the risk of being rude, I can't help but observe that this regression could have been avoided if this type of behavior were covered by a unit test, and I'll note that your fix does not contain a unit test, so this behavior could be regressed in the future.

**Comment by krmahadevan** [comment]
@robbytx - Thanks for confirming that the fix works fine.

> At the risk of being rude, I can't help but observe that this regression could have been avoided if this type of behavior were covered by a unit test, and I'll note that your fix does not contain a unit test, so this behavior could be regressed in the future.

Sure. Feedback taken. On the flip-side of not sounding blunt, adding a unit test for this would be a bit more involved effort, since 

* I would have to figure out a mechanism that detects if the classloading was resorted to. 
* I would also need to figure out a mechanism that would intercept a call to the internet and then fake it. 

I didn't have the time. Also I self concluded that this is not a functionality that is going to be changing a lot over time and so I did a quick cost effort weighing in and *intentionally* skipped adding a test.

But all said and done, if you have any ideas on how to go about adding a test for this, please feel free to contribute. If it's via a PR, it's even more merrier. We will be more than happy to get it vetted out and merged.
