### ISSUE TITLE
Regarding TestNG issue.Please assist me

### ISSUE THREAD

**Issue by aparnalavanuru** [cbeust/testng#2408]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Here is my code Reading multiple data using dataProvider
[register.xlsx](https://github.com/cbeust/testng/files/5505856/register.xlsx)

-----------------------------

package com.selpractise.Test1;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;

import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class ReadData {
	public static FileInputStream fis;
	public static XSSFWorkbook workbook;

    public static WebDriver d;
    String chrome_path;
    
    public static XSSFSheet worksheet;
    public static DataFormatter formatter= new DataFormatter();
    public static String file_location = "C:\\Users\\Amar\\eclipse-workspace\\com.selpractise\\src\\test\\resources\\register.xlsx";
    static String SheetName= "Sheet1";
    public  String Res;

    public int DataSet=-1;
 
	  @BeforeMethod
      public void login() throws IOException
       {
	 
	   System.setProperty("webdriver.gecko.driver", "C:\\Users\\Amar\\Downloads\\geckodriver-v0.27.0-win64\\geckodriver.exe");
	   d=new FirefoxDriver();
	   d.get("http://automationpractice.com/index.php");
	   
       }
	  @Test //Test method
	  (dataProvider="ReadVariant") //It get values from ReadVariant function method
	   
	 
	  
	 
		public void AddVariants(String email,String first,String last,String pass,String add,String city,String state,String zip,String phone,String alias)
		{
		  DataSet++;
		  System.out.println("NAme of product available are:" +email);
		  System.out.println("Weight for products are:" +first);
		 
		   
		  WebDriverWait wait =  new WebDriverWait(d, 90);
		   wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[@class='login']")));
			System.out.println(email);
			d.findElement(By.xpath("//a[@class='login']")).click();
			d.findElement(By.xpath("//input[@id='email_create']")).clear();
			d.findElement(By.xpath("//input[@id='email_create']")).sendKeys(email);
			d.findElement(By.id("customer_firstname")).clear();
			d.findElement(By.id("customer_firstname")).sendKeys(first);
			d.findElement(By.id("customer_lastname")).clear();
			d.findElement(By.id("customer_firstname")).sendKeys(last);
			d.findElement(By.id("passwd")).clear();
			d.findElement(By.id("passwd")).sendKeys(pass);
			d.findElement(By.id("address1")).clear();
			d.findElement(By.id("address1")).sendKeys(add);
			d.findElement(By.id("city")).clear();
			d.findElement(By.id("city")).sendKeys(city);
			WebElement drop=d.findElement(By.id("id_state"));
			drop.click();
			Select s=new Select(drop);
			s.selectByVisibleText(state);
			d.findElement(By.id("postcode")).clear();
			
			d.findElement(By.id("postcode")).sendKeys(zip);
			d.findElement(By.id("phone_mobile")).clear();
			d.findElement(By.id("phone_mobile")).sendKeys(phone);
			d.findElement(By.id("alias")).clear();
			
			d.findElement(By.id("alias")).sendKeys(alias);
			d.findElement(By.xpath("//span[contains(text(),'Register')]")).click();
		}
		@DataProvider
		
	    public static Object[][] ReadVariant() throws IOException
	    {
	    FileInputStream fileInputStream= new FileInputStream(file_location); //Excel sheet file location get mentioned here
	        workbook = new XSSFWorkbook (fileInputStream); //get my workbook 
	        worksheet=workbook.getSheet(SheetName);// get my sheet from workbook
	        XSSFRow Row=worksheet.getRow(0);     //get my Row which start from 0   
	     
	        int RowNum = worksheet.getPhysicalNumberOfRows();// count my number of Rows
	        int ColNum= Row.getLastCellNum(); // get last ColNum 
	         
	        Object Data[][]= new Object[RowNum-1][ColNum]; // pass my  count data in array
	         
	            for(int i=0; i<RowNum-1; i++) //Loop work for Rows
	            {  
	                XSSFRow row= worksheet.getRow(i+1);
	                 
	                for (int j=0; j<ColNum; j++) //Loop work for colNum
	                {
	                    if(row==null)
	                        Data[i][j]= "";
	                    else
	                    {
	                        XSSFCell cell= row.getCell(j);
	                        if(cell==null)
	                            Data[i][j]= ""; //if it get Null value it pass no data 
	                        else
	                        {
	                            String value=formatter.formatCellValue(cell);
	                            Data[i][j]=value; //This formatter get my all values as string i.e integer, float all type data value
	                        }
	                    }
	                }
	            }
	 
	        return Data;
	    }
}

TraceError msg
-----------------------
java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at com.selpractise.Test1.ReadData.ReadVariant(ReadData.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 20 more

**Comment by krmahadevan** [comment]
@aparnalavanuru the exception seems to suggest that the problem is in your data provider. Please fix your data provider. 

Request you to post queries on TestNG on the TestNG Google groups. We would like to keep user support confined to the forums and use GitHub issues for tracking bugs.

**Comment by aparnalavanuru** [comment]
@krmahadevan  the dataProvider I have used nothing seems to have issues in it. Can you please elaborate what you are trying to convey

**Comment by krmahadevan** [comment]
@aparnalavanuru 

I am suggesting that you fix this problem 

```
Caused by: java.lang.NullPointerException
at com.selpractise.Test1.ReadData.ReadVariant(ReadData.java:112)
```

**Comment by aparnalavanuru** [comment]
@krmahadevan 
java.lang.NullPointerException

above is the issue everytime i am facing.
Kindly assit

**Comment by krmahadevan** [comment]
@aparnalavanuru that exception is not from TestNG. You would need to set breakpoints at the place where the Null pointer exception arises and backtrace from there. 

For user support ( which is what you are looking for ) please use the TestNG Google forums ( like to it available in the bug you filed above )
