### ISSUE TITLE
Annotations for finding Flutter UI Elements

### ISSUE THREAD

**Issue by ajschwieterman** [cbeust/testng#2410]
In the native Appium drivers, annotations can be added to a MobileElement variable in replacement of using the traditional `driver.findElementById()` method. Having these annotations for Flutter finder methods, like valueKey, would be very valuable.  [Flutter Driver Reference Issue](https://github.com/truongsinh/appium-flutter-driver/issues/108)
<img width="653" alt="96634588-bb5bcb80-12e8-11eb-9f94-93d17f6a755f" src="https://user-images.githubusercontent.com/50152740/98682011-646a7480-2331-11eb-9879-d2b88ffcda70.png">

**Comment by krmahadevan** [comment]
@ajschwieterman you sure if this issue is related to TestNG ?

**Comment by ajschwieterman** [comment]
@shibupanda told me to raise a proposal on this project.

**Comment by krmahadevan** [comment]
@ajschwieterman - TestNG is a test runner for running your Java based tests. The ask that you have logged seems to have nothing to do with what TestNG offers as capabilities.

**Comment by krmahadevan** [comment]
@ajschwieterman - I went through your original issue https://github.com/truongsinh/appium-flutter-driver/issues/108 and have logged a question there as well. As far as I can tell, TestNG has no role to play in your ask.

**Comment by shibupanda** [comment]
@krmahadevan look like this is coming from java-client so I will try to collaborate there.
We can close this issue.

**Comment by krmahadevan** [comment]
@shibupanda thanks. Closing this issue.
