### ISSUE TITLE
New feature TestNG - getFactoryMethodParamsInfo on ConfigurationMethod

### ISSUE THREAD

**Issue by OliverCzerman** [cbeust/testng#2426]
### TestNG Version
7.3.0

### Expected behavior
I would like to access the factory parameters from `ConfigurationMethod`.
This should work when `method.getTestMethod()` is `ConfigurationMethod`

```java
@Override
public void beforeInvocation(final IInvokedMethod method, final ITestResult testResult, final ITestContext context) {
        method.getTestMethod().getFactoryMethodParamsInfo()
}
```

### Actual behavior
 `method.getTestMethod().getFactoryMethodParamsInfo()` returns null and not ParameterInfo class

### Is the issue reproducible on runner?

I use IntelliJ and maven project.

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
I attached the sample.
[testng_test.zip.zip](https://github.com/cbeust/testng/files/5596394/testng_test.zip.zip)

**Comment by krmahadevan** [comment]
@OliverCzerman - I went back and checked this one. The support for retrieving configuration parameters are already present. You need to do it like below ( read it from `testResult.getMethod().getFactoryMethodParamsInfo().getParameters()`)

```java
import java.util.Arrays;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestContext;
import org.testng.ITestResult;

public class MyMethodListener implements IInvokedMethodListener {

  @Override
  public void beforeInvocation(IInvokedMethod method, ITestResult testResult,
      ITestContext context) {
    if (method.isConfigurationMethod()) {
      return;
    }
    System.out.println("Factory params: " + Arrays
        .toString(testResult.getMethod().getFactoryMethodParamsInfo().getParameters()));
  }
}
```

And this is the test class

```java
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(MyMethodListener.class)
public class SimpleTest {

  @DataProvider(name = "constructorArguments")
  public static Object[][] constructorArguments() {
    return new Object[][]{
        {1, false},
        {2, true},
        {3, false},
        {4, true},
    };
  }

  @Factory(dataProvider = "constructorArguments")
  public SimpleTest(int number, final boolean bool) {
  }

  @BeforeClass
  public void setup() {
  }

  @Test
  public void test() {
  }
}
```

And here's the execution output

```
Factory params: [4, true]
Factory params: [2, true]
Factory params: [3, false]
Factory params: [1, false]

===============================================
Default Suite
Total tests run: 4, Passes: 4, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by OliverCzerman** [comment]
Hi Krmahadevan,

Please remove this from your code:
 **if (method.isConfigurationMethod()) {
      return;
    }**
That is the point in this issue, that it is ConfigurationMethod. You just get the params in the beforeInvocation of the test.

**Comment by krmahadevan** [comment]
@OliverCzerman - Thanks for re-iterating that you were looking for `ConfigurationMethod`. For some reason I always kept reading it as `FactoryMethod`.
