### ISSUE TITLE
Seggregate Dependency Injection out as a clear implementation

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2429]
Currently TestNG blends in references to a lot of Guice class references within `ITestContext` and `TestRunner` and so it gives a feel that Guice backed DI is tightly coupled with TestNG.

More details on the ask can be found in the below discusssions

https://github.com/juherr/testng/commit/2d04dd837c2277b17933796e5fb009a1fb505778#r44699315

https://github.com/cbeust/testng/pull/2424

The expectation is that we should clean up all Guice related references to `Stage`, `Module`, `Injector` and have them move out of `ITestContext`, `TestRunner` and all other places.

**Comment by juherr** [comment]
@krmahadevan  I like this comment: https://github.com/juherr/testng/commit/2d04dd837c2277b17933796e5fb009a1fb505778#r44705346

> I was thinking of neither of them. Ideally speaking the Guice is being used by TestNG just for managing object creation life cycle. So the ITestContext doesn't need all of that, but merely needs to be exposing an ObjectProvider and this provider can be a SimpleObjectProvider and GuiceBackedObjectProvider
> So ITestContext would just have a method called ObjectProvider getObjectProvider() and all of the Guice DI class references should be hidden behind GuiceBackedObjectProvider.
>
> So the first step would be for us to deprecate all the Guice references from ITestContext and everywhere else, and have them confined to just GuiceBackedObjectProvider which would internally just use GuiceHelper.

That's exactly what I tried. But it is not a so easy job :)

**Comment by krmahadevan** [comment]
@juherr am glad that am also thinking on the same lines as you. 

Yeah I agree it's not a straightforward thing. I will also see if I can come up with something for solving this as a PR.
