### ISSUE TITLE
Publish snapshot builds to Central on each update of the default branch

### ISSUE THREAD

**Issue by vlsi** [cbeust/testng#2438]
### TestNG Version

`latest`

### Expected behavior

Each merge to the default branch should publish the recent snapshot builds.

### Actual behavior

:(

**Comment by juherr** [comment]
Related to #2391

**Comment by vlsi** [comment]
jitpack requires users to configure extra repository, so publishing to Central would help as well

**Comment by juherr** [comment]
As I know, Maven central doesn't provide Snapshot hosting.
But sonatype oss does.
It means you'll have to add at least this repository.
I agree sonatype is maybe more usual than jitpack.

**Comment by vlsi** [comment]
Well, technically speaking, the proper name for "Maven Central" is Sonatype OSSRH (which kindly allows hosting for both release and snapshot artifacts)

**Comment by juherr** [comment]
True. But the snapshot repository is not in the default settings.xml, right?
And Snapshot versions are not available out of the box.

I linked the 2 issues because both are part of the ci process and may be fixed together.

**Comment by vlsi** [comment]
> But the snapshot repository is not in the default settings.xml, right

it seems to be the case.

> And Snapshot versions are not available out of the box.

Well, that is solvable if every commit to `master` branch triggers the publish.
