### ISSUE TITLE
Error with maven and selenium

### ISSUE THREAD

**Issue by Nandini09** [cbeust/testng#2446]
getting below error on working with maven and selenium silk jar

``` 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project sample: There are test failures. 
[ERROR]  
[ERROR] Please refer to C:\Users\viggas\eclipse-workspace\NWISEERegressionPack\target\surefire-reports for the individual test results. 
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream. 
[ERROR] There was an error in the forked process 
[ERROR] org/openqa/selenium/WebDriver 
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process 
[ERROR] org/openqa/selenium/WebDriver
```
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by juherr** [comment]
Hi,

The description of the issue is not enough if you want help.
Please reopen the issue when you'll have a way to reproduce the issue.
