### ISSUE TITLE
Feature: allow modification of group array via IInvokedMethod

### ISSUE THREAD

**Issue by Proryanator** [cbeust/testng#2447]
### TestNG Version
> Note: only the latest version is supported

### Feature Request
Adding the ability to _modify/set_ groups from IInvokedMethod, via the IInvokedMethodListener.

If I'm not mistaken too, using _alwaysRun = true_ in conjunction with _dependsOnMethods_ does not work as expected, so using the groups tags here would also help resolve that bug as a workaround, although it's not the primary reason for this feature request.

### Actual behavior
We're not able to modify groups at runtime via this listener or via IInvokedMethod (which could be for a valid reason).

I'm not sure if there's an underlying reason for this, perhaps by the time you'd be able to modify the groups, the annotated methods themselves will already have been set in stone. If that's the case I think this would be a bigger feature request.

### Use case sample
> Please, share the test case (as small as possible) which shows the issue

Let's say you'd like every @Test that's in the project to be assigned to a default group, say 'regression'.
Instead of going into hundreds of classes and adding that 'regression' group each time (and because we're human, missing a few here and there) like we do now, you could use the IInvokeMethodListener and do the following:

```java
public class AddDefaultGroupListener implements IInvokedMethodListener {

  @Override
  public void beforeInvocation(IInvokedMethod iInvokedMethod, ITestResult iTestResult) {
    if (iInvokedMethod.isTestMethod()){
        iInvokedMethod.setGroups("defaultGroupName");
        // or optionally, adding to existing groups
        iInvokedMethod.addGroup("defaultGroupName");
    }
  }
```

Of course you could also be more specific to some situations in your project for example, where perhaps certain @BeforeMethods named a certain way should belong to a group and you'd like to just code that in one place.

In my use case, it could also be used to mark all @BeforeMethods with specific groups that will always run specific @BeforeMethods, without needing to add in the _alwaysRun = true_ to every @BeforeMethod like we do now.

```java
public class AddGroupsToEveryBeforeMethod implements IInvokedMethodListener {

  @Override
  public void beforeInvocation(IInvokedMethod iInvokedMethod, ITestResult iTestResult) {
    if (iInvokedMethod.isConfigurationMethod() && iInvokedMethod.getTestMethod()
        .isBeforeMethodConfiguration()) {
      iInvokedMethod.getTestMethod().setGroups("defaultGroupName");
      // also optionally, adding to existing groups
      iInvokedMethod.addGroup("defaultGroupName");
    }
}
```

I think a feature like this would add even more customization from the IInvokedMethodListener and could open up for some pretty slick dynamic group tagging. It would allow for those who cared to use it, the ability to remove a portion of the human error that can occur during test group tagging in a large scale project.

I'm sure we've all wondered where that one @Test was that you made and realized that you forgot to mark it with a specific group that you run each night 😉

**Comment by krmahadevan** [comment]
@Proryanator - Have you considered leveraging an `org.testng.IAnnotationTransformer` for altering values of `@Test` annotations at runtime ? This sounds like a straight forward use case for `org.testng.IAnnotationTransformer`

**Comment by krmahadevan** [comment]
Let me know if that will help you get past your current requirement and if this issue can be closed. 

By the time the `IInvokedMethodListener` implementation is invoked, TestNG has already decided what needs to be executed and what should be skipped. So it wont be possible for TestNG to provide you with that capability of setting groups like what you are asking for. This needs to be determined much ahead in the lifecyle which is where the AnnotationTransformer comes in.

**Comment by Proryanator** [comment]
> @Proryanator - Have you considered leveraging an `org.testng.IAnnotationTransformer` for altering values of `@Test` annotations at runtime ? This sounds like a straight forward use case for `org.testng.IAnnotationTransformer`

We use IAnnotationTransformer to do some modifications and I did see that I could modify _@ Test_ annotation parameters that way, but I noticed that IAnnotationTransformer is only called before _@ Test_ annotations, I don't see it being called before config methods (but I could be wrong there).

So in that case, since the only place where you can get information on @BeforeMethods through a listener appears to be IInvokedMethodListener, I can close this issue since it wouldn't be possible to do what I'm thinking 😄 correct?

**Comment by juherr** [comment]
@Proryanator For configuration methods, you can implement the following method in your listener: https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/IAnnotationTransformer2.html#transform-org.testng.annotations.IConfigurationAnnotation-java.lang.Class-java.lang.reflect.Constructor-java.lang.reflect.Method-

(the method is also available IAnnotationTransformer in the latest versions)

**Comment by Proryanator** [comment]
@juherr ah ha! In theory this would allow me to do an earlier modification of the groups attached to some @BeforeMethods correct?

**Comment by krmahadevan** [comment]
@Proryanator - In principle an annotation transformer will let you alter any attribute of any of the TestNG annotations (Test and configuration annotations). So it will help you solve what you are looking at. The newer versions of TestNG (`7.3.0` to be specific) merged multiple Iannotation transformer variants into one annotation viz., `IAnnotationTransformer`. For some reason i conveniently assumed you were on the latest version and that's why I forgot to call it out explicitly.

**Comment by Proryanator** [comment]
> @Proryanator - In principle an annotation transformer will let you alter any attribute of any of the TestNG annotations (Test and configuration annotations). So it will help you solve what you are looking at. The newer versions of TestNG (`7.3.0` to be specific) merged multiple Iannotation transformer variants into one annotation viz., `IAnnotationTransformer`. For some reason i conveniently assumed you were on the latest version and that's why I forgot to call it out explicitly.

I also forgot to mention we're on an older version hehe 😉 okay let me try this in my project and if I can get it to do what I'm looking for I'll quickly close this issue, thanks @juherr @krmahadevan 😄

**Comment by Proryanator** [comment]
@juherr so bumped my project up to 7.0.0, and I can now use an IAnnotationTransformer with overriding _transform(IConfigurationAnnotation...)_ but I don't see it actually being run from my project oddly enough.

Here's my code, for simplicity sake I took out other code I had in the _ITestAnnotation_ transform override:

```java
public class ConfigurationAnnotation implements IAnnotationTransformer {

  @Override
  public void transform(IConfigurationAnnotation annotation, Class testClass,
      Constructor testConstructor, Method testMethod) {
    System.out.println("The ConfigurationAnnotation class has been run...");
  }

  @Override
  public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor,
      Method testMethod) {
    System.out.println("The ITestAnnotation override ran...");
   }
}
```

This is attached as a listener in the POM here:
```xml
<properties>
   <property>
      <name>listener</name>
         <value>
            com.full-path.util.ConfigurationAnnotation
         </value>
      </property>
</properties>
```

Trying to see if I can modify group annotations through this method. However I'm not seeing it get run for any config methods, am I missing something?

My project has many @BeforeMethods, the first one to run is called _digitalServicesMobileSetup_, but I don't see that the other overridden transform has ran.

Here's what I see:
<img width="725" alt="Screen Shot 2020-12-31 at 11 10 14" src="https://user-images.githubusercontent.com/8595173/103419490-ea987f80-4b58-11eb-8d7b-1d8c01b31465.png">

**Comment by krmahadevan** [comment]
@Proryanator - If you are upgrading, I would suggest that you bump over to `7.3.0` (because thats the latest version and the only version in which we can fix defects if any).

Here's a sample that shows this working fine.

```java
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import org.testng.IAnnotationTransformer;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.annotations.IConfigurationAnnotation;

public class LocalTransformer implements IAnnotationTransformer, ITestListener {

  @Override
  public void transform(IConfigurationAnnotation annotation, Class testClass,
      Constructor testConstructor, Method testMethod) {
    annotation.setDescription("Dynamic Description");
  }

  @Override
  public void onFinish(ITestContext context) {
    context.getPassedConfigurations().getAllResults().forEach(each -> {
      String method = each.getMethod().getQualifiedName();
      String description = each.getMethod().getDescription();
      String text = String.format("%s() has its description as [%s]", method, description);
      System.err.println(text);
    });
  }
}
```

```java
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class SampleTestClass {

  @BeforeMethod
  public void configurationMethod() {
    System.err.println(getClass().getName() + ".configurationMethod() invoked");
  }

  @Test
  public void testMethod() {
    System.err.println(getClass().getName() + ".testMethod() invoked");
  }

}
```

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0-M1</version>
    <executions>
        <execution>
            <phase>test</phase>
        </execution>
    </executions>
    <configuration>
        <properties>
            <property>
                <name>listener</name>
                <value>
                com.rationaleemotions.github.issue2447.LocalTransformer
              </value>
            </property>
            <property>
                <name>testclass</name>
                <value>com.rationaleemotions.github.issue2447.SampleTestClass</value>
            </property>
        </properties>
    </configuration>
</plugin>

```

Here's the output of running `mvn clean test`

```
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M1:test (default-test) @ testbed ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
com.rationaleemotions.github.issue2447.SampleTestClass.configurationMethod() invoked
com.rationaleemotions.github.issue2447.SampleTestClass.testMethod() invoked
com.rationaleemotions.github.issue2447.SampleTestClass.configurationMethod() has its description as [Dynamic Description]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.717 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.937 s
[INFO] Finished at: 2020-12-31T23:36:20+05:30
[INFO] ------------------------------------------------------------------------

```

**Comment by Proryanator** [comment]
@krmahadevan 

Upgrading to 7.3.0 works with my provided code!

I noticed something however! I have the following:

I'm collecting the groups from the currently running @Test (or I could even collect other information in the future and pass it to the IConfigurationAnnotation), then setting those to every @BeforeMethod that a @Test uses.

This works as expected with running 1 test but, the logic kinda falls apart in parallel.


```java
public class AnnotationTransformer implements IAnnotationTransformer {

  // do we need to do this? Or can this just be it's own variable that's not overwritten during parallel execution?
  private static ThreadLocal<String[]> currentTestGroups = new ThreadLocal<>();

  @Override
  public void transform(IConfigurationAnnotation annotation, Class testClass,
      Constructor testConstructor, Method testMethod) {
    // we're updating the groups of every @BeforeMethod using this method
    if (annotation.getBeforeTestMethod()) {
      FrostReporter.log("Updating groups of @BeforeMethod: " + testMethod.getName());
      FrostReporter
          .log("Using groups acquired from @Test: " + Arrays.toString(currentTestGroups.get()));
      annotation.setGroups(currentTestGroups.get());
    }
  }

  @Override
  public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor,
      Method testMethod) {
    FrostReporter.log("Running ITestAnnotation for test: " + testMethod.getName());
    IRetryAnalyzer retry = annotation.getRetryAnalyzer();
    if (retry == null) {
      annotation.setRetryAnalyzer(RetryAnalyzer.class);
    }

    // if you want to change the invocation count, go for it!
    String invocationCount = System.getProperty(INVOCATION_COUNT_KEY);
    if (StringUtils.isNotBlank(invocationCount)) {
      annotation.setInvocationCount(Integer.parseInt(invocationCount));
    }

    // collect all groups attached to this TestClass#method, and store into the static hashmap
    // String key = testMethod.getDeclaringClass().getSimpleName() + "." + testMethod.getName();
    currentTestGroups.set(getGroupsFromTestClass(testMethod));
  }

  /**
   * Given the current running test, returns you the groups attached to it.
   */
  private String[] getGroupsFromTestClass(Method testMethod) {
    Test testAnnotation;

    // extract the groups from the @Test method defined in the Test Class
    for (Method method : testMethod.getDeclaringClass().getMethods()) {
      // only want to look at the @Test annotation attached to this @Test
      if (!method.getName().equals(testMethod.getName())) {
        continue;
      }

      testAnnotation = method.getAnnotation(Test.class);

      if (testAnnotation != null) {
        return testAnnotation.groups();
      }
    }

    return null;
  }
}
```

I thought the IConfigurationAnnotation would be called once per @Test that's running in parallel, however when running in parallel it's only ever called once.

<img width="604" alt="Screen Shot 2020-12-31 at 14 18 54" src="https://user-images.githubusercontent.com/8595173/103424655-22142580-4b73-11eb-943a-5b2597a552a9.png">

Is this because config methods are not a per-instance basis? I'm running @Test classes in parallel if that has anything to do with it. Notice the output, the ITestAnnotation one runs twice (I'm running 2 tests in parallel), however the IConfigurationAnnotation one runs just once per @BeforeMethod that I have.

**Comment by krmahadevan** [comment]
@Proryanator - I think you are basically getting the concept backwards.

Let me explain some of the facts and maybe that will add clarity

* Groups in testng is basically a selection mechanism using which you tell TestNG what to execute and what to skip.
* Since its a selection mechanism, it gets applied much ahead in the life cycle so that TestNG can determine what would need to be executed.
* `IAnnotationTransformer` listener is a callback listener that TestNG provides to you to give you an opportunity to change some of the attributes of either a `@Test` or a `@Before/@After` configuration and it gets applied while TestNG is determining what to run via the filtering mechanism (The other filtering mechanisms via a suite xml would include, package names or just class names or just method names within a class name etc.,)
* Once TestNG has determined what to run, there's no way you can alter it (which means except for `IAnnotationTransformer` interface, you dont get to change what can be run and what can|should be skipped. The other filtering mechanisms are ofcourse method selectors (either beanshell or `org.testng.IMethodSelector` or `org.testng.IMethodInterceptor`)
* Not all configuration methods are agnostic of the test class instance. For example `@BeforeClass`, `@AfterClass`, `@BeforeMethod` and `@AfterMethod` are very much bound to a test class instance)
* `IAnnotationTransformer` runs once per `@Test` method and once per every `configuration method` because here TestNG is just giving you what all methods are eligible for execution. At this point in time the context behind these methods are not applicable (when I say context, what I mean is how to handle a particular test method. for e.g, a test method could be bound to a data provider or may have an invocationcount which means the same test method would need to called multiple times. But from an annotation perspective which is what an `IAnnotationTransformer` is all about, its just 1 single method. And the same goes for configuration methods as well)
* Last but not the least, the whole intent of providing an `IAnnotationTransformer` is so that you the user can alter the attributes of an annotation. Annotations in Java are static and not dynamic, which means that once the JVM instantiates and assigns values to an annotation, it cannot be changed|altered easily. There are hacks which you can employ to do it, but they are very specific to JDK versions and perhaps even JDK flavors. For e.g., I wrote about once such approach in my blog post. You can read more about it [here](https://rationaleemotions.wordpress.com/2016/05/27/changing-annotation-values-at-runtime/)

Hope that adds clarity

**Comment by Proryanator** [comment]
> @Proryanator - I think you are basically getting the concept backwards.
> 
> 
> 
> Let me explain some of the facts and maybe that will add clarity
> 
> 
> 
> * Groups in testng is basically a selection mechanism using which you tell TestNG what to execute and what to skip.
> 
> * Since its a selection mechanism, it gets applied much ahead in the life cycle so that TestNG can determine what would need to be executed.
> 
> * `IAnnotationTransformer` listener is a callback listener that TestNG provides to you to give you an opportunity to change some of the attributes of either a `@Test` or a `@Before/@After` configuration and it gets applied while TestNG is determining what to run via the filtering mechanism (The other filtering mechanisms via a suite xml would include, package names or just class names or just method names within a class name etc.,)
> 
> * Once TestNG has determined what to run, there's no way you can alter it (which means except for `IAnnotationTransformer` interface, you dont get to change what can be run and what can|should be skipped. The other filtering mechanisms are ofcourse method selectors (either beanshell or `org.testng.IMethodSelector` or `org.testng.IMethodInterceptor`)
> 
> * Not all configuration methods are agnostic of the test class instance. For example `@BeforeClass`, `@AfterClass`, `@BeforeMethod` and `@AfterMethod` are very much bound to a test class instance)
> 
> * `IAnnotationTransformer` runs once per `@Test` method and once per every `configuration method` because here TestNG is just giving you what all methods are eligible for execution. At this point in time the context behind these methods are not applicable (when I say context, what I mean is how to handle a particular test method. for e.g, a test method could be bound to a data provider or may have an invocationcount which means the same test method would need to called multiple times. But from an annotation perspective which is what an `IAnnotationTransformer` is all about, its just 1 single method. And the same goes for configuration methods as well)
> 
> * Last but not the least, the whole intent of providing an `IAnnotationTransformer` is so that you the user can alter the attributes of an annotation. Annotations in Java are static and not dynamic, which means that once the JVM instantiates and assigns values to an annotation, it cannot be changed|altered easily. There are hacks which you can employ to do it, but they are very specific to JDK versions and perhaps even JDK flavors. For e.g., I wrote about once such approach in my blog post. You can read more about it [here](https://rationaleemotions.wordpress.com/2016/05/27/changing-annotation-values-at-runtime/)
> 
> 
> 
> Hope that adds clarity
> 
> 
> 
> 

I believe it does, so it runs once per each @Test, and also once per @BeforeMethod regardless of whether you're running 1 @Test or 2.

So, having @Test 1 and @Test 2 both inherit the same @BeforeMethod, IAnnotationTransformer would be called 3 times, not 4 💪🏻

I see now! I have a better understanding of how this works now, and I'll go ahead and close this issue.

**Comment by juherr** [comment]
Closed because of the need behind the feature request can be solved in another way.

**Comment by juherr** [comment]
Closed because of the need behind the feature request can be solved in another way.
