### ISSUE TITLE
[Feature request] Add onDataProviderFailure listener?

### ISSUE THREAD

**Issue by baflQA** [cbeust/testng#2456]
### TestNG Version
7.3

### Expected behavior
I wanted to add a feature to the Allure report and create attachments from the data providers. But I encountered problems with cleaning up things in case of the Data Provider failure. 
Immediately after the DP failure, TestNG sets the test status to SKIPPED, and invokes the onTestSkipped listeners. 
I am looking for a way how to be notified about the DP failure, and be able to perform some cleanup on such a failure. 
Maybe it would be nice to have some kind of listeners on the DP failure? 
Having something that can be invoked after https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/Parameters.java#L796 failure would be appreciated.

**Comment by juherr** [comment]
Hi,

Data providers are not supposed to fail and it could be considered as an execution failure a day.

Why not have a try/catch in your data provider and clean things in the catch block?

**Comment by baflQA** [comment]
Hey - the thing is that I wanted to contribute to the Allure Testng project, and add attachments from the data provider to the report. We have before and after data provider listeners, where was able to create proper objects to collect the artifacts created for the Allure report. But in case of the failure, some objects remain opened, as it goes to the test listeners directly.

**Comment by baflQA** [comment]
Wow, that fast implemented? 😅 Many, many thanks.
