### ISSUE TITLE
Add support for formatted start time in emailable-report.html

### ISSUE THREAD

**Issue by bazzani** [cbeust/testng#2459]
### TestNG Version
`7.1.1` for the sample below, but the `master` branch version can also have the new feature applied.

### Expected behavior
When I run my TestNG tests using maven and the maven surefire plugin, I would like to be able to specify a formatted _start_ datetime in the `emailable-report.html` file.

### Actual behavior
The start datetime of a test is displayed in millisceonds from the epoch, which is not human readable.

### Is the issue reproductible on runner?
- [x] Maven
- [x] Shell
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
- run TestNG tests with maven and the `maven-surefire-plugin`, check the **_Start_** column in the `emailable-report.html` file
- Screenshot attached...
  - ![image](https://user-images.githubusercontent.com/2152194/105208676-dc7ac500-5b40-11eb-9dfb-ba6320b064db.png)

### Other
I have come up with a fix in my local dev environment to support this feature by adding a protected method to the [EmailableReporter2](https://github.com/cbeust/testng/blob/7.1.1/src/main/java/org/testng/reporters/EmailableReporter2.java#L347) class which will return the formatted start datetime.

The method can then be overridden in a sub class to return the human readable String, which will be added to the report.

#### A Sample output would be
- ![image](https://user-images.githubusercontent.com/2152194/105209331-9eca6c00-5b41-11eb-8aeb-bd02af400148.png)

**Comment by krmahadevan** [comment]
@bazzani - Would you like to raise a Pull Request for this ? We will be gladly be able to help you with reviewing it and getting it merged.

**Comment by bazzani** [comment]
> @bazzani - Would you like to raise a Pull Request for this ? We will be gladly be able to help you with reviewing it and getting it merged.

I certainly would @krmahadevan!

I have already forked this repo, and pushed an interim commit to a feature branch on my fork.
I will have another look at the code to see if adding any unit tests are prudent for this change, and then get back to you.

**Comment by bazzani** [comment]
@krmahadevan can i ask when my fix for this issue will be released?
aka when is the next release of testng due?

**Comment by krmahadevan** [comment]
@bazzani - TestNG `7.4.0` has been released to Maven central.
