### ISSUE TITLE
Support for dynamic parameter values in testng.xml

### ISSUE THREAD

**Issue by lzoubek** [cbeust/testng#246]
Hi, 

I'd like to add  $title.

For example testng.xml would look this way:

```
<test name="T2">
  <parameter name="number-of-times" value="${user.home}"/>
  <class name= "TestWebServer"/>
</test>
```

test method would recieve string with replaced property value. Property replacements would be just simple. So for example ${user.${other.property}} would not work.

Would you accept patch that implements this?

**Comment by kanika-anetcorp** [comment]
Any idea, how to do this by build also?

**Comment by krmahadevan** [comment]
@kanika-anetcorp - I would suggest that you post your query on the testng-users@googlegroups.com forum with all the details of what you are trying to achieve.
