### ISSUE TITLE
testng.xml founds no test after update

### ISSUE THREAD

**Issue by mstelzer-288** [cbeust/testng#2461]
### TestNG Version
7.3.0

Hello,

i did Upgrade to the newest version 7.3.0 . In my case this results into a problem.

\<packagename\> is just a spaceholder, in the real file the name is 100% correct and contains no errors or typos.

my testng.xml looks like

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="Base" verbose="2">
  <test name="Terminal Server">

    <groups>
      <run>
        <include name="server"/>
      </run>
    </groups>
    <packages>
      <package name="<packagename>.*"/>
    </packages>
  </test>
</suite>
```

In the package there are many classes with classes and methods with the @Test annotation.
But when i run the tests in terminal there where no tests found and executed.

If i add or exchange packages with:
```
    <classes>
      <class name="<packagename>.classname"/>
    </classes>
```

the tests in this class will be executed correctly, but still not all classes in the package. But there are many many many classes and i don't want to add them all manually.
Is there a know bug and propably an solution to it?

With the previos used version (6.8.9) all works correctly.

**Comment by krmahadevan** [comment]
@mstelzer-288 - Please add `verbose=2` to your `<suite>` tag, re-run the test to see what is causing the problem.
If the problem persists, you would need to share a sample that can be used to reproduce the problem.

**Comment by mstelzer-288** [comment]
Hello @krmahadevan,

the verbose-level is allready at 2 so nothing changes.
i tried to use an other version (e.g. 7.2.0, 7.0.0 and 6.8.8) straigth from the download-section and surprisingly the same problem.

the working pom.xml from testng differs in the jboss dependencie and plugin  "maven-assembly-plugin". is this the problem?

i attached the pom and jar file which is working.
[6.8.9-mod1_jboss-vfs.zip](https://github.com/cbeust/testng/files/5867162/6.8.9-mod1_jboss-vfs.zip)

the test-code looks like this:

`@Test(groups = {SERVER})`
`public void testErrorInvalidTimestamp() throws DatatypeConfigurationException {`
`// Some code stands here`
`}`

i hope u can help me out. Thanks

**Comment by krmahadevan** [comment]
@msebire - The attached zip file does not contain a sample that can be used to reproduce the problem. Please share a sample project that can be used to recreate the problem.

**Comment by krmahadevan** [comment]
No response from the user. Closing this issue.
