### ISSUE TITLE
Execute Slowests Tests First

### ISSUE THREAD

**Issue by numeralnathan** [cbeust/testng#2463]
### TestNG Version
All

### Expected behavior
In order to minimize total test time, I run the tests in parallel.  I would like to run the slowest tests first.  Please enhance TestNG to be able to execute the tests according to slowest to fastest.  This is useful for when running tests in a build pipeline.

In order to minimize time to first failure, I run the tests again in parallel but I would like to run the fastest tests first.  Please enhance TestNG to be able to execute the tests according to fastest to slowest.  This is useful for when running tests on my laptop after making a small code change.

### Actual behavior
TestNG currently executes in some arbitrary order.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
N/A

**Comment by juherr** [comment]
TestNG won't be able to determine which tests are slow and which ones are fast.
But you can use [the group feature](https://testng.org/doc/documentation-main.html#test-groups) and choose what group you want to run first.

**Comment by numeralnathan** [comment]
Can TestNG record the test execution time each time a test method runs and use the previous execution time to determine the ordering?

**Comment by juherr** [comment]
You have many ways to do it by yourself via listener/reporter.

For example, you can have a reporter that generates a file with the duration of each method and a listener that will [organize the expected order](https://testng.org/doc/documentation-main.html#methodinterceptors) and/or [apply the expected group](https://testng.org/doc/documentation-main.html#annotationtransformers).

**Comment by krmahadevan** [comment]
@numeralnathan - Here's what you should be doing:

1. Build a TestNG listener that starts recording every test's execution time and starts persisting them in a data source (xml|json|csv|db)
2. You now build another TestNG listener (it should implement `org.testng.IMethodInterceptor`) wherein you basically would get hold of all the test methods that TestNG is about to run. Now this list could be re-ordered such that the slowest running methods (which you can now obtain from your historic recordings from (1)) are ordered to run first.

This is pretty much what @juherr has also called out.

There's nothing more to be done from TestNG side.

Closing this *question* with resolution as **answered**

Also please post TestNG questions to the TestNG users forum. We would like to keep TestNG's issue page confined to tracking bugs
