### ISSUE TITLE
Second test case's steps are ignore because depended method failed in first test case

### ISSUE THREAD

**Issue by gimnguyen** [cbeust/testng#2466]
### TestNG Version 
Version: 7.0.0, 7.3.0

I have Test cases that have some the same steps. I split the same steps to a class. 
**Test case 1:** public class TCCardViaSenpay extends BuyViaSenpay
**Test case 2:** public class TC4GViaSenpay extends BuyViaSenpay
Class: **BuyViaSenpay** contains these the same steps of both of 2 Test Case.  In this class I use depend methods:
- @Test 'checkout' is depended on confirmationOTP
- @Test 'orderDetail' is depended on confirmationOTP

### Actual behavior 
When I run Test Case 1, The @Test 'confirmationOTP' is failed. 
Running in Test Case 2, the @Test 'confirmationOTP' is passed. But these steps (checkout, orderDetail) that depend on @Test 'confirmationOTP' in Test Case 2 is skip.
I guess Test case 2 is affected by Test case 1. 

### Expected behavior
Test Case 2: depended methods do not skip when @Test 'confirmationOTP' passed

### Is the issue reproductible on runner?

- [x] IntelliJ

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
![Screen Shot 2021-01-25 at 14 34 27](https://user-images.githubusercontent.com/14172888/105677297-41a63000-5f1e-11eb-8668-a8354889c9ed.png)

**Comment by krmahadevan** [comment]
@gimnguyen - Please edit this issue and add a simple standalone example that can be used to reproduce the problem (Please ensure that it doesnt have any other library dependency apart from just a bunch of sysout statements).

**Comment by krmahadevan** [comment]
Closing this issue since there is no response from the user.
@gimnguyen - Please comment with a sample that can be used to reproduce the problem, if this issue still exists.
