### ISSUE TITLE
XmlTest does not copy the xmlClasses during clone

### ISSUE THREAD

**Issue by aditya-qapitol** [cbeust/testng#2467]
### TestNG Version
7.3.0

### Expected behavior
`getXmlClasses()`in `XmlTest ` should not be null when `xmlTest.Clone()`

### Actual behavior
`getXmlClasses()`in `XmlTest ` is null when `xmlTest.Clone()` is called

### Is the issue reproductible on runner?
- Eclipse
- IntelliJ

### Test case sample
Sample TestNG XML File
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite verbose="1" name="TestSuite" annotations="JDK">
    <test name="Test1">
        <classes>
            <class name="com.qa.SampleTest"/>
        </classes>
    </test>
</suite>
```
The listener is added in the `META-INF.services` folder
```
public class TestNgAlterSuiteListener implements IAlterSuiteListener {
    @Override
    public void alter(List<XmlSuite> suites) {
      XmlSuite suite = suites.get(0);
      List<XmlTest> xmlTests = suite.getTests();
      XmlTest test = xmlTests.get(0);
      XmlTest newTest= (XmlTest) test.clone();
      System.out.println("Contains: " + newTest.getXmlClasses().toString())
    }
}
```

**Comment by juherr** [comment]
`result.setXmlClasses(getXmlClasses());` is missing in [the clone method](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XmlTest.java#L420-L439).

Would you like the propose a fix?

**Comment by aditya-qapitol** [comment]
> `result.setXmlClasses(getXmlClasses());` is missing in [the clone method](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XmlTest.java#L420-L439).
> 
> Would you like the propose a fix?

Please check the PR for the fix
