### ISSUE TITLE
Initial_HAP_Invalid_ProviderOne_ID_Failure.xml

### ISSUE THREAD

**Issue by ZathrasOne** [cbeust/testng#2471]
[github-2471.zip](https://github.com/cbeust/testng/files/5895978/github-2471.zip)
### TestNG Version
7.3.0

### Expected behavior
Suites Slave-1 and Slave-2 should run in parallel

### Actual behavior
Suites Slave-1 and Slave-2 run in sequence

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Zip file attached (after bug creation)

**Comment by ZathrasOne** [comment]
This is the same as issue 1686 which was closed because insufficient reproduceable example with expected behavior was not provided. I have provided a full, simplified, example. Below is the output, Tests 1x and 2x should run in parallel, but are run in series (at least that is the requested behavior, how to do that). Note that I have modified the original print routine to take a message, then run it once when entering, and once when exiting, after a short pause (1 second sleep). What we want to see is for the test 1x starts to be interspersed with the test 2x starts.

[RemoteTestNG] detected TestNG version 7.3.0
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
...
... TestNG 7.3.0 by CÃ©dric Beust (cedric@beust.com)
...

Suite: <github-2471-slave-suite-1>, TestName: <github-1686-test-11>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 1 Message: Test 1 started
Suite: <github-2471-slave-suite-1>, TestName: <github-1686-test-11>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 1 Message: Test 1 done
Suite: <github-2471-slave-suite-1>, TestName: <github-1686-test-11>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 1 Message: Test 2 started
Suite: <github-2471-slave-suite-1>, TestName: <github-1686-test-11>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 1 Message: Test 2 done
Suite: <github-2471-slave-suite-1>, TestName: <github-1686-test-11>, MethodName: <com.rationaleemotions.TestCase2.one()> running on Thread : 1
Suite: <github-2471-slave-suite-1>, TestName: <github-1686-test-11>, MethodName: <com.rationaleemotions.TestCase2.two()> running on Thread : 1
PASSED: one
PASSED: two
PASSED: one
PASSED: two

===============================================
    github-1686-test-11
    Tests run: 4, Failures: 0, Skips: 0
===============================================

Suite: <github-2471-slave-suite-1>, TestName: <github-2471-test-12>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 1 Message: Test 1 started
Suite: <github-2471-slave-suite-1>, TestName: <github-2471-test-12>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 1 Message: Test 1 done
Suite: <github-2471-slave-suite-1>, TestName: <github-2471-test-12>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 1 Message: Test 2 started
Suite: <github-2471-slave-suite-1>, TestName: <github-2471-test-12>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 1 Message: Test 2 done
Suite: <github-2471-slave-suite-1>, TestName: <github-2471-test-12>, MethodName: <com.rationaleemotions.TestCase2.one()> running on Thread : 1
Suite: <github-2471-slave-suite-1>, TestName: <github-2471-test-12>, MethodName: <com.rationaleemotions.TestCase2.two()> running on Thread : 1
PASSED: one
PASSED: two
PASSED: one
PASSED: two

===============================================
    github-2471-test-12
    Tests run: 4, Failures: 0, Skips: 0
===============================================


===============================================
github-2471-slave-suite-1
Total tests run: 8, Passes: 8, Failures: 0, Skips: 0
===============================================

Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-21>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 14 Message: Test 1 started
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-22>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 15 Message: Test 1 started
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-22>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 15 Message: Test 1 done
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-21>, MethodName: <com.rationaleemotions.TestCase1.one()> running on Thread : 14 Message: Test 1 done
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-22>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 15 Message: Test 2 started
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-21>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 14 Message: Test 2 started
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-21>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 14 Message: Test 2 done
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-22>, MethodName: <com.rationaleemotions.TestCase1.two()> running on Thread : 15 Message: Test 2 done
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-22>, MethodName: <com.rationaleemotions.TestCase2.one()> running on Thread : 15
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-21>, MethodName: <com.rationaleemotions.TestCase2.one()> running on Thread : 14
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-22>, MethodName: <com.rationaleemotions.TestCase2.two()> running on Thread : 15
Suite: <github-2471-slave-suite-2>, TestName: <github-2471-test-21>, MethodName: <com.rationaleemotions.TestCase2.two()> running on Thread : 14
PASSED: one
PASSED: two
PASSED: one
PASSED: two

===============================================
    github-2471-test-22
    Tests run: 4, Failures: 0, Skips: 0
===============================================

PASSED: one
PASSED: two
PASSED: one
PASSED: two

===============================================
    github-2471-test-21
    Tests run: 4, Failures: 0, Skips: 0
===============================================


===============================================
github-2471-slave-suite-2
Total tests run: 8, Passes: 8, Failures: 0, Skips: 0
===============================================


===============================================
github-2471-master-suite
Total tests run: 16, Passes: 16, Failures: 0, Skips: 0
===============================================

**Comment by krmahadevan** [comment]
@ZathrasOne - Can you also let us know how are you executing the test? I noticed that you have checked `eclipse`. 
Just to be absolutely sure, please run the tests from the maven command line using `mvn clean test` and share your experience.

**Comment by krmahadevan** [comment]
@ZathrasOne - I have debugged this using the sample that you shared and I have noticed that the code path [here](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L1166) is being invoked. 

So this re-iterates that the suites are being run in parallel. You can setup breakpoint in the same place and then run this via the IDE and see this for yourself.

Closing this issue since there's nothing much to be done from TestNG side.
