### ISSUE TITLE
can not get  testName   (@test(testName="xxx"))

### ISSUE THREAD

**Issue by msy53719** [cbeust/testng#2474]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@msy53719 - Please include a sample that can be used to reproduce the problem and also please ensure that you are working with TestNG `7.3.0` which is the latest released version.

**Comment by krmahadevan** [comment]
No response from user. Closing this issue.
@msy53719 - Please feel free to comment with a sample that can be used to reproduce the problem.
