### ISSUE TITLE
In the command "MVN test-dxml. file=xml1,xml2", configure two XMLs, and whether XML1 and XML2 are run serially or in parallel

### ISSUE THREAD

**Issue by PearlSumRise** [cbeust/testng#2475]

**Comment by krmahadevan** [comment]
@PearlSumRise - Please use the Testng-users forum for asking questions. We would like to restrict the issues page to track actual problems.
When you post your query on the forum, please dont forget to add as much context as possible including samples etc.,
By default the suites are executed in sequence. If you set the property https://testng.org/doc/documentation-main.html#parallel-suites as detailed here via the `<property>` tag of surefire plugin, you should be able to get this done.
