### ISSUE TITLE
[Help] Can we pass argument to listeners from testng.ml

### ISSUE THREAD

**Issue by praveendvd** [cbeust/testng#2480]
### TestNG Version

v7.3.0

### Expected behavior

SHould initiate class properly for class org.testng.reporters.VerboseReporter

### Actual behavior

getting cannot initiate error

```
Cannot instantiate class org.testng.reporters.VerboseReporter
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:36)
	at org.testng.TestNG.addListeners(TestNG.java:970)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:930)
	at org.testng.TestNG.initializeEverything(TestNG.java:1018)
	at org.testng.TestNG.run(TestNG.java:1029)
	at runner.Entrypoint.main(Entrypoint.java:132)
Caused by: java.lang.InstantiationException: org.testng.reporters.VerboseReporter
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:30)
	... 5 more
Caused by: java.lang.NoSuchMethodException: org.testng.reporters.VerboseReporter.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3355)
	at java.base/java.lang.Class.newInstance(Class.java:571)
	... 6 more
```
### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample:

testng.xml
```

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite">
	<listeners>
		<listener class-name="extendreport_2.TestListener" />

		<listener class-name="org.testng.reporters.VerboseReporter" />
	</listeners>

	<test name="TestCases">


		<classes>

			<class name="test_suites.Testcase1" />

		</classes>


	</test>

</suite> <!-- Suite -->

```
<listener class-name="org.testng.reporters.VerboseReporter" />
 
throws initialization error so i removed the verboseReporter listener and did below work around.

**work around:**

Initiate testng from script instead:

	
	       TestNG testng = new TestNG();

		// Create a list of String
		List<String> suitefiles = new ArrayList<String>();

		// Add xml file which you have to execute
		suitefiles.add("path_to_testng\testng.xml");

		// now set xml file for execution
		testng.setTestSuites(suitefiles);
		
		testng.addListener(new VerboseReporter("[TestNG] "));

		// finally execute the runner using run method
		testng.run();

**I think the reporter excepts an string argument to constructor , is there a way to pass constructor argument to <listener> in testng.xml**

**Comment by krmahadevan** [comment]
@praveendvd - For queries related to TestNG please use the TestNG google forums https://groups.google.com/g/testng-users

To answer your question, TestNG will be able to instantiate a listener only if it satisfies the following:

- Has a default constructor
- Has a parameterised constructor that accepts a string.

For anything else, you would need to just work with a `org.testng.ITestNGListenerFactory` implementation which one of your test classes needs to implement.

**Comment by praveendvd** [comment]
> @praveendvd - For queries related to TestNG please use the TestNG google forums https://groups.google.com/g/testng-users
> 
> To answer your question, TestNG will be able to instantiate a listener only if it satisfies the following:
> 
> * Has a default constructor
> * Has a parameterised constructor that accepts a string.
> 
> For anything else, you would need to just work with a `org.testng.ITestNGListenerFactory` implementation which one of your test classes needs to implement.

the constructor accepts string so how would i pass it ?

**Comment by praveendvd** [comment]
> @praveendvd - For queries related to TestNG please use the TestNG google forums https://groups.google.com/g/testng-users
> 
> To answer your question, TestNG will be able to instantiate a listener only if it satisfies the following:
> 
> * Has a default constructor
> * Has a parameterised constructor that accepts a string.
> 
> For anything else, you would need to just work with a `org.testng.ITestNGListenerFactory` implementation which one of your test classes needs to implement.

@krmahadevan  hi any help ? i tried in the group but not having any response

**Comment by krmahadevan** [comment]
@praveendvd 

> the constructor accepts string so how would i pass it ?

Short answer is you cannot do it from outside. You would need to use a ListenerFactory implementation in your test class to get it done.

> hi any help ? i tried in the group but not having any response

First time posts are moderated. So until a moderator accepts your post, it will not show up. I have processed the pending messages. You should now be able to use the TestNG google forums.

But I believe your question has been already answered.
