### ISSUE TITLE
Hierarchical base- and test-class @AfterClass methods out of order using groups

### ISSUE THREAD

**Issue by flaky-test** [cbeust/testng#2489]
### TestNG Version
7.4.0

### Expected behavior
Test class hierarchy with base class extended by test class.
Expecting Baseclass @AfterClass method executed after the test class @AfterClass method

BaseClass_A
has 	@BeforeSuite(groups = "a")
	@BeforeClass(groups = "a")
	@AfterClass(groups = "a")
	@AfterMethod(groups = "a")

TestClass_A
has 	@BeforeClass(groups = "a")
	@BeforeMethod(groups = "a")
	@Test(groups = "a")
	@AfterMethod(groups = "a")
	@AfterClass(groups = "a")

**TestNG 7.3.0** execution as expected

Executing: beforeSuite_BaseClass_A
Executing: beforeClasses_BaseClass_A
Executing: beforeClass_TestClass_A
Executing: beforeMethod_TestClass_A
Executing: test1_TestClass_A
Executing: afterMethod_TestClass_A
Executing: afterClass_TestClass_A
Executing: afterClasses_BaseClass_A
Executing: afterSuite_BaseClass_A

### Actual behavior
Baseclass @AfterClass method executed before the test class @AfterClass method

**TestNG 7.4.0** execution out of order

Executing: beforeSuite_BaseClass_A
Executing: beforeClasses_BaseClass_A
Executing: beforeClass_TestClass_A
Executing: beforeMethod_TestClass_A
Executing: test1_TestClass_A
Executing: afterMethod_TestClass_A
**Executing: afterClasses_BaseClass_A
Executing: afterClass_TestClass_A**
Executing: afterSuite_BaseClass_A

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

BaseClass_A
has @BeforeSuite(groups = "a")
@BeforeClass(groups = "a")
@Afterclass(groups = "a")
@AfterMethod(groups = "a")

TestClass_A
has @BeforeClass(groups = "a")
@BeforeMethod(groups = "a")
@Test(groups = "a")
@AfterMethod(groups = "a")
@Afterclass(groups = "a")

**Comment by krmahadevan** [comment]
@flaky-test - Please share an example along with the suite file and surefire plugin configuration(if you are running this from maven) for us to be able to reproduce this issue.

**Comment by flaky-test** [comment]
Attached zip containing list of files below, test executed from within Intellij IDEA and gradle.build:

- BaseClassA.java
- TestClassA.java
- test_suite_A.xml 

[testgrouporder.zip](https://github.com/cbeust/testng/files/6103124/testgrouporder.zip)

**Comment by krmahadevan** [comment]
Initial analysis suggests that this is due to https://github.com/cbeust/testng/issues/2432
