### ISSUE TITLE
assertNotEquals returns fast when argument is null, not calling equals(Object)

### ISSUE THREAD

**Issue by Marcono1234** [cbeust/testng#2490]
### TestNG Version
7.4.0

### Actual behavior
When calling `Assert.assertNotEquals(Object, Object)` with one argument being `null`, the method returns fast, without calling `equals(Object)` on the non-`null` object.

This behavior is reasonable from a performance perspective, however (possibly also due to missing documentation on the method), it is likely that users misuse the method to check whether their `equals(Object)` implementation handles `null` correctly. The current implementation does not actually perform this check.

### Expected behavior
There might be several solutions to this:
- Clarify in the `Assert` documentation that the method `assertNotEquals` should not be used to check whether `equals(Object)` correctly handles `null`
- Change the `assertNotEquals` implementation to always call `equals(Object)` when one of the arguments is non-`null`

### Test case sample
```java
public class MyClass {
    @Override
    public boolean equals(Object o) {
        // Broken implementation
        return true;
    }
    
    public static void main(String args[]) {
      // Faulty check whether `MyClass.equals(...)` correctly handles `null`
      // EXPECTED: Both checks should throw AssertionError
      // ACTUAL: No exception is thrown, test passes
      org.testng.Assert.assertNotEquals(new MyClass(), null);
      org.testng.Assert.assertNotEquals(null, new MyClass());
      System.out.println("All tests succeeded");
    }
}
```

Edit: Changed the sample code to clarify the expected behavior.

**Comment by royanindya-code** [comment]
Hi Both,

I have created this PR - https://github.com/cbeust/testng/pull/2497 as part of this change. 

Could you please have a look ?

Thanks,
Anindya

**Comment by juherr** [comment]
What is the behavior of JUnit, AssertJ, or any other assertions API?

**Comment by Keshav-Ladha-Halodoc** [comment]
Hello,
I have created this PR - https://github.com/cbeust/testng/pull/2498 as part of this change.

Could you please review ?

Thanks,
Keshav

**Comment by royanindya-code** [comment]
Hi Julien,

I have checked in Junit 4.13.2 version. In Junit,
1.  If expected is null, then they are returning assertion error is actual is null and if not null then they are returning true.
2. And if expected is not null then they are comparing expected with actual. Basically, in junit there is no additional check if actual is null or not when expected is not null.

Let me know if you need more information on this.

Regards,
Anindya

**Comment by juherr** [comment]
I made some additional tests with JUnit 5.7 and AssertJ 3.18.1.
Only one assertion is failing: I confirm that TestNG should be fixed.

```kotlin
class TmpTest {

    class MyClass {

        override fun equals(other: Any?): Boolean {
            return true
        }

        override fun hashCode(): Int {
            return 1
        }
    }

    @Test
    fun `JUnit notEquals`() {
        assertNotEquals(null, Object())
        assertNotEquals(Object(), null)
        assertNotEquals(null, MyClass())
        assertNotEquals(MyClass(), null) // => org.opentest4j.AssertionFailedError: expected: not equal but was: <null>
    }

    @Test
    fun `JUnit notSame`() {
        assertNotSame(null, Object())
        assertNotSame(Object(), null)
        assertNotSame(null, MyClass())
        assertNotSame(MyClass(), null)
    }

    @Test
    fun `AssertJ notEquals`() {
        assertThat(null as Any?).isNotEqualTo(Object())
        assertThat(Object()).isNotEqualTo(null)
        assertThat(null as Any?).isNotEqualTo(MyClass())
        assertThat(MyClass()).isNotEqualTo(null)
    }

    @Test
    fun `AssertJ notSame`() {
        assertThat(null as Any?).isNotSameAs(Object())
        assertThat(Object()).isNotSameAs(null)
        assertThat(null as Any?).isNotSameAs(MyClass())
        assertThat(MyClass()).isNotSameAs(null)
    }
}
```

**Comment by Keshav-Ladha-Halodoc** [comment]
Hello Juherr,,
These changes will be fix for this:

 private static boolean areNotEqualImpl(Object actual, Object expected) {
    if ((expected == null) && (actual == null)) {
      return false;
    }
    if (expected != null && actual != null && actual.equals(expected) && expected.equals(actual)) {
      return false;
    }
    return true;
  }
