### ISSUE TITLE
Allow dataProvider return an array of objects

### ISSUE THREAD

**Issue by barbara79** [cbeust/testng#2502]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
```
@DataProvider
private Object[] dataProviderMethod() {
     return new Object[]{
                    new Object[]{ new MyClass(param1, param2)},
                    new Object[]{ new MyClass(param1, param2)},
    };
}
and then in my method I can pass as parameter the object got from the data provider method:
@Test
@UseDataProvider("dataProviderMethod")
public void myTest(MyClass myClassObject) {
     assertEqual("foo", myClassObject.getFoo());
}
```
### Actual behavior
I cannot use data provider for Objects at all

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
see in Expected behaviour

**Comment by juherr** [comment]
Hi,

It already works with TestNG: https://github.com/cbeust/testng/blob/master/src/test/java/test/dataprovider/OneDimDataProviderSample.java

You are using `@UseDataProvider` which is provided by https://github.com/TNG/junit-dataprovider
I think you should open an issue there.
