### ISSUE TITLE
TestNG 7.4 & 7.3 data provider data cannot be populated to onTestStart hook when BeforeMethod is failed

### ISSUE THREAD

**Issue by xuanzhaopeng** [cbeust/testng#2504]
### TestNG Version
7.4 & 7.3

### Expected behavior
When beforeMethod is failed, and in `ITestListener.onTestStart(ITestResult result)`, I execute `result.getParameters()`, I should get the parameters from DataProvider, even the beforeMethod/beforeClass is failed

### Actual behavior
ITestListener.onTestStart(ITestResult result) cannot get full parameters from Data provider when beforeMethod/beforeClass is failed. As the result, the we cannot generate correct Allure Report,  since the parameters are always change. 

when beforeMethod is failed, the parameter I got from ITestResult for test is [],  when beforeMethod is passed, the parameter is proper data from data provider.  

**Other facts:**
beforeMethodInvoke and onTestSkipped works well in this case.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```
public class RobinTest2 {

    @DataProvider
    public Object[][] data() {
        return new Object[][]{
                new Object[]{Colours.GREEN},
                new Object[]{Colours.RED},
                new Object[]{Colours.YELLOW},
                new Object[]{Colours.BLUE},
                new Object[]{Colours.BLACK}
        };
    }


    @BeforeClass
    void myBeforeClass() throws Exception {
    }

    @BeforeMethod
    void myBeforeMethod() throws Exception {
        throw new Exception("my exception");
    }

    @Test(dataProvider = "data")
    void testSuccess(Colours colour) {
        Assert.assertTrue(true);
    }
}
```

**Comment by xuanzhaopeng** [comment]
I have a workaround. 

before if we need to use `onTestStart` hook,  then we need to convert it to: 

```
   public void beforeInvocation(final IInvokedMethod method, final ITestResult testResult) {
        if (testMethod.isTest()) {
            // this is your onTestStart previously
            internalOnTestStart(testResult);
        }
    }
```

**Comment by krmahadevan** [comment]
@xuanzhaopeng - Was this ever working or is this something like a new ask ?

**Comment by juherr** [comment]
@xuanzhaopeng I agree with the issue if I understand it well. 
Could you make a pull-request with a test case? It will be a good first step for a fix.

**Comment by xuanzhaopeng** [comment]
> @xuanzhaopeng - Was this ever working or is this something like a new ask ?

Sorry, I just moving to TestNG.. hard to see that
