### ISSUE TITLE
TestNG exists with code 0 even when there are tests failures

### ISSUE THREAD

**Issue by baflQA** [cbeust/testng#2523]
### TestNG Version
7.4.0
### Expected behavior
When testNG is run from the main class and there are test failures, the java process exits with non-zero code.

### Actual behaviour
Java process always exits with 0 code.

### Is the issue reproducible on the runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I've prepared a sample project:
 https://github.com/baflQA/testNG_parallel_debug
with the tests runner 
https://github.com/baflQA/testNG_parallel_debug/blob/master/src/main/java/testngparallel/jarexitcode/TestRunner.java

In Your shells, run

 ``` 
mvn clean package -DskipTests=true
 ```

It will build a jar with all the dependencies. 
Once the build is finished, run 

```
java -jar target/testNGparallel-1.0.jar
```
Some test failures should be reported. 
In Your shell, execute:

```
echo $?
```

it will print 0, which means that the jar exited with 0 code. 

Shouldn't testNG exit with non-zero code in case there is a tests failure? 
I've workaround that with
```
`if (testng.hasFailure() || testng.hasFailureWithinSuccessPercentage()) {
            System.exit(1);
        }
```
Can You please let me know if exiting with 0 code is expected?

**Comment by krmahadevan** [comment]
@baflQA - In [your](https://github.com/baflQA/testNG_parallel_debug/blob/master/src/main/java/testngparallel/jarexitcode/TestRunner.java#L14) code I dont see you invoking `testNG.getStatus()` which gives you the proper exit code. You should be invoking this method to get the return code from TestNG and then handle it in your `main()` method.

**Comment by baflQA** [comment]
Hey @krmahadevan , thx for the quick reply :) 
In my sample code, I'm not calling this method indeed. 
I was just expecting that run() method will fail if there are any test failure, and I will get a proper exit code out of the box. 
But if it works as designed, then let me quickly investigate how can I handle getStatus() method.

**Comment by baflQA** [comment]
Ok, exiting with 
```testNG.getStatus()``` does the job, so I think that it can be closed. Thx a lot @krmahadevan !
