### ISSUE TITLE
TestNG 7.4.0 throws java.lang.AssertionError: Couldn't find resource: jquery.min.js

### ISSUE THREAD

**Issue by hnestorova** [cbeust/testng#2524]
### TestNG Version
7.4.0

### Expected behavior
Test passes without an error

### Actual behavior
TestNG 7.4.0 throws 
java.lang.AssertionError: Couldn't find resource: jquery.min.js
at org.testng.reporters.jq.Main.generateReport(Main.java:92)
	at org.testng.TestNG.generateReports(TestNG.java:1093)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### Test case sample
I saw a recent report of the same issue with an example case here
https://stackoverflow.com/questions/66971279/eclipse-testng-java-lang-assertionerror

**Comment by krmahadevan** [comment]
@hnestorova 

As of TestNG `7.4.0` the below resources loading viz.,

 1. `jquery.js`
 2. `jquery.min.*`

was streamlined when we fixed https://github.com/cbeust/testng/issues/2406

Please check your CLASSPATH and ensure that you have at-least https://mvnrepository.com/artifact/org.webjars/jquery/3.5.1 

The error is basically indicating that your class path is messed up owing to which TestNG is not able to load `jquery.js` via the web jars dependency.

If this is still a problem, please share a sample project hat can be used to reproduce the problem.

**Comment by qingmo** [comment]
> @hnestorova
> 
> As of TestNG `7.4.0` the below resources loading viz.,
> 
> 1. `jquery.js`
> 2. `jquery.min.*`
> 
> was streamlined when we fixed #2406
> 
> Please check your CLASSPATH and ensure that you have at-least https://mvnrepository.com/artifact/org.webjars/jquery/3.5.1
> 
> The error is basically indicating that your class path is messed up owing to which TestNG is not able to load `jquery.js` via the web jars dependency.
> 
> If this is still a problem, please share a sample project hat can be used to reproduce the problem.

still problem.
I just download jquery webjar file from https://mvnrepository.com/artifact/org.webjars/jquery/3.5.1. Then add it to my eclipse project's `Java Build Path`->Libraries. it appears again.

**Comment by qingmo** [comment]
![image](https://user-images.githubusercontent.com/2457285/118249435-041ee000-b4d8-11eb-8736-c487fd987ed8.png)
the project is quite simple.

**Comment by krmahadevan** [comment]
@qingmo - Is there any specific reason as to why you are not using maven/gradle as a dependency management tool ? Its hard to say what is being resolved in your classpath. The other option is, that you share a project as a reproducible sample.

**Comment by qingmo** [comment]
@krmahadevan  i just use simple java project for demo. so i don't need maven/gradle to build this project. as the result show, lower version(6.4) support this feature, but 7.4.0 report errors.

**Comment by juherr** [comment]
It looks like an eclipse plugin issue because it didn't add all needed dependencies for 7.4.0.

@missedone WDYT?

**Comment by missedone** [comment]
well, what i can tell between 7.4.0 and 7.30 is we have org.webjars.jquery_3.5.1.jar in the update-site:
* https://github.com/testng-team/testng-p2-update-site/tree/main/updatesites/7.4.0.r202105021533/plugins
* https://github.com/testng-team/testng-p2-update-site/tree/main/updatesites/7.3.0.r202008060316/plugins

however, per the code here https://github.com/cbeust/testng/blob/master/core/src/main/java/org/testng/reporters/jq/Main.java#L105-L112, it loads the jquery.min.js from classpath, as long as you put the jar jqury_3.5.1 on your classpath, it should just work.

**Comment by missedone** [comment]
@qingmo and everybody here in this thread, pls make sure you have **jquery 3.5.1** jar on your classpath since the testng code hard-coded the path: https://github.com/cbeust/testng/blob/master/core/src/main/java/org/testng/reporters/jq/Main.java#L105-L112
```
path = "/META-INF/resources/webjars/jquery/3.5.1/jquery.min.js";
```

i know it's not testng issue, but it's how webjars jquery is packaged.

**Comment by juherr** [comment]
@krmahadevan WDYT if we replace the webjar by `xsb.addString("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");`?

**Comment by qingmo** [comment]
> @qingmo and everybody here in this thread, pls make sure you have **jquery 3.5.1** jar on your classpath since the testng code hard-coded the path: https://github.com/cbeust/testng/blob/master/core/src/main/java/org/testng/reporters/jq/Main.java#L105-L112
> 
> ```
> path = "/META-INF/resources/webjars/jquery/3.5.1/jquery.min.js";
> ```
> 
> i know it's not testng issue, but it's how webjars jquery is packaged.

i just run into jquery 3.6.0 when i use testng 7.4.0.
As far as i can see, the codes is hard code with version 3.5.1.
So i have below test with webjars-locator-core support.
```java
public InputStream load(String fileName) {
	    String path;
	    if (fileName.equals("jquery.min.js")) {
	    	WebJarAssetLocator locator = new WebJarAssetLocator();
	    	String fullPathToJquery = locator.getFullPath("jquery.min.js");
	    	System.out.println(fullPathToJquery);
	    	     
	      path = "/" + fullPathToJquery;
	    } else {
	      path = fileName;
	    }
	    return getClass().getResourceAsStream(path);
	  }
```
so i just suggest to add  webjars-locator-core(as same as spring boot project does) for dynamic locate jquery path.

**Comment by missedone** [comment]
@qingmo , if you're talking about https://github.com/mwanji/webjars-locator-core, it might be out of date to be as the dependency of testng.
@juherr @krmahadevan do you have better solution to fix the hard-code jquery location?

**Comment by qingmo** [comment]
i'm talking about https://github.com/webjars/webjars-locator-core
you can get it from https://mvnrepository.com/artifact/org.webjars/webjars-locator-core. And it is not out of date.

**Comment by krmahadevan** [comment]
> @krmahadevan WDYT if we replace the webjar by `xsb.addString("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");`?

@juherr - I think that would work, but it would also mean that this perhaps needs an active internet connection right. So what would happen if a user doesnt have that ?

**Comment by krmahadevan** [comment]
> > @qingmo and everybody here in this thread, pls make sure you have **jquery 3.5.1** jar on your classpath since the testng code hard-coded the path: https://github.com/cbeust/testng/blob/master/core/src/main/java/org/testng/reporters/jq/Main.java#L105-L112
> > ```
> > path = "/META-INF/resources/webjars/jquery/3.5.1/jquery.min.js";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i know it's not testng issue, but it's how webjars jquery is packaged.
> 
> @missedone
> i just run into jquery 3.6.0 when i use testng 7.4.0.
> As far as i can see, the codes is hard code with version 3.5.1.
> So i have below test with webjars-locator-core support.
> 
> ```java
> public InputStream load(String fileName) {
> 	    String path;
> 	    if (fileName.equals("jquery.min.js")) {
> 	    	WebJarAssetLocator locator = new WebJarAssetLocator();
> 	    	String fullPathToJquery = locator.getFullPath("jquery.min.js");
> 	    	System.out.println(fullPathToJquery);
> 	    	     
> 	      path = "/" + fullPathToJquery;
> 	    } else {
> 	      path = fileName;
> 	    }
> 	    return getClass().getResourceAsStream(path);
> 	  }
> ```
> 
> so i just suggest to add webjars-locator-core(as same as spring boot project does) for dynamic locate jquery path.

@qingmo - Why not propose a pull request with this changeset that you are suggesting ?

**Comment by juherr** [comment]
I'm not feeling good to add dependencies only for the reporting part.
The initial idea was to have an integrated and lightweight reporter, and an API for more specific needs.
Why not having a dedicated module for reporters outside the core one?

**Comment by krmahadevan** [comment]
@juherr - If the intent is to have a light weight reporter, then i think we should deprecate and get rid of the html report which relies on JQuery. If we are going to be using jquery then we would need to ensure that we periodically upgrade to the latest variant of it, that is void of any security vulnerabilities. 

Please note that we already added a dependency 

```
    listOf("org.webjars:jquery:3.5.1").forEach {
        api(it)
    }
```

**Comment by juherr** [comment]
> If the intent is to have a light weight reporter, then i think we should deprecate and get rid of the html report which relies on JQuery.

I think so too :) 

> Please note that we already added a dependency

I know but I mean: not adding another dependency for that purpose.
IMO, if we can remove the dependency, it will be a better move.

**Comment by krmahadevan** [comment]
@juherr 

> I think so too :)

Then lets do that. We already have the forked version of reportng in https://github.com/testng-team/reportng So lets deprecate the html report which uses all the jquery stuff and print out warnings to users saying that this would go away from the testng core library and that users can consider using `reportng` and in a future release get rid of the html reports altogether. The emailable report can still exist because its just plain html.

The other advantage with this is that, we just need to maintain reportng and no other reporting mechanisms.

WDYT ?

**Comment by juherr** [comment]
> WDYT ?

:+1:

**Comment by missedone** [comment]
before we have proper solution in testng-core, the testng-eclipse plugin now load the jqury jar onto the test classpath https://github.com/cbeust/testng-eclipse/pull/525

**Comment by missedone** [comment]
https://github.com/cbeust/testng-eclipse/releases/tag/7.4.0.202106051955 is just released.

**Comment by juherr** [comment]
Thanks @missedone

**Comment by shrinivas-baldawa** [comment]
> 
> 
> @hnestorova
> 
> As of TestNG `7.4.0` the below resources loading viz.,
> 
>     1. `jquery.js`
> 
>     2. `jquery.min.*`
> 
> 
> was streamlined when we fixed #2406
> 
> Please check your CLASSPATH and ensure that you have at-least https://mvnrepository.com/artifact/org.webjars/jquery/3.5.1
> 
> The error is basically indicating that your class path is messed up owing to which TestNG is not able to load `jquery.js` via the web jars dependency.
> 
> If this is still a problem, please share a sample project hat can be used to reproduce the problem.

Thank you so much..it solved my problem

**Comment by leerho** [comment]
Well, It is now May 10, 2022 and:
TestNG 7.5.0 throws
java.lang.AssertionError: Couldn't find resource: jquery.min.js 

I am running Eclipse 2021-12 with JDK17 and jquery-3.5.1.jar is definitely in the classpath.

**Comment by gardolf** [comment]
> Well, It is now May 10, 2022 and: TestNG 7.5.0 throws java.lang.AssertionError: Couldn't find resource: jquery.min.js
> 
> I am running Eclipse 2021-12 with JDK17 and jquery-3.5.1.jar is definitely in the classpath.

I'm running into the same issue. I haven't found a solution yet.

[main] ERROR org.testng.reporters.jq.Main - E:\Program-Files\eclipse\eclipse-workspace\hudlmavenproject\test-output\jquery-3.6.0.min.js
java.nio.file.FileAlreadyExistsException: E:\Program-Files\eclipse\eclipse-workspace\hudlmavenproject\test-output\jquery-3.6.0.min.js

**Comment by missedone** [comment]
@gardolf , what's the testng version and testng eclipse plugin version are you using?

**Comment by KiransJingaade** [comment]
i am getting this while installing TestNG
Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
