### ISSUE TITLE
TestNG 7.4.0 (latest version main branch) getVersionString() in org.testng.internal.Version.java return "[WORKING]", not a certain version value.

### ISSUE THREAD

**Issue by shenshaojun1993** [cbeust/testng#2541]
### TestNG Version
 7.4.0

### Expected behavior
getVersionString() returns a certain value like "7.4.0"

### Actual behavior
[WORKING]

### Is the issue reproductible on runner?

- [ √] IntelliJ

![WeChat Screenshot_20210511164028](https://user-images.githubusercontent.com/28006036/117785955-a2603b00-b277-11eb-82aa-0d6f57763889.png)

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by bj-9527** [comment]
After check the source code, I think the version info has been moved to `MANIFEST.MF` file which in the META-INF folder, so you could get the version info from that file during the running of program.

**Comment by shenshaojun1993** [comment]
> After check the source code, I think the version info has been moved to `MANIFEST.MF` file which in the META-INF folder, so you could get the version info from that file during the running of program.

Hi,

Thanks, I will try it.

BR/Shaojun

**Comment by krmahadevan** [comment]
@shenshaojun1993 - Not sure what exactly are you trying. The screenshot you have shared is from the TestNG codebase. Why would you expect that API to work from within the codebase?

I just now tried this in a sample project which has TestNG `7.4.0` as a dependency and it works perfectly fine.

![image](https://user-images.githubusercontent.com/909773/118283211-bcef1a00-b4ec-11eb-90ea-f8a72a0152ff.png)
