### ISSUE TITLE
Allow providing custom file name when parsing XML suite from a dynamically built content

### ISSUE THREAD

**Issue by vlsi** [cbeust/testng#2549]
### TestNG Version

The latest

### Expected behavior

There should be an API to add a custom name to the provided input stream, so exception message could specify "file name" appropriately

### Actual behavior

Currently, TestNG refers to a non-existing file `/home/runner/work/testng/testng/core/testng.xml`, and it is hard to tell where the file was generated.

```
TestNG > Regression2 > test.annotationtransformer.AnnotationTransformerTest > annotationTransformerInXmlShouldBeRun STANDARD_OUT
    [TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >" at the top of the suite file [/home/runner/work/testng/testng/core/testng.xml] otherwise TestNG may fail or not work as expected.
```

### Test case sample

```java
  @Test
  public void annotationTransformerInXmlShouldBeRun() throws Exception {
    String xml =
        "<suite name=\"SingleSuite\" >"
            + "  <listeners>"
            + "    <listener class-name=\"test.annotationtransformer.AnnotationTransformerInTestngXml\" />"
            + "  </listeners>"
            + "  <test enabled=\"true\" name=\"SingleTest\">"
            + "    <classes>"
            + "      <class name=\"test.annotationtransformer.AnnotationTransformerInTestngXml\" />"
            + "    </classes>"
            + "  </test>"
            + "</suite>";

    ByteArrayInputStream is = new ByteArrayInputStream(xml.getBytes());
    Collection<XmlSuite> suites = new Parser(is).parse();
```

**Comment by krmahadevan** [comment]
@vlsi - Outside of a test or outside of a piece of code that uses the TestNG APIs, I am trying to understand in which other use cases would this actually come up ?

The usual thing that a user would do is to create a testng suite xml file and then use that to run the tests and in that case, I believe TestNG gets to know the proper suite name.

Only in cases such as this, TestNG defaults to its known suite file viz., `testng.xml` and appends this information to the current directory to form the suite name (which is not going to exist).

Just adding some additional context to this.

**Comment by vlsi** [comment]
Do you consider `Parser` a public API?
If the API is public, and you allow parsing `InputStream`, then the API should receive an extra `fileName` argument which would be used in error reporing.

I guess `javax.xml.transform.Source#setSystemId` is exactly for the cases like that: a resource can come from various sources (e.g. retrieved from the network or built dynamically), and the user still needs to see a human-readable pointer (e.g. file name, URL, etc)

**Comment by krmahadevan** [comment]
> Do you consider Parser a public API?

I would say _it depends_ because the end-users of TestNG are not expected to be using this API for any needs and it was meant to be serving the purposes of TestNG internally (perhaps the right way of dealing with it would be to move into an `internal` package).

**Comment by vlsi** [comment]
> perhaps the right way of dealing with it would be to move into an internal package

Ok, it makes sense. The class was looking like public API to me, so I raised the question.

However, let me put it in another way: every `Parser(InputStream is)` usage (no matter external or internal) would result in weird error messages. They would mention a non-existing file. So I would deprecate  `Parser(InputStream is)` constructor and add  `Parser(InputStream is, String sourceName)` instead.

PS. An alternative (an extra) option to mark the API is to add https://github.com/apiguardian-team/apiguardian annotations.

**Comment by juherr** [comment]
I agree `Parser` should be moved into internal if there is currently no real-life use case.
We will be free to add anything. Then the current `Parser` can be deprecated without problem.
Someone want to do it?

> PS. An alternative (an extra) option to mark the API is to add apiguardian-team/apiguardian annotations

Or have a distinct `api` module :)
