### ISSUE TITLE
Published 6.7 jar doesn't work

### ISSUE THREAD

**Issue by kyrill007** [cbeust/testng#255]
The 6.7 jar on Maven repo central http://search.maven.org/#search|ga|1|a%3A%22testng%22 is defective. It doesn't contain com/beust/jcommander package thus when you try to run tests (I use Ant), they fail with 

`
[testng] java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
   [testng] Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
   [testng]     at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
`

exception.

**Comment by stephen-smith** [comment]
Well, this is probably going to cause me to switch back to JUnit.  JCommander is not available via our private dependency management system and it serves up the maven jar for testng (and no others).

**Comment by juherr** [comment]
@stephen-smith It's another thing. Could you create an issue which ask to set JCommander optionnal? But I've no idea if it is something possible.
