### ISSUE TITLE
Can we manage indices attributes of DataProvider annotation from @Test or TestNg.xml

### ISSUE THREAD

**Issue by tulsi26ram** [cbeust/testng#2569]
### TestNG Version
> Note: 7.0

### Expected behavior
When we use indices attribute in @DataProvider annotated method, we can execute only for particular sets of data. But in future if we want to execute with different sets of data, we need to update the code. Instead of updating the code, is there any way that we can manage from either @Test level or from TestNg.xml ?

### Actual behavior
Currently we need to update the indices every time whenever we need to execute with different sets of data.

### Is the issue reproductible on runner?
It is not a issue.
- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

@DataProvider(name="testsample", indices={1,3})
public Object[][] myData(){
  return new Object[][]{{"hari","123"},{"raju","345"},{"raju","346"}}
}

**Comment by juherr** [comment]
You can use an Annotation Transformer: https://testng.org/doc/documentation-main.html#annotationtransformers

**Comment by tulsi26ram** [comment]
@juherr : I have tried with IAnnotationTransformer2 which has tranform() method which accepts IDataProviderAnnotation. But i am not able to figure out any method is available to set the indices. Can you please provide me any code snippet.

**Comment by juherr** [comment]
https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/IAnnotationTransformer2.html#transform-org.testng.annotations.IDataProviderAnnotation-java.lang.reflect.Method-

and

https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/annotations/IDataProviderAnnotation.html#setIndices-java.util.List-
