### ISSUE TITLE
Regression: @BeforeMethod failures are missing from new test reports

### ISSUE THREAD

**Issue by kyrill007** [cbeust/testng#257]
Basically, if a test fails inside @BeforeMethod, the new test reports do not show what actually failed (unlike old reports). I will be attaching screenshots to illustrate the issue. The workaround is to look at emailiable-reports.html fail.

**Comment by krmahadevan** [comment]
As of TestNG `6.14.3` (latest released version), there's a small behavior change.

If the intent here is to find out why did a particular test method get skipped, then we can find that out from the new reports as well, by looking at the skipped tests (which now shows you what caused the method to skip) 

The configuration methods (AFAIK) were never shown in the reports at all (irrespective of whether they passed or failed) except for the chronological view (which again doesn't show reason for config failures, if there were any failures).

Closing this as *working as designed*

**Sample class**
```java
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class SampleTestClass {
  @BeforeMethod
  public void beforeMethod() {
    throw new RuntimeException("Failed");
  }

  @Test
  public void testMethod() {
    System.err.println("Hello world");
  }
}
```
screenshot of the report which shows why `testMethod()` failed.

![257](https://user-images.githubusercontent.com/909773/40594406-aae24666-624c-11e8-9cc7-08b1528e8392.jpeg)
