### ISSUE TITLE
Use Guice injector for instantiate IRetryAnalyzer

### ISSUE THREAD

**Issue by qwez** [cbeust/testng#2570]
### TestNG Version
7.4.0

### Expected behavior
Test has been launched

### Actual behavior
org.testng.TestNGException: Cannot instantiate class org.testng.IRetryAnalyzer

### Test case sample
```
@Guice(modules = GuiceModule.class)
public class TestRetry {

    @Test(retryAnalyzer = IRetryAnalyzer.class)
    public void test() {
        assert false;
    }
}
```
```
public class GuiceModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(IRetryAnalyzer.class).to(Retry.class);
    }
}
```
```
public class Retry implements IRetryAnalyzer {
    private int count = 1;

    @Override
    public boolean retry(ITestResult result) {
        return !result.isSuccess() && count-- > 0;
    }
}
```

### Why I need this?
I use dependency injections inside my IRetryAnalyzer implementation, so I got `NullPointerException` if some `@Inject private MyDependency field;` are present in the `Retry` class.

**Comment by bj-9527** [comment]
After check the source code, it may not work for values of `Test` using `@Guice`, so maybe you could use `Retry` directly in `@Test(retryAnalyzer = Retry.class)`, I think this `@Guice` only works for inject. if not, @juherr could please give some comments about this.

**Comment by juherr** [comment]
I confirm that `@Test(retryAnalyzer = Retry.class)` is the best option.

I think a workaround could be possible via https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/annotations/ObjectFactory.html
where you can force the injection by guice (the callback is expected for any object created by testng). 
But it is not a common use-case and can't tell if it will work easily.

**Comment by qwez** [comment]
Yes, `@Test(retryAnalyzer = Retry.class)` is obvious solution, but my `Retry` class looks like:
```
public class Retry implements IRetryAnalyzer {
    private final int count;
    @Inject
    private Retry(MyExternalDependency dependency) {
        count = dependency.getCount();
    }

    @Override
    public boolean retry(ITestResult result) {
        return !result.isSuccess() && count-- > 0;
    }
}
```

So, I need Guice to resolve and provide `MyExternalDependency`

@juherr , any chance to use `org.testng.internal.objects.GuiceBasedObjectDispenser` for `IRetryAnalyzer` instance creation?
I could implement this by my self, if possibility exists.

**Comment by krmahadevan** [comment]
@juherr - Please allow me some time. I will have to get back on this.

**Comment by vlsi** [comment]
@qwez , @bj-9527 , @krmahadevan , I do not fully understand the discussion here, however, it would be great if you could add a use-case to [TestNG DI discussion](https://docs.google.com/document/d/1_Y_jCq6hrEj3n6_fuPBJOAvpo625c_Y1TtO_fncrOEY/edit?usp=sharing) (feel free to request editing permissions or just comment)

**Comment by qwez** [comment]
@krmahadevan have you had a chance to look on this?

@juherr btw, actually, I'am not looking for a workaround (I have one). I think this issue is a bug or feature request, isn't it? All other instances (like DataProvider) are being created with Guice, but RetryAnalyzer is not. Why?

**Comment by krmahadevan** [comment]
@qwez - No. I havent found time yet. I will try to get to this as soon as i get some time.
