### ISSUE TITLE
GuiceBasedObjectDispenser leaks memory

### ISSUE THREAD

**Issue by vlsi** [cbeust/testng#2580]
It looks like a regression since https://github.com/cbeust/testng/pull/2434

```java
class GuiceBasedObjectDispenser {
  private static final Map<Integer, GuiceHelper> helpers = new ConcurrentHashMap<>();
...
      if (ctx == null) {
        helper = helpers.computeIfAbsent(suiteCtx.hashCode(), k -> new GuiceHelper(suiteCtx));
      } else {
        helper = helpers.computeIfAbsent(ctx.hashCode(), k -> new GuiceHelper(ctx));
      }
```

- [ ] It leaks memory into a static `Map`
- [x] It might produce wrong data due to hashCode being used as a key

**Comment by krmahadevan** [comment]
This was fixed as part of commit https://github.com/cbeust/testng/commit/868447b8d824cb3f3a8d00d87c3d44a08161e86e

**Comment by vlsi** [comment]
Memory leak is still there

**Comment by juherr** [comment]
I updated the issue description.
