### ISSUE TITLE
Fix release process via GitHub Actions

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#2582]
After the big module refactoring, the release deployment broke: https://github.com/cbeust/testng/blob/master/.github/workflows/publish-maven-central.yml#L35-L42 

An option is something like
https://github.com/allure-framework/allure2/blob/430255d8cf5c236ed29bc0df0b72dcd9389c3df9/.github/workflows/release.yaml

**Comment by juherr** [comment]
Check https://github.com/shipkit

**Comment by krmahadevan** [comment]
This is taken care of and the release `7.6.0` was done by following the below steps

- Go to https://github.com/cbeust/testng/actions
- Choose https://github.com/cbeust/testng/actions/workflows/publish-maven-central.yml
- Provide an appropriate RC number as per screenshot below
- After the job runs to completion, login to the Nexus Manager portal https://oss.sonatype.org/#welcome using sonatype credentials.
- From Staging repositories view, find TestNG staged repository and release it ( https://oss.sonatype.org/#stagingRepositories )

![image](https://user-images.githubusercontent.com/909773/168975040-61e30749-d2d8-4e6d-85f3-cd9fe35d13ca.png)
