### ISSUE TITLE
Problems with IAnnotationTransformer and Class-Level tests

### ISSUE THREAD

**Issue by baubakg** [cbeust/testng#2585]
### Description
We have discovered if we are using iAnnotationTransformers in Connection with Class level tests, you will face problems is the Classes share description and test groups (more than 1)

(**work around :** make sure the classes have different descriptions)

This problem only arises in 6.X, but not in 7.X (at least not in the same way). I thought i'd simply inform you of thiss even if you won't fix it.

### TestNG Version
6.14.3

### Expected behavior
When you are using IAnnotationTransformer and class level tests

transform should be executed once per class.

### Actual behavior
When you have two  test classes having:
* multiple test groups
* sharing the same groups + dessccription as another class

AnnotationTransformer will consider them as the same class. And will only go through one of the Tests Classes

### Is the issue reproductible on runner?

- [x ] Maven
- [x ] Eclipse

### Test case sample
https://github.com/baubakg/testng-annotationtransformer.git

Two tests show this problem:
* com.adobe.campaign.tests.main.TestEGMProblem.testClassLevel_multiGroups()  -- Simple Case
*  com.adobe.campaign.tests.main.TestEGMProblem.testTestClassLevel_NoDescription_DifferentGroups() -- With different groups

**Comment by juherr** [comment]
> This problem only arises in 6.X, but not in 7.X (at least not in the same way). I thought i'd simply inform you of thiss even if you won't fix it.

Thanks for the report but we only support the latest version.
Feel free to reopen the issue if you can reproduce it in a more recent version.

**Comment by baubakg** [comment]
Hi I think I have found some issues with this now. It seems that if you change the test group of one of two class level tests, which have the same signature (groups + description), you change he values for both
