### ISSUE TITLE
Document the processs of raising a PR for TestNG

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2597]
With recent changes in TestNG's project structure and all the new plugins being added, its better that we create a document that tells a contributor as to what all steps are to be followed so that the PR can pass through all the checks that we have.

Also some steps/instructions on how we can configure the IDE (IntelliJ for e.g.,) to take care of these things would also help

@vlsi - Can you please help share the instructions so that we can include them in our [contributing](https://github.com/cbeust/testng/blob/master/.github/CONTRIBUTING.md) instructions ?

**Comment by krmahadevan** [comment]
@juherr - If you know of the steps, please share them so that we can include them in the contributing markdown file.

**Comment by krmahadevan** [comment]
Running `./gradlew autostyleApply` triggers the formatting from the command line.

**Comment by vlsi** [comment]
I suggest adding the following:

## Importing the project to IntelliJ IDEA

Please use the recent IDEA version like 2021.1+, both Community and Ultimate versions are fine.

1. Import `/build.gradle.kts` as `Project`.

    IDEA might ask you if you trust the project, and it does so for a good reason: a malicious project might steal your credentials, so take your time and verify if you take the sources from https://github.com/cbeust/testng or an authentic mirror.

1. Configure IDEA to avoid `import *`. Open `File` -> `Preferences..` -> `Editor` -> `CodeStyle` -> `Java` -> `Imports`, and adjust `Class count to use import with '*'` to 999, and `Names count to use import with '*'` to 999. Click `OK`.

1. That is it. You should be able to navigate around the code, launch tests, and so on.

## Formatting the code

The project follows [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html), and the preferred way to configure code style is `.editorconfig` file.

You can check if the files align with the style by running `./gradlew autostyleCheck`, and you can apply auto-correctable deviations by running `./gradlew autostyleApply`.

**Comment by vlsi** [comment]
There should probably be something on the naming of the test classes, packages, the style of asserts, and so on, however, I do not know what are the conventions.

For instance, it looks like you prefer adding test classes to the global test suite, however, I find no reason to keep suite for **unrelated** tests.
Suites have two major problems:
1.  The global suite file is prone to merge conflicts (different people might add unrelated tests to the same place in the suite file), so I would rather avoid using suites.
2. One can forget to include the newly added test to the suite, so the test won't get executed at all.

That is why I configured the new modules to use plain test classes, and make Gradle discover them.

**Comment by krmahadevan** [comment]
@vlsi - Here's what i experienced. 

* I pulled the latest changes from `master` branch
* I deleted my `.idea` folder
* I deleted all the `*.iml` files
* I imported the project into Intellij from command line by using `idea .`
* I added the changes that were part of the PR https://github.com/cbeust/testng/pull/2573
* I ran `./gradlew clean test`
* After the tests passed I raised a PR which failed due to codestyle check failure.
* After this I had to run `./gradlew autostyleApply` by referring [here](https://github.com/autostyle/autostyle/blob/master/plugin-gradle/src/main/kotlin/com/github/autostyle/gradle/AutostyleCheckTask.kt#L92)

So I wanted to know, what can we do such that, these codestyle issues etc., can be caught at the time of building the test itself. Earlier we used to have a shell script [build-with-gradle](https://github.com/cbeust/testng/blob/7.4.0/build-with-gradle) which could be run by the contributor and this would run the test.
Can we have something like that, which would ensure that a user is able to apply all the checks (that our CI currently checks) on a user's machine itself, so that they can work on fixing them and incorporating them into their changeset.

Asking a user to fix the validation checks later, kind of deters contributions and I was hoping we can avoid that.

> There should probably be something on the naming of the test classes, packages, the style of asserts, and so on, however, I do not know what are the conventions.

I dont think we have any of that convention yet in the codebase.
Basically there are two types of tests.

1. Tests that are automatically eligible for running which when run can vet out a particular functionality. These are the regular TestNG tests without any extra requirement.
2. Tests that need to use the TestNG apis and which extend the `test.SimpleBaseTest` (this is like a helper base class that provides a lot of convenient functions for creating testng suite, testng test (`<test>` tag) etc., and which internally uses test classes (that look like test classes in point (1) but should not be run on their own but only via the test class (see [org.testng.DryRunTest](https://github.com/cbeust/testng/blob/master/testng-core/src/test/java/org/testng/DryRunTest.java) as an example

The testng suite basically refers to both these types of classes alone and as part of the review we check to ensure that the contributor has added a reference to [src/test/resources/testng.xml](https://github.com/cbeust/testng/blob/master/testng-core/src/test/resources/testng.xml)

We have historically relied on the suite file as the one place to have all the tests run.

The problem of merge conflict happening in suites is applicable even to `CHANGES.txt` (which is usually the area that I have seen PRs having merge conflicts). So the suite file is no exception to that as well.

> That is why I configured the new modules to use plain test classes, and make Gradle discover them.

Can you please point me to that ? I think we need to start documenting a lot of these things so that new contributors dont face difficulties in giving their contributions. As it is we have very less contributors and I dont want to deter any enthusiastic contributors from coming forward with their contributions, because we dont have documentation that clearly explains to them how to go about with their contributions. That is what I am trying to capture as part of this issue.

> You can check if the files align with the style by running ./gradlew autostyleCheck, and you can apply auto-correctable deviations by running ./gradlew autostyleApply.

Is there a way wherein we can have the editor automatically apply this when a user saves code ? We can document that with screenshots if needed so that this gets auto applied. 

For e.g., the codecheck fails if I have an empty method that looks like 

```
public void fun() {
}
```

and expects that the formatting should be 

```
public void fun() {}
```

But intellij by default formats even an empty method as the first variant and not the second variant (This was one of the reasons of failure in my PR that I mentioned above and I had to run that gradle task to get that sorted out and add an additional commit.

> Configure IDEA to avoid import *. Open File -> Preferences.. -> Editor -> CodeStyle -> Java -> Imports, and adjust Class count to use import with '*' to 999, and Names count to use import with '*' to 999. Click OK.

Is it possible to configure this via the editorConfig ? If yes, then maybe we can consider doing that. If its not possible, then atleast we need to have some way wherein we can flag a failure when the user runs tests via some shell script/batch file, so that it can be fixed easily.

I am happy to document all of this, but I need some help with information so that i can collate all of them.

**Comment by vlsi** [comment]
>I imported the project into Intellij from command line by using idea .

That must never be used. IDEA's import should be used instead.

>I ran `./gradlew clean test`

First of all, `./gradlew tasks` should produce meaningful output.

Then, `clean` is not needed here.

There might be several usable Gradle tasks, and different developers have their own habits.
There's no point in having "a single command for everyone".
For instance, some of the developers do not like when tools mess up with their code, and they prefer to make the needed changes manually, so `./gradlew autostyleCheck` would be great for them.

Most of the verifications would be covered by `./gradlew build`.
The missing bits would include tasks like "publish to Central", "sign artifacts".
Publishing tasks can be approximated by `./gradlew publishAllPublicationsToLocalRepository`

>Can you please point me to that ?

Check `testng-asserts` module: https://github.com/cbeust/testng/tree/2c3f38c074c9002f6280eb1e61530e2fcf9a8776/testng-asserts

The tests are located in `testng-asserts/src/test/java` folder, and there is **no** suite file.
If you launch `./gradlew :testng-asserts:test`, then it would run all tests for the asserts module.

> But intellij by default formats even an empty method as the first variant and not the second variant

Frankly speaking, I would prefer the first variant, and I would prefer the formatting that can be configured in IDEA rather than some "technically correct, yet the one that needs to be applied afterwards"

> Configure IDEA to avoid import `*`
> Is it possible to configure this via the editorConfig ? 

Please check `.editorconfig` file. I believe I documented the exact reason there: https://github.com/cbeust/testng/blob/2c3f38c074c9002f6280eb1e61530e2fcf9a8776/.editorconfig#L29-L30

**Comment by juherr** [comment]
@krmahadevan Do you have all the needed elements for updating the process documentation?

**Comment by krmahadevan** [comment]
@juherr - I think so. Let me start compiling this information into a markdown file and then come back here in case i have more questions.
