### ISSUE TITLE
testng.org is down

### ISSUE THREAD

**Issue by benken-parasoft** [cbeust/testng#2607]
testng.org has been down this morning (maybe longer).
So, I can't access anything, including the Eclipse update site.

**Comment by juherr** [comment]
It looks like it is ok now: https://downforeveryoneorjustme.com/testng.org

**Comment by benken-parasoft** [comment]
I can't access it from my corporate network but I can access it from my home network.  Not sure what's going on yet but definitely not and issue for everyone.  Hmm . . .
