### ISSUE TITLE
TestNG suite execution fails all the consecutive methods for Rest APIs when the first POST HTTP Method fails in that sequence

### ISSUE THREAD

**Issue by abhijit1106** [cbeust/testng#2609]
### TestNG Version: 7.4.0
> Note: only the latest version is supported

### Expected Behaviour
1. TestNG suite execution should not fail all the methods consecutively when the first method fails. Even if the first method fails it should pass the remaining methods if there are no errors in the remaining Java Classes. 

### Actual behavior
1. When the first class which is of POST HTTP method in the sequence fails it is failing all the remaining POST and GET methods classes when they are no errors in the codes in those classes.

### Is the issue reproductible on runner?
The Issue is reproducible on Eclipse runner.

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Steps To Reproduce--
1. Keep the POST call class at the Top in TestNG suite file and then execute the suite file. ------ (All Classes execution will fail. -- Refer Image No 1). 
2. Keep the POST call Class at the Bottom in the sequence and execute the suite file. ---  All Classes passed except the POST call class which is at last. (Refer Image No 2).
3. Comment the POST call class and other classes which is having error in code and execute the remaining classes--- All Classes get passed -- Refer Image NO 3. 
4. Keep the POST call class at TOP and comment the classes having error in code and execute the remaining classes- All Classes in that sequence get failed. ----- Refer Image No 4.  

In The API Automation Framework- 
Annotations used are @BeforeClass, @AfterClass, @Test.   Where Before class has a method To get the access Token and After Class has a method to call the logout API to clear user session and @Test is used to get the API response.
![TestNG suite execution Fails- IMAGE 1](https://user-images.githubusercontent.com/47699166/124130488-75245200-da9c-11eb-82e3-3be94f519cf4.png)
![TestNG suite execution Fails- IMAGE 2](https://user-images.githubusercontent.com/47699166/124130497-781f4280-da9c-11eb-8c73-c6c2713efb98.png)
![TestNG suite execution Fails- IMAGE 3](https://user-images.githubusercontent.com/47699166/124130499-78b7d900-da9c-11eb-88cc-6e6ae2c004f3.png)
![TestNG suite execution Fails- IMAGE 4](https://user-images.githubusercontent.com/47699166/124130503-78b7d900-da9c-11eb-80b6-f8141670ea28.png)

**Comment by bj-9527** [comment]
Could you please share your test code, and then we can reproduce it in local. Thanks.

**Comment by abhijit1106** [comment]
Do you want me create a test project and share it with you?

**Comment by krmahadevan** [comment]
@abhijit1106 - Yes that is the ask. Screenshots dont go a long way in terms of providing inputs to figure out where the problem is.

So please help share a simple project (please donot a full fledged project and expect us to use it to reproduce the problem, because its not going to help us).

The project needs to be merely contain enough TestNG code for us to reproduce the problem at hand (So please do leave out any other framework/library references out of the sample project)

**Comment by abhijit1106** [comment]
[TESTNG DEMO PROJECT.zip](https://github.com/cbeust/testng/files/6770287/TESTNG.DEMO.PROJECT.zip)
Please note that I have added the required code in this file. Let me know if you need any other information regarding this.

**Comment by krmahadevan** [comment]
@abhijit1106 - Couple of things

1. Your project is using a really old version of TestNG (`6.9.5`). The latest released version of TestNG is `7.4.0`. Please try your scenario once again and check if the issue is reproducible.
2. If the issue is reproducible in `7.4.0` please refactor the sample project that you attached and ensure that it has only the following:
    1. No external library references. We just need a simple project that has TestNG ONLY as a dependency and which can be used to reproduce the problem.
    2. The project compiles and can be executed (The project that you have shared has package name discrepancies and its not going to be possible for us to spend time trying to fix them to get it to work, not to exclude the fact that the test project has a REST call invocation backed by an excel spreadsheet, which doesnt have any data. So how do we run it ?) Hence the request in (1)

**Comment by abhijit1106** [comment]
How can I share the data related to my project ,  the issue is related API. Ask your dev to reproduce the same using your own API. The TestNG version  7.4.0 is the latest version I m using

**Comment by krmahadevan** [comment]
@abhijit1106 - That is why I was asking that you please share a sample project which only uses testng and which can be used to reproduce thr problem. 

There is no "your dev" in open source projects. I am also a contributor to testng. 

Your pom file shows that you are using an old version of testng. 

Without a reproducible sample not much can be done on this bug in terms of triaging and suggesting a change.

**Comment by abhijit1106** [comment]
Pom is used for maven run. I am not executing through maven, execution
process was through TestNG library not through maven dependency for TestNG.
My job is to report a problem, it's TestNG who need to figure it out and
how they can handle it and I have given enough data and information about
the bug to reproduce

**Comment by krmahadevan** [comment]
@abhijit1106 

* Pon file lets you manage dependencies which eventually boils down to determining what is available in the CLASSPATH. 
* If you are adding jars to CLASSPATH in the ide to run tests then you are perhaps adding confusions to the equation. Please update your pom to use 7.4.0 and try again. 
* Not sure what is the difficulty in giving a simple project which has ONLY testng and which can be used to reproduce the problem. 
* In open source projects you would collaborate to get issues resolved. There are no dedicated full time developers for testng. Everyone who contributes to the project devotes their free time to make things better in testng. 

So am reiterating again. 

Please share a sample project that can reproduce the problem. Else there's not much that can be done on the defect and it will be closed.

**Comment by krmahadevan** [comment]
There is no response from user. Closing this issue. Please feel free to comment with a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) that can be used.
