### ISSUE TITLE
Test methods that dependsOnMethods are not grouped by class

### ISSUE THREAD

**Issue by yurloc** [cbeust/testng#261]
I need to ensure test methods get executed in a given order. This is done by:

```Java
    @Test
    public void testAlpha1() {}

    @Test(dependsOnMethods = "testAlpha1")
    public void testAlpha2() {}
```

Given these two test classes showing methods dependencies:
```
AlphaTest:
- testAlpha1()
  `- testAlpha1()

BetaTest:
- testBeta2()
  |- testBeta1()
  `- testBeta3()
```

the resulting method order should be:
- testAlpha1
- testAlpha2
- testBeta2
- testBeta1
- testBeta3

This is correct up to TestNG 6.1.1. Since 6.2, however, the result is:
- testAlpha1
- testBeta2
- testAlpha2
- testBeta1
- testBeta3

See how methods from different classes are interleaved? Looks like methods that have no dependencies get executed in the first round and the dependent methods come after them.

I need all methods to be **grouped by class** because each test method rely on an external resource configured by `@BeforeClass` method. If testBeta2() is executed before some AlphaTest method, BetaTest's `@BeforeClass` overrides the current configuration and so testAlpha2() fails because the external resource is already configured for BetaTest.

**Comment by astafev** [comment]
This issue can create problems with PowerMock as well, causing:
```
java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	...
```
Reasons are the same: Powermock uses @BeforeClass and @AfterClass to set/unset class loader.

**Comment by romeara** [comment]
Has this been fixed? I attempted to write a test within the project to reproduce this (based on the example project above) and have not been able to create the behavior - I'm not sure if my setup via package is flawed or if it's actually fixed 

Branch: https://github.com/romeara/testng/tree/dev/romeara/261-depends-on-ordering
New test class is in test.dependent package

**Comment by juherr** [comment]
I reproduced the "issue" but "group-by-instances" fixed it.
