### ISSUE TITLE
RetryAnalyzer doesn't work with DataProvider (error: wrong number of arguments)

### ISSUE THREAD

**Issue by maluyvova** [cbeust/testng#2624]
### TestNG Version
> Note: only the latest version is supported

Version: 7.4.0

```xml
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.4.0</version>
</dependency>
```

### Expected behavior
Rerun tests

### Actual behavior
Failing to  wrong number of arguments

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Issue

When have DataProvider and for test params set Array of Objects it's working fine, but when add Retry.class it's failing due wrong number of arguments, however when `unpackage` that Array and in test set exact Objects it's working fine with Retry.class

## Failing on Rerun due  (wrong number of arguments)

```java 
   @DataProvider(name = "dataProvider", parallel = true)
    public Object[][] getTestData() throws Exception {
        return new Integer[][]{
                new Integer[]{5, 1, 15}};
    }

    @Test( dataProvider = "dataProvider", description = "set warning message",retryAnalyzer = Retry.class)
    public void simpleTest(Integer [] integers) throws Exception {
        Assert.assertFalse(true);
    }
```

## Working fine without Retry

```java   
   @DataProvider(name = "dataProvider", parallel = true)
    public Object[][] getTestData() throws Exception {
        return new Integer[][]{
                new Integer[]{5, 1, 15}};
    }

    @Test( dataProvider = "dataProvider", description = "set warning message")
    public void simpleTest(Integer [] integers) throws Exception {
        Assert.assertFalse(true);
    }
```

## Working fine with Retry
```java
    @DataProvider(name = "dataProvider", parallel = true)
    public Object[][] getTestData() throws Exception {
        return new Integer[][]{
                new Integer[]{5, 1, 15}};
    }

    @Test( dataProvider = "dataProvider", description = "set warning message",retryAnalyzer = Retry.class)
    public void simpleTest(Integer one, Integer two, Integer three) throws Exception {
        Assert.assertFalse(true);
    }
```

![OneRun](https://user-images.githubusercontent.com/29768933/128556337-e81814b9-2f5f-4d04-b7dc-53a9f6b53bed.PNG)
![TesngNotWorkingPNG](https://user-images.githubusercontent.com/29768933/128556339-64f46ed0-854f-4637-aadd-9a13e4d7c20f.PNG)
![TesngWorkingPNG](https://user-images.githubusercontent.com/29768933/128556342-66663a46-3e7f-4f93-b66a-fa4874bf9566.PNG)

**Comment by bj-9527** [comment]
Could you please share the code in Retry class?

**Comment by krmahadevan** [comment]
@maluyvova - This is no longer a problem with the current code base and the fix should be available for you, once TestNG `7.5.0` has been released

You can work with the snapshot and check this for yourself
https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/7.5-SNAPSHOT/

**Comment by krmahadevan** [comment]
@juherr - I noticed that we are not using the `x.y.z` versioning strategy after the recent refactoring.

Any idea how to go about fixing this ?

I noticed that the lines https://github.com/cbeust/testng/blob/a397e1b79e5ccb6c5676ab4b1f1311484c93fd71/build.gradle.kts#L6-L7

are adding the version as `7.5-SNAPSHOT` instead of it being `7.5.0-SNAPSHOT`. I am not sure how we can go about fixing this though.

**Comment by juherr** [comment]
@krmahadevan I will check next week, after my hollidays.

**Comment by juherr** [comment]
@krmahadevan Is it important? You can add the `.0` here: https://github.com/cbeust/testng/blob/master/gradle.properties#L8

**Comment by krmahadevan** [comment]
@juherr - the `x.y.z` numbering would be important if we are going to be doing patch releases as well Like for e.g., we can right now consider doing a `7.4.1`. I will make a change in this file to fix this.

**Comment by juherr** [comment]
Ok. I think `x.y.0` and `x.y` are similar: https://blog.soebes.de/blog/2017/02/04/apache-maven-how-version-comparison-works/
BTW, there is no problem to add a trailing 0 :)
