### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#2637]
The new LTS version is out.
It is the good time to follow the rule : target the previous LTS.

WDYT @krmahadevan ?

**Comment by krmahadevan** [comment]
@juherr So it would mean that the minimum JDK version needed for testng would be JDK 11 ?

**Comment by juherr** [comment]
Yes

**Comment by krmahadevan** [comment]
Ok. Should we engage the community via some poll or something before going ahead and doing that ?

**Comment by krmahadevan** [comment]
Also, I feel that before we do an upgrade to JDK11, I think we should go ahead and do a release with `7.5.0` so that all the bug fixes that we have put into it so far, atleast those are available to current users. Maybe we can say that `7.6.0` would need JDK11. WDYT @juherr  ?

**Comment by juherr** [comment]
Yes. We can release the last java 8 version, then upgrade the guideline saying TestNG supports the current and previous LTS.

**Comment by krmahadevan** [comment]
@juherr - Any idea on what would the release process be, with the new gradle changes ?

**Comment by juherr** [comment]
The process is supposed to be the same than previously.
Do you have any issue?

I think you can publish a beta-1 version when you want.
