### ISSUE TITLE
IAnnotationTransformer and Class-Level tests : Problems when setting test groups

### ISSUE THREAD

**Issue by baubakg** [cbeust/testng#2639]
### Description

We have discovered if we are using iAnnotationTransformers in Connection with Class level tests, you will face problems if the Classes share description and test groups (more than 1)

In this case if you have two classes having the same test groups + desccription. If you change the test group of one, it will be changed for both.

(work around : make sure the classes have different descriptions)

### TestNG Version
7.4.0

### Expected behavior
In IAnnotationTraansformeer, if you change the est group of one class it should only affect that class.

### Actual behavior
When using IAnnotationTransformer if you change the est group of a Class Level it will also change all other Class Level tests sharing the same description + test group 

### Is the issue reproducible on runner?

- [ x] Maven
- [ x] Eclipse

### Test case sample
https://github.com/baubakg/testng-annotationtransformer.git

To reproduce issue run
`com.adobe.campaign.tests.main.TestEGMProblem.testTestClassLevel_NoDescription_ChangeGroupOfOne`

In this example I run a test in the package `com.adobe.campaign.tests.case1_fails`
Classes:
- TestClassA
- TestClassB

Have the same groups and descriptions. 

In this case we use the transformer TestGroupTransformer which simply sets the test group of "TestClassA" to "MYGROUP".

However as the test shows, by changing the test group of TestClassA we also change that of TestClassB

**Comment by krmahadevan** [comment]
@baubakg - I think this issue is fixed in TestNG `7.5-SNAPSHOT`.
Please retry using that and post back your result.

You need to add the below as a repository 

```xml
<repository>
    <id>snapshots-repo</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```

```xml
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.5-SNAPSHOT</version>
</dependency>
```

**Comment by baubakg** [comment]
Thanks, I suspected that. I'll give it a try.

**Comment by baubakg** [comment]
Thanks for your input Krishnan. Yes as you suggested, the snapshot does solve this issue.
