### ISSUE TITLE
Streamline Logging Across TestNG

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2646]
### TestNG Version
> Note: only the latest version is supported

7.4.0

Currently TestNG uses a mixture of sysouts and a custom logger that only logs to the console. We should enhance TestNG to use slf4j api integration so that our downstream consumers can basically work with their logging configurations and also help them streamline the test logs.

@juherr WDYT ?

**Comment by juherr** [comment]
Sure, I think slf4j is light enough to be added as a dependency.

From the architecture pov, I think we should keep the current logger facade and call slf4j from there.

**Comment by krmahadevan** [comment]
@juherr  - Cool. I will work on raising a PR that addresses this ask shortly
