### ISSUE TITLE
Inheritance + dependsOnMethods

### ISSUE THREAD

**Issue by karolrom-intel** [cbeust/testng#2658]
### Test case sample
```java
public abstract class Base {
    @Test
    void test() {
        assertEquals(getClass().getSimpleName(), "Test1");
    }
}

class Test1 extends Base {
    @Test(dependsOnMethods = "test")
    void otherTest() {}
}

class Test2 extends Base {
    @Test(dependsOnMethods = "test")
    void otherTest() {}
}
```

### Expected behavior
![image](https://user-images.githubusercontent.com/16337841/137556921-dfed09ab-0ef3-425e-804b-a0d529bd8aff.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/16337841/137556871-4469ea1a-57af-402d-8966-d9e39172bd30.png)

### TestNG Version
7.4.0
I do not know if it worked in the past

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

I do not understand if actual behavior is intended or is a bug, but would that be ok to change it? if not, is there any option that I could override it?

**Comment by krmahadevan** [comment]
@karolrom-intel 

There are a lot of things missing here. Can you please add them ?

What version of Testng are you working with. The latest version is `7.4.0`. 

Is this issue reproducible with Only gradle or is this issue seen even when you run tests from IDE. 

Any information on which testng version was this working fine after which this was broken ? This will help us narrow down the offending change. 

How are you running the tests ? Is there a suite xml that is being used ? If yes, can you please share that as well ?

**Comment by karolrom-intel** [comment]
I have updated my question with additional information.

I have analyzed related code and it looks that `MethodHeler::findDependedUponMethods` uses `MethodHeler::calculateMethodCanonicalName` to determine whether dependency between two test methods exists.

`calculateMethodCanonicalName` takes only `Method` as an input parameter. As both `Test1` and `Test2` class do not override `test` method, they do not have their own "`Method`" instances - canonical name (`Base.test`) will be the same in  both cases:
![image](https://user-images.githubusercontent.com/16337841/137642028-45dcdfcf-248d-48d0-b39c-05e01a427324.png)


https://github.com/cbeust/testng/blob/80e02ff41021210415a49c488089f05b1aa3dd12/testng-core/src/main/java/org/testng/internal/MethodHelper.java#L333

**Comment by krmahadevan** [comment]
@karolrom-intel - Have you seen this work fine before (am trying to figure out if we are dealing with a broken feature or if we are dealing with a _what is the right way this should work_ question). So please let us know what version of TestNG have you noticed this working fine.
