### ISSUE TITLE
"@BeforeClass" is not executed in inheritance order anymore

### ISSUE THREAD

**Issue by mhnot** [cbeust/testng#2670]
### TestNG Version
7.4.0

### Expected behavior
The testNg documentation says:

> TestNG guarantees that the "@Before" methods are executed in inheritance order (highest superclass first, then going down the inheritance chain)

Therefore I expect following output:
- TestParent.beforeClassParent
- TestChild.beforeClassChild
- TestChild.aTestMethod

### Actual behavior
The child impl is called first
- TestChild.beforeClassChild
- TestParent.beforeClassParent
- TestChild.aTestMethod

### Is the issue reproducible on runner?
- [ ] Shell
- [ ] Maven
- [X ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I use a test class that extends an abstract test class. Both have methods annotated with "@BeforeClass".
The child class has additionally the "groups" attribute specified on the @Test annotation on class level.
```
public abstract class TestParent {
  @BeforeClass(alwaysRun = true)
  protected void beforeClassParent() throws Exception {
    System.out.println("TestParent.beforeClassParent");
  }
}

@Test(groups = "windows")
public class TestChild extends TestParent {
  @BeforeClass
  public void beforeClassChild() throws Exception {
    System.out.println("TestChild.beforeClassChild");
  }

  @Test
  public void aTestMethod() {
    System.out.println("TestChild.aTestMethod");
  }
}
```
This is a regression compared to version 6.14.3.

However the order is as expected if I remove the group attribute from TestChild which is no alternative.
Another workaround is to add '(dependsOnMethods = "beforeClassParent")' to "beforeClassChild".

**Comment by martinaldrin** [comment]
Hi, maybe you can try my PullRequest to see if it solves your issue. I also have issues with groups and have created a review for it.
https://github.com/cbeust/testng/pull/2666

**Comment by martinaldrin** [comment]
I tested to add your issue into my PR #2666, seems that my PullRequest solves your issue as well. but my request is not approved since that affect other parts. But I just wanted to inform that We have a similar issue

**Comment by krmahadevan** [comment]
@mhnot - This is now fixed as part of the pull request https://github.com/cbeust/testng/pull/2696

Please retry using the latest snapshot of TestNG `7.5-SNAPSHOT` by adding a `~/.m2/settings.xml` with its contents as below

```xml
<?xml version="1.0"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
	<profiles>
		<profile>
			<id>allow-snapshots</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<repository>
					<id>snapshots-repo</id>
					<url>https://oss.sonatype.org/content/repositories/snapshots</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
			</repositories>
		</profile>
	</profiles>
</settings>
```
