### ISSUE TITLE
Run onTestSkipped for each value from data provider

### ISSUE THREAD

**Issue by karolrom-intel** [cbeust/testng#2674]
### TestNG Version
> 7.4.0

### Expected behavior

Expected test case output:

```
Skipped test2(foo)
Skipped test2(bar)
```

### Actual behavior

Actual test case output:

```
Skipped test2()
```

### Is the issue reproducible on runner?
- Gradle
- IntelliJ

### Test case sample

```java
@Listeners(Example.MyListener.class)
public class Example {
    @Test
    void test1() { Assert.fail(); }

    @Test(dataProvider = "items", dependsOnMethods = {"test1"})
    void test2(String value) { }

    @DataProvider(name = "items")
    Object[][] items() { return new Object[][]{{"foo"}, {"bar"}}; }

    public static class MyListener implements IResultListener2 {
        @Override
        public void onTestSkipped(ITestResult result) { handle(result); }

        private void handle(ITestResult result) {
            Object param = result.getParameters().length != 0 ? result.getParameters()[0] : "";
            System.out.printf("Skipped %s(%s)\n", result.getName(), param);
        }
    }
}
```

I need `handle` method to be called for each value from data provider. 
If I cannot configure it that way, I am ok to cover it in `onTestSkipped` but I would like to know what would be the easiest method to invoke data provider in a generic way (without a direct call to `items` method).

**Comment by krmahadevan** [comment]
@karolrom-intel - Its not clear what you are asking for. Your title says something else, but the description says something else. Also we would like to confine questions to the testng-users google groups mailing list and would like to restrict bugs/new features alone to the github issues page.

**Comment by juherr** [comment]
I think the expected output is 

```
Skipped test2(foo)
Skipped test2(bar)
```

where the actual output is

```
Skipped test2()
```

I think the asked behavior makes sense but I've no idea what can be the impacts.
As always, the new behavior should be opt-out by default.

**Comment by krmahadevan** [comment]
@juherr - A data driven test that has an upstream dependency on a failed method, is going to fail for all iterations for sure.

We already provide the distinction of a method being a data driven test method which should suffice in the reports.
Dumping the parameters associated with every iteration (obtained from a data provider) and then marking it as a skipped for all those instances, just wondering what would that be serving as a purpose?

**Comment by juherr** [comment]
@karolrom-intel could you describe your usage and why you need it?

**Comment by karolrom-intel** [comment]
I use the listener to build custom reports but I think this problem is common for existing reporters.

Each report includes different statistics like the total number of tests or pass rate.
I count each iteration of the data-driven test as a separate test and they are of the same importance as other tests.

people who know nothing about TestNG but read our reports, see that number of tests fluctuates, and the pass rate is unreliable.

**Comment by krmahadevan** [comment]
@karolrom-intel - TestNG evaluates a data driven test and reports it properly ONLY when there are passes and failures but never skips.

Are you asking that skipped data driven tests also be reported, like regular skipped tests ?

**Comment by karolrom-intel** [comment]
Yes, that is exactly what I mean.

**Comment by krmahadevan** [comment]
@karolrom-intel - This is now part of `7.5-SNAPSHOT` and will be available in the upcoming release as well.

To use this feature, you would to set the configuration `includeAllDataDrivenTestsWhenSkipping`.

For e.g., if you were to be enabling this on surefire plugin, your configuration would look like below (In the Maven world)

```xml
<configuration>
	<properties>
		<property>
		  <name>includeAllDataDrivenTestsWhenSkipping</name>
		  <value>true</value>
		</property>
	</properties>
</configuration>
```
