### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by wrbst** [cbeust/testng#2675]
### TestNG Version
7.4.0

### Expected behavior
TestNG should support the LTS Java versions - 11, 17, etc..

### Actual behavior
No information regarding the support of Java 17.

### Additional
When should expect Java 17 support ?
Thank you.

**Comment by juherr** [comment]
I don't get what is expected here.

Do you have some issues with java17 ?

Btw, TestNG is tested against java8, 11 and 17 as you can see in the actions: https://github.com/cbeust/testng/actions/runs/1470006584
