### ISSUE TITLE
TestNG test suites are executed multiple times when run selenium test cases with maven test on bitbucket pipeline where it is working properly in local system

### ISSUE THREAD

**Issue by MeghnaSc** [cbeust/testng#2680]
Anyone can help me regarding same?

**Comment by krmahadevan** [comment]
@MeghnaSc there is no enough information shared. Can you please add more context on what your project looks like, how you are running the pipeline etc? Right now there is no information to debug further.

**Comment by MeghnaSc** [comment]
@krmahadevan Thanks for the quick response..

I have created selenium aumation project and intergrate bitbucket configuration to automate the execution :

Please refer sample bitbucket-pipelines.xml file :

image: markhobson/maven-chrome:jdk-8

pipelines:
  default:
    - step:
        name: Automation Test
        caches:
          - maven
        script:
          - apt-get update
          - mvn clean test        

Whenever I run the pipeline, each test cases will be executed more than one.

Also refer testng.xml file :

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite">

<listeners>

<listener class-name="testcases.Listeners"/>

</listeners>

  <test thread-count="3" name="Test" parallel="classes">
    <classes>
      <class name="testcases.Test1"/>      
    </classes>
  </test> 
</suite>

**Comment by krmahadevan** [comment]
@MeghnaSc - When you run locally are you also doing `mvn clean test` ? Also what does your surefire plugin look like ? Also what does your listener look like ?

**Comment by MeghnaSc** [comment]
Yes with same mvn clean test command.

I am using surefire plugin  like below :

<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
    </plugins>
  </build>

**Comment by krmahadevan** [comment]
Ok. The fact that this works fine locally and the suite file is not getting executed twice re-iterates the fact that there's nothing wrong with TestNG per se here. You may have to dig into your bitbucket pipeline a bit more to find out what it is doing. I am not very conversant on bitbucket pipelines to be honest.  Please check if your pipeline is defining multiple stages wherein the `test` phase or something later than that such as `verify|package|install` etc is being invoked again. That would cause your tests to be run twice.

**Comment by MeghnaSc** [comment]
@krmahadevan Thanks for the quick response..

I did not identify anything in bitbucket-pipelines.yml file which cause this issue..

**Comment by juherr** [comment]
Not a TestNG issue.
