### ISSUE TITLE
Deprecate JUnit support in TestNG

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2683]
Currently TestNG lets a user run their JUnit tests using TestNG.
TestNG still does this only for JUnit3 and JUnit4 based tests.

JUnit has evolved and with JUnit5 coming in, there's a brand new runner capability that is being provided by the JUnit dev team itself using which one can run their testng tests using junit.

https://github.com/junit-team/testng-engine

So it makes little sense for TestNG to still support running JUnit tests using TestNG, because if the user just flips to using the testng-engine library provided by the junit team, they can run their junit as well as testng tests.

This issue is meant to track this ask and eventually remove the junit support in testng.

See here for some more discussion on this https://github.com/cbeust/testng/pull/2677#pullrequestreview-814041661

**Comment by juherr** [comment]
@marcphilipp @sbrannen fyi

**Comment by krmahadevan** [comment]
Closed via https://github.com/cbeust/testng/pull/2849
