### ISSUE TITLE
TestInvoker should clear Thread.interrupted flag before calling ITestListeners

### ISSUE THREAD

**Issue by idontusenumbers** [cbeust/testng#2685]
### TestNG Version
7.4.0

### Expected behavior
`ITestListener`s handling `onTestFailure` are run on a `Thread` that does not have `interrupted` set

### Actual behavior
`InvokeMethodRunnable` calls `Thread.interrupt()` but `TestInvoker` does not clear the `interrupted` flag by calling `Thread.interrupted()`. This prevents all cleanup code from using any IO. In my case, this means I can't grab a screenshot of a failure from a Selenium WebDriver as it immediately throws an `InterruptedException`.

This can be very difficult to diagnose, especially for less experienced folks.

### Workaround
Call `Thread.interrupted()` in `ITestListener` handler method.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners({SampleTestFailureHandler.class})
public class SampleTest {
	
	@Test
	public void sampleTest(){
		throw new AssertionError("force fail");
	}
}
```
```
import org.testng.ITestListener;
import org.testng.ITestResult;

public class SampleTestFailureHandler implements ITestListener {
	@Override
	public void onTestFailure(ITestResult result) {
		System.err.println("Thread interrupted: " + Thread.currentThread().isInterrupted());
	}
}
```

**Comment by krmahadevan** [comment]
@idontusenumbers - Thanks for submitting a detailed issue. Would you be willing to help raise a PR to fix this problem as well, since you have spent so much time in figuring out all the nuances ?

This page should help you understand the process of contributing https://github.com/cbeust/testng/blob/master/.github/CONTRIBUTING.md

What do you think ?

**Comment by idontusenumbers** [comment]
> @idontusenumbers - Thanks for submitting a detailed issue. Would you be willing to help raise a PR to fix this problem as well, since you have spent so much time in figuring out all the nuances ?

Honestly I was expecting a frustrating reason why the interrupt was needed.

If I get around to it, I'll submit a PR

**Comment by morskyrv** [comment]
@idontusenumbers, @krmahadevan  I was not able to reproduce the issue with your test case example. I reproduced it only for methods with timeout and with parallel mode. Added fix for that. It will clear interrupted flag before execution of any config or listener methods.
