### ISSUE TITLE
honor preserve-order in testng.xml and verify compatibility with dependsOnMethods sequencing

### ISSUE THREAD

**Issue by jekhardt** [cbeust/testng#271]
This topic has come up several times over the past couple years, and seems to continue to, so writing up this issue for it. It would be very valuable to my current group and I think in adoption and ease of use by others.

I think the desired behavior was best described in this group post: https://groups.google.com/forum/#!msg/testng-users/_xch2piDVl0/vOWngwFMTJMJ

Basically a user could want tests executed in order 0 - 4. But want test result dependencies on particular tests. There is a distinction between execution order and dependency chaining beyond what dependency chaining implies about execution order.

Say you want execution in this order, 0, 1, 2, 3..  But you want test 1 and 3 dependent on the result of 0.  And test 2 dependent on the result of 1. But test 3 doesn't care about the result of test 2. Say test 3 destroys something needed by test 2 which is why you really want it after test 2.

Desired results could look like...

test 0: success
test 1: success
test 2: fail
test 3: success

or

test 0: fail
test 1: skip
test 2: skip
test 3: skip

In this example, dependsOnMethods use currently forces test 3 to be executed after test 1.. so test 2 is undesirably executed after test 3.

I've seen numerous workarounds for this, but they're all pretty awkward and not really what is desired to be done.  What will it take to have preserve-order honored as a first stage of expressing the test execution sequence and have dependsOnMethods tree validated against it?  This already seems to be done by the inclusion or exclusion of particular methods vs. depeondsOnMethods. If you leave out a depended on method from testng.xml methods list, it will validate and fail. Seems it could do the same for preserve-order=true.

**Comment by krmahadevan** [comment]
The ordering of Testcase execution in TestNG has now changed to the following 

> New: Hierarchy on order features (from less important to more important): groupByInstance, preserveOrder, priority, dependsOnGroups, dependsOnMethods

If this is still a problem, please help share a sample that can be used to reproduce the problem.
