### ISSUE TITLE
Facing this issue while running Test cases through TestNG. Please Help

### ISSUE THREAD

**Issue by singourav** [cbeust/testng#2711]
[RemoteTestNG] failed to get TestNG version from class: java.lang.IllegalArgumentException: invalid version "[WORKING]": non-numeric "[WORKING]"
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] now trying to parse the version from MANIFEST.MF
[RemoteTestNG] parsing TestNG version at jar:file:///C:/Users/Lenovo/Downloads/testng-7.5.jar!/META-INF/MANIFEST.MF
[RemoteTestNG] detected TestNG version 7.5.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.testng@7.5/org.testng.log4testng.Logger.lambda$getLogger$0(Logger.java:30)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.testng@7.5/org.testng.log4testng.Logger.getLogger(Logger.java:30)
	at org.testng@7.5/org.testng.TestNG.<clinit>(TestNG.java:109)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 6 more

**Comment by kobebryant2007** [comment]
It seems testng remove the slf4j dependency, so you should add them by hand in you pom file.

**Comment by krmahadevan** [comment]
@kobebryant2007 - TestNG didn't remove an slf4j dependency until now because it never had that in the first place.
`7.5` introduces a dependency on slf4j because we decided to move into using a proper logging mechanism for TestNG as part of this issue https://github.com/cbeust/testng/issues/2646

@singourav - Please remove any slf4j exclusion that you may have within your project and things should start working fine.

**Comment by singourav** [comment]
I have tried both your suggestions but still it's not working:-
Initially, I tried to add the dependency in pom but it didn't work out
Secondly, I manually deleted slf4j from my .m2 still not happening

**Comment by krmahadevan** [comment]
@singourav - Please share the pom file that you are working with.

**Comment by singourav** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Automation</groupId>
  <artifactId>selenium</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
  
  
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.1.0</version>
</dependency>
  
<dependency> 
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-jdk14</artifactId>
  <version>1.7.30</version>
</dependency>

  
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.4.0</version>
</dependency>
  
 
  
  </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>16</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by singourav** [comment]
<?xml version="1.0"?>

-<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">

<modelVersion>4.0.0</modelVersion>

<groupId>Automation</groupId>

<artifactId>selenium</artifactId>

<version>0.0.1-SNAPSHOT</version>


-<dependencies>





-<dependency>

<groupId>org.seleniumhq.selenium</groupId>

<artifactId>selenium-java</artifactId>

<version>4.1.0</version>

</dependency>


-<dependency>

<groupId>org.slf4j</groupId>

<artifactId>slf4j-jdk14</artifactId>

<version>1.7.30</version>

</dependency>





-<dependency>

<groupId>org.testng</groupId>

<artifactId>testng</artifactId>

<version>7.4.0</version>

</dependency>

</dependencies>


-<build>

<sourceDirectory>src</sourceDirectory>


-<plugins>


-<plugin>

<artifactId>maven-compiler-plugin</artifactId>

<version>3.8.1</version>


-<configuration>

<release>16</release>

</configuration>

</plugin>

</plugins>

</build>

</project>

**Comment by singourav** [comment]
[pom.txt](https://github.com/cbeust/testng/files/7854168/pom.txt)

**Comment by krmahadevan** [comment]
@singourav - I am not able to reproduce the problem that you are facing. Please take a look at the attached zip file which is a sample project. My guess is that you are NOT sharing the proper sample.

[issue_2711.zip](https://github.com/cbeust/testng/files/7854235/issue_2711.zip)
