### ISSUE TITLE
beanshell dependency removed from testng

### ISSUE THREAD

**Issue by martinaldrin** [cbeust/testng#2715]
Hi,

Beanshell was under compile scope in TestNg 6.14.3, but totally removed in 7.5.
Why not add beanshell as a optional dependency since it seems that it is still supported, at least documentation still exists
https://testng.org/doc/documentation-main.html#beanshell

### TestNG Version
7.5
### Expected behavior
Add beanshell as a optional dependency if TestNg still support beanshell.

### Actual behavior
beanshell is removed

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@martinaldrin - TestNG has moved into a SPI approach for loading `javax.script.ScriptEngineFactory` implementations. This basically removes any dependency that TestNG has to by default bring in for supporting method selectors via beanshell (or) javascript. 

Thanks for pointing out this missing information on the documentation. We will update the documentation stating that if one needs to use beanshell for method selectors they can add up an explicit dependency on https://mvnrepository.com/artifact/org.apache-extras.beanshell/bsh/2.0b6 

Personally I see no reason for TestNG to continue to bring in such optional dependencies which can very well be added up by a downstream consumer based on their individual needs.

**Comment by martinaldrin** [comment]
thanks for the information, I just thought that this is the purpose of the optional, since they will not be resolved unless I manually add them. but I'm fine if the documentation is updated as well.

**Comment by juherr** [comment]
It was optionnal before because we had a real dependency at compile time.

Now, no more need to have it 😉
