### ISSUE TITLE
Honour custom attribute values in TestNG default reports

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2725]
### TestNG Version
> Note: only the latest version is supported
7.5

TestNG supported the notion of custom attributes in it as part of this issue https://github.com/cbeust/testng/issues/2003

But these custom attributes don't show up in the TestNG provided default reports. This issue tracks this requirement.

**Comment by itkhanz** [comment]
@krmahadevan Thanks for making this attribute also available in testng reports. Is it possible to add this custom attribute as part of junit xml reports also? perhaps as:

`<testcase classname="com.tests.ExampleTest" name="test_example_method" time="23.164" attributes="{ATTR_NAME:ATTR:VALue}"/>`

This will then enable other reporters to parse this information from JUNIT XML reports produced by TestNG.
