### ISSUE TITLE
Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml. Permission denied: no further information

### ISSUE THREAD

**Issue by kanishkapundir** [cbeust/testng#2728]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
For issues with TestNG eclipse plugin please file them in https://github.com/cbeust/testng-eclipse/issues
