### ISSUE TITLE
Show fully qualified name of the test instead of just the function name for better readability of test output.

### ISSUE THREAD

**Issue by nickolay-kondratyev** [cbeust/testng#2741]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Show fully qualified name of the test in the test output instead of just function name. This will increase the readability of test output by including the class name of the test (especially when nested classes are used). 

### Actual behavior
Only the function of the test name is displayed (class name especially nested class names are not displayed).

Eg.

```
PASSED: test_customerImageStatus
```

### Is the issue reproducible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Any test case should show this.

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by Janos893** [comment]
It is a good idea!
