### ISSUE TITLE
Element not Clickable, ''Login'' button blocked by Cookie Element

### ISSUE THREAD

**Issue by oshodiab** [cbeust/testng#2746]
### TestNG Version
> <version>6.14.3</version>

### Expected behavior
Login into Application 

### Actual behavior
org.openqa.selenium.ElementClickInterceptedException: Element <input name="btnLogin" type="submit"> is not clickable at point (575,393) because another element <div id="gdpr-consent-tool-wrapper"> obscures it
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- **[ ] IntelliJ**
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
package com.Interbanking.testCases;

import com.Interbanking.pageObjects.AddCustomerPage;
import com.Interbanking.pageObjects.LoginPage;
import org.apache.commons.lang3.RandomStringUtils;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;
import org.testng.Assert;

import java.io.IOException;

public class TC_AddNewCustomer_003 extends BasePage {

    @Test
    public void addNewCustomer() throws InterruptedException, IOException {
        LoginPage lp = new LoginPage(driver);
        lp.setUserName(username);
        logger.info("User name is provided");
        lp.setPassword(password);
        logger.info("Password is provided");
        lp.clickSubmit();

        Thread.sleep(3000);

        AddCustomerPage addcust = new AddCustomerPage(driver);
        addcust.clickAddNewCustomer();

        addcust.custName("bale");
        addcust.custgender("male");
        addcust.custdob("10", "15", "1985");
        Thread.sleep(5000);
        addcust.custaddress("NIGERIA");
        addcust.custcity("LAG");
        addcust.custstate("AP");
        addcust.custpinno("5000074");
        addcust.custtelephoneno("987890091");

        String email = randomestring() + "@gmail.com";
        addcust.custemailid(email);
        addcust.custpassword("abcdef");
        addcust.custsubmit();

        Thread.sleep(3000);

        logger.info("validation started....");

        boolean res = driver.getPageSource().contains("Customer Registered Successfully!!!");

        if (res == true) {
            Assert.assertTrue(true);
            logger.info("test case passed....");

        }

        else

            {
            logger.info("test case failed....");
            captureScreen(driver, "addNewCustomer");
            Assert.assertTrue(false);
        }

        }

}

Base Class 
=============
package com.Interbanking.testCases;

import com.Interbanking.utilities.ReadConfig;
import com.aventstack.extentreports.utils.FileUtil;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.RandomStringUtils;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;

import com.Interbanking.CookieExample.cookieRead;

//import org.apache.commons.lang3.RandomStringUtils;
//import org.apache.log4j.Logger;
//import org.apache.log4j.PropertyConfigurator;
//import java.util.logging.Logger;

public class BasePage {

    ReadConfig readconfig = new ReadConfig();

    public String baseURL = readconfig.getApplicationURL();
    public String username = readconfig.getUsername();
    public String password = readconfig.getPassword();
    public static WebDriver driver;

    //public String baseURL="https://demo.guru99.com/v4/index.php";
    //public String username="mngr367875";
    // public String password="mEnezaq";
    //public static WebDriver driver;

  public static Logger logger;

    @Parameters("browser")
    @BeforeClass
    public void setup(String br)
    {

        logger = Logger.getLogger("ebanking");
        PropertyConfigurator.configure("log4j.properties");

        if (br.equals("firefox")) {
            System.setProperty("webdriver.gecko.driver", readconfig.getFirefoxPath());
            driver = new FirefoxDriver();

        }

         else if (br.equals("chrome")) {
                System.setProperty("webdriver.chrome.driver", readconfig.getChromePath());
                driver = new ChromeDriver();

            }

            else if (br.equals("ie")) {
            System.setProperty("webdriver.ie.driver", readconfig.getIEPath());
            driver = new InternetExplorerDriver();

        }

        //driver.findElement(By.id("Accept All")).click(); // Clicking on the popup button
        //driver.switchTo().alert().accept();
        //driver.findElement(By.xpath("/html/body/app-root/app-theme/div/div/app-notice/app-theme/div/div/app-home/div/div[2]/app-footer/div/div[2]/app-action-buttons/div/button[3]/span[1]/div/span")).click();

        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        driver.get(baseURL);

        

       

    }

               // @AfterClass
              //  public void tearDown()
               // {

                   //driver.close();
                //}

                   public void captureScreen(WebDriver driver, String tname) throws IOException {
                       TakesScreenshot ts = (TakesScreenshot) driver;
                       File source = ts.getScreenshotAs(OutputType.FILE);
                       File target = new File(System.getProperty("user.dir") + "/Screenshots/" + tname + ".png");
                       FileUtils.copyFile(source,target);
                       System.out.println("Screenshot taken");
                   }

    public String randomestring()
    {
        String generatedstring= RandomStringUtils.randomAlphabetic(8);
        return (generatedstring);
    }

    public String randoneNum()
    {
        String generatedstring2=RandomStringUtils.randomAlphanumeric(4);
        return (generatedstring2);
    }

}

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
Closing this issue. Please comment once you are able to share a sample that can demonstrate the problem using latest released version of TestNG.
