### ISSUE TITLE
Add assertEquals methods for Iterable and Iterator

### ISSUE THREAD

**Issue by electrum** [cbeust/testng#275]
There are currently `assertEquals` methods for `Collection`, `Set` and `Map`. It would be helpful to have one for `Iterable` and `Iterator`. The `Iterable` version would simply delegate to the `Iterator` method after retrieving the iterators.

**Comment by raindev** [comment]
It was done already here: cbeust/testng#278. The issue could be closed.

**Comment by krmahadevan** [comment]
Closing this issue.
