### ISSUE TITLE
Exception: ERROR java.nio.file.NoSuchFileException: /tmp/testngXmlPathInJar-15086412835569336174

### ISSUE THREAD

**Issue by martinaldrin** [cbeust/testng#2761]
### TestNG Version
7.6.0

I have some bad news with last release 7.6.0, We tested a snapshot last week from master and that was working. But there seems to be a new commit in-between that affects us badly. non of the executions passed.

I expect it is related to this commit: [d190ade](https://github.com/cbeust/testng/commit/d190ade58a58e20ced922d47a9114958a5a05e8a)

Seems that some tmp path is added infront of the path

argument: -xmlpathinjar suites/postrelease/emulator_wrat_postrelease.xml

Exception: 2022-05-18T08:44:26,315 ERROR java.nio.file.NoSuchFileException: /tmp/testngXmlPathInJar-15086412835569336174/suites/old_action_test_suites/rnc_action_regression_with_configurationdata.xml

### Sample Test
```
package org.testng.sample;
import org.testng.annotations.Test;
public class XmlPathInJarTest {
		@Test
		public void test() {
			System.out.println("Test");
		}
}
```

### Sample Suite
```
<suite name="MJE PostRelease test on G2Rbs" verbose="1">
    <test name="XmlPathInJarTest" preserve-order="true">
        <classes>
            <class name="org.testng.sample.XmlPathInJarTest" />
        </classes>
    </test>
</suite>
```

### Command
java -classpath target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.testng.TestNG -testjar target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar -xmlpathinjar suites/xmlpathinjarSuite.xml

### TestNG 7.5 Output
```
Test

===============================================
MJE PostRelease test on G2Rbs
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================
```

### TestNg 7.6.0 Output
```
bash-3.2$ java -classpath target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.testng.TestNG -testjar target/testng-sample-xmlpathinjar-0.0.1-SNAPSHOT-jar-with-dependencies.jar -xmlpathinjar suites/xmlpathinjarSuite.xml
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
13:10:47.078 [main] ERROR org.testng.TestNG - java.nio.file.NoSuchFileException: /var/folders/3l/qqzzwt655k16_hjq1gk_grl40000gp/T/testngXmlPathInJar-16857375091475056093/META-INF/maven/com.google.code.findbugs/jsr305/pom.xml
```

**Comment by krmahadevan** [comment]
@martinaldrin - Can you please help add a sample that I can use to reproduce the problem ?

**Comment by martinaldrin** [comment]
> @martinaldrin - Can you please help add a sample that I can use to reproduce the problem ?

Added Example code and command above.

**Comment by martinaldrin** [comment]
I did some testing and reverted one line, so it seems to be working if I switch back this line.

![image](https://user-images.githubusercontent.com/3080866/169228778-3b6d12d2-e185-4100-8ef8-8fb134501491.png)


https://github.com/cbeust/testng/commit/d190ade58a58e20ced922d47a9114958a5a05e8a#diff-2be212be737b88302f4058b07a51c8731b5480f824a6fe98a85354e38a9fff95L79

**Comment by martinaldrin** [comment]
After more investigation I found the issue, I copied the file check from the old method and added that infront of the copy method and that seems to solve the issue. We need to ensure that the parent directory exists before we copy the file.

```
 if (!copyFile.getParentFile().exists()) {
            copyFile.getParentFile().mkdirs();
}
Files.copy(inputStream, copyFile.toPath());
```

**Comment by martinaldrin** [comment]
I have created a PR now for the issue, but I have no idea about how to create unit tests for the issue.

**Comment by krmahadevan** [comment]
@martinaldrin - Can you please check this version and see if all is well ?

https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/7.6.1-SNAPSHOT/

**Comment by martinaldrin** [comment]
Hi, Yes I will try it.

**Comment by martinaldrin** [comment]
Hi,

I can see that this issue is resolved, our test has passed.
But it can take some days before my commit is used in all our Test loops to be ensure that there is not other bugs introduced. But I see that as very low risk since my last test was based on a commit from 9th of May and that was working fine.

**Comment by krmahadevan** [comment]
@martinaldrin - Can you please check this once again against 7.6.1-SNAPSHOT. We plan to do a bug fix release over the weekend and would like to ensure that all is well.

**Comment by martinaldrin** [comment]
@krmahadevan We have been running a fork from your PR during for days now and it seems to works well. Many thanks for fast fix.

If you have submitted any new changes after this fix I have hard to try it during the weekend since we have vacation today and tomorrow.

**Comment by krmahadevan** [comment]
@martinaldrin - Yes we removed that deprecated method.

**Comment by martinaldrin** [comment]
Thanks, then it will take a bit longer for me to verify since then other projects needs to be updated.

**Comment by krmahadevan** [comment]
Sure. I can wait to hear back.

**Comment by martinaldrin** [comment]
@krmahadevan  I have now been running latest TestNg for 3 days and everything seems to be working fine so far.

**Comment by martinaldrin** [comment]
Hi @krmahadevan  do you still plan to do the bug fix release for 7.6.1 or do you plan to include more fixes before the release?

**Comment by krmahadevan** [comment]
> Hi @krmahadevan  do you still plan to do the bug fix release for 7.6.1 or do you plan to include more fixes before the release?

Yes if this fix is absolutely the immediately needed for you folks to consume 7.6.0 else we can stall it to 7.7.0 which is probably atleast a couple of months away. 

Let me know how you want it.

**Comment by martinaldrin** [comment]
Hi, yes this fix is required for us. Not a single test can pass at the moment with 7.6.0 since all our executions uses xmlPathInJar.

**Comment by krmahadevan** [comment]
@martinaldrin 

I have published a release candidate for `7.6.1`

You can get access to it by adding a repository entry such as below

```xml
        <repository>
            <id>maven-central-staging</id>
            <url>https://oss.sonatype.org/content/repositories/orgtestng-1082</url>
        </repository>
```

or if you are using Gradle, please add 

```
repositories {
    mavenCentral()

    maven {
        url 'https://oss.sonatype.org/content/repositories/orgtestng-1082' }
}
```

and add a dependency on to TestNG `7.6.1` and let me know if all is well.
Once I hear back from you, I will go ahead and finish the release process by releasing the version from the Nexus Staging repository.

**Comment by bobshie** [comment]
@krmahadevan , I'll test the TestNG version 7.6.1 rc version. and come back here after several days. 
Thanks.

**Comment by bobshie** [comment]
@krmahadevan, We have done the test and don't find any new issue on the version. 
https://oss.sonatype.org/content/repositories/orgtestng-1082/org/testng/testng/7.6.1/testng-7.6.1.jar
Thanks.

**Comment by bobshie** [comment]
@krmahadevan , OK, Very thanks for your help.
