### ISSUE TITLE
Unable to install testNg

### ISSUE THREAD

**Issue by NaukhezZaman** [cbeust/testng#2767]
Hi,

Can you please help me in installing TestNG. I have tried with current site but still getting "Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

Is there any updated site of TestNG?

**Comment by onkobu** [comment]
https://testng.org/testng-eclipse-update-site/content.xml leads to 404, so Eclipse cannot load the package catalog. Further down, for example by crafting a complete URL with a downloadable ZIP TLS certificate presents hostnames that point to GitHub. Most LTS JDKs bail out with hostname validation errors. (That cannot be suppressed.)

**Comment by onkobu** [comment]
And also dragging the Install-button from Marketplace leads to the same error since it uses the same URLs.

**Comment by krmahadevan** [comment]
@onkobu - Can you please file the eclipse plugin related issues in this project https://github.com/cbeust/testng-eclipse

**Comment by krmahadevan** [comment]
@missedone - Can you please help here ?

**Comment by rr-nick-tan** [comment]
@NaukhezZaman @onkobu let's use this issue https://github.com/cbeust/testng-eclipse/issues/529 to track the progress

**Comment by krmahadevan** [comment]
Closing this issue, since its being tracked in the testng eclipse project
