### ISSUE TITLE
After upgrading to TestNG 7.5.0, setting ITestResult.status to `FAILURE` doesn't fail the test anymore

### ISSUE THREAD

**Issue by asolntsev** [cbeust/testng#2771]
### TestNG Version
* 7.5
* 7.6.0

### Given
A project with Listener (my custom "soft assert" listener) which marks `ITestResult` status as `FAILURE` after the test. 

### Expected behavior
I expect my test to fail. 

### Actual behavior
After upgrading to TestNG 7.5, my test doesn't fail anymore. It's a bug. 

### Is the issue reproducible on runner?

- [x] Maven
- [x] Gradle
- [x] IntelliJ

### Test case sample
Please check this trivial project which stabely reproduces the problem:
https://github.com/asolntsev/testng-listeners-sample

**Comment by krmahadevan** [comment]
Can you please check in 7.6.0 which is the latest released version @asolntsev

**Comment by asolntsev** [comment]
@krmahadevan Just tried: the problem still reproduced with TestNG 7.6.0

**Comment by asolntsev** [comment]
@dr29bart Yes, it seems so. Generally, the idea to preserve the order of listeners is good. But still, TestNG own listeners should be executed AFTER all user-defined listeners (after test execution).

**Comment by hornyja4** [comment]
Hi guys, any progress in this? Totally agree with @asolntsev. This issue affected all our unit tests.

**Comment by YaroslavBurlakaLS** [comment]
Hi guys !
Can you pleae tell when this fix will be released ?

**Comment by krmahadevan** [comment]
@YaroslavBurlakaLS - We are working on adding a few more fixes before `7.8.0` goes out. So this should be out hopefully by the end of this month.
