### ISSUE TITLE
Allure report generation issues due to change in listener order after github 2588

### ISSUE THREAD

**Issue by emerson-b** [cbeust/testng#2778]
### TestNG Version
7.5 onwards 

### Expected behavior
The Allure report listener would be triggered at the end of the list of listeners for runTestListeners()
![image](https://user-images.githubusercontent.com/5680833/177509902-c7a9c7ff-878e-4cba-8154-f2b39b5910a8.png)

### Actual behavior
Since 7.5 onwards, the list of listeners is reversed for onFinish test listeners.
`List<ITestListener> listeners = isFinished ? Lists.newReversedArrayList(this.m_notifier.getTestListeners()) : this.m_notifier.getTestListeners();`

![image](https://user-images.githubusercontent.com/5680833/177511096-e216487c-a6f5-46ef-80da-7cfbb0b62776.png)

By reversing this order, the allure listener is triggered first stopping the reporting before any screenshots / end of test data can be captured and attached.

There is no way to stop this reversing of listener order.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Comment by emersonbaillie** [comment]
> Maybe you could refer to this blog post of mine and see if that helps: https://rationaleemotions.com/listener_order/ You can always build your decorated listener which can inject the listeners in the order you would like. Can you please try that?

Hi @krmahadevan I'll try and get an implementation going today to resolve this. Does this approach work with mixing 3rd and 1st party libraries like `io.qameta.allure.testng` + my own listeners?

**Comment by krmahadevan** [comment]
> Does this approach work with mixing 3rd and 1st party libraries like io.qameta.allure.testng + my own listeners?

Yes it should. But if the 3rd party libraries are being wired in via service loaders, then there's not much that you can do, because TestNG will find them as well and i am not sure as to what is the order of that because that's the JVM working.

**Comment by emersonbaillie** [comment]
@krmahadevan Thanks for this article, using the META-INF of the parent dependency project `main>resources>META-INF>services>org.testng.ITestNGListener` I could specify the order that the listeners were picked up

**Comment by krmahadevan** [comment]
So can we close this issue @emersonbaillie ?
