### ISSUE TITLE
Outdated version number at testng.org/doc/download.html

### ISSUE THREAD

**Issue by gruenich** [cbeust/testng#2779]
### TestNG Version
7.6.1

### Expected behavior
Visit testng.org/doc/download.html, there should be mentioned the latest version (7.6.1).

### Actual behavior
It shows the outdated version 7.6.0. 
I couldn't find the website content. Otherwise I would have created a merge request.

**Comment by krmahadevan** [comment]
@gruenich - You can submit a PR at here https://github.com/testng-team/testng-team.github.io
