### ISSUE TITLE
Javadoc is currently invalid

### ISSUE THREAD

**Issue by iay** [cbeust/testng#2789]
### TestNG Version

> Note: only the latest version is supported

n/a

### Expected behavior

The Javadoc at <https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/>, referred to by the web site, should be valid.

### Actual behavior

Browsing that location gives a directory listing. Various files there contain the following:

```
Build failed. See the log at jitpack.io
```

Of course, this means that any builds referencing this Javadoc are also failing.

**Comment by krmahadevan** [comment]
This is now fixed and the TestNG documentation portal correctly redirects the user to https://javadoc.io/doc/org.testng/testng/latest/index.html

[This is the PR](https://github.com/testng-team/testng-team.github.io/pull/42) that fixed the documentation portal.
