### ISSUE TITLE
wrong testng-failed.xml generating

### ISSUE THREAD

**Issue by KritikaSahare1611** [cbeust/testng#2790]
### TestNG Version
latest 

### Expected behavior
My suite XML file has 3 test cases. After running the suite, all the tests are having passed status. 
test - 1
test - 2
test - 3

Out of these tests,test-1 is passed after retrying (have used a retry analyzer).But basically after the suite completion.All my 3 testcases are in passed state.

### Expected behavior
testng-failed XML should not be generated because no tests is in failed state.

### Actual behavior
testng-failed XML is generated containing test-1 as failed

### Is the issue reproducible on runner?

maven

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@KritikaSahare1611 - Please include a sample project that uses TestNG `7.6.1` (latest released version as of today) that can be used to reproduce the problem. Without a sample, not much can be commented on what is going on.

**Comment by krmahadevan** [comment]
Closing this ticket since there's no response from the user
