### ISSUE TITLE
Test Smell: it is not a good test practice to write return statement in test cases

### ISSUE THREAD

**Issue by TestSmell** [cbeust/testng#2794]
Hi!

We notice that a test case in your project does nothing but has a return statement. 
<img width="404" alt="截屏2022-08-18 下午6 46 14" src="https://user-images.githubusercontent.com/110402847/185378408-5ebd50af-9296-49f9-8040-c523821be4a3.png">

Is it a useful test case? As far as I know, it is not a good test practice to write a return statement in a test case. Thanks.

**Comment by krmahadevan** [comment]
@TestSmell - Please post TestNG related questions on the [TestNG-Users](https://groups.google.com/g/testng-users) forum and not here. 

We would like to keep the Github page confined only to issues.
