### ISSUE TITLE
TestNG 

### ISSUE THREAD

**Issue by umair4321** [cbeust/testng#2799]
### TestNG Version
> Note: only the latest version is supported

### Actual behavior
Unable to read repository at https://testng.org/testng-eclipse-update-site.
Unable to read repository at https://testng.org/testng-eclipse-update-site/6.12.0/compositeContent.xml.
No route to host: no further information

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by juherr** [comment]
Please, report it at https://github.com/cbeust/testng-eclipse
