### ISSUE TITLE
How to Execute Cucumber Features in Parallel using TestNG?

### ISSUE THREAD

**Issue by pabitra-qa** [cbeust/testng#2803]
Is there an option to pass the features through dataprovider to execute cucumber features in parallel instead of scenarios?

```
import org.testng.annotations.DataProvider;
import io.cucumber.testng.AbstractTestNGCucumberTests;

public class RunCucumberTest extends AbstractTestNGCucumberTests{

    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
```

**Comment by juherr** [comment]
I don't see why it cannot be possible but it may have some limitations from testng too.

I think it is more a question for cucumber because we have no idea how it is integrated with testng.

**Comment by pabitra-qa** [comment]
@juherr Thanks! Let me ask this to the Cucumber team. If they have any solution.
