### ISSUE TITLE
Ability to retry a data provider in case of failures

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2819]
### TestNG Version
> Note: only the latest version is supported

7.6.1

### Expected behavior

The data provider is retried automatically

### Actual behavior

No generic mechanism to retry a data provider without doing it at a per data provider level.

### Is the issue reproducible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

No testcase, since this is a new requirement. For more details please take a look at this user post https://groups.google.com/g/testng-users/c/7Q40qIPcOLc/m/W7ibgBW2AQAJ

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by baflQA** [comment]
@krmahadevan thanks for bringing it into GitHub. 
Do You have any implementation ideas on how to approach this task?

**Comment by krmahadevan** [comment]
> @krmahadevan thanks for bringing it into GitHub. 
> 
> Do You have any implementation ideas on how to approach this task? 

@baflQA 
An working on the PR for this. Should be done in a few hours. 

The implementation would be similar to how we use retry analyser for test methods so that one can have different retry implementations for different data providers.

**Comment by baflQA** [comment]
You are amazing @krmahadevan ! Can't wait for the next release. 
Thank You for all Your work.
