### ISSUE TITLE
GitHub Depenabot shows me a high vulnerability in testNG

### ISSUE THREAD

**Issue by moatazeldebsy** [cbeust/testng#2851]
### TestNG Version
> in the latest version is supported 7.6.1

<img width="1370" alt="Screenshot 2022-12-07 at 20 40 16" src="https://user-images.githubusercontent.com/45570191/206279793-6398ddfc-2ef2-4928-8ab9-d8bbaaf03284.png">

### Expected behavior

<img width="1235" alt="Screenshot 2022-12-07 at 19 06 14" src="https://user-images.githubusercontent.com/45570191/206279783-48ebf6b3-352e-4648-b87b-f7c21b0e8c16.png">

Can someone clarify what's the issue here, especially it's affecting all the testNG versions on the maven repository

**Comment by krmahadevan** [comment]
Please refer to https://github.com/cbeust/testng/pull/2806 for understanding the context behind what this is all about.

To consume a staged release candidate refer https://github.com/cbeust/testng/issues/2665#issuecomment-1339138206

**Comment by moatazeldebsy** [comment]
OK Thank you @krmahadevan

**Comment by krmahadevan** [comment]
@moatazeldebsy - TestNG 7.7.0 which contains this fix has been released. Please check

Duplicate of #2852
