### ISSUE TITLE
How to check the test case corresponding to the invocation-numbers value from testng-failed.xml?

### ISSUE THREAD

**Issue by akshayamaldhure** [cbeust/testng#2853]
### TestNG Version
7.4.0

### Expected behavior
The test that failed in the first run should be the one that is retried.

### Actual behavior
Some other test is run in the retry using the testng-failed.xml file.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [✓] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I'm having a bunch of tests that I run in parallel with a `dataproviderthreadcount` of 10. I see that the test that fails in the first run is not the same as that run in a retry using the testng-failed.xml file that looks like below. I believe the `invocation-numbers` property value is used for retrying the failed tests. Since I observe the issue with a 100% replication rate, I'd first like to understand how to identify the test case corresponding to this value.

```
<suite thread-count="10" parallel="classes" name="Failed suite [Gradle suite]" verbose="0">
<test thread-count="10" parallel="classes" name="Gradle test(failed)" verbose="0">
<groups>
<run>
<include name="GROUP_1"/>
<include name="GROUP_2"/>
</run>
</groups>
<classes>
<class name="package.TestSample">
<methods>
<include name="beforeSuiteHook"/>
<include name="verifySomething" invocation-numbers="9"/>
<include name="beforeMethodHook"/>
<include name="afterSuiteHook"/>
</methods>
</class>
<!--  package.TestSample  -->
</classes>
</test>
<!--  Gradle test(failed)  -->
</suite>
<!--  Failed suite [Gradle suite]  -->
```

**Comment by krmahadevan** [comment]
@akshayamaldhure Can you please retry using `7.7.0` and see if its still a problem. 

If the issue persists can you please share a sample project that can be used to reproduce the problem ?

**Comment by akshayamaldhure** [comment]
> @akshayamaldhure Can you please retry using `7.7.0` and see if its still a problem.
> 
> If the issue persists can you please share a sample project that can be used to reproduce the problem ?

I certainly can. Before that, may I understand how to check the test case corresponding to the invocation-numbers value from testng-failed.xml?

**Comment by krmahadevan** [comment]
I didnt quite understand the question. Can you please rephrase ?

**Comment by akshayamaldhure** [comment]
> I didnt quite understand the question. Can you please rephrase ?

TestNG generates a testng-failed.xml file if any of the tests fail. In order to retry the failed tests with that file as a reference, I use below code in my Gradle task.

```
useTestNG() {
        useDefaultListeners = true
        suites "testng-failed.xml"
    }
```
My question is: How does TestNG identify which tests are to be (re)run in this case? Is it using the `invocation-numbers` property? How does that work?

**Comment by krmahadevan** [comment]
Yes. TestNG uses the `invocation-numbers` for figuring out which of the data provider iterations need to be retried.

If you have a testcase, that looks like below

<details>
<summary>sample testcase</summary>

```java
import java.util.concurrent.atomic.AtomicInteger;
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class SampleTestClass {

  private boolean flag = true;
  private final AtomicInteger counter = new AtomicInteger(0);

  @Test(dataProvider = "dp")
  public void testMethod(int i) {
    counter.incrementAndGet();
    if (flag) {
      flag = false;
      Assert.fail("Iteration " + counter.get() + " failed");
    } else {
      flag = true;
    }
  }

  @DataProvider(name = "dp")
  public Object[][] getTestData() {
    return new Object[][]{
        {1},
        {2},
        {3},
        {4},
        {5}
    };
  }
}

```
</details>

when you run this first time, the `testng-failed.xml` will look like below

<details>
<summary>testng-failed.xml iteration 1</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Default Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="testng_playground(failed)">
    <classes>
      <class name="com.rationaleemotions.invocations.SampleTestClass">
        <methods>
          <include name="testMethod" invocation-numbers="0 2 4"/>
        </methods>
      </class> <!-- com.rationaleemotions.invocations.SampleTestClass -->
    </classes>
  </test> <!-- testng_playground(failed) -->
</suite> <!-- Failed suite [Default Suite] -->
```
</details>

Now when you use the `testng-failed.xml` contents (I personally prefer making a copy of this suite so that I know what exactly did I run) then your new `testng-failed.xml` contents would look like below

<details>
<summary>testng-failed.xml iteration 2</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Failed suite [Default Suite]]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="testng_playground(failed)(failed)">
    <classes>
      <class name="com.rationaleemotions.invocations.SampleTestClass">
        <methods>
          <include name="testMethod" invocation-numbers="0 4"/>
        </methods>
      </class> <!-- com.rationaleemotions.invocations.SampleTestClass -->
    </classes>
  </test> <!-- testng_playground(failed)(failed) -->
</suite> <!-- Failed suite [Failed suite [Default Suite]] -->
```
</details>

The invocation numbers keep changing, because the data set for which the tests is to be run is also changing for every run.

TestNG is working as designed here AFAIK.

**Comment by akshayamaldhure** [comment]
> 

Thanks a lot for sharing the functionality with examples. Now coming back to my example, I see the `invocation-numbers` value to be `9`. So I'm still not sure how to find out which exact test case it points to from my DataProvider setup. Any thoughts on how I could achieve the same? As of now, I checked all the files generated at the location where `testng-failed.xml` is generated, but I could not find this out. Is there any additional flag I could enable so that this information becomes available?

**Comment by akshayamaldhure** [comment]
> Thanks a lot for sharing the functionality with examples. Now coming back to my example, I see the `invocation-numbers` value to be `9`. So I'm still not sure how to find out which exact test case it points to from my DataProvider setup. Any thoughts on how I could achieve the same? As of now, I checked all the files generated at the location where `testng-failed.xml` is generated, but I could not find this out. Is there any additional flag I could enable so that this information becomes available?

Thanks a lot for sharing the functionality with examples. Now coming back to my example, I see the invocation-numbers value to be 9. So I'm still not sure how to find out which exact test case it points to from my DataProvider setup. Any thoughts on how I could achieve the same? As of now, I checked all the files generated at the location where testng-failed.xml is generated, but I could not find this out. Is there any additional flag I could enable so that this information becomes available?

**Comment by akshayamaldhure** [comment]
> Yes. TestNG uses the `invocation-numbers` for figuring out which of the data provider iterations need to be retried.
> 
> If you have a testcase, that looks like below
> 
> sample testcase
> ```java
> import java.util.concurrent.atomic.AtomicInteger;
> import org.testng.Assert;
> import org.testng.annotations.DataProvider;
> import org.testng.annotations.Test;
> 
> public class SampleTestClass {
> 
>   private boolean flag = true;
>   private final AtomicInteger counter = new AtomicInteger(0);
> 
>   @Test(dataProvider = "dp")
>   public void testMethod(int i) {
>     counter.incrementAndGet();
>     if (flag) {
>       flag = false;
>       Assert.fail("Iteration " + counter.get() + " failed");
>     } else {
>       flag = true;
>     }
>   }
> 
>   @DataProvider(name = "dp")
>   public Object[][] getTestData() {
>     return new Object[][]{
>         {1},
>         {2},
>         {3},
>         {4},
>         {5}
>     };
>   }
> }
> ```
> 
> when you run this first time, the `testng-failed.xml` will look like below
> 
> testng-failed.xml iteration 1
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
> <suite name="Failed suite [Default Suite]" guice-stage="DEVELOPMENT">
>   <test thread-count="5" name="testng_playground(failed)">
>     <classes>
>       <class name="com.rationaleemotions.invocations.SampleTestClass">
>         <methods>
>           <include name="testMethod" invocation-numbers="0 2 4"/>
>         </methods>
>       </class> 
>     </classes>
>   </test> 
> </suite> 
> ```
> 
> Now when you use the `testng-failed.xml` contents (I personally prefer making a copy of this suite so that I know what exactly did I run) then your new `testng-failed.xml` contents would look like below
> 
> testng-failed.xml iteration 2
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
> <suite name="Failed suite [Failed suite [Default Suite]]" guice-stage="DEVELOPMENT">
>   <test thread-count="5" name="testng_playground(failed)(failed)">
>     <classes>
>       <class name="com.rationaleemotions.invocations.SampleTestClass">
>         <methods>
>           <include name="testMethod" invocation-numbers="0 4"/>
>         </methods>
>       </class> 
>     </classes>
>   </test> 
> </suite> 
> ```
> 
> The invocation numbers keep changing, because the data set for which the tests is to be run is also changing for every run.
> 
> TestNG is working as designed here AFAIK.

Thanks a lot for sharing the functionality with examples. Now coming back to my example, I see the invocation-numbers value to be 9. So I'm still not sure how to find out which exact test case it points to from my DataProvider setup. Any thoughts on how I could achieve the same? As of now, I checked all the files generated at the location where testng-failed.xml is generated, but I could not find this out. Is there any additional flag I could enable so that this information becomes available?

**Comment by krmahadevan** [comment]
@akshayamaldhure 

> `<include name="verifySomething" invocation-numbers="9"/>`

This basically is telling you that the data provider's 10th iteration (it starts from zero) would need to be run again because it failed before. This is TRUE only when the `testng-failed.xml` gets generated the first time. If you re-run this and if this fails again, then the value would become `0` because this time the data provider was run ONLY with 1 set of data and that also failed.

> So I'm still not sure how to find out which exact test case it points to from my DataProvider setup. Any thoughts on how I could achieve the same? 

Well this is going to be a tricky one because you would need to build some custom logic. Here's one way of doing this.

1. Ensure that all the data records implement a custom interface that will help you always uniqueuely identify the record.
2. Use a data provider interceptor to filter out records.
3. build a custom reporter that will produce a file similar to `testng-failed.xml` but with an extra parameter that lists the keys that failed.


My interface

```java
public interface Identifiable {

  long id();
}
```

```java
public class Data implements Identifiable {

  private final String name;
  private final int rowNo;

  public Data(int rowNo, String name) {
    this.name = name;
    this.rowNo = rowNo;
  }

  @Override
  public long id() {
    return rowNo;
  }

  @Override
  public String toString() {
    return String.format("(%s, %d)", name, rowNo);
  }
}
```

```java
import java.util.Arrays;
import java.util.List;
import org.testng.ITestContext;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(SimpleDataProviderInterceptor.class)
public class SampleTestCase {

  @Test(dataProvider = "dp")
  public void testMethod(Data data) {
    System.err.println(data);
  }

  @DataProvider(name = "dp")
  public Object[][] getData(ITestContext context) {
    return records().stream()
        .map(each -> new Object[] {each})
        .toArray(Object[][]::new);
  }

  private static List<Data> records() {
    return Arrays.asList(new Data(10, "a"), new Data(20, "b"));
  }
}
```

```java
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;
import org.testng.IDataProviderInterceptor;
import org.testng.IDataProviderMethod;
import org.testng.ITestContext;
import org.testng.ITestNGMethod;

public class SimpleDataProviderInterceptor implements IDataProviderInterceptor {

  @Override
  public Iterator<Object[]> intercept(Iterator<Object[]> original,
      IDataProviderMethod dataProviderMethod, ITestNGMethod method, ITestContext context) {
    List<Integer> keys = keys(context);
    Stream<Object[]> stream = StreamSupport.stream(
        Spliterators.spliteratorUnknownSize(
            original,
            Spliterator.ORDERED), false);
    if (!keys.isEmpty()) {
      List<Object[]> list = stream
          .map(each -> (Data) each[0])
          .filter(each -> keys.contains((int) each.id()))
          .map(each -> new Object[]{each})
          .collect(Collectors.toList());
      if (list.isEmpty()) {
        throw new IllegalStateException("Data Provider filtering resulted in no records");
      }
      return list.iterator();
    }
    return original;
  }

  private static List<Integer> keys(ITestContext ctx) {
    String keys = Optional.ofNullable(ctx.getCurrentXmlTest().getParameter("dataprovider.keys"))
        .orElse("");
    if (keys.isEmpty()) {
      return Collections.emptyList();
    }
    return Arrays.stream(keys.split(","))
        .mapToInt(Integer::parseInt)
        .boxed()
        .collect(Collectors.toList());
  }
}

A testng suite xml file that you can generate should be like below

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="my_suite">
  <test thread-count="5" name="my_test" verbose="2">
    <parameter name="dataprovider.keys" value="10,20"/>
    <classes>
      <class name="com.rationaleemotions.issue2853.SampleTestCase"/>
    </classes>
  </test> <!-- my_test -->
</suite> <!-- my_suite -->

```
```

**Comment by juherr** [comment]
@krmahadevan 

> If you re-run this and if this fails again, then the value would become 0 because this time the data provider was run ONLY with 1 set of data and that also failed.

It sounds like an issue because the initial index is lost, right?

**Comment by krmahadevan** [comment]
@juherr We are talking about across executions ( which means the state needs to be saved externally) since for every execution the size of the data set varies and so the invocation count changes as well. 

If testNG can determine the size of the data provider in advance then maybe it would be able to pin itself against the exact invocation count. But since we also have a lazy loading data provider i am not sure how we would be able to determine the test data size in advance.

**Comment by akshayamaldhure** [comment]
> Well this is going to be a tricky one because you would need to build some custom logic.
@krmahadevan Does it also mean the retry attempt with such a custom generated `testng-failed.xml` file as an input will not work since it does not have `invocation-numbers` (asking this since the sample generated testng suite xml does not have `invocation-numbers`)? If that's the case, it would be really good if there's some default functionality in TestNG that exposes extra details (like test name, since that could be generated based on the DataProvider records by having the test class implement the ITest interface). What do you think?

**Comment by krmahadevan** [comment]
> Does it also mean the retry attempt with such a custom generated testng-failed.xml file as an input will not work since it does not have invocation-numbers (asking this since the sample generated testng suite xml does not have invocation-numbers)?

That was a file that I created manually for demonstration purposes. If you are generating the TestNG suite xml file wherein you would like to build the intelligence of a retry of the failed invocation counts, then you would need to ensure that you include these values as well. What I shared is not meant to be used as a "use as is solution" but something that you would need to work on and tweak. So please try it out and then raise any specific issues that you may have encountered.

If this has answered your question, please feel free to close this issue.

**Comment by akshayamaldhure** [comment]
Thanks @krmahadevan, I'm closing this issue here. I'm going to try to tweak your solution in order to account for the inclusion of `invocation-numbers` as well. I'll get back if I face any issues. Thanks a lot once again!

**Comment by akshayamaldhure** [comment]
@krmahadevan A question on below line.
```
String keys = Optional.ofNullable(ctx.getCurrentXmlTest().getParameter("dataprovider.keys"))
        .orElse("");
```
How is this supposed to work? Which code populates this parameter `dataprovider.keys`?

**Comment by krmahadevan** [comment]
> How is this supposed to work? Which code populates this parameter dataprovider.keys?

Your custom implementation that generates the testng suite xml file for retries needs to ensure that it does the following:

* It captures the keys and includes a `<test>` level parameter for the class in question that needs to be retried for failed data sets (If there are more than 1 classes, then you may need to consider either having one class per `<test>` or change your listener so that it is capable of extracting out parameters at the class level.
* It includes the invocation count tag (This has no use though because your logic no longer depends on this)

**Comment by akshayamaldhure** [comment]
> It captures the keys and includes a <test> level parameter for the class in question that needs to be retried for failed data sets (If there are more than 1 classes, then you may need to consider either having one class per <test> or change your listener so that it is capable of extracting out parameters at the class level.
@krmahadevan But I do not trigger my tests with suite xml approach. I'm triggering it via a custom Gradle task as described here https://github.com/cbeust/testng/issues/2853#issuecomment-1343919169. Is it possible to ensure what you mentioned with this approach?

**Comment by krmahadevan** [comment]
>  I'm triggering it via a custom Gradle task as described

Irrespective of whether you used a suite file or not, its always going to be present. That is how TestNG internally works. So you need to add a Reporting listener that can generate this custom suite file if there were failures in data provider iterations and then instead of referring to the testng-failed.xml you would use the suite file that your IReporter implementation generated for you.

**Comment by krmahadevan** [comment]
> Just to be clear, this file is nothing but testng-failed.xml only, right?

No its not. If it were the testng-failed.xml then you are going to be ending up with depending on invocation-numbers attribute which is NOT working for your usecase. It would be the suite file that your reporter generates that should be used when there are failures in data driven tests and when you need to run only the failed iterations but in a reliable way.

**Comment by akshayamaldhure** [comment]
> It would be the suite file that your reporter generates

Sorry, I think this part isn't clear to me. How to identify this file? What is it called?

**Comment by krmahadevan** [comment]
> Sorry, I think this part isn't clear to me. How to identify this file? What is it called?

It would be your code. So you can name it whatever you want. Whatever you name it, is what you would be using in your custom gradle task. That's the only parity you would need to maintain. All of the existing TestNG reporters work on the same philosophy. You can refer to any one of them for reference for your logic.

**Comment by akshayamaldhure** [comment]
> It would be your code. 

Isn't that supposed to be the code you shared here https://github.com/cbeust/testng/issues/2853#issuecomment-1345088282? In other words, do you mean the point 3 in that comment isn't taken care of in your code sample?

**Comment by akshayamaldhure** [comment]
Also, for the original query "How to check the test case corresponding to the invocation-numbers value from testng-failed.xml?", I'm wondering if there's a simpler way to log all the test records corresponding to all the invocation-numbers. Since I see that the test failed is not the one retried, I'd like to check if the testng-failed.xml has correct invocation-numbers in the first place.

**Comment by krmahadevan** [comment]
> do you mean the point 3 in that comment isn't taken care of in your code sample?

Yes. 

>  I'm wondering if there's a simpler way to log all the test records corresponding to all the invocation-numbers. Since I see that the test failed is not the one retried, I'd like to check if the testng-failed.xml has correct invocation-numbers in the first place.

There does not exist anything today. Which was why I shared a sample that shows you how to do it.
