### ISSUE TITLE
XmlTest index is not set for test suites invoked with YAML

### ISSUE THREAD

**Issue by sbaranov-parasoft** [cbeust/testng#2857]
### TestNG Version
> 7.7

### Expected behavior
ITestResult.getTestClass().getXmlTest().getIndex() should return valid test indexes when a TestNG class is invoked from YAML test suite.

### Actual behavior
ITestResult.getTestClass().getXmlTest().getIndex() always returns 0. 
When the same test class is invoked from an XML suite, the XmlTest.getIndex() returns expected values.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
To reproduce run the following class:

```
public class TestNGTest {
    @Parameters("input")
    @Test
    public void testSomething(String input) throws Exception {
        // doSomething
    }
    @AfterMethod
    public void afterMethod(ITestResult result) {
        XmlTest xmlTest = result.getTestClass().getXmlTest();
        System.out.println("afterMethod test=" + xmlTest.getName() + ", index=" + xmlTest.getIndex());
    }
}
```
with the YAML test descriptor:
```
name: SuiteYaml
tests:
  - name: TestYaml-1
    parameters: { input: yaml_1 }
    classes:
      - test.TestNGTest
  - name: TestYaml-2
    parameters: { input: yaml_2 }
    classes:
      - test.TestNGTest
```
observe console output with '0' test indexes:
```
afterMethod test=TestYaml-1, index=0
afterMethod test=TestYaml-2, index=0
```
Run the same class with an equivalent XML test descriptor:
```
<suite name="SuiteXml">
  <test name="TestXml-1">
    <parameter name="input" value="xml_1"/>
    <classes>
      <class name="test.TestNGTest"/>
    </classes>
  </test>
  <test name="TestXml-2">
    <parameter name="input" value="xml_2"/>
    <classes>
      <class name="test.TestNGTest"/>
    </classes>
  </test>
</suite>
```
observe console output with correct test indexes:
```
afterMethod test=TestXml-1, index=0
afterMethod test=TestXml-2, index=1
```
Presumably the following code section in the `parse` method of `org.testng.internal.Yaml` should be setting the XmlTest indexes:
```
// Adjust XmlTest parents and indices
for (XmlTest t : result.getTests()) {
    t.setSuite(result);
    int index = 0;
    for (XmlClass c : t.getClasses()) {
        c.setIndex(index++);
    }
}
```

**Comment by juherr** [comment]
Hi,

Thanks for the report.

The fix should be easy. Would you like to try?

**Comment by sbaranov-parasoft** [comment]
Yes, sure, I expect I'll create a pull request in the next few days.
