### ISSUE TITLE
Skipping irrelevant test methods

### ISSUE THREAD

**Issue by bzaczynski** [cbeust/testng#286]
**Description**

Not handled exception or a failed assertion inside a method tagged with `@BeforeMethod` annotation results in all subsequent test methods within the same class being skipped. That is expected and reasonable behaviour. However, when such a class extends a base class with at least one method annotated with `@BeforeClass` then no other test class extending base class will run.

Note: replacing `@BeforeClass` with `@BeforeTest` fixes the problem but cannot be applied under all circumstances since it alters the execution flow.

**Expected**

<pre>BaseClass::@BeforeClass
A::@BeforeMethod (fails)
BaseClass::@BeforeClass
B::@Test</pre>

**Observed**

<pre>BaseClass::@BeforeClass
A::@BeforeMethod (fails and skips all other tests)</pre>

**Workarounds**

There are two workarounds known to me:
1. Explicitly catch exceptions inside `@BeforeMethod` methods so that TestNG won't skip anything.
2. Rearrange tests in `testng.xml` so that the one with `@BeforeMethod` runs last. Even if it's skipped all other tests already had a chance to run.

**Environment setup**
- Windows 7
- JDK 1.7.0_07
- Maven 3.0.4
- TestNG 6.8

I'd like to know whether it's intentional or not. Please find a sample Maven project attached to reproduce the issue.
https://gist.github.com/3839822

**Comment by juherr** [comment]
Should be fixed with #471
