### ISSUE TITLE
Failure in @BeforeTest forces remaining tests in the class to be skipped

### ISSUE THREAD

**Issue by OlegKuzovkov** [cbeust/testng#2861]
When we receive a failure in the @Before/AfterMethod all test cases in the same class will be skipped. We isolate some complex preconditions there and don't expect tests to be skipped if something is wrong for a single failure. To skip all tests if precondition fails we use @Before/AfterClass methods.
### TestNG Version
7.7.0

### Expected behavior
@Before/AfterMethod should be executed for every test in the class and single failure should not affect the execution for others.

### Actual behavior
All remaining tests should be executed irrespective of the previous test/setups failures:
![image](https://user-images.githubusercontent.com/9959366/210390789-c00a8324-a447-413a-adc2-152bba80f249.png)

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```
public class TestFail {
    private int i=0;
    @BeforeMethod
    public void beforeMethod() {
        i++;
        if (i ==1) {
            throw new RuntimeException("failedWithException");
        }
        assert true;
    }

    @Test
    public void testIt() {
        assert true;
    }

    @Test
    public void testIt2() {
        assert true;
    }
}
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@OlegKuzovkov - Have you tried setting `configfailurepolicy="continue"` in your suite xml file at the `<suite>` level? That should ensure that the `Before|After` gets executed for the next method even though they already failed earlier.

**Comment by krmahadevan** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/909773/210392777-b00f555c-7a32-4242-95ab-4588cf488fff.png">

**Comment by OlegKuzovkov** [comment]
@krmahadevan I am not running those tests as part of the XML test suite. I need them to work from the IDE and using the `-Dtest=<class_name>`. With that option set on the XML level everything works fine. This configfailurepolicy  requires more flexibility I think.

Another question: I could not find how to change the default behavior of configfailurepolicy to `continue` from `skip` as part of the framework configuration, not on a per XML suite basis. Could you please advice how to do that? Can I also define the behavior on a per test class level? That would be ideal. Maybe additional attribute should be added to the @Before/After method.

**Comment by krmahadevan** [comment]
> Can I also define the behavior on a per test class level? That would be ideal. Maybe additional attribute should be added to the @Before/After method.

@OlegKuzovkov - Ok, I don't think we can currently do this within TestNG and would need a change. Just to ensure that we track this specific ask, I went ahead and created an issue for this https://github.com/cbeust/testng/issues/2862

Please help enrich it with the expectations if you feel something has been missed out.
