### ISSUE TITLE
[Query] How can we share data between multiple data provider threads?

### ISSUE THREAD

**Issue by raunakagrawal47** [cbeust/testng#2863]
I am using an excel data provider and I have around 150 rows of data. I have a single @Test method which needs to run the test cases. I have enabled the parallel flag in the data provider class and also set the data provider-thread-count in the `<suite /> tag` in the .xml file. 

My question is: Let's say there is a global API that needs to be called for the test cases and if one test case has called the API, others can use it and others don't need to call the API again. This global API contains some data to be used from the excel file and then call the global API.

Should I share the state among the runs using a static variable in Java? Or is there any better way to achieve this in testNG?

@krmahadevan @juherr  can you please help with this?

**Comment by krmahadevan** [comment]
@raunakagrawal47 - We would like to confine the issues tracker to actually tracking issues/feature requests. 
Please post your query on the [TestNG users forum](https://groups.google.com/g/testng-users)
