### ISSUE TITLE
Allow for Specifying Group Names with Annotations

### ISSUE THREAD

**Issue by belugabehr** [cbeust/testng#2873]
# Feature Request

Instead of specifying "groups" as Strings in the TestNG annotations (e.g., `@BeforeGroups`) allow one to create an annotation specific to each group and apply it.  An example of this comes from [Google Guice](https://github.com/google/guice/wiki/BindingAnnotations).

```java
package example.test;

import static java.lang.annotation.ElementType.PARAMETER;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Target;
import java.lang.annotation.Retention;
import org.testng.annotations.GroupingAnnotation;


@GroupingAnnotation
@Target({ FIELD, PARAMETER, METHOD })
@Retention(RUNTIME)
public @interface MyTestGroup1 {}

@GroupingAnnotation
@Target({ FIELD, PARAMETER, METHOD })
@Retention(RUNTIME)
public @interface MyTestGroup2 {}
```

```java
public class MyTest {

    @BeforeGroups
    @MyTestGroup1
    @MyTestGroup2
    public void register() {
        ...
    }

    @Test
    @MyTestGroup1
    public void myTest1() {
       ...
    }

    @Test
    @MyTestGroup2
    public void myTest2() {
       ...
    }

}
```

**Comment by juherr** [comment]
You can do it by yourself by implementing an  IAnnotationTransformer https://testng.org/doc/documentation-main.html#annotationtransformers

For all beforegroup annotation, check if you find your custom annotations, convert them into strings and set the values into beforegroup.

**Comment by belugabehr** [comment]
Thanks @juherr for the feedback.  Would be great to have included out-of-the-box.

**Comment by juherr** [comment]
It won't as it could be done by 3rd party.

**Comment by krmahadevan** [comment]
@belugabehr - The reason why we don't want this to be out of the box, because the permutations and combinations are way too many and it still may not solve all of the end-user usecases.

Marking this as `Question answered` and closing it out.
