### ISSUE TITLE
TestNG(7.7.1) test cases are failing with openjdk8 version.

### ISSUE THREAD

**Issue by sevanthi-suvarna** [cbeust/testng#2883]
After upgrading to TestNG 7.7.1, TestNG test cases are failing with following error.
"cannot access org.testng.Assert
bad class file: /.m2/repository/org/testng/testng/7.7.0/testng-7.7.0.jar(org/testng/Assert.class)
class file has wrong version 55.0, should be 52.0
Please remove or make sure it appears in the correct subdirectory of the classpath."

When we run the test cases (mvn test) with openJDK8, it fails with above error.

We didn't  see this exception with TestNG 7.5.

### TestNG Version
7.7.1

### Expected behavior
The maven test should run the TestNG test cases with openJDK8.

### Actual behavior
The maven test fails with compilation error. 

### Is the issue reproducible on runner?
maven test

**Comment by krmahadevan** [comment]
7.5 is the last version that runs on JDK8. 

To use `7.7.1` you need to be using JDK11.

**Comment by sevanthi-suvarna** [comment]
Thanks for information..

We had to upgrade to 7.7.1 because of security vulnerabilities.

Do we have any plan to support TestNG7.7.1 with jdk8.

**Comment by juherr** [comment]
We won't backport changes on old jdk. But testng is oss project : you are free to fork and propose your own taste if you want.

Otherwise, upgrade your jdk: java8 is 10 years old.
