### ISSUE TITLE
How to refer to the Webdriver object in selenium without making it static to take screenshot through Testng listeners

### ISSUE THREAD

**Issue by kherath4139** [cbeust/testng#2905]
Hi Im stuck in a situation where I have declared my driver object in the test class and I have some wrappers developed in another class , all the respective variables are **not static** including the driver object , so now I want to take a screenshot on failure using testng listerners **(I have created a custom listener class implementing to ITestListener)** and when I refer to the driver object it throws a null exception probably due to driver not been static , how can I still achieve to take a screenshot without making the driver static , any testng related work around will also be helpful

this is the code line in my custom listenerclass

```java
onTestFailure(){
    bufferImage = driver.getScreenshot(); //throws null , getScreesnshot comes from my wrapper class
}
```

**Comment by krmahadevan** [comment]
We would like to confine using the github page to track bugs/feature requests. Please feel free to post your question to the users forum https://groups.google.com/g/testng-users
