### ISSUE TITLE
OutOfMemoryError (heap space) generating testng report

### ISSUE THREAD

**Issue by mondrejko** [cbeust/testng#291]
Seeing the following during our test run (about 4100 tests). The issue does not occur consistently, but does occur regularly. Increasing the max heap size does not address issue (have gone from 1g to 2g to 4g with same failure).  I was able to capture a heap dump; however, where should this be submitted?

   [testng] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
   [testng]     at java.util.Arrays.copyOf(Arrays.java:2882)
   [testng]     at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
   [testng]     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:390)
   [testng]     at java.lang.StringBuffer.append(StringBuffer.java:224)
   [testng]     at java.lang.StringBuffer.append(StringBuffer.java:284)
   [testng]     at java.util.regex.Matcher.appendReplacement(Matcher.java:746)
   [testng]     at java.util.regex.Matcher.replaceAll(Matcher.java:813)
   [testng]     at org.testng.reporters.XMLStringBuffer.toXML(XMLStringBuffer.java:327)
   [testng]     at org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:66)
   [testng]     at org.testng.TestNG.generateReports(TestNG.java:1088)
   [testng]     at org.testng.TestNG.run(TestNG.java:1047)
   [testng]     at org.testng.TestNG.privateMain(TestNG.java:1337)
   [testng]     at org.testng.TestNG.main(TestNG.java:1306)

**Comment by DRC-LGundeboina** [comment]
Hi,

I am also getting the OOM while preparing HTML Report (TestNG v6.9.10). But its kind of intermittent.
