### ISSUE TITLE
Allow assertion methods to be run after the test

### ISSUE THREAD

**Issue by binhle** [cbeust/testng#294]
Currently, if an assertion fails, the test fails right away. If there are multiple assertions within a test, then after the first assertion fails, the rest of the assertions are not run.

The new Assertion class resolves this a bit, allowing for multiple assertions to be collected, with the final assertion done at the end of the test. The problem with this is that this final assertion needs to be done at the end of every test method.

For example, if the test class has the following 2 test methods and corresponding assertions (pseudocode), then you can see that the "assertion.doFinalAssert()" operation is being done explicitly at the end of each test.

@Test
public void test1() {
    Assertion assertion = new AssertionImpl();
    assertion.assertSomething();
    assertion.assertSomethingElse();
    assertion.doFinalAssert();
}

@Test
public void test2() {
    Assertion assertion = new AssertionImpl();
    assertion.assertSomething();
    assertion.doFinalAssert();
}

It would be nice if this "assert.doFinalAssert()" is in a separate method that will be called automatically right after the @Test is completed. So the above code can result in something like this.

public void SomeTest {

```
private Assertion assertion;

@BeforeMethod
public void setup() {
    assertion = new AssertionImpl();
}

@Test
public void test1() {
    assertion.assertSomething();
    assertion.assertSomethingElse();
}

@Test
public void test2() {
    assertion.assertSomething();
}

@AfterTestMethod {
    assertion.doFinalAssert();
}
```

}

Notice the introduction of the new @AfterTestMethod annotation. If such an annotation is added, then I think it's better to re-purpose @AfterTest to @AfterTests and @AfterTest will then be this "@AfterTestMethod". If that is not possible, then @AfterTestMethod to me makes sense.

This @AfterTestMethod is different than @AfterMethod because if the assertion is placed in the @AfterMethod, then it currently results in a configuration failure instead of a test failure. The point of this is to run the method(s) with @AfterTestMethod right after the test, but the result will be part of the test.

**Comment by krmahadevan** [comment]
This can be solved using `SoftAssert` and leveraging `IHookable` implementation. Here's a sample 

```java
import org.testng.IHookCallBack;
import org.testng.IHookable;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

public class SomeTest implements IHookable {
    private static final String ASSERTION = "assertion";

    @Override
    public void run(IHookCallBack callBack, ITestResult testResult) {
        SoftAssert softAssert = new SoftAssert();
        testResult.setAttribute(ASSERTION, softAssert);
        callBack.runTestMethod(testResult);
        softAssert = (SoftAssert) testResult.getAttribute(ASSERTION);
        softAssert.assertAll();
    }

    @Test
    public void firstTestMethod() {
        SoftAssert asserts = getAssert();
        asserts.assertEquals(1, 2, "Number equality test");
        asserts.assertTrue(true, "boolean test");
        asserts.assertNull("", "null check");
    }

    @Test
    public void secondTestMethod() {
        SoftAssert asserts = getAssert();
        asserts.assertTrue(false, "boolean test");
        asserts.assertEquals(1, 1, "Number equality test");
        asserts.assertNotNull("", "null check");
    }

    private SoftAssert getAssert() {
        ITestResult result = Reporter.getCurrentTestResult();
        return (SoftAssert) result.getAttribute(ASSERTION);
    }
}
```
