### ISSUE TITLE
attribute in testng-failed.xml doesn't match case in DTD

### ISSUE THREAD

**Issue by tdrury** [cbeust/testng#301]
After importing maven projects into eclipse, eclipse is flagging the target/surefire-reports/.../testng-failed.xml file as invalid.  The file starts as:

`<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">`
`<suite thread-count="5" skipfailedinvocationCounts="false" verbose="0" name="Failed suite [Command line suite]" junit="false" annotations="JDK">`
...

but the testng-1.0.dtd says "skipfailedinvocationcounts" is all lower case.

Aside from the strangeness of eclipse validating stuff in /target, I'm fairly sure this is a bug as XML attributes are supposed to be case-sensitive.

**Comment by krmahadevan** [comment]
Closing this issue based on the above comment. Please comment if this is still a problem.
