### ISSUE TITLE
TestNG does not provide sufficient diagnostics when a test class throws an exception in instantiation

### ISSUE THREAD

**Issue by briangoetz** [cbeust/testng#303]
If the static initializer or constructor for a test throws an exception, all the user sees is an error message: 

[testng] Cannot instantiate class com.foo.FooTest
[testng] The tests failed.

The stack trace would be helpful.  (Same problem when a @Factory method throws an exception.)

**Comment by krmahadevan** [comment]
Closing this issue based on the explanation provided in https://github.com/cbeust/testng/issues/303#issuecomment-10921158
