### ISSUE TITLE
Public variables that are initialized in @BeforeSuite are being deallocated during the test run

### ISSUE THREAD

**Issue by DeanMad** [cbeust/testng#3069]
### TestNG Version
7.9.0

### Expected behavior
Public variables that are initialized in @BeforeSuite are being deallocated during the test run

### Actual behavior
The variables are being deallocated after the @BeforeSuite method,
rather than still being allocated and exists during the test in the @BeforeClass method for example.

### Is the issue reproducible on runner?
I tried it on maven project on intellij

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

**Comment by krmahadevan** [comment]
@DeanMad - Please share a sample test that can be used to reproduce the problem.

**Comment by ashwithpoojary98** [comment]
Even though I am facing this issue, but I'm not sure if it's caused by an IntelliJ plugin.

org.testng.TestNGException:
Native Injection is NOT supported for @BeforeSuite annotated beforeSuite.
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection

**Comment by krmahadevan** [comment]
@ashwithpoojary98 - Please get rid of `ITestContext` as a parameter in your code and you should be fine.

Read more at https://testng.org/#_dependency_injection

**Comment by devkirr** [comment]
What could I do now if I was using ITestContext casted as TestRunner to set output directory?

```java
@BeforeSuite()
    public void init(ITestContext ctx) throws IOException {
        TestRunner runner = (TestRunner) ctx;
        runner.setOutputDirectory("output");
        runner.setTestName("Suite1");
        /* .... */
    }
```

I also get all groups used inside the suite to perform time consuming operation once for each group...

```java
@BeforeSuite()
    public void init(ITestContext ctx) throws IOException {
        /* .... */
        Set<String> groups = ctx.getSuite().getMethodsByGroups().keySet();
    }
```

I could probably use beforeGroup for the last use case right?

**Comment by krmahadevan** [comment]
> what could I do now if I was using ITestContext casted as TestRunner to set output directory?

Why would you be doing this? Can you please help me understand your usecase? It seems to me that you are looking at building some sort of customization that would ensure that every `<test>` reports are moved to a separate folder.

If that's the case, then why not try to build an implementation of `org.testng.ITestListener#onStart` wherein you basically move the existing reports that are available in the output folder to a different path and let the rest of the things work the way they are?

> I also get all groups used inside the suite to perform time consuming operation once for each group...

Its totally upto you as to where you would like to process this, but maybe BeforeGroups could be a good fit. But I don't know on the top of my head if there are any caveats that are to be considered.

For questions, please feel free to use the TestNG users mailing list at https://groups.google.com/g/testng-users

**Comment by devkirr** [comment]
> Why would you be doing this? Can you please help me understand your usecase? It seems to me that you are looking at building some sort of customization that would ensure that every <test> reports are moved to a separate folder.

Exactly, I want to ensure at the beginning of my suite that my test reporter use the output directory provided. 
I'll look into the ITestSuiteListener#OnStart maybe as you suggested thanks!
