### ISSUE TITLE
@BeforeTest/@BeforeSuite in superclass only invoked on first instance that inherits from it. 

### ISSUE THREAD

**Issue by jabbrwcky** [cbeust/testng#313]
I noticed that a @BeforeTest/@BeforeSuite method defined in as superclass of a test will only be executed once on the first instance of the inheriting classes.
As the documentation on the test annotations is a little sparse sometimes, it is not clear to me if this should be considered as bug or as feature.

If the @BeforeTest/@BeforeSuite method is executed on every inheriting class it might lose some of its semantics and act like a method annotated with @BeforeClass, which might not be the perfect solution in my eyes.

The other way would be to clearly document this not immediately obvious behavior and use the test context (ITestContext) to provide Test-scoped configuration and instance data to running tests.
 This could be a possible solution:

``` java
public abstract class AbstractTestBase {

    /** Property Foo is set once per Suite */
    protected String foo;

    /** Property Foo is set once per Test */
    protected String bar;

    /**
     * Store foo in context.
     *
     * @param context test context for storing test conf data
     */
    @BeforeSuite
    public void beforeSuite(ITestContext context) {
        out.println("@BeforeSuite called on " + getClass().getName());
        context.setAttribute("foo", "I was set in @BeforeSuite");
    }


    /**
     * Store bar in context.
     *
     * @param context test context for storing test conf data
     */
    @BeforeTest(alwaysRun = true)
    public void beforeTest(ITestContext context) {
        out.println("@BeforeTest called on " + getClass().getName());
        context.setAttribute("bar", "I was set in @BeforeTest");
    }

    /**
     * Fetch foo and bar from context per instance.
     *
     * @param context test context to retrieve conf data from.
     */
    @BeforeClass
    public void beforeClass(ITestContext context) {
        out.println("@BeforeClass called on " + getClass().getName());
        foo = (String) context.getAttribute("foo");
        bar = (String) context.getAttribute("bar");
    }
}
```

A small project demonstrating the behavior and my current solution is here: https://github.com/jabbrwcky/testng-annotation-demo

/Jens

**Comment by DurgaManickam** [comment]
Can anyone please say me the exact difference between @Beforesuite and @BeforeTest? Explain when and where to use each of the one.

**Comment by juherr** [comment]
@DurgaManickam Please, could you ask it on StackOverflow or the mailing list first?

**Comment by krmahadevan** [comment]
@juherr - I this we can close this issue. WDYT ?

**Comment by juherr** [comment]
It works as expected: a before suite method is only called once by suite, even if it is located in a superclass.

**Comment by abdulrazak-mumms** [comment]
any conclusion fix for this issue  ?
{code} java.lang.IllegalStateException: No TestRunnerAdaptor found, @BeforeSuite has not been called
{code}

**Comment by juherr** [comment]
@abdulrazak-mumms Could you open a new issue and include a sample which reproduces the issue?
