### ISSUE TITLE
Truncated stack traces in HTML report

### ISSUE THREAD

**Issue by lsuk** [cbeust/testng#315]
When a test fails and a stack trace is displayed in the test results pane of the html reports the content is horizontally truncated to the window width so it is not possible to see the full error message. This is due to the css "overflow: hidden" property set on the wrapper container.

![screenshot_73](https://f.cloud.github.com/assets/1218862/21553/7d553c26-49bb-11e2-9676-1fc2736edafe.gif)

**Comment by krmahadevan** [comment]
Closing this based on the above comment.
