### ISSUE TITLE
Add checks compatibility of annotations and parameters types in dependency injection.

### ISSUE THREAD

**Issue by VladRassokhin** [cbeust/testng#320]
I have found undefined behavior case: (based on documentation)
- Using `@BeforeSuite` or `@AfterSuite` with `XmlTest` or `ITestContext`: 
  When more than one test in suite currently we have undefined behavior: no guaranties what exactly `XmlTest` or `ITestContext`(`TestRunner`) will be passed as parameter.

Currently  `testng.internal.Parameters#checkParameterTypes` does not checks what kind of annotation method have. So without reading documentation there may be great bugs in someone's code :)
It would be nice to improve documentation and add checks into source code.

**Comment by krmahadevan** [comment]
This is currently documented in https://github.com/cbeust/testng/wiki/Allowed-parameters-injection-in-methods
