### ISSUE TITLE
Allow injection of ISuite into @Before|@After Suite|Test|Class|Method, @Test, @DataProvider etc.

### ISSUE THREAD

**Issue by VladRassokhin** [cbeust/testng#321]
It would be nice to set ISuite attributes from @BeforeSuite method, and then use it from other methods.

**Comment by krmahadevan** [comment]
If one needs to be altering a suite `<suite>` (or) a `<test>` then one needs to be leveraging `org.testng.IAlterSuiteListener`

TestNG already injects a `ITestContext` object into a `@BeforeSuite` method. For a full list, please refer [here](https://github.com/cbeust/testng/wiki/Allowed-parameters-injection-in-methods)

Here's a sample

```java
@BeforeSuite
public void beforeSuite(ITestContext ctx) {
    XmlSuite xmlSuite = ctx.getCurrentXmlTest().getSuite();
    ISuite isuite = ctx.getSuite();
}
```
