### ISSUE TITLE
Issue with @AfterSuite

### ISSUE THREAD

**Issue by nishanthjm** [cbeust/testng#324]
Is there any extra code that runs when we run our group with mvn test -Dgroups? 

we have injected a variable 
@inject var variable

this variable returns null after my all test passes and onFinish executes.In our base class I am checking if the variable is null in @AfterSuite and it returns null. this is not same when I run test using 
mvn test -Dtest or if the after suite is changed to afterClass. Is there  any clean up that is happening and variable is initialized to null after onFinish executes?

**Comment by krmahadevan** [comment]
This issue is incomplete. When groups are involved and if a configuration method is to be executed all the time, then the attribute `alwaysRun=true` is to be set. If this is still an issue, please re-open and include a sample that can be used to reproduce the problem.
