### ISSUE TITLE
Distributed Test execution remotely

### ISSUE THREAD

**Issue by manijshrestha** [cbeust/testng#340]
This is not really an issue but a feature request. One thing I see is that testng invokes the test locally. Depending on developers machine the performance of test execution could be different. I am wondering if we can actually send the test remotely to say selenium nodes or any other remote nodes on the cloud to execute so that, regardless of developers machine config, test would run fast on remote machine?

**Comment by krmahadevan** [comment]
As @VladRassokhin pointed out, this is something that can be easily achieved using a CI tool such as Jenkins. Closing this off.
