### ISSUE TITLE
If a test method is dependent on method with expectedExceptions, then it is skipped

### ISSUE THREAD

**Issue by davidely** [cbeust/testng#342]
We're in the process of upgrading from TestNG 5.x to 6.7.  One issue that we've run into is that if a test method is dependent on another test method that has expectedExceptions, then even though the method does throw the expected exceptions, then depending method will not be called.  The below test case demonstrates this.  The verifyDependsOnThrowsRTECalled method will fail because dependsOnThrowsRTECalled is false.

``` java

import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.Test;

@Test
public class TestDependentOnExpectedExceptionMethod {

  private boolean dependsOnThrowsRTECalled = false;

  @Test(expectedExceptions = RuntimeException.class)
  public void throwsRTE() {
    throw new RuntimeException();
  }

  @Test(dependsOnMethods = "throwsRTE")
  public void dependsOnThrowsRTE() {
    // This method is never called even though throwsRTE() passes. 
    dependsOnThrowsRTECalled = true;
  }

  @AfterClass
  public void verifyDependsOnThrowsRTECalled() {
    Assert.assertTrue(dependsOnThrowsRTECalled);
  }
}

'''
```

**Comment by krmahadevan** [comment]
Retried the sample using TestNG 6.12. Cannot reproduce the issue.
