### ISSUE TITLE
Single SuiteListener registered twice, causing onStart(ISuite) to be called twice

### ISSUE THREAD

**Issue by davidely** [cbeust/testng#343]
We have a TestListener with the following signature:

public class TestListener extends TestListenerAdapter implements IReporter, ISuiteListener

We noticed that our onStart(ISuite) method is being called twice.  After digging into it a bit, we found that SuiteRunner.m_listeners contains the same instance of TestListener twice.  I assume that this is because a single class is multiple types of listeners.

We have a simple work around for this issue, so it's not critical.

**Comment by juherr** [comment]
Should be closed by #552
