### ISSUE TITLE
PDE?

### ISSUE THREAD

**Issue by dcalacci** [cbeust/testng#351]
Apologies in advance for putting this up as an issue, but there is such a dearth of resources around regarding this topic that I thought I'd get a quick and straightforward answer here.

Is there any support for PDE tests in testng? Are there any features that anyone knows of that we could use to make testing an eclipse RCP application easier?

thanks.

**Comment by krmahadevan** [comment]
@dcalacci - Since I am not aware of what PDE tests are, or what is the context here, it would be good if you could please help add a bit more context.

**Comment by missedone** [comment]
I read the PR https://github.com/cbeust/testng-eclipse/pull/82 is supposed to be for this case, but need to wait for @piotrtomiak resolve the conflicts.

**Comment by krmahadevan** [comment]
@missedone - Nick in that case, can we have an issue logged in the https://github.com/cbeust/testng-eclipse project and have this one closed out ? [ since the changes seem to be pertaining to the plugin ]

**Comment by missedone** [comment]
Yes, old close this one. Thx

**Comment by krmahadevan** [comment]
@dcalacci - I am closing off this issue. There's a PR that is tracking something around these lines https://github.com/cbeust/testng-eclipse/pull/82

If you would like, please go ahead and file a new bug under https://github.com/cbeust/testng-eclipse project.
