### ISSUE TITLE
Listener for XmlTest test start and stop

### ISSUE THREAD

**Issue by const** [cbeust/testng#356]
There are methods @BeforeTest/@AfterTest, but there are no corresponding listeners. 

I have planned to create and dispose a context for all methods in the specific test of the suite using such listener depending on parameters declared in the test.

The listener should have an access to XmlTest and it should be executed in the same thread, if the corresponding test methods are not run in the parallel.

**Comment by juherr** [comment]
In fact, `ITestListener` already exists for @Before/AfterTest usage.
