### ISSUE TITLE
Validating TestNG options from listeners

### ISSUE THREAD

**Issue by const** [cbeust/testng#357]
Our integration tests should be run in parallel, because they depend on certain events happen on the server side, and such events act as barrier for the tests.

For that purpose, we have created a listener that validates and adjusts options used to run TestNG (particularly getSuiteThreadPoolSize()). However, we currently using a deprecated API to access TestNG instance (TestNG.getDefault()).

We need to perform this check at IExecutionListener.onExecutionStart(). So it might be a good idea to pass and instance of TestNG to this listener (possibly abstracted by some interface).

This is not show stopper, but we are worrying about loosing this functionality in the future. Currently it allows us more quickly diagnose and auto-correct the configuration problems when running integration tests.

**Comment by krmahadevan** [comment]
As of TestNG v6.12 this can be easily done by building an implementation of the TestNG listener `org.testng.IAlterSuiteListener`. Through this listener TestNG exposes the actual underlying set of suites which can be used to altered to suite ones needs. This listener is invoked before TestNG starts execution and should be the right place to plug in tweaks required.
