### ISSUE TITLE
Access to XmlSuite and ISuite before execution starts

### ISSUE THREAD

**Issue by const** [cbeust/testng#359]
Our integration tests should be run in parallel, because they depend on certain events happen on the server side in certain sequence, and such events act as barrier for the tests.

For that purpose we need to count at least test suites at the moment of IExecutionListener.onExecutionStart(). This is needed to ensure that all test scenarios either finished or reached the barrier point.

However there is no public API to access the list of test suites before execution start. We currently accessing TestNG.getDefault().m_suites using reflection with setAccessible(). That solves our problem for now, but this obviously is not a good solution to the problem.

We would like to see some public API to do this, for example IReporter.generateReport(...) provide needed information, but it is provided after test execution. We need it before test execution starts. 

The previously reported feature request is related to this https://github.com/cbeust/testng/issues/357

**Comment by krmahadevan** [comment]
As of TestNG v6.12 this can be easily done by building an implementation of the TestNG listener `org.testng.IAlterSuiteListener`. Through this listener TestNG exposes the actual underlying set of suites which can be used to altered to suite ones needs. This listener is invoked before TestNG starts execution and should be the right place to plug in tweaks required.
