### ISSUE TITLE
TestResult will not be changed in the sub thread

### ISSUE THREAD

**Issue by wutingbupt** [cbeust/testng#360]
Hi,

Find a tricky issue recently, let's assume we start a child thread at test case 1, later, when the test case 2 starts, if we want to access the current test result in the child thread, it will always show test case 1.

Never changes.

Any good solution for this?

Br,
Tim

**Comment by krmahadevan** [comment]
Not much information available to debug or investigate this issue. Please feel free to reopen if you have additional context/sample test that can be used to recreate the problem that you are experiencing.
