### ISSUE TITLE
successPercentage not working correctly, tests not showing up in report

### ISSUE THREAD

**Issue by thirsch81** [cbeust/testng#369]
I had an issue when trying not to have group-dependent tests skipped, when using retries and parallel execution. It's a rather complicated example, so explaining with words doesn't really make sense, but I could boil it down to a test not showing up in the report when I tag it with successPercentage. I would love to include my small self contained Gradle sample project.

**Comment by krmahadevan** [comment]
No sample found in this issue and could not also locate the email on the mailing list which contains the project. Closing this issue for want of a sample. If this is still a problem using the latest released version of TestNG (`7.1.0` as of today), comment with a reproducible sample and we can have this issue re-opened.
