### ISSUE TITLE
The data provider Exception message is not correct

### ISSUE THREAD

**Issue by gzchest** [cbeust/testng#370]
Below exception happened when the dataProvider return type is not correct:

com.testng.Student com.testng.HelloTestNG.getStudents() must return either Object[][] or Iterator<Object>[], not class com.testng.Student

However, the message is not correct. Iterator<Object>[] should be Iterator<Object[]>

**Comment by krmahadevan** [comment]
As of TestNG 6.12 this is no longer an issue. Please see [here](https://github.com/cbeust/testng/blob/6.12/src/main/java/org/testng/internal/MethodInvocationHelper.java#L136-L137)
