### ISSUE TITLE
Make Test annotation Inerited

### ISSUE THREAD

**Issue by carlin-q-scott** [cbeust/testng#374]
I would like the Inherited annotation to be added to the Test interface so that base class Test properties are inherited.

The reason I want this is because I made a base Test class with a Before/AfterClass routine which I always want called for every test class. It works very well in most instances but certain test classes are grouped together by TestNG causing the base test's Before/AfterClass methods to be called before/after both tests are executed. I can fix this by setting the singleThreaded property to true in the inheriting test class but adding that property to every test class is a bit cumbersome.

**Comment by krmahadevan** [comment]
Adding the `@java.lang.annotation.Inherited` annotation to `@Test` can basically have un-intended effects to child classes and can cause backward compatibility to break. I am for now closing this issue.

Please add more details in terms of what is the issue and what we are trying to solve, so that we can take a closer look.

**Comment by adrian-herscu-ge** [comment]
> Adding the `@java.lang.annotation.Inherited` annotation to `@Test` can basically have un-intended effects to child classes and can cause backward compatibility to break. I am for now closing this issue.
> 
Regarding the backward compatibility I would say that no one should expect a major version to be backward compatible with previous one...

**Comment by krmahadevan** [comment]
Sure. I hear you and agree with you as well. But I am not sure if this
level of backward compatibility deviation is something that we want.

@juherr - Your thoughts ?

>

**Comment by juherr** [comment]
I'm not sure to understand the issue : 
If I'm right, `@Test` is already inherited but the lookup is done by the testng core instead of the jdk itself.
