### ISSUE TITLE
Can't use both groups and dataprovider at the same time

### ISSUE THREAD

**Issue by JoeBuddha** [cbeust/testng#378]
When I use dataprovider, it works fine, When I add a groups member, it all the sudden can't find the dataprovider. Any idea what's going wrong?

Header:

``` java
 @Test(dataProvider = "provide", groups = { "smoke" })
    public void testAllSidebarLinksExist(String item, Data.ItemTypes types)
```

Working XML:

``` xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SmokeTests" verbose="1" >
    <test name="CheckLinks">
        <classes>
            <class name="com.me.Content.ContentTests" />
        </classes>
    </test>
</suite>
```

Non-working XML:

``` xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SmokeTests" verbose="1" >
    <groups>
        <run>
            <include name="smoke"/>
        </run>
    </groups>
    <test name="CheckLinks">
        <classes>
            <class name="com.me.Content.ContentTests" />
        </classes>
    </test>
</suite>
```

Dump:

```
java.lang.NullPointerException

org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:143) 
at org.testng.internal.Parameters.handleParameters(Parameters.java:426) 
at org.testng.internal.Invoker.handleParameters(Invoker.java:1383) 
at org.testng.internal.Invoker.createParameters(Invoker.java:1075) 
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180) 
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) 
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) 
at org.testng.TestRunner.privateRun(TestRunner.java:767) 
at org.testng.TestRunner.run(TestRunner.java:617) 
```

**Comment by shwetainamdar** [comment]
I am facing the similar issue even after using alwaysRun=true. @JoeBuddha, Were you able to resolve it?

**Comment by pavetok** [comment]
+1 (6.9.6)

**Comment by cbeust** [comment]
Can you post a short example showing the problem?

-- 
Cédric

**Comment by pavetok** [comment]
I'm sorry, but I could not reproduce the error on my home laptop.

**Comment by DhartiAuto** [comment]
Hello all,
what is alternate solution of this issue? because this issue still not resolved

**Comment by krmahadevan** [comment]
@DhartiAuto - Do you have a sample standalone example that can be used to reproduce this issue? Please also make sure you are using TestNG `7.0.0`

**Comment by Satyabrata4957** [comment]
Bt using the 7.0.0 over 6.14.3 i am getting error.
[RemoteTestNG] detected TestNG version 7.0.0
java.lang.NoSuchMethodError: org.testng.remote.AbstractRemoteTestNG.addListener(Lorg/testng/ISuiteListener;)V
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

and i am still unable to use data provider and the groups at same time

**Comment by krmahadevan** [comment]
@Satyabrata4957 - You are experiencing incompatibility between the plugin version and the TestNG jar in your classpath. Please upgrade your eclipse TestNG plugin to the latest or try using an IDE such as intellij.

**Comment by DeChrish** [comment]
Issue still exists - v7.0.0 / Intellij IDE

**Comment by krmahadevan** [comment]
@DeChrish the latest released version is `7.3.0`

**Comment by krmahadevan** [comment]
Cannot reproduce this on TestNG `7.3.0`

Here's a sample

```java
import java.util.ArrayList;
import java.util.List;
import org.testng.annotations.AfterGroups;
import org.testng.annotations.BeforeGroups;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestClassSample {

  public static final List<String> logs = new ArrayList<>();

  @BeforeGroups(groups = "smoke")
  public void beforeGroups() {
    logs.add("beforeGroups");
  }

  @AfterGroups(groups = "smoke")
  public void afterGroups() {
    logs.add("afterGroups");
  }

  @Test(dataProvider = "dp", groups = "smoke")
  public void testAddition(int a, int b) {
    logs.add("testAddition: " + a + "+" + b);
  }

  @DataProvider(name = "dp")
  public Object[][] getData() {
    return new Object[][]{
        {1, 2},
        {4, 5}
    };
  }
}

```

```java
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.testng.Assert;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlGroups;
import org.testng.xml.XmlRun;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

public class IssueTest {

  @Test
  public void runTest() {
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setName("suite_378");
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("test_378");
    xmlTest.setXmlClasses(Collections.singletonList(new XmlClass(TestClassSample.class)));
    XmlRun xmlRun = new XmlRun();
    xmlRun.onInclude("smoke");
    XmlGroups xmlGroups = new XmlGroups();
    xmlGroups.setRun(xmlRun);
    xmlTest.setGroups(xmlGroups);
    System.err.println(xmlSuite.toXml());
    TestNG testng = new TestNG();
    testng.setXmlSuites(Collections.singletonList(xmlSuite));
    testng.run();
    System.err.println(TestClassSample.logs);
    List<String> expected = Arrays
        .asList("beforeGroups", "testAddition: 1+2", "testAddition: 4+5", "afterGroups");
    Assert.assertEquals(TestClassSample.logs, expected);
  }

}
```

Here's the output

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="suite_378">
  <test thread-count="5" name="test_378">
    <groups>
      <run>
        <include name="smoke"/>
      </run>
    </groups>
    <classes>
      <class name="com.rationaleemotions.issue378.TestClassSample"/>
    </classes>
  </test> <!-- test_378 -->
</suite> <!-- suite_378 -->


===============================================
suite_378
Total tests run: 2, Passes: 2, Failures: 0, Skips: 0
===============================================

[beforeGroups, testAddition: 1+2, testAddition: 4+5, afterGroups]


===============================================
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by ashishraj14** [comment]
Hi there,
I have tried all the suggestions that I could find on how to run groups with dataprovider. Below is the code which I am using to specify dataprovider and it runs like  a charm.however when I use "groups" it doesnt run any tests..
  @Test(testName ="Compare",description = "abc",groups = "Service1",
            dataProvider = "TestData", dataProviderClass = TestDataColl.class)
I have beforetest and beforemethod functions which I am using and as mentioned by everyone nothing gets executed.
I am using testng 7.3.0

It appears that groups can not be used with dataproviders where you are using beforetest and beforemethod functions. Have tried using alwaysRun=true and by using group=<name> as well.
My test looks like this


    @BeforeTest
    public void beforeTest()
    {
        // do blah
    }

    @BeforeMethod()
    public void beforeMethod()
    {
       //do blah
    }

 @Test(testName ="Compare",description = "abc",groups = "Service1",
 dataProvider = "TestData", dataProviderClass = TestDataColl.class)
    public void test1()
    {     }

**Comment by ashishraj14** [comment]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.820 s
[INFO] Finished at: 2021-02-17T10:14:48+11:00
[INFO] ------------------------------------------------------------------------
