### ISSUE TITLE
TestNg runner fails to start when socks proxy specified

### ISSUE THREAD

**Issue by vkhoroshko** [cbeust/testng#379]
For some tests we need socks proxy and we specify it in the VM parameters:
-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=7777

After that we get the following error (tried different versions of TestNG (6.8,6.3.1):
java.io.EOFException
    at java.io.DataInputStream.readBoolean(DataInputStream.java:244)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:46)

The interesting thing that JUnit works just fine.

**Comment by krmahadevan** [comment]
Ported to https://github.com/cbeust/testng-eclipse/issues/452
