### ISSUE TITLE
Possible changes to TestNG.run()

### ISSUE THREAD

**Issue by ghost** [cbeust/testng#381]
Hi 

This post is to gauge if there would be an appetite to augment the current TestNG.run() method and add three new public methods e.g prepareRun(), performRun() and postRun(). 

The reasoning for this is as follows:-
The use case is that we would like to schedule the running of all tests contained a suite.xml file. In this schedule, the configuration methods would only run once i.e. at the start of the suite and at the end of the suite (prepareRun() & postRun() but the tests would be run based on a timer or a predefined loop i.e. performRun(). 

For this use case, the schedule that determines when and how many times the tests are run is dynamic and will not be known when TestNG is started i.e. performRun() will be called programmatically.

I hope this is the correct place for this post, if not please let me know.

Many thanks
John

**Comment by krmahadevan** [comment]
This can currently be achieved by building this logic within TestNG listeners/Configuration methods such that they get executed only once per JVM (for e.g., by creating a zero byte file, or with a data base entry etc.,) Closing this issue for now. Please feel free to open up this issue, if you would like to resume a conversation on this.
