### ISSUE TITLE
TestNg braking execution while calling perl scripts (perl scripts importing other modules or scripts)

### ISSUE THREAD

**Issue by sitaramireddym** [cbeust/testng#384]
i am using testng framework(version 6.8), im calling perl scripts from my TestNG class(using Runtime.getRuntime().exec(perl filename.pl)) here i can able to call one perl script, but if  that perl script may call another script then TestNg can't handle perl execution.

Note: from java i can able to call one perl script and multiple perl scripts(having dependencies one perl script calling another perl script sub routines)

Reference:  

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import org.testng.annotations.Test;

public class PerlSample {

```
@Test
public void addhost1(){

    Process process;

    try {

        System.out.println("about to execute command");
        process = Runtime.getRuntime().exec("perl E:/oct12/PerlTestNG/src/Nodes/addNum.pl");

        process.waitFor();
        System.out.println("Result is " + process.exitValue());
        if (process.exitValue() == 0) {
            System.out.println("Command Successful");
            try {
                BufferedReader in = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line = null;
                while ((line = in.readLine()) != null) {
                    System.out.println(line);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        } 
            else {

            System.out.println("Command Failure"+ "-----Unable to excute perl script");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

}
```

addNum.pl:
# !/usr/bin/perl
# To Add a Host  locally

use strict;
use IO::Socket;
use Test::More qw(no_plan);
BEGIN {
      use_ok('SVClient');
    }
my $profile = "logins/1_lc";
my ($sessionId, $ua) = do_login_file ($profile)
       or die "Login failed!\n";
## This code is used to get cmdStr value from backend -

my $Session_filepath = "C:/SVCentral/Sessions/cgisess_$sessionId";
my $cmdStr;
my $hostIP="10.0.15.38";
# Lets parse the session file here

if (-e $Session_filepath) 
{
    #print "File Exists!";
    open (STDIN, "< $Session_filepath")
    or die "Unable to open login file $Session_filepath: $!\n";

```
while (<STDIN>) {
    if ($_ =~ m/\'userKey\' => \'(.*?)\'/) {
        $cmdStr = "key\=$1\&HMGR_ADDHOST\&\-\&10\.0\.15\.176\&".$hostIP."\&\-\&\-\&0\&low\&\-\&\-\&\-\&";
    }
}
```

}
# print "$cmdStr";

my $server = '10.0.15.176';
my $port   = 10616;
my $socket = IO::Socket::INET->new(PeerAddr => $server,
                            PeerPort => $port,
                            Proto    => "tcp",
                            Timeout  => 3000,
                            Type     => SOCK_STREAM)
    or die  print "Couldn't connect to $server:$port : $!\n";
# print $socket,$cmdStr;

$socket->send($cmdStr);
my $response="";
do
{
    $_ = <$socket>; 
    $response .= $_;
}while($_);
# and terminate the connection when we're done

close($socket);
my $status="";

sub  response {
    if($response =~ /^OK/){
        #print STDOUT "SUCCESS! Host is added Successfully!!\n $response";
        is('1','1',"SUCCESS! Host is added Successfully!!\n $response");
    }
    else {
        #print STDOUT "ERROR! $response";
        is('0','0',"ERROR! $response");
    }
}

response($response);

SVClient.pm

use Exporter;
use LWP::UserAgent;
use HTTP::Request::Common;
use URI::Escape;
use MIME::Base64;
use Data::Dumper;
use File::Basename;
use IO::Seekable;

our @ISA = qw(Exporter);
our @EXPORT = qw(
            do_login
            do_login_file
            do_logout 
            write_temp_file  
            write_any_file  
            file_exists
            do_cgi_get
            do_get
            get_file
            send_mainengine_cmd
            send_to_reporting
            init_cmd_params
            write_forensic_record
            list_forensic_dir
            get_all_file 
            finishSearching
            finishSearching1
            get_all_large_file
            get_large_file
            write_policy_user
            $sessionId $ua );

our $sessionId;
our $svbase_url;

our $ua = new LWP::UserAgent;
# allow redirection for POST - we need this for login

push @{$ua->requests_redirectable}, 'POST';
$ua->cookie_jar({ file => "$ENV{HOME}"."/svcookies.txt" });

my %encoded_params = ('password'=>1);
our %global_cmd_params;
# This is convenient way to login without specifying a whole bunch of
# parameters every time. The expected file format is kind of obvious from
# the code below, please look at 1_lc for a sample

sub init_cmd_params {
    my ($cmd_file) = @_;
    $cmd_file
        or ($cmd_file = "cmds.txt");

```
open (CMDS, "< $cmd_file")
    or die "Unable to open commands file ($cmd_file): $!\n";

my $line;
while ($line = <CMDS>) {
    $line =~ s/\s+$//g;
    if ($line =~ /^#/ || $line !~ /[A-Za-z]/) {
        next;
    }
    my ($cmd, @param_names) = split(/[\t,]/, $line);
    $global_cmd_params{$cmd} = \@param_names;
}
close CMDS;
```

}
sub do_login_file {
    my ($login_file) = @_;
    open (LOGIN, "< $login_file")
        or die "Unable to open login file $login_file: $!\n";

```
my ($line, $username, $password, $port, $url, $ssl);
while ($line = <LOGIN>) {
    if ($line =~ /-u /) {
        $username = $';
        $username =~ s/\s+$//;
        next;
    }

    if ($line =~ /-ssl/) {
        $ssl = 1;
    }

    if ($line =~ /-i /) {
        $url = "http://" . $';
        $url =~ s/\s+$//;
        next;
    }

    if ($line =~ /-p /) {
        $port = $';
        $port =~ s/\s+$//;
        next;
    }

    if ($line =~ /password=/) {
        $password = $';
        $password =~ s/\s+$//;
        next;
    }
}

close LOGIN;

if (!$port) {
    $port = "8216";     
}

if ($ssl) {
    $url =~ s/^http/https/;
}

my $baseurl = "$url:$port";
do_login ($baseurl, $username, $password);
```

}

sub do_login {
    my ($base_url, $username, $password) = @_;

```
$svbase_url = $base_url;
my $login_url = $base_url . "/cgi-bin/login.cgi";
#print $login_url."\n\n";
#Step 1: login.cgi
my $response = $ua->request(POST "$login_url", 
                            "Content_Type"=>'form-data', 
                            Content => [
                                userName => "$username",
                                password => "$password"
                                ]
                            );
#print $response->as_string();

#Step 2: Redirect to process.cgi

my $sessionLine = (grep { /cgisess=/ } split(/\n+/, $response->as_string()))[0];
#print $sessionLine ;


#print $login_url.'\t'.$svbase_url.'\t'.$username.$password;


$sessionId = undef;
if ($sessionLine =~ /cgisess=([a-f0-9]+)/) {
    $sessionId = $1;

} else {
    #print $response->as_string;
    return "";
}

#It is probably not necessary to go through any of the subsequent steps.
#print $sessionLine;
return $sessionId;

$sessionLine =~ /\"([^\"]+)\"/;
my $newurl = $1;
$newurl =~ s/^\.\.//;

$newurl = $base_url . $newurl;
$response = $ua->request (GET $newurl);

#Step 3: default.cgi
my $defaultcgi =  (grep { /location\.href/ } split(/\n+/, ($response->as_string)))[0];
$defaultcgi =~ /\"([^\"]+)\"/;
$newurl = $1;
$newurl =~ s/^\.\.//;
$newurl = $base_url . $newurl;
$response = $ua->request (GET $newurl);

#Step 4: showUIPortal.cgi
my $showuiportal = (grep { /showUIPortal/ } split(/\n+/, ($response->as_string)))[0];
$showuiportal =~ /src=\"([^\"]+)\"/;
$newurl = $1;
$newurl = $base_url . "/cgi-bin/$newurl";
$response = $ua->request (GET $newurl);

return ($sessionId, $ua);
```

}

sub do_logout {
    my $logout_url = $svbase_url . "/cgi-bin/logout.cgi?sessID=$sessionId";
    my $response = $ua->request(GET "$logout_url");
}

sub get_large_file {
    my ($filename, $destfile) = @_;
    my $fileurl = $svbase_url . "/cgi-bin/file.cgi?cgisess=$sessionId&hash=name=$filename";
    my $req = new HTTP::Request 'GET',$fileurl;
       $response = $ua->request($req,  $destfile);
        if ($response->is_success) {
        return "Success";
        }
        return "error";
}

sub get_file {
    my ($filename, $destfile) = @_;
    my $fileurl = $svbase_url . "/cgi-bin/file.cgi?cgisess=$sessionId&hash=name=$filename";
    my $response = $ua->request (GET $fileurl);
    #print $response->content;
        if ($response->is_success) {
        open (DEST, "> $destfile")
            or die "Unable to open destination file: $!\n";
        print DEST $response->content;
        close DEST;
        return "Success";
    } 
    return "error";
}

sub get_all_file {

```
my ($filelistsref,$destfolder)=@_;
foreach $file (@$filelistsref) {
    my $destfile= basename($file);
    ($x,$file)= split(/ngscentral/i,$file);
    $res="";
    my ($filename, $destfile) = ($file,$destfolder."/".$destfile);
    my $fileurl = $svbase_url . "/cgi-bin/file.cgi?cgisess=$sessionId&hash=name=$filename";
    my $response = $ua->request (GET $fileurl);
    #print $filename."\t". $destfile."\n";
    if ($response->is_success) {
        if($filename =~ /\/queries\//){
        #if(-d $filename){
            #print basename($filename)."\n\n";
            $destquer=$destfolder."/queries";
            unless(-d  $destquer){
            mkdir  $destquer,0777 ;
            }
            $destfile=$destquer."/".basename($file);
            #print "$filename\n$destquer\n$destfile\n";
        }
        open (DEST, "> $destfile")
        or die "Unable to open destination file: $!\n";
        print DEST $response->content;
        close DEST;
        $res="Success";
    }else{$res="error"; }
    #print "$file got ". $res."\n";

    }
```

}

sub get_all_large_file {

```
my ($filelistsref,$destfolder)=@_;
foreach $file (@$filelistsref) {
    #print $file."\n\n";
    my $destfile= basename($file);
    my ($x,$file)=  split(/ngscentral/i,$file);
    my ($filename, $destfile) = ($file,$destfolder."/".$destfile);
    if($filename =~ /\/queries\//){
            $destquer=$destfolder."/queries";
            unless(-d  $destquer){
            mkdir  $destquer,0777 ;
            }
            $destfile=$destquer."/".basename($file);
    }
    my $fileurl = $svbase_url . "/cgi-bin/file.cgi?cgisess=$sessionId&hash=name=$filename";
    print $destfile."\n\n";
    my $req = new HTTP::Request 'GET',$fileurl;
    $response = $ua->request($req,  $destfile);
        if ($response->is_success) {
        return "Success";
        }
        else {return "error";
        }
}
```

}

sub finishSearching {
    my ($filelistsref)=@_;
    foreach $file (@$filelistsref) {
        print $file."\n\n";
        my $destfile= basename($file);
        my ($x,$file)=  split(/ngscentral/i,$file);
        $res="";
        my ($filename, $destfile) = ($file,$destfolder."/".$destfile);
        #print $file."\n\n";
        if($filename =~ /jobstatus.ext/){
        label:
            my $fileurl = $svbase_url . "/cgi-bin/file.cgi?cgisess=$sessionId&hash=name=$filename";
            my $response = $ua->request (GET $fileurl);
             $line= $response->content;
             print $line;
                if($line =~ m/^2~(.*)$/){ #close INFILE;
                return $line;}
                else{ sleep 1; #seek INFILE,0,0;
                goto label ;
                }

```
    }
}
```

}

sub finishSearching1{
    my ($user_timestamp)=@_;
        $filename="forensics/forensicReports/".$user_timestamp."/jobstatus.ext" ;

```
    label:
        my $fileurl = $svbase_url . "/cgi-bin/file.cgi?cgisess=$sessionId&hash=name=$filename";
        my $response = $ua->request (GET $fileurl);
         $line= $response->content;

            if($line =~ m/^2~(.*)$/){ #close INFILE;
            return $line;}
            else{ sleep 1; #seek INFILE,0,0;
            goto label ;
            }
```

}

sub do_get { 
    my ($url) = @_;
    my $svurl = $svbase_url . "/" . $url;

```
#print $svurl."\n";
my $response = $ua->request(GET $svurl);
if ($response->is_success) {
    return $response->content;
}
return "";
```

}

sub write_temp_file {
    my ($filename, $content) = @_;
    my $svurl = $svbase_url . "/cgi-bin/saveXML.cgi";
    my $response = $ua->request(POST "$svurl",
                            "Content_Type"=>'www-form-urlencoded',
                            "Content"=> [
                                cgisess=> $sessionId,
                                command=>"WRITETEMPFILE#$filename#$content"
                                ]
                    );
    if ($response->is_success) {
        return $response->content;
    }
    return "";
}

sub list_forensic_dir{

```
my ($filename) = @_;
my $svurl = $svbase_url . "/cgi-bin/saveXML1.cgi";
my $response = $ua->request(POST "$svurl",
                        "Content_Type"=>'www-form-urlencoded',
                        "Content"=> [
                            cgisess=> $sessionId,
                            command=>"LISTFORENSICDIR#$filename"
                            ]
                );
#print $response->as_string;
if ($response->is_success) {
my $content = (grep { /Dirlist,/ } split(/\n+/,$response->as_string()))[0];
#print $content;
@filelists=split(/\,/,$content);
pop(@filelists);
shift(@filelists);
return  @filelists;
}
return "";
```

}

sub write_any_file {
    my ($filename, $content) = @_;
    my $svurl = $svbase_url . "/cgi-bin/saveXML.cgi";
    my $response = $ua->request(POST "$svurl",
                            "Content_Type"=>'www-form-urlencoded',
                            "Content"=> [
                                cgisess=> $sessionId,
                                command=>"WRITEATAPPPATH#$filename#$content"
                                ]
                    );
    if ($response->is_success) {
        return $response->content;
    }
    return "";
}

sub write_forensic_record {
    my ($filename, $content) = @_;
    my $svurl = $svbase_url . "/cgi-bin/saveXML1.cgi";
    #print $svurl."\n\n".$sessionId;
    my $response = $ua->request(POST "$svurl",
                            "Content_Type"=>'www-form-urlencoded',
                            "Content"=> [
                                cgisess=> $sessionId,
                                command=>"WRITEFORENSICFILE#$filename#$content"
                                ]
                    );
# print $response->as_string;

```
if ($response->is_success) {
    return $response->content;
}
return "";
```

}

sub write_policy_user {
    my ($filename, $content) = @_;
    my $svurl = $svbase_url . "/cgi-bin/saveXML1.cgi";
    print $svurl."\n\n".$sessionId;
    my $response = $ua->request(POST "$svurl",
                            "Content_Type"=>'www-form-urlencoded',
                            "Content"=> [
                                cgisess=> $sessionId,
                                command=>"WRITEPOLICYUSER#$filename#$content"
                                ]
                    );
print $response->as_string;

```
if ($response->is_success) {
    return $response->content;
}
return "";
```

}

sub write_alert_record {
    my ($filename, $content) = @_;
    my $svurl = $svbase_url . "/cgi-bin/saveXML1.cgi";
    #print $svurl."\n\n".$sessionId;
    my $response = $ua->request(POST "$svurl",
                            "Content_Type"=>'www-form-urlencoded',
                            "Content"=> [
                                cgisess=> $sessionId,
                                command=>"WRITEALERTFILE#$filename#$content"
                                ]
                    );
# print $response->as_string;

```
if ($response->is_success) {
    return $response->content;
}
return "";
```

}

sub send_to_reporting {
     my ($cmd, $sessionId) = @_;
    my $svurl = $svbase_url . "/cgi-bin/ReportingProxy.cgi";
    my $response = $ua->request(POST "$svurl",
                            "Content_Type"=>'www-form-urlencoded',
                            "Content"=> [
                                cgisess=>$sessionId,
                                command=>"$cmd"
                                ]
                    );

```
#print $response->as_string;
if ($response->is_success) {
    return $response->content;
}
```

}

sub get_cmd_params {
    my ($cmd, $params_ref) = @_;
    my @param_values;
    push @param_values, $cmd;
    #print "inside get_cmd: ".$cmd ."\t".$params_ref->{'username'};
    foreach my $pname (@{$global_cmd_params{$cmd}}) {
        #print "panme:".$pname."\n\n";
        if (!$params_ref || !$params_ref->{$pname}) {
            if ($pname ne 'unknown' && $pname !~ /\?$/) {
                warn "Params does not have $pname, which is a required parameter\n";
            }
            push @param_values, '-';
        } elsif ($encoded_params{$pname}) {
            my $value = encode_base64($params_ref->{$pname});
            $value =~ s/\s+$//;
            push @param_values, $value;
        } else {
            push @param_values, $params_ref->{$pname};
        }
    }
        #print $#param_values;

```
 return join ("&", @param_values);
```

}

sub send_mainengine_cmd {
     my ($cmd, $sessionId) = @_;
     my $svurl = $svbase_url . "/cgi-bin/eIQPostProxy.cgi";

```
 print $svurl."\n".$sessionId."\n";
my $response = $ua->request(POST "$svurl",
                    "Content_Type"=>'www-form-urlencoded',
                    "Content"=> [
                        cgisess=>$sessionId,
                        command=>$cmd,
                        ]
                );
print $response->as_string;
if ($response->is_success) {
    return $response->content;
}
```

}

sub get_mainengine_cmds {
    return %global_cmd_params;
}

sub do_cgi_get {
    my ($cgi, $params) = @_;
    my $svurl = $svbase_url . "/cgi-bin/" . $cgi . "?cgisess=$sessionId&hash=" . $params;
    my $response = $ua->request(GET $svurl);

```
$string=$response->as_string;
if ($string =~ m/(\'userKey\' => \')/) {
    @userkey=split(/\'/,$');



    return "@userkey[0]";
}

if ($response->is_success) {
    return $response->content;
}
return "";
```

}

sub get_userkey {
        $var=@_;
        print $var[1];
}1;

OutPut of PerlSample program:

Command Failure"+ "-----Unable to excute perl script

**Comment by SatishKumarKV** [comment]
@sitaramireddym 
Facing same issue , How did u resolve it..?

**Comment by juherr** [comment]
@SatishKumarKV I propose you open a new issue. This one is very old and looks really specific
