### ISSUE TITLE
EmailableReporter2 always escapes html characters

### ISSUE THREAD

**Issue by irusev** [cbeust/testng#387]
After upgrading to the last version (8.1 and the 9beta) I'm experiencing the following problem:
I'm using Reporter.log() to log some html (colors, links to screenshots, etc), but now my html characters are escaped. This happens with the new EmailableReporter2.java, even if I do Reporter.setEscapeHtml(false) - which is actually the default. If I switch to the old reporter, setting the system property "oldDestngEmailableReporter", the html characters are escaped only when we setEscapeHtml to true.

Regards,
Ivan

**Comment by krmahadevan** [comment]
This is no longer a problem with TestNG `7.8.0` (latest released version as of today)
