### ISSUE TITLE
Cant run multiple test suites - Guice injection failed

### ISSUE THREAD

**Issue by kronar** [cbeust/testng#395]
I've got a suite file and using IOC over Guice annotation

Example is here
https://gist.github.com/kronar/5696989 

For now this config fails with errors signaling that no dependecies were injected.

**Comment by krmahadevan** [comment]
The example shared can't be used to debug this problem. Closing this issue for lack of information. If the problem persists with `7.5` (latest released version) please comment and share a full fledged example that can be used to reproduce the problem.
