### ISSUE TITLE
NullPointerException in AssertNull Message when Assertion Passes

### ISSUE THREAD

**Issue by RileyAugust** [cbeust/testng#407]
When you use Assert.AssertNull() and reference the object being asserted on in the error message, such as:

String testString = null;
        Assert.assertNull(testString, "String " + testString.charAt(0) + " is null");

It throws a nullPointerException pre-generating the error message, instead of just passing the test! In production, this message is being used to pull the non-null error message from an error object (the object is null when there is no error) and TestNG throws a NullPointerException when the test passes.

I have attached the Eclipse TestNG project on Google Code (awaiting moderation).

**Comment by krmahadevan** [comment]
Closing this issue based on above comments.
