### ISSUE TITLE
Why TestNg keep instances of tests in memory ?

### ISSUE THREAD

**Issue by ValentinOzanne** [cbeust/testng#411]
Hi !

In memory dump, we can see that TestNg keep instances of tests in memory, so they are always attached to the JVM and memory was not freed.

In our project, it causes Out of Memory exeptions.
Why a such behaviour ? Is it a bug ?

Thanks in advance.

**Comment by krmahadevan** [comment]
A lot of the memory foot print has been reduced as part of fixing https://github.com/cbeust/testng/issues/2096 and this mode can be turned on by using the JVM argument `-Dtestng.memory.friendly=true`

**Comment by ValentinOzanne** [comment]
Hi, Thanks @krmahadevan  for the feedback. It's a good news.
