### ISSUE TITLE
@Parameter and @Dataprovider conflict

### ISSUE THREAD

**Issue by sechitwood** [cbeust/testng#414]
The function below never gets called, causing all tests that use this dataprovider on it to skip.

```
@Parameters({ "successFile" })
@DataProvider(name = "Success Results")
public Object[][] successData(String successData) throws IOException {

    List<Object[]> destList = getValuesCsv(successData);
    return destList.toArray(new Object[destList.size()][]);
}
```

I was able to workaround by removing the @Parameters decoration and setting successData in the @BeforeClass method.

**Comment by krmahadevan** [comment]
Even though this issue predates when compared to https://github.com/cbeust/testng/issues/906 I am closing out this one since there are some discussions and also work arounds posted in https://github.com/cbeust/testng/issues/906
