### ISSUE TITLE
Expected Exceptions Message fails to match multi-line messages

### ISSUE THREAD

**Issue by dimo414** [cbeust/testng#417]
Providing an `expectedExceptionsMessageRegExp` value to a test should intuitively match any provided regex.  However since `Invoker.messageRegExpMatches()` uses `Pattern.matches()` instead of `Matcher.find()` or `Pattern.compile(re, Pattern.DOTALL)` it is possible for a message to match or fail arbitrarily based on the existence of a newline.

Even if the user should be expected to explicitly drop the pattern into `dotall` mode, the current error message is unclear and confusing:

    The exception was thrown with the wrong message: expected ".*Illegal.*" but got "Illegal State.
    Two lines breaks the test."

Example test:

    import org.testng.annotations.Test;
    
    public class MessagePatternTest {
        @Test(expectedExceptions=IllegalStateException.class, expectedExceptionsMessageRegExp=".*Illegal.*")
        public void singleLine() {
            throw new IllegalStateException("Illegal State.");
        }
        
        @Test(expectedExceptions=IllegalStateException.class, expectedExceptionsMessageRegExp=".*Illegal.*")
        public void multiLine() {
            throw new IllegalStateException("Illegal State.\nTwo lines breaks the test.");
        }
        
        @Test(expectedExceptions=IllegalStateException.class, expectedExceptionsMessageRegExp="(?s).*Illegal.*")
        public void multiLineDOTALL() {
            throw new IllegalStateException("Illegal State.\nTwo lines breaks the test.");
        }
    }

**Comment by yusong-shen** [comment]
In case someone stucks at older version before fix but still want this to work (should rarely be the case at 2020 😂 ), here is a workaround : 
replace all the `.` to `(\\S|\\s)` in expectedExceptionsMessageRegExp
