### ISSUE TITLE
threadCount parameter does not work with ant script

### ISSUE THREAD

**Issue by khospodarysko** [cbeust/testng#419]
Hi,

I'm trying to run my TestNG tests with ant script.
The only problem I have is that I can't run them in parallel. The tests are always run in one thread.

Maybe I messed up with some parameters, but it seems that everything is correctly set up in ant script.

Here is my build.xml file:

Notes:
 - my.jar - file is built by command "maven clean package", so it has all my tests and TestNG.
 - parallel does not work for paralle="methods" and parallel="tests"

        <project name="Testing" default="runTest" basedir=".">
          <taskdef resource="testngtasks" classpath="my.jar"/>
          <target name="runTest">
            <testng testJar="my.jar"
                         classpath="my.jar" 
                         outputDir="test-output" 
                         useDefaultListeners="false" 
                         mode="testng" 
                         parallel="methods"
                         threadCount="2">
              <sysproperty key="serverUrl" value="127.0.0.1"/>
              <sysproperty key="applicationUrl" value="http://application.under.test.com"/>
              <xmlfileset dir="tests" includes="Tests.xml"/>
            </testng>
          </target>
        </project>

Tests.xml looks like:

        <suite name="My Tests">
          <test name="Test 1">
            <classes>
              <class name="Class1" />
            </classes>
          </test>
          <test name="Test 2">
            <classes>
              <class name="Class2" />
            </classes>
          </test>
          <test name="Test 3">
            <classes>
              <class name="Class3" />
            </classes>
          </test>
        </suite>

**Comment by Tygerian** [comment]
I ran into this issue as well, and after some investigation found that the title of the issue is not (or no longer) accurate as of 6.9.9.

What I found was that the threadCount attribute works, but only affects tests that are passed to TestNG directly, and not via an xml file. Whether that's an oversight or a design decision is up to the devs.

Here an example where threadCount works correctly:
```xml
<testng parallel="methods" threadCount="2">
    <classpath>
        <path refid="javac.classpath"/>
        <pathelement location="${test.classes.dir}"/>
    </classpath>
    <classfileset dir="${test.classes.dir}">
        <include name="**/tests/**/*Test.class"/>
    </classfileset>
</testng>
```
where `test.classes.dir` is a reference id to the PATH containing external jars, and `test.classes.dir` is a property pointing to the location of my built tests. Notice no mention of an xml file.

**Comment by juherr** [comment]
Nice, it may explain this problem too: https://groups.google.com/forum/#!topic/testng-users/kRmLWw6ts0U

Could you propose a pull-request with a test that shows the issue? A good start is https://github.com/cbeust/testng/tree/master/src/test/java/test/thread

**Comment by cbeust** [comment]
Definitely a bug :)

**Comment by ilanagit** [comment]
Hi, 
Maybe you know where I can see the tracking of this bug? Was it reported?
Thanks!

**Comment by aTan-aka-Xellos** [comment]
juherr, yes this topic 'Problem with parallel execution with TestNG + Surefire' describe the same problem.

**Comment by adamjson** [comment]
This bug also affects me when I am using the eclipse TestNG plugin when trying to run a specific test class / set of groups. I've tried specifying every possible value for -parallel [tests|methods|classes etc] with -threadcount 100 and the tests still run sequentially. However, if I run an XML suite that has the parallel and thread-count attributes specified, it works.

**Comment by ilanagit** [comment]
juherr, could you say please in which testNG version the fix would appear? Currently I use 6.8.8.
Thank you for fixing!

**Comment by juherr** [comment]
@ilanagit Next release: 6.9.11 or 6.10. No planned date for the moment.

**Comment by ilanagit** [comment]
juherr, thanks!
