### ISSUE TITLE
Before/AfterSuite methods may not run, when classes from suite use inheritance, and one of them has enabled=false set.

### ISSUE THREAD

**Issue by kubicz10** [cbeust/testng#420]
Hi,

I think this is a bug, and pretty nasty one too, because it may or may not manifest depending on the order of tests. 

TestNG version 6.8.5.

I have three test classes: BaseTestCase (abstract, implementing BeforeSuite method with alwaysRun=true), FirstSample (which derives from BaseTestCase), and SecondSample (it derives from BaseTestCase too).

This classes are included in suite.xml.

If FirstSample class is annotated with Test(enabled=false), BeforeSuite will probably NOT run.
If SecondSample class is annotated with Test(enabled=false), BeforeSuite will probably run.

Sometimes the order changes, but the rule is the same: two (or more) test classes, deriving from one base class, one of which is annotated with enabled=false.

Here's the code to reproduce:

BaseTestCase.java:
```java
public abstract class BaseTestCase{

    protected final static Logger logger = LoggerFactory.getLogger(BaseTestCase.class);

    @BeforeSuite(alwaysRun = true)
    public static void initEnvironment() {
        logger.info("executed initEnvironment (@BeforeSuite)");
    }
}
```

FirstSample.java:
```java
@Test(enabled = false)
public class FirstSample extends BaseTestCase {

    @Test
    public void verifySomethingFirstSample() {
        Assert.isTrue(true);
    }
}
```

SecondSample.java:
```java
public class SecondSample extends BaseTestCase {

    @Test
    public void verifySomethingSecondSample() {
        Assert.isTrue(false);
    }
}
```
sample-tests.xml:
```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Sample Tests" verbose="2" parallel="classes" thread-count="6">
    <test name="Sample test(s)">
        <packages><package name="com.sampletests"/></packages>
    </test>
</suite>
```

**Comment by juherr** [comment]
This issue should have been fixed by #667 and will be available in the next release.
