### ISSUE TITLE
Cannot run a certain group independently amongst dependent groups, in order

### ISSUE THREAD

**Issue by abhivaikar** [cbeust/testng#424]
```
<test name="test" preserve-order="true">
   <groups>
     <run>
       <include name="group1"/>
       <include name="group2"/>
       <include name="group3"/>
       <include name="group4" />
    </run>
 <dependencies>
       <group name="group3" depends-on="group2"/>
        <group name="group2" depends-on="group1"/>
</dependencies>
    </groups>

    <classes>
     <class name="foo.bar"/>
    </classes>
</test>
```

I cannot run group4 as defined in the sequence here. group4 executes just after group1 starts execution. Here I can solve the issue by making group4 dependent on group3. But that will skip group4 if group3 fails. I want to request a feature enhancement for specifying a loose dependency of a group on another where if group B depends on group A, should not get skipped if group A fails.

For example can we have something like this?

```
<dependencies>
  <group name="group4" loosely-depends-on="group3"/>
</dependencies>
```

**Comment by krmahadevan** [comment]
By default `depends-on` is a hard dependency. So downstream dependencies will get skipped if an upstream dependency failed.

The only reason why a soft dependency will be preferred is when ordering has to be maintained. I believe that TestNG already executes tests in the same order as that found in the suite xml file.

So closing this issue.
