### ISSUE TITLE
ConcurrentModificationException @ TextReporter.logResults 

### ISSUE THREAD

**Issue by chuvoks** [cbeust/testng#429]
Exception in thread "main" java.util.ConcurrentModificationException at 
java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372) 
at java.util.AbstractList$Itr.next(AbstractList.java:343) at 
org.testng.reporters.TextReporter.logResults(TextReporter.java:80) at 
org.testng.reporters.TextReporter.onFinish(TextReporter.java:32) at 
org.testng.TestRunner.fireEvent(TestRunner.java:1241) at 
org.testng.TestRunner.afterRun(TestRunner.java:1032) at 
org.testng.TestRunner.run(TestRunner.java:621) at 
org.testng.SuiteRunner.runTest(SuiteRunner.java:334) at 
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) at 
org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) at 
org.testng.SuiteRunner.run(SuiteRunner.java:240) at 
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) at 
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) at 
org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) at 
org.testng.TestNG.runSuitesLocally(TestNG.java:1149) at 
org.testng.TestNG.run(TestNG.java:1057) at 
org.testng.TestNG.privateMain(TestNG.java:1364) at 
org.testng.TestNG.main(TestNG.java:1333)

**Comment by krmahadevan** [comment]
Reviewed this with the TestNG codebase. Currently the `TextReporter` makes use of either a copy of the array list or works with a synchronized version of the array list. So there are no chances of this issue happening. 

Closing this issue. Please reopen if you see this in TestNG 6.12 or higher.
