### ISSUE TITLE
Enconding issue with XMLReporter

### ISSUE THREAD

**Issue by fragonib** [cbeust/testng#453]
XMLReporter is generating me a wrong UTF-8 encoded xml report file with non-ASCII characters in my test params Strings. I think the issue is a weakness on method of class org.testng.internal.Utils used by XMLReporter:

```java
public static void writeUtf8File(String outputDir, String fileName, XMLStringBuffer xsb, String prefix) {
    try {
      FileWriter fw = new FileWriter(new File(outputDir, fileName));
      if (prefix != null) {
        fw.append(prefix);
      }
      xsb.toWriter(fw);
      fw.close();
    } catch(IOException ex) {
      ex.printStackTrace();
    }
  }
```

This method is using FileWriter which is sensible to default encoding configuration. In some environments default configuration may no match "UTF-8" encoding fixed on file header.

**Comment by juherr** [comment]
Fixed by #460
