### ISSUE TITLE
Optional parameter is not initialized properly in Eclipse - not all <parameter> tags are being added to testng-customsuite.xml

### ISSUE THREAD

**Issue by yherasym** [cbeust/testng#455]
Eclipse Juno Service Realease 2
TestNG plugin 6.8.6.20130914_0724

Preconditions: a project has two testng xml files; a test-class uses parameters with Optional default values (simple project has been attached);
Scenario:
1. Run TestNG test by Right mouse click on test-class (see attachment YH-246 
![yh-246](https://f.cloud.github.com/assets/3171370/1376960/1b15402c-3a9e-11e3-9715-0b0695986340.jpg)
);
As result Eclipse will ask which testng xml has to be used as expected (see attachment YH-247 
![yh-247](https://f.cloud.github.com/assets/3171370/1376963/25049128-3a9e-11e3-8ebd-ea72d33c2881.jpg)
);
2. Select some file.
ActualResult: all optional parameters are initialized with "not-found" values;
see YH-248 
![yh-248](https://f.cloud.github.com/assets/3171370/1377010/d54d2752-3a9e-11e3-80a7-66056f0e1121.jpg)

ExpectedResult: the optional parameters are initialized with their specified default values;

**Comment by niranjankhare** [comment]
I am also facing this issue. has this issue been acknowledged? Any updates on this?

**Comment by bkindley** [comment]
@yherasym comment is spot on. You can see the testng-customsuite.xml being used will not contain all the params from the xml you select from the pop up. Selecting a template XML will get around this, but that is not as convenient as selecting from the pop up. I would think ALL params from the xml you select should make it to the testng-customsuite.xml which would solve this problem.

**Comment by ahoehma** [comment]
I confirm this problem too.

**Comment by juherr** [comment]
Ping @missedone

**Comment by juherr** [comment]
Fixed by cbeust/testng-eclipse/pull/275

**Comment by missedone** [comment]
hi guys,
this is fixed in latest beta of testng eclipse plugin, you can install from the beta update site: http://testng.org/eclipse-beta, please feedback me how is this doing for you.
thanks

**Comment by hasaziz** [comment]
thanks for fixing this bug
