### ISSUE TITLE
Annotate annotations with @Documented

### ISSUE THREAD

**Issue by jinahya** [cbeust/testng#461]
There are a lot of conventions for test methods. One of them looks like this.

``` java
@Test(expectedExceptions = {NullPointerException.class})
public void setName_withNullName_expectingNullPointerException {
    mock.setName(null);
}
```

If `@Test` or any other annotations annotated with `@Documented` the `expectingNullPointerException` could be emitted.

**Comment by krmahadevan** [comment]
@juherr - Does this issue merely require that we add the `@java.lang.annotation.Documented` annotation in all of the TestNG annotations ?

**Comment by juherr** [comment]
@krmahadevan I can't see why someone need javadoc on tests but adding `@Ducumented` is not a huge work and, as explained in the description, is part of the test.

**Comment by cbeust** [comment]
I'm not clear what `@Documented` adds, can you elaborate?

**Comment by juherr** [comment]
It marks the annotation for tools like the javadoc.
For example, the javadoc tool is only displaying `@Documented` annotations and skips the others.
TestNG annotations are part of the test itself (`@Test` for sure with expected exception or timeout, but I don't know for the others)
