### ISSUE TITLE
If @beforeMethod or @afterMethod fails then all children of the same base class will be skipped

### ISSUE THREAD

**Issue by smaant** [cbeust/testng#471]
I've made an example to reproduce the issue: https://github.com/smaant/testng-bug-example

#### Case#1 - normal behaviour
There're two independent classes: ```Class1``` and ```Class2```. ```Class1``` has an ```@afterMethod``` methods and for some reason it fails. All the rest method of the ```Class1``` will be skipped in this case and ```Class2``` will be executed as usual.

#### Case#2 - unexpected behaviour
There're two classes: ```Class1``` and ```Class2``` and they have one common parent ```SuperClass```. ```Class1``` has an ```@afterMethod``` method and for some reason it fails. In this case the rest of the ```Class1``` methods will be skipped AND (*unexpected part*) **all** methods of the ```Class2``` will be skipped too.

In example I've added one more super class with one child to demonstrate it will be actually executed, because of another parent.

**Comment by juherr** [comment]
Fixed by #739

**Comment by drkthng** [comment]
Problem with children being skipped when one child fails during its own @beforeClass method still holds, if children have @beforeClass and the parent class has @beforeClass AND @afterClass.
When you remove @afterClass in parent class, everything works fine, no non-failing children are skipped.

**Comment by juherr** [comment]
@drkthng Could you add your test case in TestNG tests (or update them) in a PR? See the `test.inheritance` package.
