### ISSUE TITLE
suiteXmlFiles is configured, but there is no TestNG dependency

### ISSUE THREAD

**Issue by maydaygjw** [cbeust/testng#472]
Hi cbeust

I have checked out the testng project and done a few enhancement for my project,
I have rename the project to a new maven artifact as a new test framework for my group. But when we integration with maven to execute mvn test, it prompt "suiteXmlFiles is configured, but there is no TestNG dependency", how can I config the testng artifact name inside the surefire configuration

Thank you

**Comment by krmahadevan** [comment]
Closing this issue, since this is more of a question which @fpavageau has answered.

**Comment by msonnenschein** [comment]
I was encountering this error message today and figured out how to solve it.

## Problem

This error kept occurring when trying to run tests with TestNG.  All the tests passed, but then the build failed:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (execution-name) on project project-name: suiteXmlFiles is configured, but there is no TestNG dependency -> [Help 1]
```

The `org.testng:testng` dependency was in my pom.xml, so I was pretty confused:
```xml
<dependency>
	<groupId>org.testng</groupId>
	<artifactId>testng</artifactId>
	<version>${version.testng}</version>
</dependency>
```
  I tried different versions of `testng`, adding the `provided` scope as noted above, and even tried adding the dependency to the maven-surefire plugin.

## Solution

The pom for the project I was trying to build was inheriting from a parent pom.  This parent pom had several `execution` tags defined for the `maven-surefire-plugin` that weren't doing anything. **Overriding these test executions in the child pom resolved my issue.**

After making the following changes, I was able to successfully run `mvn clean test`.  This is an example for just **one** of the overridden executions.  I actually had to override **all three executions** from the parent pom

```xml
<!-- inside the parent pom -->
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<configuration>
		<forkMode>always</forkMode>
		<forkedProcessTimeoutInSeconds>800</forkedProcessTimeoutInSeconds>
	</configuration>
	<executions>
		<execution>
			<id>execution-name</id>
			<configuration>
				<testNGArtifactName>none:none</testNGArtifactName>
			</configuration>
			<goals>
				<goal>test</goal>
			</goals>
		</execution>
<!-- plus two other executions -->
	</executions>
</plugin>

<!-- inside the updated child pom -->
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<executions>
		<execution>
			<id>execution-name</id>
			<configuration combine.self="override">
				<suiteXmlFiles>
					<suiteXmlFile>src/test/resources/testng.xml</suiteXmlFile>
				</suiteXmlFiles>
			</configuration>
		</execution>
<!-- plus two more overridden executions -->
	</executions>
	<version>3.0.0-M5</version>
</plugin>
```
