### ISSUE TITLE
Incorrect timezone info in <test-method> element of testng-results.xml

### ISSUE THREAD

**Issue by gdong42** [cbeust/testng#489]
Hi,

The TestNG XML reporter generates ISO-8601-like time formats in testng-results.xml. However, in XMLSuiteResultWriter class, while writing &lt;test-method&gt; element, the default time format being used is  "yyyy-MM-dd'T'HH:mm:ss'Z'". This is hardcoding timezone into 'Z' indicating timezone 0 (UTC) but the time format is actually using local timezone while generating the timestamp. This will confuse xml report consumer.

A similar issue https://github.com/cbeust/testng/issues/237 has been fixed before which is in XMLReporter class relating to &lt;suite&gt; and &lt;test&gt;element. I think the same fix needs to be done in &lt;test-method&gt; level. Currently they are not consistent in the report.

Thanks,
Gan

**Comment by krmahadevan** [comment]
This was fixed via https://github.com/cbeust/testng/pull/1739
