### ISSUE TITLE
Integration with Tycho

### ISSUE THREAD

**Issue by apohllo** [cbeust/testng#50]
It would be nice if TestNG could be used to test with Tycho http://tycho.sonatype.org/ (this project allows for seamless build and testing of Eclipse based projects with Maven). 

The integration requires that TestNG allows the same class look-up strategy for PackageUtils as ClassHelper. 
The implementation of this issue is available at https://github.com/apohllo/testng/tree/TESTNG-455

**Comment by missedone** [comment]
duplicates with https://github.com/cbeust/testng-eclipse/issues/133
can be closed

**Comment by Zlika** [comment]
I don't think this issue is related to #133.  #133 is about building the testng eclipse plugin with tycho, whereas this one (as I understand it) is about allowing tycho to use testng as a testing framework (currently tycho only supports junit).

**Comment by missedone** [comment]
right, i oversaw the original issue, we need reopen it

**Comment by krmahadevan** [comment]
Closing this out, since its now being tracked under https://github.com/cbeust/testng-eclipse/issues/448
