### ISSUE TITLE
Use default assertion failure message in SoftAssert

### ISSUE THREAD

**Issue by draghuram** [cbeust/testng#504]
My posting in the users list about this issue can be found here:
    https://groups.google.com/forum/#!searchin/testng-users/devarakonda/testng-users/Zn5A85lQNpI/s8xtpFWpsUwJ

Please take a look at the following groovy code:

```
import org.testng.asserts.SoftAssert

def softAssert = new SoftAssert()
softAssert.assertEquals(1, 2)
softAssert.assertEquals(3, 4, "test message.")
softAssert.assertAll()
```

Running this with testng 6.8.5 produces the following message:

"null, test message."

Notice that the failure of "softAssert.assertEquals(1, 2)" resulted in the message "null". I was expecting something like "expected [2] but found [1]" which is what a regular Assert would produce. 

It will be nice if SoftAssert can use a default assertion failure message when none is provided.

**Comment by jrocketz** [comment]
It doesn't appear as though the fix solved the issue. Here is the code that I used to test:
```java
import org.testng.Assert;
import org.testng.annotations.*;
import org.testng.asserts.SoftAssert;

public class TestAssert {
	
	@Test
	public void TestHardAssertEquals() {
		Assert.assertEquals(0,1);
	}
	
	@Test
	public void TestHardAssertBoolean() {
		Assert.assertTrue(false);
	}
	
	@Test
	public void TestSoftAssertion() {
		SoftAssert softAssert = new SoftAssert();
		softAssert.assertEquals(0,1);
		softAssert.assertTrue(false);
        softAssert.assertAll();
	}
	
}
```
And this is the result:
```
TestHardAssertBoolean	java.lang.AssertionError: expected [true] but found [false]
TestHardAssertEquals	java.lang.AssertionError: expected [1] but found [0]
TestSoftAssertion	java.lang.AssertionError: The following asserts failed:
null, null
```
I am using the following version of TestNG:
```
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.21</version>
    <scope>test</scope>
</dependency> 
```

**Comment by draghuram** [comment]
Are you sure? I just tested with your code and I see the following assert message for SoftAssert:

<pre>
FAILED: TestSoftAssertion
java.lang.AssertionError: The following asserts failed:
expected [1] but found [0], expected [true] but found [false]
</pre>

Perhaps, an older version of testng was getting used in your run?

**Comment by jrocketz** [comment]
I ended up purging my local maven repository and re-downloaded all the dependencies using this command:
```
mvn dependency:purge-local-repository
```
The only TestNG jar file that is now in my maven repository is `testng-6.8.21.jar` which is also what is listed under Maven Dependencies in Eclipse. I also opened up the `SoftAssert.class` from the `testng-6.8.21.jar` in Eclipse and verified that code change is there.
```
  public void assertAll() {
    if (! m_errors.isEmpty()) {
      StringBuilder sb = new StringBuilder("The following asserts failed:\n");
      boolean first = true;
      for (Map.Entry<AssertionError, IAssert> ae : m_errors.entrySet()) {
        if (first) {
          first = false;
        } else {
          sb.append(", ");
        }
        sb.append(ae.getKey().getMessage());
      }
      throw new AssertionError(sb.toString());
    }
  }
```
SoftAssert is still reporting `null`. I am executing the test suite from Eclipse. Is there something else that I can do to verify that I am on the latest version (6.8.21) of TestNG?

**Comment by draghuram** [comment]
This issue can perhaps be closed?

**Comment by jrocketz** [comment]
It turns out that it was a TestNG configuration issue in Eclipse. If you open the project properties and select the TestNG section, there is a checkbox for **Use project TestNG jar**. By default, it is unchecked. After checking it and re-running the tests, I now see the correct soft assertion errors. This issue can be closed.
