### ISSUE TITLE
@AfterTest in 6.8.8 is executed even after non @Test method

### ISSUE THREAD

**Issue by JeanVEGA** [cbeust/testng#507]
This fails my build:

<pre>
Failed tests:   tearDown(template.GuestMailTest): calling verify is not allowed in record state
</pre>

``` java
    @BeforeMethod
    public void setup() throws Exception {
        setUp();
    }

    @AfterTest
    public void tearDown() {
        EasyMock.verify(getMocks());
    }
```

The message means, that _EasyMock.verify()_ was called outside of a test, where I normally run _EasyMock.replay()_ before any testing.

Also judging by the message - it considers the _tearDown()_ method to be a @Test

With version _6.8.7_ this was working well and my build passed.

**Comment by krmahadevan** [comment]
If this is still a problem with TestNG latest version (`7.4.0` as of today), please help share a complete sample that can be used to reproduce the problem. Closing this issue.
