### ISSUE TITLE
Dependency outside of group throws a NullPointerException 

### ISSUE THREAD

**Issue by chesshir** [cbeust/testng#511]
Using version 6.8.7.  I've got code that looks like this:

@Test(groups = {"mygroup"})
public void MethodHead() {
...
}

@Test(dependsOnMethods = {"MethodHead"})
public void MethodMiddle() {
...
}

@Test(groups = {"mygroup"}
, dependsOnMethods = {"MethodHead", "MethodMiddle"}
, alwaysRun=true)
public void MethodTail() {
...
}

As you can see, MethodTail needs to run after MethodHead and MethodMiddle, but only if they actually get run.  It can just run without them, especially MethodMiddle.
This code setup runs just fine if all of the methods are run.  However, if I narrow down the tests to just those in the "mygroup" group, I get this error:

java.lang.NullPointerException
    at org.testng.DependencyMap.getMethodDependingOn(DependencyMap.java:58)
    at org.testng.TestRunner.createDynamicGraph(TestRunner.java:1061)
    at org.testng.TestRunner.privateRun(TestRunner.java:734)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

Any ideas on how to fix or workaround this problem?

**Comment by krmahadevan** [comment]
Attempted at recreating this issue using TestNG 6.12. Unable to reproduce. 
Following was what I used 

**Test class**
```java
import org.testng.annotations.Test;

public class Issue511TestclassSample {
    @Test(groups = {"mygroup"})
    public void methodHead() {
    }

    @Test(dependsOnMethods = {"methodHead"})
    public void methodMiddle() {
    }

    @Test(groups = {"mygroup"}, dependsOnMethods = {"methodHead", "methodMiddle"}, alwaysRun = true)
    public void methodTail() {
    }
}
```

**Test runner**
```java
import org.assertj.core.api.Assertions;
import org.testng.ITestNGListener;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlGroups;
import org.testng.xml.XmlRun;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Issue511TestRunner {
    @Test
    public void testMethod() {
        XmlSuite suite = new XmlSuite();
        suite.setName("suite");
        XmlTest test = new XmlTest(suite);
        test.setName("test");
        test.setXmlClasses(Collections.singletonList(new XmlClass(Issue511TestclassSample.class)));
        XmlGroups groups = new XmlGroups();
        XmlRun xmlRun = new XmlRun();
        xmlRun.onInclude("mygroup");
        groups.setRun(xmlRun);
        test.setGroups(groups);
        System.err.println(suite.toXml());
        TestNG testng = new TestNG();
        testng.setXmlSuites(Collections.singletonList(suite));
        TestListenerAdapter tla = new TestListenerAdapter();
        testng.addListener((ITestNGListener) tla);
        testng.run();
        List<String> methods = new ArrayList<>();
        for (ITestResult result : tla.getPassedTests()) {
            methods.add(result.getMethod().getMethodName());
        }
        Assertions.assertThat(methods).containsExactly("methodHead", "methodMiddle", "methodTail");
    }
}
```

**Output**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="suite">
  <test name="test">
    <groups>
      <run>
        <include name="mygroup"/>
      </run>
    </groups>
    <classes>
      <class name="com.rationaleemotions.github.issue511.Issue511TestclassSample"/>
    </classes>
  </test> <!-- test -->
</suite> <!-- suite -->


===============================================
suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================


===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by ranadinesh786** [comment]
issue :
=====
 How to solve NULLPOINTEREXCEPTION while using grouping concepts in POM with Extends Reporting ?


Solutions: 
======
	       1. Use below parameters to all the configuration annotations which we are using i.e. in base test;
		(alwaysRun = true)
		2. Use valid try catch block inside the page class and don’t use throws [incorrect exception]
		3. Use parameterized values instead of taking hardcode values inside the page or script.
