### ISSUE TITLE
Feature Request: Running several suite files in parallel from within testng.xml

### ISSUE THREAD

**Issue by ChristophSchaal** [cbeust/testng#512]
It should be possible to configure parallel execution of testng suite files inside testng.xml (similar to the command line option -suitethreadpoolsize) or via System Property (-Dsuitethreadpoolsize=3):

``` xml
<suite name="Suite1" verbose="1" >
  <suite-files suitethreadpoolsize="3">
    <suite-file>testng1.xml</suite-file>
    <suite-file>testng2.xml</suite-file>
    <suite-file>testng3.xml</suite-file>
  </suite-files>
</suite>
```

Advantage using system property:
- no TestNG dtd update necessary
- TestNG provider for maven surefire can use it, too
- small change in TestNG#runSuitesLocally() to use System Property if defined

**Comment by punitmishra** [comment]
@ChristophSchaal  Any updates or alternate solution to this?

**Comment by cktech529** [comment]
We seem to be having problems with running multiple suites in parallel as well.

**Comment by cbeust** [comment]
@ChristophSchaal No, this is not supported.

**Comment by iliagit** [comment]
@ChristophSchaal  Any updates on the requested feature?
