### ISSUE TITLE
TestNG does not load xml files inside jarfile

### ISSUE THREAD

**Issue by geoffreyzhang** [cbeust/testng#52]
Hi ,
I am using the version 6.0 , the behavior in this version is that :
      in the command " java -classpath XXXX-0.0.1-SNAPSHOT-jar-with-dependencies.jar -Dstp="$stp"  org.testng.TestNG $suite" , $suite is required to be a full path of a file in the disk .

```
  if you pass a jar file to testng in command line , it will only search the xml file named as testng.xml in the jar file .
```

Is it possible to add the feature to let testng support loading xml file with specified name inside jar file and run it ?

br,
geoffrey/

**Comment by CharmsStyler** [comment]
@cbeust  can we do this via maven ?

**Comment by cbeust** [comment]
@CharmsStyler Do what?

**Comment by CharmsStyler** [comment]
@cbeust  something like below. Say If I have a maven dependency which includes classes(on src/main) and Testng xml file. 
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.4.2</version>
				<configuration>
					<suiteXmlFiles>
						< xmlpathinjar>InsideJarTestng.xml</xmlpathinjar >
					</suiteXmlFiles>
				</configuration>
			</plugin>

**Comment by juherr** [comment]
@CharmsStyler
[apache/maven-surefire](https://github.com/apache/maven-surefire) is not managed by the TestNG community. [Ask them](https://issues.apache.org/jira/browse/SUREFIRE/) to add the support of xmlpathinjar. 

cc @Tibor17
