### ISSUE TITLE
run configuration overwritten

### ISSUE THREAD

**Issue by ekontothanasis** [cbeust/testng#520]
plugin: TestNG  6.8.6.20141201_2240
Version: Kepler Service Release 2
Build id: 20140224-0627

when right clicking one testng xml file in package explorer and choosing run as TestNG Suite, 
the run configuration VM arguments for this, are deleted.
This does not happen e.g. when running a Java application in the same way (by right clicking->run as Java app).
When using the run button from the run configuration this does not happen.

**Comment by krmahadevan** [comment]
Please retry using the latest released version of the TestNG eclipse plugin. If this is still a problem, please file an issue here https://github.com/cbeust/testng-eclipse/issues
