### ISSUE TITLE
TestNG 6.8 throws exception: org.testng.ITestNGListener: Provider test.serviceloader.TmpSuiteListener not found

### ISSUE THREAD

**Issue by gpawel** [cbeust/testng#522]
When testng task is executed from ant script it throws the following exception.
The discussion at https://groups.google.com/forum/#!msg/testng-users/N1X1oIMXXso/9ym9wmuLk9kJ does not help to re-solve the problem.

Exception:

   [testng] Exception in thread "main" java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider test.serviceloader.TmpSuiteListener not found
   [testng]     at java.util.ServiceLoader.fail(Unknown Source)
   [testng]     at java.util.ServiceLoader.access$300(Unknown Source)
   [testng]     at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
   [testng]     at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
   [testng]     at java.util.ServiceLoader$1.next(Unknown Source)
   [testng]     at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
   [testng]     at org.testng.TestNG.initializeConfiguration(TestNG.java:896)
   [testng]     at org.testng.TestNG.run(TestNG.java:1031)
   [testng]     at org.testng.TestNG.privateMain(TestNG.java:1364)
   [testng]     at org.testng.TestNG.main(TestNG.java:1333)

BUILD FAILED
C:\java\mfc\build.xml:57: The tests failed.

The butild file is here:
<?xml version="1.0" encoding="UTF-8"?>
<project name="Decorators_Test" default="Run_Suite" basedir="."> 

```
<tstamp>
    <format property="current.time"
     pattern="dd.MM.yyyy HH:mm" />
</tstamp>

<property name="etc" value="./etc" />
<property name="src" value="./src" />
<property name="lib" value="./lib" />
<property name="bin" value="./bin" />
<property name="report" value="./test-output" />
<property name="suitesPath" value="./test_suites" />

<path id="classpath">
    <pathelement location="${bin}" />
    <fileset dir="${lib}">
        <include name="**/*.jar" />
    </fileset>
    <fileset dir="${lib}/reportng/reportng-1.1.4">
        <include name="*.jar" />
    </fileset>
</path>

<target name="init">
    <delete dir="${bin}" />
    <mkdir dir="${bin}" />
   <delete dir="${report}" />
    <mkdir dir="${report}" />
   <delete file="jackrabbit.log_IS_UNDEFINED" />
</target>

<target name="compile" depends="init">
    <javac includeantruntime="false" srcdir="${src}" fork="true" destdir="${bin}">
        <classpath refid="classpath">
            <!--pathelement path="${bin}">
            </pathelement-->                
            <!--
            <fileset dir="${lib}">
                <include name="**/*.jar" />
            </fileset>
            -->
        </classpath>
    </javac>
</target>





<target name="Run_Suite" depends="compile">
    <echo>${browser}</echo>
    <echo>${suitesPath}/${suiteName}</echo>
    <taskdef resource="testngtasks" classpathref="classpath" /> 
    <testng outputdir="${report}" classpathref="classpath" haltonfailure="true" useDefaultListeners="false" listeners="org.uncommons.reportng.HTMLReporter" >
        <sysproperty key="browser" value="${browser}" />
        <sysproperty key="suiteName" value="${suiteName}" />
        <sysproperty key="propertiesFile" value="${propertiesFile}" />          
        <xmlfileset dir="${suitesPath}" includes="${suiteName}" />
    </testng>
</target>
```

</project>

**Comment by metacubeqa** [comment]
Just build the project in eclipse, using maven clean
And then it worked for me!!!

**Comment by krmahadevan** [comment]
Closing this issue based on the above comments.
