### ISSUE TITLE
Jenkins fails to compile newer updates of testNG if using the testNG method context.getFailedTests().removeResult(ITestResult) 

### ISSUE THREAD

**Issue by ajgwilli** [cbeust/testng#528]
Per the summary, Jenkins will fail to compile java code (using jdk 1.7 or 1.8) that utilizes the testing method context.getFailedTests().removeResults(ITestResult r).

In previous versions of testing (6.8.5 and back) this method only allowed for removing of ITestNGMethods, but recent updates have included removing ITestResults (http://grepcode.com/file/repo1.maven.org/maven2/org.testng/testng/6.8.8/org/testng/IResultMap.java#IResultMap.removeResult%28org.testng.ITestResult%29).

I am able to perform this function when compiling through Eclipse, but it will fail to compile when running through Jenkins (even though Jenkins is pointed at the correct jdk).

**Comment by krmahadevan** [comment]
Please retry using the latest released version of TestNG `6.14.3` and comment if this is still a problem.
