### ISSUE TITLE
generateReport() called multiple times for a single xml test suite.

### ISSUE THREAD

**Issue by agogs** [cbeust/testng#537]
I havea simple testng xml suite shown below.

```
<suite name="Demo Suite">

<test name="Demo1">
<classes>
<class name="foo.bar.Hello"></class>
</classes>
</test>

<test name="Demo2">
<classes>
<class name="foo.bar.HelloWorld"></class>
</classes>
</test>

</suite>

```

I have implemented IReporter in my own class called MyReporter and added this class as a Listener to my test class using @ Listeners annotation. After I run the testng xml, generateReport() is called twice. The javadoc says generateReport() is called after all the tests in the suite have run.

Is this expected behaviour or a know bug? I am using testng 6.8.8

**Comment by krmahadevan** [comment]
Closing this issue as stale issue. Please comment/add sample to reproduce if this is still a problem in TestNG `7.8.0` (latest released version)
