### ISSUE TITLE
eclipse plugin 20-60 times slower in eclipse 4.3 vs 3.7

### ISSUE THREAD

**Issue by willkil** [cbeust/testng#540]
My eclipse 4.3 installation is using TestNG plugin version 6.8.6.20141201_2240.

My eclipse 3.7 installation is using TestNG plugin version 6.8.1.20130330_0839.

One of my test classes with >90000 tests runs in 50 seconds from command line (mostly html reporter I think), 60 seconds in eclipse 3.7.2, but 3800+ seconds in eclipse 4.3.

In 4.3, Running 15000 do-nothing tests took 221996 ms according to the Results view. The following times are reported in the console for the same test run:
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@351563ff: 1347 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@b113622: 390 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@9a082e2: 1778 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@1f8b81e3: 2890 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@3b6f0be8: 95 ms

In 3.7, the Results view shows 8086 ms for the same 15000 do-nothing tests. The console output shows these times:
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@2ce1899b: 396 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@15aaf0b3: 1638 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@7f70888e: 949 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@60961dff: 2977 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@47d62270: 97 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms

I will email a sample eclipse project to the development list, however, this is the only class in my project:

    package demo.testng.eclipse;
    
    import java.util.Arrays;
    
    import org.testng.annotations.DataProvider;
    import org.testng.annotations.Test;
    
    public class EclipsePluginSlow {
        public static int COUNT = 15000;
        
        @DataProvider(name = "eclipsePluginSlow")
        public static Object[][] eclipsePluginSlowDataProvider() {
            Object[][] retVal = new Object[COUNT][];
            Arrays.fill(retVal, new Object[] { 0 });
            return retVal;
        }
    
        @Test(dataProvider = "eclipsePluginSlow")
        public void eclipsePluginSlow(int i) {
        }
    
    }

**Comment by missedone** [comment]
hi @willkil

thanks for reporting this and share your insight, 
please go ahead moving this discussion to testng-eclipse repo, and feel free to create Pull Request if you can fix it.
thanks

**Comment by juherr** [comment]
https://github.com/cbeust/testng-eclipse related issue. Please open a new issue there if the problem still exists.

**Comment by willkil** [comment]
Hi @missedone & @juherr,

I don't know whether or not the issue still exists and I haven't had a chance to check. I'm not going to open an issue if I don't know one exists, so I'll just leave this issue closed here until (unless) I find time to check.
