### ISSUE TITLE
stop TestNg execution, to close the streams

### ISSUE THREAD

**Issue by bogaty** [cbeust/testng#544]
After I have explicitly run the TestNg from Java code:
TestNG testng = new TestNG();
testng.run();

Files that are generated with TestNg can`t be removed, I think that may be related that some streams hasn`t been closed.
Currently invoke of Garbage Collector is helping me, but that is a horrible solution.
=(

**Comment by krmahadevan** [comment]
@bogaty - I can't seem to be able to reproduce this problem. If this is still an issue, please help add a sample and comment so that we can use that sample to reproduce the issue and get it fixed as well.
