### ISSUE TITLE
Weird @BeforeMethod and @AfterMethod behaviour with dependsOnMethods

### ISSUE THREAD

**Issue by mbocek** [cbeust/testng#550]
Sample code:

``` java
public class BeforeAfterMethodTest {

    @Test
    public void testWithoutBeforAndAfter() {
        System.out.println("testWithoutBeforAndAfter");
    }

    @Test
    public void test() {
        System.out.println("test");
    }

    @BeforeMethod(dependsOnMethods = "test")
    public void beforeMethod() {
        System.out.println("before");
    }

    @AfterMethod(dependsOnMethods = "test")
    public void afterMethod() {
        System.out.println("after");
    }
}
```

Result:

```
org.testng.TestNGException: 
test.BeforeAfterMethodTest.beforeMethod() is depending on method public void test.BeforeAfterMethodTest.test(), which is not annotated with @Test or not included.
    at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:111)
    at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:240)
    at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:317)
    at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:59)
    at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:191)
    at org.testng.internal.TestNGMethodFinder.getBeforeTestMethods(TestNGMethodFinder.java:64)
    at org.testng.TestClass.initMethods(TestClass.java:167)
    at org.testng.TestClass.init(TestClass.java:86)
```

Regarding documentation: 

> http://testng.org/javadoc/org/testng/annotations/BeforeMethod.html#dependsOnMethods()
> The list of methods this method depends on. There is no guarantee on the order on which the methods depended upon will be run, but you are guaranteed that all these methods will be run before the test method that contains this annotation is run. Furthermore, if any of these methods was not a SUCCESS, this test method will not be run and will be flagged as a SKIP. If some of these methods have been overloaded, all the overloaded versions will be run.

My expectation was that the before and after method will be run only before and after _test()_ method.
Please can you provide some fix or explanation.

Thank you.

**Comment by 573** [comment]
+1 @mbocek

**Comment by bredy** [comment]
+1 @mbocek

**Comment by krmahadevan** [comment]
@juherr - What do you think the behaviour here should be?

I can alter the implementation to throw an error that looks like below (for the same example test that is shared in this bug):

```
com.rationaleemotions.issue550.BeforeAfterMethodTest.beforeMethod() is configuration method that is depending upon non configuration methods.
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:148)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:303)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:397)
	at org.testng.internal.MethodHelper.lambda$collectAndOrderMethods$1(MethodHelper.java:75)
```

**Comment by krmahadevan** [comment]
> The idea is runs some specific setup/teardown operation before and after specific test method. This is the reason why i want to use this mechanism.

To achieve this, you can do something like below (My bad that this response is coming nearly 8 years after you mentioned the problem :) )

You can add `ITestNGMethod` as a parameter to the `@BeforeMethod` method and then inspect the parameter to check if it represents the method that you want to do a setup for (you can do that via either custom annotations which you can parse, or just by checking the method name)

**Comment by juherr** [comment]
@krmahadevan the exception message you propose is clearly better.

A similar check could be done for all methods that depend on methods of another type: test methods can only depend on test methods, but beforemethod can only depend on beforemethod too.

**Comment by krmahadevan** [comment]
> A similar check could be done for all methods that depend on methods of another type: test methods can only depend on test methods, but beforemethod can only depend on beforemethod too.

Yes, this goes without saying. There would be edit checks for each of the configurations that would validate the following:

1. `@Test` can depend only on other `@Test`
2. `@BeforeMethod` can depend on only another `@BeforeMethod` (and so on)
