### ISSUE TITLE
Eclipse plugin does not separate test results when using @Factory with DataProvider

### ISSUE THREAD

**Issue by jhalterman** [cbeust/testng#555]
When using a @Factory on a constructor along with a data provider, the tests are run once for each provided set of data but the results in Eclipse are not separated by each set of provided data in the same way that they are when using a dataProvider on a test method.

Displayed results should be separated when using a data provider with a Factory/constructor.

**Comment by krmahadevan** [comment]
Ported to https://github.com/cbeust/testng-eclipse/issues/453
