### ISSUE TITLE
Test Parameters not logged by Failure Reporter.

### ISSUE THREAD

**Issue by smaudet** [cbeust/testng#559]
After test failures from a test using a DataProvider, the failure reporter generates useless suite information.

Ideally there should be some mechanism to push failed parameters into the failure suite and run only those parameters with the failed methods.

Additionally, the code in FailureReporter should be audited, it appears to be doing several useless, wasteful operations.

**Comment by krmahadevan** [comment]
Revisited this using TestNG 6.12

> Ideally there should be some mechanism to push failed parameters into the failure suite and run only those parameters with the failed methods.

Here's the output of `testng-failed.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Failed suite [1020_suite]">
  <test name="Command line test 264a440b-83dc-42b8-8fc5-0e563f147c52(failed)">
    <classes>
      <class name="com.rationaleemotions.github.issue1020.Issue1020TestclassSample">
        <methods>
          <include name="testMethod" invocation-numbers="0 2 4 6 8"/>
        </methods>
      </class> <!-- com.rationaleemotions.github.issue1020.Issue1020TestclassSample -->
    </classes>
  </test> <!-- Command line test 264a440b-83dc-42b8-8fc5-0e563f147c52(failed) -->
</suite> <!-- Failed suite [1020_suite] -->
```

For a full reproducible test that was used to recreate this please see https://github.com/cbeust/testng/issues/1020#issuecomment-332401438
