### ISSUE TITLE
String cannot be cast to Integer if log property is set in maven pom.xml

### ISSUE THREAD

**Issue by iwanzarembo** [cbeust/testng#574]
Hi,  
I am using maven to run the TestNG tests. For this I created some suite.xml files like:  

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Suite Name" verbose="10" parallel="classes">
    <test name="Web Channel Tests for B2B">
        <packages>
            <package name="com.some.package" />
        </packages>
    </test>
</suite>
```

There I set the verbosity to 10, but the generated verbosity after running the test is 0.  
So I thought, I could set the verbosity from maven to 10. This is possible by setting the properties parameter 

``` xml
<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.16</version>
            <configuration>
                <properties>
                    <property>
                        <name>log</name>
                        <value>10</value>
                    </property>
                </properties>
                <suiteXmlFiles>
                    <suiteXmlFile>Some_suite.xml</suiteXmlFile>
                </suiteXmlFiles>
            </configuration>
        </plugin>
    </plugins>
</build>
```

Unfortunately TestNG dumps when reading this property, because the code in TestNG 6.8.7 looks like this:

``` java
   Integer verbose = (Integer) cmdLineArgs.get(CommandLineArgs.LOG);
    if (null != verbose) {
      result.verbose = verbose;
    }
```

The cast seems to be wrong there. The code for the threadcount setting (which can also be set by a maven property) has a conversion from String to int:

``` java
    String threadCount = (String) cmdLineArgs.get(CommandLineArgs.THREAD_COUNT);
    if (threadCount != null) {
      result.threadCount = Integer.parseInt(threadCount);
    }
```

Could you please fix the conversion of the log parameter or the generation of the correct verbosity from the initial suite.xml files?

My used versions:  
- maven-surefire-plugin 2.18
- TestNG 6.8.7

Thanks,

Iwan

**Comment by juherr** [comment]
I think it is a surefire issue. 

What do you think @Tibor17? Should a create an issue (or update [SUREFIRE-919](https://issues.apache.org/jira/browse/SUREFIRE-919))?
