### ISSUE TITLE
TestNG ignores timeOut parameter if in XML specified parallel="tests"

### ISSUE THREAD

**Issue by Mapyx** [cbeust/testng#575]
Here is my test
```java
public class TestTestNG {
    @Test(timeOut = 500)
    public void timeOutDoesNotWork() throws InterruptedException {
        TimeUnit.HOURS.sleep(Long.MAX_VALUE);
    }
}
```
and XML
```java
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="TestNG test" parallel="tests">
    <test name="Test TestNG" >
        <classes>
            <class name="ru.tpp.qadaemon.hermes.zigbee.TestTestNG" />
        </classes>
    </test>
</suite>
```

Test not fails by timeout
Affect vesions starting with 6.1

**Comment by juherr** [comment]
I didn't reproduce the problem with #735

**Comment by AvrahamAtia** [comment]
So when I executing parallel timeOut not working? I am use TestsNG 6.11

**Comment by krmahadevan** [comment]
@AvrahamAtia - Couple of things. 

1. Is this problem occurring in the latest released version of TestNG ? As of today its `6.14.3`.
2. If the problem continues to exist, please create a new issue and add a simple standalone test that can be used to reproduce the issue.

**Comment by AvrahamAtia** [comment]
@krmahadevan   I upgrade to 6.14.3, it is works fine!!!

**Comment by krmahadevan** [comment]
@AvrahamAtia - Awesome! Glad the issue is resolved for you

**Comment by AvrahamAtia** [comment]
:)
