### ISSUE TITLE
IRetryAnalyzer is broken

### ISSUE THREAD

**Issue by rschmitt** [cbeust/testng#583]
I tend to use a lot of TestNG's more advanced features for integration testing, and I'd really like to be able to use `IRetryAnalyzer` with inherently non-deterministic tests that can fail spuriously. Unfortunately that feature appears to be fundamentally broken because of how it was integrated with TestNG's various callback APIs:

* The Reporter(s) will be notified of each `FAILED` invocation attempt, even if the test method ultimately succeeds
* Similarly, the `ExitCodeListener` in `org.testng.TestNG` calls `m_mainRunner.setStatus(FAILED)` as soon as a test invocation fails (the test method's ultimate success does not matter), so TestNG will exit with a nonzero exit code (resulting in, for instance, the overall Ant or Maven task failing), even if you use one of the [hacks](http://stackoverflow.com/questions/11622365/testng-how-to-only-output-one-pass-fail-result-when-test-is-rerun) intended to fix the test report

I'm only aware of two ways around these fundamental deficiencies: reflection hacks to mutate the internal state of the `TestNG` instance, or writing a custom test runner to replace it.

I'm willing to do the design and coding work to fix this issue, but first I want to make sure everyone agrees with my statement of the problem.

**Comment by davefp** [comment]
I've recently run into the same issue. Our specific problem was that in addition to retries showing up multiple times in the report, the same retry handler is used across multiple runs of the test with different parameters using a data provider.

I'd love to see better support for the various possible configuration options.

**Comment by nmiroshnichenko** [comment]
Hi, how do you think about marking failed tests that are to be retried as 'SUCCESS_PERCENTAGE_FAILURE' and not 'SKIP' and test failed after the last retry - as usual 'FAILURE'?
In our tests we had to do this workaround, see inlined comments:
```
public class BaseTestngListener implements ITestListener, IInvokedMethodListener {
...
  @Override
  public void afterInvocation(IInvokedMethod method, ITestResult result) {
    if (method.isConfigurationMethod()
        && (result.getStatus() == ITestResult.FAILURE || result.getStatus() == ITestResult.SKIP)) {
      handleFailure(result);
    } else {
      // Workaround for testng behaviour (by the way, RetryAnalyzer feature is undocumented still).
      // TestNG marks a test to be retried as 'SKIP' and failed after retry - as 'SUCCESS_PERCENTAGE_FAILURE',
      // but it contradict 'invocationCount' feature that behave more intuitive
      // We simulate 'invocationCount' behaviour here:
      // a test to be retried is marked as 'SUCCESS_PERCENTAGE_FAILURE' (it should not look as skipped)
      // and failure after all retries must stay failure and not any special failure.
      final CommonRetryAnalyzer retryAnalyzer = (CommonRetryAnalyzer) result.getMethod().getRetryAnalyzer();
      if (retryAnalyzer != null) {
        // Here we try not to change "true skip" status for tests that are skipped due to config methods failures.
        // We think if result does not have any throwable it means the test didn't fail and was "truly skipped".
        if(result.getStatus() == ITestResult.SKIP && result.getThrowable() != null) {
          result.setStatus(ITestResult.SUCCESS_PERCENTAGE_FAILURE);
          Reporter.setCurrentTestResult(result);
        } else if (result.getStatus() == ITestResult.SUCCESS_PERCENTAGE_FAILURE) {
          result.setStatus(ITestResult.FAILURE);
          Reporter.setCurrentTestResult(result);
        }
      }
    }
```

**Comment by nmiroshnichenko** [comment]
And I think "failures-to-be-retried" should be reported (with some "non-final-failure-status"), user can ignore such status, but other users wish to track such non-final-failures. For example, we log such failures as ordinary failures (with stack traces and screenshots) with just a little (but clearly visible) addition to the message like "ERROR: Test <class.method(params)> failed but WILL BE RETRIED"

**Comment by bodaganj** [comment]
@nmiroshnichenko @davefp @rschmitt Hi Guys! Have You faced with such issue during using DataProvider with IRetryAnalyzer:

"I'm running into an issue with our test suite where my tests that use dataproviders are not using the original data parameter from the first run of the test when they get retried."

More information You could find here:
https://github.com/cbeust/testng/issues/763

Thanks in advance for Your help

**Comment by juherr** [comment]
@rschmitt Is #698 fixing this issue or do you want to keep it open for any reason?
