### ISSUE TITLE
Ability to Define Group Parameter with multiple included Suite-File

### ISSUE THREAD

**Issue by jmontanari** [cbeust/testng#589]
Problem:
If i run the Suite of suites specifying the Group parameter the field appears to be Ignored within each Suite.

Setup:
1 Suite that contains a bunch of other suites.
IE
`<suite-files>
		<suite-file path="xxx1.xml" />
		<suite-file path="xxx2.xml" />
...
</suite-files>`

I am defining Group Parameter Via Ant testng Task.
Each individual suite implements Tests and groups correctly.
If i run each Suite individually the Group parameter works as expected.
When i run the Suite of Suite the Group parameter appears to be ignored.

Has anyone else run into this and have a solution or workaround.

Bug #174 deals with 1 possible solution which i would rather be using and have had to work around for some time, Define Group at a Suite level and have all tests inherit.

**Comment by juherr** [comment]
@jmontanari Why did you close the issue? Did you find a solution?

**Comment by jmontanari** [comment]
@juherr  

I ended up coming up with a hack that works for me. Define the Suites with a Variable for the Run target. Then in ant create a method that Replaces the variables on demand with hard coded suites i want to run. It is far from ideal and ends up having to copy the Group Block to every individual suite to make it work. 


Define groups as Variables in the suite.xml
```
<test verbose="2" name="Something">
       <groups>
            <define name="All">
                <include name="Nightly"/>
            </define>
            <define name="Nightly">
                 <include name="Daily"/>
            </define>
			<run>
				<include name="@TESTGROUP@" />
			</run>
        </groups>
        <classes>
             <class name="something.Something"/>
        </classes>
</test>  
```

Then in ant i build a String replace function.
```
<target name="extractSuites" description ="Extract Suites with a Group -Dtest.group='Daily/Nightly/All' into the Suite Run directory">
		<!-- Set the Group to run. If no group set assume daily -->
	    	<condition property="test.group" value="${test.group}" else="All"><!-- Defnining Empty Group will run everything -->
	    		<isset property="test.group" />
	    	</condition>
		<!-- Create a temp Suite that has teh GroupFilled in -->
        <copy todir="${suite.run.dir}" overwrite="yes">
	        <fileset dir="${resources.dir}">
	              <include name="testng*.xml" /><!-- Search for anything in resource Directory with name starting with testng -->
	        </fileset>
	
	        <filterset>
				<filter token="TESTGROUP" value="${test.group}" />
			</filterset>

        </copy>
	</target>
```

**Comment by juherr** [comment]
@jmontanari fyi, #937 should fix your problem
