### ISSUE TITLE
RemoteTestNg#m_customTestRunnerFactory is not overrideable

### ISSUE THREAD

**Issue by yapith** [cbeust/testng#590]
TestNG version: 6.8.5

Context:
IntelliJ testNG runs with RemoteTestNG by default and it doesn't seem like you can override that easily.

Repro steps:
find code usages of RemoteTestNG.m_customTestRunnerFactory setters.

Actual:
It's only set in RemoteTestNG.buildTestRunnerFactory() to a built-in TestRunnerFactory. It's not really customizeable as the field name suggests.

Expected:
When -testrunfactory test parameter is specified for a custom TestRunnerFactory, RemoteTestNG picks it up.

**Comment by krmahadevan** [comment]
Closing this issue since the class in question is not something that is owned by/resides in the TestNG codebase
