### ISSUE TITLE
NoClassDefFoundError in TestNGClassFinder.<init>

### ISSUE THREAD

**Issue by aanno** [cbeust/testng#602]
With TestNG 6.8.21, I've got this mysterious error when I try to use the test from a maven run triggered with:

mvn cobertura:cobertura -Dcobertura.report.format=xml 

<code><pre>
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project nuclos-client: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/eclipse/jgit/api/errors/GitAPIException
[ERROR] at java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
[ERROR] at java.lang.Class.privateGetPublicMethods(Class.java:2733)
[ERROR] at java.lang.Class.getMethods(Class.java:1472)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:59)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:409)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:235)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:205)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:153)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:536)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:159)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
[ERROR] at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[ERROR] at org.testng.TestNG.run(TestNG.java:1057)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.api.errors.GitAPIException
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[ERROR] ... 22 more
</pre></code>

Even if I'm doing something nasty here, my feeling is that TestNG should recover for problem (and behave more gracefully): I don't want to do anything with org/eclipse/jgit/api/errors/GitAPIException (i.e. I'm not going to test it nor am I aware of that my tests have a dependency on this class).

In java NoClassDefFoundError is thrown when the classpath is not complete (i.e. GitAPIException is found, but it dependencies are not, it's a LinkageError). When scanning for tests, TestNG should simply emit a warning if a NoClassDefFoundError occurs, there is no need to bail out.

**Comment by cbeust** [comment]
Agreed, TestNG should catch this exception and exit more gracefully.

**Comment by juherr** [comment]
Issue closed by #603
