### ISSUE TITLE
Not able to install on eclipse 3.4+

### ISSUE THREAD

**Issue by qualityking** [cbeust/testng#619]
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://beust.com/eclipse/plugins/org.testng.eclipse_6.8.6.20141201_2240.jar.
Read timed out

**Comment by verhagen** [comment]
Have you tried again to install the TestNG plug-ins? As the mentioned time-out, for the jar, does not appear. I can download the jar.

__In case the problem still exsists__
- Which version and distribution of Eclipse do you use?
- What other plug-ins have you installed?

**Comment by qualityking** [comment]
I am able to install it now... wondering, I did not make any changes, anyways closing this issue, 

Thanks,
Manish Bansal
