### ISSUE TITLE
Running test in parallel 

### ISSUE THREAD

**Issue by qualityking** [cbeust/testng#622]
Hi Folks, 
I am using TestNG with eclipse plugin along with selenium 

the only reason I moved to TestNG is to use parallel running of my test cases, which anyways supported by Junit4+ but, reports were not getting generated out of it. 

Using TestNG that issues (reports related) looks like resolved but really speaking tests are not running in parallel, 

Issue is : 
it is launching 1 browser and waits for it to load and then opens another. 
when another browser is loading, it keeps on waiting once the 2nd browser load completed moves back to first 1 and performs operation. 

really speaking it is not doing in parallel, but using only 1 thread. 

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "TestNGdtd.dtd" >
<suite name="Sample Test suite demo" parallel="tests">

    <test name="Test Project1">
        <classes >
            <class name="Project1.TestCase1"></class>
            <class name="Project1.TestCase2"></class>
        </classes>
    </test>

    <test name="Test Project2">
        <classes >
            <class name="Project2.TestCase1"></class>
            <class name="Project2.TestCase2"></class>
        </classes>
    </test>
</suite>
```

am i missing something, here ? or this is a issue with TestNG

**Comment by krmahadevan** [comment]
Not much information is provided to debug this. Closing this issue. Please feel free to re-open if this is still a problem (but please add more context along with sample tests)
