### ISSUE TITLE
Failing by throwing an FailException extending SkipException

### ISSUE THREAD

**Issue by jinahya** [cbeust/testng#623]
I just found that an extended exception whose `isSkip` returns `false` will be helpful.

````
// final Some some = getSome();
// Assert.assertNotNull(some, "not present");

final Some some
    = Optional.ofNullable(getSome())
    .orElseThrow(() -> new FailException("not present");
````
I, as documented, already know that extending `SkipException` is so free.
Can it be acceptable that adding a  class like this?
````
// an extended exception for failing
public class FailException extends SkipException {
    @Override
    public boolean isSkip() {
        return false;
    }
}
````

**Comment by juherr** [comment]
Why don't you just write:
```
final Some some
    = Optional.ofNullable(getSome())
    .orElseThrow(() -> new WhatEverException("not present");
```
Your test case won't be skipped but failed. Is it the expected behavior?

**Comment by jinahya** [comment]
Yes, actually. It will be more elegant if any predefined exception such as `FailException` is available rather than `WhatEverException` or `RuntimeException`.

**Comment by drapostolos** [comment]
It makes sense for an `Apple.class` to extend a `Fruit.class` as an apple is a Fruit. But a Failure verdict is not a Skip verdict, so I don't think it makes sense for a `FailException` to extend a `SkipException`.

Another option is to use the [assertJ](http://joel-costigliola.github.io/assertj/) library and write as follow:


```java
import static org.assertj.core.api.Assertions.assertThat;

// Omitting class/method names etc.

assertThat(getSome()).isNotNull();
```

**Comment by cbeust** [comment]
Agree with @drapostolos, `FailException` should not extend `SkipException`. I'm not sure I see the point of a `FailException` as well: just throw your own.

**Comment by jinahya** [comment]
I can't help but wanting `FailException`. Sorry.
```java
    // a utility method for integration tests
    // this method doesn't throw IOException
    static <R> R status(final HttpURLConnection connection,
                        final BiFunction<Integer, String, R> function) {
        try {
            final int statusCode = connection.getResponseCode();
            final String reasonPhrase = connection.getResponseMessage();
            return function.apply(statusCode, reasonPhrase);
        } catch (final IOException ioe) {
            fail("failed to read status", ioe);
            //throw new FailException(ioe);
            throw new RuntimeException("fail to read status", ioe);
        }
    }
```

**Comment by juherr** [comment]
Why not just making `FailException extends RuntimeException` yourself?

**Comment by jinahya** [comment]
@juherr Indeed.
