### ISSUE TITLE
Add documentation of @Test(retryAnalyzer)

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#646]
I'm trying to fix #604 but I don't understand how the feature should work (and the current tests of the feature are not clear enough).

Could you explain the feature ?

**Comment by rschmitt** [comment]
This sounds like a duplicate of https://github.com/cbeust/testng/issues/583. IRetryAnalyzer clearly was not thought through.

**Comment by juherr** [comment]
I prefer to see it like an add. 

Unlike you, I don't know how the feature should work ;) 
BTW, you look like the man of the situation! 
Could you help me to write the doc and close this issue?

**Comment by cbeust** [comment]
I've been wanting to revamp the implementation of `IRetryAnalyzer` for a long time but  never got around to it, so I'm not sure it's worth spending too much time on this right now...

**Comment by juherr** [comment]
Duplicate of #396
