### ISSUE TITLE
Do not require JCommander when run via Ant

### ISSUE THREAD

**Issue by stephen-smith** [cbeust/testng#651]
See #255.  I can't currently use TestNG because we are doing Ant builds, and fetching dependencies from a private maven repository that does not contain JCommander.

**Comment by stephen-smith** [comment]
Well, this is probably going to cause me to switch back to JUnit. JCommander is not available via our private dependency management system and it serves up the maven jar for testng (and no others).

It's unclear why to me why the ant task needs a command-line processor.

**Comment by cbeust** [comment]
I'm not sure what the problem is...

**Comment by stephen-smith** [comment]
I'm using ant, but I am unable to require JCommander as a dependency -- it's not available from the build servers that only have access to our private maven repository.  So, due to the ant task requiring a command-line processor (huh?) I am unable to use TestNG.

For now, I am continuing to use JUnit.  I mainly left the comment to prevent myself from trying TestNG again until after we switch build systems away from Ant.

**Comment by cbeust** [comment]
I don't see any dependency of `TestNGAntTask` on `JCommander`, what am I missing?

Besides, can't you bring JCommander into your private Maven repo?

**Comment by stephen-smith** [comment]
When I run the testng ant task without including JCommander in the class path, I get the same error listed in #255: 

[testng] java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException [testng] Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException [testng] at java.net.URLClassLoader$1.run(URLClassLoader.java:202)

As far as adding it to the maven repo, our project doesn't have authorization to do that, but it is something I've considered for the future.

**Comment by cbeust** [comment]
Note that it's a `NoClassDefFound`, not a `ClassNotFound`, so JCommander is on the class path.

**Comment by stephen-smith** [comment]
It's both.  NoClassDefFoundError was caused by "java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException"

**Comment by juherr** [comment]
Currently and as I understand, `TestNGAntTask` is just building a command line for `TestNG` which will be parsed by JCommander then.
So, JCommander is mandatory for the ant task. 
I should be possible to remove the dependency but won't be an easy task (and not a priority IMO).
