### ISSUE TITLE
Suite duration not correct for parallel tests

### ISSUE THREAD

**Issue by Zpetkov** [cbeust/testng#670]
When running tests in a suite the total duration of the suite is the sum of each test's duration which is not correct for tests executed in parallel.

Here is a sample test class:

```
package zpetkov.java;

import java.util.Date;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class ParallelTestNG {

   @BeforeClass
   public void beforeClass() {
      System.out.println("Start: " + new Date());
   }

   @AfterClass
   public void afterClass() {
      System.out.println("End: " + new Date());
   }

   @Test
   public void test1() throws InterruptedException {
      Thread.sleep(5000);
   }

   @Test()
   public void test2() throws InterruptedException {
      Thread.sleep(5000);
   }

   @Test()
   public void test3() throws InterruptedException {
      Thread.sleep(5000);
   }

   @Test()
   public void test4() throws InterruptedException {
      Thread.sleep(5000);
   }

}
```

The suite:

```
<?xml version="1.0" encoding="UTF-8"?>
<suite name="Suite" verbose="1">
    <test name="Test" parallel="methods" thread-count="5">
        <classes>
            <class name="zpetkov.java.ParallelTestNG" />
        </classes>
    </test>
</suite>
```

Running this you should get output:

```
Start: Sun May 03 15:31:45 EEST 2015
End: Sun May 03 15:31:50 EEST 2015

===============================================
Suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================
```

Looks like total duration is 5 seconds, but this is what eclipse shows:

![suite duration](https://cloud.githubusercontent.com/assets/7465412/7445045/8dbf6f8e-f1aa-11e4-836d-533a76c55d06.jpg)

**Comment by cbeust** [comment]
It works for me:

```
Start: Sun May 03 09:13:34 PDT 2015
End: Sun May 03 09:13:39 PDT 2015
PASSED: test3
PASSED: test4
PASSED: test1
PASSED: test2
```

The screenshot you are showing is a bit odd: the green bar does show that the 4 methods ran in 5 seconds but the tree is claiming 20 seconds. Not sure what to make of that, did the tests really take 20 seconds to run?

**Comment by Zpetkov** [comment]
Im pretty sure the whole suite does not take 20 seconds, it just reflects the sum of the durations.

**Comment by cbeust** [comment]
Oh so you were just reporting the fact that the Eclipse plug-in is reporting incorrect times, got it.

**Comment by krmahadevan** [comment]
ping @missedone - Nick can you please help take a look at this and advice if this is still a problem with the eclipse plugin ?

**Comment by missedone** [comment]
yes, looks like an issue in Eclipse Plugin:
* https://github.com/cbeust/testng-eclipse/blob/master/testng-eclipse-plugin/src/main/org/testng/eclipse/ui/tree/SuiteTreeItem.java#L42
* https://github.com/cbeust/testng-eclipse/blob/master/testng-eclipse-plugin/src/main/org/testng/eclipse/ui/tree/BaseTreeItem.java#L38

will try to fix it.

**Comment by krmahadevan** [comment]
Closing this issue since its a problem with the eclipse plugin that is being tracked separately.
