### ISSUE TITLE
TestNG is not reporting any log for skip tests. 

### ISSUE THREAD

**Issue by abhilekhsingh** [cbeust/testng#674]
TestNG is not reporting any log for skip tests. I checked the throwable of ITestResult object but it is null.
Is there anyway I can get logs for the skip tests for why it is getting skipped.

**Comment by juherr** [comment]
Skip tests are consequence of failed tests. You may have some dependencies between tests and when one fails, the following ones are skipped.

**Comment by abhilekhsingh** [comment]
is there anyway I can get the proper cause for skipped tests.

**Comment by juherr** [comment]
I don't know a way to know the cause of skipped tests. 
And as I understand the code, it won't be easy to solve it.

**Comment by dhirenmudgil** [comment]
@juherr I have a throwable set if something break in @beforeTest or @beforeClass method. But i am not able to get that throwable in ITestResult instance in case of skip test.

It return throwable as null. Can you please fix this bug as i need to log what exactly failed in case of skip and i have custom exception from where i need to log things.

**Comment by juherr** [comment]
@dhirenmudgil Could you share a sample?

**Comment by dhirenmudgil** [comment]
In test class 
`
 @BeforeClass
    public void beforeClass() throws Exception {
        throw new Exception("abcd");
    }
`
In Listener class 
`
public class Reporter implements IReporter {
    public void generateReport(List<XmlSuite> list, List<ISuite> list1, String s) {
        for (ISuite suite : list1) {
            Map<String, ISuiteResult> result = suite.getResults();
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                IResultMap skippedTests = context.getSkippedTests();
                for (ITestResult result1 : skippedTests.getAllResults()) {
                    Throwable throwable = result1.getThrowable();
                    // Here the throwable is null
                    
                    System.out.println("Throwable value "+throwable);
                }
            }
        }
    }
}
`

**Comment by juherr** [comment]
@cbeust What do you think?

**Comment by dhirenmudgil** [comment]
@cbeust @juherr Please suggest something as need your help :(

**Comment by juherr** [comment]
`ITestResult` is designed for `@Test` methods, not for configuration methods (`@BeforeX` or `@AfterX`).

I didn't check, but custom [`IInvokedMethodListener`](http://testng.org/javadocs/org/testng/IInvokedMethodListener.html) may work and provides the expected exception.

**Comment by cbeust** [comment]
Looks like a bug.

-- 
Cédric

**Comment by dhirenmudgil** [comment]
@juherr @cbeust When we can expect a fix for the same.

**Comment by juherr** [comment]
The best way is trying to propose a fix with its test(s) by yourself. It is faster for us to review code.

**Comment by dhirenmudgil** [comment]
@juherr @cbeust I tried and was not able to fix the same :( . Please mark this as bug and if you can pic this up on priority it would be a great help!!!!

**Comment by krmahadevan** [comment]
@dhirenmudgil - I have tried fixing this with a PR. Lets wait for @cbeust / @juherr to get time to take a look and help review it.

**Comment by dhirenmudgil** [comment]
@krmahadevan Thanks for your support.

**Comment by dagansandler** [comment]
I know this is an old an resolved issue, but I'd like to comment that with the accepted solution, there is now no way to tell that the throwable in the test result comes from a previous configuration method, unless you start analyzing the stack trace.

**Comment by juherr** [comment]
@dagansandler Could you open a new issue?

**Comment by dagansandler** [comment]
Sure
