### ISSUE TITLE
Calling of methods from testng.xml

### ISSUE THREAD

**Issue by SwastikGanguly** [cbeust/testng#685]
testng: testng-6.8.8
selenium: 2.45
jdk 1.8
Unable to call Parent Method while multiple 'class' are addressed from testng.xml.
Works fine with single 'class' and its parent call.

**Comment by juherr** [comment]
@SwastikGanguly Could you give us a runnable project of the use case? A link to a github repo will help us to understand the problem and fix it.
Or maybe, you can pull-request a new test (or update a current one) to TestNG?

**Comment by SwastikGanguly** [comment]
Methods could be reference by 'Methods', tag, and 'Include' , 'name' and 'parameter'. Thanks.

**Comment by missedone** [comment]
here is an example of calling a test method `com.example.Test#testMethodName(param1, param2)` in testng.xml:
```xml
  <test name="TEST_NAME" >
    <parameter name="param1" value="val1" />
    <classes>
       <class name="com.example.Test">
       <methods>
        <parameter name="param2" value="val2"/> 
        <include name="testMethodName" />
       </methods>
       </class>
    </classes>
  </test>
```

**Comment by juherr** [comment]
@SwastikGanguly Even 2 years later, your request is not clear. :/
But I hope @missedone gave you the answer you expect.
