### ISSUE TITLE
IAnnotationTransformer.transform is called for methods with testClass populated

### ISSUE THREAD

**Issue by lqc** [cbeust/testng#686]
It seems that since e7eac6a (issue #87), JDK15AnnotationFinder always calls transformers with testClass populated in spite of the documentation:

https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/IAnnotationTransformer.java#L16-L22

**Comment by cbeust** [comment]
@juherr Can you take a look?

**Comment by juherr** [comment]
@cbeust Ok, I will update the javadoc.

**Comment by lqc** [comment]
It's quite a large backwards incompatible change for someone who is using IAnnotationTrasformer. What is the new way of checking that the annotation was written on class vs. annotation was written on a method? I will be happy to write some tests for this, but I need to know if this was a deliberate change or just an accident (seems like the latter).

**Comment by juherr** [comment]
True, I see the problem now! :)

**Comment by cbeust** [comment]
Yes, sorry that's what I meant. This behavior must be preserved: only one of these three parameters must be non null.
