### ISSUE TITLE
<groups> at <suite> level not applied to <suite-files>

### ISSUE THREAD

**Issue by kunal546** [cbeust/testng#689]
I want to be able to apply group filtering to multiple suite files.

Use Case - Let's say, I have multiple test suites defining all the tests. I want to run a subset of those on our dev environment and a subset on test environment. (I may want to do this for more environments in future). I am trying to achieve this by creating a suite file for every environment and invoking the one depending on the execution environment.

E.g. file dev-env-suite.xml -
```xml
<suite name="Dev environment">
    <groups>
        <run>
            <include name="dev" />
        </run>
    </groups>
    <suite-files>
        <suite-file path="suiteA.xml"></suite-file>
        <suite-file path="suiteB.xml"></suite-file>
    </suite-files>
</suite>
```

But the <groups> filtering does not seem to get applied to tests within the <suite-files>. Is this by design and intentional?

**Comment by juherr** [comment]
Dupliate of #589

**Comment by JustAlexOne** [comment]
Is there an update for this issue. We do also have the problem with this, and would be very happy it worked.

**Comment by cbeust** [comment]
@juherr Any thoughts on this?

**Comment by juherr** [comment]
@cbeust No, I didn't have a look yet.

**Comment by JustAlexOne** [comment]
Oh, thank you for your reply! Hope you'll implement this feature soon!
