### ISSUE TITLE
Add arbitrary number of environment variables in testNg ant build.xml

### ISSUE THREAD

**Issue by abhilekhsingh** [cbeust/testng#692]
TestNg provides support of setting environment variables in ant task.
<env key="key" value="${value}"/>

But in may case I have arbitrary list of environment variables. Is there any way I can do this.
Anyone please help me in this.

**Comment by krmahadevan** [comment]
@juherr - Any idea on what this issue is all about ?

**Comment by juherr** [comment]
@krmahadevan No idea.

**Comment by krmahadevan** [comment]
@juherr - Should we close this off and ask the requester to re-open if they can provide additional details ?

**Comment by juherr** [comment]
@krmahadevan yes

@abhilekhsingh If your need still exists, could you explain more?
