### ISSUE TITLE
Redirect testng.org/javadoc to an always up2date service

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#715]
Javadoc.io provides an up2date javadoc from artifacts deployed on Maven Central.
Using it will avoid to have top update javadoc by hand.

The only thing to do is making a redirection from http://testng.org/javadoc/ to http://www.javadoc.io/doc/org.testng/testng/

**Comment by cbeust** [comment]
Great idea, done!

**Comment by juherr** [comment]
Oops, I think it should be done for http://testng.org/doc/javadocs/ too

BTW, I've just seen that links from documentation like http://testng.org/javadocs/org/testng/IAnnotationTransformer.html are not working anymore and should be redirected to http://www.javadoc.io/doc/org.testng/testng/org/testng/IAnnotationTransformer.html.
But this link is not working either...
I've just send a email to javadoc.io owner to ask him if he see a solution which can help us.

**Comment by cbeust** [comment]
Indeed. Going to restore the local javadocs for now.

**Comment by juherr** [comment]
@Grogs Do you think you could help us with that?

We'd like http://www.javadoc.io/doc/org.testng/testng/org/testng/IAnnotationTransformer.html to be redirected to the latest version of the class documentation.

I wrote a proxy few months ago (https://github.com/juherr/javadocio-proxy) but it will be awesome if the feature is build-in javadoc.io itself.
For example: https://javadocio-proxy.herokuapp.com/org.testng/testng/org/testng/IAnnotationTransformer.html

**Comment by juherr** [comment]
I've just found another service which is exactly doing what we expect: https://jitpack.io/com/github/cbeust/testng/master-SNAPSHOT/javadoc/

https://jitpack.io/com/github/cbeust/testng/master-SNAPSHOT/javadoc/org/testng/IAnnotationTransformer.html

**Comment by charpov** [comment]
Doesn't seem to be working right now.  The javadoc link on the main testng.org page is broken.

**Comment by juherr** [comment]
Already fixed by https://github.com/testng-team/testng-team.github.io/pull/21 but @cbeust has to deploy the modification.

**Comment by cbeust** [comment]
@juherr That PR is merged, doesn't it automatically get deployed?

**Comment by juherr** [comment]
@cbeust Not yet because testng.org DNS entries don't point GitHub pages.

**Comment by cbeust** [comment]
Ah yes, and they won't. I don't want to depend on external web sites for this.

**Comment by juherr** [comment]
It's just another kind of hosted services. But I respect your choice. :)
