### ISSUE TITLE
add exception verification support

### ISSUE THREAD

**Issue by revof11** [cbeust/testng#716]
# Exception Verifier Feature Request

## Request
Currently we can use `expectedExceptions` in order to ensure we get an exception type.  However, in cases where there are simple parameters or message information we want to check as well.

## Example
As an example, take [RESTEasy](http://resteasy.jboss.org)'s `WebApplicationException` and Spring's equivalent exception types.  These classes allow you to specify things like `HttpURLConnection.HTTP_BAD_REQUEST` and `HttpURLConnection.HTTP_NOT_FOUND` (400 and 404, respectively) that it would be convenient to be able to check without having to write and duplicate a try/catch block multiple times.

## Notes
* Not sure the best way to accomplish this but would be happy to collaborate on a design
* Could possibly introduce simple annotation support such as:
  * Annotation signature: `@ExceptionVerifier(name = String, parameters = Object[])`
  * Annotation with optional _name_ used on method
  * Annotation added to test method with _parameters_ providing any incoming arguments to the method invocation

## Sample
```
@Test (expectedExceptions = WebApplicationException.class)
@ExceptionVerifier (name = "webExceptionVerifier", parameters = {HttpUrlConnection.HTTP_NOT_FOUND})
public void testSomeWebCall() {
  // ...
}

@ExceptionVerifier (name = "webExceptionVerifier")
public void verifyWebException(WebApplicationException e, int statusCode) {
  Assert.assertEquals(e.getResponse().getStatus(), statusCode, "Invalid HTTP Response Code");
}
```

**Comment by Bobnix** [comment]
:+1: I cant tell you the number of times I have had to write try catch blocks to verify information in an exception when the annotation better describes the point of the test (i.e. I am a test for this exception).

**Comment by juherr** [comment]
What do you think about something like:

```
@Test (expectedExceptionsHolder = MyExpectedExceptionsHolder.class)
@ExpectedStatusCode(HttpUrlConnection.HTTP_NOT_FOUND) // your own annotation
public void testSomeWebCall() {
  // ...
}

static class MyExpectedExceptionsHolder implements ExpectedExceptionsHolder {
   
    public void isExpectedException(ITestNgMethod method, Throwable ite) {
       ExpectedStatusCode expectedStatusCode = ...;
       if (!(ite instanceof WebApplicationException) || expectedStatusCode == null) {
            throw ite;
       }
       WebApplicationException webException = (WebApplicationException) ite;
       Assert.assertEquals(webException.getResponse().getStatus(), expectedStatusCode.statusCode(), "Invalid HTTP Response Code");
    }
}
```

I think it is closer than the current implementation of custom things like dataProvider or retryAnalyzer, and it should be easy to implement it without changing too many things in TestNG.

**Comment by rschmitt** [comment]
@revof11, are you using Java 8? If not, would this still be a complaint if you could use higher-order functions with your assertions?

**Comment by rschmitt** [comment]
Here's what I'm thinking. We can add some very simple convenience methods to org.testng.Assert:

```java
// First things first: let's add assertion methods for basic parity with @Test(expectedExceptions = ...)
public void assertThrows(Callable<?> callable);
public void assertThrows(Callable<?> callable, String message);
public void assertThrows(Callable<?> callable, Class<? extends Throwable> expectedException);
public void assertThrows(Callable<?> callable, Class<? extends Throwable> expectedException, String message);

// Now, let's generalize this by using org.testng.internal.Invoker.Predicate:
public void assertThrows(Callable<?> callable, Predicate<? super Throwable> exceptionDecider);
public void assertThrows(Callable<?> callable, Predicate<? super Throwable> exceptionDecider, String message);
```

These methods can obviously be added to the current TestNG (which targets Java 7), but they'll be highly ergonomic to anyone using Java 8. For instance:

```java
@Test
public void testSomeWebcall() {
    // ...
    assertThrows(client::invoke, e -> e.getResponse().getStatus() == 500);
}
```

**Comment by revof11** [comment]
@rschmitt Yes I am.  That is not even something I thought of.  Perhaps we can get something like those base-level assertions added because that is EXTREMELY clean and very straight forward to follow.

@juherr That is extremely flexible and I like that type of design.

**Comment by rschmitt** [comment]
@revof11 I'm working on an implementation currently; I'll have a PR out soon.

**Comment by juherr** [comment]
@rschmitt I like the idea of assertion too but there is no need to add them in testng because the awesome assertj already provides something: http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion

@revof11 I think assertj could solve most of your problems. You should try it ;)

**Comment by rschmitt** [comment]
@juherr I'm very skeptical of the idea that I need an embedded domain-specific language with a fluent builder API in order to perform these sorts of very simple comparisons. Can't we just call functions? It's one thing if you're working around the crippling limitations of older versions of Java, but in Java 8 you're just adding needless complexity. Here's AssertJ:

```java
@Test
public void testException() {
   assertThatThrownBy(() -> { throw new Exception("boom!") }).isInstanceOf(Exception.class)
                                                             .hasMessageContaining("boom");
}
```

Here's TestNG with assertThrows:

```java
@Test
public void testException() {
   assertThrows(() -> throw new Exception("boom!"), e -> e.getMessage().contains("boom")
                                                      && e instanceof Exception.class);
```

**Comment by revof11** [comment]
@juherr I have to agree with @rschmitt on this one.  The other thing is pulling in yet _another_ dependency to support.  Sure it's easy with Maven and all, but adding something simple with the lambda really hits the nail on the head.  That being said, however, take a look at AssertJ to see what else it might have to offer.

**Comment by juherr** [comment]
We are talking about tests. Not sure trying to limit the number of dependencies has a real interest. 

In fact, I'm not sure the top priority of testng is to be competitive on the assert API when some other projects are already doing it very well. 
But it doesn't mean we should refuse pr on this subject ;p
@cbeust what is your opinion?

**Comment by rschmitt** [comment]
The purpose of `assertThrows` is not to compete with [outdated](http://blog.jooq.org/2014/05/30/java-8-friday-most-internal-dsls-are-outdated/) DSL-based gimmick libraries, but rather to provide a vanilla assertion function that can be reused and composed with other things. This is not merely a matter of programmer convenience or verbosity reduction, either: I've seen people hand-write manual exception verification over and over again, and I've seen people get it wrong every way you can possibly get it wrong. Even I got the initial cut of `assertThrows` wrong (I was calling `Assert#fail` from inside the `try` block).

There's a great talk by Rich Hickey that points out programmers' tendency to choose superficial convenience and ease-of-use over reusability and composability: http://www.infoq.com/presentations/Simple-Made-Easy

**Comment by cbeust** [comment]
My overall feeling is that you can achieve a great deal of flexibility with just a custom layer without having anything (or much) to add to TestNG. When it comes to verifying that the exception is exactly what you expect it to be, you quickly reach a point where there is no other way than writing some Java code yourself. Trying to bake this in TestNG will be very limited in scope.

I drew the line at

1. the type of the exception
2. a regexp on the message

I think anything beyond that should be implemented by the user (and it's pretty trivial these days as pointed out in this thread: Java 8 closures, AssertJ, etc...).
