### ISSUE TITLE
Testng xml file running classes out of order with 

### ISSUE THREAD

**Issue by dcihal** [cbeust/testng#721]
I have a testng file that acts differently sometimes even though nothing has changed inside the file.  I am running it grouped by classes with `preserve-order` set to `true`.  For some reason it will sometimes run out of class order and based on the priority inside the tests instead.  For instance, the tests below will run `com.test.termsOfService` first and then skip to `com.test.addCategory` rather than running `com.test.billPayEnrollment`.

Shouldn't the tests run by class first and then by the priority within the class order?

```
<suite name="Company Smoke Tests" verbose="2">
<parameter name="WebdriverTimeout" value="30"></parameter>
<parameter name="baseConsumerUrl" value="http://local.test.url/"></parameter>
	<test name="Smoke Tests" preserve-order="true">
		<groups>
			<run>
				<include name='smoke'/>
			</run>
		</groups>
  		<classes>
  		  	<class name="com.test.termsOfService"></class>
  	  		<class name="com.test.billPayEnrollment"></class>
		  	<class name="com.test.addSubcategory"></class>				
   			<class name="com.test.addCategory"></class>
   	                <class name="com.test.changeCategory"></class>
   			<class name="com.test.changeCategorySaveChanges"></class>
   			<class name="com.test.deleteCategory"></class>
   	    </classes>
    </test>
</suite>
```

**Comment by rschmitt** [comment]
Do you mean the `priority` field in the `@Test` annotation? Is the interaction between `preserve-order` and `priority` documented?

**Comment by dcihal** [comment]
Yep, so the priorities within the classes start at 1 every time since they should be running in class order, but sometimes the tests will run based on priority instead of the class order. 

When you say is the interaction between `preserve-order` and `priority` documented what do you mean?  I have the reports that show the order running differently despite the file being the same, if that's what you mean.

`@Test(priority = 39, groups = {"smoke"}`

**Comment by dbrusilovsky** [comment]
In my experience so far, the only way to be certain that the methods inside a class run in the designated order is to mandate that order via dependencies. Or rather, in fiddling with preserve-order, I found that it provided not guarantee that the order of the functions would be, in fact, preserved. 
That said, I may just be misunderstanding the way the preserve-order arg is supposed to work.

**Comment by nirmitsrivastava** [comment]
I am facing the same problem for my project. The preserve-order works sometime and sometimes it doesn't. Its been over a year for this issue. Is there a fix for this ?

**Comment by dbrusilovsky** [comment]
From a purist perspective, test order shouldn't matter. In practice, I think I ended up using Requires/DependsOn in my tests to make it work.

**Comment by juherr** [comment]
It should be fixed in the next release: https://github.com/cbeust/testng/pull/1158
And it is already available in the snapshot version if you want to try it.

**Comment by nirmitsrivastava** [comment]
@dbrusilovsky  I know the order should not matter, but when the sign-in and sign-up are themselves testcases, then the order matters. PS: Am i doing it right ? 
@juherr  Thankyou for quick response.

**Comment by snovshadyan** [comment]
I was having the same problem. It's a bug in TestNG. But when I used version 7.0.0-beta3 it worked fine.

<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.0.0-beta3</version>
    <scope>test</scope>
</dependency>
