### ISSUE TITLE
Publish regular snapshots to Maven

### ISSUE THREAD

**Issue by rschmitt** [cbeust/testng#725]
I wanted to create an issue to track this so that it doesn't get lost in the shuffle from Maven to Gradle. The current 6.9.5-SNAPSHOT seems to be pretty old.

**Comment by rschmitt** [comment]
I assume that this can be done directly from Travis, right?

**Comment by cbeust** [comment]
I just uploaded a new snapshot:

https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/

Yes, it can be done from Travis but I need to configure it with the correct credentials, I've been meaning to do that for a while.

**Comment by cbeust** [comment]
Done: I configured Travis to automatically upload snapshots to Sonatype.
