### ISSUE TITLE
Issue in TestNG plugin issue using Selenium Webdriver.

### ISSUE THREAD

**Issue by raghav2329** [cbeust/testng#726]
![testng plugin issue](https://cloud.githubusercontent.com/assets/12811132/8054280/24b13540-0eb5-11e5-9b9c-e55b35fd1691.jpg)
 Hello,
  After creating the script in Testng using webdriver and clicking on Runas-> TestNG , i am getting plugin issue. Please find the attachment.

**Comment by missedone** [comment]
@raghav2329 
could you share the detail of error by right click on line "No repository found at ...", select "Copy Details", and paste it here, thanks

**Comment by raghav2329** [comment]
Hi,
Thanks for your reply. Today i tried to reproduce the issue but i am getting different error log. Please find the attachment.

![wedriver testng](https://cloud.githubusercontent.com/assets/12811132/8074949/c0c033f4-0f56-11e5-927a-0a6af4ed6df4.jpg)

**Comment by krmahadevan** [comment]
If this is still a problem, please open an issue in https://github.com/cbeust/testng-eclipse
