### ISSUE TITLE
TestNG should be an alternative for Android tests

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#733]
I've no real idea what it means, but TestNG should be an alternative of JUnit anywhere.

Useful links:
- https://plus.google.com/+AndroidDevelopers/posts/4a51oVb59H6?linkId=14810546
- https://github.com/googlesamples/android-testing/
- https://developer.android.com/tools/testing-support-library/index.html

**Comment by rschmitt** [comment]
Even while targeting Java 7?

**Comment by juherr** [comment]
Android supports Java7 like TestNG. 
http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Using-sourceCompatibility-1.7

What is the problem?

**Comment by rschmitt** [comment]
I dunno, ask the JUnit people. They're terrified to drop Java 5 support. TestNG can't be considered an alternative on such old JVMs.

**Comment by juherr** [comment]
I still don't understand your problem.

**Comment by rschmitt** [comment]
If TestNG runs on Java 7, and JUnit runs on Java 5, then TestNG is not an alternative to JUnit for anyone targeting Java 5 or Java 6. What's hard to understand about this?

**Comment by juherr** [comment]
I don't think there is a lot of Android dev who are using Java 5 or 6. 

And I still not understand your position against testng supporting Android tests.

**Comment by rschmitt** [comment]
I don't have one. I'm just observing that JUnit runs on much older JVMs than TestNG, and that Android tends to be a few years behind the curve.

**Comment by pfumagalli** [comment]
I managed to get a simple Instrumentation and test runner on Android... We just had way too many tests written in NG for a bunch of libraries we're "porting" to Android, and converting back was *NOT* an option.

If you folks are interested, it's here...

https://github.com/LemonadeLabInc/android-testng

**Comment by juherr** [comment]
:+1: I updated the wiki https://github.com/cbeust/testng/wiki/3rd-party-extensions

**Comment by krmahadevan** [comment]
@juherr - Should we close this ? Since there's some work done around this via `android-testng` ?

**Comment by juherr** [comment]
@krmahadevan Yes, thank!
