### ISSUE TITLE
TestNG 6.9.5 plugin does not work with Eclipse on Mac machine.

### ISSUE THREAD

**Issue by daramyogi** [cbeust/testng#737]
- I am trying to use eclipse on Mac OS X with testng 6.9.5. Plugin gets successfully installed but it does not show up in Eclipse preferences.
- I tried this with multiple eclipse versions as Kepler, Juno, Luna.
- I tried this on Mac OS 10.10.3 and 10.9.5.
- Same set up is working fine on windows machines.

**Comment by missedone** [comment]
@daramyogi 
Which jdk version you used to run eclipse, jdk 7 and above is recommended

**Comment by daramyogi** [comment]
Yes, I am using jdk 7 only.

**Comment by missedone** [comment]
Ok, do you see any relate errors on "Error Log" view (Click "Window" top-level menu -> Show View -> Error Log"

could you post relate error message here is there is any, thanks

**Comment by daramyogi** [comment]
There are no error logs.

**Comment by daramyogi** [comment]
Hey, I tried installing JDK 8 U45 and it worked for me. 
Thanks for your help.
