### ISSUE TITLE
report xml files do not validate against DTD

### ISSUE THREAD

**Issue by galan** [cbeust/testng#757]
I'm using eclipse, and I'm getting an error since the `test-output/testng-failed.xml`file creates an error in line 3:

    Attribute "guice-stage" must be declared for element type "suite"

Example outputfile:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
    <suite guice-stage="DEVELOPMENT" name="Failed suite [Default suite]">
      <test name="Default test(failed)">
        <classes>
          <class name="some.project.SomeTest">
            <methods>
              <include name="testName"/>
            </methods>
          </class> 
        </classes>
      </test> 
    </suite>

**Comment by juherr** [comment]
The dtd changed with #682 but it seems that http://testng.org/testng-1.0.dtd had never been updated.

That can explain your problem. I'm sure @cbeust will update it asap :)

**Comment by cbeust** [comment]
Done. FYI, [here is the browser friendly version of the DTD](http://testng.org/testng-1.0.dtd.php).

**Comment by galan** [comment]
Thank you, does validate correctly now.

**Comment by cbeust** [comment]
Thanks for pointing it out!

If you have a minute, can you double check that your build caches the DTD after the first download? It should not be going to the web site each time.

**Comment by galan** [comment]
At least my browser gets a 304 when refreshing, I can't say if maven and eclipse are caching the schemas.
