### ISSUE TITLE
Version 6.9.6 of TestNG is not OSGI

### ISSUE THREAD

**Issue by msebire** [cbeust/testng#759]
The latest version of TestNG don't contain any information to be OSGI complaint. Version 6.9.4 was.

**Comment by cbeust** [comment]
Probably lost them in the transition to gradle. Can you see what's missing?

**Comment by msebire** [comment]
I will take a look but don't really know gradle. I will keep you informed.

**Comment by msebire** [comment]
Just finished my investigation. You can take a look at the following pull request https://github.com/cbeust/testng/pull/762
