### ISSUE TITLE
Priority issue in version 6.8.8 and 6.9.6

### ISSUE THREAD

**Issue by mhiemstrapodiumtv** [cbeust/testng#764]
Hi all,

I am using Testng and nearly everything is working really well. There is one serious issue with priority. No matter what I do priority is ignored.

When I say

@Test( groups ="testA", priority=123 )
public void testMethodA() {
  // Do nothing
}

I see this in the output:

my.package.CalendarPage
  @BeforeMethod AbstractPageTest.beforeMethod()[pri:0, instance:my.package.CalendarPage@183b7230]
    @Test CalendarPage.testCalendarItems()[pri:0, instance:my.package.CalendarPage@183b7230]

priority isn't being read.

So I tried a IMethodInterceptor and a IAnnotationTransformer and in each listener I execute

annotation.setPriority ( 999 );

and still it says

my.package.CalendarPage
  @BeforeMethod AbstractPageTest.beforeMethod()[pri:0, instance:my.package.CalendarPage@183b7230]
    @Test CalendarPage.testCalendarItems()[pri:0, instance:my.package.CalendarPage@183b7230]

My xml contains this:

<suite name="Test suite" parallel="false">

	<listeners>
            <listener class-name="my.package.TestAnnotationTransformerListener" />
  	</listeners>

	<test name="WebsiteTests" verbose="3">
		<parameter name="browser" value="firefox" />

		<groups>
			<run>
				<include name="testA" />
			</run>
		</groups>

		<packages>
			<package name="my.package.*" />
		</packages>
	</test>
</suite>

Either there is a bug in testng with priorities or there is a configuration conflict or something.

Yours sincerly,
Martijn Hiemstra

**Comment by juherr** [comment]
In fact, it's just a visual issue because priority value is set after the creation of the displayed line.

**Comment by mhiemstrapodiumtv** [comment]
I believe this issue should be opened. The issue isn't that the priority is displayed as 0. The issue is that the priority doesn't work when you use the packages tag.

When I indicate 
<packages>
   <package name="my.package.*" />
</packages>
then the priority is ignored and everything is executed in random order.

However if I indicate
<classes>
	<class name="tv.package.ClassA" /> // Priority 1
	<class name="tv.package.ClassB" /> // Priority 3
	<class name="tv.package.ClassC" /> // Priority 2
</classes>
then first ClassA tests are executed then ClassC and then ClassB. 

It seams if you set the packages tag priority is ignored. And that's where priority is the most important otherwise I have to put 50 classes in my xml and everytime priority changes or I add a class I need to update the xml which isn't what I want.
