### ISSUE TITLE
gradle groups multiple classes

### ISSUE THREAD

**Issue by roydekleijn** [cbeust/testng#768]
Hello,

I’m trying to execute multiple groups (in once)

I’m expecting that TestNG completes all tests within the same group and then continues with the second group.

But it doesn’t do that, it executes tests randomly (from the specified groups), is that expected behavior ?

If required, I can create a public repo to demonstrate this behavior.

Thanks,
Roy

**Comment by cbeust** [comment]
If you expect first group to be run before the second one, then you need to use `dependsOnGroups`. If you don't specify such a dependency, TestNG assumes that no ordering is required and it will just run all the test methods in these groups in random order.

**Comment by roydekleijn** [comment]
Thanks for the quick reply. Let me elaborate it a bit more. I have the
following test classes:



// Class 1: those test can run independently

@Test(groups = { "validator" })

public class ValidatorTest {



@Test

public void test1() {

}



@Test

public void test2() {

}



}



// Class 2: test execution order is important

@Test(groups = { "end2end" })

public class end2endTest {



@Test

public void step1() {

}



@Test(dependsOnMethods = { "step1" })

public void step2() {

}



@Test(dependsOnMethods = { "step2" })

public void step3() {

}



}





How can I achieve this situation? So, that first the end2endTest class will
be executed and then the ValidatorTest class. (one class of tests after the
other)

I like to solve it with groups, because in the end tests can be scattered
in the entire framework.

On Tue, Jul 28, 2015 at 10:36 PM, Cedric Beust <notifications@github.com>
wrote:

> If you expect first group to be run before the second one, then you need
> to use dependsOnGroups. If you don't specify such a dependency, TestNG
> assumes that no ordering is required and it will just run all the test
> methods in these groups in random order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/testng/issues/768#issuecomment-125746506>.
>



-- 

  [image: --]
Roy de Kleijn
[image: http://]about.me/roydekleijn
     <http://about.me/roydekleijn?promo=email_sig>
