### ISSUE TITLE
SoftAssert duplicates error messages

### ISSUE THREAD

**Issue by pavelpp** [cbeust/testng#784]
TestNG version 6.9.6, running in IntelliJ IDEA. Example to reproduce:

    @Test
    public void test() {
        SoftAssert sf = new SoftAssert();
        sf.assertEquals(5, 4, "5 does not equal 4!\n");
        sf.assertEquals(1, 2, "1 does not equal 2!\n");
        sf.assertEquals(1, 1, "some message");
        sf.assertAll();
}

Output is :

    java.lang.AssertionError: The following asserts failed:
	5 does not equal 4!
	5 does not equal 4!
     expected [4] but found [5], 
	1 does not equal 2!
	1 does not equal 2!
 
    Expected :2
    Actual   :1

**Comment by prvn133t** [comment]
I tried it in eclipse and I don't see this happening.

**Comment by pavelpp** [comment]
I suspect it's a bug with TestNG plugin for IntelliJ Idea.

**Comment by juherr** [comment]
Did you open an issue on IntelliJ somewhere?

Ping @VladRassokhin

**Comment by pavelpp** [comment]
Not yet

**Comment by VladRassokhin** [comment]
Looks like some trouble with stderr/stdout or listeners.
If you think this is bug in IntelliJ TestNG support, please create new issue in https://youtrack.jetbrains.com

**Comment by juherr** [comment]
Done: https://youtrack.jetbrains.com/issue/IDEA-145327
