### ISSUE TITLE
IAnnotationTransformer2 transformed value reverts to default

### ISSUE THREAD

**Issue by varontron** [cbeust/testng#787]
Using v6.8.21 (JDK 1.6) with maven-surefire-plugin, in summary, my implementation of `IAnnotationTransformer2` picks up a test method annotation and modifies it successfully, along with all other method annotation transformations. Then at test execution time, the annotation value reverts to the hardcoded value, but only for the one method, not for any others. The other methods use the transformed values successfully.

Debugging implies the instance of the test method passed to the `DataProvider` (and it's declared annotations) is a different instance than the one with transformed annotations. This is not the case with the methods that succeed.

Details:

I have a TestNG test class `ServiceTest` with a number of test methods (>25). I also have a custom annotation `@QueryFile` which takes a list parameter containing an array of `String` which reference paths to text files containing parameters:

``` java
//ServiceTest.java snippet, original:

@Test (dataProvider="QueryTests",groups={"json","api"})
@QueryFile(list={
    "/test/inserts_multiquery_json.txt",
    "/test/selects_multiquery_json.txt"
})
public void testWithMultipleQueries(String query) throws... 
```

Previously, as in the example above, the list values were hard-coded into the `ServiceTest` class, with a separate set of paths for each method.

Recently, I have added an implementation of `IAnnotationTransformer2`, `QueryFileTransformer`, to load these paths from a properties file instead. This makes the job of toggling test parameters on and off significantly easier (e.g., I can just rename various versions of the properties files to the expected name and it gets picked up.)

Revised ServiceTest.java

``` java
// revised ServiceTest.java snippet:

@Test (dataProvider="QueryTests",groups={"json","api"})
@QueryFile(list={})
public void testWithMultipleQueries(String query) throws...
...
@Test (dataProvider="QueryTests",groups={"json","api"})
@QueryFile(list={})
public void testWithJSONParams(String query) throws...
```

TestNG_toggle.properties

```
// TestNG_toggle.properties snippet:
# General tests
testWithMultipleQueries=\
/test/inserts_multiquery_json.txt,\
/test/selects_multiquery_json.txt,\
/test/updates_multiquery_json.txt,\
/test/deletes_multiquery_json.txt
testWithJSONParams=\
/test/inserts_multi_json.txt,\
/test/selects_single_json.txt,\
/test/selects_multi_json.txt,\
/test/updates_single_json.txt
```

So to state the problem again: One of my test methods, and only one, suffers the indignity of reverting to its default `@QueryFile` annotation value during test execution. All other methods honor the annotation value resulting from `QueryFileTransfomer.transform`. In the example above, `testWithJSONParams` executes correctly with the values from the properties file, but `testWithMultipleQueries` executes with a null list, and is skipped. When `testWithMultipleQueries` has a hardcoded list, it works fine.

Some facts:
- Execution is through maven surefire and failsafe
- preserve-order="true"
- as stated above: `QueryFileTransformer` picks up the `testWithMultipleQueries` annotation and modifies it successfully, in the midst of all other transformations. Then at test execution time, the annotation value appears to revert to the hardcoded value.
- stepping through the eclipse debugger, it seems the transformation of `testWithMultipleQueries` occurs earlier than other method annotation transformations, but it's not always first. Often it is intermingled with methods from other classes, which are listed first in the xml file, whereas the rest of the ServiceTest methods seem to transform in sequence.
- Specifying the method as exclusive in the xml config file had no impact other than the expected of omitting the other methods' execution.
- Changing the order of specified methods had no impact on the issue.

I assume this is a configuration problem, but an esoteric one.  There is little to go on, online, for this feature.  Any insight you can provide will be most helpful.

Thanks!

**Comment by juherr** [comment]
Is it possible to share a runnable project which shows the issue?

Is it possible you test with the latest version of TestNG?

**Comment by varontron** [comment]
My source will be available within a few weeks -- the corp overlords have to approve before release, but that process is underway.  

This raises an interesting question which is: can the issue be reproduced?  I'll try to build a separate package on the quick and post to my personal repo.  

Regarding version, this issue arises in 6.8.21 which I believe I'm stuck with while using JDK 1.6.

**Comment by varontron** [comment]
There is a working example here: https://github.com/varontron/testng-annoxform2-bug
Results were reproduced in v6.8.21 and v6.9.6.
Details in the ReadMe.

**Comment by krmahadevan** [comment]
I don't think this issue exists any more in `6.14.3`. Please comment if this is still a problem
