### ISSUE TITLE
Method listener per test class

### ISSUE THREAD

**Issue by nemesis13** [cbeust/testng#791]
## Problem description
Currently IInvokedMethodListener can only be added to an ISuite. It would be nice if we could apply a listener per test class and per test class instance.

## Specific use case:
Multiple test classes use a common base which creates a `WebDriver` instance in `BeforeClass`. I have a method listener that takes screenshots on every failed configuration- and test method. I used to create a listener with a driver instance and pass it to `ISuite` in `BeforeClass` right after creating the driver. Unfortunately this listener is then added every time the `BeforeClass` is called and triggered multiple times on every new method invocation.
Since I'm ordering the class invocations by instance anyways, I could live with a suite listener that is replaced each time a `BeforeClass` is called - but this is impossible since you can only add listeners.
I could use a simple `AfterMethod` but that doesn't trigger on failed configuration methods (`BeforeClass`, `BeforeMethod` etc.) and I'd like to take screenshots on each failure.

## Objective / Feature request:
I'd love to have a possibility of binding an `IInvokedMethodListener` to each test class instance.

**Comment by cbeust** [comment]
You can make sure your listener only runs for specific classes by inspecting the method passed in parameter, right?

**Comment by nemesis13** [comment]
Thanks for the response.
And yeah, I just did that, but it rather feels like a workaround. For every class I create, a new listener is attached to the suite. I just looked through the code of TestNG and I wonder whether it would be better to use something like the ExitCodeListener since it already has callbacks for failed test- and configuration methods.

My workaround so far:
```java
    public class DriverMethodListener implements IInvokedMethodListener
    {

        private WebDriver driver;
        private Object testinstance;
        
        public DriverMethodListener(Object testinstance, WebDriver driver)
        {
            this.testinstance = testinstance;
            this.driver = driver;
        }
        
        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {}

        @Override
        public void afterInvocation(IInvokedMethod method, ITestResult testResult)
        {
            if (this.testinstance.equals(method.getTestMethod().getInstance()))
            {
                System.out.println("after invocation of " +testResult.getName());
                System.out.println("\t" + driver);
            }
            
        }

    }
```

**Comment by juherr** [comment]
I don't understand why you don't look for the webdriver instance in `afterInvocation`?

```
method.getTestMethod().getInstance().getClass().getField("driver")
```

**Comment by nemesis13** [comment]
So you suggest making the driver field public (it's protected ATM) and comparing it to the passed driver object in the listener? How is that different from comparing test class instances?

**Comment by juherr** [comment]
or using `setVisisble(true)`.

The idea is to remove the constructor and make it generic. So, no need to have one listener instance by test class or test instance.

**Comment by juherr** [comment]
@nemesis13 Did you solve your problem? Could we close the issue?

**Comment by nemesis13** [comment]
I don't like the idea of working around type safety and field visibility, but it would work I guess. If you think listeners per instance are overkill, I'm okay with that. I'll stick to my workaround then.

Thanks for your responses. Closing this now.

**Comment by juherr** [comment]
You can avoid the reflection by using interface, where all your tests will implement it:

```
inteface WebDriverTest {
    WebDriver getDriver();
}
```

and

```
Object instance = method.getTestMethod().getInstance();
if (instance instanceof WebDriverTest) {
   WebDriverTest webTest = (WebDriverTest) instance;
   WebDriver driver = webTest.getDriver();
   ...
}
```

**Comment by nemesis13** [comment]
The problem is not getting the driver but to distinguish them. If you create multiple instances of the same test class e.g. using a Factory the BeforeClass gets invoked every time. Since I can add this listener only to the whole suite I add the same listener to the same suite multiple times and end up having multiple listeners triggered at once on every method.

I guess I could use BeforeSuite for this and use your method of determining whether we're having a driver enabled class or not. Thanks!

**Comment by juherr** [comment]
Why would you like to distinguish them when you have the possibility to get it from the test itself?

Maybe you should share a project,  as little as possible, that I can run.

**Comment by nemesis13** [comment]
Distinguish as in "run the listener only once per instance" as opposed to "run each listener for each instance" which has horrible side-effects if you add the listener based on class. However, using one listener per suite should solve this.

**Comment by juherr** [comment]
In fact, listeners should be suite scoped IMO and I made some pr about it. Maybe IInvokedMethodListener was not yet updated and maybe I should do it. I will have a look asap.

**Comment by nemesis13** [comment]
It is suite scoped. If you want your listener to run on specific classes or instances you have to do that all in the listener. This is the whole point of this feature request.

**Comment by juherr** [comment]
> It is suite scoped.

Good!

> If you want your listener to run on specific classes or instances

Ok, that's why I'm trying to understand why you want it, because I'm sure you don't need it ;)
But without a concrete example, it is difficult to try and propose things.

**Comment by nemesis13** [comment]
Sorry, too lazy for concrete example ;-)

Yet another theoretical example:
You have a suite with one WebDriver test class and a unit test class. You want the listener to only do anything on the WebDriver enabled class. However, instead of attaching the listener to the class you'll instead have to put that logic inside the listener.

**Comment by juherr** [comment]
Yep, but in this case, you can use @BeforeX/@AfterX methods ;)

**Comment by nemesis13** [comment]
Sure. But it just happens that I use the @Before and @After annotations as parts of the tests sometimes. For example, I put test preconditions into a @BeforeClass method. If something fails there, how do I execute my analysis code (i.e. try to take screenshot)?

**Comment by juherr** [comment]
Preconditions are not supposed to fail. Otherwise, you can use a precondition test method + `dependsOnMethods` on others tests + `@AfterClass(alwaysRun=true)`.

**Comment by nemesis13** [comment]
I like to keep preconditions in a @ BeforeClass because this way I can distinguish between failed tests and failed conditions. Example of a commonly used precondition in our tests: go to login page and login (...), navigate to page XYZ. After that the tests of page XYZ begin.

Nonetheless if there's an error in @ BeforeClass I want a screenshot so I can see the state when it failed.

**Comment by juherr** [comment]
Do you have any problem with this example? https://gist.github.com/juherr/600edc68c32ba6a3f419
