### ISSUE TITLE
testng-6.9.6 git tag is missing

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#807]

**Comment by Stephan202** [comment]
Idem for 6.9.7 and 6.9.8.

**Comment by cbeust** [comment]
Done.

-- 
Cédric

**Comment by juherr** [comment]
6.9.6 is still missing :cry:

**Comment by cbeust** [comment]
Yeah, bit late for this and I don't feel like digging through the history to find the right cut out time stamp.

Is it important for you?

**Comment by juherr** [comment]
Nope ;)
