### ISSUE TITLE
NoSuchMethodError: org.testng.xml.XmlSuite.setParallel(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by Tibor17** [cbeust/testng#813]
I run the master branch because of testing a fix in surefire project and my integration test fails on
java.lang.NoSuchMethodError: org.testng.xml.XmlSuite.setParallel(Ljava/lang/String;)V

**Comment by cbeust** [comment]
This method changed signature a while ago, I'm betting you have a very old testng.jar somewhere in your classpath.

**Comment by juherr** [comment]
Not a so long time: https://github.com/cbeust/testng/pull/769 (not yet released).
I will add and deprecate the string method.
