### ISSUE TITLE
Installation Problem in myeclipse Bling (2010 - 2013)

### ISSUE THREAD

**Issue by TanujSinghAtcs** [cbeust/testng#817]
I am facing a problem with TestNG plugin in Bling. It is being installed properly but not showing any view of TestNG. Myeclipse Bling has got just the JUnit in Window -> Preferences -> Java -> JUnit but I can't see TestNG.

I have used below steps to Install the plugin.
1. Open MyEclipse IDE
2. From menu options click on Help > MyEclipse Configuration Center
3. Choose the Software tab
4. Click on add site. This opens an Add Update Site window. Add any name. I used TestNG. Add URL as http://beust.com/eclipse
5. Click on [OK]
6. This lists TestNG under Personal Software
7. Expand to view the child node. Right click on TestNG(child node) and click on [Add to profile].
8. Click on [Apply 1 change] under Pending Changes and follow the wizard.
9. When prompted, please choose to restart the IDE.
10. To verify, click on Help > About MyEclipse Enterprise Workbench. Click [Installation Details]. Choose Plug-ins tab and look for Plug-in Name TestNG

**Comment by missedone** [comment]
hi, 
i am not familiar with myeclipse, but do you see any relate log in error viewer: click window on top level menu -> show view -> other -> error.

**Comment by verhagen** [comment]
Check to see if the TestNG is correct installed in Eclipse:

1. Use Eclipse menu: _Window -> Show View -> Other..._
1. The dialog _Show view_ opens
1. In the tree open the node __Java__
1. There should be a view __TestNG__ avaiable

**Comment by TanujSinghAtcs** [comment]
Thanks for the reply.
In Eclipse it is working but not for myeclipse bling 2010 version. After proper installation also its not showing any TestNG view.

**Comment by verhagen** [comment]
Do you know on which version of Eclipse _Bling 2010_ is based? Maybe some older Eclipse 3.x release. If so you would probably need an older version of _TestNG for Eclipse_.

**Comment by TanujSinghAtcs** [comment]
Hello
These are the following information about my eclipse, Hope it may help you.

MyEclipse Blue Edition

Version: 10.6 Blue
Build id: 10.6-Blue-20120727

(c) Copyright Genuitec, L.L.C. 2000-2012.  All rights reserved.
Visit http://www.myeclipseide.com/

This product includes software developed by the following
Eclipse Foundation http://www.eclipse.org/
Apache Software Foundation http://www.apache.org/

Thanks
Tanuj Singh

**Comment by verhagen** [comment]
In standard Eclipse there is the possibility to see which software has been installed. Can you provide the table / overview?

Eclipse menu _Help -> About Eclipse_
- Use the button _Installation Details__

__OR__

Eclipse menu _Help -> Install New Software..._
- Use the 'link' in _What is **already installed** ?_

Then make screen capture of
- Installed software
- Features
- Plug-ins

**Comment by TanujSinghAtcs** [comment]
I am sending you the screen shorts of Installed software, Features and
Plug-ins.

Please find the attached file.

**Comment by verhagen** [comment]
@TanujSinghAtcs Add the image direct in the GitHub issue here #817, and not by a reply in mail. As that will not add the images to the issue. Thx

**Comment by krmahadevan** [comment]
Closing this issue, since there's no updates on this. If this is still a problem, please feel free to open a new issue on https://github.com/cbeust/testng-eclipse
