### ISSUE TITLE
Release Plan 6.9.7

### ISSUE THREAD

**Issue by Tibor17** [cbeust/testng#821]
There is a chance to include one more bug fix TestNG provider in surefire-plugin due to I have to repeat ASF Vote and release.
When we want to release testng:6.9.7 ?

**Comment by Tibor17** [comment]
@cbeust 
Do you have a lot of pending issues in backlog for 6.9.7?

**Comment by cbeust** [comment]
@Tibor17 No rush to ship 6.9.7, go ahead and keep me posted.

Thanks!

**Comment by Tibor17** [comment]
@cbeust Then sorry.

**Comment by cbeust** [comment]
I'm confused, sorry about what? Did I misunderstand what you said?

My understanding was that you're asking me to hold the 6.9.7 release so you can have some time to do a fix on your end, did I get that wrong?

**Comment by Tibor17** [comment]
To hold? No, opposite.
The situation in ASF is that we called a Vote fore surefire-plugin release.
The Vote was not successful and I have a little time till we start a new
Vote since I fixed some issues and I am waiting for response from people
who performs test. This means there is a chance to document a fix that we
done in surefire which depends on TestNG would require a new version of
TestNG. Since I am not allowed to mark the JIRA issue fixed in ASF without
really having released bug fix been already done in TestNG 6.9.7-SNAPSHOT,
I am not allowed to mark surefire fix as done. Mentioning documented fix
means closing the Jira issue together. The documentation in ASF Maven would
declare Version 6.9.7 as stable for that particular feature the TestNG
users need through Maven Plugin like surefire.
So you can see a dependency between fix done in TestNG and fix in surefire
project is dependency between release versions.

If you feel the TestNG needs more time to fix some important issues, I
don't mind and I will better wait. I plan a new release for Surefire by the
EO the year. We are talking about maybe hald day or one day maximum to
wait. I will start new Vote and there is a chance on my side to change the
statistics in Jira from 52 fixes to 53, and the one would be for TestNG.
The Vote takes three days and I cannot change anything in the release
content which is waste of the time because I could get more very good bug
fixes.

Sorry for such long explanation.

On Sun, Oct 11, 2015 at 6:46 AM, Cedric Beust <notifications@github.com>
wrote:

> I'm confused, sorry about what? Did I misunderstand what you said?
>
> My understanding was that you're asking me to hold the 6.9.7 release so
> you can have some time to do a fix on your end, did I get that wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/testng/issues/821#issuecomment-147155800>.
>



-- 
Cheers
Tibor

**Comment by juherr** [comment]
+1 for the 6.9.7 release

**Comment by Tibor17** [comment]
Guys, I don't want to make stress.
Example, on my side in Surefire project I started Vote for the release
after 9 months, was never longer before, because there was a big rework and
I still was not convinced about stability of s/w. Many people pleased me to
make the release but I did not make it because there was quality reason.

On Sun, Oct 11, 2015 at 7:21 AM, Julien Herr <notifications@github.com>
wrote:

> +1 for the 6.9.7 release
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/testng/issues/821#issuecomment-147158616>.
>



-- 
Cheers
Tibor

**Comment by cbeust** [comment]
No worries at all, I'm happy to ship 6.9.7 right now, so I'll go ahead and
do that shortly.

Thanks again for your help, Tibor!



-- 
Cédric

**Comment by Tibor17** [comment]
@cbeust @juherr I appreciate.

**Comment by Tibor17** [comment]
@cbeust 
The Version 6.9.7 was compiled with Java 8.
Is it correct?

**Comment by juherr** [comment]
As I remember it was not planned and I didn't see changes that need Java8. I supposed something gone wrong at the release time x]

**Comment by Tibor17** [comment]
The classes in old Version 6.9.6 were compiled with Java 7:
major version number of the class file format being used.
J2SE 7 = 51 (0x33 hex),
https://en.wikipedia.org/wiki/Java_class_file
Usually I open JAR file and pickup any class and open it as text editor in hexa binary mode.
I see this:
CA FE BA 00 00 00 33| etc
0x33 means Java 7

**Comment by juherr** [comment]
Don't worry. I think @cbeust will deploy a 6.9.8 with Java7 soon.

**Comment by Tibor17** [comment]
Thx a lot.

**Comment by Tibor17** [comment]
I see in Maven Central that some versions are missing. This is maybe because of those versions were dropped for some reason. Maybe we should do it with 6.9.7.

**Comment by juherr** [comment]
+1

**Comment by cbeust** [comment]
My bad, I deployed with a different computer that uses Java 8 by default,
I'll push 6.9.8 shortly.

-- 
Cédric

**Comment by Tibor17** [comment]
@juherr 
Offtopic issue.
I need someone experienced in TestNG for explaining. Can you please have a look in [1]. I am a little bit lost of the behavior of surefire and TestNG. I don't know now which one fails.
[1] https://issues.apache.org/jira/browse/SUREFIRE-983

**Comment by cbeust** [comment]
Quick thought after reading the issue: does the reporter mean to use
@AfterMethod instead of @AfterTest?
​

-- 
Cédric

**Comment by Tibor17** [comment]
@cbeust 
That's also not clear to me because he used AfterClass in his code however he mentioned AfterTest.
After using @AfterMethod and TestNG 5.10 or 6.9.6 the @AfterMethod was called three time which means once per test method. This looks like user/reporter error. What do you think?

**Comment by cbeust** [comment]
No other thought right now, I haven't looked at the attachments yet.

-- 
Cédric

**Comment by Tibor17** [comment]
@cbeust 
No problem.
Forget it. I already closed that issue. 
Thx for hint.

**Comment by cbeust** [comment]
6.9.8 is now available on JCenter (and soon on Maven Central). The binaries
should be 1.7.

-- 
Cédric

**Comment by Tibor17** [comment]
Thank you. I will continue wih Surefire release tomorrow.

On Mon, Oct 12, 2015 at 7:21 PM, Cedric Beust <notifications@github.com>
wrote:

> 6.9.8 is now available on JCenter (and soon on Maven Central). The binaries
> should be 1.7.
>
> --
> Cédric
>
>
> On Mon, Oct 12, 2015 at 7:33 AM, Cédric Beust ♔ <cedric@beust.com> wrote:
>
> > My bad, I deployed with a different computer that uses Java 8 by default,
> > I'll push 6.9.8 shortly.
> >
> > --
> > Cédric
> >
> >
> > On Mon, Oct 12, 2015 at 6:11 AM, Julien Herr <notifications@github.com>
> > wrote:
> >
> >> +1
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/cbeust/testng/issues/821#issuecomment-147394833>.
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/testng/issues/821#issuecomment-147467083>.
>



-- 
Cheers
Tibor
