### ISSUE TITLE
testng-56.xml - Contains DTD validation error

### ISSUE THREAD

**Issue by verhagen** [cbeust/testng#825]
__Why__ Looking at the file `testng-56.xml`, it contains an error, is this maybe on purpose? If so, it would be a good idea to add a XML comment, explaining that.  
If not on purpose, should the XML or the DTD be corrected?

__Description__
When loading the testng project into Eclipse it highlights errors. Normally you do not like to see errors in Eclipse. But here I'm not sure, if it should be fixed.

Looking at the file `testng-56.xml`, then the issue is that the attribute _parallel_ has the value __true__ which is not allowed, looking at the DTD.

	<suite name="TESTNG-56 Suite" verbose="3" parallel="true" thread-count="3">

Attribute _parallel_ as given in the `testng-1.0.dtd`:

    parallel (false | methods | tests | classes | instances) "false"

__Question__ On purpose or not?

- Is this on purpose, for this specific test?
- _Or_ should it be fixed in the XML `testng-56.xml` ?
- _Or_ should it be fixed in the DTD `testng-1.0.dtd` ?

__Question__ Relation of number 56

- Is there any meaning to the number _56_, of the test case? I searched for issue _56_ here on github, but did not seem to relate. Is it just a random number, or does it have some meaning?

**Comment by verhagen** [comment]
Latest checkout from master, solved this.

**Comment by juherr** [comment]
TestNG was previously on GoogleCode.
So, 56 for -> https://github.com/testng-team/testng-googlecode/issues/56
