### ISSUE TITLE
nested suites not supported by 'testnames'

### ISSUE THREAD

**Issue by Tibor17** [cbeust/testng#834]
A suite xml https://github.com/sskuts/maven-surefire-tests/blob/master/src/test/resources/suites/upstream-suite.xml binds to another one https://github.com/sskuts/maven-surefire-tests/blob/master/src/test/resources/suites/main-suite.xml which has two test names:
testGroup1
testGroup2

TestNG is configured with -testnames=testGroup2.
Expected is to run only one test.
Actual both tests run.

Is testnames supported in this kind of suites combination?

**Comment by Tibor17** [comment]
@cbeust 
Is this `-testnames` supported in nested suite as well?

**Comment by juherr** [comment]
I confirm the issue from TestNG itself. I reproduce it with master branch.

I'm trying to fix it.

**Comment by Tibor17** [comment]
@juherr 
Thank you for taking a look into it.

**Comment by juherr** [comment]
@Tibor17 Done #835

**Comment by sskuts** [comment]
@juherr thanks a lot!.. would you mind to drop a comment, after merging and publishing a new version with this fix?..

**Comment by juherr** [comment]
merge and release are @cbeust stuff ;)

**Comment by sskuts** [comment]
@cbeust would be greatly appreciated :) have been waiting for this feature support in maven-surefire-plugin for a long time...

**Comment by cbeust** [comment]
@sskuts Will do shortly.

@juherr is a release now okay with you or would you like to merge in a few additional things?

**Comment by Tibor17** [comment]
Fixed and test provided.

**Comment by sskorol** [comment]
Just built a local snapshot jar with this fix. Works like a charm. Thanks @juherr @cbeust !

**Comment by cbeust** [comment]
I just merged https://github.com/cbeust/testng/pull/835, which I believe is the PR that fixes this issue?

Can you try the "official" SNAPSHOT to make sure this is fixed before I make a new release? The snapshot repo should have the new build now (6.9.6-SNAPSHOT):

```
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
}
```

**Comment by sskorol** [comment]
@cbeust just tried with official snapshot, works fine for me as well with maven-surefire-plugin 2.19, thanks!

**Comment by cbeust** [comment]
@sskorol Thanks for confirming. 6.9.9 is almost ready to go, still need a couple of things to wrap up first.
