### ISSUE TITLE
Synthetic methods in a test-class should be ignored

### ISSUE THREAD

**Issue by andreak** [cbeust/testng#84]
When writing tests in Scala (and possibly other JVM-languages) the compiler generates some synthetic (compiler-generated) methods for all public fields ("var" in Scala).

TestNG incorrectly tries to execute these synthetic methods as test-methods. It should ignore them completely.

As mentioned here: http://beust.com/weblog/2011/03/15/announcing-testng-6-0/#comment-10330

**Comment by juherr** [comment]
Fixed by #322
