### ISSUE TITLE
preserve-order does not work with tests containing dependencies and inner classes

### ISSUE THREAD

**Issue by riemenschneider** [cbeust/testng#85]
When creating tests with dependencies and an inner class that are part of a test suite using preserve-order option, the order of tests is not preserved.
### TestNG version:

6.2.1beta (2001-08-24)
### Test suite:

``` xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Bug Demo">
  <test name="Bug Demo Test" preserve-order="true">
    <packages>
      <package name="xxx.*"/>
    </packages>
  </test>
</suite>
```
#### First class:

``` java
package xxx;

import org.testng.annotations.Test;

public class Test1 {

    @Test
    public void test1() {}

    @Test(dependsOnMethods = {"test1"})
    public void test2() {}

}
```
#### Second class:

``` java
package xxx;

import java.io.Serializable;

import org.testng.annotations.Test;

public class Test2 {

    public static class C implements Serializable {}

    @Test
    public void test1() {}

    @Test(dependsOnMethods = {"test1"})
    public void test2() {}

}
```
##### &gt;&gt; means before, &lt;&lt; means after

<p/><br/><em>Bug Demo</em><p/><small><i>(Hover the method name to see the test class name)</i></small><p/>

<table border="1">
<tr><th>Time</th><th>Delta (ms)</th><th>Suite<br>configuration</th><th>Test<br>configuration</th><th>Class<br>configuration</th><th>Groups<br>configuration</th><th>Method<br>configuration</th><th>Test<br>method</th><th>Thread</th><th>Instances</th></tr>
<tr bgcolor="bd78a8">  <td>11/08/25 09:53:42</td>   <td>0</td> <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td title="Test1.test1()[pri:0, instance:xxx.Test1@4ce2cb55]">test1</td> 
  <td>main@815578443</td>   <td></td> </tr>
<tr bgcolor="b8c8e6">  <td>11/08/25 09:53:42</td>   <td>0</td> <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td title="Test2.test1()[pri:0, instance:xxx.Test2@19484a05]">test1</td> 
  <td>main@815578443</td>   <td></td> </tr>
<tr bgcolor="bd78a8">  <td>11/08/25 09:53:42</td>   <td>15</td> <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td title="Test1.test2()[pri:0, instance:xxx.Test1@4ce2cb55]">test2</td> 
  <td>main@815578443</td>   <td></td> </tr>
<tr bgcolor="b8c8e6">  <td>11/08/25 09:53:42</td>   <td>15</td> <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td title="Test2.test2()[pri:0, instance:xxx.Test2@19484a05]">test2</td> 
  <td>main@815578443</td>   <td></td> </tr>
</table>

**Comment by akgupta0304** [comment]
Use
<test name="Automation" preserve-order="true"  enabled="true">

**Comment by AnkushMehta-GIT** [comment]
> Use: `<test name="Automation" preserve-order="true" enabled="true">`

didn't worked
