### ISSUE TITLE
[Cross-report] SUREFIRE-1194 Maven "reporter" configuration entry does not work

### ISSUE THREAD

**Issue by testn** [cbeust/testng#853]
It looks like since a477952 has removed "reporterslist" command line argument. Maven surefire testng plugin stops working since it still tries to convert reporter to reporterslist where it does not exist anymore. [https://issues.apache.org/jira/browse/SUREFIRE-1194].

The offended line is https://github.com/apache/maven-surefire/blob/master/surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/conf/TestNGMapConfigurator.java#L94

**Comment by juherr** [comment]
As it was removed for a long time, we can admit it is a surefire issue.
Then, surefire is using a deprecated method and will try to change this behavior.

Ping @Tibor17: What do you think?

**Comment by juherr** [comment]
Fix provided on surefire: https://github.com/apache/maven-surefire/pull/107

**Comment by Tibor17** [comment]
I agree with closing this issue due to surefire needs to adapted accordingly.
