### ISSUE TITLE
XmlSuite.clone method missing following state copy, in follow up of issue #866

### ISSUE THREAD

**Issue by virenv** [cbeust/testng#868]
@cbeust,

These are the states that are not copied in XmlSuite.clone method

    result.setExcludedGroups(getExcludedGroups());
    result.setIncludedGroups(getIncludedGroups());
    result.setGroupByInstances(getGroupByInstances());
    result.setGroups(getGroups());
    result.setMethodSelectors(getXmlMethodSelectors());
    result.setPackages(getPackages());
    result.setParentSuite(getParentSuite());
    result.setPreserveOrder(getPreserveOrder());
    result.setSuiteFiles(getSuiteFiles());
    result.setTests(getTests());
    result.setXmlMethodSelectors(getXmlMethodSelectors());

By definition clone is a deep copy where we copy every state of the instance.

**Comment by virenv** [comment]
I will be sending a PR for this, do review it

**Comment by cbeust** [comment]
Great, thanks @virenv!

**Comment by juherr** [comment]
@virenv  You can check every `clone` method if you want. :)
I've already seen some missing attributes somewhere else (or maybe it was this one, I can't remember).

**Comment by juherr** [comment]
Closed by #869

**Comment by virenv** [comment]
@juherr 

Sure, let me take a look and I will send a PR if I find issues.
