### ISSUE TITLE
Enable end-users of TestNG to alter XmlSuite and XmlTest

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#872]
Following is a use case which was brought up by one of my colleagues at work 

We basically have a ```<suite>``` which has 1 or more ```<test>``` in it.
This suite has been used so far to simulate a regression etc.,
Now the team basically wants to use this suite to simulate a performance testing and want to see if the following can be done :

* Given a ```<test>``` name, have the ability to run all the classes defined in it more than once.

So in a nut shell, its like having the ability to specify ```invocationCount``` but at ```<test>``` level so that all the ```@Test``` annotated ```<test>``` methods defined in it run "n" times.

This and a lot of such requirements can be fulfilled by the end user itself, if TestNG were to expose all the suites to the user for altercation before TestNG starts executing them (In the same way all the other listeners currently expose the suite via ```ISuite``` and ```ITestContext``` )

**Comment by juherr** [comment]
Fixed by #873
