### ISSUE TITLE
NullPointerException creating tests with parameters by a factory

### ISSUE THREAD

**Issue by vixgeo** [cbeust/testng#876]
Please, refer to the following post on stackoverflow for more details:
http://stackoverflow.com/questions/33676609/repeat-entire-test-class-in-testng-with-different-data-provider

**Comment by juherr** [comment]
Thank for the report! :)

**Comment by vixgeo** [comment]
It's not a bug. The factory method must be `static`.

**Comment by vixgeo** [comment]
It's not a bug. The factory method must be `static`.

**Comment by juherr** [comment]
In fact it is: testng should allow non static methods or detect the issue with an appropriate message.
