### ISSUE TITLE
@Listeners are applied to all classes, not only those in which it has been declared 

### ISSUE THREAD

**Issue by mpucholblasco** [cbeust/testng#88]
If @Listeners is specified in several classes, the whole list of listeners are applied to all classes, not only those in which should.

To test this issue, I have declared the a 'testng.xml' file for my two classes: TestNGFail, and TestNGFail2.

The classes are:
<code>
@Listeners({ MyMethodListener.class })
public class TestNGFail {
    @Test
    public void test1() {
        System.out.println("Executing test1 from class TestNGFail.");
    }
}
</code>
<code>
@Listeners({ MyMethodListener.class })
public class TestNGFail2 {
    @Test
    public void test2() {
        System.out.println("Executing test2 from class TestNGFail2.");
    }
}
</code>

And the listener is:

<code>
public class MyMethodListener implements IInvokedMethodListener2 {
    public void beforeInvocation(IInvokedMethod iim, ITestResult itr, ITestContext itc) {
        System.out.println("beforeInvocation method (" + iim.getTestMethod().getMethodName() + ") with ITestResult (" + itr + ") and ITestContext (" + itc + ").");
    }
    public void afterInvocation(IInvokedMethod iim, ITestResult itr, ITestContext itc) {
        System.out.println("afterInvocation method (" + iim.getTestMethod().getMethodName() + ") with ITestResult (" + itr + ") and ITestContext (" + itc + ").");
    }
    public void beforeInvocation(IInvokedMethod iim, ITestResult itr) {
        System.out.println("beforeInvocation method (" + iim.getTestMethod().getMethodName() + ") with ITestResult: " + itr);
    }
    public void afterInvocation(IInvokedMethod iim, ITestResult itr) {
        System.out.println("afterInvocation method (" + iim.getTestMethod().getMethodName() + ") with ITestResult: " + itr);
    }
}
</code>

If this suite is executed, the result is:
beforeInvocation method (test1) with ITestResult ([TestResult: test1 STATUS:STARTED METHOD:TestNGFail.test1()[pri:0, instance:testngfail.TestNGFail@76f8968f]]
) and ITestContext (org.testng.TestRunner@7ffc6e42).
beforeInvocation method (test1) with ITestResult ([TestResult: test1 STATUS:STARTED METHOD:TestNGFail.test1()[pri:0, instance:testngfail.TestNGFail@76f8968f]]
) and ITestContext (org.testng.TestRunner@7ffc6e42).
Executing test1 from class TestNGFail.
afterInvocation method (test1) with ITestResult ([TestResult: test1 STATUS:SUCCESS METHOD:TestNGFail.test1()[pri:0, instance:testngfail.TestNGFail@76f8968f]]
) and ITestContext (org.testng.TestRunner@7ffc6e42).
afterInvocation method (test1) with ITestResult ([TestResult: test1 STATUS:SUCCESS METHOD:TestNGFail.test1()[pri:0, instance:testngfail.TestNGFail@76f8968f]]
) and ITestContext (org.testng.TestRunner@7ffc6e42).
beforeInvocation method (test2) with ITestResult ([TestResult: test2 STATUS:STARTED METHOD:TestNGFail2.test2()[pri:0, instance:testngfail.TestNGFail2@5328f6ee]]
) and ITestContext (org.testng.TestRunner@6564dbd5).
beforeInvocation method (test2) with ITestResult ([TestResult: test2 STATUS:STARTED METHOD:TestNGFail2.test2()[pri:0, instance:testngfail.TestNGFail2@5328f6ee]]
) and ITestContext (org.testng.TestRunner@6564dbd5).
Executing test2 from class TestNGFail2.
afterInvocation method (test2) with ITestResult ([TestResult: test2 STATUS:SUCCESS METHOD:TestNGFail2.test2()[pri:0, instance:testngfail.TestNGFail2@5328f6ee]]
) and ITestContext (org.testng.TestRunner@6564dbd5).
afterInvocation method (test2) with ITestResult ([TestResult: test2 STATUS:SUCCESS METHOD:TestNGFail2.test2()[pri:0, instance:testngfail.TestNGFail2@5328f6ee]]
) and ITestContext (org.testng.TestRunner@6564dbd5).

I have analyzed the source code, and at method 'TestRunner.initListeners', all listeners are added to a list, and when the TestRunner executes the tests, this list is covered and each listener is executed. In previous example, 2 instances of previous listener are created, so these two listeners are executed. Not only that, if you have different listeners specified in different classes, even the listeners not specified for a certain class are executed in it.

For the correct running, the TestRunner should differentiate between listeners and classes, associating only the listeners specified in the annotation for a certain class (well, I think so).

If I am wrong, please notify me.

Regards,
Marcel.

**Comment by vskarda** [comment]
Just add the listener to the test order xml file, e.g <listener class-name="" />
not to the individual classes (tests)
