### ISSUE TITLE
Cannot read from stdin in TestNG test

### ISSUE THREAD

**Issue by nealxyc** [cbeust/testng#880]
Running the following test with `mvn clean test -Dtest=StdinTest`, the line `br.readLine()` does not return.
testng-6.9.9
```java
public class StdinTest {

    @Test
    public void stdinTest(){
        System.out.println("Press enter:");
        try{
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            br.readLine();
        }catch(IOException e){
            e.printStackTrace();
        }
        System.out.println("Done.");
    }

    public static void main(String[] args){
        new StdinTest().stdinTest();

    }
}
```

**Comment by juherr** [comment]
I close because TestNG is working as expected: it runs the test.

**Comment by nealxyc** [comment]
@juherr I does run the test. But were you able to get stdin input from `br.readLine()`?

**Comment by juherr** [comment]
I didn't try like it is really system dependent. Is your example working with JUnit?

**Comment by nealxyc** [comment]
@juherr Yes. it does.

**Comment by juherr** [comment]
The following main is working well:

```java
    public static void main(String... args) {
        TestNG tng = new TestNG();
        tng.setTestClasses(new Class[]{StdinTest.class});
        tng.run();
    }
```

I suppose we can say that TestNG is not the problem here? But maybe Maven is.

**Comment by nealxyc** [comment]
@juherr Oh. That seems to be true. Thanks for trying out.
