### ISSUE TITLE
parallel="classes" is not forcing test methods from the same testClass to be run in the same thread as it is suposed to (I guess)

### ISSUE THREAD

**Issue by romlom** [cbeust/testng#89]
Extract from documentation:

```
parallel="classes": TestNG will run all the methods in the same class in the same 
thread, but each class will be run in a separate thread. 
```

As this is not fully specified what the author means by <pre>all the methods in the same class</pre> in case when we have a @Test method in an abstract parent class and a @Test method in child class (They are in the same testClass but in different realClasses - as it is called in the source). 

I guess they should be run sequentially. 
If I am wrong there is no issue here and please close it. If I am right here is short example exposing the problem:

```
public abstract class A {
    @Test
    public void someMethodA1() throws InterruptedException {
        scenario("someMethodA1");
    }

    protected void scenario(String s) throws InterruptedException {
        System.out.println("START["+Thread.currentThread()+"]: " + s);
        synchronized (s) { 
            s.wait(1000);
        }
        System.out.println("END["+Thread.currentThread()+"]: " + s);
    }
}

public abstract class B extends A{
    @Test
    public void someMethodB1 () throws InterruptedException {
        scenario("something else");
    }
}

public class C extends B{
    //@Test
    public void veryImportant() {}
}
```

---

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Some Suite" >  
  <test name="Some tests" parallel="classes" thread-count="3">
    <packages>
      <package name=""/>
    </packages>
  </test>
</suite>
```

If you run this suite someMethodA1 and someMethodB1 will run in parallel (as can be seen on System.out). 
If you uncomment in class C anotation @Test  someMethodA1(), someMethodB1() and veryImportant() will execute sequentially.

**Comment by sergejjkim** [comment]
Any chance this could be fixed?

**Comment by khospodarysko** [comment]
This works as expected:

Here are my (little bit modified) classes:

```java
package com.example;
public class A {
    @org.testng.annotations.Test
    public void someMethodA1() {
        PrintThread.message("in A");
    }
}

package com.example;
public class B extends A {
    @org.testng.annotations.Test
    public void someMethodB1 () {
        PrintThread.message("in B");
    }
}

package com.example;
public class C extends B {
    //@org.testng.annotations.Test
    public void veryImportant() {
        PrintThread.message("in c");
    }
}

package com.example;
public class PrintThread {
    public static void message(String s) {
        System.out.println("START["+Thread.currentThread().getId()+"]: " + s);
        synchronized (s) {
            try { s.wait(1000); }
            catch (InterruptedException e) {}
        }
        System.out.println("END["+Thread.currentThread().getId()+"]: " + s);
    }
}

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Some Suite" >
    <test name="Some tests" parallel="classes" thread-count="3">
        <packages>
            <package name="com.example"/>
        </packages>
    </test>
</suite>
```

The output when @Test in C is commented:

```
START[11]: in A
START[12]: in A
START[13]: in A
END[12]: in A
END[11]: in A
END[13]: in A
START[12]: in B
START[11]: in B
END[12]: in B
END[11]: in B
```

So it is seen that:
* two tests were executed for class B in its own thread 
* two tests were executed for class C in its own thread 
* one test was executed for class A

All is as expected.

The output when @Test in C is uncommented:
```
START[14]: in A
START[16]: in A
START[15]: in A
END[15]: in A
END[14]: in A
END[16]: in A
START[15]: in B
START[16]: in B
END[16]: in B
END[15]: in B
START[16]: in c
END[16]: in c
```

So it is seen that:
* three tests were executed for class C in its own thread (16) 
* two tests were executed for class B in its own thread (15) 
* one test was executed for class A (14)

All is as expected.

**Comment by sergejjkim** [comment]
@khospodarysko thanks for an example.
However it doesn't contain an abstract class.
I have two classes and a suite:
```
public abstract class A {
    @Test
    public void test1() {
        message("test1");
    }

    @Test
    public void test2() {
        message("test1");
    }

    public static void message(String s) {
        System.out.println("START["+Thread.currentThread().getId()+"]: " + s);
        synchronized (s) {
            try { s.wait(1000); }
            catch (InterruptedException e) {}
        }
        System.out.println("END["+Thread.currentThread().getId()+"]: " + s);
    }
}

public class B extends A {}

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Some Suite" parallel="classes" thread-count="8">
    <test name="Some tests" >
        <classes>
            <class name="B"/>
        </classes>
    </test>
</suite>
```

what i get is two test running in separate threads:
START[12]: test1
START[13]: test1
END[13]: test1
END[12]: test1
what i expect to get is two tests running in the same thread cause they belong to a same class.

**Comment by khospodarysko** [comment]
Hey, @sergejjkim 

Your are right, I forgot about abstract.

So the one thing I did is I made classes A and B as abstract and get such output:
```
START[12]: in A
END[12]: in A
START[12]: in B
END[12]: in B
START[12]: in c
END[12]: in c
```

Is that what you are expecting?

**Comment by sergejjkim** [comment]
@khospodarysko
ok so I've made A and B abstract in your example with @Test in C commented and got
START[13]: in B
START[12]: in A
END[12]: in A
END[13]: in B
which is basically not what I'd expect to see. Also it's more about having 2 classes with 2+ methods in the abstract one.

**Comment by khospodarysko** [comment]
@sergejjkim Got it!

Similar Eclipse-related issues that I've found are: 
* https://github.com/cbeust/testng-eclipse/issues/47
* https://github.com/cbeust/testng-eclipse/issues/70

I'd say this case is rather edge-case. If one of subclasses has one @Test method all is OK.

**Comment by thibaut-sticky** [comment]
Any update or idea to fix this issue? We use a lot of abstract class tests to override just some small part of them with sub classes to change a behavior. These subclasses have no test inside, but added an empty one made these tests ran in a single thread as expected.
