### ISSUE TITLE
Changing status of test by setStatus of ITestResult

### ISSUE THREAD

**Issue by rajsrivastav1919** [cbeust/testng#895]
I was using ITestResult interface to override onTestFailure and onTestSuccess based upon some conditions. It was working in 6.9.6 as expected. Now I have updated to 6.9.9 and some things are not working as expected. Basically my use-case is as follows -

A test case is run which fails and the flow comes to my custom implementation of onTestFailure() method. I call ITestResult#setStatus method to mark the test as pass.
Earlier (& Correct) behaviour:
- Test passes
- ITestContext.getPassedTests().size() returns 1
- ITestContext.getFailedTests().size() returns 0

Current behaviour:
- Test passes
- ITestContext.getPassedTests().size() returns 0
- ITestContext.getFailedTests().size() returns 1

**Comment by juherr** [comment]
Could you share a concrete example that we can run?

**Comment by rajsrivastav1919** [comment]
Try this one-
https://github.com/rajsrivastav1919/TestNGTest

**Comment by juherr** [comment]
Ok, thank! I will have a look on it asap.

**Comment by dvikraman** [comment]
I am also facing the same issue. The above scenario works fine upto 6.9.6 only 
from 6.9.9 it started giving incorrect results.

**Comment by dvikraman** [comment]
While fixing retry reporting as per #755 . This behavior is broken.

As the result is updated in handleInvocationResults method, it should be updated by calling collectResults after the listener methods are invoked.

Adding the below statements in Invoker.class after the line number 703 would fix this issue.

if (!results.isEmpty()) {
        collectResults(tm, Collections.<ITestResult>singleton(testResult));
}

**Comment by juherr** [comment]
@dvikraman Thank for your excellent analyze.
