### ISSUE TITLE
If a configuration fails, the onTestStart method of a TestListener is invoked once

### ISSUE THREAD

**Issue by h-rueda** [cbeust/testng#911]
I created a subclass of TestListenerAdapter

I created a class containing:
- one @BeforeSuite configuration method
- two @Test methods

During execution, the @BeforeSuite method failed.

This is the behavior that I found out regarding the TestListener :

(1) The onConfigurationFailure method is invoked once
(2) The onStart method is invoked once
(3) The onTestSkipped method is invoked twice (since there are two @Test methods)
(4) The onConfigurationSkip method is invoked once
(5) The onTestStart method is invoked once

Actions (1) through (4) are the expected behavior of the TestListener.

However, action (5) is definively a bug of the testng framework.

**Comment by juherr** [comment]
Could you pull-request a new test case which shows the issue?
You can add a new test class or update/use an existing one from https://github.com/cbeust/testng/tree/master/src/test/java/test/listeners

**Comment by h-rueda** [comment]
/***   MY TEST LISTENER   ***/
public class TestListener extends TestListenerAdapter {

	public void onStart(ITestContext context) {
		System.out.println("I entered onStart");
	}
	
	public void onConfigurationFailure(ITestResult result) {
		System.out.println("I entered onConfigurationFailure");
	}
	
	public void onConfigurationSkip(ITestResult result) {
		System.out.println("Should I enter onConfigurationSkip?");
	}

	public void onTestSkipped(ITestResult result) {
		System.out.println("I entered onTestSkipped");
	}
	
	public void onTestStart(ITestResult context) {
		System.out.println("I SHOULD NOT ENTER onTestStart");
	}
}

/*** MY TESTS ***/
public class MyTest2 {

	@BeforeSuite(alwaysRun=true)
	public void setUp() { Assert.fail(); }

	@Test
	public void myTest1() {	}

	@Test
	public void myTest2() {	}
}

/***   THE TEST OUTPUT   ***/
I entered onConfigurationFailure
I entered onStart
I SHOULD NOT ENTER onTestStart
I entered onTestSkipped
I SHOULD NOT ENTER onTestStart
I entered onTestSkipped

**Comment by drapostolos** [comment]
What does your testng.xml file look like?

**Comment by h-rueda** [comment]
<suite name=".....">
	<test name="....." preserve-order="true">
		<classes>
			<class name="mypackage.MyTest2"/>
		</classes>
	</test>
	<listeners>
		<listener class-name="mypackage.TestListener" />
	</listeners>
</suite>

**Comment by h-rueda** [comment]
I see that this issue is in contradiction with #915

**Comment by juherr** [comment]
Why?
