### ISSUE TITLE
NullPointerException on loading XmlSuites programmatically

### ISSUE THREAD

**Issue by ispitkovskyi** [cbeust/testng#918]
A "NullPointerException" dropped by TestNG on loading XML suites.

This problem does NOT occur, when we use 6.9.9 version.
But, as long as 6.9.10 version is loaded, the problem starts happening.

STEPS TO REPRODUCE
1. Run testng programmatically by creating instance: TestNG testng = new TestNG();
2. Add XML suites programmatically, like:
ArrayList<String> runSuitesList = new ArrayList<>(some_length);
runList.add(suite);   //wehere evaluated in runtime    suite = C:\test\suites\smokeSuite.xml
XmlSuite suites = new XmlSuite();
suites.setSuiteFiles(runSuitesList);
testng.setXmlSuites(Arrays.asList(suites));
testng.run();

ACTUAL RESULT: During execution it drops following exception in the following block of code:
CODE (class = testng, line281):
            Path rootPath = Paths.get(s.getFileName()).getParent();
EXCEPTION
Exception in thread "main" java.lang.NullPointerException
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:281)
	at org.testng.TestNG.run(TestNG.java:1036)
	at tests.TestRunner.main(TestRunner.java:79)

NOTE: the "String suiteFile" variable within following loop shows correct valid path to XML file
for (String suiteFile : s.getSuiteFiles()) {
            Path rootPath = Paths.get(s.getFileName()).getParent();
            try {
                Collection<XmlSuite> childSuites = getParser(rootPath.resolve(suiteFile).normalize().toString()).parse();
                for (XmlSuite cSuite : childSuites){
                    cSuite.setParentSuite(s);
                    s.getChildSuites().add(cSuite);
                }
            } catch (ParserConfigurationException | IOException | SAXException e) {
                e.printStackTrace(System.out);
            }
        }

**Comment by gvenkat91** [comment]
is this issue resolved? still getting the error in 6.9.10

**Comment by krmahadevan** [comment]
@gvenkat91 - Please retry using the latest released version of TestNG viz., `6.14.2`

**Comment by venkatraman91g** [comment]
@testng-team hi mahadevan, as of now downgraded testng as a work around. Will try with latest and let you know the results. Thanks a ton for your response!
