### ISSUE TITLE
Regression in 6.9.10: ITestResult doesn't contain name if a class has @Test

### ISSUE THREAD

**Issue by dr29bart** [cbeust/testng#922]
Here is example:
https://gist.github.com/dr29bart/519fe84c286c2e559db5

The actual output of the listener is empty
In 6.9.9 it was "test"

**Comment by dmitrykondratenko** [comment]
@juherr you did some changes in scope of https://github.com/cbeust/testng/commit/06ee812f9dbb2e780083c3909e1618e49431209e

after that mentioned test name is not taken from test method. I need to specify @Test(testName="any word") on class level in order to get working mentioned example as expected.
Is it by design?

**Comment by juherr** [comment]
@dr29bart I confirm the issue with `singleThreaded`. Thank for the report.

@dmitrykondratenko I don't understand what is shocking you in the commit. `testName` from method should be used with https://github.com/cbeust/testng/commit/06ee812f9dbb2e780083c3909e1618e49431209e#diff-dee9b63261a808b691a0b486b01da144R85

**Comment by juherr** [comment]
@dmitrykondratenko 

> This attribute is ignore if @Test is not at the class level.

From [Javadoc for @Test(testName=...)](http://static.javadoc.io/org.testng/testng/6.9.10/org/testng/annotations/Test.html#testName--)

Does it answer your question? I'm not able to explain the reason of the limitation, but maybe @cbeust could.

**Comment by juherr** [comment]
@dr29bart In fact, the issue exists when you have `@Test` on class, even without parameter.

**Comment by dr29bart** [comment]
Great news. Thanks for the fix!

**Comment by cbeust** [comment]
> Does it answer your question? I'm not able to explain the reason of the limitation, but maybe @cbeust could.

Because if TestNG starts honoring `testName` on a method, then you can have several different names in a class, which doesn't make sense. I think it's just cleaner to force it at the class level.
