### ISSUE TITLE
Check values of parallel parameter

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#932]
From: https://youtrack.jetbrains.com/issue/IDEA-149750

**Comment by juherr** [comment]
@cbeust What is the goal behind `parallel=true` or `parallel=false`?
What do you think to:
* **remove** `true`, and 
* **replace** `false` by `none`?

**Comment by cbeust** [comment]
Historically, `parallel` started by just being a boolean but later, I had to change it to accept more values, so it turned into an enum.

I'm not sure I understand the problem, though: the DTD already defines these values:

    parallel (false | methods | tests | classes | instances) "false"

Is a value missing?

**Comment by juherr** [comment]
> Is a value missing?

What about `true` and `none`?

**Comment by cbeust** [comment]
Ah right. Can you send a PR? Then I'll upload the new version to the web
site (although the one that matters is probably the one shipped in
testng.jar, so we'll have to issue a new release too).

-- 
Cédric

**Comment by alexeyOnGitHub** [comment]
what's the ETA on the testng release that would fix this? I ran into this problem with IDEA 15.0.4 + testng . experimenting with junit->testng conversion and running into various issues in testng support in IDEA - mostly around groups and group init... submitted two to IDEA bug tracker. this being one of them

**Comment by AsafShochet** [comment]
+1 for this bug,
I have the similar issue, that the parallel=none, and intelij can't run the tests per group

**Comment by juherr** [comment]
@AsafShochet It is supposed to be fixed since 6.9.11
