### ISSUE TITLE
dependsOnMethods with alwaysRun = true and inheritance fails to find method

### ISSUE THREAD

**Issue by vvolkova** [cbeust/testng#949]
We have 2 classes: 
1. Parent class ClassA has methodA and methodB, methodA depends on methodB with alwaysRun = true. 
2. Child class: ClassB extends ClassA and overrides methodB.

When we run ClassB tests they do not run with the message:

> Method "ClassA.methodA()[pri:0, instance:ClassB@64cf5b3]" depends on nonexistent method "ClassA.methodB"

**Note:** this case was working in testng 4.6

**Comment by juherr** [comment]
I'm not sure to understand: Is it working with `alwaysRun = false`?

**Comment by vvolkova** [comment]
With alwaysRun = false it doesn't work as well but with different exception, and didn't work in testng 6.4

**Comment by idoromm** [comment]
I would like to report almost the opposite issue: http://stackoverflow.com/questions/35723324/weird-behaviour-in-testng-with-dependencies-no-error-raised

Or in short:

If I set: @Test(dependsOnMethods = {"method1, method2"}, alwaysRun = true)
Meaning I forget to separate the methods with " (it should be  {"method1", "method2"} ) then I get **no error** at all (during compilation or runtime), the tests just don't run at all. This is a big problem for me, and had a terrible time debugging it.

Is there anywhere in the code that I can "hook" and take care of such a situation?

**Comment by juherr** [comment]
@idoromm That's another problem. Could you create a new issue?

**Comment by idoromm** [comment]
@juherr yes I will right now. You can delete my comment/question here then. Thanks
