### ISSUE TITLE
Update apidocs to the latest.

### ISSUE THREAD

**Issue by jinahya** [cbeust/testng#954]
I found that [apidocs](http://testng.org/javadoc/) have not updated.
e.g.
[Assert](http://testng.org/javadoc/org/testng/Assert.html) don't have `expectThrows` or `assertThrows`.

**Comment by juherr** [comment]
Agree with you but prefer http://www.javadoc.io/doc/org.testng/testng/

**Comment by juherr** [comment]
Related #715

**Comment by krmahadevan** [comment]
This is resolved I believe.
