### ISSUE TITLE
Issue with order of the methods in TestNG while using DataProvider and priority

### ISSUE THREAD

**Issue by sayani-sg** [cbeust/testng#964]
Hi.. when I am using DataProvider and the priority under same annotation, the order is not proper for the methods I am calling. Need help. 

![capture](https://cloud.githubusercontent.com/assets/16641915/12507076/5335c4c8-c119-11e5-8f88-b148da3815b4.PNG)

**Comment by sayani-sg** [comment]
I want all the methods for TC01 to get invoked 1st, after that the methods for TC02 should get invoked.

**Comment by juherr** [comment]
TestNG is not supposed to work like you expect.

You have to use a [factory](http://testng.org/doc/documentation-main.html#factories) instead:

```java
public class WithPriorityAndDataProviderSample {
    private String tc;

    @Factory(dataProvider = "dp")
    public WithPriorityAndDataProviderSample(String tc) {
        this.tc = tc;
    }

    @DataProvider
    public Object[][] dp() {
        return new Object[][]{{"TC01"}, {"TC02"}};
    }

    @Test(priority = 1)
    public void test1() {}

    @Test(priority = 2)
    public void test2() {}
}
```

Then run it with the [group-by-instances](http://testng.org/doc/documentation-main.html#dependent-methods) option.

**Comment by sayani-sg** [comment]
Thanks for the solution. But using Factory and Dataprovider the order of calling the methods for tc="TC01" and "TC02" is not correct. And it is not consistent as well. Need help.

**Comment by sayani-sg** [comment]
![capture](https://cloud.githubusercontent.com/assets/16641915/12537008/b9c6ad70-c2da-11e5-9d75-586bc5c1ae47.PNG)

**Comment by juherr** [comment]
Please, provide us code we can run, not screehshot. And I need a clear output of what you expect. Thank

**Comment by sayani-sg** [comment]
public class POC_Registration {

	private String uid="";
	private String pwd="";
	POC_ExcelDataSet ed=new  POC_ExcelDataSet();
	private String tc;

    @Factory(dataProvider = "Testcase")
    public POC_Registration(String tc) {
        this.tc = tc;
        //System.out.println(tc);
    }

	@DataProvider
	public Object[][] Testcase(){
		return new Object[][] {{"TC01"},{"TC02"},{"TC03"}};
	}
	
	@Test(priority=1)
    public void Regis_Uid() throws Exception {
  	 try{  		 
  		 	Thread.sleep(2000);	
  		 	System.out.println("UserID Method For "+ tc);
          	ResultSet rs_getRegistrationData=ed.getExcelData_Registration(tc);          	
          	while (rs_getRegistrationData.next()) 
       	 	{
       	 		uid=rs_getRegistrationData.getString("UserID");
       	 	}         	
          	System.out.println("User ID is: "+ uid);
		}catch (Exception e){
	            throw e;
	        }
      }  

	@Test(priority=2)
    public void Regis_Pwd() throws Exception {
  	 try{ 		 
  		 	Thread.sleep(2000); 
  		 	System.out.println("Pwd Method For "+ tc);
          	ResultSet rs_getRegistrationData=ed.getExcelData_Registration(tc);         	
          	while (rs_getRegistrationData.next()) 
       	 	{
       	 		pwd=rs_getRegistrationData.getString("Password");
       	 	}         	
          	System.out.println("Password is: "+ pwd);
		}catch (Exception e){
	            throw e;
	        }
      }  	  
}

**Comment by sayani-sg** [comment]
when I run this code, the Regis_Uid and Regis_Pwd methods are getting called sequentially for each TC.. But I want this code to run for TC01, TC02 and TC03 one after another.. But they are getting called in random order.. e.g. TC02, TC03 then TC01.. Please help me to resolve this issue.

**Comment by juherr** [comment]
With:

```java
public class POC_Registration {

  private final String tc;

  @Factory(dataProvider = "testcase")
  public POC_Registration(String tc) {
    this.tc = tc;
  }

  @DataProvider
  public Object[][] testcase() {
    return new Object[][]{{"TC01"}, {"TC02"}, {"TC03"}};
  }

  @Test(priority = 1)
  public void regisUid() {
    System.out.println("regisUid For " + tc + " on " + Thread.currentThread().getName());
  }

  @Test(priority = 2)
  public void regisPwd() throws Exception {
    System.out.println("regisPwd For " + tc + " on " + Thread.currentThread().getName());
  }
}
```

and

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="GITHUB-964" verbose="1" >
    <test name="Factory &amp; Priority" group-by-instances="true">
        <classes>
            <class name="POC_Registration" />
        </classes>
    </test>
</suite>
```

the output is _sometimes_:

```
regisUid For TC02 on main
regisPwd For TC02 on main
regisUid For TC01 on main
regisPwd For TC01 on main
regisUid For TC03 on main
regisPwd For TC03 on main
```

If I understand you well, you'd like everytime?

```
regisUid For TC01 on main
regisPwd For TC01 on main
regisUid For TC02 on main
regisPwd For TC02 on main
regisUid For TC03 on main
regisPwd For TC03 on main
```

I'm agree, it should work. But, why do you want a specific order between test cases?

A bad workarround could be:

```java
 public class POC_Registration {

  private final String tc;

  @Parameters(value = "tc")
  public POC_Registration(String tc) {
    this.tc = tc;
  }

  @Test(priority = 1)
  public void regisUid() {
    System.out.println("regisUid For " + tc + " on " + Thread.currentThread().getName());
  }

  @Test(priority = 2)
  public void regisPwd() throws Exception {
    System.out.println("regisPwd For " + tc + " on " + Thread.currentThread().getName());
  }
}
```

and

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="GITHUB-964" verbose="1" >
    <test name="TC1">
        <parameter name="tc" value="TC01" />
        <classes>
            <class name="POC_Registration" />
        </classes>
    </test>
    <test name="TC2">
        <parameter name="tc" value="TC02" />
        <classes>
            <class name="POC_Registration" />
        </classes>
    </test>
    <test name="TC3">
        <parameter name="tc" value="TC03" />
        <classes>
            <class name="POC_Registration" />
        </classes>
    </test>
</suite>
```

**Comment by sayani-sg** [comment]
Thank you. But I think it would be better if the tcs are called randomly. As the size of testng will be increasing with the increasing number of tcs. To avoid that I have used Factory and Dataprovider.

**Comment by juherr** [comment]
@cbeust `@Factory` with `@DataProvider` seems to be run randomly. Is it the expected behavior?
What do you think if calls are only random when `preserve-order="false"`?

**Comment by cbeust** [comment]
It's not unsurprising behavior :)

The factories does instantiate the tests in a specific order but then, TestNG's ordering algorithms kick in and in that light, TestNG only sees methogs (`TC01#method1`, `TC02#method1`, etc...) so they will be run randomly unless dependencies are specified.

But it's not possible to define dependencies on a similar method belonging to a different instance (i.e. you can't say "Run TC01#foo before TC02#foo`.
