### ISSUE TITLE
Dependsonmethod setting ignored, methods executed out of order and ignoring failures

### ISSUE THREAD

**Issue by DaveBrad** [cbeust/testng#97]
On Eclipse 3.7 using testNG 6.2 problems order and failure aborts when running a suite xml of test classes that have test methods that are sequencial in order by use of dependsonmethod in the test class code. 

problem: The execution order reported on completion is not in the dependsonmethod order as expected. Additionally, some test class result report 2 or more fails for a test class. However, the test classes in question should abort out on the first fail due to the dependsonmethod arrangement.

Did a comparison with 6.1.1, where things were okay. 

With 6.2 test methods appear in the reports as out of order and in some cases test class reports multiple failures when all test methods are dependent on each other in a serial sequence.

Using a .xml suite file to run the test classes in order.

Unable to create a simple example for testing purposes. On a small example things appear okay. On ~900 test methods in 72 test classes have the issue.

Basicially: 

TestClass1

testmethod1  -  tests okay
testmethod2 (dependson testmethod1) -   test fails
testmethod3  (dependson testmethod2) - should skip

Results in the eclipse tab show

testmethod1 pass
testmethod2 fails
testmethod3 fails ????? As if the dependency is ignored

In some cases  bad order results have been observed as

testmethod pass
testmehtod3 fail
testmethod2 pass

Observations:

Had some test method names the same in different test classes. Making the method names unique names relieved the bad order ?.  But aborts of the test case if all methods are sequencial depends-on was not happening

 Appears as if in a suite run the test methods are mangled in some sort algorithm as if ignoring the dependsonmethod setting.

When run in 6.1.1, things work great and as expected.

sorry don't have any other information. Its as if dependsonmethods is being ignored for some test methods and not others.

**Comment by krmahadevan** [comment]
This is a very old issue and there's no sample that can be used to reproduce this problem. Closing this issue. If this issue is still existing in the latest released version of TestNG (as of today its `7.4.0`), please comment with a sample to use
