### ISSUE TITLE
Document How To Restrict @Listeners Scope

### ISSUE THREAD

**Issue by opticyclic** [cbeust/testng#972]
The [docs](http://testng.org/doc/documentation-main.html#listeners-testng-xml) say

> Note that the @Listeners annotation will apply to your entire suite file, just as if you had specified it in a testng.xml file. If you want to restrict its scope (for example, only running on the current class), the code in your listener could first check the test method that's about to run and decide what to do then. 

Can you put some example code of doing this in the docs so that I can copy and paste it :+1:

**Comment by krmahadevan** [comment]
@opticyclic 

Take a look here : https://github.com/cbeust/testng/issues/973#issuecomment-182685020
I just now added a sample that shows you how to do this on your own.

**Comment by krmahadevan** [comment]
@juherr 

I have raised a PR for addressing this https://github.com/testng-team/testng-team.github.io/pull/1

**Comment by juherr** [comment]
:+1:
