### ISSUE TITLE
Add An Annotation For Restricted @Listeners

### ISSUE THREAD

**Issue by opticyclic** [cbeust/testng#973]
The [docs](http://testng.org/doc/documentation-main.html#listeners-testng-xml) say

> Note that the @Listeners annotation will apply to your entire suite file, just as if you had specified it in a testng.xml file. If you want to restrict its scope (for example, only running on the current class), the code in your listener could first check the test method that's about to run and decide what to do then. 

Can you add a new annotation that is specifically for just the classes it is annotated on please.

It is a bit unexpected (if you haven't read the docs!) to annotate a single class then see it applied to the whole suite.

**Comment by krmahadevan** [comment]
@opticyclic 

You can do this today on your own without having TestNG to introduce any new changes into it.

Here's a sample that shows how to do it.

First define a marker annotation that helps us to identify such cases.

```
@Retention(RetentionPolicy.RUNTIME)
@Target ({ElementType.TYPE})
public @interface DisableListener {
}
```

Now within your listeners you can a similar logic as shown below
```
public static class LocalListener implements IInvokedMethodListener {

    public void beforeInvocation(IInvokedMethod iInvokedMethod, ITestResult iTestResult) {
        ConstructorOrMethod consOrMethod =
            iInvokedMethod.getTestMethod().getConstructorOrMethod();
        DisableListener disable = consOrMethod.getMethod().getDeclaringClass().getAnnotation(DisableListener.class);
        if (disable != null) {
            return;
        }
        System.err.println("beforeInvocation() was invoked on " + iInvokedMethod.getTestMethod()
            .getConstructorOrMethod().getDeclaringClass().getCanonicalName());
    }

    public void afterInvocation(IInvokedMethod iInvokedMethod, ITestResult iTestResult) {

    }
}

```

And finally when you would like a listener to be disabled for a particular class, you just add your new marker annotation on the class as below
```
@DisableListener
@Listeners (LocalListener.class)
public class ThisClassNeedsListener {
    @Test
    public void foo() {
        System.err.println("Hello world");
    }
}
```

**Comment by krmahadevan** [comment]
@juherr 
If you are satisfied with the explanation, then maybe you can close this issue.

**Comment by juherr** [comment]
@kamilszymanski 
Your solution looks similar to #861

As I understand the issue, @opticyclic want to register listeners for a specific class and not for the all suite context.

**Comment by krmahadevan** [comment]
@juherr 
I think you called out the wrong person in your comment.

Also if you look at the example I provided, it can be done outside of TestNG without TestNG undergoing any changes at all.

**Comment by juherr** [comment]
Link corrected, and I'm agree with you. I didn't catch all the details.

**Comment by opticyclic** [comment]
Hmm, I'm not sure about this.
My initial use case is that I want a listener to take a screenshot on failed Selenium tests (5 out of 200 in the project), however, as mentioned, the listener applies to all 200 tests.

It seems like your solution would require me to annotate 195 tests with the disable annotation.

I'm really looking for the inverse. I only want a listener to apply to classes that I have annotated them with.

**Comment by krmahadevan** [comment]
@opticyclic 
The logic would still work. Just invert what I have called out as approach by doing the following
* Annotate only those classes that need the screenshot.
* Build a separate listener which is explicitly intended for screenshots.
* Have the listener check if the marker annotation (defined in step (1)) exists and have it proceed with taking screenshots only if it is present.
