### ISSUE TITLE
Parameter with BeforeTest is not reading more than one class test

### ISSUE THREAD

**Issue by Vishnu1067** [cbeust/testng#974]
Hello All,

I have two test case classes,
      Test1.java

```
                 @Test
	         public void runTestCase(){
		    System.out.println("Test is running 1 "); 
                  }
```

   Test2.java

              @Test
	       public void runTestCase(){
		  System.out.println("Test is running 2 ");
	      }

I have one base class where the parameters are defined with @BeforeTest(). 
    BaseClass.java

  ```
import org.testng.annotations.AfterClass;`
   import org.testng.annotations.BeforeClass;
   import org.testng.annotations.BeforeTest;
   import org.testng.annotations.Parameters;

 public class BasicClass  {
  private String browserName;
        @Parameters({"Browser"})
	@BeforeTest()
	public void getBrowserNameFromTestNG(String browserName){	
		this.browserName = browserName;
	}
	
	
	@BeforeClass
	public void setUp(){
		
		String browser = browserName;
		
		if(browser.equals("Chrome")){
			System.out.println("Chrome Launched Successfully");
		}else if(browser.equals("Firefox")){
			System.out.println("Firefox Launched Successfully");
		}else{
			System.out.println("IE Launched Successfully");
		}
		
	}
	
	@AfterClass
	public void tearDown(){
		System.out.println("Closing Browser");
	}
```

testng.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Testing Parameterization" parallel="false" thread-count="3">
<test  verbose="1" name="Test_Chrome">
     <parameter name="Browser" value="Chrome"/>
     <classes>
            <class name="Test1.java" />
            <class name="Test2.java" />
    </classes>
 </test>

<test  verbose="1" name="Test_Firefox"> 
     <parameter name="Browser" value="Chrome"/>
     <classes>
            <class name="Test1.java" />
            <class name="Test2.java" />
    </classes>
 </test>

</suite>
```

Objective: Need to run two test cases (which is available in one package) with different browsers. Base class will call browser one time and set it for running accordingly.

Issue: When i run testng.xml, it is taking only the first class Test1.java and for Test2.java is showing configuration issue as Null Point Exception.

**Comment by krmahadevan** [comment]
@Vishnu1067 
I can't recreate the problem.

Here's the base class

```
public class TestBaseClass {
    private String browserName;

    @Parameters ({"browser"})
    @BeforeTest
    public void getBrowserNameFromTestNG(String browserName) {
        this.browserName = browserName;
    }

    @BeforeClass
    public void setUp() {

        String browser = browserName;

        if (browser.equals("Chrome")) {
            System.out.println("Chrome Launched Successfully");
        } else if (browser.equals("Firefox")) {
            System.out.println("Firefox Launched Successfully");
        } else {
            System.out.println("IE Launched Successfully");
        }
    }

    @AfterClass
    public void tearDown() {
        System.out.println("Closing Browser");
    }
}
```

Here are the test classes
```
public class SimpleTest1 extends TestBaseClass {
    @Test
    public void runTestCase() {
        System.out.println("Test is running 1 ");
    }
}

public class SimpleTest2 {
    @Test
    public void runTestCase(){
        System.out.println("Test is running 2 ");
    }
}

```

Here's the suite file
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="SuiteEndToEnd" parallel="false" verbose="10" thread-count="2">
    <test name="Test_Chrome" verbose="2">
        <parameter name="browser" value="Chrome"/>
        <classes>
            <class name="rationale.emotions.testng.SimpleTest1"/>
            <class name="rationale.emotions.testng.SimpleTest2"/>
        </classes>
    </test>
    <test name="Test_Firefox" verbose="2">
        <parameter name="browser" value="Firefox"/>
        <classes>
            <class name="rationale.emotions.testng.SimpleTest1"/>
            <class name="rationale.emotions.testng.SimpleTest2"/>
        </classes>
    </test>
</suite> 
```

Here's the output
```
...
... TestNG 6.9.10 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
  /Users/krmahadevan/IdeaProjects/necropolis/src/test/resources/example.xml
Chrome Launched Successfully
Test is running 1 
Closing Browser
Test is running 2 
PASSED: runTestCase
PASSED: runTestCase

===============================================
    Test_Chrome
    Tests run: 2, Failures: 0, Skips: 0
===============================================
Firefox Launched Successfully
Test is running 1 
Closing Browser
Test is running 2 
PASSED: runTestCase
PASSED: runTestCase

===============================================
    Test_Firefox
    Tests run: 2, Failures: 0, Skips: 0
===============================================

===============================================
SuiteEndToEnd
Total tests run: 4, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 51 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@775c77fb: 11 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@4f1a20af: 5 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@28e1fbe3: 10 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@52ee4084: 13 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@46e48d4: 36 ms

Process finished with exit code 0

```

**Comment by Vishnu1067** [comment]
Hi,

Test case 2 (SimpleTest2) class is not extends with Base class. Could you please extend with Base Class?

**Comment by krmahadevan** [comment]
@Vishnu1067 
Thanks. I was able to recreate the problem. But I don't think its a problem with TestNG here.
```@BeforeTest``` methods are expected to run just once per ```<test>``` tag.

So it gets executed for the first class, but for the second class its not getting executed, because it was already executed once. You will have to change your approach to get past this problem.

**Comment by Vishnu1067** [comment]
I can use Base class with @Test method. But the problem is It will launch browser each and every test case class within the <test></test> tag. It consume execution time a lot. I would expect to launch browser for one time within <test></test> and finish it one time. This is the work around in worst case.

**Comment by juherr** [comment]
As @krmahadevan said it is the expected behavior of `@BeforeTest`.

**Comment by Vishnu1067** [comment]
@juherr  How about the case something like this...

I can use Base class with @Test method. But the problem is, It will launch browser each and every test case. It consume execution time a lot. I would expect to launch browser for one time within test and finish it one time.

**Comment by juherr** [comment]
You can use `static` x]

But I'm agree with you and it is a known limitation.

Maybe @cbeust will have a better answer.

**Comment by krmahadevan** [comment]
@Vishnu1067 
I am not sure i understand your use case.
You are saying that you want a browser to be spawned only once per ```<test>``` tag. So it literally means that all your ```@Test``` annotated test methods are going to be ending up using the same browser instance.

Do you realise that this means that you can ONLY run your tests in sequence ? Wouldn't that cause a longer run time per test ? I am pretty sure that the time lost in spawning a browser per ```@Test``` method is a lot more less when compared to your current model.

I am re-iterating again. This is NOT a limitation with TestNG, but I feel that this is a limitation in how you have designed your tests.

**Comment by juherr** [comment]
@krmahadevan What I understand, he want share some objects, initialized once by `<test>` (but maybe `<suite>` too) between 2 test classes.
Using a common `BaseClass` is not the solution as `@BeforeTest/Suite` methods are only called once for all instances.

**Comment by krmahadevan** [comment]
@juherr 
Maybe then he can refer to this blog post of mine and see if he can customize it to his needs

https://rationaleemotions.wordpress.com/2014/02/13/sharing-data-across-tests-in-different-testclasses/

**Comment by juherr** [comment]
Oh true! :+1: I forgot it! Thank!

**Comment by Vishnu1067** [comment]
Hi,

Thanks for sharing the link and it is not my scenario. I want parameterization 

my scenario would be like this,

Lets say Application model;

Module A - 5 screens (Quote, Booking, File, etc)
Module B - 3 Pages 

Eclipse structure

Creating Test Packages
Package 1 - modulea - 5 class - each class have minimum 20 test cases
Package 2 - moduleb - 3 class - each class have minimum 20 test cases

`<test package 1 with firefox>
<parameter>
<class1>
<class2>
<class3>
<class4>
<class5>
</test>`

`<test package 1 with IE>
<parameter>
<class1>
<class2>
<class3>
<class4>
<class5>
</test>`

`<test package 2 with firefox>
<parameter>
<class1>
<class2>
<class3>
</test>`


`<test package 2 with IE>
<parameter>
<class1>
<class2>
<class3>
</test>`

now i want to execute all the cases in chrome, Firefox and IE in parallel. All test cases in one class should execute in same browser (not launch browser on each test case).

This is my scenario. Anyway i've made work around my framework until new feature comes up.

Once again thanks for reply.

Regards,
Vishnu.

**Comment by Nisha-Vekariya** [comment]
@Vishnu1067 I am having the same issue using the same structure as you used. Please let me know if you get any workaround for the same.
