### ISSUE TITLE
How to get the Selected value in a Spinner in Appium?

### ISSUE THREAD

**Issue by sayani-sg** [cbeust/testng#979]
if the Spinner is identified by Xpath, how to get the Selected value in Appium?

I have tried using the below code, but getting content-desc of the spinner which is not equal to what it is showing in the Spinner.

date= driver.findElement(By.xpath((String)hm_xpaths_interaction.get("Date"))).getAttribute("name");

**Comment by juherr** [comment]
Not a testng issue.

You can ask your question here:
http://appium.io/get-involved.html
http://stackoverflow.com/search?q=appium
