### ISSUE TITLE
TestNG run inherited method twice

### ISSUE THREAD

**Issue by wutingbupt** [cbeust/testng#980]
Hi,

TestNG will run the inherited method twice in this case:

Image we have two classes
For parent, we have method a and b
For child, we have method c and d.

```
<test name="RstTest">
    <classes>
        <class name="Parent">
            <methods>
                <include name="a" />
                <include name="b" />
            </methods>
        </class>
        <class name="Child">
            <methods>
                <include name="c" />
                <include name="d" />
            </methods>
        </class>
```

Instead of running a, b, c and d

TestNG will run a b b a c d

After checking the code, I found this special case confused the testng init,
TestNG will use a map m_includedMethods in XmlMethodSelector to save the relationship between class full name and the includes methods, when it parse to Child, firstly, it will load all of methods (Even includes the method from parent class), then compare if the method is included or not, due to method a and b will use the same full class name as the one in parent class (During this time, method a and b have been injected into that map), so that's why it run more than once.

Thanks very much.

Br,
Tim

**Comment by juherr** [comment]
@wutingbupt I think your analyse is good. Maybe you can propose a test case that shows the issue, and a fix?

**Comment by juherr** [comment]
Maybe related to #949 

See my comments on https://github.com/cbeust/testng/pull/950#issuecomment-179829948

**Comment by wutingbupt** [comment]
I will try if I can fix it.
2016年2月9日 下午5:32，"Julien Herr" <notifications@github.com>写道：

**Comment by juherr** [comment]
The test case is a good start ;)
