### ISSUE TITLE
Distributed Test Ng Testing

### ISSUE THREAD

**Issue by kumartheashwani** [cbeust/testng#981]
Hi Team,

I see in version 4.7 Venice introduced Distributed testing capabilities. Does testNg support this feature now as well.

Thanks,
Ashwani

**Comment by cbeust** [comment]
No, I never really had the time to fully develop it.

**Comment by juherr** [comment]
Distributed classes will be removed in the next release (#953) because it didn't work as expected. 

But classes are also available via https://github.com/testng-team/testng-distributed
