### ISSUE TITLE
Assert.assertNotEquals(boolean, boolean) et al. should be public

### ISSUE THREAD

**Issue by PerMildner** [cbeust/testng#986]
Several of the `assertNotEquals()`-variants exists, but are not public. This is unlike their `assertEquals()` counterparts which are public.

`assertEquals("foo", true)` resolves to `assertEquals(boolean,boolean)` and will therefore give a warning about inconvertible types in my IDE (which is good).
`assertNotEquals("foo", true)` resolves to `assertNotEquals(Object, Object)` and will not give a warning in my IDE (which I think is bad).

I do not know whether this is intentional (there are no JavaDoc for the `assertNotEquals()` methods, not even the public ones). I expected `assertNotEquals()` to be just like `assertEquals()` except for the desired comparison-result.

**Comment by juherr** [comment]
You are true, `assertEquals` and `assertNotEquals` should be symetric.

Feel free to propose a pull request which fixes the issue :)

**Comment by juherr** [comment]
Close by #988
