### ISSUE TITLE
Invoker throws NullPointerExceptions after a configuration method fails in a test's super class when configfailurepolicy="continue"

### ISSUE THREAD

**Issue by willsy9919** [cbeust/testng#990]
Here is a simple test that extends a test base class:

``` java
public abstract class TestBase {

    @BeforeTest
    protected void setup() {
        System.out.println("Starting test");
        throw new RuntimeException("Fail the test.");
    }

    @Test
    protected abstract void execute();

    @AfterTest(alwaysRun = true)
    protected void cleanup() {
        System.out.println("This should always run");
    }
}

public class MyTest extends TestBase {

    @Override
    @Test
    protected void execute() {
        System.out.println("Test");
    }

}
```

I run MyTest with configfailurepolicy set to "continue". Setup() fails as expected, but cleanup() doesn't run despite alwaysRun=true.

This is whats happening:
1. Setup() fails, causing Invoker.setClassInvocationFailure() to be called. When setClassInvocationFailure() is called, the TestBase class is used as the key for m_classInvocationResults.
2. When Invoker.confInvocationPassed() is called for execute() and cleanup(), m_classInvocationResults.get() is called each time (line 426). The get() is called using MyTest as the key, but TestBase was the only key added to the map.
3. Null is returned, causing the contains() call to throw a NullPointerException.
4. The exception is caught at line 672, and the method invocation fails.

**Comment by jabaraht** [comment]
@juherr is there anny update on this issue? This continues to affect our testing, and ability to qualify S/W releases.

**Comment by juherr** [comment]
Nope, sorry. I've no free time for the moment, and I'm just doing issue triage et review.

Feel free to propose a test case that shows the issue, and why not, the fix for it :)
