### ISSUE TITLE
Unable to install TestNG plugin in eclipse

### ISSUE THREAD

**Issue by Janani** [cbeust/testng#994]
http://beust.com/eclipse/ -- This page is not available and I am not able to perform a 'Install New Software' or find it in Eclipse Marketplace. Can you please suggest me any other way to get it installed in eclipse?

**Comment by cbeust** [comment]
What error are you seeing? It's not a web page, it's an Eclipse update site, so you can't view this page in your browser.

If Eclipse can't see the update site, are you using a proxy?

**Comment by Janani** [comment]
Thank you for your quick response !! 

When I try to install from Eclipse Marketplace, it is giving me the below error,
"Unknown Host : http://beust.com/eclipse/content.xml. I am trying to install in my remote machine

**Comment by missedone** [comment]
it sounds like your network issue for sure.
could you run the following curl command on your remote machine, see if it gets back the similar 301 response:

```
curl -v http://beust.com/eclipse
*   Trying 205.186.183.235...
* Connected to beust.com (205.186.183.235) port 80 (#0)
> GET /eclipse HTTP/1.1
> Host: beust.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 29 Feb 2016 13:41:20 GMT
< Server: Apache/2.2.22
< Location: http://beust.com/eclipse/
< Vary: Accept-Encoding
< Content-Length: 299
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://beust.com/eclipse/">here</a>.</p>
<hr>
<address>Apache/2.2.22 Server at beust.com Port 80</address>
</body></html>
* Connection #0 to host beust.com left intact
```

**Comment by Janani** [comment]
I tried to invoke this curl command from cmd prompt of my remote machine.. getting the below response
![image](https://cloud.githubusercontent.com/assets/17467216/13426524/eccf3a28-dfd3-11e5-8703-5452b9499565.png)

**Comment by missedone** [comment]
ok, could you curl any other internet pages, like www.google.com?
could you check if you correctly set nameserver (dns) and/or http proxy at system level.

**Comment by Janani** [comment]
When tried to execute curl command for google.com, I get the below response
![image](https://cloud.githubusercontent.com/assets/17467216/13469540/d7eb2f86-e0cd-11e5-9a9d-672449e6baf8.png)

**Comment by Janani** [comment]
I am not connecting through proxy also.

**Comment by FibreFoX** [comment]
Could you try to make a normal PING to that address? Maybe some firewall blocking that traffic?

**Comment by cbeust** [comment]
Something wrong with your DNS apparently. Can you try the IP address?

Non-authoritative answer:
Name:    beust.com
Address: 205.186.183.235

​

-- 
Cédric

**Comment by juherr** [comment]
Should be resolved now. At least open a new issue on https://github.com/cbeust/testng-eclipse

**Comment by LearnByBhanuPratap** [comment]
```
To resolve this issue.

GO to Eclipse installed folder
Edit eclipse.ini file and insert
-Djava.net.preferIPv4Stack=true
at the end of that file. Restart the eclipse.
```

**Comment by priyagautam-qait** [comment]
> ```
> To resolve this issue.
> 
> GO to Eclipse installed folder
> Edit eclipse.ini file and insert
> -Djava.net.preferIPv4Stack=true
> at the end of that file. Restart the eclipse.
> ```

Didn't work for me

**Comment by HanishS** [comment]
i cant download the eclipse plugin from marketplace after yesterday's commit
getting the following error
Unable to read repository at http://beust.com/eclipse.
Unable to read repository at http://beust.com/eclipse/6.9.13.
Unable to read repository at http://beust.com/eclipse/updatesites/6.9.13.201609291640/content.jar.
Read timed out

**Comment by hayro3122** [comment]
https://beust.com/eclipse when i hit enter i got this error:
Unable to read repository at https://beust.com/eclipse/content.xml.
Unable to read repository at https://beust.com/eclipse/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Rushrpa** [comment]
I could able to resolve above issue and install TestNG with the following modification in the eclipse.ini file

GO to Eclipse installed folder
Edit eclipse.ini file and insert
-Djava.net.preferIPv4Stack=true
at the end of that file. Restart the eclipse.

Many Thanks.

**Comment by barryku** [comment]
I ran into the same error @hayro3122 got.  What worked for me is installing the certificate into my local cacerts in jre/lib/security/cacerts by following the instructions at https://confluence.atlassian.com/kb/how-to-import-a-public-ssl-certificate-into-a-jvm-867025849.html#HowtoimportapublicSSLcertificateintoaJVM-commandline  

Download the public cert first, then import to my local cacerts.  Restart Eclipse, and it will now read the web page properly.

**Comment by Puja-Ojas** [comment]
@Rushrpa  thank you very much. I could able to resolve above issue by making updating sts.ini file

**Comment by jmeterexperts1** [comment]
Hey 

I have tried above option : 
GO to Eclipse installed folder
Edit eclipse.ini file and insert
-Djava.net.preferIPv4Stack=true
at the end of that file. Restart the eclipse.
issue while installing TestNG : HTTP Remote File Permanently Removed: http://beust.com/eclipse/content.xml HTTP Remote File Permanently Removed: http://beust.com/eclipse/content.xml HttpComponents connection error response code 410. ::: Eclipse version : clipse IDE for Java Developers Version: 2020-03 (4.15.0) Build id: 20200313-1211 (c) Copyright Eclipse contributors and others 2000, 2020. All rights reserved. Eclipse and the Eclipse logo are

**Comment by missedone** [comment]
@jmeterexperts1 , you need to install from update site: https://dl.bintray.com/testng-team/testng-eclipse-release

the old http://beust.com/eclipse/ gets retired.

**Comment by PalakArora23** [comment]
Thank you @missedone . It's working

**Comment by vicky1602** [comment]
Thank you missedone, Its working now

**Comment by raghumankali** [comment]
> @jmeterexperts1 , you need to install from update site: https://dl.bintray.com/testng-team/testng-eclipse-release
> 
> the old http://beust.com/eclipse/ gets retired.

This worked for me. If you are downloading the latest version eclipse, then it already has -Djava.net.preferIPv4Stack=true included in it

**Comment by juherr** [comment]
There is an ongoing discussion on the group: https://groups.google.com/g/testng-users/c/f6I6lmfHkmc

**Comment by sumitgarg1015** [comment]
Thanks Juherr, appreciate your help on this! Finally got new link of TestNG: https://testng.org/testng-eclipse-update-site

**Comment by missedone** [comment]
hi guys, because bintray.com sunset on May 1, so we have moved the update-site to github, 
* new update site url: https://testng.org/testng-eclipse-update-site
* the source is at https://github.com/testng-team/testng-eclipse-update-site

we will update the url on eclipse marketplace soon.

see more details: https://github.com/cbeust/testng-eclipse/issues/511#issuecomment-827179825

**Comment by jeffry01** [comment]
> 
> 
> Thanks Juherr, appreciate your help on this! Finally got new link of TestNG: https://testng.org/testng-eclipse-update-site

Thanks juherr for the updated link. Works fine for me now

**Comment by NaukhezZaman** [comment]
Hi,

Can you please help me in installing TestNG. I have all above mentioned sites but still getting "Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

Is there any updated site of TestNG?

**Comment by arun2190** [comment]
Unable to install TestNG on eclipse 4.23 getting the following error while trying to install from the eclipse marketplace. 

Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
Certificate for <testng.org> doesn't match any of the subject alternative names: [*.github.com, www.github.com, github.io, github.com, *.github.io, githubusercontent.com, *.githubusercontent.com]

Can anyone please suggest if there's any workaround solution. 

Thanks

**Comment by krmahadevan** [comment]
@arun2190 - For TestNG eclipse issues, please file issues on https://github.com/cbeust/testng-eclipse
