### ISSUE TITLE
java.lang.UnsupportedClassVersionError: org/testng/remote/RemoteTestNG : unsupported classversion 51.0

### ISSUE THREAD

**Issue by mrswadge** [cbeust/testng#995]
Hi,

I'm running TestNG 6.8.22.201505070404 embedded in Eclipse. I have an issue because we are currently stuck on using Java 1.6, but TestNG is requesting 1.7. I'm now trying to work out what was the last revision of TestNG that supported Java 1.6.

This issue isn't so much a code change, but more of a documentation request. It would make life **much easier** to have this documented and clearly marked in the documentation/download pages of http://testng.org/.

Thanks,
Stuart

**Comment by mrswadge** [comment]
It would also be helpful if these versions were made available to download or via an update site too.

**Comment by mrswadge** [comment]
Sorry, I probably should have posted this in the eclipse plugin project. However, I thought about it and it wasn't such a big deal to fix. I am now running the tests in eclipse with a 1.7 JDK. Not sure why I didn't think about it earlier. I don't suppose there is a way the eclipse plugin can ensure it is run with JDK 1.7+ instead of the project default (in my case 1.6). It's a known that it will fail with 1.6, so it shouldn't even bother trying.

**Comment by missedone** [comment]
so did you help yourself, or is there still any issue we can help?

**Comment by mrswadge** [comment]
I think the documentation issue still remains and perhaps if it is possible to ensure that a 1.7+ JDK is used when running in Eclipse.

**Comment by missedone** [comment]
ok,.will update the plugin docs for sure.
you can update to recent version 6.9.10 of testng plugin which enforces the jdk running testng process is 1.7+

**Comment by missedone** [comment]
@juherr 
this can be closed.
the site doc was updated, and the plugin has JRE version detect that make sure a JRE version >= 1.7 is required.
